### PR TITLE
3379 [Restart iiab-clone-wifi if ap0 device (for AP+STA mode) not detected by Ansible]

### PR DESCRIPTION
**Pull request by jvonau**
…#3379

### Fixes bug:
noted in

### CODE REVIEW

**Comment by jvonau** [comment]
https://github.com/iiab/iiab/commit/6b69696f7246b0acba21eae5e836e810e9bc7fbc provides clarity that only AP supported devices should be cloned, could become part of this PR so the other PR could just deal with that fix and enhancement to the template.

**Comment by holta** [comment]
> [6b69696](https://github.com/iiab/iiab/commit/6b69696f7246b0acba21eae5e836e810e9bc7fbc) provides clarity that only AP supported devices should be cloned, could become part of this PR so the other PR could just deal with that fix and enhancement to the template.

1) Either way, great progress!  How should these 2 PR's likely be sequenced?

   - PR #3389
   - PR #3390

2) What smoke/functional tests are most needed?

**Comment by jvonau** [comment]
Well the users that filed the issue/have reproducers would be in the best position to assess the changes.

**Comment by holta** [comment]
Where is variable `ansible_ap0` defined?

(What is this variable type, e.g. boolean &mdash; or is it a string of some sort, containing what?)

**Comment by jvonau** [comment]
Part of vars that are available from within ansible natively, `ansible -m setup` is captured to both iiab-install.log and iiab-network.log for reference.

**Comment by holta** [comment]
> Part of vars that are available from within ansible natively, `ansible -m setup` is captured to both iiab-install.log and iiab-network.log for reference.

Is this documented anywhere?

Or if this is an undocumented Ansible feature, is there an example you can paste in to explain?

FWIW I'm personally not seeing this `ansible_ap0` anywhere in {iiab-install.log, network.log} or online.  So it's hard to understand what is happening.

**Comment by jvonau** [comment]
https://github.com/iiab/iiab/blob/master/iiab-install#L197
https://github.com/iiab/iiab/blob/master/iiab-network#L44
Downloaded from github looks like from azuracast install #3385  [iiab-network.log](https://github.com/iiab/iiab/files/9701475/iiab-network.log)

**Comment by jvonau** [comment]
Other examples where the builtin vars are used directly:
https://github.com/iiab/iiab/blob/master/roles/0-init/tasks/create_iiab_ini.yml#L27
https://github.com/iiab/iiab/blob/master/roles/0-init/tasks/create_iiab_ini.yml#L29
https://github.com/iiab/iiab/blob/master/roles/0-init/tasks/main.yml#L88
https://github.com/iiab/iiab/blob/master/roles/0-init/tasks/main.yml#L90
https://github.com/iiab/iiab/blob/master/roles/0-init/tasks/main.yml#L92

**Comment by holta** [comment]
> Downloaded from github looks like from azuracast install #3385 [iiab-network.log](https://github.com/iiab/iiab/files/9701475/iiab-network.log)

I guess we're forced to fill in Ansible's rather incomplete documentation:
https://docs.ansible.com/ansible/latest/reference_appendices/faq.html#how-do-i-see-a-list-of-all-of-the-ansible-variables

Line 10 is what matters.
The top 80 lines (of 53018 total lines) from `/opt/iiab/iiab/iiab-network.log` are pasted in here to make everything more clear:

```
2022-09-17 16:51:36,681 p=9083 u=root n=ansible | 127.0.0.1 | SUCCESS => {
    "ansible_facts": {
        "ansible_all_ipv4_addresses": [
            "10.10.10.10",
            "172.18.0.1",
            "172.19.0.1",
            "172.17.0.1"
        ],
        "ansible_all_ipv6_addresses": [],
        "ansible_ap0": {
            "active": true,
            "device": "ap0",
            "features": {
                "esp_hw_offload": "off [fixed]",
                "esp_tx_csum_hw_offload": "off [fixed]",
                "fcoe_mtu": "off [fixed]",
                "generic_receive_offload": "on",
                "generic_segmentation_offload": "on",
                "highdma": "on",
                "hsr_dup_offload": "off [fixed]",
                "hsr_fwd_offload": "off [fixed]",
                "hsr_tag_ins_offload": "off [fixed]",
                "hsr_tag_rm_offload": "off [fixed]",
                "hw_tc_offload": "off [fixed]",
                "l2_fwd_offload": "off [fixed]",
                "large_receive_offload": "off [fixed]",
                "loopback": "off [fixed]",
                "macsec_hw_offload": "off [fixed]",
                "netns_local": "on [fixed]",
                "ntuple_filters": "off [fixed]",
                "receive_hashing": "off [fixed]",
                "rx_all": "off [fixed]",
                "rx_checksumming": "on [fixed]",
                "rx_fcs": "off [fixed]",
                "rx_gro_hw": "off [fixed]",
                "rx_gro_list": "off",
                "rx_udp_gro_forwarding": "off",
                "rx_udp_tunnel_port_offload": "off [fixed]",
                "rx_vlan_filter": "off [fixed]",
                "rx_vlan_offload": "off [fixed]",
                "rx_vlan_stag_filter": "off [fixed]",
                "rx_vlan_stag_hw_parse": "off [fixed]",
                "scatter_gather": "on",
                "tcp_segmentation_offload": "on",
                "tls_hw_record": "off [fixed]",
                "tls_hw_rx_offload": "off [fixed]",
                "tls_hw_tx_offload": "off [fixed]",
                "tx_checksum_fcoe_crc": "off [fixed]",
                "tx_checksum_ip_generic": "off [fixed]",
                "tx_checksum_ipv4": "on",
                "tx_checksum_ipv6": "on",
                "tx_checksum_sctp": "off [fixed]",
                "tx_checksumming": "on",
                "tx_esp_segmentation": "off [fixed]",
                "tx_fcoe_segmentation": "off [fixed]",
                "tx_gre_csum_segmentation": "off [fixed]",
                "tx_gre_segmentation": "off [fixed]",
                "tx_gso_list": "off [fixed]",
                "tx_gso_partial": "off [fixed]",
                "tx_gso_robust": "off [fixed]",
                "tx_ipxip4_segmentation": "off [fixed]",
                "tx_ipxip6_segmentation": "off [fixed]",
                "tx_lockless": "off [fixed]",
                "tx_nocache_copy": "off",
                "tx_scatter_gather": "on",
                "tx_scatter_gather_fraglist": "off [fixed]",
                "tx_sctp_segmentation": "off [fixed]",
                "tx_tcp6_segmentation": "on",
                "tx_tcp_ecn_segmentation": "off [fixed]",
                "tx_tcp_mangleid_segmentation": "off",
                "tx_tcp_segmentation": "on",
                "tx_tunnel_remcsum_segmentation": "off [fixed]",
                "tx_udp_segmentation": "off [fixed]",
                "tx_udp_tnl_csum_segmentation": "off [fixed]",
                "tx_udp_tnl_segmentation": "off [fixed]",
                "tx_vlan_offload": "off [fixed]",
                "tx_vlan_stag_hw_insert": "off [fixed]",
                "vlan_challenged": "off [fixed]"
            },
            "hw_timestamp_filters": [],
```

**Comment by holta** [comment]
This PR appears to be optimization(s) more than anything.

Perhaps we can bypass it &mdash; and focus on testing this larger/functional PR (5 files changes) instead?

- PR #3390

**Comment by jvonau** [comment]
This one is for what @tim-moody ran into on the W in #3379

**Comment by holta** [comment]
Superseded by:

- PR #3390 

(Which included this PR #3389's changes.)

**Pull request closed without merging**
