### PR TITLE
WIP: Stop Kolibri during reinstalls, for #1782

### PR DESCRIPTION
**Pull request by holta**
@benjaoming & @arky please review if poss?

Towards fixing #1782 (Kolibri 0.12.5 reinstall failed on Raspbian Desktop on RPi 3 B+)

Is there documentation explaining why `/usr/local/kolibri/bin/kolibri manage migrate` is needed? 
 Unfortunately I do not understand what this is doing and why: https://github.com/holta/iiab/blob/kolibri-stop-during-reinstall/roles/kolibri/tasks/main.yml#L59-L62

### CODE REVIEW

**Comment by holta** [comment]
Kolibri reinstalls (with this new PR #1828) were smoke-tested successfully on these 3 OS's:

- Raspbian Buster Lite on RPi 4
- Debian 10 Buster on x86_64 VM
- Ubuntu 18.04 Desktop on x86_64 PC

Should I merge?  And/or does this PR need further improvement?

**Comment by holta** [comment]
> @benjaoming & @arky please review if poss?
> 
> Towards fixing #1782 (Kolibri 0.12.5 reinstall failed on Raspbian Desktop on RPi 3 B+)
> 
> Is there documentation explaining why `/usr/local/kolibri/bin/kolibri manage migrate` is needed?
> Unfortunately I do not understand what this is doing and why: https://github.com/holta/iiab/blob/kolibri-stop-during-reinstall/roles/kolibri/tasks/main.yml#L59-L62

Thank you @benjaoming & @arky if you can provide comments after I merge this now, in order to broaden testing!

**Comment by benjaoming** [comment]
In light of this issue and the fact that IIAB is shipping its own systemd service, I would recommend that you open an issue to have Kolibri installed through the Debian package instead? Interactive with dpkg, whether as an uninstall, reinstall or fresh install will manage the systemd job, starting, stopping and reloading it when necessary.

**Comment by holta** [comment]
> In light of this issue and the fact that IIAB is shipping its own systemd service, I would recommend that you open an issue to have Kolibri installed through the Debian package instead?

Done, there are questions that need sorting out here for sure: https://github.com/iiab/iiab/issues/1832

**Pull request merged**
