### PR TITLE
Experimenting with various apt package installs [e.g. python3-cryptography, so Calibre-Web unit test works on Raspberry Pi OS]

### PR DESCRIPTION
**Pull request by deldesir**
This PR is for testing different packages to understand what affects Calibre-Web when installed with UNITTEST.

### CODE REVIEW

**Comment by holta** [comment]
Background:

- https://github.com/iiab/calibre-web/issues/260#issuecomment-2386679860

**Comment by holta** [comment]
@EMG70 can you help us test this PR #3815 by **unit testing** Calibre-Web?

In other words:

1. Start with a completely new [64-bit Raspberry Pi OS Lite](https://www.raspberrypi.com/software/operating-systems/#raspberry-pi-os-64-bit) running on almost any Raspberry Pi.
2. Install IIAB with this PR 3815, by running: `curl iiab.io/install.txt | bash -s 3815`
3. Type 0 (ZERO, for local_vars_unittest.yml) when it asks you to "PLEASE PICK (1) 🚵 SMALL (2) 🚢🚣 MEDIUM or (3) 🚂🚃🚃 LARGE (NEEDS 2+ GB RAM)."
4. Use [nano](https://www.nano-editor.org/dist/v2.6/nano.html) to toggle [Lines 393-394](https://github.com/iiab/iiab/blob/27e287e508bf69fce6d500919080acd76775d130/vars/local_vars_unittest.yml#L393-L394) to `True` in [/etc/iiab/local_vars.yml](https://wiki.iiab.io/go/FAQ#What_is_local_vars.yml_and_how_do_I_customize_it?)
5. Also add these 2 lines to `/etc/iiab/local_vars.yml` to speed up the install — and avoid setting up the Raspberry Pi's internal hotspot:
   ```
   network_install: False
   network_enabled: False
   ```
6. Run `sudo iiab` to install IIAB (watch for it completing in about 15 minutes?!)
7. _Test that Calibre-Web is fully working, using URLs like_ http://ACTUAL.IIAB.IP.ADDRESS/books :pray:
8. Please post here on this ticket, the URL that results from running [sudo iiab-diagnostics](https://github.com/iiab/iiab/blob/master/scripts/iiab-diagnostics.README.md), Thanks!

**Comment by EMG70** [comment]
A new VM SIZE 0 (Unittest) was installed on a RPI 400 ,Calibre-web now reachable using IP/books.
SUDO IIAB-DIAGNOSTICS https://paste.centos.org/view/e3849191

Screenshot from 2024-10-02 13-17-56

**Comment by holta** [comment]
1) fyi @deldesir also confirmed that `apt install python3-cryptography` can be run manually (as root) on a bare 64-bit Raspberry Pi OS Lite on RPi 5, to fully simulate this PR, allowing for rapid Calibre-Web unit-testing on RasPiOS at last (Great News!)

2) In future, if proven rock-solid (or close!) we'd like to move towards encouraging everyone to use a much more recent version of Python's cryptography module  / package — along the lines of PR iiab/calibre-web#262 — i.e. preferably having cryptography be internal to the Python venv (/usr/local/calibre-web-py3) as specified by the [other requirements.txt file, defined by the upstream Calibre-Web repo](https://github.com/janeczku/calibre-web/blob/master/requirements.txt) itself! 🙏

**Comment by holta** [comment]
Just FYI this PR might be reverted in future — e.g. if there's an upstream decision to auto-install `cryptography` (via Calibre-Web's [requirements.txt](https://github.com/janeczku/calibre-web/blob/master/requirements.txt)) here:

- https://github.com/janeczku/calibre-web/issues/3183

**Comment by holta** [comment]
This should now be reverted, as a result of:

- janeczku/calibre-web#3183
- PR iiab/calibre-web#275

**Pull request merged**
