### PR TITLE
Make http://box/js-menu publicly browsable [except where code/security is a risk]

### PR DESCRIPTION
**Pull request by holta**
As this used to work with Apache, and can sometimes be very useful, in the spirit of free/open source transparency.

e.g. to peruse/verify/borrow from http://iiab.me/js-menu/menu-files/menu-defs/ etc!

### CODE REVIEW

**Comment by tim-moody** [comment]
this is a security risk. make it 
/js-menu/menu-files/menu-defs and
/js-menu/menu-files/images

will it break if adm cons not installed?

**Comment by holta** [comment]
> this is a security risk. make it
> /js-menu/menu-files/menu-defs and
> /js-menu/menu-files/images

Can we make much more of this publicly browsable?

e.g. is http://box/js-menu/menu-files/services/ the veritable risk &mdash; such that this one single dir (services and its ~5 *.php files) can be blocked &mdash; with all others public underneath http://box/js-menu ?

**Comment by tim-moody** [comment]
I don't think code should be browsable. What's the purpose of anything beyond images and menu defs?

**Comment by holta** [comment]
Is allowing people to browse http://box/js-menu/menu-files/js/js-menu.js dangerous?  I don't know.  But can you clarify either way?

( That's the only other code I see outside of the 5 PHP files under http://box/js-menu/menu-files/services/ )

**Comment by holta** [comment]
Revised & tested!

@tim-moody LMK if further improvements are necessary.

**Comment by tim-moody** [comment]
if this is to be done it belongs in iiab-admin-console so it is not a forward reference

**Comment by holta** [comment]
> if this is to be done it belongs in iiab-admin-console so it is not a forward reference

Ok.  I'll remove this as soon as it's implemented in Admin Console.

**Pull request merged**
