### PR TITLE
Update moodle_installer

### PR DESCRIPTION
**Pull request by jvonau**
moodle - soft code wwwroot dbname

### CODE REVIEW

**Comment by holta** [comment]
@georgejhunt is the idea to merge this one too, as the 7 of 9 PR's that were proposed to be merged during this morning's mtg?

Or are risks too high?

Also if #16 is truly a duplicate/redundant plz close it?!

PS #39 and #42 are the two that you suggested we hold off on merging for now, but I see #39 has now been merged with a slightly new plan, so LMK when to git pull for a full update into Ubuntu in coming hours if poss?

**Comment by georgejhunt** [comment]
I f'd up on 39.

PR's 16 and 17 do not merge on github. So I'll need to do it by hand
locally.

Nothing is perfect.

**Comment by holta** [comment]
@georgejhunt: no worries!

Is it beneficial for me to "cd /opt/iiab/iiab; git pull; ./runansible" on Ubuntu now?

Or better to wait?

**Comment by georgejhunt** [comment]
go for it

**Comment by jvonau** [comment]
implemented by RP #48 not sure why there would not be conflicts now... the code s/b there....

**Pull request closed without merging**
