### PR TITLE
upgrade elgg from 1.12.12 to 1.12.16

### PR DESCRIPTION
**Pull request by georgejhunt**

### CODE REVIEW

**Comment by tim-moody** [comment]
TASK [elgg : change ownership] *************************************************
fatal: [127.0.0.1]: FAILED! => {"changed": false, "failed": true, "msg": "recurse option requires state to be 'directory'", "path": "/opt/elgg-1.12.16", "state": "absent"}

**Comment by tim-moody** [comment]
smoke test should have caught this

**Comment by holta** [comment]
What this smoke tested?

In any case, Elgg 1.12.12 and Elgg 1.12.16 both don't appear in browser, when installed as part of IIAB 6.4 master on Ubuntu or Raspbian Stretch Lite on RPi3.  (Browsing to http://box/elgg currently produces a completely blank page, with a "500 Internal Server Error" if you look under the covers.)

**Comment by holta** [comment]
@georgejhunt: in another Elgg ticket (#145) @jvonau writes "I see schoolserver mentioned in the sql dump, that might be an issue"

No idea if that's related to http://box/elgg consistently producing a blank page & the underlying "500 Internal Server Error" ?

**Pull request merged**
