### PR TITLE
Nextcloud 12.x -> 13.x

### PR DESCRIPTION
**Pull request by holta**
In support of #626 ("Test Nextcloud 13.0.0 vs 12.0.5 on RPi3, Zero W & PC (ETA 2018-02-06)") after @floydianslips's successful test of Nextcloud 13.0.0 on RPi3.

### CODE REVIEW

**Comment by holta** [comment]
Nextcloud 13.x requires: (according to @floydianslips)

> apt install -y php7.0-zip php7.0-xml php7.0-mbstring php7.0 php7.0-gd sqlite php7.0-sqlite php7.0-curl

@tim-moody, @georgejhunt & @jvonau : where do those belong within [roles/2-common/tasks/packages.yml](https://github.com/iiab/iiab/blob/master/roles/2-common/tasks/packages.yml) or otherwise?

**Comment by holta** [comment]
> apt install -y php7.0-zip php7.0-xml php7.0-mbstring php7.0 php7.0-gd sqlite php7.0-sqlite php7.0-curl

- Can someone confirm all 8 above from @floydianslips ?
- Should this really include "sqlite" unattached to any "php7.0-" prefix?
- George's "apt install php7.0-sqlite3" required for 10.7GB map city search is not included above &mdash; where does this last one belong?  SEE: https://github.com/iiab/iiab/pull/659

**Comment by jvonau** [comment]
Aren't those already part of https://github.com/iiab/iiab/blob/master/roles/nextcloud/tasks/main.yml?

**Comment by holta** [comment]
> Aren't those already part of https://github.com/iiab/iiab/blob/master/roles/nextcloud/tasks/main.yml?

Good point.  @floydianslips which if any of those 8 you mention below are truly new requirements? (on Raspbian especially...)

> apt install -y php7.0-zip php7.0-xml php7.0-mbstring php7.0 php7.0-gd sqlite php7.0-sqlite php7.0-curl

**Comment by holta** [comment]
Smoke tested and functionality tested on Ubuntu 16.04 LTS, so I will merge now.

Thanks @floydianslips who confirmed this (appears!) all to work on Raspbian also.

**Pull request merged**
