### PR TITLE
vnStat workaround for #2367

### LINKED ISSUE #2367: vnStat playbook cannot be rerun on a VM w/o LAN? Is iiab-from-console.yml part of the issue?
Thanks @jvonau who is looking into this:

On VM 191-u20-srv-BIG-0423 I clicked Admin Console (http://10.8.0.26/admin) > Configure > Install Configured Options and 2.5 min later Admin Console > Utilities > Display Job Status showed:

> TASK [vnstat : Create database for LAN to collect vnStat data if not appliance config] ***
fatal: [127.0.0.1]: FAILED! => {"changed": true, "cmd": "/usr/bin/vnstat -i none", "delta": "0:00:00.005928", "end": "2020-04-27 17:48:08.988125", "msg": "non-zero return code", "rc": 1, "start": "2020-04-27 17:48:08.982197", "stderr": "", "stderr_lines": [], "stdout": "Error: Interface \"none\" not found in database.", "stdout_lines": ["Error: Interface \"none\" not found in database."]}
>
> PLAY RECAP *********************************************************************
127.0.0.1 : ok=239 changed=57 unreachable=0 failed=1 skipped=106 rescued=0 ignored=0

(FYI this is repeatable, and both /opt/iiab/iiab and /opt/iiab/iiab-admin-console had [nearly] the latest code from their master branches.)

iiab-diagnostics output: http://dpaste.com//35AQEAJ

However the original install 4 days ago worked, according to /opt/iiab/iiab/iiab-install.log :

> 2020-04-23 21:38:04,084 p=8538 u=root n=ansible | TASK [vnstat : Create database for LAN to collect vnStat data if not appliance config] ***
> 2020-04-23 21:38:04,115 p=8538 u=root n=ansible | skipping: [127.0.0.1]

This line https://github.com/iiab/iiab/blob/master/roles/vnstat/tasks/main.yml#L19 :

```
when: iiab_lan_iface is defined
```

...could be revised to:

```
when: iiab_lan_iface is defined and iiab_lan_iface != "none"
```

...but that might be papering over a deeper problem?

_Is it possible [iiab-from-console.yml](https://github.com/iiab/iiab/blob/master/iiab-from-console.yml) is setting vars differently from the original [iiab-stages.yml](https://github.com/iiab/iiab/blob/master/iiab-stages.yml) ??_

FYI Admin Console runs this command when I click Configure > Install Configured Options :

```
/usr/bin/ansible-playbook -i /opt/iiab/iiab/ansible_hosts /opt/iiab/iiab/iiab-from-console.yml --connection=local
```

### PR DESCRIPTION
**Pull request by holta**
Resolves #2367 "vnStat playbook cannot be rerun on a VM w/o LAN? Is iiab-from-console.yml part of the issue?"

A more thorough solution might be in order later?

### CODE REVIEW

**Comment by tim-moody** [comment]
if these files are moved to stage 4 how does that make it easier to update?

**Comment by tim-moody** [comment]
the 'work around' is to install the latest master. there are many things that can break if only part of master is installed.

**Comment by tim-moody** [comment]
looks more like a bug fix than a workaround. requires retesting.

**Comment by holta** [comment]
This workaround bug fix was tested on Ubuntu 20 Server (VM).  Interestingly @jvonau clarifies:

- `./runrole vnstat` worked even without this PR
- Likewise `./iiab-install` and `./iiab-configure` worked even without this PR
- However `iiab-from-console.yml` somehow will require additional debugging, to truly get to the bottom of this...

**Pull request merged**
