### PR TITLE
Allow for NM [NetworkManager] with RPiOS

### PR DESCRIPTION
**Pull request by jvonau**
https://www.raspberrypi.com/news/the-latest-update-to-raspberry-pi-os/

### CODE REVIEW

**Comment by holta** [comment]
Is this safe to merge?

**Comment by jvonau** [comment]
Just trying to get ahead of the curve, basically the same treatment as other OS's that use NM.

**Comment by holta** [comment]
Needs testing.

This PR was merged during our Thursday call (http://minutes.iiab.io) so that testing can advance in preparation for Raspberry Pi OS's transition in coming months.

Please help if you can, reading the instructions here:

https://www.raspberrypi.com/news/the-latest-update-to-raspberry-pi-os/

**Comment by jvonau** [comment]
Works fine with wired install http://sprunge.us/X70j22

**Pull request merged**
