### PR TITLE
Use Kiwix default URI box.lan/kiwix

### PR DESCRIPTION
**Pull request by arky**
Enhances Kiwix proxypass settings, updates kiwix readme file.

### Fixes Bug

Fixes https://github.com/iiab/iiab/issues/979

### Description of changes proposed in this pull request.

Modifies one variable kiwix_url from /kiwix/ to /kiwix

### Smoke-tested in operating system.
Raspbian Stretch 

### Mention a team member for further information or comment using @ name
@holta

### CODE REVIEW

**Comment by holta** [comment]
@arky can you confirm that http://box:3000/kiwix and http://box:3000/kiwix/ work for people who want to avoid the proxy for privacy reasons?

**Comment by holta** [comment]
Overall: I'm greatly in favor of this PR if it provides a clean way to put a lid on the ongoing support nightmare of implementers/teachers/users typing in http://box/kiwix and getting Extremely Frustrated by the (up until now) non-natural need for a trailing slash.

**Comment by arky** [comment]
@holta  Currently doing extensive smoke-testing on Raspbian and Debian in next few days. At the moment they seems to work. But I need to make sure that they play nice with other vhost on Apache.

**Comment by arky** [comment]
@holta To be precise. This patch only fixes the Apache httpd http://box/kiwix using mod_proxy and mod_rewrite. 

The http://box:3000 addresses are served by kiwix-serve process. You might need to fix those in separate issue or PR.
 
https://github.com/iiab/iiab/pull/980#issuecomment-410737411

**Comment by holta** [comment]
FYI quick testing shows that http://box:3000/kiwix does not work (when there is no trailing slash).

This is unfortunate, but as @arky suggests above: this problem might be built into kiwix-serve ?

**Comment by holta** [comment]
Tested flawlessly on Ubuntu 18.04 and 16.04 and Raspbian Lite.

@tim-moody, @georgejhunt & @jvonau please suggest any further revisions/improvements building upon this.

**Comment by holta** [comment]
> Tested flawlessly on Ubuntu 18.04 and 16.04 and Raspbian Lite.

Clarif- on Ubuntu 18.04.1 http://box/kiwix2 currently/correctly returns:

> Not Found
> The requested URL /kiwix2 was not found on this server.
> Apache/2.4.29 (Ubuntu) Server at 10.8.0.x Port 80

Likewise on Ubuntu 16.04.5...

> ...
> Apache/2.4.18 (Ubuntu) Server at 10.8.0.y Port 80

Likewise on the lastest / apt-updated Raspbian Lite...

> ...
> Apache/2.4.25 (Raspbian) Server at 10.8.0.z Port 80

**Comment by tim-moody** [comment]
If the goal of this PR is simply to convert the kiwix proxy from box/kiwix/ to box/kiwix then the changes to the apache config are not necessary. Only the default kiwix_url needs to be changed.

In addition adding a ProxyPassReverse when kiwix does its own reverse proxy internally is at best unnecessary and at worst will have unintended consequences. Nor do I believe the ProxyPreserveHost On is beneficial when host is not part of any the proxy urls.

If the desire is to change the proxy url from /kiwix/ to /kiwix then simply changing the url_prefix should do this. This will break menuing, but that can be fixed rather than patched with a RewriteRule.

And none of this has anything to do with what kiwix does on port 3000.

**Comment by tim-moody** [comment]
Actually I was wrong about the need to rewrite to provide box.lan/kiwix access. However, the following kiwix.conf is sufficient:

RewriteEngine on
RewriteRule ^/kiwix$ /kiwix/ [R]

ProxyPass /kiwix/  http://127.0.0.1:3000/kiwix/

**Comment by holta** [comment]
Thanks so much Tim!  @arky can you perhaps offer a compromise PR in the coming 24h if you have time?

**Comment by holta** [comment]
> @arky can you perhaps offer a compromise PR in the coming 24h if you have time?

Or is PR #985 perhaps enough?

**Pull request merged**
