### PR TITLE
TK Issue: install Apache on demand in ./runrole elgg|lokole|moodle|nodered|phpmyadmin|cups

### PR DESCRIPTION
**Pull request by holta**
As discussed during Friday's IIAB call (http://minutes.iiab.io).  I preferred to wait for IIAB 7.2 but others consider this to be a bug fix (for TK Kang and others like him) i.e. preferring that IIAB 7.1 ship with cleaner/more uniform of `apache_installed` recordkeeping in `/etc/iiab/iiab_state.yml` for `./runrole elgg` etc.

So this PR installs Apache as a dependency to fix TK's issue (treating Apache similar to Node.js, MongoDB, PostgreSQL...as dependencies invoked by higher-level Ansible playbooks).  Building on the ideas in PRs #2407 & #2408.

This PR also deprecates the `exFAT_enabled` variable, which no longer served a purpose with exFAT now mainstream (and bonus, is included within an increasing number of Linux distros).

Smoke-tested on both:
- MIN-sized U20 Server = 10.8.0.30 (then `./runrole elgg` was run afterwards, to verify TK scenario)
- BIG-sized U20 Desktop = 10.8.0.62

### CODE REVIEW

**Comment by holta** [comment]
For good measure, this is also being tested on 183-rpi4-2g-lite-BIG-apache3 = 10.8.0.66

**Comment by jvonau** [comment]
If you are going to push this PR this late in the release cycle then #2381 should be pushed first as that PR have been on the table on one form or another for 9 months now and was placed 'on hold' while master was influx with the nginx|apache split. This PR is an extension of the split that was not completed.

**Comment by tim-moody** [comment]
To be clear, this release cycle at the stage of release candidates has already had a complete rewrite of networking and now the proposal is for a PR with changes to 34 files and another with changes to 25? I'd wait for 7.2.

BTW the exFAT_enabled variable is obsoleted not deprecated. There are security implications of allowing non-unix file systems, but that applies to other FAT devices too.

**Comment by jvonau** [comment]
>- php{{ php_version }}    # On Ubuntu 20.04 (and prob other OS's) this forces the install of: apache2 apache2-bin apache2-data apache2-utils libapache2-mod-php{{ php_version }} ETC" 

For the record the above is not true,  libapache2-mod-php is being installed during [admin-console installation](https://github.com/iiab/iiab-admin-console/search?q=libapache2-mod-php&unscoped_q=libapache2-mod-php), while admin-console advises to be nginx only.

Edit, the linked code is not installing libapache2-mod-php as packages.yml is unused and main.yml has the call # out.

**Comment by holta** [comment]
Installing php{{ php_version }} forces the install of Apache according to my tests on bare Raspbian and bare Ubuntu 20.04 LTS — as show by the output of `apt list apache2`

FYI I tested this both with `apt` at the command-line, and also with Ansible.

**Comment by jvonau** [comment]
> Installing php{{ php_version }} forces the install of Apache according to my tests on bare Raspbian and bare Ubuntu 20.04 LTS — as show by the output of `apt list apache2`
> 
> FYI I tested this both with `apt` at the command-line, and also with Ansible.

Then the bare 'apt install php{{ php_version }}' should be avoided, I'll suggest 'apt install php{{ php_version }}-common' or 'apt install php{{ php_version }}-cli'

**Comment by jvonau** [comment]
>pi@raspberrypi:~ $ apt-cache depends php7.3
php7.3
 |Depends: libapache2-mod-php7.3
 |Depends: php7.3-fpm
  Depends: php7.3-cgi
  Depends: php7.3-common

>pi@raspberrypi:~ $ apt-cache depends php7.3-common
php7.3-common
  Depends: php-common
  Depends: ucf
  Depends: libc6
  Depends: libssl1.1
  Breaks: gforge-common
  Breaks: <php7.0-curl>
  Breaks: <php7.2-sodium>

>pi@raspberrypi:~ $ apt-cache depends php7.3-cgi
php7.3-cgi
  Depends: libmagic1
  Depends: mime-support
  Depends: php7.3-cli
  Depends: php7.3-common
  Depends: php7.3-json
  Depends: php7.3-opcache
  Depends: tzdata
  Depends: ucf
  Depends: libargon2-1
  Depends: libc6
  Depends: libpcre2-8-0
  Depends: libsodium23
  Depends: libssl1.1
  Depends: libxml2
  Depends: zlib1g
  Suggests: php-pear

>pi@raspberrypi:~ $ apt-cache depends php7.3-fpm
php7.3-fpm
  Depends: libmagic1
  Depends: mime-support
  Depends: php7.3-cli
  Depends: php7.3-common
  Depends: php7.3-json
  Depends: php7.3-opcache
  Depends: tzdata
  Depends: ucf
  Depends: libapparmor1
  Depends: libargon2-1
  Depends: libc6
  Depends: libpcre2-8-0
  Depends: libsodium23
  Depends: libssl1.1
  Depends: libsystemd0
  Depends: libxml2
  Depends: zlib1g
  Suggests: php-pear

I'd use php{{ php_version }}-common in place of php{{ php_version }}, looks like php{{ php_version }} is used as short hand for include apache support. No real surprise as iiab was apache concentric up until recently, always assuming apache would be installed, some dependencies such as this one needs to be revisited and adjusted.

**Comment by holta** [comment]
> elgg/tasks/install.yml needs pkg libapache2-mod-php{{ php_version }}

FYI without this, http://box/elgg appeared as follows:

```
<?php
$autoload_path = __DIR__ . '/vendor/autoload.php';
$autoload_available = include_once($autoload_path);
if (!$autoload_available) {
	die("Couldn't include '$autoload_path'. Did you run `composer install`?");
}

\Elgg\Application::index();
```

Related: #2145

**Comment by tim-moody** [comment]
I suggest another approach to this problem. Until apache is completely eliminated, why not just install it (takes a little space) but have each role that needs it enable it (in the systemd sense not ansible). That way it doesn't use resources other than storage if not needed.

**Comment by holta** [comment]
We'll live with this small thing, but just fyi package [awstats](https://packages.debian.org/buster/awstats) (as installed in roles/awstats/tasks/install.yml) forces the installation of ancillary pkg [apache2-bin](https://packages.debian.org/buster/apache2-bin) :

> root@box:~# apt list apache2*
Listing... Done
apache2-bin/focal,now 2.4.41-4ubuntu3 arm64 [installed,automatic]
apache2-data/focal 2.4.41-4ubuntu3 all
apache2-dev/focal 2.4.41-4ubuntu3 arm64
apache2-doc/focal 2.4.41-4ubuntu3 all
apache2-ssl-dev/focal 2.4.41-4ubuntu3 arm64
apache2-suexec-custom/focal 2.4.41-4ubuntu3 arm64
apache2-suexec-pristine/focal 2.4.41-4ubuntu3 arm64
apache2-utils/focal 2.4.41-4ubuntu3 arm64
apache2/focal 2.4.41-4ubuntu3 arm64

This is odd considering `apt-cache depends awstats` output mentions "Suggests:" rather than "Depends:" &mdash; FYI on Ubuntu 20.04 on RPi 4:

> root@box:~# apt-cache depends awstats
awstats
  Depends: <perl:any>
    perl
  Recommends: libnet-xwhois-perl
 |Suggests: apache2
  Suggests: <httpd>
    tntnet
    apache2
    lighttpd
    micro-httpd
    mini-httpd
    nginx-core
    nginx-extras
    nginx-full
    nginx-light
    ocsigenserver
    webfs
    yaws
  Suggests: libnet-dns-perl
  Suggests: libnet-ip-perl
  Suggests: libgeo-ipfree-perl
  Suggests: liburi-perl

Likewise very similarly on Raspbian Lite on RPi 4:

> root@box:~# apt-cache depends awstats
awstats
  Depends: <perl:any>
    perl
  Recommends: libnet-xwhois-perl
 |Suggests: apache2
  Suggests: <httpd>
    bozohttpd
    monkey
    tntnet
    aolserver4-core
    aolserver4-daemon
    apache2
    boa
    ebhttpd
    lighttpd
    mathopd
    micro-httpd
    mini-httpd
    nginx-extras
    nginx-full
    nginx-light
    webfs
    yaws
  Suggests: libnet-dns-perl
  Suggests: libnet-ip-perl
  Suggests: libgeo-ipfree-perl
  Suggests: liburi-perl

**Comment by holta** [comment]
As discussed during this morning's call (http://minutes.iiab.io) this is largely a documentation update and code cleanup to help developers expose (make much more visible) everybody's dependencies going forward &mdash; e.g. weaning us off Apache where NGINX makes that no longer necessary, on smaller IIAB's especially (so `./runrole elgg` etc now works as TK and others want) &mdash; but perhaps more important, this PR corrects and updates a lot of associated in-code guidance, removing many stale comments, etc.

As discussed during last Friday's call (2020-05-15) let's move forward with this now so what's done is done, and our work becomes increasingly more approachable and understandable to all, which is the most important part of the late stages of any release &mdash; explanatory communications, never popular, always crucial in the end~

PR tested intensively on Raspbian, U20 on RPi 4, U20 Server on VM, U20 Graphical/Desktop on VM. 

Lightly tested on Raspbian With Desktop on RPi 4 and Debian 10.4 VM.

FYI the following can be removed from the end of `9-local-addons/tasks/main.yml` in coming days, as appropriate, one way or another, depending on what Admin Console approach @tim-moody prefers to take:

```
- name: '2020-05-21: TEMPORARILY INSTALL APACHE UNTIL ADMIN CONSOLE DECLARES (OR
REMOVES?) ITS DEPENDENCY within [console : Enable ssl] to avoid error "Neither of apache2ctl
nor apachctl found. At least one apache control binary is necessary." -- possibly var
adm_cons_force_ssl is still useful here?'
  package:
    name: apache2
  when: admin_console_install | bool

**Comment by holta** [comment]
Admin Console considerations on PR iiab/iiab-admin-console#323:

"remove module for unused apache2"
https://github.com/iiab/iiab-admin-console/commit/868d2d36554f17ba7807b715dba3714d8cad9e80

**Comment by holta** [comment]
No rush but fyi Admin Console has another dependency on Apache here:

> TASK [console : Install admin-console service config file] *********************
fatal: [127.0.0.1]: FAILED! => {"changed": false, "checksum": "34b47817903b0e6b9537451052061c24ba82b186", "msg": "Destination directory /etc/apache2/sites-available does not exist"}

Arising from https://github.com/iiab/iiab-admin-console/blob/master/roles/console/tasks/main.yml#L148-L150 here:

```
- name: Install admin-console service config file
  template: src=cmd-service.conf.j2
            dest=/etc/{{ apache_config_dir }}/cmd-service.conf

**Comment by holta** [comment]
See also:

"remove another apache dependency"
PR iiab/iiab-admin-console#326 (merged)

**Pull request merged**
