### PR TITLE
Wrong variable name [in iiab-make-kiwix-lib]

### PR DESCRIPTION
**Pull request by tim-moody**

### CODE REVIEW

**Comment by tim-moody** [comment]
currently testing on rpi

**Comment by holta** [comment]
Should this be merged today?

**Comment by tim-moody** [comment]
it's clearly bug, but since it only happens in an exception I have not been able to trigger it. risk of merging is very low

**Comment by holta** [comment]
> it's clearly bug, but since it only happens in an exception I have not been able to trigger it. risk of merging is very low

Thanks...and thanks to all for testing `iiab-make-kiwix-lib` in coming days!

**Pull request merged**
