### PR TITLE
RFC Eth0+dnsmasq

### PR DESCRIPTION
**Pull request by jvonau**
[iiab-network.log.txt](https://github.com/iiab/iiab/files/1299684/iiab-network.log.txt)
tested for dhcpd -> dnsmasq -> dhcpd operation with iiab-network. Full conductivity for dnsmasq was not evaluated at this time, just the ability to switch between the modes. Need to evaluate /usr/lib/systemd/system/dnsmasq.service from the other distros, might have differences and this one was brute forced, as there was no stop line present. The debian.yml is the only path available, looked to keep debian.yml and ifcfg_mods.yml doing the same sequence of events.  Execution time is under 2 mins on the nuc here. Have a look at #242 as a nice bugfix/enhancement to round out the install time options.

### CODE REVIEW

**Comment by tim-moody** [comment]
is this a branch off 178 or must that be applied first?

**Comment by jvonau** [comment]
Sorry I should of mentioned it's continuation of 178.  I should rebase 178 on current master first though but it looks to be a clean PR. Just have to give it a shake down 178 before this one. Or just jump to this one and start small with, I would suggest iiab.network, the log is smaller and just what is needed is loading.

**Comment by jvonau** [comment]
I should add a clean install with a good clone depth or a straight clone from me would be preferred. You could hand delete /etc/network/interfaces before running iiab.network with a 'git pull' as I have not addressed upgrades.

**Comment by jvonau** [comment]
[adam-243.txt](https://github.com/iiab/iiab/files/1304239/adam-243.txt) system is up with dhcpcd. br0 is active along with hostapd and dhcpd no reboot should be needed to use the wifi/LAN.

**Comment by jvonau** [comment]
● networking.service - Raise network interfaces
   Loaded: loaded (/lib/systemd/system/networking.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Thu 2017-09-14 15:23:02 EDT; 8min ago
     Docs: man:interfaces(5)
  Process: 464 ExecStart=/sbin/ifup -a --read-environment (code=exited, status=1/FAILURE)
  Process: 422 ExecStartPre=/bin/sh -c [ "$CONFIGURE_INTERFACES" != "no" ] && [ -n "$(ifquery --read-
 Main PID: 464 (code=exited, status=1/FAILURE)

Sep 14 15:23:02 box.lan ifup[464]: can't add wlan0 to bridge br0: Operation not supported
Sep 14 15:23:02 box.lan ifup[464]: Loading netfilter rules...run-parts: executing /usr/share/netfilte
Sep 14 15:23:02 box.lan ifup[464]: run-parts: executing /usr/share/netfilter-persistent/plugins.d/25-
Sep 14 15:23:02 box.lan ifup[464]: done.
Sep 14 15:23:02 box.lan ifup[464]: RTNETLINK answers: File exists
Sep 14 15:23:02 box.lan ifup[464]: ifup: failed to bring up br0
Sep 14 15:23:02 box.lan systemd[1]: networking.service: Main process exited, code=exited, status=1/FA
Sep 14 15:23:02 box.lan systemd[1]: Failed to start Raise network interfaces.
Sep 14 15:23:02 box.lan systemd[1]: networking.service: Unit entered failed state.
Sep 14 15:23:02 box.lan systemd[1]: networking.service: Failed with result 'exit-code'.

**Comment by georgejhunt** [comment]
I don't know how to say this gracefully, but I don't think we had agreed on our calls that dnsmasq would be part of 6.4. Certainly it's ok to check out what will be required for 6.5, and prepare for it.

**Comment by jvonau** [comment]
Don't advertise the availability in the docs and don't show the option in default or local_vars, there is further testing to be done on the dnsmasq side. Those who want to play around and provide feedback can add dnsmasq_install to their local_vars, what would make it a total opt-in option to be tested by more advanced users.

**Pull request closed without merging**
