### PR TITLE
OSM-venv

### PR DESCRIPTION
**Pull request by jvonau**

### CODE REVIEW

**Comment by tim-moody** [comment]
what amount of addition storage does using a venv require?

**Comment by jvonau** [comment]
There are two ways for the venv to be populated, files totally isolated or with symlinks pointing to what is already present on the system. That is virtualenv_site_packages= in ansible.
This fully isolated type I used du shows:
66M	/usr/local/osm/
4.0M /usr/local/osm/lib/python2.7/site-packages/iiab
22M	/usr/local/osm/lib/python2.7/site-packages/babel

While linking can save some space, the amount saved would depend on what is already installed. Nice part is all the dependencies are in /usr/local/osm/

**Comment by tim-moody** [comment]
for whoosh I see virtualenv_site_packages=no, which I believe is the default.
for osm I was expecting virtualenv_site_packages=yes

**Comment by jvonau** [comment]
I opted for the fully isolated method, wasn't sure what other frozen dependencies whoosh might have. That would be the place to toggle sharing with the system installed libraries thou. I have not tested not having virtualenv_site_packages= the same in the two stanzas. I've tried yes first but did not note the installed footprint.

**Comment by georgejhunt** [comment]
So I don't think <100MB is too much penalty for the benefits going forward

**Comment by jvonau** [comment]
It's less than 100M actually, 66 for the full install - 28 for what is installed anyway= 38M maximum space saving by sharing, didn't think it was worth it but sharing could be explored.  When updating OSM install just blow away usr/local/osm and re-install,  same hold true for kalite.

**Comment by holta** [comment]
FYI to help others understand the underlying motives here...a citation from #162: (KA Lite venv)

**Comment by georgejhunt** [comment]
I take it from the numbers regarding disk footprint, that this has successfully been smoke tested?

**Comment by georgejhunt** [comment]
included in 259

**Pull request closed without merging**
