### PR TITLE
Moodle 3.11 Released: In future we might want to set 'max_input_vars = 5000' not just in /etc/php/X.Y/fpm/php.ini but also in /etc/php/X.Y/apache2/php.ini etc ??

### PR DESCRIPTION
**Pull request by holta**
Implements #2772 now that Moodle 3.11 is released.

In future we might want to raise `max_input_vars = 1000` to `max_input_vars = 5000` in other places as well:

```
root@box:~# grep -rn max_input_vars /etc
/etc/php/7.3/apache2/php.ini:397:;max_input_vars = 1000
/etc/php/7.3/fpm/php.ini:397:;max_input_vars = 1000
/etc/php/7.3/cli/php.ini:397:;max_input_vars = 1000
```

For example if the transition from Apache to NGINX doesn't happen in time for PHP 8 later this year (2021) when `max_input_vars = 5000` [will become required (not just recommended!)](https://docs.moodle.org/311/en/Environment_-_max_input_vars)

### CODE REVIEW

**Comment by holta** [comment]
@deldesir do you have time to test this?

Thank you if so!

**Comment by deldesir** [comment]
Let's do it

**Comment by holta** [comment]
@deldesir if you're testing a fresh install / clean install, great.

And/or if you're testing this PR #2784 on an existing IIAB install, please do something like the following:

```
cd /opt/iiab/iiab
git checkout -b moodle-3.11 master
git pull https://github.com/holta/iiab moodle-3.11
# REMOVE 'www_options_installed: True' AND 'moodle_installed: True' from /etc/iiab/iiab_state.yml
./runrole www_options
./runrole moodle
```

**Review by deldesir — CHANGES_REQUESTED** [review]
We need to address this. Raised on Ubuntu Server 21.04.

TASK [moodle : Install 8 php packages (debuntu)] *******************************
fatal: [127.0.0.1]: FAILED! => {"changed": false, "msg": "No package matching 'php7.4-sodium' is available"}

**Comment by holta** [comment]
A bit more clarif for the above commit &mdash; here on 32-bit RaspiOS Lite on RPi 4:

```
root@box:~# apt list '*sodium*'
Listing... Done
libsodium-dev/stable 1.0.17-1 armhf
libsodium23/stable,now 1.0.17-1 armhf [installed,automatic]
php-libsodium/stable 1.0.6-1+b2 armhf
python-pysodium/stable 0.7.0-1 all
python3-pysodium/stable 0.7.0-1 all

root@box:~# php -i | grep sodium
sodium
sodium support => enabled
libsodium headers version => 1.0.17
libsodium library version => 1.0.17
```

**Review by deldesir — APPROVED** [review]

**Comment by holta** [comment]
@deldesir successfully tested this revised PR using an existing IIAB install on a Ubuntu Server 21.04 VM (10.8.0.94).  Then he tested Moodle's basic functionality with a text browser, e.g.:

```
lynx http://box.lan/moodle
```

All looks good.  That's enough of a basic smoke-test to merge.

Finally, @deldesir if you also have time to do a full clean install / fresh install later this week, just let us know how that goes and consider the hard work of converting Moodle from Apache to NGINX if you're willing over the coming weeks!

Ref: #2762, PR #2775, PR #2776 & https://github.com/iiab/iiab/tree/master/roles/nginx -> README.md

**Comment by holta** [comment]
> @deldesir if you're testing a fresh install / clean install, great.
> 
> And/or if you're testing this PR #2784 on an existing IIAB install, please do something like the following:
> 
> ```
> cd /opt/iiab/iiab
> git checkout -b moodle-3.11 master
> git pull https://github.com/holta/iiab moodle-3.11
> # REMOVE 'www_options_installed: True' AND 'moodle_installed: True' from /etc/iiab/iiab_state.yml
> ./runrole www_options
> ./runrole moodle
> ```

@deldesir my apologies I did not explain well above.  The more complete test (done below!) is to read http://FAQ.IIAB.IO > "28 Can I upgrade or reinstall server apps?" > "3) Prior to February 2020..." > 3rd bullet:

> - /opt/iiab/moodle/config-dist.php (Moodle version stored in /opt/iiab/moodle/version.php — major upgrades may require deleting /opt/iiab/moodle and /library/moodle, dropping the database using "dropdb -U postgres moodle" — and if nec upgrade PostgreSQL below)

Which boils down to:

```
# Get rid of the OLD Moodle e.g. 3.10
mv /opt/iiab/moodle /opt/iiab/moodle.old
mv /library/moodle /library/moodle.old
dropdb -U postgres moodle

# Set 'nginx_high_php_limits: True' in local_vars.yml (Line 169)
nano /etc/iiab/local_vars.yml

# Change 'max_input_vars = 1000' to 5000
./runrole --reinstall www_options

# Verify 'max_input_vars = 1000' changed to 5000
tail /etc/php/7.4/fpm/php.ini

# Install NEW Moodle e.g. 3.11
./runrole --reinstall moodle

# Confirm NEW Moodle e.g. 3.11 is installed
tail /opt/iiab/moodle/config-dist.php

# Run Moodle in a text browser or using a graphical browser ON THIS SAME MACHINE!
lynx http://box.lan/moodle

# READ: http://FAQ.IIAB.IO > "36 WordPress & Moodle Administration: What tips & tricks exist?" > "How do I set the Moodle URL (like http://box.lan/moodle) so it works for everyone?"
```

**Comment by holta** [comment]
CLARIF: the above testing by @deldesir happened on an Ubuntu Server 21.04 VM, where IIAB had already been installed (BIG-sized) about a week ago.

**Pull request merged**
