### PR TITLE
Using Ansible get_url module to fix warnings

### PR DESCRIPTION
**Pull request by arky**
Using Ansible 'get_url' modules instead of 'wget' to download usbmout package. Fixes warnings in bug #327 #349

### CODE REVIEW

**Comment by holta** [comment]
@arky is this smoke-tested and/or functionality-test?  Thanks if poss!

**Comment by georgejhunt** [comment]
we migrated to wget from get_url because ansible was running out of tmp
space or memory, but wget failed much less often.

**Comment by jvonau** [comment]
@holta conflicts and push

**Comment by holta** [comment]
This needs testing and @georgejhunt deserves a response or clarification prior to merge:

> we migrated to wget from get_url because ansible was running out of tmp
space or memory, but wget failed much less often.

**Comment by jvonau** [comment]
this one is for a small package, I'll toss it in a jenkins run (think I have in the past, can't recall)

**Comment by holta** [comment]
In response to @georgejhunt's comment above, we agreed during our live call (http://minutes.iiab.io) to trial this new approach on small package (usbmount) here.

**Pull request merged**
