### PR TITLE
php-stem - include all RaspOS variants

### PR DESCRIPTION
**Pull request by jvonau**
### Fixes bug:
#2797

### CODE REVIEW

**Comment by tim-moody** [comment]
the question is whether php7.3-stem.rpi.tar works on rpi W. if it does the approach should not be to exclude armv6 from the 'available' list but to install php7.3-stem.rpi.tar for armv6. As an aside I notice there is no version for arm for php7.4.

**Comment by holta** [comment]
> further down the line nextcloud fails instead

FWIW Nextcloud says it requires 512 MB RAM (`nginx_high_php_limits: True` should really be set in [/etc/iiab/local_vars.yml](http://wiki.laptop.org/go/IIAB/FAQ#What_is_local_vars.yml_and_how_do_I_customize_it.3F) in advance of installing Nextcloud).

In short, MEDIUM-sized IIAB installs are not recommended on Raspberry Pi Zero W for several reasons, but this is one of them (512 MB happens to be the total hardware system memory!)

**Comment by jvonau** [comment]
> editing php-stem.yml to either ignore armv6 or use the same source as armv7 appears to produce the same results. The check passes during installation of www_base,

That would be the part this pull request addresses

>and further down the line nextcloud fails instead; 
```
raspbian.raspberrypi.org/raspbian buster/main armhf libx11-xcb1 armhf 2:1.6.7-1+deb10u1", "  404  Not Found [IP: 93.93.128.193 80]"]}
```
You had a network glitch from your location. iiab is not fully installed, none of the options are installed.

> though cmdsrv does work now and the system can be managed through http://box/admin.

I'd slim down some of your install options or at least don't enable some of them. You can later turn those on and off at will post install with relative ease for the reasons stated above, scarce resources.

**Comment by jvonau** [comment]
> the question is whether php7.3-stem.rpi.tar works on rpi W. if it does the approach should not be to exclude armv6 from the 'available' list but to install php7.3-stem.rpi.tar for armv6. As an aside I notice there is no version for arm for php7.4.

I have a vague recollection of the compilation was on ubuntu 32bit to get php7.3-stem.rpi, if the compilation was on RaspOS then the tag should be armv6 and 'should work' on armv7 or greater. Now given this feature fix is targeted at es-wikihow should this routine be part of mediawiki as this user is not even installing mediawiki?

**Comment by tim-moody** [comment]
> I have a vague recollection of the compilation was on ubuntu 32bit to get php7.3-stem.rpi, if the compilation was on RaspOS then the tag should be armv6 and 'should work' on armv7 or greater. Now given this feature fix is targeted at es-wikihow should this routine be part of mediawiki as this user is not even installing mediawiki?

I think I labelled it rpi to indicate it would work for either arm, but it would have to be tried.

I also think there has been discussion about where to put it. But the name not withstanding es-wikihow is not a zim or mediawiki, but just a straight php module in /modules so served by nginx.

**Comment by holta** [comment]
Discussed on today's call (http://minutes.iiab.io).  @jvonau will rework this PR to take that into account.

**Review by holta — COMMENTED** [review]
This doesn't seen right, as php-stem is for RACHEL / OER2Go module http://box/modules/es-wikihow from http://oer2go.org/viewmod/es-wikihow

(It shouldn't have any connection to MediaWiki, that I know of.)

**Comment by holta** [comment]
@tim-moody can you confirm this looks good?

**Comment by Mathazzar** [comment]
nextcloud seems to consistently fail in the same way, regardless of how many modules are enabled or not, though no errors are stopping ./iiab-install early anymore, so I suspect it's probably the lack of physical resources inherent to the Zero W.

**Comment by jvonau** [comment]
https://github.com/iiab/iiab/issues/829 mentions [this error](https://github.com/iiab/iiab/issues/829#issuecomment-397348765) at a point in time where there was movement from away from php5x and stem support being available. I have a feeling the entire website was rewritten since 2018. The d/l is 12GB, a bit much to look at one file, if es-wikihow deployed anywhere the contents of /library/www/html/modules/es-wikihow/content/search/search.php would be useful to know.

**Comment by jvonau** [comment]
stem should just go away.

**Comment by holta** [comment]
Not a postcard paradise for sure.

But we should try to see what's possible here, to mitigate ongoing install problems like #2797 and #2835.

Better yet if we can get search to "largely work" for WikiHow (given this OER2Go/RACHEL content module's massive popularity in high schools).

**Pull request closed without merging**
