### PR TITLE
For discussion where should "Collections" reside? [Ansible]

### PR DESCRIPTION
**Pull request by jvonau**
idea..

### CODE REVIEW

**Comment by holta** [comment]
Should https://docs.ansible.com/ansible/latest/collections/ansible/posix/selinux_module.html be mentioned...as possibly nec for [roles/1-prep/tasks/selinux.yml](https://github.com/jvonau/iiab/blob/deb_selinux/roles/1-prep/tasks/selinux.yml) at some future date?

**Comment by holta** [comment]
i.e. should the `ansible.posix` Ansible collection be mentioned...as possibly being nec...at some future date?

https://galaxy.ansible.com/ansible/posix

Whether or not installed directly as follows:

```
ansible-galaxy collection install ansible.posix
```

**Comment by holta** [comment]
Thanks @tim-moody and @jvonau for uncovering this serious bug.

Do we know yet whether it affects all OS's ?

**Comment by holta** [comment]
Emergency patch merged...for now: PR #2648

**Comment by holta** [comment]
What are some of the advantages/disadvantages of putting Ansible Collections in `/usr/share/ansible/collections` vs. `/root/.ansible/collections/ansible_collections` ?

**Comment by jvonau** [comment]
Would allow somebody other than root to access the collections for one. Second with the collections in the filesystem proper I'm able to create a snap with ansible and collections pre-installed in the snap. Snaps don't contain a /root directory.

**Comment by jvonau** [comment]
You just glossed over the -[p option](https://docs.ansible.com/ansible/latest/user_guide/collections_using.html) when #2518 was introduced. Note the COLLECTIONS_PATHS blurb in the url.

**Comment by holta** [comment]
I'm assuming the `ansible-galaxy -p <DIR>` flag auto-creates whatever directory you ask it to use?

Just FYI here's a manifest/summary of IIAB's current Ansible Collections:

```
root@box:~# du -hsc /root/.ansible/collections/ansible_collections/*/*
2.1M    /root/.ansible/collections/ansible_collections/ansible/netcommon
1.5M    /root/.ansible/collections/ansible_collections/ansible/posix
23M     /root/.ansible/collections/ansible_collections/community/general
1.3M    /root/.ansible/collections/ansible_collections/community/kubernetes
876K    /root/.ansible/collections/ansible_collections/community/mysql
7.9M    /root/.ansible/collections/ansible_collections/google/cloud
37M     total
```

```
root@box:~# ansible-galaxy collection list

# /root/.ansible/collections/ansible_collections
Collection           Version
-------------------- -------
ansible.netcommon    1.4.1
ansible.posix        1.1.1
community.general    1.3.0
community.kubernetes 1.1.1
community.mysql      1.1.1
google.cloud         1.0.1
```

Aside: The Linux Mint community views [snaps](https://snapcraft.io/) as very proprietary and something to avoid (e.g. Linux Mint 20 [removes](https://www.zdnet.com/article/linux-mint-dumps-ubuntu-snap/) the Snap infrastructure) but possibly that might change in future ?

**Comment by jvonau** [comment]
Correct, -p states the directory for storage, the builtin defaults where ansible looks are here: https://docs.ansible.com/ansible/latest/reference_appendices/config.html#collections-paths and present in https://github.com/ansible/ansible/blob/devel/examples/ansible.cfg. When and if ansible's collections ever get to the apt packaging stage that is where the collections will have to live..

**Comment by jvonau** [comment]
> Aside: The Linux Mint community views snaps as very proprietary and something to avoid (e.g. Linux Mint 20 removes the Snap infrastructure) but possibly that might change in future ?

I personally could care less about a derivative of ubuntu, and my crystal ball is fuzzy so no future predictions from me.

**Comment by holta** [comment]
> 7.9M    /root/.ansible/collections/ansible_collections/google/cloud

Aside: offline communities could be forgiven for asking why on earth they're being forced to carry around [google.cloud](https://galaxy.ansible.com/google/cloud) software...that (even if it was needed!) is more than 5X bigger than [ansible.posix](https://galaxy.ansible.com/ansible/posix) ;)

**Comment by jvonau** [comment]
> > 7.9M    /root/.ansible/collections/ansible_collections/google/cloud
> 
> Aside: offline communities could be forgiven for asking why on earth they're being forced to carry around [google.cloud](https://galaxy.ansible.com/google/cloud) software...that (even if it was needed!) is more than 5X bigger than [ansible.posix](https://galaxy.ansible.com/ansible/posix) ;)

Same reason to need 23M of general for "ini_file" I guess..  The collections and dependence relationships are influx, there is a lot of refactoring going on behind the curtain.

**Comment by jvonau** [comment]
Think a better reason would be to allow any system user to navigate to and read /usr/share/ansible/collections/ansible_collections/community/general/CHANGELOG.rst to better understand what just blew up when something changes again in the future.

**Comment by jvonau** [comment]
I see shades of sugarlabs/olpc bleeding through creating a toxic environment, just another not invented here response with #2655

**Pull request closed without merging**
