### PR TITLE
raspbian lite images has awk but not gawk

### PR DESCRIPTION
**Pull request by georgejhunt**
This may not be true in other distros. But I guess we are focusing on raspbian first. related to Jerry's issue 59

### CODE REVIEW

**Comment by holta** [comment]
Ref #59 (missing gawk can cause Wifi detection failure on first run)

**Comment by georgejhunt** [comment]
smoke tested on VM

**Comment by jvonau** [comment]
I'd wait pending #178 but others wise push it.

**Comment by jvonau** [comment]
push this

**Pull request merged**
