### PR TITLE
Ubuntu install failure - BUGFIX dns dropout - BUGFIX wifi as gateway - ENHANCEMENT/REGRESSION dhcp assinged address when static - BUGFIX repsect user defined networking - ENHANCEMENT respect static addressing in local_vars - REGRESSION

### PR DESCRIPTION
**Pull request by jvonau**
Trying to avoid using /etc/network/interfaces at all

### CODE REVIEW

**Comment by jvonau** [comment]
Not dependant on the other change in #156 being addressed yet

**Comment by jvonau** [comment]
Without modifying the stock packages this should get back to dealing with an out of the box machine without any pre-conceived judgement on what is required. However dhcpcd may not be running/installed so a failure is possible.
check installation with 'which dhcpcd'
check running with ps -A | grep dh
if dhcpcd is not running edit etc/network/interfaces.d/iiab removing the # from the last 2 lines.
Lets play safe, reload systemd with 'systemctl daemon-reload' and restart the network with 'systemctl restart networking'.

**Comment by jvonau** [comment]
if dhcpcd is running edit /etc/dhcpcd.conf remove "#" from denyinterfaces and '#' interface and below.
Lets play safe, reload systemd with 'systemctl daemon-reload' and restart the network with 'systemctl restart networking'. Happy testing

**Comment by holta** [comment]
@jvonau working with me...3 files pasted from a virgin Raspbian Lite:

```
root@raspberrypi:~# more queen-pi.txt
::::::::::::::
/etc/resolv.conf
::::::::::::::
# Generated by resolvconf
nameserver 192.168.0.1
::::::::::::::
/etc/resolvconf.conf
::::::::::::::
# Configuration for resolvconf(8)
# See resolvconf.conf(5) for details

resolv_conf=/etc/resolv.conf
# If you run a local name server, you should uncomment the below line and
# configure your subscribers configuration files below.
#name_servers=127.0.0.1

# Mirror the Debian package defaults for the below resolvers
# so that resolvconf integrates seemlessly.
dnsmasq_resolv=/var/run/dnsmasq/resolv.conf
pdnsd_conf=/etc/pdnsd.conf
unbound_conf=/var/cache/unbound/resolvconf_resolvers.conf
::::::::::::::
/etc/dhcpcd.conf
::::::::::::::
# A sample configuration for dhcpcd.
# See dhcpcd.conf(5) for details.

# Allow users of this group to interact with dhcpcd via the control socket.
#controlgroup wheel

# Inform the DHCP server of our hostname for DDNS.
hostname

# Use the hardware address of the interface for the Client ID.
clientid
# or
# Use the same DUID + IAID as set in DHCPv6 for DHCPv4 ClientID as per RFC4361.
# Some non-RFC compliant DHCP servers do not reply with this set.
# In this case, comment out duid and enable clientid above.
#duid

# Persist interface configuration when dhcpcd exits.
persistent

# Rapid commit support.
# Safe to enable by default because it requires the equivalent option set
# on the server to actually work.
option rapid_commit

# A list of options to request from the DHCP server.
option domain_name_servers, domain_name, domain_search, host_name
option classless_static_routes
# Most distributions have NTP support.
option ntp_servers
# Respect the network MTU. This is applied to DHCP routes.
option interface_mtu

# A ServerID is required by RFC2131.
require dhcp_server_identifier

# Generate Stable Private IPv6 Addresses instead of hardware based ones
slaac private

# Example static IP configuration:
#interface eth0
#static ip_address=192.168.0.10/24
#static routers=192.168.0.1
#static domain_name_servers=192.168.0.1 8.8.8.8

# It is possible to fall back to a static IP if DHCP fails:
# define static profile
#profile static_eth0
#static ip_address=192.168.1.23/24
#static routers=192.168.1.1
#static domain_name_servers=192.168.1.1

# fallback to static profile on eth0
#interface eth0
#fallback static_eth0
```

**Comment by georgejhunt** [comment]
This may shed light on the startup and shutdown stalls I struggled with.
Perhaps the two daemons were not connected properly.

Perhaps the solution back then would have been to configure dhcpcd to work
with resolvconf rather than to fight and refuse to communicate.  Whenever
permissions are involved, unconfigured things just do not happen.

Thanks Jerry for the education.

**Comment by jvonau** [comment]
This should be testable on rpi's and run clean but use the [PR testing tool](https://github.com/iiab/iiab/blob/master/scripts/test-pr) as this PR will not be able to be used when cloning with a depth of 1 as master has advanced and I am not going to do a rebase and lose the commit/comment threading in this PR. Ubuntu & Debian-9 can be tested also, but might not succeed if dhcpcd is not pre-installed, but we need to get a baseline of what is installed by default.

**Comment by holta** [comment]
Ref #198 (pastes in output of "ip address" and 5 critical networking files, from the new Raspbian Stretch Lite released on 2017-08-16)

**Comment by jvonau** [comment]
Thanks confirms that resolvconf is being used and should not be removed, and that the wifi is being handled by dhcpcd which is controlling wpa_supplican on the rpi. Added suppression of the red warning.

**Comment by jvonau** [comment]
Oh wait a sec I'm branched from current master as of right now so testing with a depth of 1 should work with the github instructions or a direct clone of my branch like in PR #171

**Comment by georgejhunt** [comment]
I discovered that:
You disable the assignment of fixed names, so that the unpredictable kernel names are used again. For this, simply mask udev's .link file for the default policy: ln -s /dev/null /etc/systemd/network/99-default.link
-- this actually worked, and does not involve changing the /boot/cmdline.txt.  I miss that when looking for alternatives.

**Comment by jvonau** [comment]
That seems cleaner, and we can probably adapt that to the other distros rather than altering the boot prompt which might be froth with danger when editing grub. I guess a reboot is still needed to defeat udev?

**Comment by jvonau** [comment]
Full optioned [man page](https://www.daemon-systems.org/man/dhcpcd.conf.5.html) of dhcpcd.conf

**Comment by jvonau** [comment]
re-opened to update file diff for last commit - reopen if you it of have comments

**Comment by georgejhunt** [comment]
From 193492c54bf1683a7bbcbc12eec2cb22efec617c Mon Sep 17 00:00:00 2001
From: George Hunt <georgejhunt@gmail.com>
Date: Sat, 9 Sep 2017 17:17:44 -0700
Subject: [PATCH] gets me through networking on ubuntu

---
 roles/1-prep/tasks/detected_network.yml       | 5 +++--
 roles/network/tasks/main.yml                  | 6 ++----
 roles/network/templates/network/interfaces.j2 | 2 +-
 3 files changed, 6 insertions(+), 7 deletions(-)

diff --git a/roles/1-prep/tasks/detected_network.yml b/roles/1-prep/tasks/detected_network.yml
index a6e908f..3019d38 100644
--- a/roles/1-prep/tasks/detected_network.yml
+++ b/roles/1-prep/tasks/detected_network.yml
@@ -23,7 +23,8 @@
 - name: Checking for ifcfg-WAN file
   stat: path=/etc/sysconfig/network-scripts/ifcfg-WAN
   register: has_ifcfg_WAN
-  when: is_redhat
+  #when: is_redhat
+  ignore_errors: true
 
 - name: Setting ifcfg-WAN True
   set_fact:
@@ -130,7 +131,7 @@
   shell: egrep -rn ESSID /etc/sysconfig/network-scripts/ifcfg* | gawk -F ':' '{print $1}' | gawk -F '/' '{print $5}'
   register: ifcfg_WAN_wifi
   ignore_errors: True
-  when: is_redhat
+  #when: is_redhat
 
 #returns file name
 - name: Setting has_wifi_gw based on ESSID if found
diff --git a/roles/network/tasks/main.yml b/roles/network/tasks/main.yml
index a305e62..f3e3658 100644
--- a/roles/network/tasks/main.yml
+++ b/roles/network/tasks/main.yml
@@ -77,10 +77,8 @@
   shell: systemctl daemon-reload
   when: not installing
 
-- include: ifcfg_mods.yml
-  tags:
-    - network
-  when: is_redhat and not installing
+#- include: ifcfg_mods.yml
+#  when: is_redhat
 
 - include: debian.yml
   tags:
diff --git a/roles/network/templates/network/interfaces.j2 b/roles/network/templates/network/interfaces.j2
index 2b48abf..010bf40 100644
--- a/roles/network/templates/network/interfaces.j2
+++ b/roles/network/templates/network/interfaces.j2
@@ -42,7 +42,7 @@ iface br0 inet static
     dns-nameservers {{ lan_ip }}
 {% if dhcpcd_result != "enabled" or not wan_in_interfaces %}
 auto {{ iiab_wan_iface }}
-iface {{ iiab_wan_iface }} inet dhcp
+iface {{ iiab_wan_iface }} inet manual
 {% else %} # gui_static_wan_ip is set 
 auto {{ iiab_wan_iface }}
 iface {{ iiab_wan_iface }} inet static
-- 
2.7.4

stalled until I changed the dhcp to manual in /etc/network/interfaces, and reran

I do not understand why ansible was running ifcfg_mods.yml, but I had to comment it out just to see what else happened.  I did not remove the dhcp in appliance (I had two adapters plugged"

**Comment by jvonau** [comment]
I'm with you on is_redhat should of worked... Think systemd or network-manager might be in the mix...  /etc/iiab/iiab.ini should tell us some more, what does dhcpcd_result have recorded? and what does 'netstat -naup | grep dh' return?

**Comment by georgejhunt** [comment]
root@pig:~# netstat -naup |grep dh
udp        0      0 0.0.0.0:9061            0.0.0.0:*
    1457/dhcpd
udp        0      0 0.0.0.0:67              0.0.0.0:*
    1457/dhcpd
udp        0      0 0.0.0.0:68              0.0.0.0:*
    25988/dhcpcd
udp6       0      0 :::24565                :::*
     1457/dhcpd
 and dhcpcd_result: enabled

**Comment by jvonau** [comment]
{% if dhcpcd_result != "enabled" or not wan_in_interfaces %} was suppose to not write anything just leave it blank. Think that might have to be changed to 'or wan_in_interfaces  == "false"' anything in /etc/network/interfaces? and wan_in_interfaces in iiab.ini?

**Comment by georgejhunt** [comment]
# This file describes the network interfaces available on your system
# and how to activate them. For more information, see interfaces(5).

source /etc/network/interfaces.d/*

# The loopback network interface
auto lo
iface lo inet loopback

# iiab_network_mode is Gateway

#################   GATEWAY   #########################
auto br0
iface br0 inet static
    bridge_ports   eno1
    bridge_maxwait 0
    address 172.18.96.1
    netmask 255.255.224.0
    dns-nameservers 172.18.96.1
auto enxd8eb97bdae2e
iface enxd8eb97bdae2e inet manual

~

"/etc/network/interfaces" 22L, 544C                           1,1
All


ini file
wireless_list_1 = not found-1
wireless_list_2 = not found-2
num_wifi_interfaces = 0
discovered_wireless_iface = none
iiab_wireless_lan_iface = none
num_lan_interfaces = 1
detected_lan = eno1
static_wan = False
iiab_wan_enabled = True
user_wan_iface = enxd8eb97bdae2e
iiab_wan_iface = enxd8eb97bdae2e
iiab_lan_enabled = True
user_lan_iface = auto
iiab_lan_iface = br0
iiab_network_mode = Gateway
hostapd_enabled = True
host_ssid = Internet+in+a+Box
host_wifi_mode = g
host_channel = 6
iiab_network_mode_applied = Gateway
internet_available = True
gw_active = False
has_ifcfg_gw = none
discovered_wan_iface = enxd8eb97bdae2e
prior_gateway_(device_gw2) = enxd8eb97bdae2e
wireless_list_1(wifi1) = not found-1
wireless_list_2(wifi2) = not found-2
discovered_lan_iface = eno1
gui_static_wan = False
wan_in_interfaces = True
dhcpcd_result = enabled

**Comment by jvonau** [comment]
This there a /etc/network/interfaces.d/iiab file? My code doesn't write to /etc/network/interfaces, is this a git pull upgrade by any chance?

**Comment by georgejhunt** [comment]
bingo. I can reset interfaces to some reasonable definition for lo, if you
write it all to interfaces.d
Contents of /etc/interfaces.d/iiab

# This file describes the network interfaces available on your system
# and how to activate them. For more information, see interfaces(5).

source /etc/network/interfaces.d/*

# The loopback network interface
auto lo
iface lo inet loopback

# iiab_network_mode is Gateway

#################   GATEWAY   #########################
auto br0
iface br0 inet static
    bridge_ports   eno1
    bridge_maxwait 0
    address 172.18.96.1
    netmask 255.255.224.0
    dns-nameservers 172.18.96.1
 # gui_static_wan_ip is set
auto enxd8eb97bdae2e
iface enxd8eb97bdae2e inet static
    address dhcp
    netmask
    gateway
    dns-nameservers
    dns-search lan

**Comment by jvonau** [comment]
On Sat, Sep 9, 2017 at 8:49 PM, georgejhunt <notifications@github.com>
wrote:

> bingo. I can reset interfaces to some reasonable definition for lo, if you
> write it all to interfaces.d
> Contents of /etc/interfaces.d/iiab
>
> ​Please​

auto enxd8eb97bdae2e
> iface enxd8eb97bdae2e inet static
> address dhcp
> netmask
> gateway
> dns-nameservers
> dns-search lan
>
>
>
​That is what I thought, just pushed =="false Should cleanup iiab

**Comment by georgejhunt** [comment]
Does your push test on a string or a boolean? If string Capitalization
matters.

**Comment by jvonau** [comment]
wan_in_interfaces = True was intended to be a boolean for {% if dhcpcd_result != "enabled" or not wan_in_interfaces %}, so I just used that as a string but in lowercase, {% if dhcpcd_result != "enabled" or wan_in_interfaces =="false" %}

**Comment by jvonau** [comment]
think I need a space in the last change if you have an issue but I'll clean that up anyway

**Comment by jvonau** [comment]
Good data at any rate, established that ubuntu is running dhcpcd out of the box & dhcp in interfaces does not play nice as reported. If this run competes think the need for a reboot to straighten out the network and services should be gone. Now why does is_redhat not work in some places is the question that is going to bug me.

**Comment by tim-moody** [comment]
my suggestion is that redhat and debian/ubuntu are different enough that a top level conditional for separate plays would be more tractable than a bunch of conditionals spread throughout the logic.

**Comment by jvonau** [comment]
Tim: https://github.com/iiab/iiab/search?p=2&q=is_redhat&type=&utf8=%E2%9C%93 lists 17 code result currently in master, but is only failing in some sections including ones that were not changed by this PR.  George: Was this a 'runtags network', iiab-network, or runansible testing?

**Comment by georgejhunt** [comment]
I encounted the problem with runansible. But thereafter, I was doing
iiab-network

**Comment by georgejhunt** [comment]
I put a - debug: var=is_redhat
- pause:
which verified to be false.  When I hit return, it immediately errored out
in ifcfg_mods.yml

**Comment by jvonau** [comment]
> I encounted the problem with runansible.

The first failure for 'dhcp' in /etc/network/interfaces is the original bug, dhcpcd refusing to start when dhcp is present, but can't tell from the lack of posting the failure point. I'll check the 1-vars path in the morning, I see I took out an ignore where I should not of, would fail on first run when not on debian. 
> I put a - debug: var=is_redhat - pause: which verified to be false. When I hit return, it immediately errored out in ifcfg_mods.yml

The detected_network routine can be isolated with 'runtags prep' only 2 of the 8 changes are failing, and I'm not sure why at the moment, I can revert the is_redhat commit but that does not explain the if ifcfg_mods.yml failure on code that was not altered.

**Comment by jvonau** [comment]
> anything in /etc/network/interfaces? 

"post-up systemctl restart dhcpd && systemctl restart hostapd" is in your template for interfaces but not in the file on the filesystem. any ideas?

**Comment by jvonau** [comment]
[grs.txt](https://github.com/iiab/iiab/files/1291451/grs.txt)
> Sep 09 17:58:13 box.lan systemd[1]: dhcpd.service: Failed to load environment files: No such file or directory
Sep 09 17:58:13 box.lan systemd[1]: dhcpd.service: Failed to run 'start' task: No such file or directory

This is a first run situation with dhcpd is noted to fail while the network is restarting noted while poking 10.8.0.6 and as in #171 where I forced the rpi's to use the debian.yml file with is_raspbian_8(Sorry Tim, just had to know what the new raspbian-9 had out of the box). Reason is the "environment files" are supplied later during enabled_services.yml. but are present when rebooted and all is good. Less that ideal but is fixable or liveable.

**Comment by floydianslips** [comment]
-- Logs begin at Thu 2016-11-03 17:16:43 UTC, end at Thu 2017-09-14 00:35:45 UTC. --
Sep 14 00:17:03 box.lan systemd[1]: Starting dhcpcd on all interfaces...
Sep 14 00:17:03 box.lan dhcpcd[385]: Not running dhcpcd because /etc/network/interfaces
Sep 14 00:17:03 box.lan dhcpcd[385]: defines some interfaces that will use a
Sep 14 00:17:03 box.lan dhcpcd[385]: DHCP client or static address
Sep 14 00:17:03 box.lan systemd[1]: dhcpcd.service: Control process exited, code=exited status=6
Sep 14 00:17:03 box.lan systemd[1]: Failed to start dhcpcd on all interfaces.
Sep 14 00:17:03 box.lan systemd[1]: dhcpcd.service: Unit entered failed state.
Sep 14 00:17:03 box.lan systemd[1]: dhcpcd.service: Failed with result 'exit-code'.

**Comment by jvonau** [comment]
> iface enxd8eb97bdae2e 
inet static address dhcp

7029c1a should do it..

**Comment by jvonau** [comment]
Sent on:9:15pm End of run not quite there br0 no ip address dhcpd didn't ... rebooting to see if those are available on reboot, about the the same as what I've seen up till now.. the eth0-dnsmasq handles the transition better..

**Pull request closed without merging**
