### PR TITLE
Kolibri timeout fix: 90 -> 1200 sec (yes, that's 20 minutes!)

### LINKED ISSUE #2555: http://box/kolibri fails with "502 Bad Gateway" (especially when Kolibri 0.14.2 upgraded to 0.14.3 ?) [kolibri.service systemd timeout issue on boot]
I'm opening a separate ticket so we can track this better.  

The problem is not yet well understood, but has occurred on both "RaspiOS with desktop" 2020-08-20 and "Ubuntu Desktop" 20.04.1 &mdash; each running recent IIAB 7.2 pre-releases from Aug/Sept.  Thanks much to @fisherbryan as we diagnose this.

@jvonau summarizes our suspicions so far:

> 502's are service not running or dns like errors, I suspect something like #1932 related, kolibri starts before the database or slow to start with channels present.

> 502's are either dns related or the backend served by nginx failing to start before the timeout, if you see a 502 error please capture the output of `sudo systemctl status kolibri` and `sudo journalctl -b 0 -u kolibri`
>
> I suspect something like #1932 related, kolibri starts before the database or slow to start with channels present.
Additional Ref: #2318

Possibly related:

- #1646 "Migrate IIAB to kolibri-server for RPi performance?"
- #1737 "Who can help test IIAB 7.2 on Ubuntu 20.04+, Debian 10.6, Linux Mint 20 & Raspberry Pi ? [Kolibri 502 Bad Gateway?]"
- #1932 "Kolibri 0.12.8 fails to start on RPi 3 B+ as part of IIAB 7.0"
- #2045 "Kolibri's new 0.12.9 apt/deb package fails to install"
- #2318 "Is Kolibri shutting down cleanly when IIAB powers off?"

### PR DESCRIPTION
**Pull request by holta**
Fixes #2555 "http://box/kolibri fails with "502 Bad Gateway" (especially when Kolibri 0.14.2 upgraded to 0.14.3 ?)"

I tested 1000 seconds (16min40sec) as Kolibri took 9 minutes to start on a Raspberry Pi with 1GB RAM, which worked.

@jvonau suggested bumping this up to 20min so why not, let's go with that.

`TimeoutStartSec=infinity` is another option...but that seemed a bit much ;)

Revises:

- PR #2343 "Comment out both kolibri.service timeout settings"

Refs:

- #1737 "Who can help test IIAB 7.2 on Ubuntu 20.04+, Debian 10.6, Linux Mint 20 & Raspberry Pi ? [Kolibri 502 Bad Gateway?]"
- #2318 "Is Kolibri shutting down cleanly when IIAB powers off?"

### CODE REVIEW

**Comment by fisherbryan** [comment]
@holta I checked this:
d /opt/iiab/iiab
sudo git pull    # if you want to try the latest IIAB 7.2 pre-release
sudo ./runrole --reinstall kolibri    # (re)install Kolibri 0.14.3 
Results below is whithout reboot, after running the above suggestion.

'kolibri status' command shows "Stopped(1)"

Screenshot from 2020-10-05 22-03-13

Kolibri then shows up on url: http://172.18.0.130/kolibri/ but not on ip/8009 ( I see yo change the port from 8080)
In the above screenshot you will also see two process ID's for kolibri. In my case this instance of kolibri, in screenshot is not the one that I have setup because I cant login with the account that i setup from the setup page:
Screenshot from 2020-10-05 22-14-04

**Comment by holta** [comment]
@fisherbryan 

Since you reinstalled Kolibri, does the universal default login work at http://box/kolibri ?  (Where box is whatever you've arranged!)

username: Admin
password: changeme

**Comment by fisherbryan** [comment]
@holta no, and my server is http://sib.content/kolibri (i get an error that says: "This site can’t be reached") it just gives the impression that it is logging in for a second then comes back to the login screen. Have a look:
https://drive.google.com/file/d/1pFkT1Y-CS8cg83HMzR0EE20yfP7xyHXA/view?usp=sharing

**Comment by holta** [comment]
@fisherbryan it's possible reinstalling Kolibri 0.14.3 on top of Kolibri 0.14.2 creates one big mess :/

While it appears my reinstalling Kolibri 0.14.3 on top of 0.14.3 (same version!) appeared to work (?) still I'd ask you to instead play it safe — until we understand Kolibri at a deeper level...

i.e. please do one of 2 things:

1) Install Kolibri with IIAB on a _completely clean OS._

or...

2) Delete absolutely *ALL* traces of Kolibri (database, /etc residue, /library/Kolibri, etc) before attempting to reinstall Kolibri.

**Comment by jvonau** [comment]
>  http://sib.content/kolibri (i get an error that says: "This site can’t be reached")

From the client you are connecting from can you `ping sib.content` and that resolves to 172.18.0.130?

**Comment by holta** [comment]
We're getting quite far off topic here, but just fyi I get this error when trying to do a DNS lookup on sib.content :

```
Sorry, we couldn't find any name servers for 'sib.content'

**Comment by jvonau** [comment]
> We're getting quite far off topic here, but just fyi I get this error when trying to do a DNS lookup on sib.content :
> 
> ```
> Sorry, we couldn't find any name servers for 'sib.content'
> ```

No we are not, and you should get an error, where as the other network should resolve if that is the intended layout as the IIAB machine is being accessed from the WAN port and the WAN network's dns-server's responsibility to resolve that address as the IIAB machine is a guest appliance on the WAN network. Think the real question is why the url that was accessed at 172... is being swapped with sib.content in the request if that is what is going on, but I'll note the 'Admin' and 'admin' usage.

**Comment by fisherbryan** [comment]
@AHolt, Kolibri does not like to downgrade, at all it does create a mess
yes. Kolibri's default port uses 8080, if you change it, you have to use
the optiins.ini file.

I use kolibri primarily on all our servers with kolibri-server and nginx
installed as our content server.

159.65.196.188:8080 this is my cloud instance of kolibri. Upon install
(kolibri) the user ie, admin should have ownership of the kolibri instance.

When you say, "install kolibri with iiab on a completely clean os". Doe you
mean with the ./runrole command or after installing iiab successfully then
install kolibri sperately with a .deb file?

I'd rather not go with option 2, I have had many issues in the past
uninstalling and deleting all traces of kolibri and trying to install it
again. The best way is to start with a clean OS.

**Comment by fisherbryan** [comment]
It's a standalone machine I'm using for testing :) so you won't find it :)

**Comment by fisherbryan** [comment]
@Jerry, agreed.

**Comment by holta** [comment]
> When you say, "install kolibri with iiab on a completely clean os". Doe you
mean with the ./runrole command or after installing iiab successfully then
install kolibri sperately with a .deb file?

Neither.

Make sure these are set in `/etc/iiab/local_vars.yml` before you install IIAB:

```
kolibri_install: True
kolibri_enabled: True
```

Then install IIAB.  Which typically means run: `sudo iiab`

ASIDE: `./runrole kolibri` is a tinkerers' tool, not intended for the general public, but yes you can consider that if you forgot to install Kolibri during your IIAB install.

**Comment by jvonau** [comment]
> When you say, "install kolibri with iiab on a completely clean os". Doe you mean with the ./runrole command or after installing iiab successfully then install kolibri sperately with a .deb file? I'd rather not go with option 2, I have had many issues in the past uninstalling and deleting all traces of kolibri and trying to install it again. The best way is to start with a clean OS.

It's been awhile since kolibri was tested in isolation with nothing else, someone might of missed some dependency somewhere. With the clean OS installed setup local_vars.yml with kolibri being the only option to be installed|enabled before continuing 'iiab'.

**Comment by fisherbryan** [comment]
@holta please see result of fresh iiab install on clean OS: The original IIAB, no changes to .yaml file.
http://sprunge.us/1abpvY

Kolibri_True
iiab_success

Kolibri - Working (no user intervention - Will confirm how long it takes after reboot) -  
global username and password: username: Admin | password: changeme
Importing two different channel information (no the complete channel only selected one resource in a channel)
kolibri_channel_import

Moodle:
moodle

Nextcloud:
nextcloud

Wordpress:
wordpress

Welldone guys! Absolutely great job!! You guys are fantastically awesome! :-D

**Comment by fisherbryan** [comment]
FYI: don't think kolibri is running properly. Kolibri was originally installed to run as the user 'kolibri', the output of the information ie; 
Oct 06 06:41:36 box.lan kolibri[659]:         http://172.18.0.148:8009/
Oct 06 06:41:36 box.lan kolibri[659]:         http://172.18.96.1:8009/
Oct 06 06:41:36 box.lan kolibri[659]:         http://127.0.0.1:8009/
These would give you this output on the browser: if you using the ip/port address:
Screenshot from 2020-10-06 16-29-19

terminal view:
Screenshot from 2020-10-06 16-21-59

**Comment by jvonau** [comment]
Why would one want to go direct to the port 8009 and negate the benefits of nginx's better connection logging, cache and cookie management? 

I see the same responses here with FF, what you witnessed is just nginx's 'default_server' behavior and current browser behavior, the port is used only if the http(s):// part of the request from the web browser doesn't receive a response, then the browser proceeds to the port. Don't think your cloud instance is completely configured either /kolibri doesn't work while hitting the port does but that would not be through nginx, not testing the full stack Once you complete the install with a resolvable domain name think you will find the same behavior there also.

**Comment by fisherbryan** [comment]
@jvonau Indeed. In favor of nginx. Yes, I still have to properly configure my cloud instance properly, in due time.

**Pull request merged**
