### PR TITLE
Lok user

### PR DESCRIPTION
**Pull request by jvonau**
continues #2789 alternate to #2790

### CODE REVIEW

**Comment by jvonau** [comment]
@adamsclafani This is looking better,  OPWEN_SIM_TYPE='{{ lokole_sim_type }}' is still being respected via the settings.env file, think we can have webapp_secrets.sh go away  but:
```
ubuntu@box:~$ sudo journalctl -b0 --no-pager -u lokole_restarter.service 
-- Logs begin at Mon 2021-02-22 18:31:56 CST, end at Thu 2021-05-20 18:04:37 CDT. --
May 20 18:01:41 box.lan systemd[1]: Started Lokole webapp restarter.
May 20 18:01:55 box.lan webapp-restart.sh[1034]: Exception in thread Thread-1:
May 20 18:01:55 box.lan webapp-restart.sh[1034]: Traceback (most recent call last):
May 20 18:01:55 box.lan webapp-restart.sh[1034]:   File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
May 20 18:01:55 box.lan webapp-restart.sh[1034]:     self.run()
May 20 18:01:55 box.lan webapp-restart.sh[1034]:   File "/library/lokole/venv/lib/python3.8/site-packages/watchdog/observers/api.py", line 203, in run
May 20 18:01:55 box.lan webapp-restart.sh[1034]:     self.dispatch_events(self.event_queue, self.timeout)
May 20 18:01:55 box.lan webapp-restart.sh[1034]:   File "/library/lokole/venv/lib/python3.8/site-packages/watchdog/observers/api.py", line 376, in dispatch_events
May 20 18:01:55 box.lan webapp-restart.sh[1034]:     handler.dispatch(event)
May 20 18:01:55 box.lan webapp-restart.sh[1034]:   File "/library/lokole/venv/lib/python3.8/site-packages/watchdog/events.py", line 331, in dispatch
May 20 18:01:55 box.lan webapp-restart.sh[1034]:     {
May 20 18:01:55 box.lan webapp-restart.sh[1034]:   File "/library/lokole/venv/bin/manage.py", line 47, in on_created
May 20 18:01:55 box.lan webapp-restart.sh[1034]:     restart()
May 20 18:01:55 box.lan webapp-restart.sh[1034]:   File "/library/lokole/venv/lib/python3.8/site-packages/opwen_email_client/webapp/actions.py", line 124, in __call__
May 20 18:01:55 box.lan webapp-restart.sh[1034]:     check_call(['supervisorctl', 'signal', signal, component_name])
May 20 18:01:55 box.lan webapp-restart.sh[1034]:   File "/usr/lib/python3.8/subprocess.py", line 359, in check_call
May 20 18:01:55 box.lan webapp-restart.sh[1034]:     retcode = call(*popenargs, **kwargs)
May 20 18:01:55 box.lan webapp-restart.sh[1034]:   File "/usr/lib/python3.8/subprocess.py", line 340, in call
May 20 18:01:55 box.lan webapp-restart.sh[1034]:     with Popen(*popenargs, **kwargs) as p:
May 20 18:01:55 box.lan webapp-restart.sh[1034]:   File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
May 20 18:01:55 box.lan webapp-restart.sh[1034]:     self._execute_child(args, executable, preexec_fn, close_fds,
May 20 18:01:55 box.lan webapp-restart.sh[1034]:   File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
May 20 18:01:55 box.lan webapp-restart.sh[1034]:     raise child_exception_type(errno_num, err_msg, err_filename)
May 20 18:01:55 box.lan webapp-restart.sh[1034]: FileNotFoundError: [Errno 2] No such file or directory: 'supervisorctl'
```
We would have to use systemd to bounce the service, the app isn't running under supervisord now.

**Comment by jvonau** [comment]
manage.py
```
def resetdb():
    remove(AppConfig.LOCAL_EMAIL_STORE)
    remove(AppConfig.SQLITE_PATH)
email = '{}@{}'.format(name, AppConfig.CLIENT_EMAIL_HOST)
```

**Comment by jvonau** [comment]
@adamsclafani Just after Admin logs in for the first time shouldn't there be an [auto redirect](https://github.com/ascoderu/lokole/blob/master/opwen_email_client/webapp/views.py#L470-L473) to the Site Registration Form?
> On another note, the server is indeed returning a successful 201 created status code, not 200 (which is what the check assumed). Fired up a python interpreter session and made a quick script to register the client hawaii10.

Lets look at putting a WIP PR upstream, I'll make the hand change for now.

**Comment by jvonau** [comment]
Logs are being created now. Same as before after the 200 -> 201 hand change.
`cat /home/lokole/log/*.log`
``` 
[2021-05-20 23:03:37,972: INFO/MainProcess] beat: Starting...
[2021-05-20 23:03:35,649: INFO/MainProcess] Connected to sqlalchemy+sqlite:////home/lokole/state/celery.sqlite3
[2021-05-20 23:03:36,135: INFO/MainProcess] celery@box.lan ready.
[2021-05-20 23:05:55,619: INFO/MainProcess] Received task: opwen_email_client.webapp.tasks.register[671f5419-789f-4d48-86c2-2b7f8140e5c2]  
[2021-05-20 23:06:07,392: ERROR/ForkPoolWorker-1] Task opwen_email_client.webapp.tasks.register[671f5419-789f-4d48-86c2-2b7f8140e5c2] raised unexpected: AttributeError("'ClientRegister' object has no attribute 'client_name'")
Traceback (most recent call last):
  File "/library/lokole/venv/lib/python3.8/site-packages/celery/app/trace.py", line 412, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/library/lokole/venv/lib/python3.8/site-packages/celery/app/trace.py", line 704, in __protected_call__
    return self.run(*args, **kwargs)
  File "/library/lokole/venv/lib/python3.8/site-packages/opwen_email_client/webapp/tasks.py", line 91, in register
    client_register()
  File "/library/lokole/venv/lib/python3.8/site-packages/opwen_email_client/webapp/actions.py", line 296, in __call__
    opwen_settings = self._format_settings()
  File "/library/lokole/venv/lib/python3.8/site-packages/opwen_email_client/webapp/actions.py", line 266, in _format_settings
    'OPWEN_CLIENT_NAME': self.client_name.data.strip(),
AttributeError: 'ClientRegister' object has no attribute 'client_name'
```
`sudo journalctl -b0 --no-pager -u lokole_restarter.service` no extra logging for this one yet.
```
May 20 23:04:37 box.lan webapp-restart.sh[28271]: Exception in thread Thread-1:
May 20 23:04:37 box.lan webapp-restart.sh[28271]: Traceback (most recent call last):
May 20 23:04:37 box.lan webapp-restart.sh[28271]:   File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
May 20 23:04:37 box.lan webapp-restart.sh[28271]:     self.run()
May 20 23:04:37 box.lan webapp-restart.sh[28271]:   File "/library/lokole/venv/lib/python3.8/site-packages/watchdog/observers/api.py", line 203, in run
May 20 23:04:37 box.lan webapp-restart.sh[28271]:     self.dispatch_events(self.event_queue, self.timeout)
May 20 23:04:37 box.lan webapp-restart.sh[28271]:   File "/library/lokole/venv/lib/python3.8/site-packages/watchdog/observers/api.py", line 376, in dispatch_events
May 20 23:04:37 box.lan webapp-restart.sh[28271]:     handler.dispatch(event)
May 20 23:04:37 box.lan webapp-restart.sh[28271]:   File "/library/lokole/venv/lib/python3.8/site-packages/watchdog/events.py", line 331, in dispatch
May 20 23:04:37 box.lan webapp-restart.sh[28271]:     {
May 20 23:04:37 box.lan webapp-restart.sh[28271]:   File "/library/lokole/venv/bin/manage.py", line 47, in on_created
May 20 23:04:37 box.lan webapp-restart.sh[28271]:     restart()
May 20 23:04:37 box.lan webapp-restart.sh[28271]:   File "/library/lokole/venv/lib/python3.8/site-packages/opwen_email_client/webapp/actions.py", line 121, in __call__
May 20 23:04:37 box.lan webapp-restart.sh[28271]:     signal = path.read_text(encoding='ascii').strip()
May 20 23:04:37 box.lan webapp-restart.sh[28271]:   File "/usr/lib/python3.8/pathlib.py", line 1236, in read_text
May 20 23:04:37 box.lan webapp-restart.sh[28271]:     return f.read()
May 20 23:04:37 box.lan webapp-restart.sh[28271]:   File "/usr/lib/python3.8/encodings/ascii.py", line 26, in decode
May 20 23:04:37 box.lan webapp-restart.sh[28271]:     return codecs.ascii_decode(input, self.errors)[0]
May 20 23:04:37 box.lan webapp-restart.sh[28271]: UnicodeDecodeError: 'ascii' codec can't decode byte 0x9f in position 522: ordinal not in range(128)
```

**Comment by jvonau** [comment]
@holta @nzola test email sent to victest1, confirm email received from vonau-test2@last3-iiab-2792.lokole.ca should have attachment

**Comment by holta** [comment]
> @holta @nzola test email sent to victest1, confirm email received from [vonau-test2@last3-iiab-2792.lokole.ca](mailto:vonau-test2@last3-iiab-2792.lokole.ca) should have attachment

Gmail does not show any attachment, as part of the email received 5:01 AM (EDT).

If however you do Vertical Ellipsis > "Show original" the payload of the email appears as:

```
attachment <br><img src=3D"https://u20817868.ct.sendgrid.net/wf/open?upn=3D=
VX6A-2Bc-2B4nqHcQJjISP1WB6gLj2J77BwJe2bzU500c2cfkRyAcimQXOtsR46mLN0kOESZuTB=
-2FwRXTD0F1ZfsJAYp5hyblSocgx2pXDuPoV-2FoFEidJcDgB67k1HqvzVXR-2Fo4iLkG5qiQrK=
QPOmMUvx5n5TtkRqpdzd4gX6kSnR9ohUJfveLn0AMSO6agh7jV6FHkxfR-2BQU29DHT0fCY-2Bj=
tudbEMBgVmr2Yqu1BxGYuYqg-3D" alt=3D"" width=3D"1" height=3D"1" border=3D"0"=
 style=3D"height:1px !important;width:1px !important;border-width:0 !import=
ant;margin-top:0 !important;margin-bottom:0 !important;margin-right:0 !impo=
rtant;margin-left:0 !important;padding-top:0 !important;padding-bottom:0 !i=
mportant;padding-right:0 !important;padding-left:0 !important;"/>
```

**Comment by jvonau** [comment]
```
worker_1  | [2021-05-21 08:46:19,672: CRITICAL/ForkPoolWorker-1] IndexSentEmailForMailbox(args=('acdde7a8-4fae-4ff3-916f-e9eea121dd8b',), kwargs={}) (KeyError('sent_at'))
worker_1  | [2021-05-21 08:46:19,718: CRITICAL/ForkPoolWorker-5] IndexReceivedEmailForMailbox(args=('acdde7a8-4fae-4ff3-916f-e9eea121dd8b',), kwargs={}) (KeyError('sent_at'))
worker_1  | [2021-05-21 09:01:13,026: CRITICAL/ForkPoolWorker-4] IndexReceivedEmailForMailbox(args=('4863179d-1ca4-4d53-b686-25027ec1bd9a',), kwargs={}) (KeyError('sent_at'))
worker_1  | [2021-05-21 09:01:13,064: CRITICAL/ForkPoolWorker-2] IndexSentEmailForMailbox(args=('4863179d-1ca4-4d53-b686-25027ec1bd9a',), kwargs={}) (KeyError('sent_at'))
worker_1  | [2021-05-21 09:46:23,948: CRITICAL/ForkPoolWorker-5] IndexReceivedEmailForMailbox(args=('a2588614-7aaa-4e4d-8090-cb68e948f116',), kwargs={}) (KeyError('sent_at'))
worker_1  | [2021-05-21 09:46:23,964: CRITICAL/ForkPoolWorker-3] IndexSentEmailForMailbox(args=('a2588614-7aaa-4e4d-8090-cb68e948f116',), kwargs={}) (KeyError('sent_at'))
worker_1  | [2021-05-21 10:01:29,126: CRITICAL/ForkPoolWorker-5] IndexReceivedEmailForMailbox(args=('6abfa86a-2081-4de4-a228-7c974ebea8cb',), kwargs={}) (KeyError('sent_at'))
worker_1  | [2021-05-21 10:01:29,148: CRITICAL/ForkPoolWorker-3] IndexSentEmailForMailbox(args=('6abfa86a-2081-4de4-a228-7c974ebea8cb',), kwargs={}) (KeyError('sent_at'))
```

**Comment by jvonau** [comment]
```
worker_1  | [2021-05-21 18:16:26,109: CRITICAL/ForkPoolWorker-3] error sending email 45856551-8188-4803-ba85-6f54d8f7e24e:{'from': {'e
mail': 'nzola-victest1@lokole.ca'}, 'subject': 'Attach May 21/21', 'personalizations': [{'to': [{'email': 'nzola1@yahoo.ca'}], 'cc': [{'email
': 'nzola1@yahoo.ca'}]}], 'content': [{'type': 'text/html', 'value': 'Attach'}], 'attachments': [{'content': 'UEsDBBQABgAIAAAAIQDKY8bCpgEAAO4
GAAATAAgCW0NvbnRlbnRfVHlwZXNdLnhtbCCiBAIooAACAAAAAAAAAAA

'filename': 'Congolese Author.docx', 'disposition': 'attachment', 'content_id': 'Congolese Author.docx'}], 'reply_to': {'email': 'nzola@victest1.lokole.ca'}}:[{'message': 'Each email address in the personalization block should be unique between to, cc, and bcc. We found the first duplicate instance of [nzola1@yahoo.ca] in the personalizations.0.cc field.', 'field': 'personalizations.0', 'help': 'http://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/errors.html#message.recipient-errors'}] (BadRequestsError(<HTTPError 400: 'Bad Request'>))
```

**Comment by adamsclafani** [comment]
Yes, a redirect to the registration page was supposed to happen. Unfortunately the redirect wasn't happening for some reason. I'll definitely fix that. I figured it wasn't the highest priority to so I kind of put it on the back burner

**Comment by adamsclafani** [comment]
Those logs are perfect. Changing to 201 did fix the initial problem. The errors we are seeing now are from the second part of the registration process which was never executed before due to whole 200/201 check not passing. 

@jvonau did you by any chance bypass the [setup path](https://github.com/ascoderu/lokole/blob/aa7ac119361d425e4e9f28a7c85e3002e9252855/opwen_email_client/webapp/forms/register.py#L42) routine as [discussed](https://github.com/iiab/iiab/pull/2789#issuecomment-844546159) when running to produce [these](https://github.com/iiab/iiab/pull/2792#issuecomment-845683439) logs?

**Comment by jvonau** [comment]
> Those logs are perfect. Changing to 201 did fix the initial problem. The errors we are seeing now are from the second part of the registration process which was never executed before due to whole 200/201 check not passing.
>

Agreed, 
> @jvonau did you by any chance bypass the [setup path](https://github.com/ascoderu/lokole/blob/aa7ac119361d425e4e9f28a7c85e3002e9252855/opwen_email_client/webapp/forms/register.py#L42) routine as [discussed](https://github.com/iiab/iiab/pull/2789#issuecomment-844546159) when running to produce [these](https://github.com/iiab/iiab/pull/2792#issuecomment-845683439) logs?

A hand change to 201 and OPWEN_SETTINGS='{{ lokole_run_directory }}/settings.env defined got me to ['supervisorctl'](https://github.com/iiab/iiab/pull/2792#issuecomment-845540012) but the 'client_name' error is still present with the servers returned info not written. Adding the missing client_id(returned_key from server) client_name(subdomain) with the account info to settings.env resulted in my last3-iiab-2792 coming alive to create new users and send/receive email.

Side note, what we need to avoid is turning on celerybeat on non-registered machines, those spam the server with none.lokole.ca as per the schedule.

**Comment by jvonau** [comment]
818defab5f768e49873df76a30c653b21dc7ac6e cat ~/lok_status.txt
● lokole_restarter.service - Lokole webapp restarter
     Loaded: loaded (/etc/systemd/system/lokole_restarter.service; enabled; vendor preset: enabled)
     Active: active (running) since Sun 2021-05-23 14:18:12 UTC; 4min 50s ago
   Main PID: 28017 (sh)
      Tasks: 5 (limit: 4431)
     Memory: 53.5M
     CGroup: /system.slice/lokole_restarter.service
             ├─28017 sh /home/lokole/state/webapp-restart.sh
             └─28021 /library/lokole/venv/bin/python3 /library/lokole/venv/bin/manage.py restarter --directory=/home/lokole/state

May 23 14:18:12 box.lan systemd[1]: Started Lokole webapp restarter.

● lokole.service - Provides the Lokole Server
     Loaded: loaded (/etc/systemd/system/lokole.service; enabled; vendor preset: enabled)
     Active: active (running) since Sun 2021-05-23 14:18:02 UTC; 4min 59s ago
   Main PID: 27856 (sh)
      Tasks: 6 (limit: 4431)
     Memory: 211.6M
     CGroup: /system.slice/lokole.service
             ├─27856 sh /home/lokole/state/webapp.sh
             ├─27857 /library/lokole/venv/bin/python3 /library/lokole/venv/bin/gunicorn --timeout=300 --workers=4 --bind=unix:/home/lokole/state/lokole_gunicorn.sock --log-file=/home/lokole/log/LOKOLE.log --log-level=error opwen_email_client.webapp:app
             ├─27883 /library/lokole/venv/bin/python3 /library/lokole/venv/bin/gunicorn --timeout=300 --workers=4 --bind=unix:/home/lokole/state/lokole_gunicorn.sock --log-file=/home/lokole/log/LOKOLE.log --log-level=error opwen_email_client.webapp:app
             ├─27884 /library/lokole/venv/bin/python3 /library/lokole/venv/bin/gunicorn --timeout=300 --workers=4 --bind=unix:/home/lokole/state/lokole_gunicorn.sock --log-file=/home/lokole/log/LOKOLE.log --log-level=error opwen_email_client.webapp:app
             ├─27885 /library/lokole/venv/bin/python3 /library/lokole/venv/bin/gunicorn --timeout=300 --workers=4 --bind=unix:/home/lokole/state/lokole_gunicorn.sock --log-file=/home/lokole/log/LOKOLE.log --log-level=error opwen_email_client.webapp:app
             └─27886 /library/lokole/venv/bin/python3 /library/lokole/venv/bin/gunicorn --timeout=300 --workers=4 --bind=unix:/home/lokole/state/lokole_gunicorn.sock --log-file=/home/lokole/log/LOKOLE.log --log-level=error opwen_email_client.webapp:app

May 23 14:18:02 box.lan systemd[1]: Started Provides the Lokole Server.
● celerybeat.service - Celery beat timed service
     Loaded: loaded (/etc/systemd/system/celerybeat.service; enabled; vendor preset: enabled)
     Active: active (running) since Sun 2021-05-23 14:18:08 UTC; 5min ago
   Main PID: 27948 (sh)
      Tasks: 2 (limit: 4431)
     Memory: 56.2M
     CGroup: /system.slice/celerybeat.service
             ├─27948 sh /home/lokole/state/celerybeat.sh
             └─27949 /library/lokole/venv/bin/python3 /library/lokole/venv/bin/celery --app=opwen_email_client.webapp.tasks beat --pidfile=/home/lokole/state/CELERY_BEAT.pid --logfile=/home/lokole/log/CELERY_BEAT.log --loglevel=info

May 23 14:18:08 box.lan systemd[1]: Started Celery beat timed service.

● celery.service - Celery service
     Loaded: loaded (/etc/systemd/system/celery.service; enabled; vendor preset: enabled)
     Active: active (running) since Sun 2021-05-23 14:18:04 UTC; 5min ago
   Main PID: 27890 (sh)
      Tasks: 8 (limit: 4431)
     Memory: 85.6M
     CGroup: /system.slice/celery.service
             ├─27890 sh /home/lokole/state/run-celery.sh
             ├─27891 /library/lokole/venv/bin/python3 /library/lokole/venv/bin/celery --app=opwen_email_client.webapp.tasks worker --pidfile=/home/lokole/state/CELERY_WORKER.pid --logfile=/home/lokole/log/CELERY_WORKER.log --loglevel=info --concurrency=2
             ├─27972 /library/lokole/venv/bin/python3 /library/lokole/venv/bin/celery --app=opwen_email_client.webapp.tasks worker --pidfile=/home/lokole/state/CELERY_WORKER.pid --logfile=/home/lokole/log/CELERY_WORKER.log --loglevel=info --concurrency=2
             └─27973 /library/lokole/venv/bin/python3 /library/lokole/venv/bin/celery --app=opwen_email_client.webapp.tasks worker --pidfile=/home/lokole/state/CELERY_WORKER.pid --logfile=/home/lokole/log/CELERY_WORKER.log --loglevel=info --concurrency=2

May 23 14:18:04 box.lan systemd[1]: Started Celery service.

**Comment by jvonau** [comment]
https://github.com/ascoderu/lokole/blob/master/opwen_email_client/webapp/actions.py#L271-L275 made this change
```
   def _write_settings_to_file(self, client_values):
        client_values_list = ['{}={}'.format(key, value) for (key, value) in client_values.items()]

        with open(self._settings_path, 'w') as fobj:
            fobj.write('\n'.join(client_values_list))
```
```
OPWEN_CLIENT_NAME': self._client_name,
```
along with the 201 fix and adding SECRET_KEY to settings.env gives me
```
OPWEN_SESSION_KEY=sEs0Br4K39w8xoC3QvJ7ahHqAo2mzXbd
OPWEN_CLIENT_NAME=ubuntujv12
OPWEN_RESTART_PATH=
OPWEN_CLIENT_ID=edit
OPWEN_REMOTE_ACCOUNT_NAME=edit
OPWEN_REMOTE_ACCOUNT_KEY=edit
OPWEN_REMOTE_RESOURCE_CONTAINER=compressedpackages
```

**Comment by jvonau** [comment]
```
ubuntu@ubuntu:~/git/lokole$ git diff master 
diff --git a/opwen_email_client/webapp/actions.py b/opwen_email_client/webapp/actions.py
index bd940ef..a99baca 100644
--- a/opwen_email_client/webapp/actions.py
+++ b/opwen_email_client/webapp/actions.py
@@ -263,7 +263,7 @@ class ClientRegister(object):
             'OPWEN_MAX_UPLOAD_SIZE_MB': AppConfig.MAX_UPLOAD_SIZE_MB,
             'OPWEN_SIM_TYPE': AppConfig.SIM_TYPE,
             'OPWEN_EMAIL_SERVER_HOSTNAME': self.server_endpoint,
-            'OPWEN_CLIENT_NAME': self.client_name.data.strip(),
+            'OPWEN_CLIENT_NAME': self._client_name,
             'OPWEN_ROOT_DOMAIN': root_domain,
             'OPWEN_RESTART_PATH': restart_path,
         }
@@ -271,7 +271,7 @@ class ClientRegister(object):
     def _write_settings_to_file(self, client_values):
         client_values_list = ['{}={}'.format(key, value) for (key, value) in client_values.items()]
 
-        with open(self._path, 'w') as fobj:
+        with open(self._settings_path, 'w') as fobj:
             fobj.write('\n'.join(client_values_list))
 
     def __call__(self):
diff --git a/opwen_email_client/webapp/forms/register.py b/opwen_email_client/webapp/forms/register.py
index 5693922..f504369 100644
--- a/opwen_email_client/webapp/forms/register.py
+++ b/opwen_email_client/webapp/forms/register.py
@@ -35,7 +35,7 @@ class RegisterForm(FlaskForm):
         response = post(client_create_url,
                         json={'domain': client_domain},
                         headers={'Authorization': 'Bearer {}'.format(token)})
-        if response.status_code != 200:
+        if response.status_code != 201:
             raise ValidationError(i8n.FAILED_REGISTRATION)
         register.delay(name, token, path)
```

**Pull request closed without merging**
