### PR TITLE
changes to move admin console to its own repo

### PR DESCRIPTION
**Pull request by tim-moody**

### CODE REVIEW

**Comment by tim-moody** [comment]
passed smoke test on debian vm and raspbian
found and fixed a couple of functional bugs

**Comment by tim-moody** [comment]
smoke test on ubuntu fails because of zmq php binding

**Comment by tim-moody** [comment]
passed smoke test again on debian vm and raspbian except that sugarizer failed to untar on rpi

**Comment by tim-moody** [comment]
passes smoke test on cents 7.3

**Comment by jvonau** [comment]
Are you going to prepare a PR for this change on XSCE/xsce also?

**Comment by tim-moody** [comment]
wasn't planning to. would require back porting a lot of soft coding.

**Pull request merged**
