### PR TITLE
Home page [NGINX should preserve box.lan etc, instead of redirecting to 172.18.96.1]

### PR DESCRIPTION
**Pull request by jvonau**
### Fixes Bug
#2067 correct rewrite with ip addresses in browser's address bar. 
### Description of changes proposed in this pull request.
consolidate modules.conf usb-lib.conf into iiab.conf.j2,  restore iiab_home_url,

### CODE REVIEW

**Comment by georgejhunt** [comment]
Seems reasonable. There is no comment in the PR about whether it passes smoke test, and functions.

**Comment by tim-moody** [comment]
I prefer
location = / {
        return 301 {{ iiab_home_url }};
    }

**Comment by holta** [comment]
Prior to our 11AM EST call tmrw [ Thursday, http://minutes.iiab.io ] what next steps are needed here?

Tangentially related: PR #2066

**Comment by holta** [comment]
> I prefer
> location = / {
> return 301 {{ iiab_home_url }};
> }

1) Today's call (http://minutes.iiab.io) consensus is that the above [redirect instead of rewrite] is a good idea (though possibly to merged after this PR #2068?)

2) @tim-moody suspects the rewrite might be a redirect behind the scenes anyway.

**Comment by holta** [comment]
@jvonau tested this over WiFi [LAN] on Raspbian (does the right thing over WAN, and over tunnel/VPN [which is neither WAN not LAN]).

Aside: iptables does not affect tunnel/VPN.

**Comment by holta** [comment]
@jvonau this looks like a possible glitch in PR #2068 here, as merged this morning... 161-u19-srv-BIG-1219 = http://10.8.0.42 redirects to http://10.8.0.42//home/

Likewise http://192.168.0.161 redirects to http://192.168.0.161//home/

Can you tell why?

[Posted to #2073]

**Pull request merged**
