### PR TITLE
remove quotes

### PR DESCRIPTION
**Pull request by jvonau**
### Fixes Bug
#2276
quote part of #1965

### CODE REVIEW

**Comment by holta** [comment]
How safe is this PR?

(Any specific/quick tests that should be fun [run] before this is merged?)

**Comment by holta** [comment]
I just tried this PR on an offline RPi 3 B+ &mdash; for some reason it continues with the old/erroneous behaviore &mdash; putting double quotes into /etc/dhcpcd.conf within this line:

```
interface "eth0"
```

If it helps to debug where this is going wrong, I'd attached the last 975 lines of the offline machine's /etc/iiab/iiab/iiab-network.log here:

https://paste.ubuntu.com/p/rwbDjzzNXs/

**Comment by jvonau** [comment]
would like to see /etc/iiab/iiab.env also

**Comment by holta** [comment]
I forgot that this implements "fallback" to a Static/Fixed IP Address on eth0, which requires an Ethernet cable plugged in, with link-light etc.

We should state this more strongly in http://FAQ.IIAB.IO -> "22 How do I set a static IP address?"

In any case, this PR appears to be correct for new installs &mdash; so that eth0 falls back to the Fixed IP (as set in /etc/dhcpcd.conf) after about 30 to 45 seconds.

**Comment by holta** [comment]
Tested on Raspbian Desktop 2020-02-13.

**Comment by holta** [comment]
> We should state this more strongly in http://FAQ.IIAB.IO -> "22 How do I set a static IP address?"

Done!

**Pull request merged**
