### PR TITLE
Map redirect [for http://box/maps to show the latest, OSM]

### PR DESCRIPTION
**Pull request by georgejhunt**
redirect http://box.lan/maps to the most recently installed map region

### CODE REVIEW

**Comment by holta** [comment]
To fulfill #1496

**Comment by holta** [comment]
@georgejhunt @tim-moody can this be made to work today or tmrw prior to IIAB 7.0 Preview 1?

To fulfill #1496

**Comment by tim-moody** [comment]
Not sure what this is for. For zims if none is installed we add a generic menu item to the home page otherwise we add a menu item for each installed zim.

**Comment by holta** [comment]
http://box/maps should attempt to display the most recently installed Map Pack, or Map Packs, as is achievable/appropriate.

(Does this PR come close enough to achieving that, i.e. is it almost ready to merge?)

**Comment by holta** [comment]
@georgejhunt please let us know in the coming ~24h or so, if this is sufficiently tested for IIAB 7.0 Preview 1 ?

**Comment by georgejhunt** [comment]
yes, it has been tested

**Pull request merged**
