### PR TITLE
@m-anish plz help us come to a decision to get Nextcloud's php-* dependencies in place [non-php pkgs might also be added/removed?]

### PR DESCRIPTION
**Pull request by holta**
Builds on PRs #2219, #2255 given @jvonau's research under https://github.com/iiab/iiab/pull/2255#pullrequestreview-359486407

cc: @m-anish 

Background: https://docs.nextcloud.com/server/18/admin_manual/installation/source_installation.html#prerequisites-for-manual-installation

### CODE REVIEW

**Comment by jvonau** [comment]
no... php-mysql  pulls in the correct dependencies for common
yes php-xml

**Comment by holta** [comment]
@jvonau I'm trying to understand:

@m-anish has included `php-common` as it might help the situation on some OS's ...but in the end are you saying `php-common` should definitely not be included in this list here?

**Comment by jvonau** [comment]
If you were to include php-common it might generate the same type of 'is a virtual package provided by:' error as the real package is php7.3-common that provides the virtual php-common package. As noted php-mysql correctly pulls in php7.3-mysql and php7.3-common which provides php-common.  edit: Tried the apt install php-common test that looks like it would work right.

Any real reason you expanded the apt list from #2119 to include those other 8-9 problem virtual packages? Did you even try that list as provided or did you go straight to misunderstanding that some of those modules listed in prerequisites-for-manual-installation were modules at one point but that are now included in and provided by a different module, be it common, xml or some other package?

**Comment by holta** [comment]
Whatever our best-guesstimate as to what field communities likely (might) want for Nextcloud 19, 20, etc in the future should be fine for now.  This is likely a moving target after all.

e.g. @m-anish was very forthcoming explaining that his [list of Nextcloud prereq+associated packages](https://github.com/m-anish/iiab/blob/nextcloud/roles/nextcloud/tasks/install.yml#L5-L22) ...which contains extras & at least 1 duplicate ...may work on Ubuntu 19.10 today, but not necessarily elsewhere!

I'm sure Anish can add some suggestions here when he gets back online in coming days?

Even if nothing is super-easy when [Nextcloud install docs](https://docs.nextcloud.com/server/18/admin_manual/installation/source_installation.html#prerequisites-for-manual-installation) don't spell this out in a tangibly actionable way.  To be clear, I'm not at all criticizing them for including bonus extras for implementers/communities who want that, e.g. for fast image previewing and interop with other apps etc!  But I do wish Nextcloud's core requirements were spelled out in (more of) an unambiguous way.

e.g. Nextcloud's [1-line installer](https://github.com/nextcloud/vm/blob/master/nextcloud_install_production.sh/) does something a bit different from their stated requirements ;)

**Comment by holta** [comment]
FWIW even though it doesn't align perfectly with Nextcloud's official instructions (!) their [1-line installer script](https://github.com/nextcloud/vm/blob/master/nextcloud_install_production.sh/#L275-L292) here does offer insights:

```
check_command apt install -y \
    php"$PHPVER"-fpm \
    php"$PHPVER"-intl \
    php"$PHPVER"-ldap \
    php"$PHPVER"-imap \
    php"$PHPVER"-gd \
    php"$PHPVER"-pgsql \
    php"$PHPVER"-curl \
    php"$PHPVER"-xml \
    php"$PHPVER"-zip \
    php"$PHPVER"-mbstring \
    php"$PHPVER"-soap \
    php"$PHPVER"-smbclient \
    php"$PHPVER"-json \
    php"$PHPVER"-gmp \
    php"$PHPVER"-bz2 \
    php-pear
    # php"$PHPVER"-imagick \
    # libmagickcore-6.q16-3-extra
```

**Comment by holta** [comment]
@m-anish when you review this, 2 main questions:
- should we add `php-common` back in?
- should many/most of the [9 php-* packages](https://github.com/iiab/iiab/blob/master/roles/nextcloud/tasks/install.yml#L74-L88) be removed from the list of things being installed on non-Raspbian OS's ?

**Comment by tim-moody** [comment]
What problem is all this trying to solve? Did nextcloud magically stop working at some point and if so, what changed? Also, php modules needed by nextcloud should be in the nextcloud role unless used by other commonly installed roles.

**Comment by holta** [comment]
> What problem is all this trying to solve?

2 things:

- @m-anish & I are trying to respect [Nextcloud's official requirements](https://docs.nextcloud.com/server/18/admin_manual/installation/source_installation.html#prerequisites-for-manual-installation) towards reducing everyone's support surprises/burdens down the road.
- @m-anish is trying to add in other php-* packages to enhance Nextcloud's functionality e.g. for (things like image thumbail previews, image rotation, better internationalization and other speed/media stuff) that has the potential to greatly help some communities.
  - This seems like a really great idea, as Nextcloud installations are rarely disk constrained, so I went along with @m-anish's basic direction here...
  - FWIW the proposed list currently looks like: https://github.com/holta/iiab/blob/nextcloud-php-common/roles/nextcloud/tasks/install.yml#L47-L92

> Also, php modules needed by nextcloud should be in the nextcloud role unless used by other commonly installed roles.

I (think!) everyone's in agreement there.  Thanks @tim-moody for stating that upfront to make it clear.

**Comment by tim-moody** [comment]
then then name php-uncommon would be more apt, but just php-modules would do.

**Comment by tim-moody** [comment]
How will you know when 'refine' is complete? Why do base requirements need changing as they worked before? The new title sounds like we are evaluating php modules and packages to see which should support nextcloud.

**Comment by holta** [comment]
I'm just hoping @m-anish can come up with a recommendation for all of us to take seriously, but I realize he's just getting back online (talked with him very quickly last night!) and so it may take him a few days until he has time for this.

**Comment by jvonau** [comment]
I'm not the originator of any of the Nextcloud PR's just a observer, commentator, debugger trying to pointing out weaknesses in the changes. I am not the hidden hand behind any of these changes, why is my name Mentioned?

**Comment by holta** [comment]
@jvonau's name removed from ticket subject line per his request.

(Thanks Jerry for helping inform these issues, even if @m-anish did all the initial work!)

**Comment by jvonau** [comment]
another [php install list from nextcloudpi](https://github.com/nextcloud/nextcloudpi/blob/master/lamp.sh)

**Comment by holta** [comment]
@m-anish let's close this and PR #2119 if you are no longer working on Nextloud, Ok?

(Now that PR #2294 is merged especially.)

**Pull request closed without merging**
