### PR TITLE
rename current_host_channel -> current_client_channel and record

### PR DESCRIPTION
**Pull request by jvonau**
This records the channel that the upstream SSID is using for access to the internet if connected via WiFi. Helpful to note when installing over wifi as 2.4 or 5 Ghz could be used but we only offer 2.4 for the hotspot. Tested on U21.04 with both wlan0 and ap0 active with no wired cable present.

### CODE REVIEW

**Comment by jvonau** [comment]
Testable now.

**Comment by jvonau** [comment]
Use case from https://github.com/iiab/iiab/issues/2658#issuecomment-741520350
> > They stop when I do iiab-hotspot-off and I can connect to upstream WIFI Router.

> With the machine in that state can you grab sudo /usr/sbin/iw dev and sudo systemctl status systemd-networkd posting the results in this issue please. Think your upstream wifi might be a 5GHz connection, the channel in use should tell the tale.

With dual mode on 2.4Ghz with the hostapd channel being adjusted to match what is in use this is a example output:
host_channel = 11
client_wifi_channel = 11

This would be an example of a 5Ghz upstream connection being detected and hostapd not being adjusted.
host_channel = 6
client_wifi_channel = 44

**Comment by holta** [comment]
Tested on 183-rpi4-64bit-lite-BIG-2743 = 10.8.0.38 using:

```
cd /opt/iiab/iiab
git checkout -b jvonau-wifi_info master
git pull https://github.com/jvonau/iiab.git wifi_info
./iiab-network
```

Then I browsed around using http://box (clicking the links on the main page there) using an Android 11 WiFi client.

What additional testing is important, if any?

Ref: #2748

**Comment by holta** [comment]
> Tested on 183-rpi4-64bit-lite-BIG-2743 = 10.8.0.38

[iiab-diagnostics](https://github.com/iiab/iiab/blob/master/scripts/iiab-diagnostics.README.md) output if it helps: http://sprunge.us/rWFSst?en

**Pull request merged**
