### PR TITLE
sysd-netd-debian.yml typo in comment?

### PR DESCRIPTION
**Pull request by holta**
@jvonau / others can confirm.

### CODE REVIEW

**Comment by jvonau** [comment]
Using ''blame" it's easy to deduce which commit changed the line, a95d4762874faac485f2c261eb347d86cf8f4ce5. The $ looks like a truncated line from a copy and paste situation where the line is longer than than what was shown in the terminal.

**Comment by jvonau** [comment]
The full line was "Restart hostapd when WiFi is present but not when using WiFi as gateway with wifi_up_down False"

**Comment by holta** [comment]
> The full line was "Restart hostapd when WiFi is present but not when using WiFi as gateway with wifi_up_down False"

Ok.
I'll assume this exact same language applies to (what's now) Line 71 of https://github.com/iiab/iiab/blob/master/roles/network/tasks/rpi_debian.yml#L71

**Comment by jvonau** [comment]
> > The full line was "Restart hostapd when WiFi is present but not when using WiFi as gateway with wifi_up_down False"
> 
> Ok.
> I'll assume this exact same language applies to (what's now) Line 71 of https://github.com/iiab/iiab/blob/master/roles/network/tasks/rpi_debian.yml#L71

That is why I pointed out the commit to begin with and to suggest what the line was.

**Pull request merged**
