### PR TITLE
Py2

### PR DESCRIPTION
**Pull request by jvonau**
### Fixes bug:
#3711
### Description of changes proposed in this pull request:
newer workflow for U2404
### Smoke-tested on which OS or OS's:
U2404 VM at cmdline only ansible run pending

### CODE REVIEW

**Comment by jvonau** [comment]
https://sprunge.us/o4bsyv 10.8.0.30

**Comment by jvonau** [comment]
I'd double check the second test, doesn't look like kalite is part of the testing, don't have have time to look at the others ATM

**Comment by holta** [comment]
kalite/tasks/install.yml looks like it might need a couple tweaks?

To preserve the current behavior on other OS's — especially Debian 12, Raspberry Pi OS 12, Mint 21.3 (and possibly Ubuntu 22.04 even though that won't be supported much longer, given 24.04's release next month :)

**Comment by jvonau** [comment]
Some notes: 

>2024-03-04 01:33:39,636 p=59392 u=root n=ansible | TASK [kalite : Run '/usr/local/kalite/venv/bin/kalite manage setup ...'] *******
2024-03-04 01:33:50,071 p=59392 u=root n=ansible | fatal: [127.0.0.1]: FAILED! => {"ansible_job_id": "j370488288154.63217", "changed": true, "cmd": ["/usr/local/kalite/venv/bin/kalite", "manage", "setup", "--username=Admin", "--password=changeme", "--noinput"], "delta": "0:00:00.003003", "end": "2024-03-04 01:33:39.883674", "finished": 1, "msg": "non-zero return code", "rc": 1, "results_file": "/root/.ansible_async/j370488288154.63217", "start": "2024-03-04 01:33:39.880671", "started": 1, "stderr": "Traceback (most recent call last):\n  File \"/usr/local/kalite/venv/lib/python2.7/site.py\", line 190, in <module>\n    main()\n  File \"/usr/local/kalite/venv/lib/python2.7/site.py\", line 18, in main\n    rewrite_standard_library_sys_path()\n  File \"/usr/local/kalite/venv/lib/python2.7/site.py\", line 97, in rewrite_standard_library_sys_path\n    import os\nImportError: No module named os", "stderr_lines": ["Traceback (most recent call last):", "  File \"/usr/local/kalite/venv/lib/python2.7/site.py\", line 190, in <module>", "    main()", "  File \"/usr/local/kalite/venv/lib/python2.7/site.py\", line 18, in main", "    rewrite_standard_library_sys_path()", "  File \"/usr/local/kalite/venv/lib/python2.7/site.py\", line 97, in rewrite_standard_library_sys_path", "    import os", "ImportError: No module named os"], "stdout": "", "stdout_lines": []}

> ls /usr/local/kalite/venv/lib/python2.7
lib-dynload  os.py  os.pyc  site-packages  site.py  site.pyc

Note os.py is present, not sure why this one popped up with python2 removed from the system as the virtual environment should be all self-contained, [a737c8c](https://github.com/iiab/iiab/pull/3714/commits/a737c8c05aad5eda76012a2ae422c732377315f3) was the simple fix. 

[5fc4952](https://github.com/iiab/iiab/pull/3714/commits/5fc495259539049c52bf61f41c0407200852ba22) was a copy and paste oversight  

[66eb986](https://github.com/iiab/iiab/pull/3714/commits/66eb9862ee678d57fffcc69d21a02b6930396c84) Not sure why the exec bit was not propagated from my git to upstream when the bit was correctly set when I ran `git add`. Little rusty I guess.

**Comment by jvonau** [comment]
> kalite/tasks/install.yml looks like it might need a couple tweaks?
> 

Think [f871683](https://github.com/iiab/iiab/pull/3714/commits/f871683c2db3c1718d53bcc1b13fbc99e954bc41)  is what you were referring to.

> To preserve the current behavior on other OS's — especially Debian 12, Raspberry Pi OS 12, Mint 21.3 

Should be better now no?

> (and possibly Ubuntu 22.04 even though that won't be supported much longer, given 24.04's release next month :)

I'll call BS on [ending support](https://endoflife.date/ubuntu)

Currently U24.04 is shipping both python 3.12 and 3.11 but that will most likely change before the release date and if it does I would suggest removing the 3.11 on U24.04. Pretty sure this scrip will run on Deb12 and variants if the arch based repo section from the other python2 script was add which should be added anyway to support the other arches but I don't have time to fully test that.

**Comment by jvonau** [comment]
Screenshot from 2024-03-05 05-33-16

Should that not be locat_vars_small.yml to actually test something in a pull request? I trust you can fix that without me having to summit a PR.

**Comment by holta** [comment]
> > kalite/tasks/install.yml looks like it might need a couple tweaks?
> 
> Think [f871683](https://github.com/iiab/iiab/pull/3714/commits/f871683c2db3c1718d53bcc1b13fbc99e954bc41) is what you were referring to.
> 
> > To preserve the current behavior on other OS's — especially Debian 12, Raspberry Pi OS 12, Mint 21.3
> 
> Should be better now no?

Looks to be, yes. 👍 

> Currently U24.04 is shipping both python 3.12 and 3.11 but that will most likely change before the release date and if it does I would suggest removing the 3.11 on U24.04.

Are you saying Lines 11-12 are partly (or entirely) optional here?

https://github.com/jvonau/iiab/blob/f871683c2db3c1718d53bcc1b13fbc99e954bc41/scripts/U2404_python2.sh#L11-L12

> Pretty sure this scrip will run on Deb12 and variants if the arch based repo section from the other python2 script was add which should be added anyway to support the other arches but I don't have time to fully test that.

Interesting.

**Comment by holta** [comment]
> > (and possibly Ubuntu 22.04 even though that won't be supported much longer, given 24.04's release next month :)

Old News / Clarif / Just FYI: IIAB will not support OS's from many years ago — no matter if those OS's describe themselves as "LTS" or not:

- PR #3034
- PR #3691
- https://github.com/iiab/iiab/wiki/IIAB-Platforms

**Comment by holta** [comment]
> Screenshot from 2024-03-05 05-33-16
> 
> Should that not be locat_vars_small.yml to actually test something in a pull request?

GitHub Actions doesn't quite offer enough memory to test SMALL-sized IIAB installs.

(So the use of local_vars_none.yml is very intentional here.)

**Comment by holta** [comment]
FWIW Line 41 below has side effects beyond scripts/install_python2.sh — e.g. removal of python3-pip used by scripts/ansible:

```
apt -y remove libmpdec3 python3-pip python3-wheel
```

https://github.com/jvonau/iiab/blob/f871683c2db3c1718d53bcc1b13fbc99e954bc41/scripts/U2404_python2.sh#L41

(Are these removals really necessary?)

**Comment by jvonau** [comment]
> FWIW Line 41 below has side effects beyond scripts/install_python2.sh — e.g. removal of python3-pip used by scripts/ansible:
> 
> ```
> apt -y remove libmpdec3 python3-pip python3-wheel
> ```

False statement, python3-venv is installed and doesn't depend on either on U24.04 but pulls in python3-pip-whl python3-setuptools-whl wheels are used within virtual environments as python packaged programs

From apt info  python3-venv:
>Depends: python3.12 (= 3.12.2-1), python3-pip-whl (>= 22.2), python3-setuptools-whl
Breaks: python3-pip (<< 1.5.6-4)
 
> https://github.com/jvonau/iiab/blob/f871683c2db3c1718d53bcc1b13fbc99e954bc41/scripts/U2404_python2.sh#L41
> 
> (Are these removals really necessary?)

You want a stable OS environment? Those packages were pulled in by using U22.04 packages with slightly different dependencies otherwise they would never be installed. I'll see if I can slim down some stuff as to avoid pulling a raft of compilers, you know my feelings on shipping compiles out into the wild.

**Comment by holta** [comment]
I thought python3-venv dragged in python3-pip in the past.  But maybe I'm remembering wrong, and it was the other way around.

**Comment by jvonau** [comment]
> I thought python3-venv dragged in python3-pip in the past. But maybe I'm remembering wrong, and it was the other way around.

Not really, but I'm not in the mood to teach python history. Anyway the compilers are not dragged in now and things feel a whole pile safer to me. On a side note leaving things with `apt mark` in place might block some important update at some point.

**Comment by holta** [comment]
@EMG70 would you have time to test a SMALL-sized IIAB install (or anything including KA Lite!) using...

```
curl iiab.io/fast.txt | bash -s 3714
```

...on Ubuntu 24.04 and/or on any other OS?

**Comment by jvonau** [comment]
On could try just the script on Debian 12 amd64, if that proves workable then the arch specific repo stanza could be added for the others.

**Comment by EMG70** [comment]
IIAB-DIAGNOSTICS  - http://sprunge.us/ULadIl?en
Installed IIAB SMALL size on Debian 12,no issues found.Ka lite and all APPS working ok.

**Comment by EMG70** [comment]
Tested on the following OS with small size IIAB .ALL Apps working well and Ka-Lite downloading OK on both.
Raspberry PI 400 
IIAB DIAGNOSTICS - http://sprunge.us/B7uPqJ?en

Linux Mint 21.3 
IIAB DIAGNOSTICS - http://sprunge.us/haQgq1?en

**Comment by holta** [comment]
Amazing!

Thanks @emg70 for doing the vital & hard work of validating that the ancient KA Lite can live on — for another year or two perhaps — to assist those with tiny devices like Raspberry Pi Zero 2 W 😄

**Pull request merged**
