### PR TITLE
replacement for 2500

### PR DESCRIPTION
**Pull request by jvonau**
Replacement for the rudely reverted #2500 with new ability to back fit the fix for #2475 to recent installs

### CODE REVIEW

**Comment by jvonau** [comment]
more disregard for pending PRs

**Comment by tim-moody** [comment]
`# use 'Update' in the name line when the role is not optional`

how does 'update' mean 'required'?

**Comment by jvonau** [comment]
For the most part "install" is conditional upon local_vars being set to True for the role, with install.yml being present in the role, pylib's doesn't have an install.yml file and no entries in local_vars.yml. 'Update' is used as a visual reminder that the role is not optional. Would "Mandatory Update" be more descriptive?

**Comment by tim-moody** [comment]
I like Mandatory. looking at packages.yml in 2-common, I see they all say install

**Comment by jvonau** [comment]
forking

**Pull request closed without merging**
