### PR TITLE
Refine roles/jupyterhub/README.md

### PR DESCRIPTION
**Pull request by holta**
Thanks @georgejhunt if you can review and/or enhance this!

- PR #2719
- PR #2733
- PR #2736
- PR #2737

### CODE REVIEW

**Comment by holta** [comment]
@georgejhunt I still find jupyterhub/README.md somewhat confusing — _can you help clarify for introductory teachers:_

- Is it better for students to use JupyterHub with or without a username/password, in your opinion?
- Is the idea that teachers can create a username/password for each student to allow for greatly enhanced functionality?

**Comment by georgejhunt** [comment]
On Sun, Aug 1, 2021 at 4:02 AM A Holt ***@***.***> wrote:

> @georgejhunt <https://github.com/georgejhunt> I still find
> jupyterhub/README.md somewhat confusing — *can you help clarify for
> introductory teachers:*
>
>    - Is it better for students to use JupyterHub with or without a
>    username/password, in your opinion?
>
> I guess you are hinting that you don't want a username/password. I do not
know how to protect one student from another on a server without some sort
of authenticated identity.

>
>    - Is the idea that teachers can create a username/password for each
>    student to allow for greatly enhanced functionality?
>
> What needs to be added to:


   - Once a user signs in with a username and password, these credentials
   are stored, and are used thereafter to gain access to the user's files.


Maybe there needs to be a statement that  the teacher does not need to be
involved in the troublesome administration of username/password--that they
are created by the student on first use.

**Comment by holta** [comment]
> I guess you are hinting that you don't want a username/password.

I'm not hinting anything; I'm just trying to understand a typical school scenario.

While trying to understand the sentence "individual users [can] start using their own Notebook on the IIAB server (http://box.lan/jupyterhub) without needing an individual server account" &mdash; maybe this sentence needs to be rewritten?

Your suggestions help.  I'll try to revise the current README.md but a call might also help.

**Comment by georgejhunt** [comment]
"individual server account" is the problem.  It is misleading. For linux
nerds like me, it might have some historical meaning. But it should go away.

**Comment by holta** [comment]
> "individual server account" is the problem.  It is misleading. For linux
nerds like me, it might have some historical meaning. But it should go away.

Thanks!  Can you review this new draft I've just posted?

https://github.com/holta/iiab/tree/jupyterhub-readme/roles/jupyterhub#jupyterhub-programming-environment-with-student-notebooks

**Comment by georgejhunt** [comment]
One of the expected problems is that a student will forget his password,
and not be able to log in.

I don't have a clean install of the jupyterhub role.  Could you look to see
if the user data is actually at /var/lib/private? ---as it is on my
development machine (before the PR was merged into master).

I don't know where the user password is stored. So to work around a
forgotten password, the teacher can have the student create a new
user-password pair, and then "sudo cp /var/lib/private/<old
username/*.ipynb /var/lib/private/<new username/"

**Comment by holta** [comment]
> Could you look to see if the user data is actually at /var/lib/private? ---as it is on my development machine (before the PR was merged into master).

Sort of!  Each user has 2 (typically empty) directories like:

```
/var/lib/private/iiab-admin/.cache/yarn/v6/.tmp/
/var/lib/private/iiab-admin/.local/share/jupyter/runtime/
```

The exception is the above 'runtime' dir which sometimes contains 2 files:

```
-rw-r--r-- 1 64763 64763 288 Aug  1 15:51 nbserver-9395.json
-rw-r--r-- 1 64763 64763 592 Aug  1 15:51 nbserver-9395-open.html
```

No doubt related to systemd (sub)services, one for each user...

```
root@box:~# systemctl status jupyter-iiab-admin-singleuser.service
● jupyter-iiab-admin-singleuser.service - /bin/bash -c cd /var/lib/iiab-admin && exec jupyterhub-singleuser --port=34729
   Loaded: loaded (/run/systemd/transient/jupyter-iiab-admin-singleuser.service; transient)
Transient: yes
   Active: active (running) since Sun 2021-08-01 15:50:59 EDT; 16min ago
 Main PID: 9395 (jupyterhub-sing)
    Tasks: 6 (limit: 3258)
   CGroup: /system.slice/jupyter-iiab-admin-singleuser.service
           └─9395 /opt/iiab/jupyterhub/bin/python3 /opt/iiab/jupyterhub/bin/jupyterhub-singleuser --port=34729

Aug 01 16:06:59 box.lan bash[9395]: [I 2021-08-01 16:06:59.596 SingleUserNotebookApp log:189] 302 GET /jupyterhub/user/iiab-admin/tree? -> /jupyterhub/hub/api/oauth2/authorize?client_id=jupyterhub-user-iiab-admin&redirect_uri=%2Fjupyterhub%2Fuser%2Fiiab-admin%2Foauth_callback&response_type=code&state=[secret] (@10.8.0.66) 3.01ms
Aug 01 16:07:00 box.lan bash[9395]: [I 2021-08-01 16:07:00.223 SingleUserNotebookApp auth:992] Logged-in user {'kind': 'user', 'name': 'iiab-admin', 'admin': False, 'groups': [], 'server': '/jupyterhub/user/iiab-admin/', 'pending': None, 'created': '2021-08-01T17:45:14.687162Z', 'last_activity': '2021-08-01T20:07:00.149139Z', 'servers': None}
Aug 01 16:07:00 box.lan bash[9395]: [I 2021-08-01 16:07:00.226 SingleUserNotebookApp log:189] 302 GET /jupyterhub/user/iiab-admin/oauth_callback?code=[secret]&state=[secret] -> /jupyterhub/user/iiab-admin/tree? (@10.8.0.66) 331.90ms
Aug 01 16:07:00 box.lan bash[9395]: [I 2021-08-01 16:07:00.295 SingleUserNotebookApp log:189] 200 GET /jupyterhub/user/iiab-admin/tree? (iiab-admin@10.8.0.66) 8.44ms
Aug 01 16:07:00 box.lan bash[9395]: [I 2021-08-01 16:07:00.709 SingleUserNotebookApp log:189] 200 GET /jupyterhub/user/iiab-admin/api/config/tree?_=1627848419489 (iiab-admin@10.8.0.66) 17.70ms
Aug 01 16:07:00 box.lan bash[9395]: [I 2021-08-01 16:07:00.733 SingleUserNotebookApp log:189] 200 GET /jupyterhub/user/iiab-admin/api/config/common?_=1627848419490 (iiab-admin@10.8.0.66) 18.96ms
Aug 01 16:07:00 box.lan bash[9395]: [I 2021-08-01 16:07:00.735 SingleUserNotebookApp log:189] 200 GET /jupyterhub/user/iiab-admin/api/terminals?_=1627848419491 (iiab-admin@10.8.0.66) 16.70ms
Aug 01 16:07:00 box.lan bash[9395]: [I 2021-08-01 16:07:00.753 SingleUserNotebookApp log:189] 200 GET /jupyterhub/user/iiab-admin/api/sessions?_=1627848419492 (iiab-admin@10.8.0.66) 10.73ms
Aug 01 16:07:00 box.lan bash[9395]: [I 2021-08-01 16:07:00.755 SingleUserNotebookApp log:189] 200 GET /jupyterhub/user/iiab-admin/api/terminals?_=1627848419493 (iiab-admin@10.8.0.66) 10.71ms
Aug 01 16:07:00 box.lan bash[9395]: [I 2021-08-01 16:07:00.877 SingleUserNotebookApp log:189] 200 GET /jupyterhub/user/iiab-admin/api/contents?type=directory&_=1627848419494 (iiab-admin@10.8.0.66) 6.76ms
```

ASIDE: For teachers in the field, username `Admin` is much more suitable than `iiab-admin` &mdash; so we should probably change that here: [roles/jupyterhub/templates/jupyterhub_config.py#L1060](https://github.com/iiab/iiab/blob/d0e8e048347bf46c02a2cdb0da9c5cd0c489fe40/roles/jupyterhub/templates/jupyterhub_config.py#L1060)

And probably also uncomment Line 67 [c.JupyterHub.admin_access = False](https://github.com/iiab/iiab/blob/master/roles/jupyterhub/templates/jupyterhub_config.py#L67) too?  _But that doesn't seem to be enough below :/  So hopefully you know more!_

> I don't know where the user password is stored.

Passwords themselves appear to be stored at the very top of the filesystem here: `/passwords.dbm.db`
That's not very kosher obviously (!) so probably we should move that using [FirstUseAuthenticator.dbm_path](https://github.com/jupyterhub/firstuseauthenticator#firstuseauthenticatordbm_path) if you know how?

_"dbm file should be put where regular users do not have read/write access to it."_

Possibly moving that file into some place like `/opt/iiab/jupyterhub/etc/` ?
Also note the entire file `passwords.dbm.db` can be wiped, allowing all JupyterHub users to create new passwords &mdash; but going nuclear like that is a bit much :/

To Summarize: 2 really key questions if you have time in coming days?

1) How can a teacher access the "administrator's page" discussed in the [JupyterHub FAQ](https://jupyterhub.readthedocs.io/en/stable/getting-started/institutional-faq.html#how-do-i-manage-users) here?

   _"The users of a JupyterHub are stored locally, and can be modified manually by an administrator of the JupyterHub. Moreover, the active users on a JupyterHub can be found on the administrator’s page. This page gives you the abiltiy to stop or restart kernels, inspect user filesystems, and even take over user sessions to assist them with debugging."_

   Clicking 'Control Panel' in the top-right of http://10.8.0.14/jupyterhub/user/iiab-admin/tree seems to offer only these 2 colorful buttons at http://10.8.0.14/jupyterhub/hub/home:

   image

2) https://github.com/jupyterhub/firstuseauthenticator#how-can-i-change-my-password and https://tljh.jupyter.org/en/latest/howto/auth/firstuse.html#users-changing-their-own-password both say users can change their passwords on a page like http://10.8.0.14/jupyterhub/hub/auth/change-password &mdash; do you know if this can possibly be made to work?

_(Feel free to log into and modify RPi 4 10.8.0.14 if it helps!)_

**Comment by holta** [comment]
> 1. How can a teacher access the "administrator's page" discussed in the [JupyterHub FAQ](https://jupyterhub.readthedocs.io/en/stable/getting-started/institutional-faq.html#how-do-i-manage-users) here?

The 5 "extra privileges" of JupyterHub Admins...are also listed here:

https://github.com/iiab/iiab/blob/d0e8e048347bf46c02a2cdb0da9c5cd0c489fe40/roles/jupyterhub/templates/jupyterhub_config.py#L1049-L1054

**Comment by holta** [comment]
JupyterHub remains confusing to new teachers &mdash; we definitely need to address the questions above.

Still, until then, this jupterhub/README.md at least represents a big step forward.

And I've just pushed 2 tiny changes to [roles/jupyterhub/templates/jupyterhub_config.py](https://github.com/iiab/iiab/blob/master/roles/jupyterhub/templates/jupyterhub_config.py) https://github.com/iiab/iiab/pull/2892/commits/c97c46693099cd74f767db6a5dbc9312d33f6e03 (for `/opt/iiab/jupyterhub/etc/jupyterhub/jupyterhub_config.py`) so as to encourage wider community testing.

Thanks @georgejhunt if you can weigh after your return from Northern California!

**Pull request merged**
