### PR TITLE
Run 'systemctl restart freepbx' twice, so http://box:83/freepbx works right away on install, prior to reboot -- Re: "Unable to run Pre-Asterisk hooks, because Asterisk is already running"

### PR DESCRIPTION
**Pull request by holta**
After many false leads, let's hope this solution is reliable!

Tested on a Debian 11 (server) VM.  Refs:

- PR #2905
- PR #2908
- PR #2910
- PR #2911
- PR #2912 
- PR #2913 
- PR #2914

With thanks to @jvonau & @lemueldsouza.

### CODE REVIEW

**Comment by holta** [comment]
While running `systemctl restart freepbx` **twice** does the job, we could also consider things like:

```
fwconsole reload
```

Considering this detailed March 2021 recipe for Raspberry Pi:

http://mghadam.blogspot.com/2021/03/install-asterisk-18-freepbx-15-on.html

**Comment by jvonau** [comment]
post the output of `sudo journalctl --no-pager -u freepbx` from your test subject please.

**Comment by holta** [comment]
To be clear, the "Unable to run Pre-Asterisk hooks, because Asterisk is already running" message doesn't go away (from `journalctl -u freepbx` logs).

This patch just allows operators to use http://box:83/freepbx right away on install, prior to reboot.

As the "hooks" complaint seems to happen just once.  Hence the pragmatic workaround, i.e. running `systemctl restart freepbx` twice.

**Comment by jvonau** [comment]
Simple request post the logging info from above for review, so others might learn or offer suggestions.

**Comment by holta** [comment]
Just FYI this PR was tested to work using Debian 11 and Ubuntu 20.04 VM's (the server not graphical desktop versions).

**Comment by holta** [comment]
> post the output of `sudo journalctl --no-pager -u freepbx` from your test subject please.

root@u20-srv:~# journalctl -u freepbx.service | pastebinit
https://paste.ubuntu.com/p/HqBMP52pcY/

**Comment by jvonau** [comment]
Thanks, I know the brute force killall worked like a charm [here](https://github.com/iiab/iiab/pull/2912#issuecoment-893174982)
```
changed: [127.0.0.1] => (item=./start_asterisk start)
changed: [127.0.0.1] => (item=./install -n --webroot /var/www/html/freepbx --dbuser asterisk --dbpass asterisk --dbname asterisk --cdrdbname asteriskcdrdb)
changed: [127.0.0.1] => (item=killall -9 safe_asterisk)
changed: [127.0.0.1] => (item=killall -9 asterisk)
```
not sure why your install was showing 'OK' for both in https://github.com/iiab/iiab/pull/2913#issuecomment-893252632 
```
changed: [127.0.0.1] => (item=./start_asterisk start)
changed: [127.0.0.1] => (item=./install -n --webroot /var/www/html/freepbx --dbuser asterisk --dbpass asterisk --dbname asterisk --cdrdbname asteriskcdrdb)
ok: [127.0.0.1] => (item=killall -9 safe_asterisk)
ok: [127.0.0.1] => (item=killall -9 asterisk)
```
That would suggest the process crashed during the prior step or ansible is giving different feedback for some unknown reason.

Seen that /usr/sbin/asterisk -rx "core stop gracefully" was tried did that not shut down asterisk cleanly? or did safe_asterisk spawn the process again like it should? Comes down to cleaning up what start_asterisk does, perhaps 'fwconsole stop' could be an alternative at this point where killall was as fwconsole knows about the use of safe_asterisk internally and systemd won't run the ExecStop= line unless it is the one that started the processes.

**Comment by holta** [comment]
> perhaps 'fwconsole stop' could be an alternative at this point where killall was as fwconsole knows about the use of safe_asterisk internally and systemd won't run the ExecStop= line unless it is the one that started the processes.

I agree.  I haven't tried that.

Evidently FreePBX has other bitrotting/buggy code too (!)  Just one very prominent example from `/opt/iiab/freepbx/start_asterisk` (https://git.freepbx.org/projects/FREEPBX/repos/framework/browse/start_asterisk#60) here:

```
root@u20-srv:~# asterisk -rx "stop gracefully"
No such command 'stop gracefully' (type 'core show help stop gracefully' for other possible commands)
```

In this case the fix is of course:

```
asterisk -rx "core stop gracefully"
```

(Hopefully many of these things will be fixed prior to [FreePBX 16](https://www.freepbx.org/freepbx-16-beta-is-here/)'s final release?!)

ASIDE: here's the latest list of 363 [Asterisk commands](https://wiki.asterisk.org/wiki/display/AST/CLI+Syntax+and+Help+Commands):

> root@u20-srv:~# asterisk -rx "core show help" | pastebinit
> https://paste.ubuntu.com/p/W5X3J5znyX/

**Comment by jvonau** [comment]
> (Hopefully many of these things will be fixed prior to [FreePBX 16](https://www.freepbx.org/freepbx-16-beta-is-here/)'s final release?!)
> 

File a bug upstream, that is how that will get fixed. For now lets document the need for asterisk to be stopped prior to starting the custom freepbx unit file. Suppressing the "Unable to run Pre-Asterisk hooks, because Asterisk is already running" is a bit worrisome as this might be a onetime operation that needed to be preformed but was not, with the second pass assuming the action was carried out. I prefer a nice clean log so things don't bubble up to the top later because of a shortcut.

The double restart might be fine if all the service are running, but I would not try to configure the machine until rebooted with everything should be under running under freepbx's fwconsole agreed?

> ASIDE: here's the latest list of 363 [Asterisk commands](https://wiki.asterisk.org/wiki/display/AST/CLI+Syntax+and+Help+Commands):
> 
> > root@u20-srv:~# asterisk -rx "core show help" | pastebinit
> > https://paste.ubuntu.com/p/W5X3J5znyX/

Been there done that.. haven't figured out how to dump this without being in the console
```
ubuntu@box:/etc/asterisk$ sudo asterisk -rvvv
[sudo] password for ubuntu: 
Asterisk 18.5.1, Copyright (C) 1999 - 2021, Sangoma Technologies Corporation and others.
Created by Mark Spencer <markster@digium.com>
Asterisk comes with ABSOLUTELY NO WARRANTY; type 'core show warranty' for details.
This is free software, with components licensed under the GNU General Public
License version 2 and other licenses; you are welcome to redistribute it under
certain conditions. Type 'core show license' for details.
=========================================================================
Running as user 'asterisk'
Running under group 'asterisk'
Connected to Asterisk 18.5.1 currently running on box (pid = 228660)
box*CLI> config list
core                 /etc/asterisk/acl.conf                            
res_adsi             /etc/asterisk/adsi.conf                           
core                 /etc/asterisk/agents.conf                         
app_alarmreceiver    /etc/asterisk/alarmreceiver.conf                  
core                 /etc/asterisk/ari.conf                            
core                 /etc/asterisk/asterisk.conf                       
calendar             /etc/asterisk/calendar.conf                       
ccss                 /etc/asterisk/ccss.conf                           
cdr_csv              /etc/asterisk/cdr.conf                            
core                 /etc/asterisk/cdr.conf                            
cdr_adaptive_odbc    /etc/asterisk/cdr_adaptive_odbc.conf              
cdr_manager          /etc/asterisk/cdr_manager.conf                    
cdr_odbc             /etc/asterisk/cdr_odbc.conf                       
cdr_pgsql            /etc/asterisk/cdr_pgsql.conf                      
cdr_sqlite3_custom   /etc/asterisk/cdr_sqlite3_custom.conf             
cdr_tds              /etc/asterisk/cdr_tds.conf                        
cel_manager          /etc/asterisk/cel.conf                            
core                 /etc/asterisk/cel.conf                            
cel_odbc             /etc/asterisk/cel_odbc.conf                       
cel_pgsql            /etc/asterisk/cel_pgsql.conf                      
cel_sqlite3_custom   /etc/asterisk/cel_sqlite3_custom.conf             
cel_tds              /etc/asterisk/cel_tds.conf                        
core                 /etc/asterisk/cli.conf                            
core                 /etc/asterisk/cli_permissions.conf                
codec_speex          /etc/asterisk/codecs.conf                         
plc                  /etc/asterisk/codecs.conf                         
core                 /etc/asterisk/confbridge.conf                     
chan_console         /etc/asterisk/console.conf                        
dnsmgr               /etc/asterisk/dnsmgr.conf                         
dsp                  /etc/asterisk/dsp.conf                            
pbx_dundi            /etc/asterisk/dundi.conf                          
enum                 /etc/asterisk/enum.conf                           
extconfig            /etc/asterisk/extconfig.conf                      
pbx_config           /etc/asterisk/extensions.conf                     
core                 /etc/asterisk/features.conf                       
app_festival         /etc/asterisk/festival.conf                       
app_followme         /etc/asterisk/followme.conf                       
func_odbc            /etc/asterisk/func_odbc.conf                      
core                 /etc/asterisk/hep.conf                            
http                 /etc/asterisk/http.conf                           
chan_iax2            /etc/asterisk/iax.conf                            
chan_iax2            /etc/asterisk/iaxprov.conf                        
indications          /etc/asterisk/indications.conf                    
logger               /etc/asterisk/logger.conf                         
manager              /etc/asterisk/manager.conf                        
manager              /etc/asterisk/manager_additional.conf             
manager              /etc/asterisk/manager_custom.conf                 
core                 /etc/asterisk/modules.conf                        
core                 /etc/asterisk/motif.conf                          
res_musiconhold      /etc/asterisk/musiconhold.conf                    
res_musiconhold      /etc/asterisk/musiconhold_additional.conf         
res_musiconhold      /etc/asterisk/musiconhold_custom.conf             
app_osplookup        /etc/asterisk/osp.conf                            
02b997f5-d17a-4e71-b /etc/asterisk/pjproject.conf                      
df30c49c-fd23-498e-a /etc/asterisk/pjsip.conf                          
e5175a31-ff04-47a3-9 /etc/asterisk/pjsip.conf                          
f940b52e-983a-4b94-a /etc/asterisk/pjsip.conf                          
16847d82-e31f-4f37-a /etc/asterisk/pjsip.conf                          
7f481434-ce5a-44a1-a /etc/asterisk/pjsip.conf                          
1a6fe07b-ef67-4383-a /etc/asterisk/pjsip.conf                          
3149fd61-ec3e-4b8f-9 /etc/asterisk/pjsip.conf                          
8aafdf67-da76-4da1-8 /etc/asterisk/pjsip.conf                          
015d142e-9c30-4eb6-8 /etc/asterisk/pjsip.conf                          
06a80a9a-b22d-478f-b /etc/asterisk/pjsip.conf                          
59010918-3a4d-4267-9 /etc/asterisk/pjsip.conf                          
d764df27-e07c-4af7-9 /etc/asterisk/pjsip.conf                          
f1ec7a14-3102-4ebf-9 /etc/asterisk/pjsip.conf                          
4a3e2fb9-a248-4eb1-b /etc/asterisk/pjsip.conf                          
core                 /etc/asterisk/pjsip_notify.conf                   
registration         /etc/asterisk/pjsip_wizard.conf                   
identify             /etc/asterisk/pjsip_wizard.conf                   
endpoint             /etc/asterisk/pjsip_wizard.conf                   
aor                  /etc/asterisk/pjsip_wizard.conf                   
auth                 /etc/asterisk/pjsip_wizard.conf                   
core                 /etc/asterisk/prometheus.conf                     
app_queue            /etc/asterisk/queuerules.conf                     
app_queue            /etc/asterisk/queues.conf                         
app_queue            /etc/asterisk/queues_additional.conf              
app_queue            /etc/asterisk/queues_custom.conf                  
app_queue            /etc/asterisk/queues_custom_general.conf          
app_queue            /etc/asterisk/queues_general_additional.conf      
app_queue            /etc/asterisk/queues_post_custom.conf             
res_config_curl      /etc/asterisk/res_curl.conf                       
res_fax              /etc/asterisk/res_fax.conf                        
res_odbc             /etc/asterisk/res_odbc.conf                       
core                 /etc/asterisk/res_parking.conf                    
res_config_pgsql     /etc/asterisk/res_pgsql.conf                      
res_snmp             /etc/asterisk/res_snmp.conf                       
res_stun_monitor     /etc/asterisk/res_stun_monitor.conf               
core                 /etc/asterisk/resolver_unbound.conf               
res_resolver_unbound /etc/asterisk/resolver_unbound.conf               
rtp                  /etc/asterisk/rtp.conf                            
app_playback         /etc/asterisk/say.conf                            
chan_sip             /etc/asterisk/sip.conf                            
chan_sip             /etc/asterisk/sip_notify.conf                     
chan_skinny          /etc/asterisk/skinny.conf                         
res_smdi             /etc/asterisk/smdi.conf                           
sorcery              /etc/asterisk/sorcery.conf                        
core                 /etc/asterisk/stasis.conf                         
core                 /etc/asterisk/statsd.conf                         
36c70ee1-9af9-47ff-9 /etc/asterisk/stir_shaken.conf                    
1a6d73d8-6f22-45e5-8 /etc/asterisk/stir_shaken.conf                    
b8d02a74-4c5c-41e6-a /etc/asterisk/stir_shaken.conf                    
core                 /etc/asterisk/udptl.conf                          
chan_unistim         /etc/asterisk/unistim.conf                        
app_voicemail        /etc/asterisk/users.conf                          
chan_iax2            /etc/asterisk/users.conf                          
chan_sip             /etc/asterisk/users.conf                          
manager              /etc/asterisk/users.conf                          
pbx_config           /etc/asterisk/users.conf                          
app_voicemail        /etc/asterisk/voicemail.conf                      
core                 /etc/asterisk/xmpp.conf           
```
Lots of stuff to keep an eye on.

**Comment by jvonau** [comment]
My working theory is that stock asterisk install /etc/asterisk/cel.conf and/or /etc/asterisk/cdr.conf might need tinkering before or perhaps after calling start_asterisk as these are part of 'core' but might be disable due to a [Radcli error](https://github.com/iiab/iiab/pull/2905/files#diff-fab5901d22b49153f45b5b596441fe65ee47704087ce9cb318a914d91f561e7bR130-R133). Not a show stopper but should the module become enabled unexpected results should be expected.

**Comment by holta** [comment]
I would hope that `fwconsole reload` or `fwconsole restart` or `fwconsole stop` might help, instead of 1-or-both of Ansible's systemctl restarts of freepbx.service &mdash; this summary of fwconsole commands is updated often which bodes well:

https://wiki.freepbx.org/pages/viewpage.action?pageId=37912685

But I'm away much of the day helping a friend with a serious medical issue.  And of course there are possibly higher priorities like NGINX work outlined at #2914, and docs outlined at #2905.  (Many thanks to @lemueldsouza who laid those 2 out, even if just in draft form for now!)

**Pull request merged**
