### PR TITLE
Ap0+wifi up down2 [WIP] [simultaneous WiFi-as-hotspot AND WiFi-as-client]

### PR DESCRIPTION
**Pull request by jvonau**
status update rpi install http://dpaste.com//13CDA44 more commits to come.

### CODE REVIEW

**Comment by holta** [comment]
Building on:
- PR #2380 "Ap0+wifi up down rebased [simultaneous WiFi-as-hotspot AND WiFi-as-client]"

Related:
- #2382 "merged 2380 [how to configure upstream & downstream WiFi?]"
- PR #2383 "2382 [hostapd / restart / dnsmasq / systemd-networkd refinement]"

**Comment by jvonau** [comment]
Starting from the top up to commit 0ef7026 has been running in production for about a week now with positive results. 
Next 3 commit ending at 67588ae are part of master 
Up to d149bed is running here locally, I'll update later 
Up to 8e39c3d is running on 183-rpi4-2g-lite-eth-MIN-PR2383 
on rpi-next-run branch http://dpaste.com//23WMD10

**Comment by jvonau** [comment]
b3ae819 ran to completion but wifi-test needed work.
596f924 U20-arm64-server rebooted http://dpaste.com//3SH271N

**Comment by holta** [comment]
After WiFi-installing this PR (#2384) onto Ubuntu 20.04 LTS Desktop on an actual Acer laptop (134-u20-desk-acer-wifi-PR2384 = 10.8.0.26) the output of iiab-diagnostics _(after rebooting)_ is here:

http://dpaste.com//01FSX46

**Comment by holta** [comment]
> 134-u20-desk-acer-wifi-PR2384 = 10.8.0.26

FYI Dual WiFi worked before AND after reboot.  As confirmed by quickly associating an Android phone with the laptop's internal SSID and then browsing to `box/` = http://box/ (meanwhile the laptop's upstream WiFi connection to the Internet continued to work!)

**Comment by jvonau** [comment]
80dfaae 183-rpi4-2g-lite-eth-MIN-PR2383 = .62 http://dpaste.com//2WT4F30 updated and rebooted

**Comment by holta** [comment]
I don't know if this PR is appropriate for [IIAB 7.1](https://github.com/iiab/iiab/wiki/IIAB-7.1-Release-Notes) (that needs to enter feature freeze/code freeze very soon now!) but this is an option we can discuss during Thursday's weekly call (http://minutes.iiab.io) 10AM NYC Time tomorrow.

**Comment by jvonau** [comment]
.26, .34, and mine at 6b56f77 all function correctly with ./iiab-network and reboot.

**Comment by tim-moody** [comment]
>I don't know if this PR is appropriate for IIAB 7.1 (that needs to enter feature freeze/code freeze very soon now!) but this is an option we can discuss during Thursday's weekly call (http://minutes.iiab.io) 10AM NYC Time tomorrow.

If this is a set of fixes for #2382 then it either needs to be completed and tested before release or 2382 should be backed out. Not sure why a PR that does a major rewrite of networking was merged between preview 4 and 5.

**Comment by holta** [comment]
FYI this PR was tested quite heavily today, on 3 different OS's, and all signs are very encouraging so far, so it will quite (likely) be merged in the coming 24h.

Anybody who can further contribute, please install:

`curl d.iiab.io/install-test.txt | sudo bash`

...e.g. a WiFi install onto Raspbian Desktop (our most popular OS) or any other OS you prefer, Great!

**Comment by tim-moody** [comment]
How should one test beyond the smoke test?

**Comment by tim-moody** [comment]
> Raspbian Desktop (our most popular OS) 

As measured how?

**Comment by holta** [comment]
> How should one test beyond the smoke test?

I usually install IIAB over WiFi then test the hotspot both before and after reboot.

But let's ask @jvonau what else we should also be testing-

**Comment by holta** [comment]
> > Raspbian Desktop (our most popular OS)
> 
> As measured how?

Raspbian Desktop is an order of magnitude more popular than Raspbian Lite among the newcomer IIAB implementers I've spoken to over the past 1-2 years.

It's become obvious they're just Far More Comfortable with a visual/graphical desktop, for sundry/various reasons — even when I suggest Raspbian Lite — they don't want it...

**Comment by jvonau** [comment]
> > I don't know if this PR is appropriate for IIAB 7.1 (that needs to enter feature freeze/code freeze very soon now!) but this is an option we can discuss during Thursday's weekly call (http://minutes.iiab.io) 10AM NYC Time tomorrow.
> 
> If this is a set of fixes for #2382 then it either needs to be completed and tested before release or 2382 should be backed out. Not sure why a PR that does a major rewrite of networking was merged between preview 4 and 5.

In the issue 2382 you pointed out that when installing via a wired interface that the AP was unavailable post-install/pre-reboot, which from your tone I took this to mean this was a regression. Not the end of the world but I tend to agree so #2383 was born to address your observation.

**Comment by tim-moody** [comment]
All I'm saying about 2382 and this PR is that any release should either have both or neither. I don't see stopping half way.

**Comment by holta** [comment]
Fresh WiFi-based installs tested successfully on 3 different OS's on RPi 4: (intentionally without an Ethernet cable!)
- Ubuntu Server 20.04 LTS (bonus: SSID works prior to reboot)
   117-rpi4-1g-u20-PR2384 = 10.8.0.34
- Raspbian With Desktop (SSID doesn't work properly until IIAB install completes and you reboot)
   126-rpi4-2g-desk-PR2384 = 10.8.0.22
- Raspbian Lite (ditto...SSID requires reboot to work properly)
   136-rpi4-2g-lite-PR2384 = 10.8.0.62

**Comment by holta** [comment]
See PR #2393 instead.

**Comment by jvonau** [comment]
inspiration from https://raspberrypi.stackexchange.com/questions/95485/creating-router-without-using-ethernet and #194 #197 #430 #431 #543

**Pull request closed without merging**
