### PR TITLE
CUPS Printing: Spring Cleaning + NGINX fix for URL's like http://box/print + hardening of URL's like http://box/print/admin

### PR DESCRIPTION
**Pull request by holta**
Building on @deldesir's:

- PR #2775

Most URL's still fail (certainly on RaspiOS) but this PR puts IIAB's CUPS role on a more solid foundation for the coming decade [as CUPS evolves](https://github.com/apple/cups/releases), sweeping out the cobwebs after about half a decade.  Let's use this opportunity not just to clean house, improve security, and eliminate risky bitrot &mdash; but also to get these URL's working very soon now:

- http://box:631
- http://box.lan:631
- http://box/print
- http://box.lan/print

ASIDE: While URL's like http://10.8.0.30:631 could also be made to work, very easily using these 2 lines...

```
cupsctl --remote-any
systemctl restart cups
```

_...this is probably very unwise, as `cupsctl --remote-any` turns off remote administration of CUPS, which CUPS documentation does not make clear!_

Refs:

- #2766 
- PR #2845
- #2842

### CODE REVIEW

**Review by Didi99999 — APPROVED** [review]

**Comment by holta** [comment]
Clarification: this PR was tested on 32-bit RaspiOS Lite (RPi 4) and 64-bit Ubuntu Server 21.10 pre-release (VM).

In both cases these URL's work:

- http://localhost:631
- http://127.0.0.1:631
- http://192.168.0.x:631

Whereas these URL's do not:

- http://localhost/print
- http://127.0.0.1/print
- http://192.168.0.x/print

(Hopefully @deldesir has time later today to explain, and ideally suggest revisions arising from his PR #2775 !)

**Comment by holta** [comment]
@deldesir please give this a quick review today if you can!

PS this is well-tested on 32-bit RaspiOS Lite (RPi 4) and 64-bit Ubuntu Server 21.10 pre-release (VM).

**Comment by holta** [comment]
Quick Summary of this PR as excerpted/paraphrased from the new roles/cups/tasks/main.yml and install.yml:

- ADMINISTER CUPS AT http://box/print/admin WITH iiab-admin + ITS LINUX PASSWORD

- LET'S STICK MUCH CLOSER TO THE DEFAULT /etc/cups/cupsd.conf THX TO NEW NGINX (cups/templates/cups.conf) so that [roles/cups/tasks/install.yml](https://github.com/holta/iiab/blob/cups-nginx/roles/cups/tasks/install.yml) can be dramatically trimmed down.

- The NEW [roles/cups/templates/cups.conf](https://github.com/holta/iiab/blob/cups-nginx/roles/cups/templates/cups.conf) for `/etc/nginx/conf.d/cups.conf` FIXED URL'S LIKE: http://box/print, http://box.lan/print, http://192.168.0.x/print, http://172.18.96.1/print and http://10.8.0.x/print (WITH OR WITHOUT THE TRAILING SLASH!)  RECAP:

  1. So be it that these 2 URL'S STILL DON'T WORK: http://box:631, http://box.lan:631 (due to CUPS' internal web server's overly stringent hostname checks, i.e. '400 Bad Request')
  2. While these 2 CORE URL'S STILL ***DO*** WORK: http://localhost:631, http://127.0.0.1:631
  3. Whereas these 3 URL'S NO LONGER WORK: http://192.168.0.x:631, http://172.18.96.1:631, http://10.8.0.x:631 (now that we're suddenly hewing closer to the default /etc/cups/cupsd.conf)"

**Comment by deldesir** [comment]
Looks good to me.

**Review by deldesir — APPROVED** [review]
Good. I didn't notice the trailing slash issue earlier. Thanks for the patch @holta.

**Comment by holta** [comment]
Please if you can read IIAB's new CUPS **README.md** here:

https://github.com/iiab/iiab/tree/master/roles/cups

If anybody can offer improvements and/or clarifications to this document (for implementers and especially field communities wanting less complicated printing) that would be most appreciated!

**Comment by holta** [comment]
"CUPS 2.4 Coming Next Month, CUPS 2.5 + CUPS 3.0 Already In Planning"

Excerpt:

> An Open Printing micro-conference took place today during the Linux Plumbers Conference 2021 week. While it's hard to get excited about printers in 2021, it is exciting the renewed effort around CUPS with it now being back to effectively led by the community and CUPS founder Michael Sweet who left Apple. CUPS 2.4 is coming as the first feature release in quite a while and then CUPS 2.5 followed by CUPS 3.0 are already being talked about with features being discussed.

https://www.phoronix.com/scan.php?page=news_item&px=CUPS-2.4-Next-Year-Then-2.5-3.0

**Pull request merged**
