### PR TITLE
Install apache2 + its 'rewrite' mod in freepbx_dependencies.yml -- so roles/httpd can be phased out

### PR DESCRIPTION
**Pull request by holta**
Tested on Ubuntu Server 20.04 VM.  So that we're covered either way[*] &mdash; in preparation for:

- #2762
- PR #2850
- PR #2905

[*] Whether folks use `pbx_try_nginx: True` or `pbx_try_nginx: False` !  As outlined and implemented by:

- #2914
- PR #2916 
- PR #2917

### CODE REVIEW

**Comment by holta** [comment]
Just for the heck of it, fresh install testing of this PR #2920 is also underway on an RPi 4 running 64-bit Ubuntu Server 21.04, with FreePBX using Apache (default) instead of NGINX in this particular case.

(Just a reminder that FreePBX 16 cannot run on any OS with PHP < 7.4 -- which includes 32-bit RaspiOS.)

**Comment by jvonau** [comment]
Go back to the complete user setup stanza exactly the way it was, the ansible user module is very finicky with the options selected, you have been warned. Make the user www-data addition to asterisk group conditional on pbx_try_nginx 

The installation of apache might fail as port 80 is already occupied by nginx when apt installs the package.

**Comment by holta** [comment]
> ansible user module is very finicky with the options selected

No doubt.

Is there legit documentation that user 'asterisk' needs to be a system user?  (I don't see it, but if I'm looking in the wrong place LMK.)

Likewise, where do we have evidence that user 'asterisk' needs to be a member of groups 'audio' and 'dialout' ?  (There are bread crumbs from 2 decades ago, but so far I haven't seen anything that passes as authoritative.)

> Make the user www-data addition to asterisk group conditional on pbx_try_nginx

Good idea, and why not.  Done.

> The installation of apache might fail as port 80 is already occupied by nginx when apt installs the package.

Installing 'apache2' does not fail despite NGINX already using port 80, in 3 tests so far.

**Comment by jvonau** [comment]
> > ansible user module is very finicky with the options selected
> 
> No doubt.
> 
> Is there legit documentation that user 'asterisk' needs to be a system user? (I don't see it, but if I'm looking in the wrong place LMK.)
> 
> Likewise, where do we have evidence that user 'asterisk' needs to be a member of groups 'audio' and 'dialout' ? (There are bread crumbs from 2 decades ago, but so far I haven't seen anything that passes as authoritative.)
> 

You are quite welcome to gain hands on experience with what works and what doesn't, why not just toss other's judgements out the window because you haven't discovered why the hard way yet. Go on continue, can't teach those who don't want to be taught. teacher's hat off, good luck.

**Comment by holta** [comment]
There's circumstantial evidence that groups 'audio' and 'dialout' might still be relevant, still 2 decades later.  So there's an argument this might legitimately help a few implementers.

However adding user 'asterisk' as a system user appears to be a pure cargo cult.  But thankfully a relatively harmless cargo cult, likely having no ill effects.

**Comment by jvonau** [comment]
How about stopping the malarkey about official howtos and keep what is working as is, if the setup is working with the apache webserver running as www-data keep the setup as is, we have already deviated from the official `sudo sed -i 's/^\(User\|Group\).*/\1 asterisk/' /etc/apache2/apache2.conf`and if it's working don't mess with it, we are one up on the others... Or this the apache install half-baked and we just are too naive to know it? Keep it objective, one variable change at a time.

**Pull request merged**
