### PR TITLE
unbuntu field fix

### PR DESCRIPTION
**Pull request by jvonau**
Partial implementation of #178 and partial revert of #156 needed for fact gathering info.

### CODE REVIEW

**Comment by jvonau** [comment]
On the rpi's dhcpcd is pre-installed and functions without any entries in /etc/network/interfaces.  Think the intent was to allow **dhcpcd** control of all of the interfaces except for creation of the bridge, which does works as is on the rpi's. Now it appears that changing to manual works, but removing the entries should work also and that you can test by just removing the entries and rebooting. If that works ok, push this so we can see what a out of the box install offers before installing dhcpcd.

**Comment by georgejhunt** [comment]
This re-enables resolvconf, as well as fixing the reference to dhcp, which stalls dhcpcd. Is there any testing to show that resolvconf is properly configured, and does not cause long reboot?

**Comment by jvonau** [comment]
> 2017-09-09 17:14:28,254 p=9274 u=root |  TASK [network : in upgrade from earlier 6.2, delete the resolvconf] ************
2017-09-09 17:14:28,442 p=9274 u=root |  fatal: [127.0.0.1]: FAILED! => {"changed": false, "failed": true, "msg": "unsupported parameter for module: enabled"}
2017-09-09 17:14:28,442 p=9274 u=root |  ...ignoring

Think the task failed and resolvconf was left installed if it was
> 2017-09-09 17:14:28,454 p=9274 u=root |  TASK [network : Get the dhcp client daemon used in recent raspbian] ************
2017-09-09 17:14:36,195 p=9274 u=root |  changed: [127.0.0.1]
2017-09-09 17:14:36,206 p=9274 u=root |  TASK [network : for upgrades from earlier 6.2, remove br0 file] ****************
2017-09-09 17:14:36,326 p=9274 u=root |  ok: [127.0.0.1]
2017-09-09 17:14:36,338 p=9274 u=root |  TASK [network : default to lan controller] *************************************
2017-09-09 17:14:36,359 p=9274 u=root |  skipping: [127.0.0.1]
2017-09-09 17:14:36,371 p=9274 u=root |  TASK [network : Copy the bridge script -- was in interfaces.d/] ****************
2017-09-09 17:14:36,606 p=9274 u=root |  changed: [127.0.0.1]
2017-09-09 17:14:36,617 p=9274 u=root |  TASK [network : start up the dhcpcd service] ***********************************
2017-09-09 17:14:36,785 p=9274 u=root |  fatal: [127.0.0.1]: FAILED! => {"changed": false, "failed": true, "msg": "Unable to start service dhcpcd: Job for dhcpcd.service failed because the control process exited with error code. See \"systemctl status dhcpcd.service\" and \"journalctl -xe\" for details.\n"}
2017-09-09 17:14:36,786 p=9274 u=root |  	to retry, use: --limit @/opt/iiab/iiab/iiab.retry
2017-09-09 17:14:36,786 p=9274 u=root |  PLAY RECAP *********************************************************************
2017-09-09 17:14:36,786 p=9274 u=root |  127.0.0.1                  : ok=195  changed=122  unreachable=0    failed=1   

This one was using the debian.yml path

**Comment by jvonau** [comment]
Revised PR to just to gather data, no conflict with #238 just not forcing the install.

**Comment by jvonau** [comment]
@georgejhunt Don't be so fast with the close button, can you reopen this as the branch was updated to exclude your objection about resolvconf or should I just open a new PR?

**Pull request closed without merging**
