### PR TITLE
scripts/ansible: Minor readability tweaks

### PR DESCRIPTION
**Pull request by holta**
Ref: PR #2690

### CODE REVIEW

**Comment by tim-moody** [comment]
`CURR_VER=undefined` 
is an oxymoron.

**Comment by holta** [comment]
> `CURR_VER=undefined`
> is an oxymoron.

I think this is a legacy of @jvonau or @georgejhunt wanting vars described/declared near the top of the file to make the code generally readable.  Which is a very reasonable ask, even if declaring some vars like CURR_VER and GOOD_VER isn't adding a whole lot of value in this case, for sure.  As both are barely used at all (!)

**Comment by holta** [comment]
FYI this PR was tested on Ubuntu 20.04

**Comment by holta** [comment]
Conversely, I can strip out bash's `-e` flag completely if others (@jvonau ?) believe it's basically useless.

**Comment by jvonau** [comment]
> Conversely, I can strip out bash's `-e` flag completely if others (@jvonau ?) believe it's basically useless.

Bad idea, you want the install to stop dead should any of the commands fail resulting in ansible not being full installed perhaps due to network issues at the user's location.

**Pull request merged**
