### PR TITLE
OPWEN_SETTINGS

### PR DESCRIPTION
**Pull request by jvonau**
From an install.py machine where supervisord is used this value is passed
pi@jv-rpi-stock:~ $ cat /etc/supervisor/conf.d/lokole_gunicorn.conf
[program:lokole_gunicorn]
command="/lokole/venv/bin/gunicorn" --bind="unix:/lokole/state/lokole_gunicorn.sock" --timeout=300 --workers=3 --log-level=error opwen_email_client.webapp:app
autostart=true
autorestart=true
startretries=3
stopasgroup=true
stderr_logfile=/lokole/logs/lokole_gunicorn.stderr.log
stdout_logfile=/lokole/logs/lokole_gunicorn.stdout.log
user=root
environment=OPWEN_SETTINGS=/lokole/state/settings.env

### CODE REVIEW

**Comment by jvonau** [comment]
https://github.com/ascoderu/lokole/issues/454#issuecomment-695786351
https://github.com/ascoderu/lokole/blob/master/opwen_email_client/webapp/config.py#L11

**Comment by jvonau** [comment]
@adamsclafani Think this one is the root cause of the registration failure, doesn't know where to write the values.

**Comment by jvonau** [comment]
quick test on an installed machine would be to edit /home/lokole/state/webapp_secrets.sh adding:
export OPWEN_SETTINGS='/home/lokole/state/settings.env'

**Comment by adamsclafani** [comment]
Another missing variable strikes again. 

[Here](https://github.com/ascoderu/lokole/blob/aa7ac119361d425e4e9f28a7c85e3002e9252855/opwen_email_client/webapp/forms/register.py#L42) is the function that sets up the path, which is used in the registration routine to write the values. The install script used the same method to setup the path, so I basically copied that into the path setup function. I think there is a bug here that is also messing things up with the [returned path that is used](https://github.com/ascoderu/lokole/blob/aa7ac119361d425e4e9f28a7c85e3002e9252855/opwen_email_client/webapp/forms/register.py#L54). Now that I'm looking at things, I don't think all this extra path setup code is necessary.

**Comment by adamsclafani** [comment]
Just in case anyone else wants to know what is going on :)

[Here](https://github.com/ascoderu/lokole/blob/aa7ac119361d425e4e9f28a7c85e3002e9252855/opwen_email_client/webapp/actions.py#L233) is the routine which was supposed to be initiated as a background task via celery by the register.delay() [call](https://github.com/ascoderu/lokole/blob/aa7ac119361d425e4e9f28a7c85e3002e9252855/opwen_email_client/webapp/forms/register.py#L40) , which was being blocked by the server throwing an unexpected status code and failing the [check](https://github.com/ascoderu/lokole/blob/aa7ac119361d425e4e9f28a7c85e3002e9252855/opwen_email_client/webapp/forms/register.py#L38), which we messed around with yesterday. When I removed the check upon registering hawaii9, register.delay() should have been initiated. I do think that a malformed/missing path is part of the problem.

**Comment by jvonau** [comment]
[install.py](https://github.com/ascoderu/lokole/blob/master/install.py#L421-L461) has some added [headers](https://github.com/ascoderu/lokole/blob/master/install.py#L425-L426) add to the request that is sent.

**Comment by jvonau** [comment]
> Another missing variable strikes again.
> 
> [Here](https://github.com/ascoderu/lokole/blob/aa7ac119361d425e4e9f28a7c85e3002e9252855/opwen_email_client/webapp/forms/register.py#L42) is the function that sets up the path, which is used in the registration routine to write the values. The install script used the same method to setup the path, so I basically copied that into the path setup function. I think there is a bug here that is also messing things up with the [returned path that is used](https://github.com/ascoderu/lokole/blob/aa7ac119361d425e4e9f28a7c85e3002e9252855/opwen_email_client/webapp/forms/register.py#L54). Now that I'm looking at things, I don't think all this extra path setup code is necessary.

Think I agree, that was one of the routines I brute forced around.

**Comment by adamsclafani** [comment]
The headers were explicitly laid out in the install script due to the usage of the more basic url lib. The requests package is a bit higher level should handle the json/content length automatically. 

On another note, the server is indeed returning a successful  201 created status code, not 200 (which is what the check assumed). Fired up a python interpreter session and made a quick script to register the client hawaii10.

**Comment by jvonau** [comment]
lets push this for now

**Comment by jvonau** [comment]
> On another note, the server is indeed returning a successful 201 created status code, not 200 (which is what the check assumed). Fired up a python interpreter session and made a quick script to register the client hawaii10.

Tried the same 201 change, form completes but dug this out of celery.service 
```
ay 20 04:06:57 box.lan celery[21191]: [2021-05-20 04:06:57,281: INFO/MainProcess] Received task: opwen_email_client.webapp.tasks.register[f65a7e9d-3e32-4765-a03b-4efac1e05982]
May 20 04:07:22 box.lan celery[21265]: [2021-05-20 04:07:22,987: ERROR/ForkPoolWorker-2] Task opwen_email_client.webapp.tasks.register[f65a7e9d-3e32-4765-a03b-4efac1e05982] raised unexpected: AttributeError("'ClientRegister' object has no attribute 'client_name'")
May 20 04:07:22 box.lan celery[21265]: Traceback (most recent call last):
May 20 04:07:22 box.lan celery[21265]:   File "/library/lokole/venv/lib/python3.8/site-packages/celery/app/trace.py", line 412, in trace_task
May 20 04:07:22 box.lan celery[21265]:     R = retval = fun(*args, **kwargs)
May 20 04:07:22 box.lan celery[21265]:   File "/library/lokole/venv/lib/python3.8/site-packages/celery/app/trace.py", line 704, in __protected_call__
May 20 04:07:22 box.lan celery[21265]:     return self.run(*args, **kwargs)
May 20 04:07:22 box.lan celery[21265]:   File "/library/lokole/venv/lib/python3.8/site-packages/opwen_email_client/webapp/tasks.py", line 91, in register
May 20 04:07:22 box.lan celery[21265]:     client_register()
May 20 04:07:22 box.lan celery[21265]:   File "/library/lokole/venv/lib/python3.8/site-packages/opwen_email_client/webapp/actions.py", line 296, in __call__
May 20 04:07:22 box.lan celery[21265]:     opwen_settings = self._format_settings()
May 20 04:07:22 box.lan celery[21265]:   File "/library/lokole/venv/lib/python3.8/site-packages/opwen_email_client/webapp/actions.py", line 266, in _format_settings
May 20 04:07:22 box.lan celery[21265]:     'OPWEN_CLIENT_NAME': self.client_name.data.strip(),
May 20 04:07:22 box.lan celery[21265]: AttributeError: 'ClientRegister' object has no attribute 'client_name'

```

**Comment by jvonau** [comment]
>May 20 06:31:00 box.lan celery[26276]: [2021-05-20 06:31:00,562: INFO/MainProcess] Received task: opwen_email_client.webapp.tasks.sync[4d6aacda-e68b-47b9-b989-e570cf05676b]
May 20 06:31:00 box.lan celery[26282]: [2021-05-20 06:31:00,569: ERROR/ForkPoolWorker-2] Task opwen_email_client.webapp.tasks.sync[4d6aacda-e68b-47b9-b989-e570cf05676b] raised unexpected: TypeError('gethostbyname() argument 1 must be str, bytes or bytearray, not None')
May 20 06:31:00 box.lan celery[26282]: Traceback (most recent call last):
May 20 06:31:00 box.lan celery[26282]:   File "/library/lokole/venv/lib/python3.8/site-packages/celery/app/trace.py", line 412, in trace_task
May 20 06:31:00 box.lan celery[26282]:     R = retval = fun(*args, **kwargs)
May 20 06:31:00 box.lan celery[26282]:   File "/library/lokole/venv/lib/python3.8/site-packages/celery/app/trace.py", line 704, in __protected_call__
May 20 06:31:00 box.lan celery[26282]:     return self.run(*args, **kwargs)
May 20 06:31:00 box.lan celery[26282]:   File "/library/lokole/venv/lib/python3.8/site-packages/opwen_email_client/webapp/tasks.py", line 41, in sync
May 20 06:31:00 box.lan celery[26282]:     if check_connection(AppConfig.EMAIL_SERVER_HOSTNAME, 80):
May 20 06:31:00 box.lan celery[26282]:   File "/library/lokole/venv/lib/python3.8/site-packages/opwen_email_client/util/network.py", line 7, in check_connection
May 20 06:31:00 box.lan celery[26282]:     host = gethostbyname(hostname)
May 20 06:31:00 box.lan celery[26282]: TypeError: gethostbyname() argument 1 must be str, bytes or bytearray, not None

**Comment by adamsclafani** [comment]
Aha, missing variable again. 

Adding OPWEN_EMAIL_SERVER_HOSTNAME = 'mailserver.lokole.ca' to the webapp secrets file should do the trick

**Comment by jvonau** [comment]
testing the addition in new PR seems to work but starts to spam the mailserver as noted in the new PR.

**Pull request merged**
