### PR TITLE
Reverse Proxy Cups with Nginx

### PR DESCRIPTION
**Pull request by deldesir**
### Fixes bug: 
CUPS is now accessible via http://box.lan/print/

### Description of changes proposed in this pull request:
Created nginx.yml task and corresponding templates

### Smoke-tested on which OS or OS's: 
Ubuntu 20.10

### Mention a team member @username e.g. to help with code review:
@holta

### CODE REVIEW

**Comment by holta** [comment]
Awesome.

@georgejhunt can you review this PR ?

Ref: #2766

**Comment by tim-moody** [comment]
@deldesir thanks for your help on this. There's more where it came from.

**Comment by deldesir** [comment]
> 
> 
> @deldesir thanks for your help on this. There's more where it came from.

Yes, you're right @tim-moody. The "additional" directives (the WebSocket part) from https://anthe.studio/blog/en/cups-nginx-reverse-proxy that I choosed to ignore would throw "Unable to encrypt connection: The TLS connection was non-properly terminated". I don't have any idea right now why it won't work with them. I also choose not to disable Cups authentication because I didn't notice any pages fail to load or load infinitely as stated in the aforementioned article. I'd be glad to learn from any improvements anyone could add to it.


Here is the output of /var/log/cups/error.log : https://paste.ubuntu.com/p/B7FSdfw3Nj/

**Comment by tim-moody** [comment]
@deldesir IIAB doesn't use TLS (https) because self-signed certificates cause the browser to tell users not to use the site. I'm not sure if web sockets are the same, but web workers don't work unless there is TLS.

**Comment by jvonau** [comment]
>E [04/May/2021:16:16:35 -0400] Hostname lookup for "{{ lan_ip }}" failed.
E [04/May/2021:16:16:35 -0400] Bad Listen address {{ lan_ip }}:631 at line 4.

{{ lan_ip }}:631 something is wrong with the cupsd.conf template that should be an ip address
>E [04/May/2021:16:16:35 -0400] Unable to open listen socket for address [v1.::1]:631 - Cannot assign requested address.

Looks to be a ipv6 notation, think that is because ipv6 is disabled globally.

**Comment by holta** [comment]
> {{ lan_ip }}:631 something is wrong with the cupsd.conf template that should be an ip address

@deldesir can you look into this before this PR gets merged?

(Nobody is asking for perfection, but better to fix things now if they turn out to be fixable!)

**Comment by deldesir** [comment]
> Looks to be a ipv6 notation, think that is because ipv6 is disabled globally.

Not an elegant solution, but I would suggest to comment out L4 in cupsd.conf for now since IIAB focus on IPv4.

**Comment by holta** [comment]
> Not an elegant solution, but I would suggest to comment out L4 in cupsd.conf for now since IIAB focus on IPv4.

Does that also solve the following?

> E [04/May/2021:16:16:35 -0400] Hostname lookup for "{{ lan_ip }}" failed.
> E [04/May/2021:16:16:35 -0400] Bad Listen address {{ lan_ip }}:631 at line 4.

(Apologies I don't know where @jvonau's above 2 lines come from, but hopefully you or he can shed light to help others understand.)

**Comment by holta** [comment]
@deldesir: what final testing is most needed before this PR gets merged?

(And/or summarize what testing you've already done, Thanks!)

**Comment by deldesir** [comment]
> 
> Above two lines come from my own cups log. The timestamps from the "pastebin" look the same.
> I discover another thing. Changing from `Listen localhost:631;` to `Listen 127.0.0.1;` in cupsd.conf seems to supress error:
> E [04/May/2021:16:16:35 -0400] Unable to open listen socket for address [v1.::1]:631 - Cannot assign requested address.
> It shouldn't since I always knew IPV6 doesn't take precedence over IPV4 resoving from http://localhost.

This explains it (or, does it?):
https://unix.stackexchange.com/questions/530976/why-does-localhost-resolve-to-1-but-not-127-0-0-1

**Comment by deldesir** [comment]
@jvonau and Do you think https://unit.nginx.org/ can be useful here? I am willing to invest some time in it if it can lead to some better handling of reverse proxying in general. I just want to be sure I am not doing anything that would go off the networking path settled for IIAB.

**Comment by jvonau** [comment]
> @jvonau and Do you think https://unit.nginx.org/ can be useful here? I am willing to invest some time in it if it can lead to some better handling of reverse proxying in general. I just want to be sure I am not doing anything that would go off the networking path settled for IIAB.

https://nginx.org/en/docs/http/ngx_http_upstream_module.html
That might be worth while, you thinking of using something like?
upstream cups_backend
server unix:/var/run/cups/cups.sock

**Comment by holta** [comment]
@deldesir let's not forget to update this NGINX status document:

https://github.com/iiab/iiab/blob/master/roles/nginx/README.md

(Either as part of this PR, or as follow-up soon after, either is fine!)

Ref: #2762

**Comment by jvonau** [comment]
> > @jvonau and Do you think https://unit.nginx.org/ can be useful here? I am willing to invest some time in it if it can lead to some better handling of reverse proxying in general. I just want to be sure I am not doing anything that would go off the networking path settled for IIAB.
> 
> https://nginx.org/en/docs/http/ngx_http_upstream_module.html
> That might be worth while, you thinking of using something like?
> upstream cups_backend
> server unix:/var/run/cups/cups.sock

Kind of like the setup in #2776

**Comment by holta** [comment]
@deldesir do you still recommend this PR?

(Removing Apache completely may be a long-term goal for 2021, but we also need quick/efficient decisions to move us forward here, Thanks!!)

**Comment by holta** [comment]
We got burned by the trailing slash again:

- http://192.168.0.182/print/ works!
- http://192.168.0.182/print does not!

I'll now work on patching this up, as part of:

- PR #2858

Thanks @deldesir for your patience over 10 weeks.  Now the test plan is more clear.

**Pull request merged**
