### PR TITLE
scripts/ansible: apt-key command is going away, so load .gpg key from repo

### PR DESCRIPTION
**Pull request by holta**
Tested on Ubuntu 21.04

Certainly we don't know the future of distro norms for the coming decade, but this WIP enhances discoverability by allowing `iiab-ansible-keyring.gpg` to be findable in directory `/usr/share/keyrings`, which appears to be the general/evolving recommendation going forward.

Builds on @jvonau's PR #2747

Refs: #2721, PR #2742, PR #2743

### CODE REVIEW

**Comment by jvonau** [comment]
Think this PR is an example of bad engineering see comment in https://github.com/iiab/iiab/pull/2747#issuecomment-825282805

**Comment by holta** [comment]
Discoverability and understandability are very high priorities in my view of software engineering.

We'll have to disagree on this small matter, and that's ok.

e.g. if in future `/usr/local/share/keyrings` becomes a truly established norm (i.e. enhancing discoverability) we can go with that.

**Comment by holta** [comment]
Humbly disagree.

Time to dial back the vitriol.

**Comment by jvonau** [comment]
>ubuntu@box:~$ dpkg -S /usr/share/keyrings
ubuntu-advantage-tools, ubuntu-keyring: /usr/share/keyrings

**Comment by holta** [comment]
32-bit RaspiOS:
```
root@box:~# dpkg -S /usr/share/keyrings
raspbian-archive-keyring: /usr/share/keyrings
```
64-bit RaspiOS, Debian 10 & 11 RC1:
```
root@box:~# dpkg -S /usr/share/keyrings
debian-archive-keyring: /usr/share/keyrings
```
Linux Mint 20:
```
root@box:~# dpkg -S /usr/share/keyrings
ubuntu-advantage-tools, linuxmint-keyring, ubuntu-dbgsym-keyring, ubuntu-keyring: /usr/share/keyrings
```

**Comment by jvonau** [comment]
Above dpkg is showing joint ownership of the /usr/share/keyrings/ directory by the various deb packages installed. Seems to support my notion of /usr/share/keyrings/ being apt managed and intended to be reserved for apt packaged distro os keys.

**Comment by holta** [comment]
FWIW here are a few keyrings having little to do with the core OS, currently being installed in `/usr/share/keyrings` :

```
/usr/share/keyrings/nodesource.gpg
/usr/share/keyrings/ubuntu-advantage-cis.gpg
/usr/share/keyrings/ubuntu-advantage-esm-apps.gpg
/usr/share/keyrings/ubuntu-advantage-esm-infra-trusty.gpg
/usr/share/keyrings/ubuntu-advantage-fips.gpg
```

When the dust settles (might take a couple years) IIAB will follow Linux norms.

Regardless whether various norms like `/usr/local/share/keyrings` take off, or possibly a more modern form of key management.  As https://en.wikipedia.org/wiki/APT_(software) hopefully evolves towards stronger security (and less of that other APT, https://en.wikipedia.org/wiki/Advanced_persistent_threat) almost a quarter century after apt-the-packaging-tool was born in 1997-1999 (Windows 95 era).

Likewise, IIAB currently installs more than 30 things in `/usr/bin` even when `/usr/local/bin` is very standardized for similar such situations.  If there are truly legit reasons to later move things in one direction or another (and change documentation, expectations, painful but sometimes necessary) then so be it &mdash; that too can happen in future.

**Comment by tim-moody** [comment]
Think it's fine for iiab to have its own packages store keys in keyrings. I don't think we should store the keys of others there.

**Comment by jvonau** [comment]
> /usr/share/keyrings/ubuntu-advantage-cis.gpg
> /usr/share/keyrings/ubuntu-advantage-esm-apps.gpg
> /usr/share/keyrings/ubuntu-advantage-esm-infra-trusty.gpg
> /usr/share/keyrings/ubuntu-advantage-fips.gpg


Those ubuntu-advantage keys are part of a installed .deb https://packages.ubuntu.com/hirsute/arm64/ubuntu-advantage-tools/filelist
 
> When the dust settles (might take a couple years) IIAB will follow Linux norms.
> 

The dust never settles, constant churn.

> Regardless whether various norms like `/usr/local/share/keyrings` take off, or possibly a more modern form of key management. 

> Above dpkg is showing joint ownership of the /usr/share/keyrings/ directory by the various deb packages installed. Seems to support my notion of /usr/share/keyrings/ being apt managed and intended to be reserved for apt packaged distro os keys.

Just to put this to bed, /usr/share/keyrings/ is being [encouraged](https://wiki.debian.org/DebianRepository/UseThirdParty?action=show&redirect=RepositoryInstructions) as the new norm, leaving the mongodb and yarn roles to be updated away from apt-key.

**Pull request merged**
