### PR TITLE
Revert PR #3815: python3-cryptography no longer needed

### PR DESCRIPTION
**Pull request by holta**
Pulling together conclusion from a month ago, thanks to new upstream cleanup:

- PR #3815 
- janeczku/calibre-web#3183
- iiab/calibre-web#264
- PR iiab/calibre-web#275

### CODE REVIEW

**Comment by holta** [comment]
This PR is being merged aggressively so @EMG70 can do a quick install test of IIAB Calibre-Web ASAP, onto any "SAFE" OS !

(i.e. almost any OS except for Ubuntu 24.10 and 25.04, until @deldesir resolves iiab/calibre-web#267 !)

Thanks @EMG70  if possible !!

**Comment by EMG70** [comment]
A new 24.04 fresh VM was installed.
SUDO-IIAB-DIAGNOSTICS - https://paste.centos.org/view/d48904fa
I managed to download a Youtube video  https://www.youtube.com/watch?v=67jolgTfaLU without any issues.
Screenshot From 2024-10-27 17-19-03

**Comment by holta** [comment]
> https://paste.centos.org/view/d48904fa
> I managed to download a Youtube video https://www.youtube.com/watch?v=67jolgTfaLU without any issues.

Huge Thanks @EMG70 !

**Comment by holta** [comment]
> A new 24.04 fresh VM was installed.

Oops I forgot to mention Raspberry Pi OS testing is even more important here.

_(So hopefully someone can confirm that too soon!)_

**Comment by EMG70** [comment]
A new IIAB Unittest test was installed on Rapsberry PI 400 (64 Bit lite)  .
IIAB-DIAGNOSTICS - https://paste.centos.org/view/040cf9ba
 I managed to download the same Youtube video https://www.youtube.com/watch?v=67jolgTfaLU as done on 24.04  without any issues.
Screenshot From 2024-10-27 20-46-18

**Comment by holta** [comment]
> A new IIAB Unittest test was installed on Rapsberry PI 400 (64 Bit lite) .
> IIAB-DIAGNOSTICS - https://paste.centos.org/view/040cf9ba
> I managed to download the same Youtube video

Incredible news, Thank You @EMG70 🤠

**Pull request merged**
