### PR TITLE
http://box/info/admin-console offline docs [& fix iiab-refresh-wiki-docs e.g. for scraping of Raspberry Pi Images docs]

### PR DESCRIPTION
**Pull request by holta**
Thanks @deldesir for the suggestion.

Tested on Ubuntu 23.04 daily build.

### CODE REVIEW

**Comment by holta** [comment]
CLARIF: The 3 docs were moved to abide by GitHub wiki's rules &mdash; characters like `:` are not allowed in wiki titles.
FYI this also prevented offline browsing with relative links, so all the more reason to abide by their rules/recommendations:

https://docs.github.com/en/communities/documenting-your-project-with-wikis/adding-or-editing-wiki-pages#about-wiki-filenames

In conclusion, the 3 new doc URL's are:

- https://github.com/iiab/iiab/wiki/Raspberry-Pi-Images-~-Summary
- https://github.com/iiab/iiab/wiki/Raspberry-Pi-Images-~-Installation
- https://github.com/iiab/iiab/wiki/Raspberry-Pi-Images-~-Features

(All 3 are "scraped" properly to http://box/info by this PR.)

**Comment by tim-moody** [comment]
please rename variable ADMINCONSOLEPATH to ADMINDOCSPATH to avoid confusion with /opt/admin

**Comment by holta** [comment]
@deldesir this cleanup was overdue for other reasons as well:

The `/usr/bin/iiab-refresh-wiki-docs` command (to update all docs within http://box/info) should now be substantially more resilient going forward!

**Comment by holta** [comment]
@deldesir one way to test this PR on top of an existing IIAB:

```
sudo su -
cd /opt/iiab/iiab
git switch -c refresh-wiki-docs    # Optional (create a new local branch)
git pull https://github.com/holta/iiab refresh-wiki-docs

./runrole www_base       # Then hit <Enter> twice
./runrole www_options    # Then hit <Enter> twice

iiab-refresh-wiki-docs
```

_(If that works, browse http://box/info and verify that important links work.)_

**Comment by deldesir** [comment]
Thanks. This is helpful.

**Review by deldesir — APPROVED** [review]
Tested on Ubuntu 22.10. It works as expected 👍

**Pull request merged**
