### PR TITLE
phpmyadmin was never migrated to nginx -- missing shim config file

### PR DESCRIPTION
**Pull request by georgejhunt**
The current master has access to mysql "root" user (with all privileges) wide open. But phpmyadmin fails to open a mysql server with a blank password. (The mysql client does provide root privilege without password) -- so it is possible for our end users to remedy the situation.

I do question whether we want to leave mysql root user wide open in the long run since mysql is now a standard service. 

I searched our docs, FAQ, default_vars.yml, and mysql role, without finding any reference to mysql security.

I was able to log into phymyadmin by executing the following string in mysql client:
```
 grant all on * to ghunt identified by "<password>"
```
and then I could start phpmyadin on a clean install of current raspi-os lite.

### CODE REVIEW

**Comment by holta** [comment]
@georgejhunt huge thanks for digging into this.

@tim-moody or @jvonau do you have time to review this PR?

**Comment by jvonau** [comment]
https://github.com/iiab/iiab/pull/2488 has some user table notes for comparison can you 
`sudo mysql -u root`
`select user,host,password,plugin from mysql.user;`

> grant all on * to ghunt identified by "<password>"

Not sure this is really need, Can you post these contents from the myphpadmin's config.inc.php file please
>$cfg['Servers'][$i]['host']          = '127.0.0.1'; // MySQL hostname or IP address
$cfg['Servers'][$i]['port']          = '';          // MySQL port - leave blank for default port
$cfg['Servers'][$i]['socket']        = '';          // Path to the socket - leave blank for default socket
$cfg['Servers'][$i]['connect_type']  = 'tcp';       // How to connect to MySQL server ('tcp' or 'socket')
$cfg['Servers'][$i]['extension']     = 'mysqli';    // The php MySQL extension

Above taken from https://www.digitalocean.com/community/questions/cannot-log-in-to-the-mysql-server-without-code-using-phpmyadmin-on-centos7

**Comment by jvonau** [comment]
https://github.com/iiab/iiab/blob/master/roles/phpmyadmin/templates/config.inc.php is supplied, we need to update some values.
connect_type should use socket to connect to the backend database

**Comment by holta** [comment]
@georgejhunt is busy polishing off JupyterHub Notebooks (PR #2733) and some important ~10GB content packs (#2695 Etc) — but when there's a break in coming weeks — let's finalize this PR so phpMyAdmin is legit.

**Comment by holta** [comment]
@deldesir here's another NGINX task for 2021.

FYI it is low-priority, as few people use [phpmyadmin](https://github.com/iiab/iiab/tree/master/roles/phpmyadmin).

Still, cleaning up [NGINX](https://github.com/iiab/iiab/tree/master/roles/nginx) to fully deprecate [Apache](https://github.com/iiab/iiab/blob/master/roles/3-base-server/tasks/main.yml#L11-L18) before the end of the year would be really great &mdash; 2 years after the transition began in November 2019.  As is being tracked in these 3 places:

- https://github.com/iiab/iiab/blob/master/roles/nginx -> README.md
- #2762 "Notes: Stalled progress on nginx front"
- [roles/3-base-server/tasks/main.yml#L11-L18](https://github.com/iiab/iiab/blob/master/roles/3-base-server/tasks/main.yml#L11-L18)

**Comment by holta** [comment]
RG in India asks if this PR-or-similar can be reconsidering for his IIAB field implementation.

I've asked if he's able to contribute, help to refine and test this PR to possibly make this happen?

Refs:

- #2924

**Comment by holta** [comment]
@rickgurmet:

What are you using phpMyAdmin for in the field for schools or communities in India &mdash; can you say just a bit more as to how you use this?

**Comment by rickgurmet** [comment]
> @rickgurmet:
> 
> What are you using phpMyAdmin for in the field for schools or communities in India — can you say just a bit more as to how you use this?

We are making local content for the villagers and we are developing some web applications using PHP, Mysql, etc, so in order to manage the database easily, we require phpMyAdmin.

**Comment by holta** [comment]
> We are making local content for the villagers and we are developing some web applications using PHP, Mysql, etc, so in order to manage the database easily, we require phpMyAdmin.

Thank you @rickgurmet.

Your explanation helps everybody understand & contextualize.

Such that this might be fixed going forward.

**Comment by holta** [comment]
@georgejhunt can you try the 1-button rebase please?

To avoid "Files changed 417" (as is currently shown above, making it nearly impossible to understand this PR!)

The 1-button rebase is near the top-right of:
https://github.com/georgejhunt/iiab/tree/phpmyadmin

Look for the "Fetch upstream" button, just above the code.

Thanks!

**Comment by holta** [comment]
> The 1-button rebase is near the top-right of: https://github.com/georgejhunt/iiab/tree/phpmyadmin
> 
> Look for the "Fetch upstream" button, just above the code.

Clarif: you need to be logged into GitHub's website of course 👍

**Comment by georgejhunt** [comment]
The one button rebase does not work for me.

**Pull request merged**
