### PR TITLE
stretch seems to have dependency hell about the requirements for npm …

### PR DESCRIPTION
**Pull request by georgejhunt**
…-- give it time, and disable for now

### CODE REVIEW

**Comment by holta** [comment]
@georgejhunt when you say "disable for now", do you recommend we disable Sugarizer in IIAB 6.4?

(If so presumably trying to get it work in IIAB 6.5 later this year?)

Ref #193 'Ansible fails all subsequent runs on Raspbian Stretch: Sugarizer "npm : Depends: node-gyp (>= 0.10.9)"'

**Comment by georgejhunt** [comment]
Smoke tested on VM

**Comment by jvonau** [comment]
since npm is being used to install nodejs perhaps installing the native [nodejs](https://packages.debian.org/stretch/nodejs) package would be enough to satisfy this dependency and might be a better long term solution?  
edit: Never mind it's is flaky on [debian](https://anonscm.debian.org/cgit/collab-maint/nodejs.git/log/?id=refs/heads/master-6.x) but looks like 6.X is available but not sure of the apt magic to get it, might be the setup routine that is already enabled.

**Comment by georgejhunt** [comment]
npn fails on second attempt to reinstall. We should test for installed npm, and don't try to reinstall

**Pull request closed without merging**
