### PR TITLE
New Transmission playbook: eases KA Lite downloads using BitTorrent

### PR DESCRIPTION
**Pull request by arky**
### Fixes Bug #884
https://github.com/iiab/iiab/issues/884

### Description of changes proposed in this pull request.
This adds a new playbook for transmission-daemon. The provisioning system adds ka-lite torrents for download.

### Smoke-tested in operating system.

Smoke tested on Debian 10 i586 machine. 

The ports 9091 51413 needs to be opened for WAN and local lan. 

### Mention a team member for further information or comment using @ name
@holta

### CODE REVIEW

**Review by arky — COMMENTED** [review]
In future, please kindly refrain from submitting such large changes via PR reviews. 

I can not approve these changes because I don't have credentials on the main repo.  :(

**Comment by holta** [comment]
> In future, please kindly refrain from submitting such large changes via PR reviews.

I'm not understanding: is there a better way to co-evolve suggestions around large amounts of text needing copy-editing like this?  You can certainly revert any changes (such as those I proposed, as mentioned earlier, all are merely suggestions) or is that not true for some reason?

https://github.com/arky/iiab/tree/transmission/roles/transmission

**Comment by holta** [comment]
Correction, this is what I'm trying to offer suggestions around:

https://github.com/arky/iiab/blob/transmission/roles/transmission/README.rst

**Comment by holta** [comment]
Clarif: no collaboration software is perfect (not even close, even SW like Trello, Slack, Asana, etc specialized around community workflows...that we should be aware of if not considering?) but in any case let's also try to find innovative ways within GitHub itself...to cultivate contributions from all...during different phases from design-to-QA-to-product, if at all possible!

**Pull request merged**
