### PR TITLE
Rename local_vars_min.yml to local_vars_small.yml, local_vars_big.yml to local_vars_large.yml (ETC)

### PR DESCRIPTION
**Pull request by holta**
_It will take Many Days to fix documentation in countless different places,_ to correspond to the {S, M, L} lingo (just like T-Shirt sizes) that essentially everyone prefers.

But these 2 PR's are the 1st Step.

At Long Last &mdash; see also this Companion PR:

- https://github.com/iiab/iiab-factory/pull/193

### CODE REVIEW

**Comment by tim-moody** [comment]
how about renaming unittest to local_vars_zero. should it have apache_allow_sudo: True? And I don't think vpn should be enabled.

**Comment by holta** [comment]
Good questions.

So a clarification is definitely in order:

local_vars_unittest.yml has been an absolute lifesaver for unit-testing (of individual Ansible roles especially) over the past 2-3 months &mdash; it has allowed for a tremendously accelerated workflow used by many testing folk old and new &mdash; who need VPN access right away so that collaboration is nearly completely hassle-free.  (Allowing IIAB testing feedback to become increasingly far more efficient-and-meaningful than it was the past, a big step forward compared to even 3 months ago.)  This push to make the testing community growth as completely obstacle-free and hassle-free as possible is indeed critical towards allowing IIAB to scale.  In that light, as much as possible anyway, the particular filename should really should reflect what it's being used for most (which is in fact unit testing, in this particular case).  Whereas another stock local_vars.yml file might be advisable, for those who want something more completely bare bones.

**Comment by holta** [comment]
> should it have apache_allow_sudo: True?

I'm assuming this default value remains fine across the board at this time, and is also useful to allow everyone to try & test the http://box/common/services/power_off.php "OFF BUTTON" hidden near the bottom of many/most IIAB main pages (http://box.lan).

But possibly this variable should be renamed to `nginx_allow_sudo` in future?

**Comment by tim-moody** [comment]
>Whereas another stock local_vars.yml file might be advisable, for those who want something more completely bare bones.

I'll add one

**Comment by jvonau** [comment]
How about a heads-up that the primary local_vars.yml files were to be renamed, kind of messes up automated workflows where `cp vars/local_vars_min.yml /etc/iiab/local_vars.yml` was used. Easy to change on my end but a hey this is changing would be nice in the future.

**Pull request merged**
