### PR TITLE
U17: Ubuntu 17.10 preparations

### PR DESCRIPTION
**Pull request by jvonau**
### Fixes Bug
#502 
### Description of changes proposed in this pull request.
add support and ckeanup
### Smoke-tested in operating system.
developmental for ubuntu-17+

### CODE REVIEW

**Comment by holta** [comment]
@jvonau is this smoke-tested and/or safe enough to push for @floydianslips & @deldesir ?

**Comment by jvonau** [comment]
This is present on Ubuntu and Debian as a means to detect if dhcpcd is installed as Raspbian does install dhcpcd as the exception, moves the logic to local_facts to avoid using shell in ansible. Fix in the last commit.
> 00:10:25.118 ==> debian: TASK [network : check to see if dhcpcd is installed and active - Can Fail] *****
00:10:25.346 ==> debian: fatal: [127.0.0.1]: FAILED! => {"changed": true, "cmd": "systemctl is-enabled dhcpcd", "delta": "0:00:00.011752", "end": "2017-11-09 13:20:55.310082", "failed": true, "msg": "non-zero return code", "rc": 1, "start": "2017-11-09 13:20:55.298330", "stderr": "Failed to get unit file state for dhcpcd.service: No such file or directory", "stderr_lines": ["Failed to get unit file state for dhcpcd.service: No such file or directory"], "stdout": "", "stdout_lines": []}
00:10:25.348 ==> debian: ...ignoring

works in jenkins job/Mem-change-test/91/console

**Comment by jvonau** [comment]
side issue of using command:  su - postgres remains
> 00:14:55.214 ==> ubuntu: TASK [postgresql : Initialize the postgres db] *********************************
00:14:58.498 ==> ubuntu: changed: [127.0.0.1]
00:14:58.499 ==> ubuntu:  [WARNING]: Consider using 'become', 'become_method', and 'become_user' rather
00:14:58.499 ==> ubuntu: than running su

**Comment by holta** [comment]
All agreed during our community/team call (http://minutes.iiab.io) to move ahead and give this a shot, even as our [IIAB 6.5](https://github.com/iiab/iiab/milestone/2) release timeframe is quickly approaching.

WARNING: Ubuntu 17.10 will remain unsupported/experimental, alongside and separate from IIAB's mainline support for LTS OS's like Ubunty 16.04, Debian 9.2.1, CentOS 7.4 and of course Raspbian on Raspberry Pi!

But if this is proven, in preparation for Ubuntu 18.04 LTS in about 5 months, others stand to benefit &mdash; thanks @deldesir for trying!

**Pull request merged**
