### PR TITLE
FreePBX: side-by-side testing of Apache & NGINX + easy './runrole pbx' mods, using a more dynamic iiab-gen-iptables

### PR DESCRIPTION
**Pull request by holta**
Builds on @jvonau's PR #2951 (establishing both `pbx_use_apache: True` and `pbx_use_nginx: True` as on by default) but with:

- [roles/pbx/tasks/enable-or-disable.yml](https://github.com/holta/iiab/blob/pbx-dual/roles/pbx/tasks/enable-or-disable.yml) overhauled to better support turning PBX web server fundamentals ON-or-OFF as necessary.
  - The implementer/operator might decide their FreePBX no longer needs either Apache or NGINX &mdash; or no longer needs _both_ web servers &mdash; e.g. if they prefer Asterisk/CLI commands once they understand the underlying IP telephony landscape.
- [roles/network/templates/iiab-gen-iptables](https://github.com/holta/iiab/blob/pbx-dual/roles/network/templates/gateway/iiab-gen-iptables) is substantially cleaner and more dynamic, to support these post-install changes, using `./runrole pbx`
  - As outlined above, this can include reverting all 3 vars to `pbx_use_apache: False` AND `pbx_use_nginx: False` AND `pbx_enabled: False` (or any subset/combination thereof!) &mdash; and then running `./runrole pbx` should then take care of everything for you w/o hassle.
- New bash function [iiab_var_value()](https://github.com/holta/iiab/blob/pbx-dual/roles/network/templates/gateway/iiab-gen-iptables#L47-L51) supports this, by reading most any variable values live from [default_vars.yml](https://github.com/iiab/iiab/blob/master/vars/default_vars.yml) & [local_vars.yml](http://FAQ.IIAB.IO#What_is_local_vars.yml_and_how_do_I_customize_it.3F)
  - With the exception of the 17 vars that are themselves softcoded within /opt/iiab/iiab/vars/default_vars.yml
  - 16 of these 17 vars can trivially be made to work, given these are quite gratuitous softcodings of what's on the line(s) just above.
  - The 17th is also remarkably gratuitous: `local_tz: "{{ ansible_date_time.tz }}"` dynamically grabs Ansible's interpretation of the OS's Time Zone as specified by symlink `/etc/localtime` (or lack of such a symlink, which means UTC).  Which IIAB no longer needs.  In short, this bash function can work resiliently, with ALL IIAB vars specified in `/opt/iiab/iiab/vars/default_vars.yml` and `/etc/iiab/local_vars.yml`, should that be necessary.
- Cleans out & deprecates stale variables from 0-init, 2-common, and default_vars.yml — this includes `pbx_try_nginx` and others.

cc: @jvonau, @lemueldsouza 

Refs:

- PR #2564
- PR #2728
- #2914
- PR #2916
- PR #2941

### CODE REVIEW

**Comment by holta** [comment]
Heavily rested on a Debian 11 VM.  Further fresh install testing is ongoing.

**Comment by holta** [comment]
Another successful fresh install.

With basic testing of http://box:83/freepbx (Apache) and http://box/freepbx (NGINX) working simultaneously, side-by-side, then with one or the other disabled, etc.

**Comment by holta** [comment]
FreePBX is a Work-in-Progress (by definition, it's in Beta!) but let's merge this now to improve the state-of-the-art.

Allowing for much more community testing, as this converges into a powerful community product.

_Thank you to @lemueldsouza and @jvonau for the very hard work here, that has made this tremendous advance possible over the last month._

**Comment by holta** [comment]
Thanks to @lemueldsouza who reviewed this quickly, and whose continued work on [pbx/README.adoc](https://github.com/iiab/iiab/tree/master/roles/pbx#pbx-readme) should now greatly help this circulate more broadly.

In fact: this roles/pbx work should be considered as part of BIG-sized IIAB demo installs in coming weeks, with a warning about compile time of course, and especially if it's confirmed to run reasonably on Raspberry Pi OS 11 / Bullseye when that's released in coming weeks / days !

**Comment by jvonau** [comment]
I was going to update my PR but you went ahead and forked what I was debugging, wasn't in final form yet.
https://github.com/iiab/iiab/blob/master/roles/pbx/tasks/enable-or-disable.yml#L48-L52 may not be need, if you change both
https://github.com/iiab/iiab/blob/master/roles/pbx/templates/asterisk.conf#L46
https://github.com/iiab/iiab/blob/master/roles/pbx/templates/asterisk.conf#L71 to 'asterisk'

**Comment by holta** [comment]
@jvonau: Good to know.

We should be open to experimental PR's, if this is an important thing to drive community testing, and has passed preliminary testing in common case(s) ?

cc: @lemueldsouza

**Comment by jvonau** [comment]
My entire branch was "experimental" you chose to run with it before the picture came into focus and that is still quite fuzzy.

**Pull request merged**
