### PR TITLE
Rename `xklb` to `library` for pipx

### PR DESCRIPTION
**Pull request by holta**
@deldesir @EMG70 plz review ASAP?

Thanks!!

Related:

- https://github.com/pypi/support/issues/3100
- https://github.com/chapmanjacobd/library/releases/tag/v3.0.034
- https://github.com/chapmanjacobd/library/commit/b37c0b341f376ec80fa187a798417f50b4bf6cea

### CODE REVIEW

**Review by deldesir — APPROVED** [review]

**Comment by holta** [comment]
Thanks @deldesir:

Let's merge aggressively in this case, as (1) this is a simple change and it has to be done regardless to move forward, and (2) @EMG70 should be testing very shortly in case minor revisions turn out to be needed.

**Comment by holta** [comment]
See also doc changes, reflecting the name change from `xklb` to `library` at the pipx level:

https://github.com/chapmanjacobd/library/commit/b37c0b341f376ec80fa187a798417f50b4bf6cea

(More doc changes to come, from @deldesir, hopefully very shortly!)

**Comment by EMG70** [comment]
SUDO IIAB-DIAGNOSTICS - https://paste.centos.org/view/7aaefcec
A new size 1 IIAB was installed on 24.04 LTS.
calibre-web and other apps working ok.
lb --version shows it's not installed.
Screenshot from 2024-12-14 21-37-10

**Comment by holta** [comment]
@deldesir

Is there any chance the command was renamed from `lb` to `library` ?  In some places if not all places?

**Comment by EMG70** [comment]
> @deldesir
> 
> Is there any chance the command was renamed from `lb` to `library` ? In some places if not all places?

library --version returns command not found.
IMG_6250

**Comment by deldesir** [comment]
The problem is xklb is not unistalled in your vm @EMG70. As a workaround, you can just do the following:
```
sudo -i
pipx uninstall xklb
pipx install library --force
```
Then, `lb --version` should work.
I am making a PR to address this @holta.

**Comment by EMG70** [comment]
My IIAB was a completely new instal on a new 24.04LTS on an SSD .

**Comment by deldesir** [comment]
> My IIAB was a completely new instal on a new 24.04LTS on an SSD .

Understood. Can you give it a try again now #3862 is merged?

**Comment by EMG70** [comment]
I am still getting command "lb "not found on a new IIAB on new 24.04LTS installed in last hour.
SUDO IIAB-DIAGNOSTICS - https://paste.centos.org/view/82efff9d
IMG_6277

**Comment by holta** [comment]
@EMG70 did you try `lb --version` while running as root?

(When installing / testing IIAB, running as root is required in almost all cases.)

**Comment by EMG70** [comment]
Apologies for wasting your time ,that was the mistake which I was making.One to remember for the future.
IMG_6278

**Pull request merged**
