### PR TITLE
Very basic iiab-update command, that also upgrades IIAB Calibre-Web

### PR DESCRIPTION
**Pull request by holta**
- This PR is introduces an extremely simple command-line tool (iiab-update) to "git pull" from IIAB's 2 main repos, while offering a few basic extras, e.g. to validate that these very basic upgrades of IIAB and Admin Console appear sane.
- Also assists with "git pull" upgrading of IIAB Calibre-Web (i.e. sync'ing from GitHub to local repo `/usr/local/calibre-web-py3`, and using pipx to upgrade xklb and yt-dlp).
- Safeguards are built in, in all 3 cases — e.g. to avoid damage if local repo is being customized (e.g. if any of the 3 local repos have files modified or have staged changes; or if any of these 3 local repos {iiab, iiab-admin-console, calibre-web} are not currently set to the "master" branch).

Related:

- iiab/calibre-web#31

### CODE REVIEW

**Comment by holta** [comment]
Bonus:

The `iiab-update -f` ≈ `iiab-update --fast` command should allow almost anybody to upgrade [IIAB Calibre-Web](https://github.com/iiab/calibre-web/wiki) very quickly, i.e. by avoiding the ~4 slower steps that (1) check for and apply apt updates, (2) upgrade Ansible, (3) run Ansible. ✅

**Comment by holta** [comment]
Tested on an Ubuntu 24.10 pre-release:

- All looks good (or good enough!) so I'll likely go ahead and merge this in coming minutes, so as to allow more people to try it out.
- And we can evolve from there ~ as this will surely need to be refined later.

**Comment by holta** [comment]
- "Overwrite executing bash script files"
   https://stackoverflow.com/questions/21096478/overwrite-executing-bash-script-files

I suspect the above-explanation-or-similar is the nub of the bug/problem/pattern — as I noticed the problem become even more severe when running "iiab-update -f" from location `/usr/bin/iiab-update` (that effectively overwrites itself, using `cp iiab-update [...] /usr/bin` !)

...i.e. the above glitch appears even more severe than when "iiab-update" was run from location `/opt/iiab/iiab/scripts/iiab-update` (that location shouldn't overwrite itself — but possibly was glitchy for a similar reason (e.g. if `git pull` was perhaps creating some kind of similar race condition i.e. operating on this very same file, or possibly locking the running file briefly... _**as**_ it was running??!)

https://github.com/iiab/iiab/blob/3d6a11635278543680636e767f078e0acb61c7d2/scripts/iiab-update#L76-L94

**Comment by avni** [comment]
Extremely helpful for folks testing frequently! Thank you! I will test and report back.

**Comment by holta** [comment]
> Extremely helpful for folks testing frequently! Thank you! I will test and report back.

Apologies it's "Alpha quality" at the moment!

I'll try to raise it to at least "Beta quality" today — safety measure(s) like the following are needed:

Related:

- [How to make shell scripts robust to source being changed as they run](https://stackoverflow.com/questions/2285403/how-to-make-shell-scripts-robust-to-source-being-changed-as-they-run)
- [Can a shell script indicate that its lines be loaded into memory initially?](https://stackoverflow.com/questions/2336977/can-a-shell-script-indicate-that-its-lines-be-loaded-into-memory-initially)

**Comment by holta** [comment]
Revised!  The following clean-up PR has now been merged, to help allow for wider community testing:

- PR #3770

**Pull request merged**
