### PR TITLE
Ethernet Static IP if DHCP not detected (for eth0 on RPi, link-local 169.154.* optional)

### PR DESCRIPTION
**Pull request by holta**
Builds on PR #1938

### CODE REVIEW

**Comment by holta** [comment]
Needs:
- reconfirm testing works in "HOME" (dhcp w/ cablemodem) and "SCHOOL" Static IP scenarios
- revise/clean http://FAQ.IIAB.IO Item 21 accordingly

**Comment by holta** [comment]
Smoke-tested on Raspbian Lite 2019-07-10 on RPi 4.

**Comment by jvonau** [comment]
[Others appear to suffer the same static ip issue with Raspbian Buster.](https://github.com/RPi-Distro/pi-gen/issues/292) It appears moving to rpi buster introduced a update to dhcpcd:
Rasp9 contains: dhcpcd5/stable,now 1:6.11.5-1+rpt7 armhf [installed] 
Rasp10 contains: dhcpcd5/testing,now 1:7.0.8-0.1+rpt1 armhf [installed]
[which appear to of broken static ip assignment](https://roy.marples.name/archives/dhcpcd-discuss/0002450.html) with a fix released in a later version of dhcpcd by upstream but is not part of Raspbian at this time. The arping/profile/fallback is a workaround with the currently installed version with a benefit of allowing dhcp requests when the machine moves into a dhcp controlled network.

**Comment by tim-moody** [comment]
How can you possibly hard code to the arbitrary address 192.168.1.99?  How do you know the address is available?  How do you know it is the right subnet? How do other machines on the net get their ip addresses if there is no dhcp server?

arping 192.0.2.1 looks odd.

There was already logic to set a static ip address. This probably conflicts with it.

**Comment by holta** [comment]
Clarifs:
- 192.168.1.99 is not hard-coded, but was specifically requested by Chiapas/Mexico schools, and definitely works as demonstrated in several of their schools last week.  Again it's not hard-coded, but made available to those who've asked for it, by uncommenting the relevant lines in local_vars.yml
- Recap that all student PC's IP addresses were hard-coded long ago (there is no DHCP server in Chiapas/Mexico schools, anyway none have been encountered to date, and there is no plan to change their current infra at this time &mdash; they want it kept as is at this time).
- Further testing shows the `arping` line is very likely not necessary at this time (which we had thought was necessary to force detection of DHCP and then fallback to a Static IP).
- While likely no longer needed (if the `arping 192.0.2.1` line indeed goes away!) FYI 192.0.2.1 was chosen by @jvonau very methodically (an intentionally non-existent IP address, as explained in the code, per [RFC5737](https://tools.ietf.org/html/rfc5737)).

**Comment by holta** [comment]
Closing this PR in favor of PR #1940, as the `arping` line proved unnecessary during testing.

**Pull request closed without merging**
