### PR TITLE
Wip Feb 21 - restart kiwix on abort / add Indian language codes

### PR DESCRIPTION
**Pull request by tim-moody**
restart kiwix on abort
add Indian Language codes

PR prototyped, but not tested

### CODE REVIEW

**Comment by holta** [comment]
At https://github.com/iiab/iiab/issues/684#issuecomment-368642245 @tim-moody said "it [#687] is ready to merge".

@tim-moody are you saying this [#687] is in fact smoke-tested?

**Comment by tim-moody** [comment]
no. functional tested.

**Comment by holta** [comment]
If someone can do a smoke-test from scratch of this PR #687 that'd really help!

**Comment by holta** [comment]
@tim-moody explained on our community/team call (http://minutes.iiab.io) this is very safe to merge, so let's give it a shot.

**Pull request merged**
