### PR TITLE
add warning for 5Ghz NOT CHANGING HOSTAPD

### PR DESCRIPTION
**Pull request by jvonau**
### Fixes bug:
skype debugging upstream 5Ghz WiFi connection

### CODE REVIEW

**Comment by holta** [comment]
Relevant to the several issues[*] surfaced by @pumpkinpi85 at #2497

[*] Several networking WiFi issues, and also Ethernet failing due to inadequate electrical power coming into the RPi 3 B+.

**Comment by holta** [comment]
@jvonau is this safe/ready to merge?

Related:

PR #2509 "Warning about 5 GHz sabotaging IIAB's internal WiFi was not being read. So raise it within local_vars.yml & MAKE IT LOUDER"

**Comment by holta** [comment]
How do the pre-existing and proposed `syslog info` commands work within bash script `/lib/dhcpcd/dhcpcd-hooks/50-hostapd` sourced from template [50-hostapd](https://github.com/iiab/iiab/blob/master/roles/network/templates/hostapd/50-hostapd) ?

```
root@box:/opt/iiab/iiab# grep -rn 'syslog info'
roles/network/templates/hostapd/50-hostapd:2:    syslog info "50-iiab IF_UP br0 restarting dnsmasq"
roles/network/templates/hostapd/50-hostapd:10:        syslog info "50-iiab CARRIER change wlan0"
roles/network/templates/hostapd/50-hostapd:22:        syslog info "50-iiab set channel $FREQ2"
roles/network/templates/hostapd/50-hostapd:33:    #syslog info "50-iiab set ap0 spam $REASON"
roles/network/templates/hostapd/50-hostapd:35:        syslog info "50-iiab set ap0 up $REASON"
```

Does this somehow work in bash scripts, despite failing below?

```
root@box:~# syslog info "THIS MACHINE SHOULD BE REBOOTED"
-bash: syslog: command not found
```

**Comment by jvonau** [comment]
Don't waste my time, you would know 'syslog' is a function built into dhcpcd if you bothered to inspect other files present in /lib/dhcpcd/dhcpcd-hooks/.

**Comment by holta** [comment]
> Don't waste my time

Personal attacks are not welcome here.

All questions are welcome in a community volunteer project, from curious people of all kind, sincerely seeking to participate.

**Comment by jvonau** [comment]
> > Don't waste my time
> 
> Personal attacks are not welcome here.

Why the assumption was made that the hook file is a bash script without having a shabang line at the top of the file is beyond me.

> 
> All questions are welcome in a community volunteer project, from curious people of all kind, sincerely seeking to participate.

As one of those volunteers I find it worrisome that the 'merge master' has questions on existing code.

**Pull request merged**
