### PR TITLE
PBX fixes [open Asterisk ports on WAN using iptables, problem reinstalling FreePBX?]

### PR DESCRIPTION
**Pull request by m-anish**
* Fix FreePBX to rerun install everytime as it was causing some intermittent issues
* Open Asterisk ports on WAN if pbx_enabled = True

Please smoke test

### CODE REVIEW

**Comment by holta** [comment]
Fixes #1474, building on #1405.

Future Ref: #1467 "Get Asterisk/FreePBX working on RPi too!"

**Comment by holta** [comment]
> Please smoke test

_Smoke test failed when applying this PR to a pre-existing Asterisk/FreePBX -- where PR #1405 had already run -- on Ubuntu Server 18.04.1 (single interface) VM.  Full error pasted in below.  Suggestions?_

TASK [pbx : FreePBX - Install - CAN TAKE 2 MIN OR LONGER!] *********************
changed: [127.0.0.1] => (item=./start_asterisk start)
Setting Permissions...
Setting base permissions...Done
Setting specific permissions...
 42028 [============================]
Finished setting permissions
Updating tables admin, ampusers, cronmanager, featurecodes, freepbx_log, freepbx_settings, globals, module_xml, modules, notifications...Done
No directory /var/www/html/freepbx/admin/modules/framework/amp_conf/htdocs, install script not needed
Generating CSS...Done
Module framework successfully installed
Updating Hooks...Done
Chowning directories...
In Self_Helper.class.php line 212:

  Unable to locate the FreePBX BMO Class 'Core'A required module might be dis
  abled or uninstalled. Recommended steps (run from the CLI): 1) fwconsole ma
   install core 2) fwconsole ma enable core


ma [-f|--force] [-d|--debug] [--edge] [--stable] [--color] [--skipchown] [-e|--autoenable] [--skipdisabled] [--snapshot SNAPSHOT] [--format FORMAT] [-R|--repo REPO] [-t|--tag TAG] [--sendemail] [--] [<args>]...

failed: [127.0.0.1] (item=./install -n --webroot /var/www/html/freepbx --dbuser asterisk --dbpass asterisk --dbname asterisk --cdrdbname asteriskcdrdb) => {"changed": true, "cmd": ["./install", "-n", "--webroot", "/var/www/html/freepbx", "--dbuser", "asterisk", "--dbpass", "asterisk", "--dbname", "asterisk", "--cdrdbname", "asteriskcdrdb"], "delta": "0:01:44.764430", "end": "2019-02-10 11:36:10.761065", "item": "./install -n --webroot /var/www/html/freepbx --dbuser asterisk --dbpass asterisk --dbname asterisk --cdrdbname asteriskcdrdb", "msg": "non-zero return code", "rc": 1, "start": "2019-02-10 11:34:25.996635", "stderr": "    0/7946 [>---------------------------]   0%\n  100/7946 [>---------------------------]   1%\n  200/7946 [>---------------------------]   2%\n  300/7946 [=>--------------------------]   3%\n  400/7946 [=>--------------------------]   5%\n  500/7946 [=>--------------------------]   6%\n  600/7946 [==>-------------------------]   7%\n  700/7946 [==>-------------------------]   8%\n  800/7946 [==>-------------------------]  10%\n  900/7946 [===>------------------------]  11%\n 1000/7946 [===>------------------------]  12%\n 1100/7946 [===>------------------------]  13%\n 1200/7946 [====>-----------------------]  15%\n 1300/7946 [====>-----------------------]  16%\n 1400/7946 [====>-----------------------]  17%\n 1500/7946 [=====>----------------------]  18%\n 1600/7946 [=====>----------------------]  20%\n 1700/7946 [=====>----------------------]  21%\n 1800/7946 [======>---------------------]  22%\n 1900/7946 [======>---------------------]  23%\n 2000/7946 [=======>--------------------]  25%\n 2100/7946 [=======>--------------------]  26%\n 2200/7946 [=======>--------------------]  27%\n 2300/7946 [========>-------------------]  28%\n 2400/7946 [========>-------------------]  30%\n 2500/7946 [========>-------------------]  31%\n 2600/7946 [=========>------------------]  32%\n 2700/7946 [=========>------------------]  33%\n 2800/7946 [=========>------------------]  35%\n 2900/7946 [==========>-----------------]  36%\n 3000/7946 [==========>-----------------]  37%\n 3100/7946 [==========>-----------------]  39%\n 3200/7946 [===========>----------------]  40%\n 3300/7946 [===========>----------------]  41%\n 3400/7946 [===========>----------------]  42%\n 3500/7946 [============>---------------]  44%\n 3600/7946 [============>---------------]  45%\n 3700/7946 [=============>--------------]  46%\n 3800/7946 [=============>--------------]  47%\n 3900/7946 [=============>--------------]  49%\n 4000/7946 [==============>-------------]  50%\n 4100/7946 [==============>-------------]  51%\n 4200/7946 [==============>-------------]  52%\n 4300/7946 [===============>------------]  54%\n 4400/7946 [===============>------------]  55%\n 4500/7946 [===============>------------]  56%\n 4600/7946 [================>-----------]  57%\n 4700/7946 [================>-----------]  59%\n 4800/7946 [================>-----------]  60%\n 4900/7946 [=================>----------]  61%\n 5000/7946 [=================>----------]  62%\n 5100/7946 [=================>----------]  64%\n 5200/7946 [==================>---------]  65%\n 5300/7946 [==================>---------]  66%\n 5400/7946 [===================>--------]  67%\n 5500/7946 [===================>--------]  69%\n 5600/7946 [===================>--------]  70%\n 5700/7946 [====================>-------]  71%\n 5800/7946 [====================>-------]  72%\n 5900/7946 [====================>-------]  74%\n 6000/7946 [=====================>------]  75%\n 6100/7946 [=====================>------]  76%\n 6200/7946 [=====================>------]  78%\n 6300/7946 [======================>-----]  79%\n 6400/7946 [======================>-----]  80%\n 6500/7946 [======================>-----]  81%\n 6600/7946 [=======================>----]  83%\n 6700/7946 [=======================>----]  84%\n 6800/7946 [=======================>----]  85%\n 6900/7946 [========================>---]  86%\n 7000/7946 [========================>---]  88%\n 7100/7946 [=========================>--]  89%\n 7200/7946 [=========================>--]  90%\n 7300/7946 [=========================>--]  91%\n 7400/7946 [==========================>-]  93%\n 7500/7946 [==========================>-]  94%\n 7600/7946 [==========================>-]  95%\n 7700/7946 [===========================>]  96%\n 7800/7946 [===========================>]  98%\n 7900/7946 [===========================>]  99%\n 7946/7946 [============================] 100%\nIn Process.php line 239:\n                                                                  \n  The command \"/usr/sbin/fwconsole ma install framework\" failed.  \n                                                                  \n  Exit Code: 255(Unknown error)                                   \n                                                                  \n  Working directory: /opt/iiab/freepbx                            \n                                                                  \n  Output:                                                         \n  ================                                                \n                                                                  \n                                                                  \n  Error Output:                                                   \n  ================                                                \n                                                                  \n\ninstall [--dbengine DBENGINE] [--dbname DBNAME] [--cdrdbname CDRDBNAME] [--dbuser DBUSER] [--dbpass DBPASS] [--user USER] [--group GROUP] [--dev-links] [--skip-install] [--webroot WEBROOT] [--astetcdir ASTETCDIR] [--astmoddir ASTMODDIR] [--astvarlibdir ASTVARLIBDIR] [--astagidir ASTAGIDIR] [--astspooldir ASTSPOOLDIR] [--astrundir ASTRUNDIR] [--astlogdir ASTLOGDIR] [--ampbin AMPBIN] [--ampsbin AMPSBIN] [--ampcgibin AMPCGIBIN] [--ampplayback AMPPLAYBACK] [-r|--rootdb] [-f|--force]", "stderr_lines": ["    0/7946 [>---------------------------]   0%", "  100/7946 [>---------------------------]   1%", "  200/7946 [>---------------------------]   2%", "  300/7946 [=>--------------------------]   3%", "  400/7946 [=>--------------------------]   5%", "  500/7946 [=>--------------------------]   6%", "  600/7946 [==>-------------------------]   7%", "  700/7946 [==>-------------------------]   8%", "  800/7946 [==>-------------------------]  10%", "  900/7946 [===>------------------------]  11%", " 1000/7946 [===>------------------------]  12%", " 1100/7946 [===>------------------------]  13%", " 1200/7946 [====>-----------------------]  15%", " 1300/7946 [====>-----------------------]  16%", " 1400/7946 [====>-----------------------]  17%", " 1500/7946 [=====>----------------------]  18%", " 1600/7946 [=====>----------------------]  20%", " 1700/7946 [=====>----------------------]  21%", " 1800/7946 [======>---------------------]  22%", " 1900/7946 [======>---------------------]  23%", " 2000/7946 [=======>--------------------]  25%", " 2100/7946 [=======>--------------------]  26%", " 2200/7946 [=======>--------------------]  27%", " 2300/7946 [========>-------------------]  28%", " 2400/7946 [========>-------------------]  30%", " 2500/7946 [========>-------------------]  31%", " 2600/7946 [=========>------------------]  32%", " 2700/7946 [=========>------------------]  33%", " 2800/7946 [=========>------------------]  35%", " 2900/7946 [==========>-----------------]  36%", " 3000/7946 [==========>-----------------]  37%", " 3100/7946 [==========>-----------------]  39%", " 3200/7946 [===========>----------------]  40%", " 3300/7946 [===========>----------------]  41%", " 3400/7946 [===========>----------------]  42%", " 3500/7946 [============>---------------]  44%", " 3600/7946 [============>---------------]  45%", " 3700/7946 [=============>--------------]  46%", " 3800/7946 [=============>--------------]  47%", " 3900/7946 [=============>--------------]  49%", " 4000/7946 [==============>-------------]  50%", " 4100/7946 [==============>-------------]  51%", " 4200/7946 [==============>-------------]  52%", " 4300/7946 [===============>------------]  54%", " 4400/7946 [===============>------------]  55%", " 4500/7946 [===============>------------]  56%", " 4600/7946 [================>-----------]  57%", " 4700/7946 [================>-----------]  59%", " 4800/7946 [================>-----------]  60%", " 4900/7946 [=================>----------]  61%", " 5000/7946 [=================>----------]  62%", " 5100/7946 [=================>----------]  64%", " 5200/7946 [==================>---------]  65%", " 5300/7946 [==================>---------]  66%", " 5400/7946 [===================>--------]  67%", " 5500/7946 [===================>--------]  69%", " 5600/7946 [===================>--------]  70%", " 5700/7946 [====================>-------]  71%", " 5800/7946 [====================>-------]  72%", " 5900/7946 [====================>-------]  74%", " 6000/7946 [=====================>------]  75%", " 6100/7946 [=====================>------]  76%", " 6200/7946 [=====================>------]  78%", " 6300/7946 [======================>-----]  79%", " 6400/7946 [======================>-----]  80%", " 6500/7946 [======================>-----]  81%", " 6600/7946 [=======================>----]  83%", " 6700/7946 [=======================>----]  84%", " 6800/7946 [=======================>----]  85%", " 6900/7946 [========================>---]  86%", " 7000/7946 [========================>---]  88%", " 7100/7946 [=========================>--]  89%", " 7200/7946 [=========================>--]  90%", " 7300/7946 [=========================>--]  91%", " 7400/7946 [==========================>-]  93%", " 7500/7946 [==========================>-]  94%", " 7600/7946 [==========================>-]  95%", " 7700/7946 [===========================>]  96%", " 7800/7946 [===========================>]  98%", " 7900/7946 [===========================>]  99%", " 7946/7946 [============================] 100%", "In Process.php line 239:", "                                                                  ", "  The command \"/usr/sbin/fwconsole ma install framework\" failed.  ", "                                                                  ", "  Exit Code: 255(Unknown error)                                   ", "                                                                  ", "  Working directory: /opt/iiab/freepbx                            ", "                                                                  ", "  Output:                                                         ", "  ================                                                ", "                                                                  ", "                                                                  ", "  Error Output:                                                   ", "  ================                                                ", "                                                                  ", "", "install [--dbengine DBENGINE] [--dbname DBNAME] [--cdrdbname CDRDBNAME] [--dbuser DBUSER] [--dbpass DBPASS] [--user USER] [--group GROUP] [--dev-links] [--skip-install] [--webroot WEBROOT] [--astetcdir ASTETCDIR] [--astmoddir ASTMODDIR] [--astvarlibdir ASTVARLIBDIR] [--astagidir ASTAGIDIR] [--astspooldir ASTSPOOLDIR] [--astrundir ASTRUNDIR] [--astlogdir ASTLOGDIR] [--ampbin AMPBIN] [--ampsbin AMPSBIN] [--ampcgibin AMPCGIBIN] [--ampplayback AMPPLAYBACK] [-r|--rootdb] [-f|--force]"], "stdout": "Checking if SELinux is enabled...Its not (good)!\nReading /etc/asterisk/asterisk.conf...Done\nChecking if Asterisk is running and we can talk to it as the 'asterisk' user...Yes. Determined Asterisk version to be: 16.1.1\nChecking if NodeJS is installed and we can get a version from it...Yes. Determined NodeJS version to be: 10.15.1\nPreliminary checks done. Starting FreePBX Installation\nChecking if this is a new install...No (/etc/freepbx.conf file detected)\nUpdating tables admin, ampusers, cronmanager, featurecodes, freepbx_log, freepbx_settings, globals, module_xml, modules, notifications...Done\nInitializing FreePBX Settings\nFinished initalizing settings\nCopying files (this may take a bit)....\n\nDone\nbin is: /var/lib/asterisk/bin\nsbin is: /usr/sbin\nFinishing up directory processes...Done!\nRunning variable replacement...Done\nCreating missing #include files...Done\nSetting up Asterisk Manager Connection...Done\nRunning through upgrades...\nChecking for upgrades..\nNo further upgrades necessary\nFinished upgrades\nSetting FreePBX version to 15.0.2.13...Done\nWriting out /etc/amportal.conf...Done\nChowning directories...\nDone\nInstalling framework...", "stdout_lines": ["Checking if SELinux is enabled...Its not (good)!", "Reading /etc/asterisk/asterisk.conf...Done", "Checking if Asterisk is running and we can talk to it as the 'asterisk' user...Yes. Determined Asterisk version to be: 16.1.1", "Checking if NodeJS is installed and we can get a version from it...Yes. Determined NodeJS version to be: 10.15.1", "Preliminary checks done. Starting FreePBX Installation", "Checking if this is a new install...No (/etc/freepbx.conf file detected)", "Updating tables admin, ampusers, cronmanager, featurecodes, freepbx_log, freepbx_settings, globals, module_xml, modules, notifications...Done", "Initializing FreePBX Settings", "Finished initalizing settings", "Copying files (this may take a bit)....", "", "Done", "bin is: /var/lib/asterisk/bin", "sbin is: /usr/sbin", "Finishing up directory processes...Done!", "Running variable replacement...Done", "Creating missing #include files...Done", "Setting up Asterisk Manager Connection...Done", "Running through upgrades...", "Checking for upgrades..", "No further upgrades necessary", "Finished upgrades", "Setting FreePBX version to 15.0.2.13...Done", "Writing out /etc/amportal.conf...Done", "Chowning directories...", "Done", "Installing framework..."]

**Comment by holta** [comment]
@m-anish I'm hopeful any revised version of this PR can be part of IIAB 6.7 RC3 when that's released within 24h?

(Whether _or not_ FreePBX is reinstalled each time the 'pbx' playbook is run!)

**Comment by holta** [comment]
Updates:
- IIAB networking doc https://github.com/iiab/iiab/wiki/IIAB-Networking#list-of-open-ports--services has been updated to show Asterisk's ports, thanks @m-anish
- "./runrole pbx" froze the 2nd time I ran it on an Ubuntu Server 18.04.1 VM, at this stage:
```
TASK [pbx : FreePBX - Enable & (Re)start 'freepbx' systemd service (if pbx_enabled)] ***
```
This might explain why?
```
root@box:~# tail -5 /var/log/asterisk/freepbx.log
[2019-Feb-10 23:35:01] [freepbx_log.INFO]: Connection attmempt to AMI failed [] []
[2019-Feb-10 23:36:01] [freepbx_log.INFO]: Connection attmempt to AMI failed [] []
[2019-Feb-10 23:37:01] [freepbx_log.INFO]: Connection attmempt to AMI failed [] []
[2019-Feb-10 23:38:01] [freepbx_log.INFO]: Connection attmempt to AMI failed [] []
[2019-Feb-10 23:39:01] [freepbx_log.INFO]: Connection attmempt to AMI failed [] []
```

**Comment by holta** [comment]
@m-anish will the line "[ACTUAL IP ADDRESS] pbx.lan" still be necessary in some client machines' `hosts` files as of 2019-02-14 when IIAB 6.7 is released?

Hopefully not!

But either way: am trying to clean up the documentation @ https://github.com/iiab/iiab/blob/master/roles/pbx/README.rst#using-it so let's keep in touch here~

**Comment by m-anish** [comment]
Created #1491 as a minor clarification on README.md. 

I think this and #1491 are good to merge.

**Comment by holta** [comment]
I'm not sure PR #1491 is correct.

Even when installing IIAB as a gateway, several of us do its web-based administration from the WAN side where pbx.lan does not resolve.

**Comment by m-anish** [comment]
> I'm not sure PR #1491 is correct.
> 
> Even when installing IIAB as a gateway, several of us do its web-based administration from the WAN side where pbx.lan does not resolve.

hmm
I felt this was atleast clearer than "sometimes". Maybe we should be more explicit then?

When accessing over WAN, please do the /etc/hosts thing

**Comment by holta** [comment]
Merging provisionally to encourage more testing/refinements as part of master.

Absolute worst case this can be reverted if major probs arise.

**Pull request merged**
