### PR TITLE
runrole: auto-prompt to pass 'APP_install: True' to Ansible + properly validate 5 dependencies

### PR DESCRIPTION
**Pull request by holta**
Alternative to @jvonau's PR #2616 with interactive explanations so testers know exactly what's happening.

This streamlines testing by cleaning up ad hoc installation of IIAB's 5 auto-installed dependencies {apache, nodejs, postgresql, mongodb, yarn}, allowing `./runrole <APP>` and `./runrole --reinstall <APP>` to work gracefully for most all of IIAB's Ansible [roles](https://github.com/iiab/iiab/tree/master/roles), in most all situations.

It does this by automatically prompting implementers/testers/you e.g. if you forgot to set APP_install: True in [/etc/iiab/local_vars.yml](http://wiki.laptop.org/go/IIAB/FAQ#What_is_local_vars.yml_and_how_do_I_customize_it.3F) &mdash; allowing you to quickly (A) pass variable `APP_install: True` directly to Ansible, by hitting [Enter] at the prompt &mdash; or (B) exit to the command-line to edit `/etc/iiab/local_vars.yml` if you prefer that instead.

Also var validation of IIAB's 5 core dependencies is fixed.  With blue-on-green Ansible output when [0-init](https://github.com/iiab/iiab/tree/master/roles/0-init) runs, making clear which validations the 5 dependencies are bypassing.

Background: PR https://github.com/iiab/iiab/pull/2613#issuecomment-721329979

This PR has been heavily tested on Ubuntu Server 20.04.1

### CODE REVIEW

**Comment by tim-moody** [comment]
>IIAB's 5 auto-installed dependencies {apache, nodejs, postgresql, mongodb, yarn}

Why install all of these?

**Comment by holta** [comment]
> > IIAB's 5 auto-installed dependencies {apache, nodejs, postgresql, mongodb, yarn}
> 
> Why install all of these?

I'm not sure I quite understand the question.

But to clarify, each of these 5 are:
- auto-installed by other IIAB Apps/Services when required (what is meant by "dependency")
- or, manually installed during testing, maintenance, development etc

**Comment by holta** [comment]
Later, `./runrole <APP>` should probably be revised to accommodate multiple roles, as is currently done by `./runroles <APP1> <APP2> <APP3>` (see [runroles](https://github.com/iiab/iiab/blob/master/runroles)).

**Comment by jvonau** [comment]
> Later, `./runrole <APP>` should probably be revised to accommodate multiple roles, as is currently done by [./runroles ](https://github.com/iiab/iiab/blob/master/runroles)

That is what iiab-configure does runs through stages 4-9 so multiple roles can be updated in one go.

**Comment by holta** [comment]
> > Later, `./runrole <APP>` should probably be revised to accommodate multiple roles, as is currently done by [./runroles ](https://github.com/iiab/iiab/blob/master/runroles)
> 
> That is what iiab-configure does runs through stages 4-9 so multiple roles can be updated in one go.

A very good reminder, to promote [./iiab-configure](https://github.com/iiab/iiab/blob/master/iiab-configure) more, as growing numbers edit-or-tweak their [/etc/iiab/local_vars.yml](http://wiki.laptop.org/go/IIAB/FAQ#What_is_local_vars.yml_and_how_do_I_customize_it.3F) after an IIAB install.

Also: some ppl also want a Command-Line Interface to be able to very quickly do things like `./runroles <APP1> <APP2>` during development, testing etc.

Personally, during QA, I often find myself chaining together a few runrole commands as follows:

```
./runrole <APP1> ; ./runrole <APP2>
```

**Comment by jvonau** [comment]
> > > Later, `./runrole <APP>` should probably be revised to accommodate multiple roles, as is currently done by [./runroles ](https://github.com/iiab/iiab/blob/master/runroles)
> > 
> > 
> > That is what iiab-configure does runs through stages 4-9 so multiple roles can be updated in one go.
> 
> A very good reminder, to promote [./iiab-configure](https://github.com/iiab/iiab/blob/master/iiab-configure) more, as growing numbers edit-or-tweak their [/etc/iiab/local_vars.yml](http://wiki.laptop.org/go/IIAB/FAQ#What_is_local_vars.yml_and_how_do_I_customize_it.3F) after an IIAB install.
> 
> Also: some ppl also want a Command-Line Interface to be able to very quickly do things like `./runroles <APP1> <APP2>` during development, testing etc.
> 
> Personally, during QA, I often find myself chaining together a few runrole commands as follows:
> 
> ```
> ./runrole <APP1> ; ./runrole <APP2>
> ```

Just a thought, maybe you could of started hacking on runroles if you were looking to chain multiple roles together but the need to manually remove 'installed' exists for a --reinstall situation but could pretty easy to retrofit. I like the temporary override of the *_installed var for testing, I just don't like the language used that suggests "echo -e "Usually it's best to set this in: $LOCAL_VARS_FILE\n"" that is really misleading as the vars in question(apache, nodejs, postgresql, mongodb, yarn) do not appear in local_vars.yml and should not,

I just see no reason to carry "*_enabled" for nodejs or yarn, there is no service attached to these roles, 'enabled' was added just to pass "validation", no other reason.

> > IIAB's 5 auto-installed dependencies {apache, nodejs, postgresql, mongodb, yarn}
> 
> Why install all of these?

These roles are not being auto-installed carte blanche, the only way the above roles are called is indirectly from within another role's install.yml where 'set_vars foo_install True' is used and foo's role called to install the dependency or directly from runrole(s). The former works perfect, while the latter just needs a tweak in default_vars as shown in #2616. Even if this PR is pushed runrole(s) are still in the same situation, just with a nice misleading statement to add something to local_vars for runrole while runroles blows up as it does now. Try running runroles with apache, nodejs, postgresql, mongodb, or yarn, you will see what I'm describing

pi@box:/opt/iiab/iiab $ sudo ./runroles httpd
> TASK [httpd : Assert that "apache_install is sameas true" (boolean not string etc)] *******************
fatal: [127.0.0.1]: FAILED! => {"assertion": "apache_install is sameas true", "changed": false, "evaluated_to": false, "msg": "PLEASE SET 'apache_install: True' e.g. IN: /etc/iiab/local_vars.yml"}

**Comment by jvonau** [comment]
pi@box:/opt/iiab/iiab $ sudo ./runrole nginx

>WARNING: /etc/iiab/iiab_state.yml already has this/these line(s):
nginx_installed: True
To reinstall it, run: ./runrole --reinstall nginx
Or continue, e.g. to enable/disable it based on var 'nginx_enabled' ? [Y/n] 

Why is there a suggestion to use --reinstall even mentioned for what is a normal operation? Seems to suggest that --reinstall is missing and should always be included, in which it is not. What would be useful is to display the actual current *_enable value before the prompt to continue.

**Comment by holta** [comment]
> pi@box:/opt/iiab/iiab $ sudo ./runrole nginx
> 
> > WARNING: /etc/iiab/iiab_state.yml already has this/these line(s):
> > nginx_installed: True
> > To reinstall it, run: ./runrole --reinstall nginx
> > Or continue, e.g. to enable/disable it based on var 'nginx_enabled' ? [Y/n]
> 
> Why is there a suggestion to use --reinstall

Operator education proved critical in the last year here...when people became very frustrated not realizing they sometimes need to include the `--reinstall` flag.

> Seems to suggest that --reinstall is missing and should always be included

The wording can be changed if necessary but it's absolutely not mandating `--reinstall`

It's just educating the operator about the `--reinstall` flag and then allowing them to carry on without it, by hitting [Enter] for the default.

> What would be useful is to display the actual current *_enable value before the prompt to continue.

That's very easy to add, and a good idea probably.

**Comment by jvonau** [comment]
> Operator education proved critical in the last year here...when people become very frustrated not realizing they sometimes need to include the `--reinstall` flag.

The docs are lacking some substance around the subject.
 
> > Seems to suggest that --reinstall is missing and should always be included
> 
> The wording can be changed if necessary but it's absolutely not mandating `--reinstall`
> 

The message is confusing for what is an "optional" opt-in function.
> It's just educating the operator about the `--reinstall` flag and then allowing them to carry on without it, by hitting [Enter] for the default.

It's a fine line between education and indoctrination. 
> 
> > What would be useful is to display the actual current *_enable value before the prompt to continue.
> 
> That's very easy to add, and a good idea probably.

**Comment by jvonau** [comment]
replace 'To reinstall it, run: ./runrole --reinstall nginx'
with 'Already installed not performing upgrade. See http://some_webpath_pointer about upgrades'

**Comment by holta** [comment]
> replace 'To reinstall it, run: ./runrole --reinstall nginx'
> with 'Already installed not performing upgrade. See http://some_webpath_pointer about upgrades'

The above feels like highly unnecessary obfuscation.

People want to know about the `--reinstall` flag.

**Comment by jvonau** [comment]
That is what documentation is for where you can expand on what a 'reinstall/upgrade' is, what --reinstall does, and the dangers that might exist in some roles. It's intentional to encourage people to read and just not blindly think 'hey it says reinstall lets always do that so it doesn't stop for this warning'.

>pi@box:/opt/iiab/iiab $ sudo ./runrole --reinstall internetarchives
ERROR: /etc/iiab/iiab_state.yml has no lines that begin with 'internetarchives_'
Try again without the '--reinstall' flag?

Ok, bails on fresh installs that seems fine but what blows me away is execution is stop to prompt for 'normal' operational behavior above while the below 'expert level operation' cruses right though without a sanity 'you really want to do this' check.
>pi@box:/opt/iiab/iiab $ sudo ./runrole --reinstall nginx
These line(s) in /etc/iiab/iiab_state.yml are now being deleted:
nginx_installed: True
bash will now run this, adding single quotes around the {...} curly braces:
ansible-playbook -i ansible_hosts run-one-role.yml --connection=local --extra-vars {"reinstall":True,"role_to_run":"nginx"}
^C [ERROR]: User interrupted execution
^C [ERROR]: User interrupted execution
 
I feel the emphasis toward encouraging --reinstall is backwards and can be potentially harmful to real data in the real world not just a testing environment. Want a blind reinstall with no checking use `runroles`

**Comment by holta** [comment]
Every Learning Curve is a roller coaster...but this tries to improve the ride:

PR #2622 "runrole: explain unknown flag (--reinstall) with more context"

**Pull request merged**
