### PR TITLE
http://box/elgg fatal error: stricter syntax for Ansible 2.4.x ?

### PR DESCRIPTION
**Pull request by jvonau**

### CODE REVIEW

**Comment by holta** [comment]
Possibly helps mitigate stuff like #330 (Elgg 2.3.4 regression if installing with Ansible 2.4.0) ?

Might be related to stricter syntax in Ansible 2.4.0 ?

**Comment by holta** [comment]
Moving to target [IIAB 6.4](https://github.com/iiab/iiab/milestone/1) in case there's hopefully time to evaluate prior to release.

**Comment by holta** [comment]
@jvonau I forgot to mention I smoke-tested this successfully, but it shows [no visible improvement](https://github.com/iiab/iiab/issues/330#issuecomment-333348079) in getting Elgg to install.

Despite multiple runs of "./runtags elgg" and many reboots for good measure, ah well back to the drawing board :)

**Comment by holta** [comment]
@jvonau does this ticket have remaining value?

Or do we resolve given Elgg still won't install?

**Comment by jvonau** [comment]
Need further clarification of won't install as you stated that the install is successful but a 2nd pass breaks elgg.

**Pull request closed without merging**
