### PR TITLE
U17-2: refine network for Ubuntu 18.04 LTS daily builds

### PR DESCRIPTION
**Pull request by jvonau**
### Fixes Bug
post 6.5 release

### CODE REVIEW

**Comment by holta** [comment]
Related:

#553 "U17: 18.04 daily builds with a desktop have NetworkManager installed"
#502 "Ubuntu 17.10 (Artful Aardvark) Stretch Goal for IIAB 6.5 - Calibre 3.7 + Nextcloud issues"

**Comment by jvonau** [comment]
I would prefer to have this PR in place for the better network backend detection, so we can identify more easily what program is running the network and work from there without having to go through the Q&A routine to gather the info....   Using 'runtags network-discover', posting copy of the iiab-debug.log would be helpful before proceeding to 'iiab-install' on any of the newer releases.

**Comment by holta** [comment]
> I would prefer to have this PR in place for the better network backend detection

While this PR is marked as [IIAB 6.6](https://github.com/iiab/iiab/milestone/3), I've added it to our community/team call agenda for Thursday 2017-12-07 @ http://minutes.iiab.io so all can talk it over then &mdash; i.e. whether it's tested as sufficiently safe to add to [IIAB 6.5](https://github.com/iiab/iiab/milestone/2).

**Comment by holta** [comment]
@tim-moody studied this code during our live community/team call and wishes he could understand it all, but until then we agreed (during our call @ http://minutes.iiab.io) to merge this and unroll any serious problems if they should arise.

**Pull request merged**
