### PR TITLE
PHP 8.0 brings a couple changes—slightly affecting Moodle, Nextcloud etc: (1) php8.0-xmlrpc moved to PECL (2) php8.0-json is now baked into PHP itself

### PR DESCRIPTION
**Pull request by holta**
WIP for #2814 (PHP 8) and #2818 (Ubuntu 21.10).

This PR will be re-tested on Ubuntu Server 21.10 pre-release and other OS's.

### CODE REVIEW

**Comment by holta** [comment]
Second smoketest also successful.

What functionality tests are most important to understand if the removal of `php{{ php_version }}-xmlrpc` matters?

**Comment by holta** [comment]
Smoke-tested with a fresh install of IIAB (BIG-sized) onto 32-bit RaspiOS Lite on RPi 4.

**Comment by holta** [comment]
@georgejhunt @tim-moody @jvonau 

> What functionality tests are most important to understand if the removal of php{{ php_version }}-xmlrpc matters?

So far I do not see any consequences from repeated install tests of this PR without php{{ php_version }}-xmlrpc.

Does anybody remember its purpose?

**Comment by tim-moody** [comment]
The most recent agreement was that we would have php and various libraries as part of the web server role since they are of general interest. This was part of the general movement towards using ansible as a procedural language instead of a declarative language.

If you want to return to a declarative approach, this is just the tip of the iceberg.

Such changes to design strategy should be discussed as a group.

**Comment by jvonau** [comment]
> @georgejhunt @tim-moody @jvonau
> 
> > What functionality tests are most important to understand if the removal of php{{ php_version }}-xmlrpc matters?
> 
> So far I do not see any consequences from repeated install tests of this PR without php{{ php_version }}-xmlrpc.
> 
> Does anybody remember its purpose?

Once upon a time an apt installation within a role was used to denote dependencies of an **optional** role. Now with both Nextcloud and Moodle roles falling into the optional category as both are **not** part of min-vars I see little value in moving the dependencies from being optional to being mandatory in www_base. The process is backwards www_base should be the file with entries being removed not the roles' dependencies, there is no harm in repeating dependencies amongst the optional roles. The analogy I'll use here is "buying snow tires for a car that is to be driven only in a warm climate is a waste of time, the snow tires will never will get used."

**Pull request merged**
