### PR TITLE
WIP: Extricate IIAB from 2 web servers complexity [Apache -> NGINX]

### PR DESCRIPTION
**Pull request by holta**
Still Evolving.  To bring about a more sustainably focused software ecosystem using just 1 nervous system ([NGINX](https://github.com/iiab/iiab/tree/master/roles/nginx)).  Rather than 2 interneural/interwoven complexities (Apache + NGINX).  Deprecating takes time and a lot of patience even in the best of circumstances (imperial system, metric system, IPv6, etc).  Meantime:

- This is tested on 32-bit RaspiOS Lite (RPi 4).
- Testing is ongoing on 64-bit Ubuntu Desktop 20.04 (VM).

Eternal questions of course remain &mdash; as to when global learning communities will truly invest in the ongoing upkeep of lesser-used apps &mdash; e.g. Elgg and phpMyAdmin are the topics of the hour, whether or not they will be upgraded or gracefully put out to pasture.

But the very same questions of legit community impact apply far more broadly, than to just those 2 rather unmaintained apps/services.  Santa Claus does not provide glittering objects on demand.  And she too needs to eat.

Refs:

- #2762
- PR #2794
- PR #2832
- PR #2841 
- PR #2843 
- PR #2845 
- PR #2846 
- PR #2847 
- PR #2849

### CODE REVIEW

**Comment by holta** [comment]
> Testing is ongoing on 64-bit Ubuntu Desktop 20.04 (VM).

Above test completed.  A 3rd test is now running on Debian Server 10.10 (VM).

**Comment by holta** [comment]
> A 3rd test is now running on Debian Server 10.10 (VM).

Above test completed.  A 4th test is now running on Debian 11 Desktop (VM).

**Comment by holta** [comment]
> A 4th test is now running on Debian 11 Desktop (VM).

FYI `./runrole calibre` was also tested, which successfully installs Calibre 5.12 from 2021-02-26, as confirmed by logging into: http://box:8080

```
root@deb11-desk:~# apt -a list "*calibre*"
Listing... Done
calibre-bin/testing,now 5.12.0+dfsg-1 amd64 [installed]

calibre/testing,now 5.12.0+dfsg-1 all [installed]
```

```
root@deb11-desk:~# systemctl status calibre-serve.service
● calibre-serve.service - Provides the Calibre Book Server
     Loaded: loaded (/etc/systemd/system/calibre-serve.service; enabled; vendor preset: enabled)
     Active: active (running) since Wed 2021-07-07 10:01:01 EDT; 4min 3s ago
    Process: 128056 ExecStart=/usr/bin/calibre-server --daemonize --log=/var/log/calibre.log --pidfile=/var/run/calibre.pid --port=8080 --enable-auth --userdb=/library/calibre/users.sqlite /library/calibre (code=exited, status=0/SUCCESS)
   Main PID: 128069 (BonJour)
      Tasks: 14 (limit: 2325)
     Memory: 179.0M
        CPU: 3.263s
     CGroup: /system.slice/calibre-serve.service
             └─128069 /usr/bin/python3.9 /usr/bin/calibre-server --daemonize --log=/var/log/calibre.log --pidfile=/var/run/calibre.pid --port=8080 --enable-auth --userdb=/library/calibre/users.sqlite /library/calibre

Jul 07 10:01:00 box.lan systemd[1]: Starting Provides the Calibre Book Server...
Jul 07 10:01:01 box.lan systemd[1]: Started Provides the Calibre Book Server.
```

**Comment by holta** [comment]
Please if you can read IIAB's new CUPS **README.md** here:

https://github.com/iiab/iiab/tree/master/roles/cups

If anybody can offer improvements and/or clarifications to this document (for implementers and especially field communities wanting less complicated printing) that would be most appreciated!

**Comment by holta** [comment]
Unfortunate that the Desktop version of Debian 11 seems to install Apache out-of-the-box:

```
root@deb11-desk:~# apt list apache2-bin
Listing... Done
apache2-bin/testing,now 2.4.48-3.1 amd64 [installed,automatic]
```

```
root@deb11-desk:~# apt-cache rdepends --installed apache2-bin
apache2-bin
Reverse Depends:
  libapache2-mod-dnssd
  gnome-user-share
```

**Comment by jvonau** [comment]
There is more than just one desktop available seems you elected to go with gnome, see https://wiki.debian.org/DesktopEnvironment -> How it works? Installation of a Desktop Environment. Stick with something that uses Network-Manager to configure the networking for the least hassle network wise.

**Comment by holta** [comment]
> Stick with something that uses Network-Manager to configure the networking for the least hassle network wise.

Good to know.  FWIW I believe I chose all defaults when installing Debian 11 with graphical desktop.  But it was a couple months ago so it's entirely possible the install GUI (https://wiki.debian.org/DesktopEnvironment#How_it_works.3F) might have changed a  little bit since then.

- #2749

**Comment by holta** [comment]
Another fresh install just completed on Ubuntu Server 20.04 LTS here: http://10.8.0.58

**Comment by jvonau** [comment]
Given apache is popping up unexpectedly as above think it would be wrong to remove the code that would enable nginx to install while the http port is occupied by apache, better to cover that possibility rather than stopping the install dead when nginx can't bind to the same port as apache is using. Is freepbx not going to be supported under apache going forward? If not now would be the time to give it the same treatment as elgg.

**Comment by holta** [comment]
> Given apache is popping up unexpectedly as above think it would be wrong to remove the code that would enable nginx to install while the http port is occupied by apache, better to cover that possibility rather than stopping the install dead when nginx can't bind to the same port as apache is using. Is freepbx not going to be supported under apache going forward? If not now would be the time to give it the same treatment as elgg.

@lemueldsouza is making a lot of progress investigating our options here.  Good questions.  If Apache can go away completely, everybody's lives will be a Whole Lot Simpler.  But we'll know a whole lot more within a week.

**Comment by jvonau** [comment]
As is this PR will break the installer when run on https://github.com/iiab/iiab/pull/2850#issuecomment-882093007 please rework to cover the possibility of apache being preinstalled and/or have a second look at #2834's alternate port arrangement which should be useful when the primary http port is already occupied.

**Comment by holta** [comment]
> As is this PR will break the installer when run on [#2850 (comment)](https://github.com/iiab/iiab/pull/2850#issuecomment-882093007)

Excellent point.

Another option might be to mandate that Apache not be installed prior to installing IIAB, fair and square, and simply refuse to install/support such byzantine arrangements.

**Comment by jvonau** [comment]
> Another option might be to mandate that Apache not be installed prior to installing IIAB, fair and square, and simply refuse to install/support such byzantine arrangements.

Lets not waste user's time, add the test for apache in the first file retrieved. As a baby step I suggest you look at https://github.com/iiab/iiab-factory/pull/136 as to warn the end user that their proposed OS target is not supported very early in the install process rather than after ansible is installed and then pukes at iiab-install.

**Comment by holta** [comment]
> Lets not waste user's time, add the test for apache in the first file retrieved. As a baby step I suggest you look at [iiab/iiab-factory#136](https://github.com/iiab/iiab-factory/pull/136) as to warn the end user that their proposed OS target is not supported very early in the install process rather than after ansible is installed and then pukes at iiab-install.

At the same time it's critically important to do active community outreach to "distro junkies" who are willing to do the heavy-lifting to actually make things work, and thereby expand edtech communities like IIAB overall.  I'm torn.  But it's definitely worth looking into for sure, so that we're laying out a better "welcome mat" to different-new-and-evolving demographics.

**Comment by jvonau** [comment]
> > Lets not waste user's time, add the test for apache in the first file retrieved. As a baby step I suggest you look at [iiab/iiab-factory#136](https://github.com/iiab/iiab-factory/pull/136) as to warn the end user that their proposed OS target is not supported very early in the install process rather than after ansible is installed and then pukes at iiab-install.
> 
> At the same time it's critically important to do active community outreach to "distro junkies" who are willing to do the heavy-lifting to actually make things work, and thereby expand edtech communities like IIAB overall. I'm torn. But it's definitely worth looking into for sure, so that we're laying out a better "welcome mat" to different-new-and-evolving demographics.

Just change the logic away from 'exit 1' to just displaying a better big fat warning, I'd still exit on apache being installed to allow the user a chance to correct the condition that will lead to an eventual failure later in the install. Also include the fact that a second admin user being 'iiab-admin' is going to be forced created without user intervention in local_vars.yml. Lots of people don't see the need for another admin on the target machine as a security issue and not using iiab-admin day to day anyway. (think TK uncovering the login bug caused by iiab-admin's old routine which is still has flaws in design).

**Comment by jvonau** [comment]
> At the same time it's critically important to do active community outreach to "distro junkies" who are willing to do the heavy-lifting to actually make things work

Who are those users? All I ever see is wish-listing from people, occasional bug when taken outside of the intended use case. You want to use try to use docker, go ahead it's not a fun job to support across the various distros|desktops|ways to install|use docker.  I suggest disabling auto-networking to serve the niche market of VMs and one-off installs, those who need wifi to serve the content can just run iiab-network to enable that functionality at anytime post install.

**Comment by holta** [comment]
> All I ever see is wish-listing

According to Mitt Romney, 47% of people are takers not givers: https://youtu.be/XnB0NZzl5HA

So yes it's easy to become cynical &mdash; as it's true those dedicating themselves to a wider purpose don't appear every day.

**Comment by holta** [comment]
> I suggest disabling auto-networking to serve the niche market of VMs and one-off installs, those who need wifi to serve the content can just run iiab-network to enable that functionality at anytime post install.

These PR's look very promising:

- #2876 
- iiab/iiab-factory#175

Even if I don't fully understand them and all their ramifications (e.g. documentation will need to change a lot, etc) just yet.

**Comment by jvonau** [comment]
https://github.com/iiab/iiab-factory/pull/175 is an easy fallback to the current installation layout without the enduser having to manually run iiab-network when wifi hardware is detected. RPi hardware users would not have to adjust any current workflows when using the curl routine, the re-ordering of the operations is all that is being done.

**Comment by jvonau** [comment]
well lets take the poison pill now and dicker about #2920 later..

**Comment by holta** [comment]
This PR #2850 is currently being tested on VM 192-u20-desk-BIG-PBX-2850 = 10.8.0.54

ASIDE: while my Ubuntu Server 20.04 still has a 5.4 kernel &mdash; this one's apt suddenly/mysteriously upgraded the kernel from 5.8 to 5.11 &mdash; presumably as a result of Ubuntu 20.04.3 expected [2021-08-19](https://wiki.ubuntu.com/FocalFossa/ReleaseSchedule):

```
root@u20-srv:~# uname -a
Linux box.lan 5.4.0-80-generic #90-Ubuntu SMP Fri Jul 9 22:49:44 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

```
root@u20-desk:~# uname -a
Linux u20-desk 5.8.0-63-generic #71~20.04.1-Ubuntu SMP Thu Jul 15 17:46:08 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

```
root@u20-desk:~# uname -a
Linux box.lan 5.11.0-25-generic #27~20.04.1-Ubuntu SMP Tue Jul 13 17:41:23 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by jvonau** [comment]
So... How many times did it reboot get to the final kernel when you ran iiab?

**Comment by holta** [comment]
Another fresh install test is running on 184-rpi-u2104-srv-BT-CP-pbx-2850 = 10.8.0.22

**Comment by holta** [comment]
> So... How many times did it reboot get to the final kernel when you ran iiab?

Just one reboot (from kernel 5.8 to 5.11) as a result of an `apt update` in recent days.

It's confusing as all are marked as "Ubuntu 20.04.2 LTS" within /etc/issue &mdash; despite 3 very different kernels!

My guess as to the reason: I probably installed Ubuntu Server (happily stuck on kernel 5.4, despite apt updates) at a different time from Ubuntu Desktop (kernel 5.8 -> 5.11).

i.e. possibly I installed Ubuntu Server back in the 20.04.1 era?  As this colorful chart would seem to suggest: https://ubuntu.com/kernel/lifecycle#support-20-04

**Comment by holta** [comment]
Good enough, almost 5 weeks after this PR was posted.

Rome Wasn't Built in a Day.

**Comment by holta** [comment]
> Another fresh install test is running on 184-rpi-u2104-srv-BT-CP-pbx-2850 = 10.8.0.22

Since renamed to 184-rpi4-u2104-srv-BIG-PBX-2850:

- `cd /opt/iiab/iiab ; sudo ./iiab-configure` is now running, as it upgrades itself from sub-MIN to BIG-sized.
- In about an hour, I'll run `sudo /usr/bin/iiab-update-menus` so that http://10.8.0.22 reflects this new reality.

**Comment by jvonau** [comment]
> Good enough, almost 5 weeks after this PR was posted.

Coming from the guy with commit rights, what is your point? I've had PRs open as long as a year.
> Rome Wasn't Built in a Day.

Nor by a single person, but a single barbarian brought the entire empire down.

**Pull request merged**
