### PR TITLE
half of #2834 with a different name

### PR DESCRIPTION
**Pull request by jvonau**
### Fixes bug:
#2904 via local_vars.yml
### Description of changes proposed in this pull request:
new on demand variable
### Smoke-tested on which OS or OS's:
NA
Just because it meets half of the mentioned objective, suppress changing the hostname on demand

### CODE REVIEW

**Comment by holta** [comment]
Ref:

- PR #2834

**Comment by jvonau** [comment]
#2931 @georgejhunt @tim-moody ping these are sort of related, both look to alter|not alter /etc/hostname and the rest of the httpd stack.

**Comment by holta** [comment]
Just FYI

```
hostnamectl set-hostname alice.bob.com
```

...overwrites `/etc/hostname` (putting 'alice.bob.com' in there) but does not touch `/etc/hosts`

**Comment by jvonau** [comment]
I know what the command does, you do see the lineinfile that alters /etc/hosts just below right?

**Comment by holta** [comment]
Related:

- #2933

**Pull request closed without merging**
