### PR TITLE
Pbx no apache

### PR DESCRIPTION
**Pull request by jvonau**

### CODE REVIEW

**Comment by holta** [comment]
@lemueldsouza see this progression building on:

- PR #2862

**Comment by jvonau** [comment]
@holta needs clean install testing, and the code is has not been tried cause I'm heading out for the evening if you could give it a spin just to see if `./start_asterisk stop` shuts down the underling asterisk cleanly so freepbx can start up without the noted warning 'Unable to run Pre-Asterisk hooks, because Asterisk is already running on PID 79506 and has been running for 2 minutes, 27 seconds' in https://github.com/iiab/iiab/pull/2908#issuecomment-892930686

**Comment by holta** [comment]
Thanks: test just begin on an Ubuntu Server 20.04 VM.

I'll push changes to https://github.com/holta/iiab/tree/pbx-no-apache2 if it looks solid.

**Comment by jvonau** [comment]
> I'll push changes to https://github.com/holta/iiab/tree/pbx-no-apache2 if it looks solid.

won't be clean I rolled back a couple of commits

**Comment by jvonau** [comment]
and now the PR broken again...

**Pull request closed without merging**
