### PR TITLE
new default_vars.yml for IIAB 6.6: dhcpd & named -> False; dnsmasq -> True

### PR DESCRIPTION
**Pull request by holta**
@georgejhunt plz review this suggestion from @jvonau & @tim-moody, Thanks!

(It will be not be merged until after IIAB 6.5 is released...)

### CODE REVIEW

**Comment by jvonau** [comment]
To match what dnsmasq is replacing, as you don't want to enable a dhcp server when one is not required as in an appliance mode, maybe use: 
dnsmasq_install: True
dnsmasq_enabled: False

**Comment by holta** [comment]
> To match what dnsmasq is replacing, as you don't want to enable a dhcp server when one is not required as in an appliance mode, maybe use:
dnsmasq_install: True
dnsmasq_enabled: False

Done: Thanks @jvonau.

@georgejhunt & @tim-moody please review prior to Monday's March 19th's community/team call (http://minutes.iiab.io), Thanks!

**Comment by tim-moody** [comment]
it really turns on whether you think enabled means turn on or permit to be turned on.

**Comment by holta** [comment]
These PR's are also under immediate consideration for IIAB 6.6:

#711 "Restore scripts/ansible now that Ansible 2.5.0 is released & smoke-tested"
#712 "Support Ansible 2.5.x: include_role to import_role in Stages 3-9"

**Comment by holta** [comment]
@jvonau & All: should this stale PR be closed, or fixed up to be mergeable with the latest [default_vars.yml](https://github.com/iiab/iiab/blob/master/vars/default_vars.yml) ?

ASIDE: the 6+1 local_vars files in [/opt/iiab/iiab/vars](https://github.com/iiab/iiab/tree/master/vars) might need to be modified too?

**Comment by holta** [comment]
> @jvonau & All: should this stale PR be closed [?]

e.g. is PR #837 might already be sufficient for now?

**Comment by holta** [comment]
CLARIF: @jvonau asked me to close this as he will be moving the 1 critical change/piece (that's still relevant 4 months later) into a new PR.

**Pull request closed without merging**
