### PR TITLE
Net not rpi - wip

### PR DESCRIPTION
**Pull request by jvonau**
The assumption is that the user or the system tools have already written a valid /etc/network/interfaces for the default gateway, don't overwrite that and just supplement the configuration. Joshua K's wifi as WAN issue 'should be' solved with this but needs testing. Testing with wired gateway should be valid as well, but /etc/network/interfaces behaviour needs to be confirmed.

### CODE REVIEW

**Comment by jvonau** [comment]
cool br0.j2  in /etc/network/interfaces.d/ with the default gateway in /etc/network/interfaces works on ubuntu so wifi as WAN is possible. Think that is a cleaner layout, just need to see a pre-runansible copy of /etc/network/interfaces to understand what the system tools created.

**Comment by jvonau** [comment]
ready for testing

**Comment by holta** [comment]
Huge thanks @tim-moody for offering to test!

@jvonau we're assembling a 1000-RPi3 cluster so you can conduct a complete smoke test in less than 1 second going forward (between every keystroke, hopefully you have still a have Corvette in your yard to power this thing ;)

**Comment by tim-moody** [comment]
TASK [network : Copy the bridge script] ****************************************
fatal: [127.0.0.1]: FAILED! => {"changed": false, "failed": true, "msg": "AnsibleError: template error while templating string: Unexpected end of template. Jinja was looking for the following tags: 'elif' or 'else' or 'endif'. The innermost block that needs to be closed is 'if'.. String: # generated by IIAB\n\n# iiab_network_mode is {{ iiab_network_role }}\n# gui_desired_network_role is {{ gui_desired_network_role }}\n\n#################   WIRELESS LAN   #########################\n{% if iiab_wireless_lan_iface != 'none' %}\n# we always want the wireless to be configured (and under bridge) if it exists\nauto {{ iiab_wireless_lan_iface }}\niface {{ iiab_wireless_lan_iface }} inet manual\n   pre-up   ifconfig $IFACE up\n   pre-down ifconfig $IFACE down\n{% endif %}\n\n#################   BRIDGE & SLAVES   #########################\n# hostapd will insert the wireless into the bridge at a later point\nauto br0\niface br0 inet static\n    bridge_ports {% if iiab_wireless_lan_iface != \"none\" %} {{ iiab_wireless_lan_iface }} {% if detected_lan != \"none\" %} {{ detected_lan }} {% endif %}\n    bridge_maxwait 0\n    address {{ lan_ip }}\n    netmask {{ lan_netmask }}\n    dns-nameservers {{ lan_ip }}\n    dns-search {{ iiab_domain }}\n    post-up systemctl restart dhcpd && systemctl restart hostapd\n\n"}
        to retry, use: --limit @/opt/iiab/iiab/iiab.retry

**Comment by jvonau** [comment]
Figures I missed one... fix pushed, git pull and retest please

**Comment by tim-moody** [comment]
TASK [network : Copy the bridge script] ****************************************
fatal: [127.0.0.1]: FAILED! => {"changed": false, "failed": true, "msg": "AnsibleUndefinedVariable: 'iiab_network_role' is undefined"}

**Comment by jvonau** [comment]
That should of been iiab_network_mode, change pushed

**Comment by tim-moody** [comment]
TASK [network : Copy the bridge script] ****************************************
fatal: [127.0.0.1]: FAILED! => {"changed": false, "failed": true, "msg": "AnsibleUndefinedVariable: 'detected_lan' is undefined"}
        to retry, use: --limit @/opt/iiab/iiab/iiab.retry

**Comment by tim-moody** [comment]
let me know when you have found and removed all the syntax errors

**Comment by jvonau** [comment]
Well that was the last variable used in that file, hope there are no more.

**Comment by tim-moody** [comment]
TASK [network : restart the networking service] ********************************
fatal: [127.0.0.1]: FAILED! => {"changed": false, "failed": true, "msg": "Unable to restart service networking: Job for networking.service failed because the control process exited with error code.\nSee \"systemctl status networking.service\" and \"journalctl -xe\" for details.\n"}
        to retry, use: --limit @/opt/iiab/iiab/iiab.retry

PLAY RECAP *********************************************************************
127.0.0.1                  : ok=197  changed=31   unreachable=0    failed=1

root@raspberrypi:/opt/iiab/iiab# systemctl status networking.service
● networking.service - Raise network interfaces
   Loaded: loaded (/lib/systemd/system/networking.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Mon 2017-08-28 21:43:46 UTC; 16min ago
     Docs: man:interfaces(5)
  Process: 4752 ExecStop=/sbin/ifdown -a --read-environment --exclude=lo (code=exited, status=0/SUCCESS)
  Process: 4788 ExecStart=/sbin/ifup -a --read-environment (code=exited, status=1/FAILURE)
  Process: 4782 ExecStartPre=/bin/sh -c [ "$CONFIGURE_INTERFACES" != "no" ] && [ -n "$(ifquery --read-environment --list --exclude=lo)" ] && udevadm settle (code=exited, status=0/SUCCESS)
 Main PID: 4788 (code=exited, status=1/FAILURE)

Aug 28 21:43:46 raspberrypi ifup[4788]: Loading netfilter rules...run-parts: executing /usr/share/netfilter-persistent/plugins.d/15-ip4tables start
Aug 28 21:43:46 raspberrypi ifup[4788]: run-parts: executing /usr/share/netfilter-persistent/plugins.d/25-ip6tables start
Aug 28 21:43:46 raspberrypi ifup[4788]: done.
Aug 28 21:43:46 raspberrypi ifup[4788]: Job for dhcpd.service failed because of unavailable resources or another system error.
Aug 28 21:43:46 raspberrypi ifup[4788]: See "systemctl status dhcpd.service" and "journalctl -xe" for details.
Aug 28 21:43:46 raspberrypi ifup[4788]: ifup: failed to bring up br0
Aug 28 21:43:46 raspberrypi systemd[1]: networking.service: Main process exited, code=exited, status=1/FAILURE
Aug 28 21:43:46 raspberrypi systemd[1]: Failed to start Raise network interfaces.
Aug 28 21:43:46 raspberrypi systemd[1]: networking.service: Unit entered failed state.
Aug 28 21:43:46 raspberrypi systemd[1]: networking.service: Failed with result 'exit-code'.
root@raspberrypi:/opt/iiab/iiab# df
Filesystem     1K-blocks    Used Available Use% Mounted on
/dev/root      123588700 2305744 120011384   2% /
devtmpfs          470176       0    470176   0% /dev
tmpfs             474784       0    474784   0% /dev/shm
tmpfs             474784   12280    462504   3% /run
tmpfs               5120       4      5116   1% /run/lock
tmpfs             474784       0    474784   0% /sys/fs/cgroup
/dev/mmcblk0p1     42136   21473     20663  51% /boot
tmpfs              94956       0     94956   0% /run/user/1000
root@raspberrypi:/opt/iiab/iiab# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
2: enxb827eb6f70ac: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether b8:27:eb:6f:70:ac brd ff:ff:ff:ff:ff:ff
    inet 192.168.0.37/24 brd 192.168.0.255 scope global enxb827eb6f70ac
       valid_lft forever preferred_lft forever
3: wlan0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc pfifo_fast state DOWN group default qlen 1000
    link/ether b8:27:eb:3a:25:f9 brd ff:ff:ff:ff:ff:ff
4: br0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN group default qlen 1000
    link/ether ca:cd:4c:27:79:09 brd ff:ff:ff:ff:ff:ff
    inet 172.18.96.1/19 brd 172.18.127.255 scope global br0
       valid_lft forever preferred_lft forever
    inet 169.254.99.176/16 brd 169.254.255.255 scope global br0
       valid_lft forever preferred_lft forever

**Comment by jvonau** [comment]
> Aug 28 21:43:46 raspberrypi ifup[4788]: Job for dhcpd.service failed because of unavailable resources or another system error.
Aug 28 21:43:46 raspberrypi ifup[4788]: See "systemctl status dhcpd.service" and "journalctl -xe" for details.

Ok so 'post-up systemctl restart dhcpd && systemctl restart hostapd ' in br0 is failing. don't think I need to see that but it couldn't hurt.

> inet 169.254.99.176/16 brd 169.254.255.255 scope global br0

Think dhcpcd took over the interface, that is a link-local address, if so there needs to a stanza for the gateway device with dhcp in it, like the the combined interfaces. After that should dhcpcd be turned off would be the question.

**Comment by jvonau** [comment]
>    root@raspberrypi:/opt/iiab/iiab# ps -A | grep dh
      551 ?        00:00:00 dhcpcd
        yea raspbain-8 maybe 9 also is using dhcpcd, in the client all the others look like dhclient is used  via network.service. Can you check 'ps -A | grep dh' should show dhcpcd or dhclient

​While poking at JK's Ubuntu machine I saw 2 both dhcpcd & dhclient running, that was with dhcp in the interfaces or br0 file. I was not sure what client would be present coming out of the box, that was the reasoning behind suppressing installation of dhcpcd. Still not totally sure what a virgin Ubuntu machine is equipped with as dhcpcd was installed during JK's ansible run.

Tim's reboot needed master test run machine would of being using dhcp in the config file so I suspect it has the same, 2 client running situation. It works but I rather not do that, feels icky. 11f100c has detection code,  e62d1d3 is the dhcpcd stop/start deal with the above error, without resorting to using a config file just yet. Yea I understand 'been around the barn'.  

This should be testable to this point

> so there needs to a stanza for the gateway device with dhcp in it, like the the combined interfaces. After that should dhcpcd be turned off would be the question.

I'm now leaning towards dhcpcd/manual if wan file is needed as being the most used. 1320924  has the future pick the {{ dhcp_client }} for the wan file. The idea is to fall back to dhclient/dhcp should dhcpcd not be available, wan file will be required,  is present but currently disabled pending the outcome. 

The goal here is to make using wifi as upstream painless as possible for the end user by not using the interfaces file.

**Comment by jvonau** [comment]
enabled the final file replacement routine

**Comment by georgejhunt** [comment]
What problem is this PR trying to fix?

**Comment by holta** [comment]
@georgejhunt plz read http://minutes.iiab.io

A very reliable, very compact IIAB on Raspbian Stretch is the #1 goal we're all working towards, that everything else depends on.

Today ./runansible fails and a reboot followed by a 2nd ./runansible acts as a don't-ask-don't-tell workaround.

@jvonau worked extremely hard on #171 here but testing hasn't worked out as we hoped (everyone hoped this would solve things during Monday August 28th's call) so it needs you to put your head together with Jerry & @tim-moody to work out a thoughtful/clean/resilient solution.

_Thanks all for your Extreme Ongoing Dedication, as this central question is indeed Tough As Hell!_

**Comment by jvonau** [comment]
The whole point is to allow users to use wifi as the upstream, like on the XO's 
> At this point my WIFI could not be detected automatically. This is apart from the fact that during setup i had successfully accessed my home WIFI. so i entered the configuration manually in editing the following file using nano
	sudo nano /etc/network/interfaces
auto <wireless interface name> 
iiface <wireless interface name> inet dhcp 
wpa-ssid <your_router> 
wpa-psk <your_wpa_key>
I then did shut down the interface and turned it back on using
 	sudo ifdown <wireless interface name> && sudo ifup -v <wireless interface name>
I then jumped to https://github.com/iiab/iiab/wiki/IIAB-Installation#do-everything-from-scratch

**Comment by georgejhunt** [comment]
I'd like to check this out:

https://raspberrypi.stackexchange.com/questions/53245/pi-3-raspbian-stretch-testing-disables-wifi

**Comment by jvonau** [comment]
Closing as #178 is current but the debug info gathered, noted errors, and other potential fixes might be referred to later. Thanks for testing.

**Pull request closed without merging**
