### PR TITLE
Fix Wordpress posting + raise limits in fpm/php.ini when {Moodle, Nextcloud, PBX, WordPress} installed + move {www_back_end, www_front_end} to {www_base, www_options}

### PR DESCRIPTION
**Pull request by holta**
Attempts to fix serious & ongoing WordPress posting problems (#2274).

@tim-moody, @jvonau, @georgejhunt, @ericnitschke, @kananigit: can you confirm that /etc/php/{{ php_version }}/fpm/php.ini is relevant to WordPress & Moodle?

Specifically: is line 73 @ https://github.com/holta/iiab/blob/wordpress-fixes/roles/www_front_end/tasks/main.yml#L73 the way we want it?

### CODE REVIEW

**Comment by tim-moody** [comment]
php defaults appear to be hard coded. why not softcode?

**Comment by holta** [comment]
> php defaults appear to be hard coded. why not softcode?

When this was done around 2018, a higher-level toggle (nginx_high_php_limits) was deemed far more useful than a "paradox of freedom" flooding new implementers with an overwhelming array of persnickety choices.

Regardless, more experienced implementers will all be manually hacking their own /etc/php/{{ php_version }}/fpm/php.ini

But that design decision of 2018 could certainly be revisited, e.g. if there's rising popular demand to fuss with i.e. modify all 5 of these php.ini settings possibly?

**Comment by tim-moody** [comment]
> Regardless, more experienced implementers will all be manually hacking their own /etc/php/{{ php_version }}/fpm/php.ini

will they expect to lose their changes if they ever runrole or install?

**Comment by holta** [comment]
> > Regardless, more experienced implementers will all be manually hacking their own /etc/php/{{ php_version }}/fpm/php.ini
> 
> will they expect to lose their changes if they ever runrole or install?

Always a risk if they don't edit `roles/www_front_end/tasks/main.yml` directly. [*]

Some kind of very-higher-level informed consent warning is certainly needed here...to enhance newcomer+intermediate+guru implementers' understanding.  We all know Linux gurus won't read instructions, as they literally cannot stop themselves from hand-editing files in /etc and other such places.

Hence our perpetual need to try to better communicate which files are intentionally auto-edited ~ under what circumstances ~ for what purposes.


[*] please see @tim-moody's suggestion at  https://github.com/iiab/iiab/commit/8abc11d54b1ce3512dfe6e0657ef86caf4aa73c4#commitcomment-37696578 that we rename mini-roles:

- roles/www_back_end
- roles/www_front_end

To...

- roles/www_base
- roles/www_configurable [let's try out www_options which is much shorter!]

**Comment by holta** [comment]
@jvonau can say where you want these "apt install php-fpm" calls moved to?

- [www_options/tasks/main.yml#L32-L35](https://github.com/holta/iiab/blob/wordpress-fixes/roles/www_options/tasks/main.yml#L32-L35)
- (https://github.com/holta/iiab/blob/wordpress-fixes/roles/nextcloud/tasks/install.yml#L55)

And why you want all apt/package installs entirely removed from 4-server-options ?

**Comment by holta** [comment]
Tested on Debian 10.3

**Comment by jvonau** [comment]
> @jvonau can say where you want these "apt install php-fpm" calls moved to?
> 
>     * [www_options/tasks/main.yml#L32-L35](https://github.com/holta/iiab/blob/wordpress-fixes/roles/www_options/tasks/main.yml#L32-L35)
> 

Just remove the apt call as php-fpm is already being installed in [nginx's role](https://github.com/iiab/iiab/blob/master/roles/nginx/tasks/install.yml). No real point to limiting to (nextcloud_install or pbx_install) when admin-console needs php socket to be active, might want to add enabled just to be safe.

>     * (https://github.com/holta/iiab/blob/wordpress-fixes/roles/nextcloud/tasks/install.yml#L55)
> 
> 
> And why you want all apt/package installs entirely removed from 4-server-options ?

I don't, you seem to not apply the same 'installed' framework around php-fpm as other services (that went a bit too far for things installed in 1-3 IMHO) but that is fine with me as php-fpm is installed in 3-base-server via nginx and the fine tuning is performed in 4-server-options. I'm for soft-coding, make those available for use manually and provide a "quick preset" that could populate the variables.

**Pull request merged**
