### PR TITLE
Lockout installs and upgrades when no internet present

### PR DESCRIPTION
**Pull request by jvonau**
just stuff

### CODE REVIEW

**Comment by tim-moody** [comment]
is configuration of a role possible when there is no internet? (e.g. packages installed on a previous run but database or other configuration has not completed.)

**Comment by holta** [comment]
Good question.  Also there are so many different ways to reinstall vs. upgrade vs. reconfigure vs. change data(base) content vs. wipe/safeguard personal data — that this can get painful/confusing as hell :/

**Comment by jvonau** [comment]
> is configuration of a role possible when there is no internet? (e.g. packages installed on a previous run but database or other configuration has not completed.)

Why does iiab-from-console.yml exist if one can't configure and enable|disable already installed web apps? Should I put in a PR to remove  iiab-from-console.yml as nobody does configuration after the initial iiab-install?

 > Good question. Also there are so many different ways to reinstall vs. upgrade vs. reconfigure vs. change data(base) content vs. wipe/safeguard personal data — that this can get painful/confusing as hell :/

Please keep the noise applicable to the respective PRs.. This PR is about early halting and warning the user that internet is required for the requested operation.

**Comment by jvonau** [comment]
forking

**Pull request closed without merging**
