### PR TITLE
WIP: AppArmor works with IIAB on Debian 10/11, so is this now also true on Ubuntu?

### PR DESCRIPTION
**Pull request by holta**
To be determined.

In any case, this PR helps community-testing towards cleaner resolution of the AppArmor question(s).

### CODE REVIEW

**Comment by holta** [comment]
I'll try to evaluate this by rebuilding 182-rpi4-2g-u2010-srv-MIN

**Comment by holta** [comment]
fyi the 1-line install to test this (PR #2654) is:

```
curl d.iiab.io/install.txt | sudo bash -s 2654
```

i.e. to test this on one Ubuntu or another.

**Comment by holta** [comment]
> I'll try to evaluate this by rebuilding 182-rpi4-2g-u2010-srv-MIN

The new name is: `182-rpi4-2g-u2010-srv-MIN-1128`

Testers who want to check out the ongoing install (currently in Stage 4 of 9) can log in to: `10.8.0.42`

**Comment by holta** [comment]
> Testers who want to check out the ongoing install (currently in Stage 4 of 9) can log in to: `10.8.0.42`

Install completed & rebooted.

I'm now converting it from MIN-sized to MEDIUM-sized to broaden testing, and so changing the name to:
`182-rpi4-2g-u2010-srv-MEDIU-1128`

**Comment by jvonau** [comment]
AppArmor might work ok with apt(dnsmasq, nginx, php) installed programs, but we have custom apps that AppArmor knows nothing about, those are the ones I would be concerned about functioning properly.

**Comment by holta** [comment]
> AppArmor might work ok with apt(dnsmasq, nginx, php) installed programs, but we have custom apps that AppArmor knows nothing about, those are the ones I would be concerned about functioning properly.

Good to know.

Given IIAB has quite a [number of apps](http://wiki.laptop.org/go/IIAB/FAQ#What_services_.28IIAB_apps.29_are_suggested_during_installation.3F) installed via non-apt approaches (Kiwix, Moodle, Sugarizer, Internet Archive, and others...)

These 2 installations of PR #2654 are available for testing, to help us do a bit better with security, now that AppArmor is becoming more universal across Debian, Ubuntu, etc:

- http://10.8.0.42 = 182-rpi4-2g-u2010-srv-MEDIU-1128 (Ubuntu Server 20.10, on a Raspberry Pi 4)
- http://10.8.0.34 = 191-u20041-srv-BIG-PR2654-1128 (Ubuntu Server 20.04.1, on a VM, install not yet complete but currently in Stage 6 of 9)

**Comment by holta** [comment]
> * http://10.8.0.42 = 182-rpi4-2g-u2010-srv-MEDIU-1128 (Ubuntu Server 20.10, on a Raspberry Pi 4)
> * http://10.8.0.34 = 191-u20041-srv-BIG-PR2654-1128 (Ubuntu Server 20.04.1, on a VM)

Both above installations of `curl d.iiab.io/install.txt | sudo bash -s 2654` are now complete.  To help with testing this PR so it can be merged and/or revised as necessary.

**Comment by holta** [comment]
This PR was also tested on a 3rd OS (Linux Mint 20, on VM 195-mint20-MIN, now being upgraded to 195-mint20-BIG-1128) without encountering any problems.

**Comment by holta** [comment]
Functionality testing of all 3 above OS's did not uncover any obvious flaws with AppArmor running, as shown by:

```
systemctl status apparmor
```

So I'm now merging this PR, to expand community testing yet further.

**Pull request merged**
