### PR TITLE
Remove 'when: internet_available' from 25 files [preserving it in network/tasks/netplan.yml + www_options/tasks/main.yml for now]

### PR DESCRIPTION
**Pull request by holta**
Building on @jvonau's:

- PR #2971

This is years overdue, given that `when: internet_available` was never used as intended, as explained at #2959.

Testing is ongoing to verify.

### CODE REVIEW

**Comment by jvonau** [comment]
Too far, network and www_options lack install.yml those roles still need internet_available to be present..

**Comment by jvonau** [comment]
whatever your ball now you run with with it..

**Comment by holta** [comment]
> Too far, network and www_options lack install.yml those roles still need internet_available to be present..

That makes sense for [www_options](https://github.com/iiab/iiab/tree/master/roles/www_options), Ok:

https://github.com/iiab/iiab/blob/1f94166a232e3d6bc0b496b010dbe27e28bb77bd/roles/www_options/tasks/main.yml#L159-L161

Note that [Groovy](https://releases.ubuntu.com/20.10/) was EOL'd on [2021-07-22](https://wiki.ubuntu.com/Releases#End_of_Life), so this code needs to be updated regardless:

https://github.com/iiab/iiab/blob/a581d6ebf4dec6b41a3b61fa578507c9ff33db8b/roles/network/tasks/netplan.yml#L62-L66

Should it be changed to something like `is_ubuntu` ?  Or are post-Groovy particulars like `hirsute` and `impish` still important?

Ref:

- #2585

**Comment by jvonau** [comment]
> Note that Groovy was EOL'd on 2021-07-22, so this code needs to be updated regardless:
> 
> https://github.com/iiab/iiab/blob/a581d6ebf4dec6b41a3b61fa578507c9ff33db8b/roles/network/tasks/netplan.yml#L62-L66
> 
> Should it be changed to something like `is_ubuntu` ? Or are post-Groovy particulars like `hirsute` and `impish` still important?

The fix is 'Groovy' specific, 21.04 and later should have the fix baked into a newer apt package installed by default.

**Comment by jvonau** [comment]
back out the two mentioned roles, (re network - the match covers 20.10 as nothing stops the user from starting at that point..) ok  done I see, thanks

**Comment by holta** [comment]
Testing is ongoing with a BIG-sized IIAB install onto a Debian 11 (server) VM.

**Pull request merged**
