### PR TITLE
fix runtags XXX

### PR DESCRIPTION
**Pull request by jvonau**

### CODE REVIEW

**Comment by holta** [comment]
@jvonau @tim-moody @georgejhunt

Can we consider "list-tags" or similar, instead of "XXX" ?

(Unfortunately I did not grasp what the error message was saying earlier: I thought XXX within "./runtags XXX" was some kind of placeholder, rather that an actual flag/command!)

**Comment by tim-moody** [comment]
./runtags list-tags should already work

**Comment by tim-moody** [comment]
I also do not believe we should encourage people to use runtags

**Comment by holta** [comment]
@tim-moody "./runtags list-tags" starts (some kind of) very lengthy Ansible run, rather than listing possible tags as I would have expected.

**Comment by jvonau** [comment]
cause you know everything

**Comment by jvonau** [comment]
> I also do not believe we should encourage people to use runtags

How do you expect remote help to work when runansible crashes before getting to openvpn? In #172 moving the openvpn playbook earlier got poo poo'd. 

How does one remotely execute anything if you can't get to the web-console?

**Comment by holta** [comment]
I know for a fact @tim-moody uses ./runtags to fix his home dishwasher ;) so perhaps it's fair to say that ./runtags should not be used regularly, and certainly not with multiple tags &mdash; and *definitely* not by casual readers of http://FAQ.IIAB.IO !

**Comment by jvonau** [comment]
I showed you what to change to match the language already present. Do as you see fit.

**Pull request closed without merging**
