### PR TITLE
Ubuntu 20.04 mostly clean install on pre-release version

### PR DESCRIPTION
**Pull request by georgejhunt**
1. Problem with ntpd -- does not start at boot via systemd. but systemd restart works. Tried to make after=network-online.target -- but that did not work.
1. I can't figure out how to make ansible script to use pip3 -- maybe it's an upstream issue, and we just use apt for ansible on ubuntu 20.04.
1. This PR was tested on ubuntu18 and debian10 VMs as well as rpi4 1GB version
1. I used the rpi-imager to copy my ubuntu20.04 image to an SD card. Easy, and does verification also.

### CODE REVIEW

**Comment by jvonau** [comment]
Can you post the iiab-install.log from ubuntu-20.04 please

**Comment by jvonau** [comment]
Chances are ntp is not starting because it is being masked at the systemd level, it is masked on raspbian.
> i@box:~ $ systemctl status ntp
● ntp.service
     Loaded: masked (Reason: Unit ntp.service is masked.)
     Active: inactive (dead)

because something like chrony that was installed in 1-prep/main.yml is providing that functionality 
> pi@box:~ $ systemctl status chrony
● chrony.service - chrony, an NTP client/server
     Loaded: loaded (/lib/systemd/system/chrony.service; enabled; vendor preset: enabled)
     Active: active (running) since Mon 2020-03-09 17:18:34 GMT; 5 days ago
       Docs: man:chronyd(8)
             man:chronyc(1)
             man:chrony.conf(5)
   Main PID: 902 (chronyd)
      Tasks: 2 (limit: 4915)
     Memory: 1.5M
     CGroup: /system.slice/chrony.service
             ├─902 /usr/sbin/chronyd -F -1
             └─917 /usr/sbin/chronyd -F -1
Mar 09 17:18:33 box.lan systemd[1]: Starting chrony, an NTP client/server...
Mar 09 17:18:33 box.lan chronyd[902]: chronyd version 3.5 starting (+CMDMON +NTP +REFCLOCK +RTC +PRIV>
Mar 09 17:18:34 box.lan chronyd[902]: Frequency 23.548 +/- 0.041 ppm read from /var/lib/chrony/chrony>
Mar 09 17:18:34 box.lan chronyd[902]: Loaded seccomp filter
Mar 09 17:18:34 box.lan systemd[1]: Started chrony, an NTP client/server.
Mar 09 17:19:07 box.lan chronyd[902]: Selected source 172.105.10.241
Mar 09 17:19:07 box.lan chronyd[902]: System clock wrong by 12.592242 seconds, adjustment started
Mar 09 17:19:19 box.lan chronyd[902]: System clock was stepped by 12.592242 seconds
Mar 13 10:39:09 box.lan chronyd[902]: Source 172.105.10.241 replaced with 207.34.48.31
 
Neither ntp nor chrony are really needed as systemd-timesync is enabled by default on modern OS with systemd. 

> pi@box:~ $ systemctl status systemd-timesyncd --no-pager -l
● systemd-timesyncd.service - Network Time Synchronization
     Loaded: loaded (]8;;file://box.lan/lib/systemd/system/systemd-timesyncd.service/lib/systemd/system/systemd-timesyncd.service]8;;; enabled; vendor preset: enabled)
    Drop-In: /lib/systemd/system/systemd-timesyncd.service.d
             └─]8;;file://box.lan/lib/systemd/system/systemd-timesyncd.service.d/disable-with-time-daemon.confdisable-with-time-daemon.conf]8;;
     Active: inactive (dead)
  Condition: start condition failed at Mon 2020-03-09 17:18:22 GMT; 5 days ago
       Docs: ]8;;man:systemd-timesyncd.service(8)man:systemd-timesyncd.service(8)]8;;
Mar 09 17:18:22 box.lan systemd[1]: Condition check resulted in Network Time Synchronization being skipped.

but gets disabled once chrony or ntp is installed
> pi@box:~ $ cat /lib/systemd/system/systemd-timesyncd.service.d/disable-with-time-daemon.conf 
[Unit]
\# don't run timesyncd if we have another NTP daemon installed
ConditionFileIsExecutable=!/usr/sbin/ntpd
ConditionFileIsExecutable=!/usr/sbin/openntpd
ConditionFileIsExecutable=!/usr/sbin/chronyd
ConditionFileIsExecutable=!/usr/sbin/VBoxService

Nice catch with fake-hwclock need that for offline. The question becomes should we bother to install any more time support add-ons, and if we do, only install one. I'd go with less is better and not install either as the OS is providing that functionality out of the box. #2289 is where I was going with that thinking, I limited the dphys-swapfile mods to raspbian as I was unsure if dphys-swapfile package was available or the same name, but swapfile is needed for when the box becomes stressed. I'll update that PR with the new information.

`apt -y install ansible python3-pymysql python3-psycopg2 python3-passlib python3-pip python3-setuptools python3-venv virtualenv`
does the equivalent for now, can you review #2291?

**Comment by holta** [comment]
Earlier research on Ubuntu 20.04 LTS pre-releases:

#2269 
#2270

**Comment by georgejhunt** [comment]
diagnostics: https://pastebin.com/qh4qbVmt
 last 5000 lines of log: https://paste.ubuntu.com/p/T8dvtWzssG/

**Comment by jvonau** [comment]
Perfect thanks
> 2020-03-15 01:51:18,051 p=20814 u=root n=ansible | changed: [127.0.0.1] => (item={'option': 'dhcpcd_result', 'value': ''})
2020-03-15 01:51:18,699 p=20814 u=root n=ansible | changed: [127.0.0.1] => (item={'option': 'network_manager_active', 'value': False})
2020-03-15 01:51:19,285 p=20814 u=root n=ansible | changed: [127.0.0.1] => (item={'option': 'systemd_networkd_active', 'value': True})
2020-03-15 01:51:19,870 p=20814 u=root n=ansible | changed: [127.0.0.1] => (item={'option': 'wan_in_interfaces', 'value': False})

The log shows that netplan.yml was run
> 2020-03-15 01:52:26,464 p=20814 u=root n=ansible | TASK [network : Netplan in use on Ubuntu 18.04+] ***********************************************************************************************************************************
2020-03-15 01:52:26,664 p=20814 u=root n=ansible | included: /opt/iiab/iiab/roles/network/tasks/netplan.yml for 127.0.0.1
2020-03-15 01:52:26,940 p=20814 u=root n=ansible | TASK [network : Figure out netplan file name] **************************************************************************************************************************************
2020-03-15 01:52:27,562 p=20814 u=root n=ansible | changed: [127.0.0.1]
2020-03-15 01:52:27,705 p=20814 u=root n=ansible | TASK [network : Disable cloud-init the easy way] ***********************************************************************************************************************************
2020-03-15 01:52:27,768 p=20814 u=root n=ansible | skipping: [127.0.0.1] => (item=50-cloud-init.yaml) 
2020-03-15 01:52:27,914 p=20814 u=root n=ansible | TASK [network : Remove stock netplan template] *************************************************************************************************************************************
2020-03-15 01:52:28,579 p=20814 u=root n=ansible | changed: [127.0.0.1] => (item=50-cloud-init.yaml)
2020-03-15 01:52:28,721 p=20814 u=root n=ansible | TASK [network : Cheap way to do systemd unmask] ************************************************************************************************************************************
2020-03-15 01:52:29,358 p=20814 u=root n=ansible | ok: [127.0.0.1]
2020-03-15 01:52:29,499 p=20814 u=root n=ansible | TASK [network : Ensure systemd-networkd-wait-online is enabled] ********************************************************************************************************************
2020-03-15 01:52:30,610 p=20814 u=root n=ansible | ok: [127.0.0.1] => (item=systemd-networkd-wait-online)
2020-03-15 01:52:30,754 p=20814 u=root n=ansible | TASK [network : Static IP computing CIDR] ******************************************************************************************************************************************
2020-03-15 01:52:30,801 p=20814 u=root n=ansible | skipping: [127.0.0.1]
2020-03-15 01:52:30,950 p=20814 u=root n=ansible | TASK [network : Static IP setting CIDR] ********************************************************************************************************************************************
2020-03-15 01:52:30,996 p=20814 u=root n=ansible | skipping: [127.0.0.1]
2020-03-15 01:52:31,138 p=20814 u=root n=ansible | TASK [network : Supply netplan template] *******************************************************************************************************************************************
2020-03-15 01:52:32,313 p=20814 u=root n=ansible | changed: [127.0.0.1]

We have NM being skipped and with systemd_networkd_active we have sysd-netd-debian.yml being run creating br0.
> 2020-03-15 01:52:32,455 p=20814 u=root n=ansible | TASK [network : NetworkManager in use] *********************************************************************************************************************************************
2020-03-15 01:52:32,502 p=20814 u=root n=ansible | skipping: [127.0.0.1]
2020-03-15 01:52:32,649 p=20814 u=root n=ansible | TASK [network : systemd-networkd in use] *******************************************************************************************************************************************
2020-03-15 01:52:32,858 p=20814 u=root n=ansible | included: /opt/iiab/iiab/roles/network/tasks/sysd-netd-debian.yml for 127.0.0.1
2020-03-15 01:52:33,147 p=20814 u=root n=ansible | TASK [network : Copy the bridge script - Creates br0] ******************************************************************************************************************************
2020-03-15 01:52:34,338 p=20814 u=root n=ansible | changed: [127.0.0.1]
2020-03-15 01:52:34,478 p=20814 u=root n=ansible | TASK [network : Copy the bridge script - Assigns IP address] ***********************************************************************************************************************
2020-03-15 01:52:35,704 p=20814 u=root n=ansible | changed: [127.0.0.1]

rpi_debian.yml is never run so any changes in that file are being ignored and not being performed.
> 2020-03-15 01:52:44,069 p=20814 u=root n=ansible | TASK [network : RPi's have dhcpcd in use] ******************************************************************************************************************************************
2020-03-15 01:52:44,111 p=20814 u=root n=ansible | skipping: [127.0.0.1]
2020-03-15 01:52:44,267 p=20814 u=root n=ansible | TASK [network : Not RPi, Not NetworkManager, Not systemd-networkd in use] **********************************************************************************************************
2020-03-15 01:52:44,321 p=20814 u=root n=ansible | skipping: [127.0.0.1]

**Comment by georgejhunt** [comment]
closed in favor of #2320

**Pull request closed without merging**
