### PR TITLE
mongodb/tasks/install.yml: Try 5.0.x (was 4.4.x) on all four 64-bit OS's (for Sugarizer)

### PR DESCRIPTION
**Pull request by holta**
Thanks to @llaske's recommendation at:

- #3190

### CODE REVIEW

**Comment by holta** [comment]
@llaske: Is it possible your Ubuntu 21.10 preserved libssl 1.1 (or parts of it?!) allowing MongoDB 5.0.8 to install — somewhat artificially — which might explain why MongoDB 5.0.8 still today cannot be installed on a fresh install of Ubuntu 22.04?

RECAP:

(1) This PR does not solve the Ubuntu 22.04 problem (see `Depends: libssl1.1 (>= 1.1.1) but it is not installable` errors pasted below, just the same as #3190 according to the test I just ran).

(2) On the bright side, this PR is probably a good idea for other reasons &mdash; simply to modernize IIAB's MongoDB from 4.4.x to 5.0.x (while others are now beginning to move to MongoDB 6.0).

> TASK [mongodb : Install packages: mongodb-org, mongodb-org-server] *************
fatal: [127.0.0.1]: FAILED! => {"cache_update_time": 1652019062, "cache_updated": false, "changed": false, "msg": "'/usr/bin/apt-get -y -o \"Dpkg::Options::=--force-confdef\" -o \"Dpkg::Options::=--force-confold\"       install 'mongodb-org' 'mongodb-org-server'' failed: E: Unable to correct problems, you have held broken packages.\n", "rc": 100, "stderr": "E: Unable to correct problems, you have held broken packages.\n", "stderr_lines": ["E: Unable to correct problems, you have held broken packages."], "stdout": "Reading package lists...\nBuilding dependency tree...\nReading state information...\nSome packages could not be installed. This may mean that you have\nrequested an impossible situation or if you are using the unstable\ndistribution that some required packages have not yet been created\nor been moved out of Incoming.\nThe following information may help to resolve the situation:\n\nThe following packages have unmet dependencies:\n mongodb-org-mongos : Depends: libssl1.1 (>= 1.1.1) but it is not installable\n mongodb-org-server : Depends: libssl1.1 (>= 1.1.1) but it is not installable\n mongodb-org-shell : Depends: libssl1.1 (>= 1.1.1) but it is not installable\n", "stdout_lines": ["Reading package lists...", "Building dependency tree...", "Reading state information...", "Some packages could not be installed. This may mean that you have", "requested an impossible situation or if you are using the unstable", "distribution that some required packages have not yet been created", "or been moved out of Incoming.", "The following information may help to resolve the situation:", "", "The following packages have unmet dependencies:", " mongodb-org-mongos : Depends: libssl1.1 (>= 1.1.1) but it is not installable", " mongodb-org-server : Depends: libssl1.1 (>= 1.1.1) but it is not installable", " mongodb-org-shell : Depends: libssl1.1 (>= 1.1.1) but it is not installable"]}

**Comment by holta** [comment]
Clarification that the above test _(attempting to install MongoDB 5.0.8)_ on Ubuntu Desktop 22.04 used:

```
root@box:~# cat /etc/apt/sources.list.d/mongodb-org.list
deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/5.0 multiverse
```

Which leads to the same error as when _(attempting to install MongoDB 4.4.13)_ using:

```
root@box:~# cat /etc/apt/sources.list.d/mongodb-org.list
deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/4.4 multiverse
```

**Comment by llaske** [comment]
> @llaske: Is it possible your Ubuntu 21.10 preserved libssl 1.1 (or parts of it?!) allowing MongoDB 5.0.8 to install — somewhat artificially — which might explain why MongoDB 5.0.8 still today cannot be installed on a fresh install of Ubuntu 22.04?

@holta yes it's possible.

**Comment by holta** [comment]
This PR was tested on the older Ubuntu Server 20.04:

http://box/sugarizer appears to run fine with MongoDB 5.0.8

**Pull request merged**
