### PR TITLE
PR to help with Asterisk 20 testing

### PR DESCRIPTION
**Pull request by holta**
Thank you @EMG70 if you get the chance to run this on Debian 11:

```curl iiab.io/install.txt | bash -s 3508```

As outlined within:

- #3502

ASIDE: The May 2022 fix to assure the latest FreePBX is here:

- PR #3229

### CODE REVIEW

**Comment by EMG70** [comment]
I am currently on it, I will let you know by Sunday evening UK time.Thanks.

**Comment by holta** [comment]
@EMG70 do you get this same exact **jansson-2.14** error below, when installing Asterisk 20 on Debian 11?

Any idea if the error below is repeatable or intermittent?

Oct 2022 discussion of jansson-2.14 with Asterisk 20...that might possibly be helpful:
https://community.asterisk.org/t/problems-installing-asterisk/94503/19

```
2023-03-24 16:51:41,117 p=4471 u=root n=ansible | TASK [pbx : Asterisk - Run './configure --with-pjproject-bundled --with-jansson-bundled'] ***
2023-03-24 16:51:44,199 p=4471 u=root n=ansible | fatal: [127.0.0.1]: FAILED! => {"changed": true, "cmd": ["./configure", "--with-pjproject-bundled", "--with-jansson-bundled"], "delta": "0:00:02.732043", "end": "2023-03-24 16:51:44.156844", "msg": "non-zero return code", "rc": 1, "start": "2023-03-24 16:51:41.424801", "stderr": "make: *** [Makefile:68: /tmp/jansson-2.14.tar.bz2] Error 5\nmake: *** Deleting file '/tmp/jansson-2.14.tar.bz2'\nconfigure: error: Re-run the ./configure command with 'NOISY_BUILD=yes' appended to see error details.", "stderr_lines": ["make: *** [Makefile:68: /tmp/jansson-2.14.tar.bz2] Error 5", "make: *** Deleting file '/tmp/jansson-2.14.tar.bz2'", "configure: error: Re-run the ./configure command with 'NOISY_BUILD=yes' appended to see error details."], "stdout": "checking build system type... x86_64-pc-linux-gnu\nchecking host system type... x86_64-pc-linux-gnu\nchecking for gcc... gcc\nchecking whether the C compiler works... yes\nchecking for C compiler default output file name... a.out\nchecking for suffix of executables... \nchecking whether we are cross compiling... no\nchecking for suffix of object files... o\nchecking whether we are using the GNU C compiler... yes\nchecking whether gcc accepts -g... yes\nchecking for gcc option to accept ISO C89... none needed\nchecking how to run the C preprocessor... gcc -E\nchecking for grep that handles long lines and -e... /usr/bin/grep\nchecking for egrep... /usr/bin/grep -E\nchecking for ANSI C header files... yes\nchecking for sys/types.h... yes\nchecking for sys/stat.h... yes\nchecking for stdlib.h... yes\nchecking for string.h... yes\nchecking for memory.h... yes\nchecking for strings.h... yes\nchecking for inttypes.h... yes\nchecking for stdint.h... yes\nchecking for unistd.h... yes\nchecking minix/config.h usability... no\nchecking minix/config.h presence... no\nchecking for minix/config.h... no\nchecking whether it is safe to define __EXTENSIONS__... yes\nchecking whether char is unsigned... no\nchecking for uname... /usr/bin/uname\nchecking for g++... g++\nchecking whether we are using the GNU C++ compiler... yes\nchecking whether g++ accepts -g... yes\nchecking how to run the C preprocessor... gcc -E\nchecking how to run the C++ preprocessor... g++ -E\nchecking for a sed that does not truncate output... /usr/bin/sed\nchecking for egrep... grep -E\nchecking for ld used by gcc... /usr/bin/ld\nchecking if the linker (/usr/bin/ld) is GNU ld... yes\nchecking for gawk... gawk\nchecking for a BSD-compatible install... /usr/bin/install -c\nchecking whether ln -s works... yes\nchecking for ranlib... ranlib\nchecking for GNU make... make\nchecking for egrep... (cached) /usr/bin/grep -E\nchecking for strip... strip\nchecking for ar... ar\nchecking for bison... /usr/bin/bison\nchecking for cmp... /usr/bin/cmp\nchecking for cat... /usr/bin/cat\nchecking for cut... /usr/bin/cut\nchecking for flex... /usr/bin/flex\nchecking for grep... (cached) /usr/bin/grep\nchecking for python2.7... no\nchecking for python2... no\nchecking for python... no\nchecking for python3... /usr/bin/python3\nchecking for find... /usr/bin/find\nchecking for basename... /usr/bin/basename\nchecking for dirname... /usr/bin/dirname\nchecking for sh... /bin/bash\nchecking for ln... /usr/bin/ln\nchecking for doxygen... /usr/bin/doxygen\nchecking for dot... /usr/bin/dot\nchecking for wget... /usr/bin/wget\nchecking for curl... /usr/bin/curl\nchecking for xmllint... :\nchecking for xmlstarlet... /usr/bin/xmlstarlet\nchecking for bash... /bin/bash\nchecking for git... /usr/bin/git\nchecking for alembic... :\nchecking for bzip2... /usr/bin/bzip2\nchecking for tar... /usr/bin/tar\nchecking for patch... /usr/bin/patch\nchecking for sed... (cached) /usr/bin/sed\nchecking for nm... /usr/bin/nm\nchecking for realpath... /usr/bin/realpath\nchecking for ldconfig... /usr/sbin/ldconfig\nchecking for sha1sum... /usr/bin/sha1sum\nchecking for openssl... /usr/bin/openssl\nchecking for pkg-config... /usr/bin/pkg-config\nchecking pkg-config is at least version 0.9.0... yes\nchecking for bison that supports parse-param... /usr/bin/bison\nchecking for soxmix... no\nchecking for md5... no\nchecking for md5sum... md5sum\nchecking for a sed that does not truncate output... (cached) /usr/bin/sed\nchecking whether gcc is Clang... no\nchecking whether pthreads work with -pthread... yes\nchecking for joinable pthread attribute... PTHREAD_CREATE_JOINABLE\nchecking whether more special flags are required for pthreads... no\nchecking for PTHREAD_PRIO_INHERIT... yes\nchecking for RAII support... checking for gcc -fnested-functions... no\nchecking for clang strsep/strcmp optimization... no\nconfigure: checking OPENSSL with pkg-config\nconfigure: checking whether system openssl > 1.1.0\nchecking for OPENSSL... yes\nchecking for embedded jansson (may have to download)... configuring\n[jansson]  Downloading https://raw.githubusercontent.com/asterisk/third-party/master/jansson/2.14/jansson-2.14.tar.bz2 to /tmp/jansson-2.14.tar.bz2\n[jansson]  Retrying download\n[jansson]  Downloading https://raw.githubusercontent.com/asterisk/third-party/master/jansson/2.14/jansson-2.14.tar.bz2 to /tmp/jansson-2.14.tar.bz2\nfailed\nconfigure: Unable to configure /opt/iiab/asterisk/third-party/jansson", "stdout_lines": ["checking build system type... x86_64-pc-linux-gnu", "checking host system type... x86_64-pc-linux-gnu", "checking for gcc... gcc", "checking whether the C compiler works... yes", "checking for C compiler default output file name... a.out", "checking for suffix of executables... ", "checking whether we are cross compiling... no", "checking for suffix of object files... o", "checking whether we are using the GNU C compiler... yes", "checking whether gcc accepts -g... yes", "checking for gcc option to accept ISO C89... none needed", "checking how to run the C preprocessor... gcc -E", "checking for grep that handles long lines and -e... /usr/bin/grep", "checking for egrep... /usr/bin/grep -E", "checking for ANSI C header files... yes", "checking for sys/types.h... yes", "checking for sys/stat.h... yes", "checking for stdlib.h... yes", "checking for string.h... yes", "checking for memory.h... yes", "checking for strings.h... yes", "checking for inttypes.h... yes", "checking for stdint.h... yes", "checking for unistd.h... yes", "checking minix/config.h usability... no", "checking minix/config.h presence... no", "checking for minix/config.h... no", "checking whether it is safe to define __EXTENSIONS__... yes", "checking whether char is unsigned... no", "checking for uname... /usr/bin/uname", "checking for g++... g++", "checking whether we are using the GNU C++ compiler... yes", "checking whether g++ accepts -g... yes", "checking how to run the C preprocessor... gcc -E", "checking how to run the C++ preprocessor... g++ -E", "checking for a sed that does not truncate output... /usr/bin/sed", "checking for egrep... grep -E", "checking for ld used by gcc... /usr/bin/ld", "checking if the linker (/usr/bin/ld) is GNU ld... yes", "checking for gawk... gawk", "checking for a BSD-compatible install... /usr/bin/install -c", "checking whether ln -s works... yes", "checking for ranlib... ranlib", "checking for GNU make... make", "checking for egrep... (cached) /usr/bin/grep -E", "checking for strip... strip", "checking for ar... ar", "checking for bison... /usr/bin/bison", "checking for cmp... /usr/bin/cmp", "checking for cat... /usr/bin/cat", "checking for cut... /usr/bin/cut", "checking for flex... /usr/bin/flex", "checking for grep... (cached) /usr/bin/grep", "checking for python2.7... no", "checking for python2... no", "checking for python... no", "checking for python3... /usr/bin/python3", "checking for find... /usr/bin/find", "checking for basename... /usr/bin/basename", "checking for dirname... /usr/bin/dirname", "checking for sh... /bin/bash", "checking for ln... /usr/bin/ln", "checking for doxygen... /usr/bin/doxygen", "checking for dot... /usr/bin/dot", "checking for wget... /usr/bin/wget", "checking for curl... /usr/bin/curl", "checking for xmllint... :", "checking for xmlstarlet... /usr/bin/xmlstarlet", "checking for bash... /bin/bash", "checking for git... /usr/bin/git", "checking for alembic... :", "checking for bzip2... /usr/bin/bzip2", "checking for tar... /usr/bin/tar", "checking for patch... /usr/bin/patch", "checking for sed... (cached) /usr/bin/sed", "checking for nm... /usr/bin/nm", "checking for realpath... /usr/bin/realpath", "checking for ldconfig... /usr/sbin/ldconfig", "checking for sha1sum... /usr/bin/sha1sum", "checking for openssl... /usr/bin/openssl", "checking for pkg-config... /usr/bin/pkg-config", "checking pkg-config is at least version 0.9.0... yes", "checking for bison that supports parse-param... /usr/bin/bison", "checking for soxmix... no", "checking for md5... no", "checking for md5sum... md5sum", "checking for a sed that does not truncate output... (cached) /usr/bin/sed", "checking whether gcc is Clang... no", "checking whether pthreads work with -pthread... yes", "checking for joinable pthread attribute... PTHREAD_CREATE_JOINABLE", "checking whether more special flags are required for pthreads... no", "checking for PTHREAD_PRIO_INHERIT... yes", "checking for RAII support... checking for gcc -fnested-functions... no", "checking for clang strsep/strcmp optimization... no", "configure: checking OPENSSL with pkg-config", "configure: checking whether system openssl > 1.1.0", "checking for OPENSSL... yes", "checking for embedded jansson (may have to download)... configuring", "[jansson]  Downloading https://raw.githubusercontent.com/asterisk/third-party/master/jansson/2.14/jansson-2.14.tar.bz2 to /tmp/jansson-2.14.tar.bz2", "[jansson]  Retrying download", "[jansson]  Downloading https://raw.githubusercontent.com/asterisk/third-party/master/jansson/2.14/jansson-2.14.tar.bz2 to /tmp/jansson-2.14.tar.bz2", "failed", "configure: Unable to configure /opt/iiab/asterisk/third-party/jansson"]}
2023-03-24 16:51:44,233 p=4471 u=root n=ansible | TASK [pbx : SEE ERROR ABOVE (skip_role_on_error: False)] ***********************
2023-03-24 16:51:44,281 p=4471 u=root n=ansible | fatal: [127.0.0.1]: FAILED! => {"changed": false, "msg": ""}
2023-03-24 16:51:44,284 p=4471 u=root n=ansible | PLAY RECAP *********************************************************************
2023-03-24 16:51:44,285 p=4471 u=root n=ansible | 127.0.0.1                  : ok=267  changed=144  unreachable=0    failed=1    skipped=82   rescued=1    ignored=2

**Comment by holta** [comment]
Good news the above jansson-2.14 error was a transient download/mirroring issue.

(Hopefully these things don't happen too often...)

**Comment by holta** [comment]
@EMG70 the Asterisk 20.2.0 + FreePBX 16.0.39 install worked well for me in the end (after I reran `sudo iiab` to deal with jansson's downloading glitch!)

So I'll go ahead and merge this PR (making Asterisk 20 the default) into IIAB's mainline branch.

FYI I didn't do very thorough testing but everything worked when I registered a username/password/email address at http://box/freepbx and also when I confirmed the basics at the command-line here:

```
root@box:~# fwconsole ma list
No repos specified, using: [standard] from last GUI settings

+------------------+-----------+---------+---------+-----------+
| Module           | Version   | Status  | License | Signature |
+------------------+-----------+---------+---------+-----------+
| backup           | 16.0.62.7 | Enabled | GPLv3+  | Sangoma   |
| builtin          |           | Enabled |         | Unsigned  |
| callrecording    | 16.0.19   | Enabled | AGPLv3+ | Sangoma   |
| cdr              | 16.0.30   | Enabled | GPLv3+  | Sangoma   |
| conferences      | 16.0.9    | Enabled | GPLv3+  | Sangoma   |
| core             | 16.0.68.9 | Enabled | GPLv3+  | Sangoma   |
| customappsreg    | 16.0.5    | Enabled | GPLv3+  | Sangoma   |
| dashboard        | 16.0.16   | Enabled | AGPLv3+ | Sangoma   |
| featurecodeadmin | 16.0.11   | Enabled | GPLv3+  | Sangoma   |
| filestore        | 16.0.15   | Enabled | AGPLv3  | Sangoma   |
| framework        | 16.0.39   | Enabled | GPLv2+  | Sangoma   |
| infoservices     | 16.0.2    | Enabled | GPLv2+  | Sangoma   |
| logfiles         | 16.0.7    | Enabled | GPLv3+  | Sangoma   |
| music            | 16.0.2    | Enabled | GPLv3+  | Sangoma   |
| pm2              | 16.0.8    | Enabled | AGPLv3+ | Sangoma   |
| recordings       | 16.0.14   | Enabled | GPLv3+  | Sangoma   |
| sipsettings      | 16.0.26   | Enabled | AGPLv3+ | Sangoma   |
| soundlang        | 16.0.9    | Enabled | GPLv3+  | Sangoma   |
| voicemail        | 16.0.48   | Enabled | GPLv3+  | Sangoma   |
+------------------+-----------+---------+---------+-----------+
```

```
root@box:~# fwconsole ma showupgrades
No repos specified, using: [standard] from last GUI settings

Up to date.
```

**Comment by EMG70** [comment]
I can also confirm Asterisk 20 is now loading OK .
Asterisk 20.2.0, Copyright (C) 1999 - 2022, Sangoma Technologies Corporation and others.
Created by Mark Spencer <[markster@digium.com](mailto:markster@digium.com)>
Asterisk comes with ABSOLUTELY NO WARRANTY; type 'core show warranty' for details.
This is free software, with components licensed under the GNU General Public
License version 2 and other licenses; you are welcome to redistribute it under
certain conditions. Type 'core show license' for details.
=========================================================================
Running as user 'asterisk'
Running under group 'asterisk'
Connected to Asterisk 20.2.0 currently running on box (pid = 8073)

**Pull request merged**
