### PR TITLE
Using Ansible file module to fix warnings

### PR DESCRIPTION
**Pull request by arky**
Using Ansible file modules instead of 'chmod' to recursively change iiab_base directory permissions. Fixes warning in #324

### CODE REVIEW

**Comment by tim-moody** [comment]
the items that produce these warnings are not there by accident. you must verify that the alternate syntax does not cause other problems, for example performance degredation.

**Comment by holta** [comment]
@arky & @tim-moody can we resolve this one way or another Monday?

Thanks!

(And of course...if this should be merged plz confirm which OS's it has been smoke-tested on.)

**Comment by holta** [comment]
@arky has this been smoke-tested?

On which OS if poss, Thanks!

**Comment by holta** [comment]
@jvonau smoke-tested & needs to look at resulting permissions.

Post Jenkins URL if poss, so we can merge soon?

**Comment by holta** [comment]
From @jvonau: http://jenkins:8080/job/IIAB-debian-jvonau/56/consoleFull on Hadron confirms smoke test.

Can someone verify that the equivalent of "chown -R root:root {{ iiab_base }}" is in fact working?

**Comment by jvonau** [comment]
I'm wondering why this change would be in kiwix_install.yml?
http://jenkins:8080/job/Mem-change-test/63 results in:
> root@ubuntu-xenial:/home/iiab-admin# ls -la /opt/
total 32
drwxr-xr-x  8 root     root     4096 Oct 25 16:59 .
drwxr-xr-x 25 root     root     4096 Oct 25 16:28 ..
drwxr-xr-x  2 root     root     4096 Oct 25 16:59 admin
lrwxrwxrwx  1 www-data www-data   12 Oct 25 16:43 elgg -> ./elgg-2.3.4
drwxr-xr-x  6 www-data www-data 4096 Oct 25 16:43 elgg-2.3.4
drwxr-xr-x 11 root     root     4096 Oct 25 16:53 iiab
drwxr-xr-x 15 www-data www-data 4096 Oct 25 16:46 nextcloud
lrwxrwxrwx  1 www-data root       32 Oct 25 16:58 phpmyadmin -> phpMyAdmin-4.2.7.1-all-languages
drwxr-xr-x  9 root     root     4096 Oct 25 16:58 phpMyAdmin-4.2.7.1-all-languages
drwxr-xr-x  9 root     root     4096 Oct 25 16:25 VBoxGuestAdditions-5.1.28

> root@ubuntu-xenial:/home/iiab-admin# ls -la /opt/iiab
total 44
drwxr-xr-x 11 root root 4096 Oct 25 16:53 .
drwxr-xr-x  8 root root 4096 Oct 25 16:59 ..
drwxr-xr-x  2 root root 4096 Oct 25 16:58 downloads
drwxr-xr-x  8 root root 4096 Oct 25 16:27 iiab
drwxr-xr-x  7 root root 4096 Oct 25 16:59 iiab-admin-console
drwxr-xr-x  7 root root 4096 Oct 25 16:26 iiab-factory
drwxr-xr-x  8 root root 4096 Oct 25 16:26 iiab-menu
drwxr-xr-x  3 root root 4096 Oct 25 16:53 kiwix
drwxr-xr-x 49 root root 4096 Oct 25 16:49 moodle
drwxr-xr-x  2 root root 4096 Oct 25 16:51 pip-packages
drwxr-xr-x  2 root root 4096 Oct 25 16:28 yum-packages

**Comment by holta** [comment]
@jvonau great point: [roles/kiwix/tasks/kiwix_install.yml](https://github.com/iiab/iiab/blob/master/roles/kiwix/tasks/kiwix_install.yml#L73-L75) really shouldn't be changing ownership/permissions on everybody else's code in /opt/iiab :/

**Comment by jvonau** [comment]
@holta can you resolve the conflicts and push?

**Comment by holta** [comment]
@georgejhunt asks that cause & effect be tested prior to merging, given serious problems he's faced with Ansible non-shell approach (@arky can you help?)

I'm not too concerned about performance degradation in this case as /opt/iiab/kiwix contains very few items (in this case certainly!)

**Pull request merged**
