### PR TITLE
scripts/iiab-root-login: Set + Enable sftp password, for FileZilla uploads of local/community content to IIAB

### PR DESCRIPTION
**Pull request by holta**
New CLI tool to enable (and set!) root login password for ssh and sftp.

To help everyday IIAB implementers upload content with FileZilla:
https://wiki.iiab.io/go/FAQ#How_do_I_add_my_own_content%3F

AT YOUR OWN RISK.  If this absolutely must be run non-interactively, use:
`sudo iiab-root-login <PASSWORD>`

Tested on Ubuntu 24.10

### CODE REVIEW

**Comment by holta** [comment]
@EMG70 please retest in coming days if you have time?

Many thanks!!

**Comment by holta** [comment]
@avni if you have time to test the new overhauled/simplified FileZilla routine (https://wiki.iiab.io/go/FAQ#How_do_I_add_my_own_content%3F) on macOS in coming days, Many Thanks! 💯

**Comment by tim-moody** [comment]
What is the recovery method if root password is lost, for example if the user mistyped the password when changing it?

I am still of the opinion that using sftp with PKI is a safer option.

I'm wondering if adm cons should allow you to generate keys.

**Comment by holta** [comment]
> What is the recovery method if root password is lost, for example if the user mistyped the password when changing it?

User (implementer) can run `sudo iiab-root-login` again.

As necessary.

> sftp with PKI is a safer option

Yes, it can be, if UX doesn't overwhelm newbie user / implementer:

- Newbie users / implementers all seem to want "dead simple" instructions to upload to IIAB very quickly.

- Helping them understand deeper PKI might worst case get hairy, awful fast (:

> I'm wondering if adm cons should allow you to generate keys.

Definitely conceivable:

- 90% of the challenge (possibly 99% of the challenge?) is likely to be mentoring newbies (very sincere newcomers) who often don't quite understand ssh, sftp and Diffie–Hellman key management — and painfully struggle to understand the CLI as well as the `nano` text editor in many cases. 🙀

- Conversely people who understand PKI with ssh and sftp, will often already have done this themselves.

- The balancing act would be to see if a very clean "zero confusion" UX is achievable, helping the demographic of overwhelmed-but-aspiring-newbies(TM) to strengthen their ssh and sftp skills (e.g. supplemented by PKI) atop the current FileZilla with root password solution (https://wiki.iiab.io/go/FAQ#How_do_I_add_my_own_content%3F), and if this can be made into a "painless doctor's visit" that would indeed definitely be a public service. 😇

**Comment by holta** [comment]
CLARIF:

- Instructions for Android and iPhone were added to https://wiki.iiab.io/go/FAQ#How_do_I_add_my_own_content%3F
- To help implementers (and exceptional teachers, etc) upload community content from phones/devices where FileZilla does not run!

**Comment by avni** [comment]
>@avni if you have time to test the new overhauled/simplified FileZilla routine (https://wiki.iiab.io/go/FAQ#How_do_I_add_my_own_content%3F) on macOS in coming days, Many Thanks! 💯

Successfully works! Instructions were easy to follow. TY! 🎉 

Screenshot 2024-08-13 at 1 21 27 AM

**Comment by avni** [comment]
Successful from mobile using FTPManager! Thanks @holta for all of the networking help this evening! 🥇

**Comment by holta** [comment]
Future Question:

Local communities MIGHT prefer https://Piwigo.org instead of Nextcloud (& raw NGINX folders )
 to host their ever-evolving photo / video "albums" ?!

(While some will of course insist on a UI closer to Google Photos / Apple's iCloud Photos — e.g. https://immich.app talks the self-hosting talk, but appears to suffer from cargo cult fanboyism ?)

**Comment by holta** [comment]
@avni found this comparison table:

"Free and OpenSource Photo Libraries"
https://meichthys.github.io/foss_photo_libraries/

Nextcloud Photos and Nextcloud Memories are each highly rated — might be worth investigating?

**Comment by avni** [comment]
+1 on looking at NextCloud Memories, based on the comparison table and online reviews found. That’s on my list next. 

For Piwigo, I found this [Reddit post](https://www.reddit.com/r/selfhosted/comments/13vu5i6/piwigo_selfhosted_vs_others/) helpful; it’s also where I found the link to the comparison table. From playing around with a trial Piwigo account, it was relatively easy to use though the UI is a bit dated and some of the navigation was not intuitive - e.g., traversing from a photo view to an album view and back. It blends the view and admin parts of photo management software in a non-intuitive way imo. It didn’t blow me out of the water so will look at other options like NextCloud Memories mentioned above.

**Pull request merged**
