### PR TITLE
gui_desired_network_role is defined in systemd.j2 [solves two Debian 11 issues?]

### PR DESCRIPTION
**Pull request by jvonau**

### CODE REVIEW

**Comment by holta** [comment]
Thanks @deldesir and @jvonau for the very quick fix and/or enhancement!

Is a fresh install or any other test useful to confirm this?

Ref: PR #2582

**Comment by holta** [comment]
@jvonau summarizes:

> when available deb-11 can be continued to confirm [this correction/direction], The basic reason the vm worked ok is there was only one interface present, so br0 was suppressed from being created and the faulty template skipped. Fast forward from the deb-8/u-16 base for that snippet of code to today to where if you have a wifi device you automatically have 2 devices on wifi gateway and ap0 under br0, the fix applied is the same code from rpi.j2, just never figured ifupdown [wouldn't and] didn't die [in recent years]

**Comment by holta** [comment]
@deldesir to be 100% sure (there are several ppl who ask for a live/full smoke-test prior to merging all PR's) can you run the following on your Debian 11 laptop?

```
cd /opt/iiab/iiab/roles/network/templates/network/
sudo su -
mv systemd.j2 systemd.j2.OLD
wget https://raw.githubusercontent.com/jvonau/iiab/deb_11/roles/network/templates/network/systemd.j2
cd /opt/iiab/iiab
./iiab-network
```

Thanks so much!

**Comment by holta** [comment]
@deldesir has no electricity right now but will confirm tomorrow.

**Comment by jvonau** [comment]
> @jvonau summarizes:
> 
> > when available deb-11 can be continued to confirm [this correction/direction], The basic reason the vm worked ok is there was only one interface present, so br0 was suppressed from being created and the faulty template skipped. Fast forward from the deb-8/u-16 base for that snippet of code to today to where if you have a wifi device you automatically have 2 devices on wifi gateway and ap0 under br0, the fix applied is the same code from rpi.j2, just never figured ifupdown [wouldn't and] didn't die [in recent years]

Don't ever paraphrase my words, quote my words in full as written bad spelling, grammar and all or do not quote me at all.
>no, waiting on you.. just push it and lets test master for no ill effects, there won't be and when available deb-11 can be continued to confirm that is the need correction, and it is, The basic reason the vm worked ok is there was only one interface present, so br0 was suppressed from being created and the faulty template skipped. Fast forward from the deb-8/u-16 base for that snippet of code to today to where if you have a wifi device you automatically have 2 devices on wifi gateway and ap0 under br0, the fix applied is the same code from rpi.j2, just never figured ifupdown didn't die with horrible death yet (I'm shocked) so I wasn't in a rush to fix anything given the prior lack of useful feedback when asked for some further information.

**Comment by jvonau** [comment]
> @deldesir to be 100% sure (there are several ppl who ask for a live/full smoke-test prior to merging all PR's) can you run the following on your Debian 11 laptop?

Who is that? I never hear or see anything more that 'smoketested' without any actual data to backup that claim before merges.   

> cd /opt/iiab/iiab/roles/network/templates/network/
> sudo su -
> mv systemd.j2 systemd.j2.OLD
> wget https://raw.githubusercontent.com/jvonau/iiab/deb_11/roles/network/templates/network/systemd.j2
> cd /opt/iiab/iiab
> ./iiab-network
> ```
> 
> Thanks so much!

Please stop giving out bad advice. You failed to take into account STAGE=0 is present in iiab.env, iiab-network will not allow itself to run in that situation. Now iiab-install must be completed again, just use 'iiab' to continue with the install once either a hand fix is applied to the file as above or this PR is merged. Should you hand fix the file Adam should provide the steps to return the git repo to a state where a git pull can be performed without error. How is it possible to have a completed install with iiab_state.yml populated and the stage be '0' I ask. More bad instructions or old habits using iiab-install --reinstall I would suggest.

**Comment by holta** [comment]
Thank you to @deldesir who successfully tested this PR after finding electricity in Haiti today.

**Comment by holta** [comment]
Re-opening this to monitor general testing coverage of Debian 10/11 over the coming days.

Alongside #2585 for Ubuntu 20.10 which is also acting as an incredibly useful canary-in-the-coal-mine.

**Comment by holta** [comment]
Oops wrong ticket, I meant #2582!

**Pull request merged**
