### PR TITLE
Create lokole user

### PR DESCRIPTION
**Pull request by jvonau**
needs clean install test, not sure if lokole_uuid.results in the template will fly or not. If not then set_fact will be needed as an extra step 

next to do - create real lokole system user

### CODE REVIEW

**Comment by holta** [comment]
@deldesir can you do a clean/fresh install test of this PR #2782 today if you have time?

cc: @adamsclafani

**Comment by deldesir** [comment]
I'll do it right now.

**Comment by holta** [comment]
@deldesir tested this PR successfully on 3 VM's:

- a pre-release of Debian 11 Bullseye: http://sprunge.us/ay74Q4?en
- Ubuntu Server 21.04: http://sprunge.us/k9cq8p?en
- Ubuntu Desktop 21.04: http://sprunge.us/4lFXQH?en

However on a 4th VM running Linux Mint 20, Lokole did not install with this PR: (possibly this is a longstanding issue?)

- #2783 "Lokole failed to install on Linux Mint 20: apt package 'python3-dev' repeatedly fails to install"

**Comment by jvonau** [comment]
The registration credentials expect to be written to setting.env, so lets keep the vars in one place, celery service should now run as lokole user.

**Comment by jvonau** [comment]
tested via runrole, should be good for wider testing

**Comment by jvonau** [comment]
This should be set the stage to test live registration, recording what is returned by that process. Once those values are know hand addition to webapp_secrets.sh should have a working relay.
 
Future work webapp.sh should read settings.env via webapp_secrets.sh, but for another day.

**Pull request merged**
