### PR TITLE
Lokole nginx only

### PR DESCRIPTION
**Pull request by jvonau**
### Fixes bug:
#2507 #2762
### Description of changes proposed in this pull request:
drop apache
### Smoke-tested on which OS or OS's:
hand tested Ubuntu 20.10
### Mention a team member @username e.g. to help with code review:
@holta

### CODE REVIEW

**Comment by holta** [comment]
Awesome.

@adamsclafani & @deldesir please review if you can?!

**Comment by jvonau** [comment]
Please don't be an impediment to progress, do a quick clean install test when it passes the smoke testing merge quickly so Nzola and others don't have to do a test PR dance. Going forward just un# lokole_sim_type= in local_vars before the (re)install then proceed straight admin login and test registration from there.

**Comment by jvonau** [comment]
implemented https://github.com/iiab/iiab/pull/2507#issuecomment-691478352 with elements of #2773

**Comment by adamsclafani** [comment]
The config file matches the nginx config on the lokole install script so I have no complaints here.

**Comment by holta** [comment]
> @adamsclafani & @deldesir please review if you can?!

1. _Asking people to suddenly change their Friday night plans is highly inappropriate._

   _And yet that's what happened._

   _Apologies._

2. Be that as it may, thank you to @adamsclafani who visually reviewed this PR overnight, and @deldesir who tested it overnight with a clean install on Debian 10, using:

   ```
   curl d.iiab.io/install.txt | sudo bash -s 2776
   ```

   Then @deldesir logged into http://box/lokole and verified that `sue@none.lokole.ca` could successfully email `bob@none.lokole.ca` — the basics (offline email) anyway.

   However when @deldesir used Lokole to email an attachment, the screenshot (.png attachment) was unreadable by the person receiving the email, as the final result was somehow dramatically shrunk.

   @nzola are you aware of attachment frustrations like this?  Overly shrunk (unreadable) screenshot attachment is pasted in here:

   Screenshot from 2021-05-01 23-44-33

3. Please see the "Using It" section of roles/lokole/README.rst which is a first stab at important -> evolving documentation:

    https://github.com/iiab/iiab/blob/master/roles/lokole/README.rst#using-it

Ref: #2767

**Comment by holta** [comment]
> However when @deldesir used Lokole to email an attachment, the screenshot (.png attachment) was unreadable by the person receiving the email, as the final result was somehow dramatically shrunk.
>
> @nzola are you aware of attachment frustrations like this?  Overly shrunk (unreadable) screenshot attachment is pasted in here:
>     Screenshot from 2021-05-01 23-44-33

@nzola says this is a Known Issue.  One possible workaround is to paste screenshots into .docx or .odf (Open Document Format) before sending the attachment.

Not everyone has Microsoft Office and/or LibreOffice however :/

So @deldesir / others might want to explore if there's a better way?

Keeping in mind that Lokole is competing for attention with things like WhatsApp for relevance, so it might also be a matter of modernizing Lokole's scaling down of screenshots/photos, to make them substantially more readable for the new decade (maybe aiming for 100KB instead of 10KB?!)

**Comment by jvonau** [comment]
> Keeping in mind that Lokole is competing for attention with things like WhatsApp for relevance, so it might also be a matter of modernizing Lokole's scaling down of screenshots/photos, to make them substantially more readable for the new decade (maybe aiming for 100KB instead of 10KB?!)

The intent is to keep upstream internet data usage as low as possible because cellular bandwidth costs $$ in the intended deployment location.

**Pull request merged**
