### PR TITLE
Lok super

### PR DESCRIPTION
**Pull request by jvonau**
### Fixes bug:
replaces #2790 #2792 

### Description of changes proposed in this pull request:
switch over to supervisor
### Smoke-tested on which OS or OS's:
ubuntu-21-04
@adamsclafani

### CODE REVIEW

**Comment by jvonau** [comment]
@adamsclafani needed changes upstream https://github.com/iiab/iiab/pull/2792#issuecomment-846630427

**Comment by jvonau** [comment]
https://github.com/iiab/iiab/pull/2792#issuecomment-845540012

**Comment by jvonau** [comment]
@holta needs clean install testing

**Comment by holta** [comment]
FYI @nzola began testing this PR about 4-5 hours ago.

If there's a need to merge it, please LMK.

**Comment by nzola** [comment]
There is no option to register a sub domain, olny users and it has been working for me.
How do I register a subdomain and get it to show up on Lokole Status Board. Do I have to do it on Terminal?Right now the default client or subdomain is NONE. How do I change it for different location names? Right now I have created 2 local users under the subdomain NONE : nzola@none.lokole.ca and swasi@none.lokole.ca
They are exchanging emails without any problems including the default admin@none.lokole.ca

**Comment by jvonau** [comment]
There is no 'click here to register' when you are in http://192.168.0.12/lokole/admin/settings to bring up registration use http://192.168.0.12/lokole/admin/register as the url

**Comment by nzola** [comment]
image

**Comment by nzola** [comment]
image

**Comment by nzola** [comment]
Cool!

**Comment by jvonau** [comment]
@adamsclafani [patch](https://raw.githubusercontent.com/iiab/iiab/f63eb2349fcd0381f6017da82031e08c336deb4c/lokole/jv.patch) location `wget or curl` to the root of the git repo, then apply with `patch -p1 -i jv.patch`, `git diff` to see the changes before committing

**Comment by nzola** [comment]
This is the output I get when I try to register a client
image

**Comment by adamsclafani** [comment]
@nzola No worries. Jerry did lots of work on debugging. Changes are coming soon to hopefully fix this. I should have a PR up in the next couple of days

**Comment by nzola** [comment]
@adamsclafani Thanks Adam

**Comment by holta** [comment]
Just FYI this temporary PR #2800 will be closed after @adamsclafani's PR ascoderu/lokole#548 is merged (to create Lokole 0.6.16 !)

**Pull request closed without merging**
