### PR TITLE
Lint & Clarify roles/remoteit [remote.it for remote support]

### PR DESCRIPTION
**Pull request by holta**
Building on @georgejhunt's PR #3003.

SEE ALSO: http://FAQ.IIAB.IO -> "31 How can I remotely manage my Internet-in-a-Box?"

### CODE REVIEW

**Comment by holta** [comment]
FYI @deldesir @georgejhunt:

This PR is currently being tested on 182-rpi4-lite-unittest-PR3005 = 10.8.0.30

**Comment by holta** [comment]
> This PR is currently being tested on 182-rpi4-lite-unittest-PR3005 = 10.8.0.30

Success!

Including following all 5 steps in the instructions here:
https://github.com/iiab/iiab/blob/master/roles/remoteit/README.md

**Comment by holta** [comment]
Conclusion & Next Steps:

1. Raspberry Pi OS works &mdash; but more testing and some enhancement re-work is needed &mdash; to beef up these 2 lines which currently undoubtedly cause IIAB installs to fail on Ubuntu & Debian etc: https://github.com/iiab/iiab/blob/master/roles/remoteit/defaults/main.yml#L10-L11
2. I've begun overhauling https://wiki.iiab.io/go/FAQ -> "31 How can I remotely manage my Internet-in-a-Box?" **to make sure this is actually used...**

**Comment by jvonau** [comment]
```
TASK [remoteit : Download https://downloads.remote.it/remoteit/v4.13.5/remoteit-4.13.5.armhf.rpi.deb device package to /opt/iiab/downloads] ****************************
changed: [127.0.0.1]

TASK [remoteit : Uninstall the device package remoteit-4.13.5.armhf.rpi.deb] *******************************************************************************************
ok: [127.0.0.1]

TASK [remoteit : Install device package /opt/iiab/downloads/remoteit-4.13.5.armhf.rpi.deb] *****************************************************************************
fatal: [127.0.0.1]: FAILED! => {"changed": false, "msg": "Unable to install package: E:Could not open file /opt/iiab/downloads/remoteit-4.13.5.armhf.rpi.deb - open (20: Not a directory)"}

PLAY RECAP *************************************************************************************************************************************************************
127.0.0.1                  : ok=51   changed=17   unreachable=0    failed=1    skipped=4    rescued=0    ignored=0   
```
RaspiOS updated to bullseye

**Comment by jvonau** [comment]
As merged everything other than the arm32/armhf RaspiOS platform is broken, you are not expecting an **_armhf.rpi.deb_** package to install on an **_amd64_** machine are you?

**Pull request merged**
