### PR TITLE
Explain networking packages in 1-prep and 2-common -- and experimentally deprecate exfat-fuse, exfat-utils, ntfs-3g -- mandating 5.4+ kernels

### PR DESCRIPTION
**Pull request by holta**
Thanks to @jvonau's very helpful contextualizing at https://github.com/iiab/iiab/pull/2876#issuecomment-887668201

### CODE REVIEW

**Comment by jvonau** [comment]
avahi-daemon is used with https://github.com/iiab/iiab/blob/master/roles/network/tasks/avahi.yml

**Comment by holta** [comment]
> avahi-daemon is used with https://github.com/iiab/iiab/blob/master/roles/network/tasks/avahi.yml

Ok.  Who uses the above and is it important?  I saw the above `avahi.html` section run as I smoke-tested this PR (fresh install of IIAB including this PR #2882) onto RPi 4 &mdash; which somehow completed without complaints:

> 183-rpi4-lite-MIN-2882 = 10.8.0.62

(Feel free to log in if it helps!)

**Comment by holta** [comment]
FYI this PR experimentally comments out the installation of these 3 packages:

- exfat-fuse
- exfat-util
- ntfs-3g

As they _should_ no longer be necessary with Linux 5.4+ kernels &mdash; Raspberry Pi OS has been using 5.10 for months now &mdash; and Debian 10 for PC is essentially no longer supported as the transition to Debian 11 is now underway.  (Last but not least, Ubuntu 20.04 and Linux Mint 20 have been using 5.4 kernels for almost a year and a half now.)

But see also this symlink warning &mdash; affecting Arch Linux, Slackware, etc:
https://superuser.com/questions/1050544/mount-with-kernel-ntfs-and-not-ntfs-3g

**Comment by holta** [comment]
Additional post-merge smoke-testing is ongoing, with another fresh install of IIAB onto a different RPi 4 here:

181-rpi4-lite-MIN-0727 = 10.8.0.38

**Pull request merged**
