### PR TITLE
Lokole sync, building on PRs #2507 & #2513

### PR DESCRIPTION
**Pull request by holta**
@adamsclafani can you please review/tweak and if this is what you want, and if so run a smoke-test (any vanilla installation!) so we can merge with confidence this baseline works?

Thanks all!

cc: @c-w @jvonau

Builds on PRs #2507 & #2513

### CODE REVIEW

**Comment by jvonau** [comment]
Please use better descriptions for commits, update, clarify, cleaner are not descriptive enough to know 'what' was changed in the commit. 
f0a1ca2b0ab06dcf60cb8f4f9f4239a09a47ebea any reason why the 3 services were not combined with the above stanza?
7e9c31d5db223b50550362f0df137e63a584812b was in reverse starting order, any real reason why the order was changed?
fbcbc82050438ee217a20f464dd5c2de8f1b3644 & 41a91beccd2ef1305845862e1af05d8473779754 any reason this was not mentioned in the original PR when this code was in a script?

**Comment by holta** [comment]
> f0a1ca2 any reason why the 3 services were not combined with the above stanza?

To avoid running daemon_reload 4 times.

> 7e9c31d was in reverse starting order

Is reverse starting order truly necessary?  (@adamsclafani please also weigh in if you can!)

**Comment by jvonau** [comment]
> > [f0a1ca2](https://github.com/iiab/iiab/commit/f0a1ca2b0ab06dcf60cb8f4f9f4239a09a47ebea) any reason why the 3 services were not combined with the above stanza?
> 
> To avoid running daemon_reload 4 times.
> 

Fair enough, could split the daemon_reload to its own stanza to be done before the multi-restart of the 4 services, excluding daemon_reload there.
> > [7e9c31d](https://github.com/iiab/iiab/commit/7e9c31d5db223b50550362f0df137e63a584812b) was in reverse starting order
> 
> Is reverse starting order truly necessary? (@adamsclafani please also weigh in if you can!)

Only makes sense 1 2 3 4 operational app 4 3 2 1 flushed to disk.

**Comment by adamsclafani** [comment]
Everything looks good to me!

**Comment by holta** [comment]
@c-w and @adamsclafani should Lokole's sync documentation be revised at https://github.com/iiab/iiab/tree/master/roles/lokole#nightly-internet-email-sync-not-easy with a follow-up PR?

In any case I'm now merging this, as the install smoke-test and very basic functionality tests succeeded on the latest [IIAB 7.2 pre-release](http://download.iiab.io) on the very standard 32-bit Raspberry Pi OS with desktop, running on an RPi 4 with 2GB RAM:

```
sudo nano /etc/iiab/local_vars.yml    # Set 'lokole_install: True' and 'lokole_enabled: True'
cd /opt/iiab/iiab
sudo ./runrole lokole
```

(FYI it took almost 7 minutes to install Lokole, but ah well that may well be normal, as half of that time was the pip install from https://pypi.org/project/opwen-email-client/ which populated `/library/lokole/venv` with 132 MB.)

**Comment by jvonau** [comment]
Waiting on a reply to:
> fbcbc82 & 41a91be any reason this was not mentioned in the original PR when this code was in a script?

**Comment by holta** [comment]
> Waiting on a reply to:
> 
> > [fbcbc82](https://github.com/iiab/iiab/commit/fbcbc82050438ee217a20f464dd5c2de8f1b3644) & [41a91be](https://github.com/iiab/iiab/commit/41a91beccd2ef1305845862e1af05d8473779754) any reason this was not mentioned in the original PR when this code was in a script?

No reason.  @adamsclafani is new to Ansible and if I'd seen it I would have mentioned it, to help him learn the ropes.

**Comment by jvonau** [comment]
I see, for 3 days you did not notice what could of been incorporated into the final PR before I branched the PR. I saw and knew but I left those entries as is to illustrate that separate files are not required, the call can be one line contained in the unit file to the original author. If you are going to play PR cop apply your law equally, at first sight, but justice is currently being blinded by the limelight of promoting one's self interests.

**Pull request merged**
