### PR TITLE
pin virtualenv to version in U22.04

### PR DESCRIPTION
**Pull request by jvonau**
### Fixes bug:
#3573 
### Description of changes proposed in this pull request:
use version of virtualenv from U22.04
### Smoke-tested on which OS or OS's:
U23-04 VM

### CODE REVIEW

**Comment by jvonau** [comment]
replaces #3582

**Comment by holta** [comment]
FYI this approach does not work.  For the same reasons encountered when testing the earlier .deb approach (20.19.0, borrowed from Ubuntu 23.04).  After running `scripts/install_python2.sh` on Ubuntu 23.10, the result is:

```
root@u2310:~# which virtualenv
/usr/bin/virtualenv
root@u2310:~# virtualenv --version
virtualenv 20.23.0+ds from /usr/lib/python3/dist-packages/virtualenv/__init__.py
```

FWIW even if this approach could be made to work, it would carry risks running a version of virtualenv ([20.13.0](https://virtualenv.pypa.io/en/latest/changelog.html#v20-3-0-2021-01-10)) packaged for a different OS, from 16 months earlier than 20.21.1

**Comment by holta** [comment]
Context:

/var/log/apt/history.log (below) shows how virtualenv 20.13.0 drags in python3-virtualenv 20.23.0 (in bold)

> Start-Date: 2023-05-20  10:35:23
Commandline: apt -y install virtualenv=20.13.0+ds-2
Install: libalgorithm-merge-perl:amd64 (0.08-5, automatic), python3-setuptools-whl:amd64 (66.1.1-1, automatic), g++-12:amd64 (12.3.0-1ubuntu1, automatic), virtualenv:amd64 (20.13.0+ds-2), gcc-12:amd64 (12.3.0-1ubuntu1, automatic), build-essential:amd64 (12.9ubuntu3, automatic), cpp:amd64 (4:12.2.0-3ubuntu1, automatic), libpython3-dev:amd64 (3.11.2-1, automatic), g++:amd64 (4:12.2.0-3ubuntu1, automatic), gcc:amd64 (4:12.2.0-3ubuntu1, automatic), libalgorithm-diff-perl:amd64 (1.201-1, automatic), libfakeroot:amd64 (1.31-1.2, automatic), **python3-virtualenv:amd64 (20.23.0+ds-1, automatic),** python3-pip-whl:amd64 (23.1.2+dfsg-1, automatic), bzip2:amd64 (1.0.8-5build1, automatic), python3-wheel-whl:amd64 (0.40.0-2, automatic), libcc1-0:amd64 (13.1.0-2ubuntu2, automatic), zlib1g-dev:amd64 (1:1.2.13.dfsg-1ubuntu4, automatic), libfile-fcntllock-perl:amd64 (0.22-4build1, automatic), python3-platformdirs:amd64 (3.5.0-1, automatic), dpkg-dev:amd64 (1.21.22ubuntu1, automatic), make:amd64 (4.3-4.1build1, automatic), lto-disabled-list:amd64 (41, automatic), python3-dev:amd64 (3.11.2-1, automatic), python3-distlib:amd64 (0.3.6-1, automatic), cpp-12:amd64 (12.3.0-1ubuntu1, automatic), libpython3.11-dev:amd64 (3.11.3-1, automatic), libdpkg-perl:amd64 (1.21.22ubuntu1, automatic), python3-filelock:amd64 (3.12.0-0ubuntu1, automatic), python3.11-dev:amd64 (3.11.3-1, automatic), libjs-jquery:amd64 (3.6.1+dfsg+~3.5.14-1, automatic), libexpat1-dev:amd64 (2.5.0-1, automatic), libalgorithm-diff-xs-perl:amd64 (0.04-8, automatic), libjs-sphinxdoc:amd64 (5.3.0-4, automatic), gcc-12-base:amd64 (12.3.0-1ubuntu1, automatic), javascript-common:amd64 (11+nmu1, automatic), libjs-underscore:amd64 (1.13.4~dfsg+~1.11.4-3, automatic), fakeroot:amd64 (1.31-1.2, automatic), libgcc-12-dev:amd64 (12.3.0-1ubuntu1, automatic), libstdc++-12-dev:amd64 (12.3.0-1ubuntu1, automatic)
End-Date: 2023-05-20  10:35:39

**Comment by jvonau** [comment]
> FYI this approach does not work. For the same reasons encountered when testing the earlier .deb approach (20.19.0, borrowed from Ubuntu 23.04). After running `scripts/install_python2.sh` on Ubuntu 23.10, the result is:
> 
> ```
> root@u2310:~# which virtualenv
> /usr/bin/virtualenv
> root@u2310:~# virtualenv --version
> virtualenv 20.23.0+ds from /usr/lib/python3/dist-packages/virtualenv/__init__.py
> ```
> 

`apt install python3-virtualenv=20.13.0+ds-2`, before installing virtualenv= 20.13.0+ds-2 the same version, both use the same source package.

> FWIW even if this approach could be made to work, it would carry risks running a version of virtualenv ([20.13.0](https://virtualenv.pypa.io/en/latest/changelog.html#v20-3-0-2021-01-10)) packaged for a different OS, from 16 months earlier than 20.21.1

How is that different from using pip to install an earlier version? Now carrying the risk of pip breaking other system path components with --break-system-packages. Whatever, don't care going forward.

**Comment by holta** [comment]
> `apt install python3-virtualenv=20.13.0+ds-2`, before installing virtualenv= 20.13.0+ds-2 the same version, both use the same source package.

That seemed promising so I tried it.  But it fails as follows:

```
root@box:~# cat /etc/apt/sources.list.d/python2.list
deb [trusted=yes] http://archive.ubuntu.com/ubuntu jammy main universe
deb [trusted=yes] http://archive.ubuntu.com/ubuntu jammy-updates main universe
```
```
root@box:~# apt update
[...many lines, as it completed...]
```
```
root@box:~# apt install python3-virtualenv=20.13.0+ds-2
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 python3-virtualenv : Depends: python3-platformdirs (< 3) but 3.5.0-1 is to be installed
E: Unable to correct problems, you have held broken packages.
```

So @neomatrixcode's suggestion (using pip in PR #3582) definitely appears to be the most promising for now.

**Comment by jvonau** [comment]
When you are mixing repos from different OSs the dependencies should be explicitly listed to help keep things sane as apt will always try to install the latest version. Might take longer to get a sucessful combination figured out but in the end one is not mixing package managers, apt vs pip and goes along way to promote a stable installation in the long run.

`apt install python3-platformdirs=2.5.1-1` prior to python3-virualenv and should be held also. (`apt-mark hold`)
There might be others that pop up, deal with them in the same way.

**Pull request closed without merging**
