### PR TITLE
PR #2727 w/ on-screen warnings for iiab-internet-on|off

### PR DESCRIPTION
**Pull request by holta**
WIP, refining PR #2727.

### CODE REVIEW

**Comment by holta** [comment]
Tested on RaspiOS Lite on RPi 4.

Thanks goes to @jvonau as this is just PR #2727 with a few cleanups.

**Comment by holta** [comment]
FYI this was also tested on Ubuntu Server 20.10 on RPi 4.

**Comment by holta** [comment]
> Thanks goes to @jvonau as this is just PR #2727 with a few cleanups.

Documentation is now cleaner here:

https://github.com/iiab/iiab/wiki/IIAB-Networking#firewall-iptables

**Comment by jvonau** [comment]
The author of eeefe546e7f270c1afa74fd431e3513072a3b788 fails to follow form that was started from that start of this project from a time before the author became involved with ansible. Templates that have variables within them should have.j2 appended to the name to denote the use of variables, this automatically requires the use of full dest directives to be able to change the name, ie dropping the .j2 I chose the form I did because that was consistent with all the other roles use of template where the source file have .j2 appended to denote the use of variables but j2 needs to be removed when place on the target filesystem. It's actions like this that drive myself away. 

Should mention that the change will persist through a reboot until the opposite command is run as the rule set was changed and saved.

**Comment by holta** [comment]
> Should mention that the change will persist through a reboot until the opposite command is run as the rule set was changed and saved.

Done.  That explanation is now added here:

https://github.com/iiab/iiab/wiki/IIAB-Networking#firewall-iptables

**Pull request merged**
