### PR TITLE
NM not playing nice on ubuntu-16, use older method

### PR DESCRIPTION
**Pull request by jvonau**
limit NM to ubuntu 18 as ifupdown is available on ubuntu 16

### CODE REVIEW

**Comment by holta** [comment]
This [NetworkManager] PR also re-orders boot sequence of hostapd & dhcpd for Ubuntu 16.04.

(Needs to be confirmed on Raspbian, Ubuntu 18.04 Desktop & also Server...)

**Comment by holta** [comment]
> (Needs to be confirmed on Raspbian, Ubuntu 18.04 Server & also Desktop...)

Tested on Raspbian Lite & U18 Desktop, including reboot and then "systemctl status dhcpd" and finally verifying AP/SSID is fully working (displays http://box.lan).

**Comment by holta** [comment]
Despite working earlier, `./iiab-network` no longer works on the slower of the Ubuntu 16.04 machines (192.168.0.124) after attempting `./iiab-install --reinstall`:

> TASK [network : Restart the networking service] ********************************
fatal: [127.0.0.1]: FAILED! => {"changed": false, "msg": "Unable to start service networking: Job for networking.service failed because the control process exited with error code. See \"systemctl status networking.service\" and \"journalctl -xe\" for details.\n"}

**Comment by jvonau** [comment]
Cleaned out older network info for br0 from /etc/network/interfaces, was trying to bring up br0 twice. iiab-network worked without issue.

**Comment by holta** [comment]
> Cleaned out older network info for br0 from /etc/network/interfaces, was trying to bring up br0 twice. iiab-network worked without issue.

Great.  For reference, this is how /etc/network/interfaces should appear on Ubuntu 16.04 with IIAB:

```
# This file describes the network interfaces available on your system
# and how to activate them. For more information, see interfaces(5).

source /etc/network/interfaces.d/*

# The loopback network interface
auto lo
iface lo inet loopback

# Possibly followed by something like...
auto enp3s0
iface enp3s0 inet dhcp
```

**Pull request merged**
