### PR TITLE
6-generic-apps/tasks/main.yml: AzuraCast restoration prep

### PR DESCRIPTION
**Pull request by holta**
Prep work in conjunction with:

- PR #2946

Other/ongoing prep + doc work as 10080 is likely changing to 12080:

1) https://github.com/iiab/iiab/wiki/IIAB-Networking#list-of-ports--services
   - Ports Question: https://github.com/iiab/iiab/pull/2946#pullrequestreview-1090437439
2) http://FAQ.IIAB.IO -> "9 What services (IIAB apps) are suggested during installation?"
   - That's https://wiki.iiab.io/go/FAQ#What_services_%28IIAB_apps%29_are_suggested_during_installation%3F
3) IIAB's [AzuraCast README.rst](https://github.com/iiab/iiab/tree/master/roles/azuracast#readme) is currently spartan + stale (broken link to upstream screenshots etc!)
   - It should really point towards AzuraCast's own best implementer/teacher tips etc!

Stretch Goal...if this turns out to be possible in coming weeks:

- #1770

Related:

- #1546

### CODE REVIEW

**Comment by jvonau** [comment]
stage 6 is a shitty location from a engineering stand point for the code to be run at see #2741 #3174

**Comment by holta** [comment]
Let's keep grand architectural debates entirely separate.

The focus here is on restoring AzuraCast to reliable + well-documented operation.

**Comment by jvonau** [comment]
None of those were in place before as the role was going out the door, address the wider engineering scope that you continue to ignore.

**Comment by holta** [comment]
This is not the place for grand architectural debates.

If there's an AzuraCast problem, let's address that here or  as part of PR #2946 etc.

**Comment by holta** [comment]
> If there's an AzuraCast problem, let's address that here or as part of PR #2946 etc.

For example if AzuraCast-with-Docker installation in [roles/9-local-addons](https://github.com/iiab/iiab/tree/master/roles/9-local-addons) (just as an example?) would allow for substantially more reliable installation of IIAB, let's just state that clearly, if that's indeed the case.

**Comment by holta** [comment]
~4 [docs.azuracast.com](https://docs.azuracast.com/) links are posted under:

- https://github.com/iiab/iiab/issues/1546#issuecomment-1216973645

**Comment by holta** [comment]
@jvonau @rickgurmet @m-anish please LMK where improvements to [AzuraCast's README](https://github.com/iiab/iiab/tree/master/roles/azuracast#readme) are possible &mdash; so instructions are crystal clear for all communities in all countries

Thank you!

**Pull request merged**
