### PR TITLE
[Debian 10] [Fixes #902] Generate correct os_ver for Debian 10/Buster Release 

### LINKED ISSUE #902: [Debian 10]  Ansible reports os_ver as "OS_not_supported"
### Expected behavior and actual behavior.
Installation of IIAB to start 
### Steps to reproduce the problem.
On Debian 10 

curl download.iiab.io/6.6/load-big.txt | sudo bash 

### Specifications like the version of the IIAB, operating system version, or hardware details.
Debian 10 (buster/sid)

Full logs https://paste.ubuntu.com/p/HY7DmSJJ4C/
Full ansible local vars https://paste.ubuntu.com/p/nwn3pkSVVb/

### PR DESCRIPTION
**Pull request by arky**
### Fixes Bug
Allows IIAB to install on future releases of Debian 10 / Buster Release, by correctly generating os_ver variable from VERSION_ID in /etc/*release files. 
Fixes #902 
### Description of changes proposed in this pull request.
Adds a new file in /vars/debian-10.yml 
Adds a new switch routine in scripts/local_facts.fact

### Smoke-tested in operating system.
Early preview of Debian 10 / Bester / Testing 

### Mention a team member for further information or comment using @ name
@holta

### CODE REVIEW

**Comment by arky** [comment]
At the moment, Buster is missing some of the php 7.2 packages like mcrypt. So, I guess php_version:7.1 is best bet for now.

**Comment by holta** [comment]
> At the moment, Buster is missing some of the php 7.2 packages like mcrypt. So, I guess php_version:7.1 is best bet for now.

Perhaps try adding mcrypt packages to Debian 10 "Buster" similar to PR #899 ?
(FWIW PHP 7.2 has been working in vars/ubuntu-18.yml since late 2017)

**Comment by arky** [comment]
I didn't find a php7.2-mcrypt package in buster. Perhaps it will be land
before the freeze.

https://packages.debian.org/buster/php/

Will continue to test and add support as the release is finalized.

On Jul 16, 2018 7:34 PM, "A Holt" <notifications@github.com> wrote:

At the moment, Buster is missing some of the php 7.2 packages like mcrypt.
So, I guess php_version:7.1 is best bet for now.

Perhaps try adding mcrypt packages to Debian 10 "Buster" similar to PR #899
<https://github.com/iiab/iiab/pull/899> ?
(FWIW PHP 7.2 has been working in vars/ubuntu-18.yml since late 2017)

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/iiab/iiab/pull/904#issuecomment-405232755>, or mute the
thread

**Comment by jvonau** [comment]
mcrypt have been removed from php-7.2 if I recall correctly.

**Comment by holta** [comment]
> mcrypt have been removed from php-7.2 if I recall correctly.

Right, much as how we navigated to Ubuntu 18.04's PHP 7.2 earlier this year.

I'll bet @arky you can get PHP 7.2 working on Debian 10 similarly, if you dig around here:
- https://github.com/iiab/iiab/blob/master/roles/nextcloud/tasks/main.yml#L61-L81
- PR #762's https://github.com/iiab/iiab/pull/762/files#diff-a45913a4ffde64b946e0db1c03591a25

**Comment by arky** [comment]
@holta @jvonau Ah ha! Thanks, I'll give it a shot!

**Comment by holta** [comment]
@arky: @jvonau suspects that mcrypt should be stripped out of all packages a decade-or-so after the move to openssl (or perhaps it already has been, and me might be good to go without mcrypt already ??)

**Pull request merged**
