### PR TITLE
initial check in

### PR DESCRIPTION
**Pull request by tim-moody**
This is smoke tested on rpi
Not connected to any top level role
Needs more refinement on splash page
ToDo add auto submit on splash page

### CODE REVIEW

**Comment by tim-moody** [comment]
Not sure where this belongs in the stepwise install. It needs to own iptables.

**Comment by holta** [comment]
Ref #412 "Captive Portal design choices: onboarding non-Latin communities / URL literacy"

**Comment by tim-moody** [comment]
not sure if it restores previous iptables rules on stop - it does

**Comment by tim-moody** [comment]
anecdotally enabling nds and rebooting yields the correct iptables rules

**Comment by tim-moody** [comment]
Need to check status of pass through which seems enabled

**Comment by holta** [comment]
@deldesir is interested in making this work on Ubuntu 16.04 and 18.04 &mdash; thanks @deldesir if you get a chance to work with @tim-moody here!

**Comment by tim-moody** [comment]
Client Platform | Test Results
-- | --
Win 10 Laptop | IIAB home page shown on connect to SSID
Android 7.0 | Got redirected to home page, but still says Sign In at top   Went to wifi connection page and took ‘keep this connection; looks like I   have access to internet sites’   Now the splash page no longer appears   Restarted nodogsplash   Rebooted Android   Forgot connection   Still don’t get splash page   Now checked and nodogsplash no running   Started it and phone went to splash page; I clicked continue and now   don’t see signin (?but is it because it remembers the box page from previous   access)   I still think I am getting passthrough   12/8 changed config to redirect to home page and put variable back in   form field. Even when clicking continue I still see sign in to network in   bold letters at top (and fonts are wrong)
Android 4.3 | Connected without popup; has message sign into network   I clicked that and the splash screen came up and auto redirected to   the home page (which does not say signin)
iPhone 4, iOS 6.1.3 | Connected; then popped up and auto redirected to home page   BUT home page says login   I set it down and then it went back to AirX   Clicked iiab ssid and got iiab.me?!   Entered box and got to home page, BUT maybe remembered it.   BTW, Appendicitis video can not be started (nor pancreatitis)
Mac Air | Connected and showed splash then auto redirected.   Menu does not show sign in message (actuall in top bar it says “join   Internet in a Box”   BTW, Appendicitis video can not be started

**Pull request merged**
