### PR TITLE
Ubuntu - ppa install for ansible 2.4

### PR DESCRIPTION
**Pull request by jvonau**

### CODE REVIEW

**Comment by jvonau** [comment]
[unbutu-byhand.txt](https://github.com/iiab/iiab/files/1341740/unbutu-byhand.txt)

**Comment by holta** [comment]
@germanrs @kananigit @kmw

I'm looking for a sponsor to get this 1-liner Ansible 2.4.0 approach finalized for IIAB 6.4, smoke-tested and merged into master today or overnight if you can possibly help!

**Comment by germanrs** [comment]
Tested on Ubuntu 16.04 LTS (installed from scratch)

 I'm testing basic services, internet gateway, wifi, dhcp, dns, kiwix.

I'll keep you all informed.

For any purpose I'm attaching install.log
[iiab-install.log](https://github.com/iiab/iiab/files/1342792/iiab-install.log)

**Comment by holta** [comment]
Thx German!

Can you double-check "ansible --version" now responds 2.4.0.0 on Ubuntu?

**Comment by germanrs** [comment]
root@box:/opt/iiab/iiab# ansible --version
ansible 2.4.0.0
  config file = /opt/iiab/iiab/ansible.cfg
  configured module search path = [u'/usr/share/ansible']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
root@box:/opt/iiab/iiab#

**Comment by jvonau** [comment]
No need, the log says 2.4.0.0 with /usr/bin/anisble as the path, that is .deb install as opposed to pip that would use the /usr/local/bin/ansible path.

**Comment by holta** [comment]
This should be pushed into master unless there are immediate objections?

(I've polled for objections on our 7-person chat channel that arose out of this morning's call... http://minutes.iiab.io  ...all speak now, or hold your peace!)

**Pull request merged**
