### PR TITLE
Open Kolibri port in iptables, for on-campus browsing on WAN side of IIAB (e.g. http://192.168.0.x:8009)

### LINKED ISSUE #911: Kolibri times out in browser on Raspbian & Ubuntu 16.04 (sometimes other OS's too)
### Expected behavior and actual behavior.

http://box:8009 times out on Raspbian, despite Kolibri's Ansible installation completing (`./runrole kolibri`).  This also happen on Ubuntu 16.04/Desktop and Ubuntu 18.04/Server occasionally.

This is extremely odd given that http://box:8009 works on 18.04/Desktop (and Debian 9.5) using the exact same steps!  (http://box:8009 worked just once Raspbian out of many tries, before that too broke when Kolibri was re-installed using `./runrole kolibri`.)

CLARIF: of course verify that /opt/iiab/iiab/vars/local_vars.yml contains both `kolibri_install: True` and `kolibri_enabled: True`

### Steps to reproduce the problem.

After installing a BIG-sized version of [IIAB 6.6/master](http://download.iiab.io/6.6/load-big.txt) test http://box:8009 to see if the page loads.

If a page does load (e.g. on Raspbian) also try re-installing Kolibri to see if that breaks it:
```
cd /opt/iiab/iiab
git pull
./runrole kolibri    # or "./iiab-install --reinstall"
```
In all such breakage cases, visiting http://box:8009 causes the browser to "spin" and then time out (give up completely) about 15 seconds later.

_`systemctl status kolibri` shows "**active (exited)**" in green on all systems, both on those that are working (U18/Desktop, Raspbian) and on those that are not (U18/Server, U16/Desktop)._

Strangely nothing additional appears in Kolibri's log file on systems: (after trying to visit http://box:8009)
- more /library/kolibri/kolibri.log

FYI nothing additional appears on ANY of the systems (working and non-working) when checking logs like: (after trying to visit http://box:8009)
- more /library/kolibri/server.log
- journalctl -u kolibri --no-pager

@arky or @jvonau do you have any ideas?

### Specifications like the version of the IIAB, operating system version, or hardware details.

Ubuntu 18.04 systems were generally running on their own Inter NUC, whereas Debian 9.5 systems were generally running as VM's.

Raspbian Lite sysems (including the one that briefly displayed http://box:8009 initially!) were all running on RPi 3 B+.

All systems were fully updated using "apt update; apt -y dist-upgrade; reboot" prior to running http://download.iiab.io/6.6/load-big.txt to install BIG-sized IIAB including Kolibri.

### PR DESCRIPTION
**Pull request by holta**
VPN access to http://10.8.0.x:8009 and http://localhost:8089 work on RPi 3, but http://192.168.0.x:8009 doesn't(*) due to iptables.

Hopefully this PR Fixes #911 ?

(*) However http://192.168.0.x:8089 seems to work on VM's and similar, where 192.168.0.x is the "only" IP address (i.e. no AP hotspot exists, or none was configured...)

### CODE REVIEW

**Comment by holta** [comment]
This PR smoke-tested on RPi 3 B+ where it works!

CLARIF: these are the only files that matter to open up kolibri_http_port (8009) on the WAN side of IIAB:
- roles/network/templates/gateway/iiab-gen-iptables
- vars/default_vars.yml

Changes to these other 4 files constitute readability modernizations for our networking code:
- roles/network/tasks/debian.yml
- roles/network/tasks/down-debian.yml
- roles/network/tasks/ifcfg_mods.yml
- roles/network/tasks/restart.yml

**Comment by holta** [comment]
> Perhaps in future IIAB could adopt dbus based firewalld that is way more simpler to manage programmatically
https://firewalld.org/

@jvonau do you know anything about the above, in consideration of your firewall work around 15 years ago?

ASIDE: this PR #916 wil be merged as it was tested to fix Kolibri access on Ubuntu 18.04/Server and Ubuntu 16.04/Desktop too &mdash; all the situations were "WAN side" http://192.168.0.x:8089 is desired but had been blocked as a result of those IIAB's having an internal "LAN side" AP/hotspot.

RECAP / in hindsight the pattern is clear: those VM's and the one NUC that had no internal AP/hotspot, corresponded exactly to those where http://192.168.0.x:8089 worked (for both Ubuntu 18.04 and Debian 9.5).

**Comment by jvonau** [comment]
Drive by suggestions require work to implement, pull requests accepted.

**Comment by holta** [comment]
CLARIF: arguably, this PR prob should also have opened ports 8006 (for French KA Lite) and 8007 (for Spanish KA Lite), as published @ https://github.com/iiab/iiab/wiki/IIAB-Networking#list-of-open-ports--services

But I chose not to in the end, certainly for now.

FYI KA Lite tips on many such related issues are published here for IIAB implementers:
http://FAQ.IIAB.IO#KA_Lite_Administration:_What_tips_.26_tricks_exist.3F

**Pull request merged**
