### PR TITLE
pi-gen

### PR DESCRIPTION
**Pull request by jvonau**
support of [pi-gen](https://github.com/jvonau/pi-gen/tree/iiab) for IIAB

### CODE REVIEW

**Comment by georgejhunt** [comment]
- I think the objective of this PR, along with #2008, is to work towards the ability to quickly toggle enabled flags, from the Admin Console.
- If that is the objective, the timing, and benefits vs cost, need to be examined.
- Collectively, we had agreed that running under nginx  was a 7.1 objective.
- I'd like to get the nginx PR (#2009) into master before we look at making changes to over 100 files, as specified in these two PR's.
- I think that testing such a large group of changes will take significant effort. If we decide to proceed, we will have our work cut out for us in Boston. (Jerry, please come).

**Comment by holta** [comment]
> * I think the objective of this PR, along with #2008, is to work towards the ability to quickly toggle enabled flags, from the Admin Console.

At the command-line too.  @tim-moody's voice connection was cut off during this morning's call (http://minutes.iiab.io) but if I understood him correctly he outlined the possibility of commands _(like)_ `./iiab-enable <role>` and `./iiab-disable <role>` &mdash; that would interoperate cleanly with Admin Console &mdash; while also allowing rapid understandability at the command-line, for our many IIAB implementers who do *not* want to dive into Ansible details ;)

Design(s) like this I'd greatly support &mdash; e.g. whatever we can come up with that provides very simple, crystal clear ops to newbie implementers &mdash; from both the command-line and Admin Console.

> * If that is the objective, the timing, and benefits vs cost, need to be examined.

Together let's ask ourselves which *specific* implementers' need(s) are we trying to solve here, as we move forward with several large-scale PR's in coming weeks, Yes.

> * Collectively, we had agreed that running under nginx was a 7.1 objective.

Did we?   Sure why not, if it leads us towards improved Kolibri performance arising from [kolibri-server](https://github.com/learningequality/kolibri-server) and/or other concrete implementer usability deltas (etc).

At the same time IIAB 7.1's release is not contingent on a wholesale conversion to NGINX &mdash; let's see how far we get organically, and then ship when it's time to ship &mdash; preferably before New Years Day fireworks of 2020-01-01.  In parallel with several other [possible IIAB 7.1 objectives](https://github.com/iiab/iiab/wiki/IIAB-7.0-Release-Notes#what-might-future-versions-bring) outlined in that rough/prelim road map.

FYI field operators/implementers are happy with Apache being the backbone of IIAB today, none of whom are asking for better web server performance at this time.  However: if their lives (their IT maintenance burdens) can be made significantly easier and our software / content updates substantially more maintainable (i.e. IIAB upkeep, IIAB installation, IIAB software/content updates shortly after install, etc) then let's push to now lay out those specific NGINX advantage very publicly &mdash; articulating what we're heading for, so implementers understand and buy in.

> * I'd like to get the nginx PR (#2009) into master before we look at making changes to over 100 files, as specified in these two PR's.

_Am not there yet, but starting to understand better the objective(s) of these several larger PR's.  Thank you to **everyone** laying out these ongoing explanations, communicating (to all, if possible!) the critical underlying purpose(s) of each._

> * I think that testing such a large group of changes will take significant effort. If we decide to proceed, we will have our work cut out for us in Boston. (Jerry, please come).

YES!

**Comment by jvonau** [comment]
>     * I think the objective of this PR, along with #2008, is to work towards the ability to quickly toggle enabled flags, from the Admin Console.
> 
>     * If that is the objective, the timing, and benefits vs cost, need to be examined.
> 
>     * Collectively, we had agreed that running under nginx  was a 7.1 objective.
> 
>     * I'd like to get the nginx PR (#2009) into master before we look at making changes to over 100 files, as specified in these two PR's.
> 
>     * I think that testing such a large group of changes will take significant effort. If we decide to proceed, we will have our work cut out for us in Boston. (Jerry, please come).

Ok, let's move the refactoring debate to 2008 which in effect introduces a really really small chance of regressions as there are no new wrinkles to iron out during the install and doesn't introduce anything to upset the post install functional evaluation.

**Comment by jvonau** [comment]
> > * I think the objective of this PR, along with #2008, is to work towards the ability to quickly toggle enabled flags, from the Admin Console.
> 
> At the command-line too. @tim-moody's voice connection was cut off during this morning's call (http://minutes.iiab.io) but if I understood him correctly he outlined the possibility of commands _(like)_ `./iiab-enable <role>` and `./iiab-disable <role>` — that would interoperate cleanly with Admin Console — while also allowing rapid understandability at the command-line, for our many IIAB implementers who do _not_ want to dive into Ansible details ;)
> 
> Design(s) like this I'd greatly support — e.g. whatever we can come up with that provides very simple, crystal clear ops to newbie implementers — from both the command-line and Admin Console.
> 
> > * If that is the objective, the timing, and benefits vs cost, need to be examined.
> 
> Together let's ask ourselves which _specific_ implementers' need(s) are we trying to solve here, as we move forward with several large-scale PR's in coming weeks, Yes.

Think 2008 would go along way to differentiate the functions of installing what is needed to deploy the service|app and what is required to turn the service|app on|off, nothing is in stone iiab-enable|disable could be in the cards, just need to define what enable does... is that an implied install if not installled?
 
> > * Collectively, we had agreed that running under nginx was a 7.1 objective.
> 
It is, but when in the 7.1 time frame is the debate.

> Did we? Sure why not, if it leads us towards improved Kolibri performance arising from [kolibri-server](https://github.com/learningequality/kolibri-server) and/or other concrete implementer usability deltas (etc).
> 
> At the same time IIAB 7.1's release is not contingent on a wholesale conversion to NGINX — let's see how far we get organically, and then ship when it's time to ship — preferably before New Years Day fireworks of 2020-01-01. In parallel with several other [possible IIAB 7.1 objectives](https://github.com/iiab/iiab/wiki/IIAB-7.0-Release-Notes#what-might-future-versions-bring) outlined in that rough/prelim road map.
> 

I would recommend an opt in, dual support with apache being the default while the code that supports nginx is being refined. With the frame work laid out in 2008 the time to deploy a test on nginx would be drastically reduced needing just editing of local_vars and running iiab-configure that 2008 introduces or ICO to make the flip over to nginx. 

> FYI field operators/implementers are happy with Apache being the backbone of IIAB today, none of whom are asking for better web server performance at this time. However: if their lives (their IT maintenance burdens) can be made significantly easier and our software / content updates substantially more maintainable (i.e. IIAB upkeep, IIAB installation, IIAB software/content updates shortly after install, etc) then let's push to now lay out those specific NGINX advantage very publicly — articulating what we're heading for, so implementers understand and buy in.
> 

That is my don't rock the boat, opt in preference to the wholesale flip to nginx 

> > * I'd like to get the nginx PR (#2009) into master before we look at making changes to over 100 files, as specified in these two PR's.
>
I'll point out that you are changing 47 files while rocking the foundations of what is currently building up iiab. I'll help rebase what you have now, and lets get this right for a seamless transition.  
 
> _Am not there yet, but starting to understand better the objective(s) of these several larger PR's. Thank you to **everyone** laying out these ongoing explanations, communicating (to all, if possible!) the critical underlying purpose(s) of each._
> 
> > * I think that testing such a large group of changes will take significant effort. If we decide to proceed, we will have our work cut out for us in Boston. (Jerry, please come).
> 
> YES!

**Comment by georgejhunt** [comment]
Jerry suggests "I would recommend an opt in, dual support"

I think we had agreed to have nginx and apache side by side on into the
future, until at some point, we didn't need apache.

If the end user opts in or out, it doubles our testing of services we
already have running under apache, but would then need to also support
under nginx.

**Pull request closed without merging**
