### PR TITLE
First run logic

### PR DESCRIPTION
**Pull request by jvonau**
continuation of #275 and #279

### CODE REVIEW

**Comment by holta** [comment]
@georgejhunt let us know when u can review this, Thx!

**Comment by tim-moody** [comment]
this pr eliminates the effect of using admin console as no changes done there will ever be used by runansible

**Comment by jvonau** [comment]
I don't understand the objection, runansible is intended to run **only once** to bootstrap the system, to be able in install the console afterwords, once complete should not be used again. For testing a second pass,  to simulate running the gui for the first time, should work without issue. I agree that runtags would disregard config_vars, but is being targeted at developers as a debugging tool and not enduser use, although it can be.  Don't understand why one would need to 'runansible' a second time once the gui is functioning. Please explain.

**Comment by tim-moody** [comment]
OK. In that case let runansible check for the existence of config vars and stop with a notice if found, since creating it is the last thing done.

**Comment by jvonau** [comment]
Think we can have that both ways, add the ability to override the check if '
runansible  --debug' is passed on the cmdline?

**Comment by jvonau** [comment]
runansible --debug support added

**Comment by jvonau** [comment]
smoketested 
[0921-revised_net_feedback-clean.txt](https://github.com/iiab/iiab/files/1323612/0921-revised_net_feedback-clean.txt)

**Pull request merged**
