### PR TITLE
Bluetooth PAN and Terminal servers

### PR DESCRIPTION
**Pull request by tim-moody**

### CODE REVIEW

**Comment by tim-moody** [comment]
passed smoke test on non-rpi
bt-term not working on rpi

**Comment by tim-moody** [comment]
passed smoke test on rpi
win 10 can connect to pan

**Comment by jvonau** [comment]
To ensure updates don't undue the change please copy the Bluetooth service file to /etc/systemd/system/ and edit that copy.

**Comment by tim-moody** [comment]
good point. thanks for catching it.

**Comment by georgejhunt** [comment]
What a pain to have to add "| bool" to all our flags. Some are missing in this PR

**Comment by tim-moody** [comment]
It's my impression that when there is a Boolean operation the cast is not required. so when: is_rpi and bluetooth_install but when: is_rpi |bool

**Comment by georgejhunt** [comment]
good to know, thanks

**Review by jvonau — APPROVED** [review]
Let's go with it..

**Pull request merged**
