### PR TITLE
ansible package regression [fix for Ubuntu 16.04 LTS]

### PR DESCRIPTION
**Pull request by georgejhunt**
not smoke tested

### CODE REVIEW

**Comment by jvonau** [comment]
Think a later version can be enabled via ppa I've updated #316 to use the ppa listed there.
https://launchpad.net/~ansible/+archive/ubuntu/ansible

**Comment by holta** [comment]
@arky and @tim-moody have asked that we move towards rapid release now, by accepting byte-sized (and bite-sized if nec!) changes only.

e.g. if this 6 line-change is truly needed & tested in our final remaining hours?

**Comment by holta** [comment]
Thank you @kmw for the following bug report &mdash; reconfirmed twice by trying to install [IIAB 6.4 RC5](https://github.com/iiab/iiab/releases/) onto Ubuntu 16.04 LTS:
```
TASK [2-common : include]
******************************************************
fatal: [127.0.0.1]: FAILED! => {"failed": true, "reason": "ERROR! no
action detected in task\n\nThe error appears to have been in
'/opt/iiab/iiab/roles/2-common/tasks/udev.yml': line 21, column 3, but
may\nbe elsewhere in the file depending on the exact syntax
problem.\n\nThe offending line appears to be:\n\n\n- name: Ask systemd to
recognize the changes\n  ^ here\n"}
```

**Comment by jvonau** [comment]
> ubuntu 16.04 comes with ansible 2.0.0.2 -- no systemd module

Think we need to enable the ppa for ansible noted above. @arky until #316 is merged can you try adding the equivalent of https://github.com/iiab/iiab/pull/316/commits/649ebb50815e61edcde185d5c1478bc617577b71 when provisioning the Unbutu VM? I just have not had a chance to provision a Unbutu instance on hadron yet.

**Comment by holta** [comment]
@georgejhunt and @germanrs have tested this successfully on Ubuntu 16.04 LTS, see https://github.com/iiab/iiab/issues/322#issuecomment-332680393

Has anybody completed a Raspbian Stretch smoke and/or functional test yet here?!

**Comment by holta** [comment]
Clarif: this PR #323 uses Ansible 2.0.0.2 from January 2016, is tight and it works (on Ubuntu at least!) most important.

At the same time be aware there's a growing/sudden/worthwhile discussion among many people I've talked to today as to whether we can/should all stay more sane going forward by possibly unifying all distros around Ansible 2.4.x.x (or some such strategy; it remains unclear when this can-or-should happen but it needs a very healthy debate in context with PR #316 and similar...)

**Comment by georgejhunt** [comment]
passed smoke test

**Comment by holta** [comment]
> passed smoke test

@georgejhunt can you clarify precisely what you mean?  I wrote above that you and German (and now others!) have smoke-tested this on Ubuntu yesterday.

Has this been smoke-tested on Raspbian do you know?  Thx!

**Comment by tim-moody** [comment]
passed smoke test on raspbian

**Pull request merged**
