### PR TITLE
(1) ansible-core 2.14.0 fails to install on 32-bit ARM OS's (2) Some 32-bit RPi OS's end up upgrading to the older ansible-core 2.11.x

### PR DESCRIPTION
**Pull request by holta**
Thanks @deldesir for surfacing this bug, on Raspberry Pi OS Lite (64-bit??) on a Raspberry Pi 3 Model B Rev 1.2

I've confirmed with 32-bit Raspberry Pi OS with desktop (32-bit) on an identical CPU to his.

@deldesir please explain more if you discover more details in coming days, Thanks!

Related:

- PR #3418

### CODE REVIEW

**Comment by holta** [comment]
Apparently ansible-core 2.14.0 does work on the latest 64-bit RasPiOS on Raspberry Pi 3 and Raspberry Pi 3 B+ (!)

@deldesir will explain more when he figures out more what's happening.

**Comment by holta** [comment]
@deldesir: Is it possible **_32-bit_** RasPiOS does not allow recent versions of Ansible?

(Given that ansible-core 2.14.0 seems to run fine on **_64-bit_** RasPiOS on RPi 3 and 3 B+)

**Comment by jvonau** [comment]
How can this be the right fix if the ansible version installed is really part of scripts/ansible? #3418

**Comment by holta** [comment]
> How can this be the right fix if the ansible version installed is really part of scripts/ansible? #3418

[scripts/ansible](https://github.com/iiab/iiab/blob/master/scripts/ansible) installs ansible-core 2.11.12 on 32-bit OS's.  Try it and you will see.  Hopefully @deldesir can reconfirm.

(So we need to be more forgiving of [almost 2 year old versions], for people who want/need [that] while it still works!)

**Comment by deldesir** [comment]
CLARIF. Ansible-core (latest version via pip3 --upgrade ansible-core) won't install on RPI 3 B with Raspberry Pi OS from 22-9-2022.

**Comment by deldesir** [comment]
CLARIF. Ansible-core (latest version via pip3 --upgrade ansible-core) won't install on RPI 3 B with Raspberry Pi OS from 22-9-2022. 

What I found:

1- ansible-core 2.14 depends on cryptography that requires having a rust toolchain. Ansible won't install via pip on RPI 3B  because there's an issue with wheel building mechanism for RPI 3B (won't fix with pip3 upgrade --pip, nor disabling rust in the build process). The only choice left is to use older versions of ansible-core.

2- To use latest Ansible (ansible-core 2.14) on RPI 3B, I used Ansible off GitHub repo with cryptography<=3.3.2,
but the problem is Ansible script check for existence of Ansible bin in standard path /usr/bin. Symlinking the "GitHub" Ansible binary in usr/bin or usr/local/bin will break import mechanisms of Ansible package unless I do some tweaks in each python files.

**Comment by deldesir** [comment]
CLARIF. Ansible-core (latest version via pip3 --upgrade ansible-core) won't install on RPI 3 B with Raspberry Pi OS from 22-9-2022. 

What I found:

1- ansible-core 2.14 depends on cryptography that requires having a rust toolchain. Ansible won't install via pip on RPI 3B  because there's an issue with wheel building mechanism for RPI 3B (won't fix with pip3 upgrade --pip, nor disabling rust in the build process). The only choice left is to use older versions of ansible-core.

2- To use latest Ansible (ansible-core 2.14) on RPI 3B, I used Ansible off GitHub repo with cryptography<=3.3.2,
but the problem is Ansible script check for existence of Ansible bin in standard path /usr/bin. Symlinking the "GitHub" Ansible binary in usr/bin or usr/local/bin will break import mechanisms of Ansible package unless I do some tweaks in each python files.

**Comment by holta** [comment]
> CLARIF. Ansible-core (latest version via pip3 --upgrade ansible-core) won't install on RPI 3 B with Raspberry Pi OS from 22-9-2022.

FYI I had a somewhat different experience:

For me `scripts/ansible` (equivalent to `pip3 install --upgrade ansible-core`) installed ansible-core 2.11.12 (i.e. yesterday's point release) onto 32-bit "Raspberry Pi OS with desktop" on RPi 3 (Raspberry Pi 3 Model B Rev 1.2, identical to @deldesir's CPU).

(Though note mine was running an earlier version of RasPiOS with desktop, not 2022-09-22!)

Just FYI: [ansible-core 2.11.0](https://docs.ansible.com/ansible/latest/roadmap/ROADMAP_2_11.html) was originally released on 2021-04-26.

**Comment by holta** [comment]
> Ansible off GitHub repo with cryptography<=3.3.2

If ansible-core 2.11.12 continues to work fine on 32-bit OS's (e.g. on RPi 3 and similar machines) that's what we should use for now :checkered_flag:

(Certainly tinkering with Rust crypto libraries within fundamental infra is... not the best use of our time... let's avoid getting too involved in an upstream packaging soap opera if at all possible ;-)

**Comment by jvonau** [comment]
Still broken
```
INSTALL ANSIBLE + CORE IIAB SOFTWARE + ADMIN CONSOLE / CONTENT PACK MENUS...

Install Ansible...


YOU ARE RUNNING: /opt/iiab/iiab/scripts/ansible (TO INSTALL ANSIBLE ETC)

RECOMMENDED PREREQUISITES:
(1) Verify you're online
(2) Remove all prior versions of Ansible using...
    'apt purge ansible-core'  and/or  'pip3 uninstall ansible-core'  and/or
    'apt purge ansible-base'  and/or  'pip3 uninstall ansible-base'  and/or
    'apt purge ansible'       and/or  'pip3 uninstall ansible'
(3) Remove all lines containing 'ansible' from...
    /etc/apt/sources.list and /etc/apt/sources.list.d/*

IIAB INSTALL INSTRUCTIONS: (OLDER, MANUAL APPROACH)
https://github.com/iiab/iiab/wiki/IIAB-Installation#do-everything-from-scratch

ANSIBLE NOT FOUND ON THIS COMPUTER -- LET'S TRY TO INSTALL IT!
(Internet-in-a-Box requests ansible-core 2.14.0 or higher)


apt update; apt install python3-pip    # Also installs 'python3-setuptools' and 'python3' etc
Hit:1 http://raspbian.raspberrypi.org/raspbian bullseye InRelease
Hit:2 http://archive.raspberrypi.org/debian bullseye InRelease
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
All packages are up to date.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
python3-pip is already the newest version (20.3.4-4+rpt1+deb11u1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Writing to /etc/pip.conf


'pip3 install --upgrade ansible-core' will now run:

Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting ansible-core
  Downloading https://www.piwheels.org/simple/ansible-core/ansible_core-2.14.0-py3-none-any.whl (2.2 MB)
     |████████████████████████████████| 2.2 MB 232 kB/s 
Collecting resolvelib<0.9.0,>=0.5.3
  Downloading https://www.piwheels.org/simple/resolvelib/resolvelib-0.8.1-py2.py3-none-any.whl (16 kB)
Collecting PyYAML>=5.1
  Downloading https://www.piwheels.org/simple/pyyaml/PyYAML-6.0-cp39-cp39-linux_armv7l.whl (45 kB)
     |████████████████████████████████| 45 kB 7.6 MB/s 
Requirement already satisfied: cryptography in /usr/lib/python3/dist-packages (from ansible-core) (3.3.2)
Collecting packaging
  Downloading https://www.piwheels.org/simple/packaging/packaging-21.3-py3-none-any.whl (40 kB)
     |████████████████████████████████| 40 kB 274 kB/s 
Collecting jinja2>=3.0.0
  Downloading https://www.piwheels.org/simple/jinja2/Jinja2-3.1.2-py3-none-any.whl (133 kB)
     |████████████████████████████████| 133 kB 231 kB/s 
Collecting MarkupSafe>=2.0
  Downloading https://www.piwheels.org/simple/markupsafe/MarkupSafe-2.1.1-cp39-cp39-linux_armv7l.whl (23 kB)
Collecting pyparsing!=3.0.5,>=2.0.2
  Downloading https://www.piwheels.org/simple/pyparsing/pyparsing-3.0.9-py3-none-any.whl (98 kB)
     |████████████████████████████████| 98 kB 336 kB/s 
Installing collected packages: pyparsing, MarkupSafe, resolvelib, PyYAML, packaging, jinja2, ansible-core
  Attempting uninstall: MarkupSafe
    Found existing installation: MarkupSafe 1.1.1
    Not uninstalling markupsafe at /usr/lib/python3/dist-packages, outside environment /usr
    Can't uninstall 'MarkupSafe'. No files were found to uninstall.
  Attempting uninstall: jinja2
    Found existing installation: Jinja2 2.11.3
    Not uninstalling jinja2 at /usr/lib/python3/dist-packages, outside environment /usr
    Can't uninstall 'Jinja2'. No files were found to uninstall.
Successfully installed MarkupSafe-2.1.1 PyYAML-6.0 ansible-core-2.14.0 jinja2-3.1.2 packaging-21.3 pyparsing-3.0.9 resolvelib-0.8.1


IIAB requires these ~4 Ansible Collections: (we upgrade them here if possible!)

ERROR: Ansible could not initialize the preferred locale: unsupported locale setting
Type 'exit [Enter]' to continue
```

Don't you need to fix the version in scripts/ansible? with `pip3 install --upgrade ansible-core==2.13.5` to get something less than the 'latest'?

**Comment by jvonau** [comment]
```
python3-pip is already the newest version (20.3.4-4+rpt1+deb11u1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Writing to /etc/pip.conf


'pip3 install --upgrade ansible-core' will now run:

Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting ansible-core==2.13.5
  Downloading https://www.piwheels.org/simple/ansible-core/ansible_core-2.13.5-py3-none-any.whl (2.1 MB)
     |████████████████████████████████| 2.1 MB 231 kB/s 
Requirement already satisfied: packaging in /usr/local/lib/python3.9/dist-packages (from ansible-core==2.13.5) (21.3)
Requirement already satisfied: cryptography in /usr/lib/python3/dist-packages (from ansible-core==2.13.5) (3.3.2)
Requirement already satisfied: jinja2>=3.0.0 in /usr/local/lib/python3.9/dist-packages (from ansible-core==2.13.5) (3.1.2)
Requirement already satisfied: resolvelib<0.9.0,>=0.5.3 in /usr/local/lib/python3.9/dist-packages (from ansible-core==2.13.5) (0.8.1)
Requirement already satisfied: PyYAML>=5.1 in /usr/local/lib/python3.9/dist-packages (from ansible-core==2.13.5) (6.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.9/dist-packages (from jinja2>=3.0.0->ansible-core==2.13.5) (2.1.1)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /usr/local/lib/python3.9/dist-packages (from packaging->ansible-core==2.13.5) (3.0.9)
Installing collected packages: ansible-core
  Attempting uninstall: ansible-core
    Found existing installation: ansible-core 2.14.0
    Uninstalling ansible-core-2.14.0:
      Successfully uninstalled ansible-core-2.14.0
Successfully installed ansible-core-2.13.5


IIAB requires these ~4 Ansible Collections: (we upgrade them here if possible!)

Starting galaxy collection install process
Process install dependency map
Starting collection install process
Downloading https://galaxy.ansible.com/download/ansible-posix-1.4.0.tar.gz to /root/.ansible/tmp/ansible-local-79416r1fxgf60/tmpdnrwwxs6/ansible-posix-1.4.0-bk9ljxxo
Installing 'ansible.posix:1.4.0' to '/usr/share/ansible/collections/ansible_collections/ansible/posix'
Downloading https://galaxy.ansible.com/download/community-postgresql-2.3.0.tar.gz to /root/.ansible/tmp/ansible-local-79416r1fxgf60/tmpdnrwwxs6/community-postgresql-2.3.0-e1idqd9i
ansible.posix:1.4.0 was installed successfully
Installing 'community.postgresql:2.3.0' to '/usr/share/ansible/collections/ansible_collections/community/postgresql'
Downloading https://galaxy.ansible.com/download/community-mysql-3.5.1.tar.gz to /root/.ansible/tmp/ansible-local-79416r1fxgf60/tmpdnrwwxs6/community-mysql-3.5.1-a2i174aw
community.postgresql:2.3.0 was installed successfully
Installing 'community.mysql:3.5.1' to '/usr/share/ansible/collections/ansible_collections/community/mysql'
Downloading https://galaxy.ansible.com/download/community-general-6.0.0.tar.gz to /root/.ansible/tmp/ansible-local-79416r1fxgf60/tmpdnrwwxs6/community-general-6.0.0-8zhv4cyh
community.mysql:3.5.1 was installed successfully
Installing 'community.general:6.0.0' to '/usr/share/ansible/collections/ansible_collections/community/general'
community.general:6.0.0 was installed successfully


SUCCESS!  PLEASE VERIFY ANSIBLE WITH COMMANDS LIKE:

    ansible --version
    pip3 show ansible-core
    apt -a list "ansible*"
    ansible-galaxy collection list

```

**Comment by jvonau** [comment]
side note after 2.13.5 is installed one can install 2.14.0 but fails at collections
```
apt update; apt install python3-pip    # Also installs 'python3-setuptools' and 'python3' etc
Hit:1 http://raspbian.raspberrypi.org/raspbian bullseye InRelease
Hit:2 http://archive.raspberrypi.org/debian bullseye InRelease
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
All packages are up to date.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
python3-pip is already the newest version (20.3.4-4+rpt1+deb11u1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Writing to /etc/pip.conf


'pip3 install --upgrade ansible-core' will now run:

Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: ansible-core in /usr/local/lib/python3.9/dist-packages (2.13.5)
Collecting ansible-core
  Downloading https://www.piwheels.org/simple/ansible-core/ansible_core-2.14.0-py3-none-any.whl (2.2 MB)
     |████████████████████████████████| 2.2 MB 227 kB/s 
Requirement already satisfied: resolvelib<0.9.0,>=0.5.3 in /usr/local/lib/python3.9/dist-packages (from ansible-core) (0.8.1)
Requirement already satisfied: PyYAML>=5.1 in /usr/local/lib/python3.9/dist-packages (from ansible-core) (6.0)
Requirement already satisfied: cryptography in /usr/lib/python3/dist-packages (from ansible-core) (3.3.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.9/dist-packages (from ansible-core) (21.3)
Requirement already satisfied: jinja2>=3.0.0 in /usr/local/lib/python3.9/dist-packages (from ansible-core) (3.1.2)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.9/dist-packages (from jinja2>=3.0.0->ansible-core) (2.1.1)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /usr/local/lib/python3.9/dist-packages (from packaging->ansible-core) (3.0.9)
Installing collected packages: ansible-core
  Attempting uninstall: ansible-core
    Found existing installation: ansible-core 2.13.5
    Uninstalling ansible-core-2.13.5:
      Successfully uninstalled ansible-core-2.13.5
Successfully installed ansible-core-2.14.0


IIAB requires these ~4 Ansible Collections: (we upgrade them here if possible!)

ERROR: Ansible could not initialize the preferred locale: unsupported locale setting
```

**Comment by holta** [comment]
> Still broken

Please mention HW & exact OS?

(This original issue arose b/c @deldesir thought he was running 64-bit Raspberry Pi OS Lite on Raspberry Pi 3 Model B Rev 1.2 — when in reality it turns out he'd installed the 32-bit OS.)

**Comment by holta** [comment]
> Don't you need to fix the version in scripts/ansible? with pip3 install --upgrade ansible-core==2.13.5 to get something less than the 'latest'?

Personally I did not need any such.

Running `scripts/ansible` just worked for me, to install ansible-core 2.11.12, on 32-bit "RasPiOS with desktop" (an earlier version than 2022-09-22) on Raspberry Pi 3 Model B Rev 1.2

So the facts still need to be established.

**Comment by jvonau** [comment]
Some 'facts': http://sprunge.us/3fyNhH?bash line 96 from #3385 has 2.13.4 being installed. This error is from my build pipeline with 2022-09-22-raspios-bullseye-armhf.img.xz as the source.

**Comment by holta** [comment]
> This error is from my build pipeline with 2022-09-22-raspios-bullseye-armhf.img.xz as the source.

Can you mention the CPU & exact OS?

> http://sprunge.us/3fyNhH?bash line 96 from #3385 has 2.13.4

I don't see how that's related?  (The above is 64-bit where there are no known problems.  Above pastebin is Intel i3 FWIW, unrelated to Raspberry Pi.)

**Comment by holta** [comment]
> 2022-09-22 raspios-bullseye-armhf.img.xz as the source.

That probably implies 32-bit Raspberry Pi OS with desktop.

Knowing the CPU (is this an RPi 400?) would also help @deldesir get up to speed understanding.

**Comment by jvonau** [comment]
http://sprunge.us/e7omTt?bash line 93 installed on 2022-10-23 from #3408 installed 2.13.5

**Comment by jvonau** [comment]
https://github.com/pyca/cryptography/issues/7651

**Pull request merged**
