### PR TITLE
Reserved device [reserved_device LAN-side networking variable]

### PR DESCRIPTION
**Pull request by jvonau**
untested

### CODE REVIEW

**Comment by holta** [comment]
@jvonau,

Currently https://github.com/iiab/iiab/wiki/IIAB-Networking#common-customizations says:

> (2) If your Internet-in-a-Box (IIAB) contains multiple Wi-Fi interfaces, put the following into /etc/iiab/local_vars.yml to ask IIAB not to create a LAN-side access point on the wlan0 interface:
>
> `reserved_wifi: wlan0`

Is this related and/or should it be changed?

Ref: #2610

**Comment by jvonau** [comment]
S/B changed see 1693e502bad7c933b8887918524c8030340fe74e & aed16ca9f2b000ba8c07bd83ef72760b3561f5bb, the description now needs work as this routine never really was wifi specific but that was the original use cases. "used to exclude listed device in network detection and calculation of 'br0's member(slave) devices'"

**Comment by holta** [comment]
> the description now needs work as this routine never really was wifi specific but that was the original use case

Not the final word, but hopefully this documentation/explanation is improved:

https://github.com/iiab/iiab/wiki/IIAB-Networking#common-customizations -> Item (2)

**Comment by holta** [comment]
@georgejhunt can you review this and/or suggest what testing is most desirable?

**Comment by georgejhunt** [comment]
This PR deletes initiaization of /etc/iiab/iiab.env for network interfaces. Without extensive testing, I think the risk of unintended consequences is pretty high. Who knows how many times the values in /etc/iiab/iiab.env are used? I don't. 

Unrelated note: I remember that the admin console has a reboot and poweroff button which caused my Digital Ocean droplet to fall off line when I thought I had  the buttons disabled.

**Comment by holta** [comment]
> This PR deletes [initialization] of /etc/iiab/iiab.env for network interfaces

Is that confirmed true?

Or is it possible this recording to iiab.env is just moved down from Line 7 (detected_network.yml) to Line 53 (enable_services.yml) of...?

https://github.com/iiab/iiab/blob/master/roles/network/tasks/main.yml

**Comment by georgejhunt** [comment]
Sorry, I missed that move to a different file.

**Comment by holta** [comment]
> I remember that the admin console has a reboot and poweroff button which caused my Digital Ocean droplet to fall off line when I thought I had the buttons disabled.

@tim-moody do you understand that?

**Comment by georgejhunt** [comment]
I'm sorry Tim that Adam had to bother you about trying to figure out what I meant.
The variable I was too lazy to find was:
./roles/js-menu/files/menu.json:16:  "allow_poweroff" : true
I was not taking responsibility for my error and not remembering correctly.

**Comment by holta** [comment]
@tim-moody do you have time to review this PR or suggest what testing is most desirable?

**Pull request closed without merging**
