### PR TITLE
asterisk-test-script

### PR DESCRIPTION
**Pull request by lemueldsouza**
### Description of changes proposed in this pull request:
A simple and basic script that creates pjsip extensions and a quick test call from the console to help the user quickly test if asterisk is working (add more tests in future). In the real world, you are requested to perform these actions using FreePBX webpage. 

The script asterisk_test uses the two files pjsip_custom.conf and extensions_custom.conf to create pjsip extensions and a dialplan. 

On successful execution of the script, you could directly register the extension (301 and/or 302) on your softphone app using steps mentioned in PBX README and credentials in pjsip_custom.conf

### Usage
- `sudo ./asterisk_test`
Default - Executes the complete script and reverts file changes done during the test and restarts asterisk

- `sudo ./asterisk_test retain`
Files not reverted after the test. Extensions created remain active

- `sudo ./asterisk_test revert`
In case you selected retain earlier, but now like to revert the changes. This will only revert the changes to the files and restart asterisk, no other actions are performed

- `sudo ./asterisk_test restart`
Restarts asterisk, no other actions are performed

- `sudo ./asterisk_test testcall`
Makes a test call from asterisk console to extension 1000

### Smoke-tested on which OS or OS's:
Tested on Raspberry Pi Buster

@holta Please test it other other systems

### CODE REVIEW

**Comment by holta** [comment]
Thanks @lemueldsouza !

Regarding [/opt/iiab/iiab/roles/pbx/templates/asterisk_test](https://github.com/lemueldsouza/iiab/blob/master/roles/pbx/templates/asterisk_test) which today has non-runnable permissions 0644, when this current PR is installed as part of IIAB:

- Whether this should live in `/usr/bin` as `/usr/bin/iiab-asterisk-test` (or anywhere else!) let's make sure it's hassle-free for new implementers to try out, with permissions set correctly out of the box!

- Personally I don't find `/opt/iiab/iiab/scripts` and `/opt/iiab/iiab/roles/pbx/files` very discoverable for new people.  (But there may be other options you want to suggest?)

(All of this will of course help keep [README.adoc](https://github.com/iiab/iiab/tree/master/roles/pbx#pbx-readme) succinct, i.e. pointing the way very clearly!)

Refs:

- PR #2896
- PR #2941

**Comment by holta** [comment]
@lemueldsouza I'm swamped this week and so am merging this to encourage wider community testing:

Can you add ~2 sentences within (or nearby) https://github.com/iiab/iiab/tree/master/roles/pbx#try-it-out-with-an-android-or-iphone-softphone-sip-app to make sure folks know about this?

**Comment by holta** [comment]
@lemueldsouza is this `asterisk_test` script (possibly to be renamed `iiab-asterisk-test` in future?) most useful to provide very rapid diagnostics _even prior_ to setting up any Android/iPhone/laptop SIP clients?

(And/or other purposes that I and others might not have considered?  Thanks for clarifying who can most benefit!)

**Comment by lemueldsouza** [comment]
> Can you add ~2 sentences within (or nearby) https://github.com/iiab/iiab/tree/master/roles/pbx#try-it-out-with-an-android-or-iphone-softphone-sip-app to make sure folks know about this?

Sure, will do that today

> @lemueldsouza is this asterisk_test script (possibly to be renamed iiab-asterisk-test in future?) most useful to provide very rapid diagnostics even prior to setting up any Android/iPhone/laptop SIP clients?

> (And/or other purposes that I and others might not have considered? Thanks for clarifying who can most benefit!)

Yes, we could rename it in future. Yes, its a rapid test to _create extensions_ without using FreePBX and _make a test call without registering a softphone_. Asterisk provides the `dial` command to place a call from the console.

There may be better ways to test this (anyone is welcome to help make this better), but this is what I use now.

**Pull request merged**
