### PR TITLE
Dual WiFi WARNING: 5 GHz connection from internal WiFi to Internet...ends up sabotaging legacy WiFi client devices that require 2.4GHz !

### PR DESCRIPTION
**Pull request by holta**
Thanks @jvonau for reviewing this verbiage/warning if poss.

Background: Willem in South Africa got stuck...when his phone could connect to IIAB's internal hotspot but his older laptop could not.  A big thank you to @jvonau for figuring out why this was happening!

### CODE REVIEW

**Comment by holta** [comment]
ASIDE: Our quick outreach intro/teaser explaining "Dual Wi-Fi" is further clarified here &mdash; for non-technical folk who want a quick understanding &mdash; as to why they might want this:

https://github.com/iiab/iiab/wiki/IIAB-7.1-Release-Notes#whats-new

**Comment by holta** [comment]
If these warnings need further enhancement after merging, please let me know!

**Comment by tim-moody** [comment]
rpi 4 only

**Comment by holta** [comment]
> rpi 4 only

And RPi 3 B+ too presumably (which uses the identical 43455 WiFi chip).

**Pull request merged**
