### PR TITLE
RFC netplan systemd-networkd static support (fixed IP address on Ubuntu 18.04/Server)

### PR DESCRIPTION
**Pull request by jvonau**

### CODE REVIEW

**Comment by georgejhunt** [comment]
Does it make sense to put an if clause in the template so that the admin console can toggle fixed ip?

Right now, the template is only written if not dhcp. I think it would be better to put the conditional in the template, and then it would work in both directions

**Comment by jvonau** [comment]
Yea was thinking about that, then the hockey game started 'go jets' and I paused for a bit.

**Comment by holta** [comment]
Thank you to @georgejhunt for making this all possible, with the Ubuntu 18.04/Server test machine and ongoing review.

**Comment by georgejhunt** [comment]
I wonder if there is a reason for debian-auto -> patch-auto. I have been tripped up many times when file names or variable names change without reason (worst case is into the ini file).

**Comment by jvonau** [comment]
I created the template as debian-auto with the intent to deploy it like that and Tim suggested patch-auto as the final name.

**Comment by holta** [comment]
PR #791 (that we hope to merge very shortly!) supercedes this, per discussion during our community/team call this morning @ http://minutes.iiab.io

**Pull request closed without merging**
