### PR TITLE
maps_from_internet_archive & tidying of iiab-network, default_vars.yml, local_vars.yml, iiab-admin/README.rst, osm-vector-maps/README.md [Aside: iiab_home_url clarif ongoing, recommend ansible-base 2.10.2]

### PR DESCRIPTION
**Pull request by holta**
For iiab/maps#38 (faster install of Map Packs) and the upcoming IIAB 7.2 RC3.

i.e. to resolve the 1st half of #2553 (speeding up OSM downloads, whereas Satellite Photo downloads [from Sentinel Cloudless, rate limited to ~300 kbit/s] are a whole other ball wax ;)

Refs: #2560

### CODE REVIEW

**Comment by holta** [comment]
Not always possible, but I'm again trying to bring local_vars.yml files & default_vars.yml back within 80 characters width (much more readable on some ssh clients etc) in preparation for our upcoming release.

**Comment by holta** [comment]
I added @jvonau's suggestion to further strengthen the warning as `./iiab-network` completes:

```
Please REBOOT to fully verify your network -- graphical desktops MUST reboot!

**Comment by jvonau** [comment]
@georgejhunt  Please look at this PR and I have quick question. Isn't openvpn_handle intended to be an optional enduser override for the unique uuid generated at install time and stored in /etc/iiab/uuid that would otherwise be used when this variable is left unpopulated?

**Comment by holta** [comment]
> @georgejhunt Please look at this PR and I have quick question. Isn't openvpn_handle intended to be an optional enduser override for the unique uuid generated at install time and stored in /etc/iiab/uuid that would otherwise be used when this variable is left unpopulated?

That's the idea, but our longstanding implementation since ~2016 is a bit fragile in that `/etc/iiab/uuid` is only used when openvpn_handle is set to the empty string ("") according to my tests in 2018: https://github.com/iiab/iiab/blob/master/roles/openvpn/tasks/main.yml#L45 (SEE ALSO https://github.com/iiab/iiab/blob/master/roles/openvpn/templates/announcer.j2#L37)

Of course this could be changed, if anybody really wants to change it, but since IIAB's OpenVPN operation has been wonderfully reliable for ~4 years (possibly 5 years now?) I personally have not gone into the guts of the OpenVPN implementation to try changing it!

Ref: #2361

**Pull request merged**
