### PR TITLE
Ejabberd continued

### PR DESCRIPTION
**Pull request by jvonau**
This restores ejabberd_xs to a working state for legacy installs on is_redhat, providing further development of current ejabberd on all distros.

### CODE REVIEW

**Comment by holta** [comment]
Thanks @jvonau for re-constituting this when time.

Clarif for all: ejabberd_xs is in STAGE 5 and ejabberd is in STAGE 6 @ [iiab.yml](https://github.com/iiab/iiab/blob/master/iiab.yml).

**Comment by holta** [comment]
Just FYI when using a BIG-sized local_vars.yml that includes the follow: (in Stage 6 of our 9 Ansible stages)
```
ejabberd_install: True
ejabberd_enabled: False
```
...the following shows up in red on boot: (on Raspian Lite 2017-09-07 on RPi3, running current IIAB master)
```
Failed to start A distributed, fault-tolerant Jabber/XMPP server.
```

**Comment by jvonau** [comment]
Think this has is a similar root cause as the isc-dhcp-server issue noted in #337, where we drop a custom systemd service file into place but fail to disable the stock os provided service file name.

**Comment by holta** [comment]
@jvonau smoke-tested earlier autumn and all 4 of us {George, Tim, Holt, Jerry} agreed to merge this during our community/team call (http://minutes.iiab.io)

**Pull request merged**
