### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by georgejhunt**
Document what I have found running runansible, and iiab-admin/install. Still running ICO, and finding things

### CODE REVIEW

**Comment by tim-moody** [comment]
hope there are not too many of these things that were sitting in my PR that may have been done elsewhere

**Comment by georgejhunt** [comment]
After ICO, on debian VM, the following were checked and worked:
nextcloud, kiwix, kalite, sugarizer, munin
failed: awstats (probably not enough time to accumulate log)
          moodle -- we need a solution
Tim do these changes look ok to  you? (master is currently broken and I'd like to fix as soon as possible)

**Comment by tim-moody** [comment]
I took all the is_OS: false out of the OS.yml and put in default_vars rather than having them spread all over the place.

**Comment by tim-moody** [comment]
you need to reboot before awstats works

**Comment by tim-moody** [comment]
how is master broken (not rhetorical)?

**Comment by tim-moody** [comment]
for some reason default_vars has is_rpi:true. should be false

**Comment by georgejhunt** [comment]
So I discovered an is_ubuntu, and an is_redhat missing, when I was running
iiab-admin.

I guess I need to let you fix it the way you want to.

**Comment by georgejhunt** [comment]
These changes demonstrate the brokenness of master. My fault -- for not better testing what I pulled into master after this morning's call

**Pull request merged**
