### PR TITLE
Gitea 1.15 is imminent [now released] ⁠— basic testing with IIAB would be great!

### PR DESCRIPTION
**Pull request by holta**
- https://dl.gitea.io/gitea/1.15
- https://github.com/go-gitea/gitea/tree/release/v1.15
- https://github.com/go-gitea/gitea/blob/main/CHANGELOG.md (e.g. 1.15.0-rc1 from 2021-07-15)
- https://github.com/go-gitea/gitea/milestones
- https://docs.gitea.io

Building on:

- #2725

### CODE REVIEW

**Comment by jvonau** [comment]
Anything that uses lets-encrypt more or less requires a real FQDN to work correctly, using the stock '.lan ' domain just doesn't cut it for ssl.

**Comment by holta** [comment]
RC2 just released:

https://github.com/go-gitea/gitea/releases/tag/v1.15.0-rc2

**Comment by holta** [comment]
Gitea 1.15.0 is now released, with changelog/details here:

https://github.com/go-gitea/gitea/releases/tag/v1.15.0

**Comment by holta** [comment]
Instructions are here — if anybody gets the chance to do some quick spot-checking which would be fantastic:
https://github.com/iiab/iiab/tree/master/roles/gitea#gitea-readme

**Pull request merged**
