### PR TITLE
give apache_user poweroff permission

### PR DESCRIPTION
**Pull request by tim-moody**

### CODE REVIEW

**Comment by holta** [comment]
Supremely important feature in the developing world where electricity is sparse, _thank you Tim!_

**Comment by georgejhunt** [comment]
This should be cherry-picked into rc2 also I think

**Comment by holta** [comment]
> This should be cherry-picked into rc2 also I think

I have no problem if you want to rename it RC3 on the spot as well.  Whatever you do just LMK.

**Comment by holta** [comment]
@tim-moody can you reconfirm the URL remains http://box/iiab-menu/menu-files/services/power_off.php or similar, so I can start getting clean documentation/FAQ in place?

Also: any tips you have for disabling this, so that sneaky kids in schools are blocked from sabotaging (powering off) their teacher/school's IIAB -- is this as easy as deleting /library/www/html/iiab-menu/menu-files/services/power_off.php _(or do you have another recommendation?)_

**Pull request merged**
