### PR TITLE
Lokole sync [transition from Apache lokole.conf -> NGINX lokole-nginx.conf ?]

### PR DESCRIPTION
**Pull request by adamsclafani**
Currently, the IIAB version of the Lokole email client only works in local mode. To work towards online capability, Celery was enabled, which is depended upon by the webapp sync worker. For more information see: [Lokole issue 453](https://github.com/ascoderu/lokole/issues/453), and [Lokole issue 454](https://github.com/ascoderu/lokole/issues/454)

The [development environment repo](https://github.com/arky/iiab-dev-mode) linked in the contributors guide was used. The debian/stretch64 vagrant box was utilized.
@holta @c-w

### CODE REVIEW

**Comment by holta** [comment]
@jvonau can you review this?

**Comment by jvonau** [comment]
Basic form looks fine, needs to have "Disable & Stop" like "'lokole' systemd service, if not lokole_enabled" has for the 2 new service. Could fold the file installation into one stanza and use 'with_items' The 'new*.service" files could(should...) use "Before=" to clarify the starting dependency order.

**Comment by holta** [comment]
@adamsclafani can you consider any of @jvonau's above suggestions?

(If so let us know if you need help!)

**Comment by adamsclafani** [comment]
@holta @jvonau Sure can, thanks much!

**Comment by holta** [comment]
@adamsclafani thanks for your hard work implementing & testing.

Just shout if you get stuck with any of these 3 systemd unit files or otherwise...so this can hopefully be merged very shortly.

**Comment by holta** [comment]
@adamsclafani just a head's up that [IIAB 7.2](https://github.com/iiab/iiab/wiki/IIAB-7.2-Release-Notes) should be released by/around late September.

As you and Nzola very carefully laid out this effort during our several calls back in June and July, you should hopefully make the cut, to get this important Lokole sync included &mdash; but please also understand that everyone strongly prefers a few weeks of beta/final testing &mdash; so ideally try to wrap this up in the coming week ?

_(Helping all with real-world testing where you possibly can :-)_

**Comment by c-w** [comment]
@holta @adamsclafani We'll have to do some net-new work on the Lokole side (adding admin screens to configure registering the client with the cloud email services; this is currently done via a script at hardware setup time but for IIAB we'll have to do this on first start of the app) so I doubt this will be "done done" in time for release 7.2. When will the next release after 7.2 ship?

**Review by c-w — APPROVED** [review]
Changes LGTM! 🚀

We'll have to add some screens in the Flask app to enable admins on first run of the Lokole+IIAB application to register their client with the backend services in Azure to emulate what [install.py's ClientSetup](https://github.com/ascoderu/lokole/blob/0c0d9fe629ecc5857fe3ba162b1fcee0fc82cd2b/install.py#L421-L479) is doing during the Lokole hardware setup so that the sync, restarter, and beat daemons have a real backend to work with. This is task 2. described on https://github.com/ascoderu/lokole/issues/454.

@adamsclafani Let me know if the above is something you'd be interested in working on and we can sync on next steps.

**Comment by holta** [comment]
> We'll have to do some net-new work on the Lokole side (adding admin screens to configure registering the client with the cloud email services; this is currently done via a script at hardware setup time but for IIAB we'll have to do this on first start of the app)

Thanks!

> I doubt this will be "done done" in time for release 7.2

Ok, and no worries.

If most/everything appears to be falling in place by/around Sept 30, that's something to proud of, and possibly even promote (!) so just keep in touch.

> When will the next release after 7.2 ship?

It'd be wonderful if IIAB 8.0 shipped by New Years Day...but...time will tell ;-)

**Comment by adamsclafani** [comment]
@holta I'll have the proposed changes submitted very soon! Is there anything you would like me to put in the before= for the new unit files? As far as the newly implemented services go, I'm not too sure if the startup of them depend on one another.

On another note, we need to get cracking on our end with a few changes as Clemens mentioned, to truly complete this!

**Comment by adamsclafani** [comment]
@c-w I'm definitely interested in step 2. Let's definitely sync up on the next steps!

**Comment by holta** [comment]
> @holta I'll have the proposed changes submitted very soon! Is there anything you would like me to put in the before= for the new unit files? As far as the newly implemented services go, I'm not too sure if the startup of them depend on one another.

@jvonau is the expert, I am not: feel free to go with your instinct, or consult with him &mdash; if there's more to his suggestion here than meets the eye:

> The 'new*.service" files could(should...) use "Before=" to clarify the starting dependency order.

**Comment by jvonau** [comment]
> > @holta I'll have the proposed changes submitted very soon! Is there anything you would like me to put in the before= for the new unit files? As far as the newly implemented services go, I'm not too sure if the startup of them depend on one another.
> 
> @jvonau is the expert, I am not: feel free to go with your instinct, or consult with him — if there's more to his suggestion here than meets the eye:
> 
> > The 'new*.service" files could(should...) use "Before=" to clarify the starting dependency order.

Was just easier to do the changes than explain what to do, see #2513

**Comment by holta** [comment]
This PR was superseded by PRs #2513 and #2514 (now merged).

**Comment by jvonau** [comment]
Any chance somebody could look at creating a nginx webserver config file that uses nginx directly without using apache as the primary webserver? Basically translate the contents of [lokole.conf.j2](https://github.com/iiab/iiab/blob/master/roles/lokole/templates/lokole.conf.j2) for apache to [lokole-nginx.conf.j2](https://github.com/iiab/iiab/blob/master/roles/lokole/templates/lokole-nginx.conf.j2) for nginx.

**Comment by c-w** [comment]
The base Lokole installer uses nginx and you can find our configuration [here](https://github.com/ascoderu/lokole/blob/0c0d9fe629ecc5857fe3ba162b1fcee0fc82cd2b/install.py#L575-L591) if you're interested.

**Comment by holta** [comment]
Thanks @c-w !

Excellent question from @jvonau

Hopefully a volunteer will step forward to make this happen.

Internet-in-a-Box's NGINX README.md is here:
https://github.com/iiab/iiab/tree/master/roles/nginx

**Comment by holta** [comment]
Just to clarify this small task in case @nzola can help us find someone to complete this!

1. Copy https://github.com/iiab/iiab/blob/master/roles/lokole/templates/lokole-nginx.conf.j2 to `/etc/nginx/conf.d/lokole-nginx.conf`
   1. Where `{{ lokole_url }}` is `/lokole` per https://github.com/iiab/iiab/blob/master/roles/lokole/defaults/main.yml#L25
   2. Remove this line, i.e. remove the proxying to Apache:
      ```
      proxy_pass http://127.0.0.1:{{ apache_port }}{{ lokole_url }}/;
      ```
      Aside: `apache_port` is `8090` per https://github.com/iiab/iiab/blob/master/vars/default_vars.yml#L282
   3. **Insert suitable NGINX directive(s) !**
2. Run `systemctl reload nginx`
3. Verify it works (adjust as nec for Lokole functionality!)
4. Permanently comment out https://github.com/iiab/iiab/blob/master/roles/lokole/tasks/main.yml#L57-L58 :
   ```
   - name: SHIM FOR NOW SO ALWAYS DO THE...Enable/Disable/Restart Apache
     include_tasks: apache.yml
   ```

Tangentionally related: #2526 (slow shutdowns due to Lokole's Celery service)

**Comment by holta** [comment]
@adamsclafani

Do you have time to resolve these 3 merge conflicts in the coming week?

Reason: it would be incredible to get this worked out and merged this month &mdash; so that Nzola's shipment to Congo (DRC) is well-integrated in June/July.

cc: @deldesir, re: PR #2775

**Comment by jvonau** [comment]
> @adamsclafani
> 
> Do you have time to resolve these 3 merge conflicts in the coming week?
> 
replaced by 2776

**Comment by nzola** [comment]
What qualification should this person have as far as programming language?

**Comment by jvonau** [comment]
@nzola sit tight, these '3 merge conflicts' are a red herring, only important for those who want to "flamingo" their role in the solution.

**Comment by nzola** [comment]
You said; maybe I can find someone to help. Yes I would do so, but not
being a specialist on software or IT profession, I need help to know what
is the qualification we need to find?

**Comment by holta** [comment]
Replaced by PR #2776.

A big thank you to @adamsclafani for inspiring this effort, motivating many others to push forward.

**Pull request closed without merging**
