### PR TITLE
Modularize & Clean @jvonau's PR #2171 - uWSGI for Captive Portal & Admin Console on NGINX

### PR DESCRIPTION
**Pull request by holta**
Builds on PR #2171 in service of Captive Portal especially (#1182).

### CODE REVIEW

**Comment by holta** [comment]
Tested on 182-rpi4-2g-MIN-0122-PR2171 where...

1) `systemctl status uwsgi` shows all 6 child process (3 for Captive Portal and 3 for Admin Console)
2) http://10.8.0.66:9090 redirects correctly to http://box.lan &mdash; which is a great "quick & dirty" way to test Captive Portal without using an actual WiFi device/phone/etc.  As such, port 9090 is now recorded in https://github.com/iiab/iiab/wiki/IIAB-Networking#list-of-ports--services
3) `netstat | grep 9090` shows results of network transactions such as the above, for about 1-2min until that disappears.  With partial / more permanent records being recorded to `/var/log/uwsgi/app/captiveportal.log`

And just as importantly... `cd /opt/iiab/iiab; ./runrole captive portal` works to enable or disable Captive Portal, depending on the value of `captiveportal_enabled` in [/etc/iiab/local_vars.yml](http://wiki.laptop.org/go/IIAB/FAQ#What_is_local_vars.yml_and_how_do_I_customize_it.3F)

**Comment by holta** [comment]
PS @jvonau suspects Captive Portal WILL work with Ubuntu & Debian internal WiFi AP's too!

@menneal are you able to possibly test that authoritatively for https://github.com/iiab/iiab/issues/2172 if you have an old laptop or similar whose WiFi drivers are supported by Linux / Ubuntu 19.10 / Debian 10.2?  (Or if not just test on RPi for now!)

But it likely won't work with external WiFi AP's (i.e. those connected to IIAB using an Ethernet able) for now~

**Comment by menneal** [comment]
I can test with an 2Gig RPI4. What command should I use to load the version you want tested.  I had been using a full Debian desktop version modified for my projects.  For this test, I'll start with a virgin Raspbian Lite that I just downloaded tonight. Does that plan provide the useful results you require?

**Comment by holta** [comment]
> I can test with an 2Gig RPI4. What command should I use to load the version you want tested.

This is now merged into IIAB's master branch, so use IIAB's regular 1-line installer:

```
curl d.iiab.io/install.txt | sudo bash
```

> I had been using a full Debian desktop version modified for my projects. For this test, I'll start with a virgin Raspbian Lite that I just downloaded tonight. Does that plan provide the useful results you require?

Any OS along the lines of [Raspbian Desktop, Raspbian Lite, Ubuntu 19.10 or Debian 10.2](https://github.com/iiab/iiab/wiki/IIAB-Platforms) is fine, Thanks @menneal !

**Comment by menneal** [comment]
Installing now 19:02 PST

**Comment by menneal** [comment]
Captive portal loaded chrome and iiab on connect to network on windows 10.
Captive portal did not function on linux mint firefox. Redirects from google and yahoo to iiab were missing. box.lan directly entered worked.
I will test on amazon and android tablets later the AM
I used this as a baseline with great success after some changes to .htaccess.
https://braindead-security.blogspot.com/2017/06/building-rogue-captive-portal-for.html

**Pull request merged**
