### PR TITLE
Hostapd enabled

### PR DESCRIPTION
**Pull request by jvonau**
### Fixes Bug
#1599

### CODE REVIEW

**Comment by jvonau** [comment]
skip supplying systemd unit file when hostapd is not enabled,

**Comment by jvonau** [comment]
lets install unit file when hardware is detected.

**Comment by holta** [comment]
Tested on a single-interface Ubuntu 18.04 VM.

Tested on Raspbian Lite 2019-07-10 on 1GB RPi 4.

**Comment by holta** [comment]
Currently testing on a fresh Ubuntu 18.04 VM to verify more fully, thanks to @jvonau

**Comment by holta** [comment]
Confirmed fully working on a fresh install onto an Ubuntu 18.04 VM:
- confirmed that /etc/hostapd/ that does not contain any .conf files:
```
root@box:~# ls -l /etc/hostapd/
total 4
-rwxr-xr-x 1 root root 3129 Aug 13 14:07 ifupdown.sh
```
- confirmed that hostapd unit file is not present -- or masked in this case:
```
root@box:~# ls -l /etc/systemd/system/hostapd.service
lrwxrwxrwx 1 root root 9 Aug 15 12:29 /etc/systemd/system/hostapd.service -> /dev/null
```
- confirmed that /etc/iiab/iiab.env contains `HOSTAPD_ENABLED=False`

**Pull request merged**
