### PR TITLE
Contextualize @jvonau's /etc/php/7.4/fpm/pool.d/asterisk.conf (PR #2930) for FreePBX on NGINX + CHECKREFERER false in /etc/freepbx.conf if pbx_try_nginx + server_name box -> $hostname in /etc/nginx/server.conf

### PR DESCRIPTION
**Pull request by holta**
For @jvonau PR #2930.

Testing is ongoing on an Ubuntu Desktop 20.04 VM.

ASIDE: I earlier installed a pre-release Asterisk 19 [*] as will be released 2021-09-28, so now we know — FreePBX 16 does not yet support it — freepbx.yml's 'install -n' line fails as follows:

> Checking if Asterisk is running and we can talk to it as the 'asterisk' user...Error!", "Unsupported Version of 19", "Supported Asterisk versions: 13, 14, 15, 16, 17, 18"

[*] by running `cd /opt/iiab` then `git clone https://github.com/asterisk/asterisk -b 19`

cc: @lemueldsouza

Refs:

- PR #2899
- PR #2905
- #2914
- PR #2916
- PR #2929

### CODE REVIEW

**Comment by holta** [comment]
> Testing is ongoing on an Ubuntu Desktop 20.04 VM.

If all goes well, this test (192-u20-desk-2931 = 10.8.0.42) should complete before 9AM New York Time / EDT.

**Comment by holta** [comment]
@jvonau @lemueldsouza clicking "Submit" is blocked after logging in to http://10.8.0.42/freepbx (standard field/teacher Admin password) at the bottom of page Settings >> Advanced Settings.

Before even clicking 'Apply Config' (red button on top) the error is:

> Potential Security Breach
You are attempting to modify settings from a URL that does not appear to have come from a FreePBX page link or button. This can occur if you manually typed in the URL below. This action has been blocked because the HTTP_REFERER does not match your current SERVER. If you require this access, you can set Check Server Referrer=false in Advanced Settings to disable this security check
>
> The suspect URL is listed below. If this action is intended, you can click this link and your action will be processed. Do not proceed with this if you did not intended to execute this command as it may result in changes to your configuration.
>
> SUSPECT LINK:  http://box/freepbx/admin/config.php?display=advancedsettings

**Comment by holta** [comment]
URL CORRECTED JUST ABOVE: http://10.8.0.42/freepbx (not .34)

**Comment by holta** [comment]
> action has been blocked because the HTTP_REFERER does not match your current SERVER

@jvonau @lemueldsouza please feel free to log in to 10.8.0.42 if that helps understanding the above?

Does [/etc/nginx/conf.d/freepbx-nginx.conf](https://github.com/holta/iiab/blob/fpm-asterisk/roles/pbx/templates/freepbx-nginx.conf.j2) need to be modified?

Or is the root cause possibly deeper, e.g. in [/etc/php/7.4/fpm/pool.d/asterisk.conf](https://github.com/holta/iiab/blob/fpm-asterisk/roles/pbx/templates/asterisk.conf) ?

**Comment by jvonau** [comment]
That warning occurs with apache also when you are not using 'box' in the browser's url.

**Comment by holta** [comment]
> That warning occurs with apache also when you are not using 'box' in the browser's url.

Not for me.  This above warning/error does not occur with Apache at http://10.8.0.22:83/freepbx

Feel free to log in with standard field/teacher Admin password to reconfirm.  FYI 10.8.0.22 is an Ubuntu Server 21.04 RPi 4 running our Asterisk 18 and FreePBX 16: (installed just over 24h ago)

```
root@box:~# asterisk -V
Asterisk 18.5.1
```

```
root@box:~# amportal a ma list | grep framework
| framework        | 16.0.10.10 | Enabled | GPLv2+  |
```

**Comment by holta** [comment]
> ```
> root@box:~# amportal a ma list | grep framework
> | framework        | 16.0.10.10 | Enabled | GPLv2+  |

Oops I should have used the new version of the (same) command: `fwconsole ma list | grep framework`

**Comment by jvonau** [comment]
There are bigger things to fix like why the user control panel at /ucp is not working under either apache or nginx. Think the browser matters, that variable is passed from the client so FF and chrome could differ. Also note the 'not to be trusted' blurb at https://www.php.net/manual/en/reserved.variables.server.php

**Comment by holta** [comment]
> action has been blocked because the HTTP_REFERER does not match your current SERVER

> Does [/etc/nginx/conf.d/freepbx-nginx.conf](https://github.com/holta/iiab/blob/fpm-asterisk/roles/pbx/templates/freepbx-nginx.conf.j2) need to be modified?
>
> Or is the root cause possibly deeper, e.g. in [/etc/php/7.4/fpm/pool.d/asterisk.conf](https://github.com/holta/iiab/blob/fpm-asterisk/roles/pbx/templates/asterisk.conf) ?

I'm not up to speed, but might this relate to either https://github.com/iiab/iiab/issues/2914#issuecomment-894657637 issue below?

1) `/var/lib/php/asterisk_sessions/` set up at [freepbx.yml#L146-L156](https://github.com/iiab/iiab/blob/master/roles/pbx/tasks/freepbx.yml#L146-L156)

   As used by Apache's [freepbx.conf Line 16](https://github.com/iiab/iiab/blob/master/roles/pbx/templates/freepbx.conf.j2#L16) here:

   `php_value session.save_path /var/lib/php/asterisk_sessions/`

2) [apache.yml Line 13](https://github.com/iiab/iiab/blob/master/roles/pbx/tasks/apache.yml#L13) is:

   ```
   - libapache2-mpm-itk    # To serve FreePBX through a VirtualHost as asterisk user
   ```

   As used by Apache's [freepbx.conf (Lines 12-14)](https://github.com/iiab/iiab/blob/master/roles/pbx/templates/freepbx.conf.j2#L12-L14) here:

   ```
   <IfModule mpm_itk_module>
   AssignUserId asterisk asterisk
   </IfModule>
   ```

**Comment by jvonau** [comment]
> > action has been blocked because the HTTP_REFERER does not match your current SERVER
> 
> I'm not up to speed, but might this relate to either [#2914 (comment)](https://github.com/iiab/iiab/issues/2914#issuecomment-894657637) issue below?

Or there is known less than ideal php code within freebpx so there is an option to disable the code. see 'not to be trusted' link above.

**Comment by holta** [comment]
Just FYI this PR would be extremely safe to merge, e.g. to bring us forward to a common baseline.

(Even if it does not yet allow FreePBX to work as cleanly on NGINX as on Apache.)

**Comment by jvonau** [comment]
Cleanly? Apache is broken also, you just haven't found or not looking for the breakage yet. Good, since you know what to doing you can take the code to completion. I'll go write the blog about the other steps needed and you can grok what is written if I publish my notes.

**Comment by holta** [comment]
> action has been blocked because the HTTP_REFERER does not match your current SERVER

A very basic workaround that works, thanks to @lemueldsouza, is to change `server_name box;` to `server_name 10.8.0.42;` _(or whatever name is hopefully more permanent than that!)_ on Line 3 of [/etc/nginx/server.conf](https://github.com/iiab/iiab/blob/master/roles/nginx/templates/server.conf.j2#L3)

And then run: `fwconsole restart` (or `systemctl restart freepbx`)

This would appear similar to WordPress and Moodle's need to hard-code the main server-name-in-URL explained at https://FAQ.IIAB.IO#WordPress_.26_Moodle_Administration:_What_tips_.26_tricks_exist.3F

**Comment by holta** [comment]
A couple options we might consider to improve IIAB's NGINX configuration on [Line 3 of /etc/nginx/server.conf](https://github.com/iiab/iiab/blob/master/roles/nginx/templates/server.conf.j2#L3) :

1. `server_name {{ iiab_hostname }}.{{ iiab_domain }};`
2. NGINX can dynamically instantiate the machine’s hostname (presumably from /etc/hostname, /etc/hosts and/or similar) if we use (quite literally!) this string: `server_name $hostname;` as documented here: http://nginx.org/en/docs/http/server_names.html#miscellaneous_names

**Comment by holta** [comment]
If necessary we can:

1. Modify http://FAQ.IIAB.IO to explain the `/etc/nginx/server.conf` workaround.
or 
2. A more failsafe approach might be to create an implementer-settable variable like `nginx_server_name: 10.8.0.42` for /etc/iiab/local_vars.yml ?

(While of course noting that Apache doesn't require this hard-coding.  So possibly there might be a more hassle-free solution for NGINX as well.)

**Comment by holta** [comment]
Not necessarily the final word!

But I've added a commit for @lemueldsouza's suggestion, as it seems to at least be an improvement: https://github.com/iiab/iiab/pull/2931/commits/ccff5b30e1c8a601c857bc83820d6f614601bed5

**Comment by jvonau** [comment]
Why apache doesn't need hostname coding, doesn't set hostname:
https://github.com/iiab/iiab/commit/8a1094e964f5ead89bfbc19db132c1d7129d0dbc#diff-8e91957eb883b85f6827d51ba0f5717a52f00690fab0407603f1c9b04716d765
re: server_name $hostname Think we can fudge what is passed to the php scrips with fastcgi_param overriding SERVER_NAME as needed maybe pass pbx and adjust pbx to resolve to localhost also? or maybe just not define server_name? Or multiple times as needed?
>If no server_name is defined in a server block then nginx uses the empty name as the server name.

Remember this whole 'server name' 'domain name' is geared for offline usage from the ground up.

**Comment by holta** [comment]
> or maybe just not define server_name?

Interesting idea.

Just FYI when I tried that, an empty string propagates into HTTP_REFERER e.g. `http:///freepbx/admin/config.php?display=advancedsettings` &mdash; and so is similarly blocked, with the usual warning/error message, "action has been blocked because the HTTP_REFERER does not match your current SERVER".

**Comment by jvonau** [comment]
I'm accessing over localhost with no errors when pressing 'Apply Config' so perhaps this is intended behavior as a security measure? Does it make a difference if you use eth0's or tun0's ip address to access the machine?

**Comment by holta** [comment]
An ugly approach to permanently force off FreePBX's checking of HTTP_REFERER, would be to comment out these 3 lines:

https://git.freepbx.org/projects/FREEPBX/repos/framework/browse/amp_conf/htdocs/admin/config.php#202-204

I tested this workaround within `/var/www/html/freepbx/admin/config.php` and it certainly works.

( If we later decide such a brute force approach is really necessary, it could of course also be done pre-install within `/opt/iiab/freepbx/amp_conf/htdocs/admin/config.php` )

**Comment by holta** [comment]
> Does it make a difference if you use eth0's or tun0's ip address to access the machine?

Both work for me, e.g. 192.168.0.x or 10.8.0.y

**Comment by jvonau** [comment]
sorry should of been clearer, to save setting or is that depended on which one is defined as server_name?

**Comment by jvonau** [comment]
```
sudo fwconsole setting CHECKREFERER 0
Changing "CHECKREFERER" from [1] to [0]
```

**Comment by jvonau** [comment]
With /etc/nginx/server.conf more static once the install is preformed, what you wanting is to be able to dynamically assign all possible ip addresses found on the machine and populate 'server_name' to cover all possible points of access? Or just let the user edit to fit their layout.... Or have 'nginx_server_names' take a string of names? Lots of ways to address this.

**Comment by jvonau** [comment]
> An ugly approach to permanently force off FreePBX's checking of HTTP_REFERER, would be to comment out these 3 lines:
> 
> https://git.freepbx.org/projects/FREEPBX/repos/framework/browse/amp_conf/htdocs/admin/config.php#202-204
> 
> I tested this workaround within `/var/www/html/freepbx/admin/config.php` and it certainly works.
> 
> ( If we later decide such a brute force approach is really necessary, it could of course also be done pre-install within `/opt/iiab/freepbx/amp_conf/htdocs/admin/config.php` )

Don't think you need to hack try the above command, `sudo fwconsole setting -l` is your friend.

**Comment by holta** [comment]
Eureka, adding `$amp_conf['CHECKREFERER'] = false;` near the BOTTOM of /etc/freepbx.conf is one workaround that demonstrably works.

Apologies @lemueldsouza, my mistakes earlier were:
- adding this near the TOP of the file (it would need to be near the bottom)
- using quotation marks (when I should have used `false` or `0`)

**Comment by holta** [comment]
> `fwconsole setting -l`

Very useful!

(Though it doesn't take `/etc/freepbx.conf` into account, so doesn't quite show the full picture.)

**Comment by holta** [comment]
> [Variables must be added] near the BOTTOM of /etc/freepbx.conf

@jvonau this also means that my code at [freepbx.yml#L238-L249](https://github.com/iiab/iiab/blob/master/roles/pbx/tasks/freepbx.yml#L238-L249) was very flawed here:

```
#   lineinfile:
#     path: /etc/freepbx.conf
#     insertafter: '^<\?php$'    # Match exact line '<?php'
#     line: "$amp_conf['AMPASTERISKWEBUSER'] = 'www-data';"
```

The fix is the change the `insertafter:` line to: `insertbefore: '^\?>'`

(Might this shed any light, or is running this no longer useful in any way?)

**Comment by jvonau** [comment]
> > [Variables must be added] near the BOTTOM of /etc/freepbx.conf
> 
> @jvonau this also means that my code at [freepbx.yml#L238-L249](https://github.com/iiab/iiab/blob/master/roles/pbx/tasks/freepbx.yml#L238-L249) was very flawed here:
> 
> ```
> #   lineinfile:
> #     path: /etc/freepbx.conf
> #     insertafter: '^<\?php$'    # Match exact line '<?php'
> #     line: "$amp_conf['AMPASTERISKWEBUSER'] = 'www-data';"
> ```
> 
> The fix is the change the `insertafter:` line to: `insertbefore: '^\?>'`
> 
> (Might this shed any light, or is running this no longer useful in any way?)

Keep that in the back pocket, might be needed else where but looks like now its not needed with this new fpm setup.

**Comment by holta** [comment]
> sorry should of been clearer, to save setting or is that depended on which one is defined as server_name?

Maybe I'm not quite understanding the question, but FYI:

FreePBX by default requires that the `X` in `http://X/Y/Z.php` must match the `A` in NGINX's `server_name: A B C;`

**Comment by jvonau** [comment]
server_name can be more than one value, just a string before the ; and freepbx is enforcing a match only on A when your target match is C in the list?

**Comment by holta** [comment]
> server_name can be more than one value, just a string before the ; and freepbx is enforcing a match only on A when your target match is C in the list?

I think we're saying the same thing in different ways:

- B and C (and anything to the right) are effectively ignored by FreePBX.
- A (the leftmost value) is what matters to FreePBX's HTTP_REFERER logic.

> FreePBX by default requires that the `X` in `http://X/Y/Z.php` must match the `A` in NGINX's `server_name: A B C;`

**Comment by holta** [comment]
This PR isn't the final word, but takes several very significant steps forward: so should probably be merged?

@lemueldsouza do you have an opinion?

**Comment by holta** [comment]
> ASIDE: I earlier installed a pre-release Asterisk 19 [*] as will be released 2021-09-28, so now we know — FreePBX 16 does not yet support it — freepbx.yml's 'install -n' line fails as follows:
> 
> > Checking if Asterisk is running and we can talk to it as the 'asterisk' user...Error!", "Unsupported Version of 19", "Supported Asterisk versions: 13, 14, 15, 16, 17, 18"
> 
> [*] by running `cd /opt/iiab` then `git clone https://github.com/asterisk/asterisk -b 19`

If there's later a need to try out Asterisk 19 with FreePBX 16, it's likely as easy as circumventing the above trigger warning, by commenting out these 6 lines ([lines 38-43](https://github.com/FreePBX/framework/blob/release/16.0/install.php#L38-L43)) from `/opt/iiab/freepbx/install.php` :

```php
if (version_compare($astversion, "13", "lt") || version_compare($astversion, "19", "ge")) {
     out(sprintf(_("<error>Error!</error>")));
     out(sprintf(_("<error>Unsupported Version of %s </error>"), $astversion));
     out(sprintf(_("<error>Supported Asterisk versions: 13, 14, 15, 16, 17, 18</error>")));
     exit(1);
}
```

**Comment by jvonau** [comment]
Not that I'm a fan of the "server_name $hostname;" change as that is changing the new default to 'box.lan' away from just "box" as has it has been from the introduction of nginx. @tim-moody @georgejhunt Back that change out and let it the PR rip as there would be no 'global changes' just pbx related changes and we can leave "server_name" for another day.

**Comment by holta** [comment]
I tested `server_name $hostname;` on [Line 3 of /etc/nginx/server.conf](https://github.com/holta/iiab/blob/fpm-asterisk/roles/nginx/templates/server.conf.j2#L3) carefully, by logging into BIG-sized IIAB's ~20 main apps and clicking around a bit.  With a fresh install of this PR onto a Ubuntu Server 20.04 LTS VM at 10.8.0.54

Certainly `box.lan` works better than `box` in my experience over the years, hence the reason it's used across most of our documentation.

Of course @darkenvy has good reason to feel differently, given that `/etc/hosts` technically [doesn't allow periods](https://github.com/iiab/iiab/issues/2904#issuecomment-894540138) ... but this seems to be ... a quite different issue and file in question:

- #2904

**Comment by holta** [comment]
FQDN's are predominant to the right side of NGINX's `server_name` directives, across [NGINX's documentation](http://nginx.org/en/docs/http/server_names.html).

Let's follow these global norms, rather than being different just for the sake of being different.

This will also somewhat improve the visibility of `box.lan` (as we've seen with FreePBX, and setting a better precedent for other possibly similar apps/services in future if so).

Unless there's truly a compelling reason.  Which I frankly do not see.  @darkenvy feel free to suggest anything!

In any case, the time to standardize NGINX (as best we can anyway!) is now.

**Comment by holta** [comment]
Reducing bureaucracy is another advantage of `server_name $hostname;` — some basic softcoding comes for free.

This gives field operators somewhat more direct ongoing Command-Line control over their very own Linux hostname and domain (using very standard tools like `hostnamectl` or similar).

i.e. with somewhat less drowning in obscure/obtuse Ansible ritualizations and incantation — like `cd /opt/iiab/iiab ; ./runrole nginx` etc.

**Comment by holta** [comment]
This PR was reviewed by @lemueldsouza, who is in favor as this gives us a new shared baseline.

To try to work out any remaining bugs with FreePBX 16 on NGINX and beyond.

**Comment by jvonau** [comment]
> FQDN's are predominant to the right side of NGINX's `server_name` directives, across [NGINX's documentation](http://nginx.org/en/docs/http/server_names.html).
> 
> Let's follow these global norms, rather than being different just for the sake of being different.
>

That would of been nice to do before nginx hit the seen. You are aware that stock default nginx site uses 'server_name _;' with 'server_name example.com;' intended to be a Virtual Host as supplied by apt? The full file set can be obtained by downloading the  nginx-common deb file and viewing the contents with your favorite extraction tool. 
 [default.txt](https://github.com/iiab/iiab/files/6969106/default.txt)

> This will also somewhat improve the visibility of `box.lan` (as we've seen with FreePBX, and setting a better precedent for other possibly similar apps/services in future if so).
> 

The only place where box.lan can or should be used from is on the LAN clients, http://box/home or http://box.lan/home should both work from the LAN with some clients needing to use box.lan to workaround the browser trying to do search on what is in the browser's address bar. Working on the iiab server machine 'box' or 'localhost' should work, having box.lan work without having the LAN present is the hack within /etc/hosts.

> Unless there's truly a compelling reason. Which I frankly do not see. @darkenvy feel free to suggest anything!
> 
> In any case, the time to standardize NGINX (as best we can anyway!) is now.

In the interests of being 'more normal' are you going to rewrite the unusual use of conf.d?

**Comment by holta** [comment]
Very informative post just above.  Thx @jvonau.

> The only place where box.lan can or should be used from is on the LAN clients

Are you saying we should solve the #2904 bug @darkenvy surfaced a week ago, now or soon?

- #2904

> > In any case, the time to standardize NGINX (as best we can anyway!) is now.
>
> In the interests of being 'more normal' are you going to rewrite the unusual use of conf.d?

Not this week.

But if there's a way to make IIAB's NGINX layout more cleanly understandable and natural to NGINX gurus worldwide, we should definitely consider and welcome that.

Later this year or absolutely any time someone chooses to do a quality job, including explaining their work by revising or overhauling https://github.com/iiab/iiab/blob/master/roles/nginx/README.md &mdash; converted to [AsciiDoc](https://www.raspberrypi.org/blog/bring-on-the-documentation/) ([.adoc](https://asciidoc.org/)) ideally!

cc: @deldesir, @lemueldsouza

**Comment by jvonau** [comment]
> > `fwconsole setting -l`
> 
> Very useful!
> 
> (Though it doesn't take `/etc/freepbx.conf` into account, so doesn't quite show the full picture.)

Think you are misunderstanding that freepbx is storing these setting in some sort of database if you can't toggle these setting from http://someip/freepbx/admin/config.php?display=advancedsettings (where 'Check Server Referrer' lives see pic) then I think the connection to the database backend is not configured correctly. By populating /etc/freepbx.conf you are just altering the displaying of the settings not actually changing them like how 'fwconsole setting' can and does. Try to alter some values within 'advancedsettings' then check if the value was changed in the backend with `fwconsole setting -l`
pbxsettings

Think the missing piece is the mariadb-connector-odbc which is pretty easy to build

**Comment by holta** [comment]
> By populating /etc/freepbx.conf you are just altering the displaying of the settings not actually changing them like how 'fwconsole setting' can and does.

It's true there are 3 main ways to change FreePBX settings:

1. http://box/freepbx/admin/config.php?display=advancedsettings >> Submit
2. Run `fwconsole set CHECKREFERER 0` e.g. to set CHECKREFERER to false
3. Edit `/etc/freepbx.conf`

> Try to alter some values within 'advancedsettings' then check if the value was changed in the backend with `fwconsole setting -l`

Methods 1. and 2. seem to be 100% equivalent, changing settings in FreePBX's backend / internal database / stored settings.

Method 3. is the strongest, overriding FreePBX's stored settings set by 1. or 2. (or set during the initial install of FreePBX!)

FYI the two approaches below to viewing settings (i.e. their values) are equivalent — displaying the same value, either way:

- http://box/freepbx/admin/config.php?display=advancedsettings
- `fwconsole set -l`
  - Or `fwconsole set CHECKREFERER` which shows the value of setting CHECKREFERER in a more human-readable form

Background: `fwconsole set` commands are always equivalent to `fwconsole setting` — run `fwconsole set -h` for more details.

> Think the missing piece is the mariadb-connector-odbc which is pretty easy to build

This seems necessary for CDR i.e. Call Detail Records (or so it's claimed?!)

Are you able to check?

**Comment by jvonau** [comment]
Things found in freepbx.log
>Aug  9 15:30:09] WARNING[140148] res_odbc.c: res_odbc: Error SQLConnect=-1 errno=0 [unixODBC][Driver Manager]Data source name not found, and no default driver specified
[Aug  9 15:30:09] NOTICE[140148] res_odbc.c: Registered ODBC class 'asteriskcdrdb' dsn->[MySQL-asteriskcdrdb]
[Aug  9 15:30:09] NOTICE[140148] cdr.c: CDR simple logging enabled.
[Aug  9 15:30:09] WARNING[140148] res_odbc.c: res_odbc: Error SQLConnect=-1 errno=0 [unixODBC][Driver Manager]Data source name not found, and no default driver specified
[Aug  9 15:30:09] WARNING[140148] cdr_adaptive_odbc.c: No such connection 'asteriskcdrdb' in the 'asteriskcdrdb' section of cdr_adaptive_odbc.conf.  Check res_odbc.conf.

Things found in ucp_err.log
>Error: Cannot find module 'mariasql' 

`ls /var/www/html/freepbx/admin/modules/ucp/node/node_modules`

Running `sudo fwconsole ma downloadinstall ucp --force` cleaned up for readability
>Leaving directory '/var/www/html/freepbx/admin/modules/ucp/node/node_modules/mariasql/build' 
gyp ERR! build error  
gyp ERR! stack Error: `make` failed with exit code: 2 
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23) 
gyp ERR! stack     at ChildProcess.emit (events.js:400:28) gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12) 
gyp ERR! System Linux 5.8.0-1032-raspi 
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" 
gyp ERR! cwd /var/www/html/freepbx/admin/modules/ucp/node/node_modules/mariasql 
gyp ERR! node -v v14.17.4 gyp ERR! node-gyp -v v5.1.0 
gyp ERR! not ok  
npm ERR! code ELIFECYCLE 
npm ERR! errno 1 
npm ERR! mariasql@0.2.6 install: `node-gyp rebuild` 
npm ERR! Exit status 1 
npm ERR!  
npm ERR! Failed at the mariasql@0.2.6 install script. 
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.  
npm ERR! A complete log of this run can be found in: 
npm ERR!     /var/lib/asterisk/.npm/_logs/2021-08-05T23_08_30_253Z-debug.log 
[npm-cache] [ERROR] 
[npm] error running npm install 
[npm-cache] [ERROR] error installing dependencies  [] []

but the install does not stop
>Failed updating libraries!
Stopping old running processes...Done
Refreshing all UCP Assets, this could take a while...
Generating Module Scripts...Done
Generating Module CSS...Done
Generating Main Scripts...Done
Generating Main CSS...Done
Done!
Generating CSS...Done
Module ucp version 16.0.12 successfully installed
Updating Hooks...Done
Chowning directories...Done


https://github.com/mscdex/node-mariasql/issues/209

I'm not spending any more time looking at this BS, the install is broken and has nothing to do with nginx and everything to do with the version on node installed #2914, and maybe the bump to asterisk 18 in #2896

**Comment by holta** [comment]
> Things found in freepbx.log

> Things found in ucp_err.log

It's great to have the above internal details written down &mdash; so we can monitor them in coming months &mdash; as FreePBX 16 and Asterisk 19 (ETA 2021-08-28) final releases are published.

Thanks @jvonau.

**Pull request merged**
