### PR TITLE
ansible 2.3.1

### PR DESCRIPTION
**Pull request by jvonau**
intended as a replacement for scripts/ansible

### CODE REVIEW

**Comment by georgejhunt** [comment]
I do not know whether this is smoke tested. Scripts/ansible has been
working on all platforms for a long time.  I'd rather just change the
target version at the bottom of the script we have been using.

Unless there is a persuasive reason to do otherwise.

**Comment by jvonau** [comment]
It's intended for testing along with [this branch](https://github.com/iiab/iiab/compare/master...jvonau:strict), shifting CentOS back to using rpms avoiding pip to install ansible. The goal is to figure out why kalite is messed up on CentOS with the [ssl error](https://groups.google.com/forum/#!topic/xsce-devel/C39HGCwMKFk). The other branch is in response to [Andreas Gros's June 18 CentOS install error.](https://groups.google.com/forum/#!topic/xsce-devel/9sgqLBBoDwg) and noted in issue #78 which I think was introduced in PR #20's on June 9. Short story is 'if' pip does need to be updated, do it once and do it early. Now if a python program requires a specific version of a library and not the latest/greatest then virtual environments (#162 #163 ) might be used in place of using pip on what are shared libraries that all python programs use.

**Comment by holta** [comment]
@georgejhunt suggested I give "apt install ansible" a shot which I did: very refreshing that this installs within ~1 minute instead of the usual ~7 minutes, as documented in #249.

However apt (currently) installs Ansible 2.2.1.0-2 on Raspbian, which (as we've long known!) **does not work with IIAB's Admin Console** ...all jobs seem to appear in http://box/admin -> Utilities -> Display Job Status as "SCHEDULED" ...but never proceed beyond that :/

Can we lock in a particular version of Ansible using "apt-get install ansible=2.2.1.0-2" ?  Yes we *could* but which one(s) are actually workable+available ?!

Unfortunately "apt-get install ansible=2.2.0.0-x" does not work, where x = {0, 1, 2, 3, 4}

And/or: can deeper issues be worked out with @tim-moody to work with a more modern version of Ansible now a year later (possibly 2.3.2 released 2017-08-08...or hypothetically even 2.4.x in the nearby future?)

**Comment by holta** [comment]
@jvonau any idea if this PR #164 can be made faster than the usual dog-slow "cd /opt/iiab/iiab/scripts/; ./ansible" ?  (Whether or not using any of the ideas in #249 !)

**Comment by jvonau** [comment]
On Sat, Sep 16, 2017 at 11:53 AM, A Holt <notifications@github.com> wrote:

> @georgejhunt <https://github.com/georgejhunt> suggested I give "apt
> install ansible" a shot which I did: very refreshing that this installs
> within ~1 minute instead of the usual ~7 minutes!
>
​much better​



> However it installs Ansible 2.2.1.0-2 on Raspbian, which (as we've long
> known!) does not work with IIAB's Admin Console...all jobs seem to appear
> in Utilities -> Display Job Status as "SCHEDULED" ...but never proceed
> beyond that.
>
Can't keep switching distros or running old libraries because the console
pukes, figure out what is wrong with the code in the playbook or the
console and fix it. ​That was a year ago and I found old code that might of
been responsible in issue #66.... Perhaps it is time to revisit what the
Admin-Console will do with the current code on 2.2.1?

> Can we lock in a particular version of Ansible using "apt-get install
> ansible=2.2.1.0-2" ? Yes we can but which one(s) are actually available?
>
​If you can find the versions a local apt install like usbmount ​can be
done. Or use apt to grab the base dependencies, remove the .deb then pip
install what you want would be better than what is in 'ansible' now.



> Unfortunately "apt-get install ansible=2.2.0.0-x" does not work, where x =
> {0, 1, 2, 3, 4}
>
> And/or can deeper issues be worked out with @tim-moody
> <https://github.com/tim-moody> to work with a more modern version of
> Ansible now a year later (possibly 2.3.2 released 2017-08-08...or
> hypothetically even 2.4.x in the nearby future?)
>
​Well you have ansible installed give runasible and install the console and
see what occurs.... And if there are issues where can the log file be
retrieved from?​

**Comment by holta** [comment]
Clarif for @jvonau: Ansible 2.2.1 runs to completion with IIAB's core ./runansible and also when installing Admin Console using "cd /opt/iiab/iiab-admin-console/; ./install"

True the installation of 2.2.0 remains a royal slowpoke, but prob will have to do for IIAB 6.4 (I and @georgejhunt were both hoping for a more drop-in rapidly-installing replacement 2.2.0, accelerating the contributor community's rapid experimentation on RPi3, but that just might not exist for 2.2.0 / IIAB 6.4...)

**Comment by jvonau** [comment]
On Sat, Sep 16, 2017 at 2:00 PM, A Holt <notifications@github.com> wrote:

> Clarif for @jvonau <https://github.com/jvonau>: Ansible 2.2.1 runs to
> completion with IIAB's core ./runansible and also when installing Admin
> Console using "cd /opt/iiab/iiab-admin-console/; ./install"
>
​Now do a 'save change console run'... lets see if what you install/enabled
in local_vars runs.​



> True the installation 2.2.0 remains a royal slowpoke, but prob will have
> to do for IIAB 6.4 (I and@georgejhunt were both hoping for a more drop-in
> rapidly-installing replacement 2.2.0, accelerating the contributor
> community's rapid experimentation on RPi3, but that just might not exist
> quite...)
>

​I rather see the use of pip go away for installing ansible

**Comment by holta** [comment]
> do a 'save change console run'

@jvonau if you're talking about http://box/admin -> Configure -> "Save Configuration" and "Install Configured Options" buttons, see what I wrote above ~2h ago:

> all jobs seem to appear in http://box/admin -> Utilities -> Display Job Status as "SCHEDULED" ...but never proceed beyond that :/

**Comment by jvonau** [comment]
console path need adjusting #249

**Comment by georgejhunt** [comment]
Chose to use what's in debian 9

**Comment by jvonau** [comment]
needs work yet

**Comment by tim-moody** [comment]
can we move this to iiab-factory/box/generic

**Comment by jvonau** [comment]
Smoketested in #305 but stale data in this PR do to premature closure. https://github.com/iiab/iiab-factory/pull/31

**Pull request closed without merging**
