### PR TITLE
Wifi3 - simultaneous AP & WiFi-as-client on RPi (using dnsmasq)

### PR DESCRIPTION
**Pull request by georgejhunt**
### Fixes Bug
Permits wifi to be used simultaneously upstream and downstream, with the downstream under a bridge, which is compatible with bluetooth.
### Description of changes proposed in this pull request.
Creates virtual wifi device, and assigns it a different MAC address
### Smoke-tested in operating system.
Moved back and forth between rpi3 and rpiW. Does not run on ubuntu 18.04. Not tested on CentOS. Previous PR (#690) was tested on debian-9, but needs validation if this is to be included in 6.5.

### CODE REVIEW

**Comment by georgejhunt** [comment]
Passes equivalent of a smoke test on debian9 and ubuntu16 on VM test machine.  Still requires functional test, which I only trust on real hardware.

**Comment by tim-moody** [comment]
rpi 3, latest raspbian lite with local_vars:
```
# for PR 697
# dhcpd
dhcpd_install: False
dhcpd_enabled: False

# named
named_install: False
named_enabled: False

dnsmasq_enabled: True
dnsmasq_install: True

TASK [network : include_tasks] *************************************************************************************************************************************************************
included: /opt/iiab/iiab/roles/network/tasks/enable_services.yml for 127.0.0.1

TASK [network : Disable the Access Point 'hostapd' service] ********************************************************************************************************************************
skipping: [127.0.0.1]

TASK [network : Disable dhcpd service] *****************************************************************************************************************************************************
skipping: [127.0.0.1]

TASK [network : Enable dhcpd service] ******************************************************************************************************************************************************
skipping: [127.0.0.1]

TASK [network : Copy /etc/sysconfig/dhcpd file] ********************************************************************************************************************************************
skipping: [127.0.0.1] => (item={u'dest': u'/etc/sysconfig/dhcpd', u'src': u'dhcp/dhcpd-env.j2', u'mode': u'0644'})
skipping: [127.0.0.1] => (item={u'dest': u'/etc/dhcpd-iiab.conf', u'src': u'dhcp/dhcpd-iiab.conf.j2', u'mode': u'0644'})

TASK [network : Copy named file] ***********************************************************************************************************************************************************
changed: [127.0.0.1] => (item={u'dest': u'/var/named-iiab/', u'src': u'named/school.local.zone.db', u'mode': u'0644'})
changed: [127.0.0.1] => (item={u'dest': u'/var/named-iiab/', u'src': u'named/school.internal.zone.db', u'mode': u'0644'})

TASK [network : Enable named service] ******************************************************************************************************************************************************
skipping: [127.0.0.1]

TASK [network : Disable named service] *****************************************************************************************************************************************************
skipping: [127.0.0.1]

TASK [network : Disable dnsmasq] ***********************************************************************************************************************************************************
skipping: [127.0.0.1]

TASK [network : dnsmasq copy config file to /etc] ******************************************************************************************************************************************
changed: [127.0.0.1]

TASK [network : Enable dnsmasq] ************************************************************************************************************************************************************
fatal: [127.0.0.1]: FAILED! => {"changed": false, "msg": "Could not find the requested service dnsmasq: host"}
```

**Comment by holta** [comment]
See PR #699's proposed modif of [default_vars.yml](https://github.com/iiab/iiab/blob/master/vars/default_vars.yml)  in support of IIAB 6.6...
- http://wiki.laptop.org/go/IIAB/6.6
- https://github.com/iiab/iiab/milestone/3

**Comment by tim-moody** [comment]
I ran iiab-hotspot-on and moved the card to a W. I can connect to the hotspot, but can not ssh in or see anything with browser. box.lan is not resolved and can not connect with 172.18.96.1. nmap sees it, but windows can not ping it (or gets no response)

**Comment by holta** [comment]
> I ran iiab-hotspot-on and moved the card to a W. I can connect to the hotspot, but can not ssh in or see anything with browser. box.lan is not resolved and can not connect with 172.18.96.1. nmap sees it, but windows can not ping it (or gets no response)

Just a clarif that @tim-moody is running on Raspbian 2018-03-13 Lite.

**Comment by georgejhunt** [comment]
Would you verify that it is still failing? The W is sloooow, and take a
long time to do fsck (I've never done 128GB)


Synopsis:

I downloaded 2018-3-13, put #697 on it, did "iiab-install", did a
iiab-hotspot-on, connected with my laptop, and verified ssh, and browser
access (on a rpi3)

Then I transferred the sd card to piW, and waited for fsck (I was using a
32GB SD).  Without a monitor on it, it is hard to verify that it has booted
completely.

###############################
Log:
What follows is history (abridged for troublshooting a bad ethernet wire)
17  apt-get install -y git
   18  raspi-config
   19  git clone ssh://10.10.123.13/opt/git/tools
   20  cd tools/
   21  ./ssdebian d(puts my software keys, and points to squid proxy in
bashrc)
   22  ./debian-startup (reproduced below)
. . .
   28  git checkout -b wifi3 ghunt/wifi3
   29  ll vars/
   30  ./iiab-install
. . .
   44  cd ../iiab-admin-console/
   45  ./install
   46  cd ../iiab-menu/
   47  ./cp-menus
   48  ip a
   49  cd
   50  cd tools/
   51  ls
   52  cp wpa_supplicant.conf /etc/wpa_supplicant/
   53  iiab-hotspot-on
   54  ip a
needed to change the ssid to something unique
   55  vi /etc/hostapd/hostapd.conf
   56  sr hostapd
   57  ip a
(used laptop to verify ssh and browser access  to the rpit3)
   58  poweroff
Transferred SD to piW

   59  ssh box.lan
   60  cat /etc/hostapd/hostapd.conf
   61  iiab-internet-on -f
   62  ping yahoo.com
   63  history|less
   64  history>process

##############################################################
Then to test from my linux laptop:

[root@linux ~]# ssh box.lan
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@    WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
IT IS POSSIBLE THAT SOMEONE IS DOING SOMETHING NASTY!
Someone could be eavesdropping on you right now (man-in-the-middle attack)!
It is also possible that a host key has just been changed.
The fingerprint for the ECDSA key sent by the remote host is
SHA256:S3cYKrFu1LwsS+8jIgmLzkfPsS5EhkZ3zSMwdhC+RrQ.
Please contact your system administrator.
Add correct host key in /root/.ssh/known_hosts to get rid of this message.
Offending ECDSA key in /root/.ssh/known_hosts:5
Password authentication is disabled to avoid man-in-the-middle attacks.
Keyboard-interactive authentication is disabled to avoid man-in-the-middle
attacks.
Linux box.lan 4.9.80+ #1098 Fri Mar 9 18:51:28 GMT 2018 armv6l

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Fri Mar 16 04:34:29 2018 from 172.18.123.84

SSH is enabled and the default password for the 'iiab-admin' user is
unchanged.
This is a security risk - please login as the 'iiab-admin' user and type
'passwd' to change password.

root@box:~# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group
default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
2: wlan0: <BROADCAST,MULTICAST,PROMISC,UP,LOWER_UP> mtu 1500 qdisc
pfifo_fast state UP group default qlen 1000
    link/ether b8:27:99:12:34:56 brd ff:ff:ff:ff:ff:ff
    inet 10.10.123.212/16 brd 10.10.255.255 scope global wlan0
       valid_lft forever preferred_lft forever
3: br0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP
group default qlen 1000
    link/ether b8:27:eb:ef:35:30 brd ff:ff:ff:ff:ff:ff
    inet 172.18.96.1/19 brd 172.18.127.255 scope global br0
       valid_lft forever preferred_lft forever
4: wlan0_ap: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast
master br0 state UP group default qlen 1000
    link/ether b8:27:eb:ef:35:30 brd ff:ff:ff:ff:ff:ff
root@box:~# exit
logout
Connection to box.lan closed.
[root@linux ~]# ping yahoo.com
PING yahoo.com (206.190.39.42) 56(84) bytes of data.
64 bytes from 206.190.39.42: icmp_seq=1 ttl=128 time=42.1 ms
64 bytes from 206.190.39.42: icmp_seq=2 ttl=128 time=47.4 ms
64 bytes from 206.190.39.42: icmp_seq=3 ttl=128 time=59.8 ms
^C
--- yahoo.com ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 6049ms
rtt min/avg/max/mdev = 42.112/49.819/59.873/7.442 ms
[root@linux ~]#

################################################################
debian-startup script:
#!/bin/bash -x
# required to start loading XSCE
set -e
#source /root/tools/ssdebian
#source /root/.bashrc

# use the normal ansible install to bring in the dependencies
apt-get -y update
apt-get -y upgrade
apt-get install -y  mlocate vim tree

cd /opt
mkdir iiab
cd iiab
git clone https://github.com/iiab/iiab
pushd iiab
git remote add ghunt https://github.com/georgejhunt/iiab
git fetch --all
popd
git clone https://github.com/iiab/iiab-admin-console
pushd iiab-admin-console
git remote add ghunt https://github.com/georgejhunt/iiab-admin
git fetch --all
popd
git clone https://github.com/iiab/iiab-factory
pushd iiab-factory
git remote add ghunt https://github.com/georgejhunt/iiab-factory
git fetch --all
popd
git clone https://github.com/iiab/iiab-menu
cd iiab
# install ansible and all the dependencies
#apt-get install -y ansible
./scripts/ansible (installed version 2.4.2)
# the ansible current version 2.2.1 has a flaw which the following fixes
#sed -i 's/StrictVersion/LooseVersion/g'
/usr/lib/python2.7/dist-packages/ansible/modules/core/web_infrastructure/htpasswd.py


cd /opt/iiab/iiab/vars
wget download.iiab.io/6.4/rpi/local_vars_min.yml
wget download.iiab.io/6.4/rpi/local_vars_big.yml
wget download.iiab.io/6.4/rpi/local_vars.yml
mv local_vars.yml local_vars_med.yml
ln -sf local_vars_min.yml local_vars.yml
exit 1

**Comment by tim-moody** [comment]
I minified the image from the 128G card and wrote to 32G card
I attached a monitor
Put into W and booted
login prompt appeared on the monitor in less than 30 seconds
connected to ssid from laptop successfully
my ip address is 172.18.116.88, gw 172,18,96.1
can not connect over ssh to either 172,18,96.1 or box.lan (timeout)
browser times out on both as well

**Comment by tim-moody** [comment]
put the same 32G card into rpi 3
I was able to ssh in fairly quickly (over wire), which makes me think resizing was done on W.
BUT (and I didn't check before) my laptop can not connect on ssh or browser as with the W.
SO don't think the problem is the W.

**Comment by tim-moody** [comment]
win10 desktop with putty 0.70, same version as laptop

**Comment by georgejhunt** [comment]
Can you give the failing SD card a wififails handle, and put it on the vpn
via the wire that works?

**Comment by tim-moody** [comment]
I added a dongle to the W and now have wired ssh and http access to it via the wire.

**Comment by georgejhunt** [comment]
I connected and looked around. The /boot/rpi-startup2 appears to have
pretty much what I remember to be required.

There are no received packets/bytes on wlan0_ap. I wonder if you could
change the SSID, and drop back to no security.
My hostapd looks like:
# Basic configuration

interface=wlan0_ap

ssid=wifi3
channel=1
bridge=br0

# Hardware configuration
driver=nl80211
country_code=US
# limit emissions to what is legal in country
ieee80211d=1
hw_mode=g

-- just to see.

If you were able to pass data on the rpi3 through the wifi, that would be a
data point -- though I think you said no data on wifi at all on any
hardware.

**Comment by tim-moody** [comment]
if I remove security I can ssh in and access by http

it is also acting as a  gateway

**Comment by tim-moody** [comment]
so perhaps this is unrelated to 697, though security used to work.

**Comment by tim-moody** [comment]
N.B. iiab_gateway_enabled: False

**Comment by tim-moody** [comment]
I set it back to secure
root@box:/etc/hostapd# systemctl status hostapd
● hostapd.service - Hostapd IEEE 802.11 AP, IEEE 802.1X/WPA/WPA2/EAP/RADIUS Authenticator
   Loaded: loaded (/etc/systemd/system/hostapd.service; disabled; vendor preset: enabled)
   Active: active (running) since Fri 2018-03-16 19:38:51 UTC; 5s ago
 Main PID: 10792 (hostapd)
   CGroup: /system.slice/hostapd.service
           └─10792 /usr/sbin/hostapd -P /run/hostapd.pid /etc/hostapd/hostapd.conf

Mar 16 19:38:51 box.lan systemd[1]: Started Hostapd IEEE 802.11 AP, IEEE 802.1X/WPA/WPA2/EAP/RADIUS Authenticator.
Mar 16 19:38:51 box.lan hostapd[10792]: Configuration file: /etc/hostapd/hostapd.conf
Mar 16 19:38:51 box.lan hostapd[10792]: Failed to create interface mon.wlan0_ap: -95 (Operation not supported)
Mar 16 19:38:51 box.lan hostapd[10792]: wlan0_ap: interface state UNINITIALIZED->COUNTRY_UPDATE
Mar 16 19:38:51 box.lan hostapd[10792]: wlan0_ap: Could not connect to kernel driver
Mar 16 19:38:51 box.lan hostapd[10792]: Using interface wlan0_ap with hwaddr b8:27:eb:1f:7a:99 and ssid "Internet in a Box"
Mar 16 19:38:51 box.lan hostapd[10792]: wlan0_ap: interface state COUNTRY_UPDATE->ENABLED
Mar 16 19:38:51 box.lan hostapd[10792]: wlan0_ap: AP-ENABLED

I connect from my laptop
Note that I get an ip addr from the server:
● hostapd.service - Hostapd IEEE 802.11 AP, IEEE 802.1X/WPA/WPA2/EAP/RADIUS Authenticator
   Loaded: loaded (/etc/systemd/system/hostapd.service; disabled; vendor preset: enabled)
   Active: active (running) since Fri 2018-03-16 19:38:51 UTC; 1min 46s ago
 Main PID: 10792 (hostapd)
   CGroup: /system.slice/hostapd.service
           └─10792 /usr/sbin/hostapd -P /run/hostapd.pid /etc/hostapd/hostapd.conf

Mar 16 19:38:51 box.lan hostapd[10792]: Failed to create interface mon.wlan0_ap: -95 (Operation not supported)
Mar 16 19:38:51 box.lan hostapd[10792]: wlan0_ap: interface state UNINITIALIZED->COUNTRY_UPDATE
Mar 16 19:38:51 box.lan hostapd[10792]: wlan0_ap: Could not connect to kernel driver
Mar 16 19:38:51 box.lan hostapd[10792]: Using interface wlan0_ap with hwaddr b8:27:eb:1f:7a:99 and ssid "Internet in a Box"
Mar 16 19:38:51 box.lan hostapd[10792]: wlan0_ap: interface state COUNTRY_UPDATE->ENABLED
Mar 16 19:38:51 box.lan hostapd[10792]: wlan0_ap: AP-ENABLED
Mar 16 19:39:32 box.lan hostapd[10792]: wlan0_ap: STA a4:34:d9:5c:81:bd IEEE 802.11: associated
Mar 16 19:39:32 box.lan hostapd[10792]: wlan0_ap: AP-STA-CONNECTED a4:34:d9:5c:81:bd
Mar 16 19:39:32 box.lan hostapd[10792]: wlan0_ap: STA a4:34:d9:5c:81:bd RADIUS: starting accounting session 5AAC1D4B-00000000
Mar 16 19:39:32 box.lan hostapd[10792]: wlan0_ap: STA a4:34:d9:5c:81:bd WPA: pairwise key handshake completed (RSN)
but the laptop can not ping 172.18.96.1
and box.lan does not resolve

**Comment by tim-moody** [comment]
root@box:/etc/hostapd# cat /var/lib/misc/dnsmasq.leases
1521232772 a4:34:d9:5c:81:bd 172.18.116.88 TimPC 01:a4:34:d9:5c:81:bd

**Comment by tim-moody** [comment]
my phone can connect to the ssid and gets a lease, but I can't connect over ssh or http

**Comment by tim-moody** [comment]
is it possible that resolve does not work in secure mode?

**Comment by tim-moody** [comment]
root@box:/etc/hostapd# systemctl status dnsmasq
● dnsmasq.service - DNS caching server.
   Loaded: loaded (/etc/systemd/system/dnsmasq.service; enabled; vendor preset: enabled)
   Active: active (running) since Fri 2018-03-16 14:18:31 UTC; 5h 54min ago
 Main PID: 743 (dnsmasq)
   CGroup: /system.slice/dnsmasq.service
           └─743 /usr/sbin/dnsmasq -k

Mar 16 19:57:06 box.lan dnsmasq-dhcp[743]: DHCPREQUEST(br0) 172.18.122.128 ec:1f:72:12:27:d3
Mar 16 19:57:06 box.lan dnsmasq-dhcp[743]: DHCPACK(br0) 172.18.122.128 ec:1f:72:12:27:d3 Galaxy-S6-edge
Mar 16 19:58:55 box.lan dnsmasq-dhcp[743]: DHCPREQUEST(br0) 172.18.116.88 a4:34:d9:5c:81:bd
Mar 16 19:58:55 box.lan dnsmasq-dhcp[743]: DHCPACK(br0) 172.18.116.88 a4:34:d9:5c:81:bd TimPC
Mar 16 19:58:56 box.lan dnsmasq-dhcp[743]: DHCPDISCOVER(br0) ec:1f:72:12:27:d3
Mar 16 19:58:56 box.lan dnsmasq-dhcp[743]: DHCPOFFER(br0) 172.18.122.128 ec:1f:72:12:27:d3
Mar 16 19:58:56 box.lan dnsmasq-dhcp[743]: DHCPREQUEST(br0) 172.18.122.128 ec:1f:72:12:27:d3
Mar 16 19:58:56 box.lan dnsmasq-dhcp[743]: DHCPACK(br0) 172.18.122.128 ec:1f:72:12:27:d3 Galaxy-S6-edge
Mar 16 20:08:55 box.lan dnsmasq-dhcp[743]: DHCPREQUEST(br0) 172.18.116.88 a4:34:d9:5c:81:bd
Mar 16 20:08:55 box.lan dnsmasq-dhcp[743]: DHCPACK(br0) 172.18.116.88 a4:34:d9:5c:81:bd TimPC

**Comment by tim-moody** [comment]
why is IIAB_WAN_DEVICE=wlan0_ap in /etc/iiab/iiab.env? isn't it part of the br0

**Comment by tim-moody** [comment]
root@box:/etc/hostapd# iptables -t nat -L
Chain PREROUTING (policy ACCEPT)
target     prot opt source               destination
DNAT       tcp  --  anywhere            !box.lan              tcp dpt:http to:172.18.96.1:3128

is this squid?

**Comment by georgejhunt** [comment]
At this point, I agree.

In order to set up iptables properly before I put the br0 back in (#690), I
needed the lan and wan device names to set up iptables properly. Now, br0
seems more appropriate than wlan0_ap, as the lan device.

**Comment by georgejhunt** [comment]
yes x.x.x.x:3128 is squid

**Comment by tim-moody** [comment]
the problem is that wlan0_ap is WAN not LAN. don't think that should ever happen

**Comment by tim-moody** [comment]
shouldn't IIAB_WAN_DEVICE.*/IIAB_WAN_DEVICE=wlan0
wlan0_ap is the lan

**Pull request closed without merging**
