### PR TITLE
If local_vars specifies DansGuardian on Debian Buster or similar, abort iiab-install & explain

### PR DESCRIPTION
**Pull request by jvonau**
### Fixes Bug
#1980 
release-7.0

### CODE REVIEW

**Comment by jvonau** [comment]
Once this is merged into release-7.0 a second PR with release-7.0 as the source should be created and pushed into master.

**Comment by holta** [comment]
This appears overstrict given DansGuardian is still a part of Ubuntu 18.04 and 18.10.  I'm assuming Ubuntu 19.04 and 19.10 and 20.04 LTS will not offer DansGuardian (but I could be wrong!)

Friday night I added a warning into IIAB 7.1 pre-release / master (PR #1983) which could certainly be made stronger and/or partially enforced if nec ?!

**Comment by holta** [comment]
However we proceed, we should sync up (align this work with) PR https://github.com/iiab/iiab-factory/pull/80

**Comment by holta** [comment]
We really should tolerate DansGuardian on Debian 9 / Stretch too.  (A few of these still exist...)

**Pull request closed without merging**
