### PR TITLE
https://bugs.launchpad.net/ubuntu/+bug/1872897 [Bluetooth on Ubuntu]

### PR DESCRIPTION
**Pull request by jvonau**
### Fixes Bug
https://bugs.launchpad.net/ubuntu/+bug/1872897

### CODE REVIEW

**Comment by holta** [comment]
@tim-moody @georgejhunt is it Ok to merge this now?

**Comment by holta** [comment]
FYI this is urgent, as @jvonau believes master will brick Ubuntu installs until this is merged.

**Comment by tim-moody** [comment]
No opinion except that trying to use an os before it is released is hazardous.

**Comment by holta** [comment]
Tangentially related:

#2293 "bluetooth network support for ubuntu on rpi"

**Comment by georgejhunt** [comment]
Ok by me

**Pull request merged**
