### PR TITLE
Correct URI for IIAB license file

### PR DESCRIPTION
**Pull request by arky**
Correct the URI  http://github.com/XSCE/iiab/blob/master/LICENSE to http://github.com/XSCE/iiab/blob/master/LICENSE.md

### CODE REVIEW

**Comment by tim-moody** [comment]
why not https://github.com/iiab/iiab/blob/master/LICENSE.md

**Comment by tim-moody** [comment]
also, I don't think that credits.html is used anywhere.

rather https://github.com/iiab/iiab-menu/blob/master/menu-files/html/credits.html

**Comment by holta** [comment]
> also, I don't think that credits.html is used anywhere.
>
> rather https://github.com/iiab/iiab-menu/blob/master/menu-files/html/credits.html

Somehow I missed Tim's above comment.

In any case, this credits.html that @arky found is now more up-to-date:
https://github.com/iiab/iiab/blob/master/roles/httpd/files/html/credits.html

@tim-moody should this new one be moved to https://github.com/iiab/iiab-menu/blob/master/menu-files/html/credits.html

(And deleted from roles/httpd/files/html if so?)

**Comment by tim-moody** [comment]
they look identical to me

**Comment by tim-moody** [comment]
one needs to be removed

**Comment by holta** [comment]
> they look identical to me

https://github.com/iiab/iiab/blob/master/roles/httpd/files/html/credits.html has a dozen improvements and corrections I've added over the last hour.

If poss @tim-moody can you copy/move this to https://github.com/iiab/iiab-menu/blob/master/menu-files/html/credits.html ?

Then we should delete roles/httpd/files/html/credits.html

**Pull request merged**
