### PR TITLE
update bootstrap 3 and 4 and jquery to latest versions

### PR DESCRIPTION
**Pull request by tim-moody**
tested on ub 20.04.1 vm

### CODE REVIEW

**Comment by holta** [comment]
Great!

Fixes #2754 (we hope!)

**Comment by tim-moody** [comment]
>Fixes #2754 (we hope!)

The only problem reported by #2754 is that the js is out of date and subject to a CVE. An upgrade fixes the reported problem.

**Comment by holta** [comment]
Oops I reversed the digits.

Typo Correction: this fixes #2745.

**Comment by tim-moody** [comment]
now, as you say, we'll see if it breaks anything else.

**Pull request merged**
