### PR TITLE
Mediawiki 1.34.0 strictly disallows password 'changeme' so for now let's use 'changeme2020'

### PR DESCRIPTION
**Pull request by holta**
Until we come up with something better!

Builds on PR #1973 from 2019-09-30, and PR #2158 from 2020-01-16.

### CODE REVIEW

**Comment by holta** [comment]
Important: needs to be documented in http://FAQ.IIAB.IO -> "13 What are the default passwords?" after this PR merges!

**Comment by tim-moody** [comment]
I have not seen this in my testing. What evidence is there?

**Comment by holta** [comment]
> I have not seen this in my testing. What evidence is there?

'changeme' failed on 3 OS's Ubuntu 18.04, 19.10, Raspbian Lite on RPi 4.

I changed the password to 'changeme2020' per this PR, and the problem went away.

**Comment by holta** [comment]
We can change the password to something else later, if there's something better than `changeme2020`

Or perhaps implement an override within MediaWiki that allows weak passwords, if you can find such a setting @tim-moody, and we're confident that will remain supported in future versions of MediaWiki ?

**Comment by holta** [comment]
> Important: needs to be documented in http://FAQ.IIAB.IO -> "13 What are the default passwords?" after this PR merges!

Done.

**Pull request merged**
