### PR TITLE
Drop bridge-utils [and deprecate br0.j2]

### PR DESCRIPTION
**Pull request by deldesir**

### CODE REVIEW

**Comment by holta** [comment]
Many Thanks @deldesir for rebasing @jvonau's PR #2752.

If you happen to have time to test this over the course of the week...that would be amazing.

**Comment by holta** [comment]
I don't know if the older `net-tools` apt package should be removed just yet, but either way let's not lose @jvonau's discussion point from https://github.com/iiab/iiab/pull/2752#issuecomment-828603569, excerpted here:

> `for i in arp ifconfig ipmaddr iptunnel nameif mii-tool; do grep -r $i /opt/iiab/iiab/roles; done` pointed out https://github.com/iiab/iiab/blob/master/roles/captiveportal/templates/capture-wsgi.py.j2#L396 is using net-tools commands.

**Comment by jvonau** [comment]
Some useful hints while using git:
Set your name and email before you commit with `git config --global --edit`
If you forgot the above you will see
>root@box:/opt/iiab/iiab# git commit -a -m"test"
[master 09744e30] test
 Committer: root <root@box.lan>
Your name and email address were configured automatically based
on your username and hostname. Please check that they are accurate.
You can suppress this message by setting them explicitly. Run the
following command and follow the instructions in your editor to edit
your configuration file:
    git config --global --edit
After doing this, you may fix the identity used for this commit with:
    git commit --amend --reset-author
 1 file changed, 1 insertion(+), 1 deletion(-)

`git commit --amend --reset-author` will rewrite the last commit and alter the author of that commit. The --amend options opens a text editor where you can change the last commit message, useful if you didn't like your initial -m "I changed message" no need to pass --reset-author to just edit a commit message. Keep the first line brief (that is what was passed from -m"blabla" from git commit) and you can explain in greater detail a couple of lines down if you wish.

**Comment by holta** [comment]
Extremely useful tips.  A bit more detail here if nec:

"How to modify existing, unpushed commit messages?"
https://stackoverflow.com/questions/179123/how-to-modify-existing-unpushed-commit-messages/179147#179147

**Comment by jvonau** [comment]
> I don't know if the older `net-tools` apt package should be removed just yet, but either way let's not lose @jvonau's discussion point from [#2752 (comment)](https://github.com/iiab/iiab/pull/2752#issuecomment-828603569), excerpted here:
> 
> > `for i in arp ifconfig ipmaddr iptunnel nameif mii-tool; do grep -r $i /opt/iiab/iiab/roles; done` pointed out https://github.com/iiab/iiab/blob/master/roles/captiveportal/templates/capture-wsgi.py.j2#L396 is using net-tools commands.

@georgejhunt net-tools should not be removed until the dependency on arp is removed in capture-wsgi.py, `ip neigh show` is the replacement for arp.
>ubuntu@box:/opt/iiab/iiab$ ip n show
20.20.20.1 dev eth0 lladdr 00:fc:8d:db:66:92 STALE
192.168.0.1 dev eth0 lladdr 00:fc:8d:db:66:92 REACHABLE
ubuntu@box:/opt/iiab/iiab$ arp
Address                  HWtype  HWaddress           Flags Mask            Iface
20.20.20.1               ether   00:fc:8d:db:66:92   C                     eth0
hitronhub.home           ether   00:fc:8d:db:66:92   C                     eth0

Both return the same information, just the gawk line would need adjusting for the different column where the mac address presented.

**Comment by jvonau** [comment]
iiab-diagnostics need attention also.

**Comment by holta** [comment]
> iiab-diagnostics need attention also.

I get the feeling some Linux veterans refuse to give up their older networking CLI habits from 20-30 years ago.

So maybe we nudge them gradually, rather than pushing them over the cliff too abruptly ;)

**Comment by jvonau** [comment]
Sigh.. iiab-diagnostics still has a [brctl call](https://github.com/deldesir/iiab/blob/master/scripts/iiab-diagnostics#L191) that should be altered also.

**Comment by holta** [comment]
> Sigh.. iiab-diagnostics still has a [brctl call](https://github.com/deldesir/iiab/blob/master/scripts/iiab-diagnostics#L191) that should be altered also.

I'm not understanding.  Didn't you already fix this with @deldesir here?

https://github.com/deldesir/iiab/blob/drop-bridge-utils/scripts/iiab-diagnostics#L192

**Comment by jvonau** [comment]
Yea guess so, late night sore eyes, more of a note when reviewing the other testing PR. It was noted that older commands were being used from code that was imported and written in awhile a go. Low hanging fruit with a pretty straight forward replacement. Others can do as they want, just trying to keep things a bit more tidy, up to date and mainstream.

**Comment by holta** [comment]
@tim-moody cautions us that Admin Console also uses the 'brctl' command &mdash; which should probably also now be changed from `brctl show` to `bridge -d link` ?

https://github.com/iiab/iiab-admin-console/blob/master/roles/cmdsrv/files/iiab-cmdsrv3.py#L1176

**Comment by holta** [comment]
@jvonau is helping @tim-moody to try to work this out.  Thankfully both are in /usr/sbin

(Hopefully the output of `bridge -d link` is sufficiently similar, so that Admin Console's scraping of the output still works!)

**Comment by holta** [comment]
Thanks to @tim-moody:

PR iiab/iiab-admin-console#396 "brctl to bridge"

**Pull request merged**
