### PR TITLE
Add concurrency to iiab-make-kiwix-lib

### PR DESCRIPTION
**Pull request by tim-moody**

### CODE REVIEW

**Comment by holta** [comment]
Fixes #804 == iiab/iiab-admin-console#73  (we hope!)

**Comment by holta** [comment]
@jvonau wonders if flock (for concurrency) should be installed in kiwix role, not 2-common?

> I'd toss that on to kiwix to avoid a full reinstall"

@tim-moody wondered if 2-common was better:

> took 2-common. think all our distros have a flock package

If this debate matters, let's talk it through in coming days or during our Thur/Fri community/team call (http://minutes.iiab.io)

**Comment by tim-moody** [comment]
smoke and functional testing done on u18.04 vm

**Comment by holta** [comment]
@tim-moody is this working on Raspbian or at least safe enough to merge?

**Comment by holta** [comment]
Discussed on community/team call (http://minutes.iiab.io).

Needs testing on RPi etc.

**Pull request merged**
