### PR TITLE
unconditionally install sqlite3

### PR DESCRIPTION
**Pull request by georgejhunt**
### Fixes bug:
Tim's image is fixed by installing php7.3-sqlite3

### CODE REVIEW

**Comment by holta** [comment]
Presumably this resolves #2461 ??

("Maps for OSM for IIAB7.1 do not appear to be loading correctly")

**Comment by holta** [comment]
`when: is_debuntu and (not is_debian_8) and (not is_ubuntu_16)` covers all 3 of our currently supported OS's {RaspiOS 10, Ubuntu 20, Debian 10} so I'm confused how commenting this out helps &mdash; @georgejhunt can you explain more?

**Comment by holta** [comment]
> state is required for package module

Good catch, thanks @georgejhunt 

Does this fix #2461 ?

**Comment by tim-moody** [comment]
when logged in as root and with an internet connection for IIAB I did

```
apt update
apt install php7.3-sqlite3

```
The initial map still has no tiles even though it says zoom level 5, but zooming in and out got a map although with many missing tiles.

```
systemctl restart nginx
systemctl restart php7.3-fpm.service
```

helped, but some tiles still fail to appear, mostly satellite I think.

On reboot the initial map was populated, but still with some missing tiles.

**Comment by tim-moody** [comment]
I still have some of these errors

```
Uncaught Error: Unimplemented type: 3
    at Pbf.skip (index.js:166)
    at Pbf.readFields (index.js:16)
    at MVT.readFeatures (MVT.js:225)
    at VectorTile.<anonymous> (featureloader.js:61)
```

**Comment by georgejhunt** [comment]
#2463 not smoke tested

**Comment by georgejhunt** [comment]
Yes I had the missing tile problem also. In the past, it has come and gone, and what seemed to fix it was to define data-root in tileserver.php (with our new viewer--program separated from data approach).
But doing that will require redoing the 12 map zip files. It may be that php-frm does not do the same as apache php.
I think it much easier to use apache for vector-maps than to redo 12 zipped bundles that are going away anyway.

**Comment by holta** [comment]
Great if OSM is moving towards defining its own dependencies (e.g. sqlite3 in this case).

As such, shouldn't the installation of `php{{ php_version }}-sqlite3` be removed from roles/httpd/tasks/install.yml if it's no longer serving a purpose there?

(Or does Apache somehow truly require sqlite3 for some reason?)

**Comment by georgejhunt** [comment]
I don't think that we have agreement on which direction we are "moving toward".

**Comment by holta** [comment]
> I don't think that we have agreement on which direction we are "moving toward".

As will always be the case in any democracy.  e.g. it could take weeks if reverting to Apache needs to be investigated and carefully tested.

Along the way we should also answer the original Yes/No question: does Apache somehow truly require sqlite3 ?
(I'll assume the answer is No, as we fix master in the coming hours so that people can use OSM as part of regular IIAB 7.2 pre-releases.  But if I'm wrong, and Apache also needs sqlite3 for other reasons, please LMK.)

**Comment by tim-moody** [comment]
first, is there possibly a timeout or file size that can be changed to fix the couple of tile blocks that don't load. feels to me like timeout as they load more readily as soon as things get cached by the server.

Is it viable to move forward to the viewer code rather than backwards to apache?
I agree we don't want to rebuild the zipped bundles.
What happens if you take the viewer code and after downloading a 7.1 bundle you move the mbtiles to /library/www/osm-vector-maps/viewer/tiles? the 3rd stage of the admin cons tile download could easily be modified to do this. 
What happens if you modify regions.json to point to the new mbtiles packages? my bet is that adm cons will be none the wiser and just download them with no change to the user interface.

**Comment by tim-moody** [comment]
> Along the way we should also answer the original Yes/No question: does Apache somehow truly require sqlite3 

apache2 has no dependency on php or sqlite3

**Comment by georgejhunt** [comment]
I don't think reverting to apache is a very good idea. The code base has
changed so much, and I cannot figure it out quickly.
I like the idea of exploring exactly why php-fpm is getting errors.
It seems very repeatable for me, and some tiles never seem to render
correctly. I remember that the satellite database initially had many
missing tiles. So I wrote a python program to verify and fetch the missing
ones, and they will be added at the end. So I'm sure access times for some
tiles will be longer, going through the index tree.

**Comment by georgejhunt** [comment]
The defect seems to be in the satellite sqlite database. I substituted
satellite_z0-z9_v3.mbtiles. Cleared local cache-->didn't fix. Then rebooted
the server ->fixed.
So Tim's suggestion of changing the script in admin-console which loads the
zip file can work.
In each zip package there is a symbolic link satellite.mbtiles
-> satellite_z0-z9.mbtiles which needs changing to satellite.mbtiles
-> satellite_z0-z9_v3.mbtiles
The new satellite file is up at
https://archive.org/download/satellite_z0-z9_v3.mbtiles/satellite_z0-z9_v3.mbtiles

**Comment by georgejhunt** [comment]
I wonder if  the "san_jose" zip file might not be the only one we need to
update.  I cannot imagine that 7.0 had the problem we have seen with
satellite tiles without a lot of complaints.
I think we just removed san-jose from regions -- but for 7.1 we renamed it
to "World to zoom 10", and started using it as our test platform because it
was smaller.
Redoing the "world to zoom 10" zip file might be another option.

**Comment by georgejhunt** [comment]
Or just remove the "world to zoom 10" from regions.json

**Comment by georgejhunt** [comment]
I can confirm that the central_america zip package has the _v3 version of
satellite.mbtiles

**Comment by tim-moody** [comment]
Isn't World to zoom 10" just the name in the regions.json file?

**Comment by georgejhunt** [comment]
yes

**Comment by georgejhunt** [comment]
no actually "World to zoom 10" is the content of the title field in the
san_jose region.

**Comment by holta** [comment]
Should no longer be necessary, as a result of PR #2464 which is now merged.

**Pull request closed without merging**
