### PR TITLE
Infastructure for proper versioning.

### PR DESCRIPTION
**Pull request by jvonau**
Add the recording of IIAB_REVISION to stage 9 to allow incriminating the value to reflect major change in a role that would require a re-install where such roles would be recorded in upgrade_roles, works with https://github.com/iiab/iiab-factory/pull/134

Change the value for any roles' source version that would require a re-install, that gets noted in upgrade_roles and iiab_revision gets bumped. The big mongodb change is a perfect test subject.

### CODE REVIEW

**Comment by jvonau** [comment]
You see the release workflow going on here right?
make a change that requires a reinstall
bump iiab_revision 
add iiab_revision number and role to upgrade_roles

134 has the logic in bash to remove the role based on upgrade_roles from the iiab_state.yml file just like runrole --reinstall does for a single role. Could be done in other places but lets start with this in place to have something to test against?

**Comment by jvonau** [comment]
This PR was tagged with "question" a week ago, with no question asked. What is the deal here?

**Comment by holta** [comment]
Let's surface exactly these design/architectural questions and needs for this PR and others (PR #2511 and others) during our Thursday 10AM NYC IIAB Calls (http://minutes.iiab.io) so everybody can understand where changes like this are critically important, how they serve specific implementer/field communities's needs, medium-term versus long-term etc.

All hugely important questions.

Keeping in mind that [IIAB 7.2](https://github.com/iiab/iiab/wiki/IIAB-7.2-Release-Notes) should ship this month with very few changes, if possible (i.e. most all structural/design changes should really target IIAB 8.0 at this point).  No rule is completely hard & fast -- but as stated at http://minutes.iiab.io -- we should try to keep those remaining IIAB 7.2 pre-release changes bounded in these 3 rough categories: (if at all possible!!)
- Ansible 2.10 support #2479
- Friendlier install of new OSM Map Packs + Satellite Photos (with Admin Console integration as nec?)
- WiFi hotspot reliability issues if/as needed by #2497 ?

**Comment by jvonau** [comment]
The general idea is to use iiab_revision in conjunction with tagging|branching to denote an easy a point in time reference of the code-base without resorting to git hashes.

**Comment by jvonau** [comment]
This goes into 7.2 or the freebies stop.

**Comment by tim-moody** [comment]
is the proposal to track revisions by role or by entire install?

**Comment by jvonau** [comment]
By the role

**Comment by jvonau** [comment]
@holta Get off your high horse you power freak.

**Comment by jvonau** [comment]
Despite the childish attempt to block testing progress by reverting this commit /iiab/iiab-factory#134 proved to be a success http://sprunge.us/YlHp09 note the order of entries in /etc/iiab/iiab_state.yml the 3 roles were automatically upgraded as the new entries are below calibreweb_installed, the last role to possibly be installed on a machine that was first installed on July 20.

**Pull request merged**
