### PR TITLE
For discussion php softcode 

### PR DESCRIPTION
**Pull request by jvonau**

### CODE REVIEW

**Comment by jvonau** [comment]
#69

**Comment by georgejhunt** [comment]
What problem is this PR addressing?

**Comment by jvonau** [comment]
https://github.com/iiab/iiab/issues/69

**Comment by holta** [comment]
I'm not qualified to say if this is important for IIAB 6.4 -- hopefully @georgejhunt and @tim-moody can help?

fyi @jvonau has done extensive research on this in #69

**Pull request closed without merging**
