### PR TITLE
Kalite venv

### PR DESCRIPTION
**Pull request by jvonau**

### CODE REVIEW

**Comment by georgejhunt** [comment]
I like this idea. I'm not sure about the disk size footprint, but it seems like it will forestall problems long term.

**Comment by jvonau** [comment]
du -h /usr/local/kalite | grep M

2.9M	/usr/local/kalite/venv/lib/python2.7/site-packages/kalite/packages/dist/django/conf/locale
3.1M	/usr/local/kalite/venv/lib/python2.7/site-packages/kalite/packages/dist/django/conf
35M	/usr/local/kalite/venv/lib/python2.7/site-packages/kalite/packages/dist/django
6.6M	/usr/local/kalite/venv/lib/python2.7/site-packages/kalite/packages/dist/youtube_dl/extractor
7.5M	/usr/local/kalite/venv/lib/python2.7/site-packages/kalite/packages/dist/youtube_dl
1.3M	/usr/local/kalite/venv/lib/python2.7/site-packages/kalite/packages/dist/requests/packages/chardet
1.9M	/usr/local/kalite/venv/lib/python2.7/site-packages/kalite/packages/dist/requests/packages
2.6M	/usr/local/kalite/venv/lib/python2.7/site-packages/kalite/packages/dist/requests
1.6M	/usr/local/kalite/venv/lib/python2.7/site-packages/kalite/packages/dist/south
1.1M	/usr/local/kalite/venv/lib/python2.7/site-packages/kalite/packages/dist/cherrypy/test
2.9M	/usr/local/kalite/venv/lib/python2.7/site-packages/kalite/packages/dist/cherrypy
55M	/usr/local/kalite/venv/lib/python2.7/site-packages/kalite/packages/dist
90M	/usr/local/kalite/venv/lib/python2.7/site-packages/kalite/packages
150M	/usr/local/kalite/venv/lib/python2.7/site-packages/kalite
1.7M	/usr/local/kalite/venv/lib/python2.7/site-packages/setuptools
1.4M	/usr/local/kalite/venv/lib/python2.7/site-packages/pip/_vendor/distlib
1.3M	/usr/local/kalite/venv/lib/python2.7/site-packages/pip/_vendor/requests/packages/chardet
1.8M	/usr/local/kalite/venv/lib/python2.7/site-packages/pip/_vendor/requests/packages
2.4M	/usr/local/kalite/venv/lib/python2.7/site-packages/pip/_vendor/requests
1.1M	/usr/local/kalite/venv/lib/python2.7/site-packages/pip/_vendor/html5lib
6.1M	/usr/local/kalite/venv/lib/python2.7/site-packages/pip/_vendor
7.0M	/usr/local/kalite/venv/lib/python2.7/site-packages/pip
1.6M	/usr/local/kalite/venv/lib/python2.7/site-packages/south
1.1M	/usr/local/kalite/venv/lib/python2.7/site-packages/cherrypy/test
2.9M	/usr/local/kalite/venv/lib/python2.7/site-packages/cherrypy
230M	/usr/local/kalite

230M total - 150M installed anyway = 80M maximum installed by not using sitepackages

**Comment by tim-moody** [comment]
I am persuaded that for the two I think we have, osm and kalite, saving the extra space is not worth the complexity.

**Comment by jvonau** [comment]
Not so much for complexity, but for protection against the symlinked
libraries getting updated via yum, apt, or pip causing an unexpected change.​​

**Comment by georgejhunt** [comment]
included in PR 259

**Pull request closed without merging**
