### PR TITLE
 fix kiwix_serve_enabled -> kiwix_enabled in vars/default_vars.yml + other files

### PR DESCRIPTION
**Pull request by holta**

### CODE REVIEW

**Comment by holta** [comment]
Helps with #421 that @tim-moody diagnosed.

**Comment by holta** [comment]
Also changed "kiwix_enabled: False" -> "kiwix_enabled: True" to abide by community norms @ http://wiki.laptop.org/go/IIAB/local_vars.yml

**Review by tim-moody — CHANGES_REQUESTED** [review]
don't forget the code that uses the variable

**Comment by holta** [comment]
Smoke-tested & functionality-tested on Raspbian Lite, also with "./runtags sugarizer" & "./runtags kiwix".

I'll merge in coming minutes if there are no objections.

Thanks @jvonau & @tim-moody who helped review.

@floydianslips can you help test on Ubuntu 16.04 or Debian 9.2 in coming days?

PS @jvonau now has installs running to completion on CentOS 7.4 too if that helps!

**Pull request merged**
