### PR TITLE
REVISED: Add Node-RED and Mosquitto (MQTT) IIAB playbooks for IoT

### PR DESCRIPTION
**Pull request by m-anish**
This is the updated and fixed PR for #854

### CODE REVIEW

**Comment by holta** [comment]
@tim-moody asked us to change the way default_vars.yml works: https://github.com/iiab/iiab/pull/1352

So now default_vars.yml is equivalent to MIN-sized, with most all apps/services set not to install or be enabled.

Can you revise this PR's default_vars.yml as such?

**Comment by m-anish** [comment]
> @tim-moody asked us to change the way default_vars.ymk works: #1352
> 
> So now default_vars.yml is equivalent to MIN-sized, with most all apps/services set not to install or be enabled.
> 
> Can you revise this PR's default_vars.yml as such?

Done! Thanks for pointing it out.

**Comment by m-anish** [comment]
**PLEASE READ THIS BEFORE MERGING**

Test on the following environments:

- Debian
- Raspberry pi
- Test first with all flags `nodered_install, nodered_enabled, mosquitto_install, mosquitto_enabled` set to **False**
- Then test by enabling them all and rerunning the install

Thanks!

**Comment by holta** [comment]
> * Test first with all flags `nodered_install, nodered_enabled, mosquitto_install, mosquitto_enabled` set to **False**

Confirmed:
- Worked on 3 OS's {Raspbian Lite, Ubuntu 16.04 & Ubuntu 18.04} with above 4 flags set to **False**
- And then again worked on all 3 OS's with the 4 flags set to **True** (i.e. BIG-sized /etc/iiab/local_vars.yml)

@m-anish & all: can you please test on [Debian 9.6 "Stretch"](https://www.debian.org/releases/stretch/) and also [Debian 10 "Buster" (pre-release) daily-build](https://www.debian.org/devel/debian-installer/) if at all poss?

**Comment by m-anish** [comment]
**Alert! NOTE!** **node-red fails on 9.6!!**

1. the install proceeds smoothly
2. but node red install in a directory other than where the systemd service is expecting it to
3. i will make a fix 
4. so, the testing must involve actually opening <box_ip>:1880 
5. and enter the following creds  Admin:g0adm1n

**Comment by m-anish** [comment]
This now works on Debian 9.6(VM), and Ubuntu 18.04(VM)

**Comment by m-anish** [comment]
This works on Debian 10(VM) as well, after applying the fixes described in #1387

**Comment by holta** [comment]
Successfully tested http://box:1880 (Node-RED's console) with both http://LAN-ip:1880 & http://WAN-ip:1880 on these 3 OS's:

- Raspbian Lite on RPi 3 B+
- Ubuntu Desktop 16.04 on NUC
- Ubuntu Server 18.04 on NUC

PS the key was adding `daemon-reload: True` to Ansible's systemd calls, and making sure `./iiab-network` has indeed run.

**Pull request merged**
