### PR TITLE
Test adding allow all

### PR DESCRIPTION
**Pull request by jvonau**
for the hidden file issue
### Fixes bug:
#3072 
### Smoke-tested on which OS or OS's:
systemctl restart nginx is clean

### CODE REVIEW

**Comment by holta** [comment]
Thanks.

Let's merge this experimentally and I'll test it right away.

**Comment by holta** [comment]
Unfortunately applying this PR (`cd /opt/iiab/iiab` then `sudo ./runrole --reinstall kiwix`) did not improve the situation.

( http://10.8.0.14/kiwix/wikipedia_en_all_maxi_2021-03/A/.apple still shows **403 Forbidden** )

**Comment by jvonau** [comment]
Now I wonder why this was not hand tested before merging, and if this is not the fix why is it not reverted yet?

**Comment by holta** [comment]
This PR was tested immediately after it was merged.

It did not help, as explained above.

So it was reverted by:

- PR #3074

**Comment by jvonau** [comment]
Still does not explain why a single one line change was not hand tested on the machine with the dataset installed before merging.

**Pull request merged**
