### PR TITLE
iiab-diagnostics: dmesg | grep -i <about 9 WiFi patterns> | head -100 (firmware/driver msgs)

### PR DESCRIPTION
**Pull request by holta**
@jvonau, @shanti-bhardwa & others: are 100 lines really useful/necessary?

Or should this number be reduced?

Not quite related but just fyi this was also just added:

- PR #3332

### CODE REVIEW

**Comment by holta** [comment]
Or is a targeted grep-like extract of `dmesg` output... _more useful?_

(Anything like the following possibly?)

```
root@iiab-mint01:~# dmesg | grep -i -e 80211 -e 802\.11 -e wireless -e wlan0
[   16.126273] cfg80211: Loading compiled-in X.509 certificates for regulatory database
[   16.138932] cfg80211: Loaded X.509 cert 'sforshee: 00b28ddf47aef9cea7'
[   16.818795] wlan0: Broadcom BCM4315 802.11 Hybrid Wireless Controller 6.30.223.271 (r587334)
[   17.220686] wl 0000:0c:00.0 wlp12s0: renamed from wlan0
```

**Comment by jvonau** [comment]
That is pretty concise and you have the timestamps as a pointer for other events that might be recorded in the journal.

**Comment by holta** [comment]
```
dmesg | grep -i -e 80211 -e 802\.11 -e wireless -e wlan0`
```

> That is pretty concise and you have the timestamps as a pointer for other events that might be recorded in the journal.

Ok.

Probably it should be moved up and combined with Line 219 in that case:

https://github.com/iiab/iiab/blob/45bd088c70ee8006d0c3640e31f2e7449eb9d6f3/scripts/iiab-diagnostics#L219

@shanti-bhardwa does this cover your driver monitoring needs — _or are there more grep keywords that we should add?_

**Comment by holta** [comment]
5 more grep keywords that should probably be added?  (to grep through `dmesg` output!)

- wifi
- realtek
- broadcom 
- brcm
- bcm

Any others?

**Comment by holta** [comment]
These 9 grep patterns (to tighten up `dmesg` output into <= 100 lines) might appear long-winded.
But they do serve a function.

In Summary: The current list of 9 patterns can be shrunk or expanded &mdash; e.g. if other dominant keywords are appropriate, beyond just {brcm, realtek, etc} ?

**Comment by holta** [comment]
Good enough.

This can be further revised in future if/as nec.

**Pull request merged**
