### PR TITLE
U20test / Ubuntu 20.04 to offer PHP 7.3 and 7.4 [Nextcloud PHP deps, php-stem on U20, ap0 prep, KA Lite on Ubermix, etc]

### PR DESCRIPTION
**Pull request by jvonau**
### Fixes Bug
alternate to #2290 includes #2269 fixes nextcloud install when there is multiple php versions available to install.
### Description of changes proposed in this pull request.
U-20 offers php 7.3 and 7.4, we can use 7.3 for now.
### Smoke-tested in operating system.
[u20and64bit.txt](https://github.com/iiab/iiab/files/4354189/u20and64bit.txt)

### CODE REVIEW

**Comment by jvonau** [comment]
testing included #2266 #2289 #2291 #2293

**Comment by jvonau** [comment]
ap0 is working nicely without upstream wifi connected, will test dual support later.
> ubuntu@ubuntu:/opt/iiab/iiab$ sudo tail /var/log/syslog
Mar 19 11:49:04 box -- MARK --
Mar 19 12:09:04 box -- MARK --
Mar 19 12:15:28 box hostapd: ap0: STA cc:61:e5:49:0b:6f IEEE 802.11: associated
Mar 19 12:15:28 box hostapd: ap0: STA cc:61:e5:49:0b:6f RADIUS: starting accounting session 236B7288430F966E
Mar 19 12:15:32 box dnsmasq-dhcp[204066]: DHCPDISCOVER(br0) cc:61:e5:49:0b:6f 
Mar 19 12:15:32 box dnsmasq-dhcp[204066]: DHCPOFFER(br0) 172.18.100.204 cc:61:e5:49:0b:6f 
Mar 19 12:15:32 box dnsmasq-dhcp[204066]: DHCPDISCOVER(br0) cc:61:e5:49:0b:6f 
Mar 19 12:15:32 box dnsmasq-dhcp[204066]: DHCPOFFER(br0) 172.18.100.204 cc:61:e5:49:0b:6f 
Mar 19 12:15:32 box dnsmasq-dhcp[204066]: DHCPREQUEST(br0) 172.18.100.204 cc:61:e5:49:0b:6f 
Mar 19 12:15:32 box dnsmasq-dhcp[204066]: DHCPACK(br0) 172.18.100.204 cc:61:e5:49:0b:6f android-8426491f0c2ed4ce

**Comment by holta** [comment]
@m-anish can you help identify your Nextcloud PHP dependency needs, comparing this PR to PR #2258 ?

(In context with your original PR #2119)

**Comment by holta** [comment]
@jvonau smoke-tested this on an Ubuntu 20.04 pre-release on RPi 4, but not Raspbian.

**Comment by holta** [comment]
BIG-sized reinstall smoke-test of this PR (#2294) just begun on Raspbian Lite / RPi 4 2GB @ 10.8.0.54 as follows:

```
mv /etc/iiab/iiab_state.yml /etc/iiab/iiab_state.yml.old
cd /opt/iiab/iiab
./iiab-install --reinstall
```

It's working thru Stage 4 (of 9) at the moment...

**Comment by holta** [comment]
`./iiab-install --reinstall` test of PR #2294 completed on RPi 4 10.8.0.54

**Pull request merged**
