### PR TITLE
change resize service to use growpart, which must be installed for raspios

### PR DESCRIPTION
**Pull request by tim-moody**
parted no longer works on ub 20

### CODE REVIEW

**Comment by holta** [comment]
@tim-moody does `tune2fs -m 1 /dev/mmcblk0p2` (at https://github.com/iiab/iiab-factory/blob/master/iiab#L175-L180) remain ok on RaspiOS and Ubuntu-on-RPi both?

**Comment by tim-moody** [comment]
I have no reason to think otherwise.

**Comment by holta** [comment]
Is this reasonably safe to merge?

**Comment by tim-moody** [comment]
just testing

**Comment by tim-moody** [comment]
passed smoke test

**Comment by holta** [comment]
> passed smoke test

On which OS?

**Comment by tim-moody** [comment]
passed functional test on ub20 (and seems faster)
>On which OS?

should be irrelevant as long as rpi

**Comment by tim-moody** [comment]
passed smoke and functional tests on raspios

**Comment by holta** [comment]
@tim-moody clarifies (https://github.com/iiab/iiab/issues/2517#issuecomment-692344235) that this PR apparently introduced an upstream bug (https://bugs.launchpad.net/cloud-utils/+bug/1881014) causing serious IIAB image corruption (boots fail) when `growpart` fails to interpret the output of `uname -r` ?

This should probably be documented in our [IIAB 7.2 Known Issues](https://github.com/iiab/iiab/wiki/IIAB-7.2-Release-Notes#known-issues) (until this is hopefully solved upstream?)

**Comment by holta** [comment]
Related discussion of possible mitigation (not quite bug fix) is ongoing here:

PR #2522 "strict ordering [fix for #2517 boot failures on Zero W re: growpart ? Partition fsck / resizing questions]"

**Pull request merged**
