### PR TITLE
provide python2.7 virtual environment for iiab apps

### PR DESCRIPTION
**Pull request by jvonau**
Keeps current python2.7 apps contained in virtualenv till porting can be completed, step to solve #2013 as the dependencies supplied by pip are in flux pending review and testing.

### CODE REVIEW

**Comment by holta** [comment]
Ref: #1810

**Comment by jvonau** [comment]
iiab-make-kiwix-lib.py iiab-update-maps ported to python3

**Comment by holta** [comment]
@georgejhunt can you please review this now?

@jvonau @tim-moody what smoke/functional tests are most needed here?

**Comment by georgejhunt** [comment]
Adam asked me to review this.
I don't understand what problem this is trying to solve.
If it is just geojson, I think this is overkill.
I think Tim has said that he has all his code running under py3

**Comment by georgejhunt** [comment]
And as I read more, trying to educate myself about uWSGI and python3, it seems that many suggest that all significant programs should be housed in a venv. 
So if Tim's ok with it, since I don't know any different, I'm fine with #2034;
But don't we want to be shooting for py3 in the long term? Should we take the time now to get it running on py3?

**Comment by georgejhunt** [comment]
I have succeeded in getting admin-console running on #2034 
Change uwsgi to:
[uwsgi]
	uid = www-data
	gid = www-data
	socket = /tmp/admin-console.sock
	chdir = /opt/admin/console
	wsgi-file = cmd-service.wsgi
	master = true
        plugins = python3 <=====
change uwsgi.unit to:
[Unit]
Description=uWSGI Service

[Service]
ExecStart=/usr/bin/uwsgi --ini /etc/uwsgi/apps-enabled/admin-console.ini <====
Restart=always
RestartSec=5
KillSignal=SIGQUIT
Type=notify
NotifyAccess=all

[Install]
WantedBy=multi-user.target

**Comment by jvonau** [comment]
Wrong PR but I'll continue here to sum up the sequence of events, Tim asked for https://github.com/iiab/iiab/pull/2042/commits/0b0014df4074321eb549c0f9aeaecfe618e8bae7 but didn't provide the file in 263. Placing the file as need with the above edit results in a working admin-console backend on U-19.10 as 2042 does not address moving to python3 directly but is careful not to add python2 as a dependency.

**Comment by georgejhunt** [comment]
Are you wanting to run admin-console under py2.7? If so why? Which iiab
apps do you think require py2.7?

**Comment by jvonau** [comment]
> Are you wanting to run admin-console under py2.7? If so why? Which iiab apps do you think require py2.7?

Wrong PR, but when I started out there was no activity to port to python3 and Ubuntu-19.10 was failing due to python2 dependencies. Today it looks like the only thing left to port to python3 is captive-portal which I didn't address directly because the backend is Apache but your original PR never dealt with, but can provide a virtualenv to run python2 in for captive-portal to run in.

**Comment by georgejhunt** [comment]
I've verified that captive portal does not error out under python3. But I
don't currently have the ability to test all the clients against py3, and
verify function.

**Comment by jvonau** [comment]
replaced by 2048

**Pull request closed without merging**
