### PR TITLE
Osm split

### PR DESCRIPTION
**Pull request by jvonau**
### Fixes Bug
#2186

### CODE REVIEW

**Comment by holta** [comment]
What tests are most appropriate to test this?

**Comment by tim-moody** [comment]
why the departure from the enable.yml naming convention?

**Comment by jvonau** [comment]
apply the PR
`sudo ip r del default ` kills internet access but not local WAN/LAN
ping somewhere on the internet to confirm access is not possible
`sudo ./runrole osm-vector-maps`
note that operation completed without internet access
reboot to restore default gateway that was removed for testing

**Comment by holta** [comment]
> why the departure from the enable.yml naming convention?

"Do as you say, say as you do"

(enable-or-disable.yml is far more accurate description of what is really happening)

**Comment by jvonau** [comment]
> why the departure from the enable.yml naming convention?

wonderchild wants it like that...

**Comment by tim-moody** [comment]
Since we have a flag that is _enable(d) T/F that drives the process I think most people get that this yml deals with both states.
I am 100% opposed to the application churn required to retrofit this new name to all roles.

**Comment by holta** [comment]
> Since we have a flag that is _enable(d) T/F that drives the process I think most people get that this yml deals with both states.

Disagree: install.yml only installs and cannot uninstall.  Which is fine.  But we should "say as we do, do as we say" wherever humanly possible if we want understanding to grow towards onboarding of new IIAB people demanding tangible clarity in our actions, which is imperative for our survival.

**Comment by holta** [comment]
The goal for IIAB 7.1 is not to entrench the past, but to set up more cleanly understandable playbooks for the future.  I will do the work to make sure this happens.

**Comment by holta** [comment]
Also note that both proposed enable.yml and enable-or-disable.yml are disappearing entirely from many playbooks, see for example:
- https://github.com/iiab/iiab/blob/master/roles/wordpress/tasks/main.yml
- https://github.com/iiab/iiab/blob/master/roles/munin/tasks/main.yml

**Comment by jvonau** [comment]
> Also note that both proposed enable.yml and enable-or-disable.yml are disappearing entirely from many playbooks, see for example:
> 
>     * https://github.com/iiab/iiab/blob/master/roles/wordpress/tasks/main.yml
> 
>     * https://github.com/iiab/iiab/blob/master/roles/munin/tasks/main.yml

Any role that has a service behind it that would need to be turned off|on does require something more than the wordpress press example. If you are looking to move the restarting of the service back into the main.yml as munin is setup, go for it. You are on your own to change all the existing playbooks in short order for the proposed release time frame.

**Comment by holta** [comment]
Background: My presumption is that [IIAB will not support uninstalls](https://github.com/iiab/iiab/blob/master/vars/default_vars.yml#L7-L8) of its [~30 apps/services](http://wiki.laptop.org/go/IIAB/FAQ#What_services_.28IIAB_apps.29_are_suggested_during_installation.3F) for the foreseeable future.  But that could of course change possibly.

**Comment by holta** [comment]
I presume this PR does not address OSM install issue #2197 ...is that correct?

**Comment by jvonau** [comment]
> I presume this PR does not address OSM install issue #2197 ...is that correct?

Not directly but the index.files are contained in enable-or-disable.yml for a clearer look at them.

**Comment by holta** [comment]
> apply the PR
> `sudo ip r del default ` kills internet access but not local WAN/LAN
> ping somewhere on the internet to confirm access is not possible
> `sudo ./runrole osm-vector-maps`
> note that operation completed without internet access
> reboot to restore default gateway that was removed for testing

Above test worked (i.e. running `./runrole osm-vector-maps` before and after disabling Internet) after this PR was applied to 181-rpi4-1g-lite-BIG-0120-PR2171 = 10.8.0.74

**Pull request merged**
