### PR TITLE
mysql - php-xml  moodle php-zip for raspbian-9 BUGFIX

### PR DESCRIPTION
**Pull request by jvonau**
moodle or mysql might have issues on raspbian-8 due to [missing dependencies](https://github.com/iiab/iiab/search?utf8=%E2%9C%93&q=is_debian_8&type=)

### CODE REVIEW

**Comment by jvonau** [comment]
[debian-9 dependencies](https://github.com/iiab/iiab/search?utf8=%E2%9C%93&q=is_debian_9&type=)

**Comment by tim-moody** [comment]
I agree you have clearly shown the places where debian 9 packages are selected. Only testing will show if they are needed on raspbian stretch.
(is there a reason why we need usbmount 0.0.14 instead of 0.0.22?)

**Comment by jvonau** [comment]
I suspect the distinction made in mysql for php-xml is important as mysql is part of the base install. No idea about the bump in usbmount but if you what that usbkey as optional storage option it's needed.

**Comment by tim-moody** [comment]
I'll concede php-xml, though the other way to do it would be in raspbian-9.yml.

Looks to me like the usbmount conditional preserves a hack for the time when stretch was not complete and this change would perpetuate it on raspbian-9 as well. if I apt-get usbmount on raspbian-9 I get 0.0.22.

**Comment by jvonau** [comment]
The that was a stop gap measure are far as I can recall.

**Comment by tim-moody** [comment]
usbmount play fails after os upgrade on debian as package is upgraded from 0.0.14 to 0.0.22

**Comment by jvonau** [comment]
I'm not dealing with usbmount in this PR, that is a totally different issue from what is being addressed. Open an issue and wait or summit a PR to remove the usbmount hack.

**Comment by jvonau** [comment]
reworked for just the package naming discrepancies with raspbian

**Comment by holta** [comment]
ASIDE: usbmount 0.0.14 vs 0.0.22 issues differ on each OS, but are moving forward well in #195

**Pull request closed without merging**
