### PR TITLE
WIP: What's Changed in Maps for the IIAB 7.2 Release? [OSM]

### PR DESCRIPTION
**Pull request by holta**
@georgejhunt I'd like to call if you have time today.

Obviously I don't have answers and just want to understand this better — so new map & satellite opportunities are properly promoted as part of IIAB 7.2's upcoming release.

Refs:

- #1605 'New OSM Vector Maps need clean UX + clean instructions ("pick a continent or region")'
- iiab/maps#29 'IIAB Maps installer page explanations overhauled'
- iiab/iiab-admin-console#340 'Mods for new Maps'

### CODE REVIEW

**Comment by holta** [comment]
FYI these 7-point instructions have a few errors and ambiguities that make them quite confusing, to new people especially &mdash; as @avni observed in early September:

https://github.com/iiab/iiab/wiki/IIAB-Maps#for-iiab-72-and-later-maps-how-do-i-select-and-install-tiles-for-my-region

I'll clean them up in the coming week or so (or if somebody else beats me to it, even better ;)

BONUS: hopefully these 7-point instructions can be made a lot shorter after iiab/maps#29 is merged!

**Comment by holta** [comment]
An open question from https://github.com/iiab/maps/pull/29#issuecomment-699648075 when we (incl @georgejhunt, if he knows?) can:

> How resilient are these 2 CLI commands? [*]
>
> - e.g. if implementer loses her Internet connection, or ssh connection to IIAB, etc — do you think these commands can be restarted w/o too many problems — to carry on from where they began?
>
> - e.g. what network failure situation(s) would be most important to test in your opinion?
>
> [*] to install a Map Pack or Satellite Photo region

i.e. these 2 commands:
- /usr/bin/[iiab-install-map-region](https://github.com/iiab/maps/blob/master/osm-source/pages/viewer/scripts/iiab-install-map-region)
- /usr/bin/[iiab-extend-sat.py](https://github.com/iiab/maps/blob/master/osm-source/pages/viewer/scripts/iiab-extend-sat.py)

**Comment by holta** [comment]
Just as a sanity check[*] in preparation for IIAB 7.2 RC2, this PR was installed on a fresh OS @ u20-desk-subMIN-PR2551 = 10.8.0.34

[*] this documentation-centric PR is NOT ready to merge!  Let's try to clean up [roles/osm-vector-maps/README.md](https://github.com/holta/iiab/blob/osm-readme/roles/osm-vector-maps/README.md#whats-changed-in-maps-for-the-iiab-72-release) first.

**Comment by holta** [comment]
At https://github.com/iiab-share/js-menu-files/blob/master/menu-defs/en-map_test.json#L7 this line:

```
  "title": "OpenStreetMap Test Page",
```

...should change to something like:

```
  "title": "Install IIAB Maps",
```

And Line 9:

```
  "description": "Follow this link to add maps for various regions.",
```

...should change to something like:

```
  "description": "Download an IIAB Map Pack for your continent, and Hi-Res Satellite Photos for your local region(s).",
```

**Comment by holta** [comment]
@tim-moody @georgejhunt should we also rename https://github.com/iiab-share/js-menu-files/blob/master/menu-defs/en-map_test.json itself?  While changing (the corresponding) Line 2 from:

```
  "name": "en-map_test",
```

...to something far more accurate, like:

```
  "name": "en-install_maps",
```

**Comment by avni** [comment]
> At https://github.com/iiab-share/js-menu-files/blob/master/menu-defs/en-map_test.json#L7 this line:
> 
> ```
>   "title": "OpenStreetMap Test Page",
> ```
> 
> ...should change to something like:
> 
> ```
>   "title": "Install IIAB Maps",
> ```
> 
> And Line 9:
> 
> ```
>   "description": "Follow this link to add maps for various regions.",
> ```
> 
> ...should change to something like:
> 
> ```
>   "description": "Download an IIAB Map Pack for your continent, and Hi-Res Satellite Photos for your local region(s).",
> ```

https://github.com/iiab-share/js-menu-files/pull/7

**Comment by holta** [comment]
> Just as a sanity check[*] in preparation for IIAB 7.2 RC2, this PR was installed on a fresh OS @ u20-desk-subMIN-PR2551 = 10.8.0.34

It all finally worked!  i.e. Map Pack for San Jose & Satellite Photos Region around Port-au-Prince, Haiti @ http://10.8.0.34/maps
(Thanks to merged PR's iiab/maps#29 and emergency patch PR iiab/maps#30, tested in combination with this WIP PR #2551.)

@georgejhunt please consider merging PR iiab/maps#31 (iiab-extend-sat.py typo), Thanks!

**Comment by tim-moody** [comment]
> should we also rename https://github.com/iiab-share/js-menu-files/blob/master/menu-defs/en-map_test.json itself to something like en-install_maps.

My preference would be that you clone en-map_test to en-map_installer and then make your changes. This can all be done with the admin console without a PR. It will then require changing iiab-admin-console/roles/js-menu/files/menu.json, which will be a PR.

**Comment by tim-moody** [comment]
>It all finally worked! 

How did you download each of the following:?

>[*] in this case, the 3 files are:

>- osm_san_jose_z11-z14_2019.mbtiles (20M) _downloaded to /library/working/maps_
>- satellite_z0-z9_v3.mbtiles (931M) _downloaded to /library/working/maps_
>- osm-planet_z0-z10_2019.mbtiles (1.7G) _downloading begun..._

I don't think satellite_z0-z9_v3.mbtiles and osm-planet_z0-z10_2019.mbtiles are on the installer menu.

**Comment by holta** [comment]
> > It all finally worked!
> 
> How did you download each of the following:?

The 3 files are auto-downloaded sequentially for you, if you request "World to Zoom Level 10" (which is really San Jose, Calif) and paste in the command to kick that off.

> > [*] in this case, the 3 files are:
> 
> > * osm_san_jose_z11-z14_2019.mbtiles (20M) _downloaded to /library/working/maps_
> > * satellite_z0-z9_v3.mbtiles (931M) _downloaded to /library/working/maps_
> > * osm-planet_z0-z10_2019.mbtiles (1.7G) _downloading begun..._
> 
> I don't think satellite_z0-z9_v3.mbtiles and osm-planet_z0-z10_2019.mbtiles are on the installer menu.

Correct, essentially:

Each of the 12 Map Packs downloads 3 individual files, which is internal machinery to achieve (A) the custom Hi-Res [z11-z14] map region then (C) Lo-Res [z0-z9] satellite photos worldwide then (B) Lo-Res [z0-z10] maps worldwide — as outlined here:

https://github.com/iiab/maps/blob/master/osm-source/pages/installer/build/index.html#L32

**Comment by holta** [comment]
> My preference would be that you clone en-map_test to en-map_installer and then make your changes. This can all be done with the admin console without a PR.

That's done, en-map_installer is uploaded and ready here:
https://github.com/iiab-share/js-menu-files/blob/master/menu-defs/en-map_installer.json

This one's refined too: (@georgejhunt should help me further refine by phone when he has time!)
https://github.com/iiab-share/js-menu-files/blob/master/menu-defs/en-osm_viewer_v2.json

> It will then require changing iiab-admin-console/roles/js-menu/files/menu.json, which will be a PR.

@tim-moody if possible can you do that now?

Presumably the obsolete en-map_test.json should be preserved for now, e.g. for IIAB 7.1 legacy users, does that make sense?

**Comment by holta** [comment]
A 6-point draft of the "full instructions" is posted for review:

#### How do I install Map Pack(s) and Satellite Photo Region(s) on IIAB 7.2+ ?
https://github.com/iiab/iiab/wiki/IIAB-Maps#how-do-i-install-map-packs-and-satellite-photo-regions-on-iiab-72-

Please find friends/family of all ages who can run thru this and provide feedback, Thank You !!

Ref: https://github.com/iiab/iiab/pull/2551#issuecomment-700281727

**Comment by tim-moody** [comment]
Why do I need to download san jose?

I also notice that /usr/bin/iiab-install-map-region removes the preview files. Does installer still work afterwards?

**Comment by holta** [comment]
> Why do I need to download san jose?

You don't.

San Jose is a harmless 20MB included on purpose so that we all having something to test, quickly and efficiently (as part of topmost Map Pack, "World to Zoom Level 10").

@georgejhunt renamed it from "San Jose" to "World to Zoom Level 10" in order to avoid confusion, which was a wise move in my opinion.  (Most people don't care and don't need to know that 20MB of additional vector map detail is included.)

> I also notice that /usr/bin/iiab-install-map-region removes the preview files. Does installer still work afterwards?

I don't know what preview files are, can you or @georgejhunt explain?

(FWIW http://10.8.0.34/osm-vector-maps/installer/ continues to work well for me, anything else I should test?)

**Comment by holta** [comment]
> @tim-moody if possible can you do that now?

@tim-moody's PR https://github.com/iiab/iiab-admin-console/pull/343 is merged, and this is really starting to come together becoming more self-explanatory, Thanks.

Ideally (if possible!) I'd like to speak to @georgejhunt so this PR #2551 can be cleaned up before releasing IIAB 7.2 RC2 soon.

**Comment by holta** [comment]
Today I overhauled several sections of our IIAB Maps doc, from top to bottom: https://github.com/iiab/iiab/wiki/IIAB-Maps

(It's a work in progress...but getting there...needing more input from @georgejhunt & others!)

**Comment by holta** [comment]
> @georgejhunt please consider merging PR [iiab/maps#31](https://github.com/iiab/maps/pull/31) (iiab-extend-sat.py typo), Thanks!

@georgejhunt please also consider merging PR iiab/maps#32 = CLARIFS: sat res 500m not 5km (z9) + downloads 2X faster (on "Install IIAB Maps" page)

**Comment by holta** [comment]
I haven't heard from @georgejhunt in a few days, and while many questions remain to get our OSM outreach on target ([osm-vector-maps/README.md](https://github.com/holta/iiab/blob/osm-readme/roles/osm-vector-maps/README.md) etc) there's a need for IIAB 7.2 RC2 to hit the streets with better public-facing explanations very shortly now.

So I'll try to include these 3 PR's: #2551, iiab/maps#31 and iiab/maps#32 in a final test before publishing it.

**Comment by holta** [comment]
Dry-run for IIAB 7.2 RC2 is going well @ 10.8.0.66 = deb10-srv-maps

But Archive.org is taking forever, as mentioned at #2553 this is a very serious issue.

**Comment by holta** [comment]
I could have pushed IIAB 7.2 RC2 overnight.

Instead I decided this was a good opportunity to bang on IIAB Maps more thoroughly &mdash; testing it in a few more ways &mdash; before we unleash/promote IIAB 7.2 far more broadly.

So I started with downloading a whole bunch of different Hi-Res Satellite Photo Regions (including all 3 sizes of squares) and even downloading multiple Map Packs &mdash; if I can stand to wait for those excruciating #2553 downloads to complete ;)

ETC: so far everything's looking GREAT (except for the painfully slow downloading!!) which hopefully means IIAB 7.2 RC2 can finally be released later today... _and possibly might even be good enough to be our final release ?_

**Comment by holta** [comment]
To help others visualize, the latest "Install IIAB Maps" page appears as follows:
image
Refs PRs: iiab/maps#29 iiab/maps#30 iiab/maps#32 iiab/maps#33

**Pull request merged**
