### PR TITLE
kiwix-serve 2017-09-28 for RPi fixes video & full-text search!

### PR DESCRIPTION
**Pull request by holta**

### CODE REVIEW

**Comment by holta** [comment]
Need testing: we're hopeful this may fix the ZIM's-with-video regression (https://github.com/kiwix/kiwix-tools/issues/76).

**Comment by holta** [comment]
(smoke-tests successfully...but on hold as [functional testing shows no improvement](https://github.com/kiwix/kiwix-tools/issues/76#issuecomment-332394283) towards resolving the ZIMs-that-include-video regression)

**Comment by holta** [comment]
Let's wait for a better kiwix-tools that passes more functional/unit tests, even if IIAB 6.4 regrettably has to ship w/o solid video support etc.  IIAB 6.5 will dramatically beef this up very shortly it appears.

**Comment by holta** [comment]
Brand new kiwix-tools 2017-09-28 work, on armhf anyway!

(kiwix-tools 2017-09-28 for linux64 haven't been published yet...)

**Comment by holta** [comment]
Smoke-tested & basic functional testing complete.

Can't wait for the same to be ready for Ubuntu & all too!  (linux64 version, hopefully in comings hours/days)

**Comment by tim-moody** [comment]
think the 9-27 intel works, though nicer for our purposes to have a single release for both

**Pull request merged**
