### PR TITLE
Samba role standardized/modularized, for runrole etc

### LINKED ISSUE #2536: Design decisions made by committee, later warnings ignored. Is the release cycle open again?
### Expected behavior and actual behavior:
Not have roles install when the local_vars.yml is set to False
### Steps to reproduce the problem:
grep samba /etc/iiab/local_vars.yml 
samba_install: False
samba_enabled: False
sudo ./runrole samba or sudo ./runroles samba

>TASK [Set 'samba_installed: True'] ******************************************************
ok: [127.0.0.1]

>TASK [Add 'samba' variable values to /etc/iiab/iiab.ini] ********************************
changed: [127.0.0.1] => (item={'option': 'name', 'value': 'Samba'})
changed: [127.0.0.1] => (item={'option': 'description', 'value': '"Samba is a Microsoft-compatible network file system that re-implements SMB/CIFS (Common Internet File System)."'})
changed: [127.0.0.1] => (item={'option': 'enabled', 'value': False})

Now this has set the user up to fail at the next run of ansible when validate.yml catches the local_vars|iiab_state mismatch of samba_install{ed) in this case. Breaks the basic presumption of False is false.

layout of meta agreed to by committee  https://github.com/iiab/iiab/pull/2052
lockout relation change by committee https://github.com/iiab/iiab/pull/2126
highjack of PR removing installed check from main,yml https://github.com/iiab/iiab/pull/2134
moving of installed from main.yml  ***warning***  https://github.com/iiab/iiab/pull/2142
moving of installed to meta https://github.com/iiab/iiab/pull/2190/files

### PR DESCRIPTION
**Pull request by holta**
Resolves (Partially!) #2536

In recent years, IIAB's Samba role was unmaintained as several of us were thinking of deprecating it.  However this created sloppy usage with runrole etc.  Thanks @jvonau for identifying this within #2536.

To avoid those risks, this PR modernizes IIAB's Samba role, so it checks variables `samba_install` and `samba_enabled`, as other roles have been doing for many months now.

Tested on Ubuntu Desktop 20.04.1

(At the same time let's keep open the option of deprecating / de-supporting Samba completely in future, as it's very rarely used and might be more trouble than it's worth!)

### CODE REVIEW

**Comment by holta** [comment]
FYI these 4 roles fall in the same bucket as Samba, and could/should also be refined:

- cups
- minetest
- phpmyadmin
- transmission

The asterisks near the bottom of this [README.md](https://github.com/iiab/iiab/blob/master/roles/nginx/README.md) help keep track of these roles...that need improvement (or need to deprecated, as the case may be!)

i.e. we can-and-should deprecate things that incur ongoing maintenance/security costs, and have no known community of users &mdash; e.g. cups, phpmyadmin, etc ?

**Comment by holta** [comment]
> FYI these 4 roles fall in the same bucket as Samba, and could/should also be refined:

See also @jvonau's longer list at https://github.com/iiab/iiab/issues/2536#issuecomment-696200743

(Of course several of these should be deprecated, rather that generating yet more code debt, especially when communities of users simply don't exist for that functionality.)

**Comment by jvonau** [comment]
I still find it rather interesting and amusing that the test for a proper boolean is after the test for "is true". Makes more sense to ensure that the variable is a proper boolean before checking if the boolean variable is set to 'True'.

**Comment by holta** [comment]
> I still find it rather interesting and amusing that the test for a proper boolean is after the test for "is true". Makes more sense to ensure that the variable is a proper boolean before checking if the boolean variable is set to 'True'.

A role's x_**install** is tested to be boolean _while_ it's being tested "is sameas true" on Line 11: (as we mandate that it must be both!)

```
  assert:
    that: samba_install is sameas true
```

Whereas a role's x_**enabled** can have either value (e.g. True or False) so is only tested to be boolean on Line 17:

```
 assert:
    that: samba_enabled | type_debug == 'bool'

**Comment by jvonau** [comment]
> Whereas a role's x_**enabled** can have either value (e.g. True or False) so is only tested to be boolean on Line 17:
> 
> ```
>  assert:
>     that: samba_enabled | type_debug == 'bool'
> ```

What is the reasoning behind this? It's a duplicate of the code in validate.yml that is suppose to catch this error much earlier.
I can see this in place while working up a brand new role but once the role is merged the new role needs to be added to {{ vars_checklist }} in validate.yml anyway. Might want to check for missing roles. 

>- name: Assert that {{ vars_checklist | length }} "XYZ_enabled" vars are all... type boolean (NOT type string, which can invert logic!)
  assert:
    that: "{{ item }}_enabled | type_debug == 'bool'"

Fastest code is code that doesn't run...

**Comment by holta** [comment]
> What is the reasoning behind this? It's a duplicate of the code in validate.yml

Safe software enforces its own preconditions, at different levels of modularity/granularity.

i.e. this is duplicate code very much on purpose, to quickly surface errors no matter how code is reused in future.

> Might want to check for missing roles.

Indeed: [validate_vars.yml](https://github.com/iiab/iiab/blob/master/roles/0-init/tasks/validate_vars.yml) needs regular maintenance, as vars come and go.

Roles enforcing their own preconditions...helps here (to a degree) though doesn't surface errors near the very beginning of iiab-install, iiab-configure etc &mdash; as validate_vars.yml seeks to do.

**Comment by holta** [comment]
FYI this PR annotates AzuraCast as "UNMAINTAINED" as development (IIAB-AzuraCast integration) is not moving forward at the moment.

Please contact @m-anish (Anish Mangal) if you can help change this!

**Comment by holta** [comment]
That's enough for 1 PR.  To be continued in another PR.

Not that [all ~15 roles](https://github.com/iiab/iiab/issues/2536#issuecomment-696200743) should be carried forward (as there's much dead weight here, not serving anybody in 2020, that needs to be eliminated completely!)

But yes a goodly number of them should be cleaned up (as was done for Samba in this PR).

**Comment by jvonau** [comment]
> > Might want to check for missing roles.
> 
> Indeed: [validate_vars.yml](https://github.com/iiab/iiab/blob/master/roles/0-init/tasks/validate_vars.yml) needs regular maintenance, as vars come and go.

That is your baby.

> Roles enforcing their own preconditions...helps here (to a degree) though doesn't surface errors near the very beginning of iiab-install, iiab-configure etc — as validate_vars.yml seeks to do.

You should then have no issue with #2539, stop the user if sudo is not used right up front and add 'sudo' to the user facing feedback. Move validate to the very first ansible role to lead the parade. With runrole being more of a developer|power user tool targeting a single role, lets keep the noise to a minimum. Now iiab-network should really validate a small subset of user settings but we have been lucky so far. I really don't want to slow down the runtime needlessly with an eye towards something like #2375 with a smaller subset of network running during|post boot via systemd. Heck I have even done a full install or iiab-configure using a unit file and one systemd command, but you have to watch syslog or journalctl to see it running.

**Comment by jvonau** [comment]
1d3627510573f343fa140b96a166669bf47e87d0 is interesting, most the top level yaml files use iiab_state.yml as a reference and would blowup without it. The only routine that might bump into this is 'runroles' when 4-server-options is used in the list of roles.

**Pull request merged**
