### PR TITLE
Native nginx services [MediaWiki, WordPress, OSM, AWStats]

### PR DESCRIPTION
**Pull request by tim-moody**
Implemented: wordpress and mediawiki

### CODE REVIEW

**Comment by holta** [comment]
Does this actively remove DokuWiki's http://box/wiki, addressing #2056?

Or is a separate PR needed for that?

**Comment by tim-moody** [comment]
needs its own PR

**Comment by tim-moody** [comment]
can probably just change the url var to dokuwiki from wiki if we want to keep it around for now

**Comment by tim-moody** [comment]
smoke and function tests pass on ubuntu 19.10 vm

**Comment by holta** [comment]
Can this PR #2086 possibly include...?

> short term dokuwiki_url: /wiki can be changed to dokuwiki_url: /dokuwiki in default vars

...per https://github.com/iiab/iiab/issues/2056#issuecomment-569528171

Ideally: let's support both http://box/wiki and http://box/mediawiki (legacy) for MediaWiki.

**Comment by holta** [comment]
1) @georgejhunt, @jvonau can you review this PR?

2) FYI these 2 NGINX regressions remain unsolved, if you have ideas here:
- #2057 NGINX: http://box/gitea displays 404 and broken images
- #2078 NGINX somehow prevents rapid testing of IIAB apps/services [e.g. during IIAB installation]

**Comment by holta** [comment]
Does this PR deprecate the use of http://box/awstats/awstats.pl in favor of http://box/awstats ?

(If so I will change documentation @ http://FAQ.IIAB.IO)

**Comment by tim-moody** [comment]
I will stop here as I clearly did not understand #2078

**Pull request merged**
