### PR TITLE
WIP: vars/ubuntu-2110.yml, is_ubuntu_2204 etc, for twice-per-year Ubuntu releases

### PR DESCRIPTION
**Pull request by holta**
SUMMARY: Fine-grained specfiles like `/opt/iiab/iiab/vars/ubuntu-2204.yml` and Ansible vars like `is_ubuntu_2204` for Ubuntu but not for other distros.

Yes this fine-grained approach inherently creates more ongoing maintenance burden (i.e. complexity, VERY BAD!)

However, in this case the dominance of Ubuntu means we have to face this ugly reality, e.g. people getting emotionally attached to interim non-LTS Ubuntu releases.  Since this is the community reality ("communities love bikeshedding") ponying up and paying the price is the most pragmatic way forward &mdash; to avoid endless future soap operas &mdash; e.g. if October 2022's Ubuntu 22.10 has very different {PHP, PostgreSQL, Python, etc} than April 2022's Ubuntu 22.04 etc.

Refs:

- #2749
- #2818
- #2820
- PR #2984
- PR #2987

### CODE REVIEW

**Comment by holta** [comment]
Testing looks good but is ongoing to be sure, e.g. on machines and VM's like:

- 10.8.0.42 = u20-srv-MEDIUM-2988

**Comment by holta** [comment]
> 10.8.0.42 = u20-srv-MEDIUM-2988

Above install was successful: http://sprunge.us/OIKBqH?en

A BIG-sized install (onto 32-bit Raspberry Pi OS Lite, on RPi 4) will take much longer, and is ongoing here:

- 10.8.0.46 = 183-rpi4-lite-BIG-2988

**Comment by holta** [comment]
> > 10.8.0.42 = u20-srv-MEDIUM-2988
> 
> Above install was successful: http://sprunge.us/OIKBqH?en

Also Good News: the above was upgraded to BIG-sized, by putting the larger [/etc/iiab/local_vars.yml](http://FAQ.IIAB.IO#What_is_local_vars.yml_and_how_do_I_customize_it.3F) in place, and then running `cd /opt/iiab/iiab` and `sudo ./iiab-configure` &mdash; which completed without a hitch.

Its new name is: u20-srv-BIG-2988

**Comment by holta** [comment]
> A BIG-sized install (onto 32-bit Raspberry Pi OS Lite, on RPi 4) will take much longer, and is ongoing here:
> 
> * 10.8.0.46 = 183-rpi4-lite-BIG-2988

1) Above install also worked great.

2) IIAB installs onto Debian and Mint should definitely work A-Ok too, but as always let's keep an eye on things as broader community-testing kicks in.

3) While also looking out for further/continuous improvement, e.g. one longer-term idea might be to:

   - Dramatically simplify by completely getting rid of the flood of all vars like `is_ubuntu_2204` &mdash; and instead consider consolidating around 1 single var (VERSION_ID, from `/etc/os-release`) &mdash; that can be used for numerical/version comparisons within Ansible (e.g. wherever a Minumum and/or Maximum OS version number needs to be verified or enforced, for whatever reason...)

**Comment by holta** [comment]
Good enough for now!

Follow-on PR's can make this distro-logic and associated vars dramatically more concise and understandable as we move forward in coming days/years.

**Comment by jvonau** [comment]
> Yes this fine-grained approach inherently creates more ongoing maintenance burden (i.e. complexity, VERY BAD!)

Hogwash, there is no ongoing maintenance once the OS file is created.

> However, in this case the dominance of Ubuntu means we have to face this ugly reality, e.g. people getting emotionally attached to interim non-LTS Ubuntu releases. Since this is the community reality ("communities love bikeshedding") ponying up and paying the price is the most pragmatic way forward — to avoid endless future soap operas — e.g. if October 2022's Ubuntu 22.10 has very different {PHP, PostgreSQL, Python, etc} than April 2022's Ubuntu 22.04 etc.

More dribble, get off the soapbox.

**Comment by holta** [comment]
Ansible's most useful built-in variable (fact scraped from systemd-compliant `/etc/os-release`) in these situations, is:

```
ansible_distribution_version
```

Of course there are many other/similar Ansible variables / facts if absolutely necessary.

But the above is the most important, when streamlining & cleaning up these aspects of IIAB's code base in future (now that Ansible is very stable, there is no need to try to outsmart them, using our own scraping/parsing of `/etc/os-release`).

SUMMARY: The 2 links below are a bit dated, but give a decent overview of the situation in recent years...

https://raymii.org/s/tutorials/Ansible_-_Only_if_on_specific_distribution_or_distribution_version.html :

```
when: ansible_distribution == 'CentOS' and ansible_distribution_version == '6.4'

when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'precise'

when: ansible_distribution == 'Debian' and ansible_distribution_version == '7'

when: ansible_os_family == "RedHat" and ansible_lsb.major_release|int >= 5
```

https://www.claudiokuenzler.com/blog/989/ansible-linux-distribution-release-discovery-handle-ubuntu-20.04 :

```
ansible@ansibleserver:~$ ansible ubuntu1604 -m setup | grep distribution
        "ansible_distribution": "Ubuntu",
        "ansible_distribution_file_parsed": true,
        "ansible_distribution_file_path": "/etc/os-release",
        "ansible_distribution_file_variety": "Debian",
        "ansible_distribution_major_version": "16",
        "ansible_distribution_release": "xenial",
        "ansible_distribution_version": "16.04",
```

**Pull request merged**
