### PR TITLE
Fpm asterisk

### PR DESCRIPTION
**Pull request by jvonau**
Looks promising
```
ubuntu@box:/opt/iiab/iiabsudo systemctl status php7.4-fpm.service 
● php7.4-fpm.service - The PHP 7.4 FastCGI Process Manager
     Loaded: loaded (/lib/systemd/system/php7.4-fpm.service; enabled; vendor preset: enabled)
     Active: active (running) since Mon 2021-08-09 13:44:29 CDT; 43min ago
       Docs: man:php-fpm7.4(8)
    Process: 123688 ExecStartPost=/usr/lib/php/php-fpm-socket-helper install /run/php/php-fpm.sock /etc/php/7.4/fpm/pool.d/www.conf 74 (code=exited, status=0>
   Main PID: 123662 (php-fpm7.4)
     Status: "Processes active: 0, idle: 24, Requests: 0, slow: 0, Traffic: 0req/sec"
      Tasks: 25 (limit: 4136)
     CGroup: /system.slice/php7.4-fpm.service
             ├─123662 php-fpm: master process (/etc/php/7.4/fpm/php-fpm.conf)
             ├─123664 php-fpm: pool asterisk
             ├─123665 php-fpm: pool asterisk
             ├─123666 php-fpm: pool asterisk
             ├─123667 php-fpm: pool asterisk
             ├─123668 php-fpm: pool asterisk
             ├─123669 php-fpm: pool asterisk
             ├─123670 php-fpm: pool asterisk
             ├─123671 php-fpm: pool asterisk
             ├─123672 php-fpm: pool asterisk
             ├─123673 php-fpm: pool asterisk
             ├─123674 php-fpm: pool asterisk
             ├─123675 php-fpm: pool asterisk
             ├─123676 php-fpm: pool www
             ├─123677 php-fpm: pool www
             ├─123678 php-fpm: pool www
             ├─123679 php-fpm: pool www
             ├─123680 php-fpm: pool www
             ├─123681 php-fpm: pool www
             ├─123682 php-fpm: pool www
             ├─123683 php-fpm: pool www
             ├─123684 php-fpm: pool www
             ├─123685 php-fpm: pool www
             ├─123686 php-fpm: pool www
             └─123687 php-fpm: pool www

```
fastcgi_pass should use the the socket where asterisk is running as the user.

### CODE REVIEW

**Comment by holta** [comment]
@lemueldsouza please take a look!

Possibly this is a critical piece to getting FreePBX 16 (etc) working with PHP 7.4?  Re:

- PR #2896
- PR #2899
- PR #2916

**Comment by jvonau** [comment]
Not really 7.4 that is reported to be working under apache, but rather under nginx only where the noted asterisk www-data cron errors are reported when saving new settings.

**Comment by holta** [comment]
> Not really 7.4 that is reported to be working under apache, but rather under nginx only where the noted asterisk www-data cron errors are reported when saving new settings.

Ah.  Backstory for others...the [cron](https://crontab.guru/) issue was reported 3 days ago here:

- https://github.com/iiab/iiab/pull/2916#issuecomment-894585322

**Comment by jvonau** [comment]
These are not nginx related but the path /etc/radiusclient-ng/radiusclient.conf noted below does not exist related to radiuscfg mentioned in #2905
```
root@box:/opt/iiab/iiab# cat /var/log/asterisk/messages 
[Aug  9 17:07:11] Asterisk 18.5.1 built by root @ box.lan on a x86_64 running Linux on 2021-08-09 20:57:39 UTC
[Aug  9 17:07:12] NOTICE[78665] loader.c: 339 modules will be loaded.
[Aug  9 17:07:12] NOTICE[78665] res_config_ldap.c: No directory user found, anonymous binding as default.
[Aug  9 17:07:12] ERROR[78665] res_config_ldap.c: No directory URL or host found.
[Aug  9 17:07:12] ERROR[78665] res_config_ldap.c: Cannot load LDAP RealTime driver.
[Aug  9 17:07:12] ERROR[78665] res_config_pgsql.c: PostgreSQL RealTime: Failed to connect database asterisk on 127.0.0.1: 
[Aug  9 17:07:12] WARNING[78665] res_config_pgsql.c: PostgreSQL RealTime: Couldn't establish connection. Check debug.
[Aug  9 17:07:12] NOTICE[78665] cdr.c: CDR simple logging enabled.
[Aug  9 17:07:12] NOTICE[78665] res_smdi.c: No SMDI interfaces are available to listen on, not starting SMDI listener.
[Aug  9 17:07:12] WARNING[78665] res_phoneprov.c: Unable to find a valid server address or name.
[Aug  9 17:07:12] NOTICE[78665] chan_skinny.c: Configuring skinny from skinny.conf
[Aug  9 17:07:12] ERROR[78665] ari/config.c: No configured users for ARI
[Aug  9 17:07:12] NOTICE[78665] confbridge/conf_config_parser.c: Adding default_menu menu to app_confbridge
[Aug  9 17:07:12] NOTICE[78665] cel_radius.c: Cannot load radiusclient-ng configuration file /etc/radiusclient-ng/radiusclient.conf.
[Aug  9 17:07:12] WARNING[78665] cel_pgsql.c: CEL pgsql config file missing global section.
[Aug  9 17:07:12] NOTICE[78665] cel_custom.c: No mappings found in cel_custom.conf. Not logging CEL to custom CSVs.
[Aug  9 17:07:12] NOTICE[78665] cdr_radius.c: Cannot load radiusclient-ng configuration file /etc/radiusclient-ng/radiusclient.conf.
[Aug  9 17:07:12] NOTICE[78665] cdr_pgsql.c: cdr_pgsql configuration contains no global section, skipping module load.
[Aug  9 17:07:12] NOTICE[78665] cel_tds.c: cel_tds has no global category, nothing to configure.
[Aug  9 17:07:12] WARNING[78665] cel_tds.c: cel_tds module had config problems; declining load
[Aug  9 17:07:12] WARNING[78665] loader.c: Some non-required modules failed to load.
[Aug  9 17:07:12] WARNING[78665] loader.c: Module 'res_monitor' has been loaded but may be removed in a future release. Its replacement is 'app_mixmonitor'.
[Aug  9 17:07:12] WARNING[78665] loader.c: Module 'res_adsi' has been loaded but may be removed in a future release.
[Aug  9 17:07:12] WARNING[78665] loader.c: Module 'app_ices' has been loaded but may be removed in a future release.
[Aug  9 17:07:12] WARNING[78665] loader.c: Module 'app_macro' has been loaded but may be removed in a future release. Its replacement is 'app_stack (GoSub)'.
[Aug  9 17:07:12] WARNING[78665] loader.c: Module 'app_adsiprog' has been loaded but may be removed in a future release.
[Aug  9 17:07:12] WARNING[78665] loader.c: Module 'app_image' has been loaded but may be removed in a future release.
[Aug  9 17:07:12] WARNING[78665] loader.c: Module 'app_getcpeid' has been loaded but may be removed in a future release.
[Aug  9 17:07:12] WARNING[78665] loader.c: Module 'app_nbscat' has been loaded but may be removed in a future release.
[Aug  9 17:07:12] WARNING[78665] loader.c: Module 'chan_oss' has been loaded but may be removed in a future release.
[Aug  9 17:07:12] WARNING[78665] loader.c: Module 'app_url' has been loaded but may be removed in a future release.
[Aug  9 17:07:12] ERROR[78665] loader.c: cel_radius declined to load.
[Aug  9 17:07:12] ERROR[78665] loader.c: cdr_sqlite3_custom declined to load.
[Aug  9 17:07:12] ERROR[78665] loader.c: cdr_tds declined to load.
[Aug  9 17:07:12] ERROR[78665] loader.c: cdr_radius declined to load.
[Aug  9 17:07:12] ERROR[78665] loader.c: cdr_pgsql declined to load.
[Aug  9 17:07:12] ERROR[78665] loader.c: cel_tds declined to load.
[Aug  9 17:07:12] ERROR[78665] loader.c: cel_sqlite3_custom declined to load.

```

**Comment by jvonau** [comment]
root@box:/opt/iiab/iiab# pastebinit -b sprunge.us < /var/log/asterisk/full
http://sprunge.us/EsnwOz
>[2021-08-09 18:28:54] VERBOSE[101509] loader.c: Reloading module 'res_odbc.so' (ODBC resource)
[2021-08-09 18:28:54] WARNING[101509] res_odbc.c: res_odbc: Error SQLConnect=-1 errno=0 [unixODBC][Driver Manager]Data source name not found, and no default driver specified
[2021-08-09 18:28:54] NOTICE[101509] res_odbc.c: Registered ODBC class 'asteriskcdrdb' dsn->[MySQL-asteriskcdrdb]
[2021-08-09 18:28:54] VERBOSE[101509] loader.c: Reloading module 'extconfig' (Configuration)
[2021-08-09 18:28:54] VERBOSE[101509] loader.c: Reloading module 'res_config_odbc.so' (Realtime ODBC configuration)
[2021-08-09 18:28:54] VERBOSE[101509] loader.c: Reloading module 'cdr' (CDR Engine)
[2021-08-09 18:28:54] NOTICE[101509] cdr.c: CDR simple logging enabled.
[2021-08-09 18:28:54] VERBOSE[101509] loader.c: Reloading module 'cdr_adaptive_odbc.so' (Adaptive ODBC CDR backend)
[2021-08-09 18:28:54] WARNING[101509] res_odbc.c: res_odbc: Error SQLConnect=-1 errno=0 [unixODBC][Driver Manager]Data source name not found, and no default driver specified
[2021-08-09 18:28:54] WARNING[101509] cdr_adaptive_odbc.c: No such connection 'asteriskcdrdb' in the 'asteriskcdrdb' section of cdr_adaptive_odbc.conf.  Check res_odbc.conf.

**Comment by jvonau** [comment]
re 842808e
>root@box:/opt/iiab/iiab# pastebinit -b sprunge.us < /opt/iiab/iiab/iiab-install.log
http://sprunge.us/FVnlWA

**Comment by jvonau** [comment]
Good enough for further testing.

**Pull request merged**
