### PR TITLE
Staging of captive portal

### PR DESCRIPTION
**Pull request by jvonau**

### CODE REVIEW

**Comment by georgejhunt** [comment]
I feel the captive portal should be it's own role, and not part of the networking role. Though I recognize that it does add some configuration to dnsmasq, and requires dnsmasq rather than bind9

**Comment by holta** [comment]
@jvonau wrote:
> If CP is to be stand-alone please clarify the use of code in iiab-gen-iptables that is part of the original PR [#1300]

( Let's try to get to the bottom of this during our Wedn call: http://minutes.iiab.io )

**Comment by holta** [comment]
@georgejhunt can you please help @jvonau understand https://github.com/iiab/iiab/blob/master/roles/network/templates/gateway/iiab-gen-iptables#L126-L128 ?

Thanks!

**Comment by holta** [comment]
Discussed with @georgejhunt during today's http://minutes.iiab.io call &mdash; on hold pending @georgejhunt's review of iptables &mdash; possible this iptables rule is causing wider problems ?

**Pull request closed without merging**
