### PR TITLE
3 scripts for IIAB 6.5 & beyond: ansible-2.4.x + ansible-2.5.x + scripts/ansible

### PR DESCRIPTION
**Pull request by holta**
Ansible 2.5.0 smoke-tested on Raspbian Lite 2018-03-13 (medium-sized local_vars.yml) and Ubuntu 16.04 (big-sized local_vars.yml).

Ref's
#669 "is Ansible 2.4.3 running out of memory when installing IIAB 6.5/master on RPi3?"
#698 "Ansible fails to enable iiab-cmdsrv on ubuntu-18 -- maybe other os's"

### CODE REVIEW

**Comment by holta** [comment]
Warning: our /opt/iiab/iiab/ansible.cfg is diverging more and more from the official /etc/ansible/ansible.cfg and needs a sanity check in such areas as:
```
system_warnings = False   #let's restore the default (True)
deprecation_warnings = False   #let's restore the default (True)
```
Thanks @jvonau for the warning here:
https://docs.ansible.com/ansible/devel/reference_appendices/config.html

**Comment by holta** [comment]
> Warning: our /opt/iiab/iiab/ansible.cfg is diverging more and more from the official /etc/ansible/ansible.cfg

After thinking about it, @jvonau recommends removing /opt/iiab/iiab/ansible.cfg entirely.  Let's trial this approach (hewing closer to the Ansible community's actual defaults, to keep IIAB config files from bitrotting too far away from mainline usage).

If so: where should IIAB-specific customizations be stored?  Who knows how many of these are critical??  e.g. are things like [Lines 16-17 of /opt/iiab/iiab/ansible.cfg](https://github.com/iiab/iiab/blob/master/ansible.cfg#L16-L17) (pasted in below) still important?
```
remote_tmp     = /opt/iiab/iiab/.ansible/tmp
local_tmp = /opt/iiab/iiab/.ansible/tmp
```

**Comment by jvonau** [comment]
Yes, I agree, that is why in chat I suggested the removal of the file from the git repo and replaced with a readme on ansible's over-rides or maybe auto creation of ansible.cfg from scripts/ansible should iiab even be need to use an override in the future. Less is better IMHO. Leaving the override in place cleans up the feedback but hides bit-rot.

**Comment by holta** [comment]
Should we start fresh, with a new /opt/iiab/iiab/ansible.cfg containing just these 2 lines?
```
remote_tmp = /opt/iiab/iiab/.ansible/tmp
local_tmp = /opt/iiab/iiab/.ansible/tmp
```
(Or is it possible the above are no longer needed?)

**Comment by jvonau** [comment]
That change was for a [bug](https://github.com/ansible/ansible/pull/18551) in ansible that has since been fixed, so I believe no longer needed.

**Comment by holta** [comment]
/opt/iiab/iiab/ansible.cfg → /opt/iiab/iiab/ansible.cfg.deprecated

(Experimental renaming is now part of this PR #711 &mdash; plz all review the contents of https://github.com/iiab/iiab/blob/master/ansible.cfg for any IIAB customizations that we don't want to lose!)

**Comment by holta** [comment]
Ref from July 4, 2017:
PR #62 "Update ansible.cfg to match upstream" (fix for Ansible 2.2.1 & 2.3.0)

**Comment by jvonau** [comment]
https://github.com/iiab/iiab/issues/300 has a reference to https://github.com/iiab/iiab-admin-console/pull/29 that would affect iiab-admin-console, the symlink in {{ cmdsrv_dir }} should be removed also to evaluate its behaviour with this change in place.

**Comment by holta** [comment]
./[runtags](https://github.com/iiab/iiab/blob/master/runtags) does not work with Ansible 2.5.0, likely due to stale syntax in /opt/iiab/iiab/[iiab.yml](https://github.com/iiab/iiab/blob/master/iiab.yml)

We should try to use the newer syntax similar to /opt/iiab/iiab/[iiab-stages.yml](https://github.com/iiab/iiab/blob/master/iiab-stages.yml) ?

**Comment by holta** [comment]
Thanks to @jvonau and @tim-moody who proposed an empty stub /opt/iiab/iiab/ansible.cfg as follows:
```
# Future overrides of /etc/ansible/ansible.cfg belong in this file.
# Used by iiab-admin-console
```
Which is now part of this PR #711 &mdash; while the original /opt/iiab/iiab/ansible.cfg is safeguarded at /opt/iiab/iiab/ansible.cfg.deprecated

**Comment by holta** [comment]
Plz see @jvonau's summary of Ansible 2.4.x & 2.5.x packages/sites @ https://github.com/iiab/iiab/issues/715#issuecomment-377086655

**Comment by holta** [comment]
All 3 scripts tested.

Makes it easier for [lIAB load scripts](http://download.iiab.io/6.5/rpi/) to toggle between Ansible 2.4, 2.5 and 2.6

REMINDER: downgrading (e.g. from Ansible 2.5.0 to 2.4.x pinning) requires that you remove repo lines from:
- /etc/apt/sources.list
- /etc/apt/sources.list.d/ansible*.list

Specifically, lines like the following would need to be removed: (e.g. to downgraded and pin to Ansible 2.4.x)
- deb http://ppa.launchpad.net/ansible/ansible/ubuntu xenial main
- deb http://ppa.launchpad.net/ansible/ansible-2.5/ubuntu xenial main

**Pull request merged**
