### PR TITLE
Skip yarn add if installed, but allow yarn upgrade if set in local_vars.yml

### PR DESCRIPTION
**Pull request by jvonau**
### Fixes Bug #1812
Install only once to allow faster operation of [iiab-from-console](https://github.com/iiab/iiab/blob/master/iiab-from-console.yml) from the iiab admin page. Allows future upgrades with a fact that can be set via local_vars or some other logic to toggle the fact.

### CODE REVIEW

**Comment by mitra42** [comment]
@jvonau this something I added to my list yesterday so its great ... 
I think there are three cases
a) fresh install of IIAB + IA - we want it to do `yarn install`
b) repeat install of IIAB + IA - we want it to skip 
c) the update case - where I was planning to tell the user to do a `runrole internetarchive` and have it do a `yarn upgrade`.   

I think with your PR the `runrole internetarchive` would be a No-op ? 

(Apologies for any slow response, I'm leaving San Francisco for Australia later today, though I'll probably have a couple of internet windows during between now and arrival Monday evening Australia time (Sunday night US time)

**Comment by jvonau** [comment]
You have to remember that iiab-install, runrole, and admin-console all share the same code from the roles directory. A & B work as is with this revision, while C just requires populating local_vars.yml (or config_vars if the code is in the admin-console for it) with 'internetarchive_upgrade: True' to run the yarn upgrade path with runrole. Warning while testing I did run into the same kind of failure as in #1915 but using yarn upgrade under runrole.

**Comment by mitra42** [comment]
Yes - this all makes sense except asking people to edit config files ... which I suspect will lead to failures. Feel free to accept the PR thought, I can leave the instructions I give people as 
```
cd /opt/iiab/internetarchive && yarn upgrade
```
rather than telling them to use runrole. 

Note, I'm presuming there is no way to tell pass this arg to runrole.

**Comment by jvonau** [comment]
Um, I changed runrole to take --reinstall as an optional argument and pass that info to ansible covering option C.  Without --reinstall runrole internetarchive will behave like A&B above but cover disabling/enabling the service quickly post-install. Now with  runrole --reinstall internetarchive you will run the yarn upgrade code path.

**Comment by mitra42** [comment]
Thanks @jvonau - looks good (at least to my minimal ansible knowledge)

During some testing I noticed that `nodejs` is also reinstalling every time, even if its installed, and takes about 2 or 3 minutes even on a fast link - it might be worth using a similar technique there (and on `yarn`, though that only takes about a minute to reinstall each time)

**Comment by jvonau** [comment]
> During some testing I noticed that `nodejs` is also reinstalling every time, even if its installed, and takes about 2 or 3 minutes even on a fast link - it might be worth using a similar technique there (and on `yarn`, though that only takes about a minute to reinstall each time)

There is a minor speedup with PR #1920 with skipping the setup of nodesources.list. Little background on ansible's package module's state: latest verses state: present, using 'present' just checks if the packages are installed and skips the install if already present while 'latest' will force an upgrade to the newest when the newest is not installed. We have to use latest in those roles to install the newest packages offered from the third party repos as the stock distro might have already installed a lessor version of the requested package.

**Comment by mitra42** [comment]
Agreed regarding `latest`, but note I test by doing the runrole and then immediately repeating the runrole so that any time is purely 'wasted' time, rather than a legitimate upgrade.

**Comment by mitra42** [comment]
@jvonau I've been investigating this more as I write install scripts for other platforms. (esp OrangePi/Armbian). I discovered the 'right' combo is .... 
If not already installed `yarn install`
If already installed `yarn install; yarn upgrade` 

The install runs really quickly if there is nothing to do, but catches cases where something new has been added or a version dependency changed. 

I'm not sure how to do this in the ansible? 
Note - I also posted a request for someone with a 1GB RPI4 to test with a config change to yarn - its in https://github.com/iiab/iiab/issues/1931, I don't have such a machine to test on.

**Pull request merged**
