### PR TITLE
WIP: MongoDB Spring Cleaning (bug fixes) for #3236

### PR DESCRIPTION
**Pull request by holta**
See in-line comments explaining, to begin to resolve:

- #3236

Building on:

- PR #3214

### CODE REVIEW

**Comment by holta** [comment]
FYI @nzola this fix is tested on Raspberry Pi 4, so I'm merging this now to help you get back on track.

But note this is likely NOT the final word!

_As I'd like to make this even more resilient in coming days &mdash; preferably with input from @jvonau and others._

**Comment by jvonau** [comment]
https://github.com/docker-library/mongo/issues/485#issuecomment-891991814 The 5.X mongodb issue is going to bubble over into Intel/AMD land also with the minimum cpu requirements that comes with 5.X.

**Comment by GermanAizek** [comment]
@jvonau,
Most likely this is due to the fact that MongoDB 5.0+ requires AVX instructions, to solve this problem you need to build with my patch, or edit SConstruct build configuration file yourself.
https://github.com/GermanAizek/mongodb-without-avx

**Comment by holta** [comment]
@GermanAizek thank you for the tip!

Just FYI IIAB currently uses MongoDB 5.0 on 64-bit ARM and MongoDB 6.0 on 64-bit Intel/AMD:

- PR #3481
- PR #3483

**Comment by tim-moody** [comment]
Is this the problem?

https://www.makeuseof.com/what-is-avx-512-why-intel-killing-it/

**Pull request merged**
