### PR TITLE
Fix for Graphical and TTY Logins [clean up auto-checking for iiab-admin's published password]

### LINKED ISSUE #2561: TK: Installing IIAB blocks most logins, except for sudoers with NOPASSWD: set [EXCEPTIONS: (1) RaspiOS graphical logins work (2) sudoers can survive non-graphical logins by typing in their passwords twice]
@jvonau is monitoring TK Kang's progress in understanding the problem, which has been reproduced ~3 times now on Ubuntu 20.04 VM's and PC's.

### PR DESCRIPTION
**Pull request by holta**
Resolves #2561 and its very serious `sudo` problem.

By greatly simplifying `/etc/profile.d/sshpwd-profile-iiab.sh` since the prior version was quite broken, for those with graphical desktops especially, as TK & @shanti-bhardwa confirmed.

Needs more testing on more OS's than just Ubuntu Desktop 20.04.1 (where it was smoke-tested & functionality tested) so this important fix can hopefully be merged in short order.

Refs: #1252, PR #1253, #1537, PR #1551, #2432, PR #2434, PR #2571

### CODE REVIEW

**Comment by tim-moody** [comment]
iiab-admin is soft coded in iiab_admin_user: iiab-admin

**Comment by holta** [comment]
1) I will be reinforcing [sshpwd-lxde-iiab.sh](https://github.com/iiab/iiab/blob/master/roles/iiab-admin/templates/sshpwd-lxde-iiab.sh) as well, which is not nearly as vulnerable, but has longstanding problems as well.

2) I'm trying to find the equipment and/or a volunteer to test this on 'RaspiOS with desktop' this wkd &mdash; so we have very solid coverage on 2 mainline graphical OS's.

3) [Debian 10 (incl Graphical Desktop) and Linux Mint 20](https://github.com/iiab/iiab/wiki/IIAB-Platforms#operating-systems) testing would be really great on top of the above, as a Stretch Goal if more volunteers can help, now or in coming months!

**Comment by holta** [comment]
Tested with a fresh install on 'RaspiOS with desktop' on RPi 4.

Looking good to merge soon for IIAB 7.2 RC3, with testing on more graphical and headless OS's en route.

**Comment by holta** [comment]
> /etc/sudoers.d/* files should have permission 0440 ...
@tim-moody: if possible make this same change for roles/js-menu/templates/021_apache_set_time.j2

Background - sudo asks that these files all be 0440:

https://www.apt-browse.org/browse/ubuntu/trusty/main/amd64/sudo/1.8.9p5-1ubuntu1/file/etc/sudoers.d/README

**Comment by holta** [comment]
i.e. https://github.com/iiab/iiab-admin-console/blob/master/roles/js-menu/tasks/main.yml#L133 is currently:

```
mode: 0644
```

It should be:

```
mode: 0440
```

**Comment by holta** [comment]
> Tested with a fresh install on 'RaspiOS with desktop' on RPi 4.
> 
> Looking good to merge soon for IIAB 7.2 RC3, with testing on more graphical and headless OS's en route.

This revised PR has also now been re-tested on Ubuntu Desktop 20.04.1.

All logins should now work (both graphical & tty logins) unimpeded by problems arising from `/etc/profile.d/sshpwd-profile-iiab.sh` and `/etc/xdg/lxsession/LXDE-pi/sshpwd-lxde-iiab.sh`

Regardless whether an implementer prefers to set up their `iiab-admin` account(s) with sudo in either of its forms (sudo with password...or sudo with `NOPASSWD:` set in `/etc/sudoers` or `/etc/sudoers.d`).

Recap: when/if setting up the `iiab-admin` i.e. {{ iiab_admin_user }} user, this PR also...

- Dispenses with the `wheel` group to reduce complexity
- Uses the `sudo` group alone
- Avoids setting sudo's `NOPASSWD:` flag for the user and the group
- Softcodes {{ iiab_admin_user }} in yet more places (let's keep the core notion of `iiab-admin` community understandability front-row center, wherever this heads next, yes we have many options going forward as is currently being discussed on #2561 !)  _In Short: "if a product is not understandable, it is not a product, it is ignored..." :/_

Summary: as part of this PR, [roles/iiab-admin/tasks/admin-user.yml](https://github.com/iiab/iiab/blob/master/roles/iiab-admin/tasks/admin-user.yml) has been put on a diet for the sake of understandability &mdash; which leads to better security &mdash; at very level (:

**Pull request merged**
