### PR TITLE
RTC Fixes

### PR DESCRIPTION
**Pull request by jvonau**
### Fixes Bug
#2270

### CODE REVIEW

**Comment by holta** [comment]
See also:

#2288 "RTC routine 2 issues"

**Comment by jvonau** [comment]
9d331e8  is required if somebody wants to use BT keyboard/mouse

**Comment by holta** [comment]
@jvonau @georgejhunt what tests are most important to evaluate/review this?

**Comment by holta** [comment]
Smoke-tested by @jvonau on RPi 4 on both OS's: Ubuntu 20.04 pre-release & Raspbian.

**Pull request merged**
