### PR TITLE
silence pip upgrade nag

### PR DESCRIPTION
**Pull request by jvonau**
alternate to #164

### CODE REVIEW

**Comment by holta** [comment]
I can't claim to understand this in full, but FYI @georgejhunt expressed his preference that we stick with Ansible 2.2.0 for IIAB 6.4 during this morning's call.

I did not hear any complaints (or words of support) from @tim-moody so hopefully he can weigh in as well?

FWIW Ansible 2.2.0 works for me, so we can get IIAB solid+reliable quickly in September, and then presumably upgrade Ansible for IIAB 6.5 in November or some such...

**Comment by jvonau** [comment]
At least consider suppressing the pip upgrade check, people see that and
panic while it is not really required to be preformed. Would sort of help
with CentOS, but it seems that things are pip happy in the code base. I'm
starting not to care as nobody else wants to put out a quality polished
product.

**Comment by holta** [comment]
Can't claim to understand pip :/ but I've added this to the agenda for Monday's call @ http://minutes.iiab.io

**Comment by jvonau** [comment]
Automated testing would prefer not to be prompted for action
From [xsce-devel](https://groups.google.com/forum/#!topic/xsce-devel/gONb4q6xT3g)
>  # Installs the correct version of Ansible
      I was prompted to upgrade my pip version from 8.1.1 to 9.0.1
      Pip install --upgrade pip

**Pull request closed without merging**
