### PR TITLE
Branch Maps7.3 -- includes 2020 OSM data and 2020 satellite images

### PR DESCRIPTION
**Pull request by georgejhunt**
Tested on Ubuntu vbox, and rpi hardware, San_Jose, Spanish_speakers, Central_America, and tested on my repo. Needs to be coordinated with branch maps7.3 into the iiab/maps rep. This is a test version and cannot be pulled into master without modification to roles/osm-vector-maps/defaults/main.yml.

Code for generation is a jupyter notebook at https://github.com/georgejhunt/maps/blob/maps7.3/osm-source/jupyter-code/maps.ipynb.

Notes: For 2020 (this version) are at  https://github.com/georgejhunt/maps/blob/maps7.3/osm-source/jupyter-code/README.md

### CODE REVIEW

**Comment by holta** [comment]
Looks great!  If anybody's reviewing this, see also its partner PR here:

- PR iiab/maps#45

And this point form (8 bullets) summary:

- "How does History explain some of the MAP quirks?"<br>https://github.com/georgejhunt/maps/blob/maps7.3/osm-source/jupyter-code/README.md

**Comment by jvonau** [comment]
Not that upgrades are supported given admin-console would need to be reinstalled also.. Is there any harm other than taking up space in having the older 2019 files laying around the filesystem? I pulled this PR and just did a `sudo ./runrole --reinstall osm-vector-maps` on an install that never installed additional regions via the admin-console, what needed to be updated was marked 'changed'.

**Comment by tim-moody** [comment]
So no backwards compatibility? Once you install iiab that's the osm version you get. Same for adm cons. If you try to reinstall with a new version it may or may not work.

**Comment by holta** [comment]
See also George's:

- PR iiab/maptools#4
- https://github.com/georgejhunt/maptools/blob/main/README.md

**Comment by holta** [comment]
@georgejhunt a side question:

Is it possible...these 2 can be deleted?

- http://timmoody.com/iiab-files/maps.    # Looks like a typo (stray "dot" on the right)
- http://timmoody.com/iiab-files/maps/planet_z0-z5.mbtiles

Or is that last one useful?

**Comment by holta** [comment]
@georgejhunt what remaining testing is needed if any — prior to merging this PR?

Related Admin Console PR:

- PR iiab/iiab-admin-console#478

**Pull request merged**
