### PR TITLE
6.4 needs the most-tested local_vars.yml (medium-sized) + restore 5-xo-services to iiab.yml

### PR DESCRIPTION
**Pull request by holta**

### CODE REVIEW

**Comment by holta** [comment]
As smoke-tested and functionality-tested dozens of times in the past week from:
http://download.iiab.io/6.4/rpi/local_vars.yml
http://wiki.laptop.org/go/IIAB/local_vars.yml

**Comment by holta** [comment]
I'll merge this in coming minutes if there are no objections.

**Comment by holta** [comment]
This PR also restores "5-xo-services" in iiab.yml, after SMS consultation with George (per our earlier agreement to allow & encourage experimentation among all XO/Sugar users!)

**Comment by holta** [comment]
The extra 10-15 min to install 5-xo-services during every RPi3 run is one giant pain in the wazoo...

(Am personally VERY tempted to rip this back out before shipping 6.4, and document how to uncomment [Line 16 of /opt/iiab/iiab.yml](https://github.com/iiab/iiab/blob/d3b487fe1d95586eb1cda4158c608c6538bdc80d/iiab.yml#L16) for @germanrs and those who still need XO services &mdash; unless others have objections??)

**Comment by jvonau** [comment]
Might want to revive #117? At least ejabberd becomes installable as it lives under the 5-xo-services umbrella. And one for the experimentation crowd #143. Feel free to hit the restore button if you want further discussion on those PRs

**Pull request merged**
