### PR TITLE
FreePBX fixes and changes

### PR DESCRIPTION
**Pull request by m-anish**
* Patches upstream freepbx bug which hasn't been fixed yet
* Moves pbx.lan -> box.lan:8888
* Fixes documentation accordingly

### CODE REVIEW

**Comment by holta** [comment]
Replaces PR #1686 towards solving #1685

**Comment by tim-moody** [comment]
can't break the 8000 habit

**Comment by holta** [comment]
@web-anish

1) plz verify "5060, 5160, 5161, 8888, 10000-20000" are correct and that all are TCP in https://github.com/iiab/iiab/wiki/IIAB-Networking#list-of-ports--services ?  _**[Done]**_

2) Supposedly 8888 is already used by "Default for IPython / Jupyter notebook dashboards" according to https://en.wikipedia.org/wiki/List_of_TCP_and_UDP_port_numbers#Registered_ports

(Do we / @mikkokotila care?)

**Comment by holta** [comment]
Emailed @mikkokotila to try to quickly clear this up, so @m-anish can finalize a port number.

@tim-moody suggests possibly considering port 10080.

**Comment by holta** [comment]
> @tim-moody suggests possibly considering port 10080.

Already taken by AzuraCast (PR #1733) per https://github.com/iiab/iiab/wiki/IIAB-Networking#list-of-ports--services

**Comment by mikkokotila** [comment]
8888 is the default for Jupyter, but I think it automatically goes to the next available if 8888 is already in use. I'm not 100% on how this plays out in different systems, but I guess it would be like that across the board. Still to be safe, maybe use other than 8888.

**Comment by holta** [comment]
> 8888 is the default for Jupyter, but I think it automatically goes to the next available if 8888 is already in use. I'm not 100% on how this plays out in different systems, but I guess it would be like that across the board. Still to be safe, maybe use other than 8888.

Agreed!  Let's go with 83 as suggested by @tim-moody, that Anish has documented here: https://github.com/iiab/iiab/wiki/IIAB-Networking#list-of-ports--services

**Comment by holta** [comment]
I've updated the following from 8888 to 83:

http://FAQ.IIAB.IO Item 9 "What services (IIAB apps) are suggested during installation?"

**Pull request merged**
