### PR TITLE
MediaWiki 1.30.0 -> 1.31.0 LTS

### PR DESCRIPTION
**Pull request by holta**

### CODE REVIEW

**Comment by holta** [comment]
Is it possible clean installs of 1.31.0 work, and that it's just the upgrades from 1.30.0 to 1.31.0 that are failing?

(Of course we want both to work in the end!)

PS dropping the database (iiab_mediawiki) is *not* sufficient to move from 1.30.0 to 1.31.0 (on Ubuntu 18.04 anyway!)

**Comment by holta** [comment]
"./runrole mediawiki" ran on 10.8.0.46 (RPi 3 B+) trying to add MediaWiki 1.31 onto a clean MEDIUM-sized IIAB, that never contained MediaWiki.

The error is the same ("Alert!: HTTP/1.0 500 Internal Server Error") as during the upgrade attempt earlier this morning (when trying to visit http://localhost/mediawiki using lynx, a non-graphical browser).

**Comment by holta** [comment]
@tim-moody summarizes (below) the flaw with MediaWiki 1.31.0 &mdash; in the interim one can comment out ~2 lines from /library/mediawiki-1.31.0/LocalSettings.php as follows:
```
# Enabled skins.
# The following skins were automatically enabled:
#wfLoadSkin( 'CologneBlue' );
#wfLoadSkin( 'Modern' );
wfLoadSkin( 'MonoBook' );
wfLoadSkin( 'Vector' );
```

> I wonder if it is broken, since it enables skins it doesn't supply

> https://www.mediawiki.org/wiki/Skin:Cologne_Blue

> root@box:~# ls -lav /library/mediawiki-1.31.0/skins/
> total 24
> drwxr-xr-x  5 root www-data 4096 Jun 13 17:19 .
> drwxr-xr-x 15 root www-data 4096 Jun 14 22:16 ..
> drwxr-xr-x  6 root www-data 4096 Jun 13 17:20 MonoBook
> -rwxr-xr-x  1 root www-data 1208 Jun 13 17:19 README
> drwxr-xr-x  5 root www-data 4096 Jun 13 17:20 Timeless
> drwxr-xr-x  8 root www-data 4096 Jun 13 17:20 Vector

> no CologneBlue

**Comment by holta** [comment]
Informative MediaWiki 1.31.0 Release Notes:
https://www.mediawiki.org/wiki/Release_notes/1.31

**Comment by holta** [comment]
@tim-moody "Starting from MediaWiki 1.31, the Cologne Blue skin has been removed from the bundle." according to official doc https://www.mediawiki.org/wiki/Skin:Cologne_Blue

Likewise "Starting from MediaWiki 1.31, the Modern skin has been removed from the bundle." according to official doc https://www.mediawiki.org/wiki/Skin:Modern

Can we permanently comment out or remove [Lines 125 and 126 of roles/mediawiki/templates/LocalSettings.php.j2](https://github.com/iiab/iiab/blob/master/roles/mediawiki/templates/LocalSettings.php.j2#L125-L126) now, so this PR can be merged?

**Comment by holta** [comment]
Smoke-tested & functionality-tested on Ubuntu 18.04/Server.

Further testing on Raspbian would be great!

**Comment by holta** [comment]
@tim-moody does this MediaWiki playbook possibly handle upgrades of mysql DB "iiab_mediawiki" ?

(Either 1.30.0 to 1.31.0 LTS, or future DB/schema upgrades?)

**Comment by tim-moody** [comment]
we don't do this for any of our playbooks

**Pull request merged**
