### PR TITLE
Kiwix for i586 and i686 - towards resolving #864 & #865

### PR DESCRIPTION
**Pull request by holta**
@arky can you test this PR please?

As I don't have access to the requisite hardware, Thanks!

### CODE REVIEW

**Comment by holta** [comment]
FYI this PR attempts to resolve kiwix-tools' changing filename/compression (.bz2->.gz) as summarized in #864 & kiwix-tools' changing internal file structure (bin directory is no longer included) as summarized in #865.

**Comment by holta** [comment]
> @arky can you test this PR please?
>
> As I don't have access to the requisite hardware, Thanks!

CLARIF this should do it...providing the basic smoke-test we need to merge this PR:
```
cd /opt/iiab/iiab
git checkout -b holta-kiwix-i586 master
git pull https://github.com/holta/iiab.git kiwix-i586
./iiab-install --reinstall
```

**Comment by holta** [comment]
@arky I will merge this now as it smoke-tested on Raspbian and Ubuntu 18.04, but you really do need to smoke-test ( and functional test http://box/kiwix/ ) on the i586/i686 architecture, so we know if this is accomplishing anything, Thanks!

**Comment by arky** [comment]
@holta Patch works as expected on i586. The kiwix-tools is downloaded and uncompressed properly. Thanks! 
   
   
pi@box:/opt/iiab/iiab$ ls -l ../kiwix
total 4
drwxr-xr-x 2 root root 4096 Jul  8 07:30 bin
pi@box:/opt/iiab/iiab$ ls -l ../kiwix/bin/
total 234112
-rwxrwxr-x 1 root root 96083578 Jun 20 10:00 kiwix-manage
-rwxrwxr-x 1 root root 21611088 Jun 20 10:00 kiwix-read
-rwxrwxr-x 1 root root 23151922 Jun 20 10:00 kiwix-search
-rwxrwxr-x 1 root root 98876235 Jun 20 10:00 kiwix-serve

**Pull request merged**
