### PR TITLE
Fix Whitespace warnings in Ansible-lint

### PR DESCRIPTION
**Pull request by arky**
Fixes various whitespace warnings in ansible-lint CI tests.  Fixes some of the problems in #409

### CODE REVIEW

**Comment by holta** [comment]
@arky can u rebase, off of current master?

To avoid accidentally causing many regressions (the 47 proposed "Files changed' would undo many serious improvements from the past few days :)

**Comment by arky** [comment]
@holta Did a rebase and three way merge.

**Comment by holta** [comment]
Something's not working!

Clicking on "Files changed 47" shows this PR still proposes to revert many important improvements from the past few days, having nothing to do with whitespace :/

**Comment by holta** [comment]
@arky I'm sure you have better ways from the command-line...but here's one way to rebase on master (so that you grab the latest bug fixes) when you're away from CLI:

https://www.sitepoint.com/quick-tip-sync-your-fork-with-the-original-without-the-cli/

PS what tool did you use to clean up whitespace out of curiosity?

**Pull request closed without merging**
