### PR TITLE
WIP: Tighten up roles/mongodb — runs 'apt-mark hold mongodb-org mongodb-org-server' on 64-bit RPi if installing MongoDB >= 5.0

### PR DESCRIPTION
**Pull request by holta**
Towards making IIAB's MongoDB install routine more resilient on [all 4 of IIAB's mainline OS's](https://github.com/iiab/iiab/wiki/IIAB-Platforms) &mdash; across the most common CPU architectures:

- #3236
- PR #3238

Tested on RasPiOS Lite on Raspberry Pi 4.

This should be tested much more broadly to verify and further beef up where needed.

Related:

- PR #3040
- PR #3099
- #3190

### CODE REVIEW

**Comment by jvonau** [comment]
Why not just remove the mongo apt repo definition to prevent future upgrades? The net result would be the same as using deb with url as is done with Kolibri.

**Comment by holta** [comment]
> Why not just remove the mongo apt repo definition to prevent future upgrades? The net result would be the same as using deb with url as is done with Kolibri.

It's definitely an idea.

The OS's own apt repos might complicate things in some isolated cases hypothetically however &mdash; by suggesting diverse MongoDB package updates/alternatives that are not wanted hypothetically?

Some version of `apt-mark hold mongodb*` appears to lock MongoDB in place rather simply and also rather strictly (as desired on RasPiOS).

With different OS's deserving different treatment &mdash; trying hard not to allow all this complexity to mushroom beyond nec.

_Certainly I need to sleep on it._

Ref:

- #3217

**Comment by holta** [comment]
Note to self... Ansible's [dpkg_selections](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/dpkg_selections_module.html) module can hold apt packages if nec:

```
- name: Hold mongodb-org-server
  dpkg_selections:
    name: mongodb-org-server
    selection: hold
```

Per https://stackoverflow.com/a/63983134

**Comment by jvonau** [comment]
Better question is what is missing from the 64-bit raspbian_mongodb_5.0.5.gz file that would require installing a binary incomparable version with apt? The new step is not needed with the (much) older 32-bit tar file version installed for RaspiOS.

**Comment by holta** [comment]
> Better question is what is missing from the 64-bit raspbian_mongodb_5.0.5.gz file that would require installing a binary incomparable version with apt? The new step is not needed with the (much) older 32-bit tar file version installed for RaspiOS.

Testing shows there's only 1 file really needed from raspbian_mongodb_5.0.5.gz and that's `/usr/bin/mongod`

(The other 2 files added by raspbian_mongodb_5.0.5.gz don't seem to matter for Sugarizer... but apparently don't hurt...)

- /usr/bin/mongo
- /usr/bin/mongos

So the strategy here is: layer the 1 critical file on top of MongoDB's own 5.0.9 installer (to abstract away all the evolving/finer details across MongoDB's different files/directories, as much as possible — so IIAB intentionally does not try to micromanage...)

**Comment by jvonau** [comment]
Or just install version 4.4.13 of mongodb from the repo, sidestepping the whole cpu issue that comes with 5.X.X as the same kind of cpu issue exists in Intel/AMD land not just on ARM64, mainly because you are targeting the reuse of older hardware. I'll further suggest that sugarizer be removed from auto installing within the medium and large vars files should you continue to go down the 5.X.X path to save pain and suffering for the newbies that may come along in the future with substandard Intel/AMD hardware.

**Comment by holta** [comment]
This PR is now reworked to support softcoding the MongoDB version number to be installed on 64-bit OS's &mdash; set to `mongodb_64bit_version: 4.4` for now:

- With the unfortunate reality that MongoDB 4.0 has already been [EOL'd as of 2022-04-30](https://www.mongodb.com/support-policy/lifecycles).
- So `mongodb_64bit_version: 5.0` and/or `mongodb_64bit_version: 6.0` might potentially become useful over the coming year, among those with "post-2011" CPU's that support AVX instructions:
  - https://github.com/docker-library/mongo/issues/485#issuecomment-891991814

Finally: this PR was tested successfully on Ubuntu 20.04 (Server) x86_64 VM &mdash; http://box/sugarizer works and the PR would appear to be almost ready to merge.

**Comment by holta** [comment]
Tested successfully on Mint 20.3 (graphical desktop) x86_64 VM — http://box/sugarizer works.

**Comment by holta** [comment]
Tested successfully on 64-bit Raspberry Pi OS (Lite) on Raspberry Pi 4 — http://box/sugarizer works.

**Comment by holta** [comment]
Future testing suggestion:

Test shut-down times on 32-bit Raspberry Pi OS e.g. on RPi 3 and 3 B+.

_(...if this older 32-bit OS still matters, now that 64-bit Raspberry Pi OS is becoming increasingly mainline!)_

**Pull request merged**
