### PR TITLE
Dynamically extract python_ver & postgresql_version

### PR DESCRIPTION
**Pull request by holta**
To end the hard-coding of both variables, which were not only bureaucratic but also problematic in certain situations, e.g. as pre-release OS's like Debian 12 Bookworm and Ubuntu 23.04 Lunar Lobster evolve:

- Python version had _both_ been hard-coded (with Ansible, for Lokole template) and dynamically-extracted (using shell call-out python3 itself) e.g. by Lokole.  This rather sloppy approach (violating SSOT, IIAB has been using 2 different potentially contradictory variables `python_ver` and `python_version`) is put to an end, in favor of dynamically-extracting IIAB's Python 3 version, uniformly across the board.

- PostgresSQL version (`postgresql_version`) hard-coding is likewise removed, but unlike above, this is fully contained within its tasks/install.yml

- PHP version (`php_version`) possibly could be dynamically-extracted in future to further simplify (and make IIAB installs yet more resilient) but this PR opts to leave that untouched.

- Ubuntu 20.04 is more fully desupported after almost 3 years, finally.

This PR is tested on the latest Ubuntu 23.04

Refs:

- #3416

### CODE REVIEW

**Comment by tim-moody** [comment]
assumes no venv?

**Comment by holta** [comment]
> assumes no venv?

This PR doesn't change any assumptions regarding IIAB's current venv / virtualenv virtual environments.

(If things are installed in a venv, global IIAB/Ansible variable python_ver can be ignored if one chooses a different version of Python there.)

PS This PR formally makes Python 3 a requirement for IIAB, as explained here:

https://github.com/holta/iiab/blob/b691bd8252a67205f6c6f4c7660fc7c18153b780/scripts/local_facts.fact#L128-L133

**Comment by holta** [comment]
> * PHP version (`php_version`) possibly could be dynamically-extracted in future to further simplify (and make IIAB installs yet more resilient) but this PR opts to leave that untouched.

FYI this will be done in a separate PR.

Possibly by parsing the output of `apt list php` &mdash; so that this works regardless of whether PHP is already installed or not.

**Comment by holta** [comment]
Looks good.  Merging to broaden community testing.

Dynamic extraction of PHP version can follow at a later date &mdash; to make IIAB installs even more resilient a.k.a. antifragile.

**Comment by holta** [comment]
Also successfully tested with a LARGE-sized IIAB install onto Ubuntu Server 22.04

**Review by deldesir — COMMENTED** [review]
Reviewed.

**Review by deldesir — COMMENTED** [review]
Removed

**Comment by deldesir** [comment]
Reviewed them. Ignore my previous confusion (thought I was on 3439)

**Pull request merged**
