### PR TITLE
Python2 fix [for KA Lite on Debian 12 or Ubuntu 23.04 / 23.10]

### PR DESCRIPTION
**Pull request by jvonau**
### Fixes bug:
Replacement for #3530 https://github.com/iiab/iiab/pull/3530#issuecomment-1501603024
### Description of changes proposed in this pull request:
drops the need to install libssl1.1 for python2
### Smoke-tested on which OS or OS's:
U23.04beta and RasPiOS-12 #3526 in PR3530

### CODE REVIEW

**Comment by holta** [comment]
Amazing if a somewhat future-proof method has been found (for those communities that still refuse to give up Python 2-based KA Lite!)

Related / prior work:

- #2680
  - #3289
  - #3399
  - #3450
- #3526
  - PR #3527
  - PR #3530

**Comment by holta** [comment]
In future we might expand this Python 2 retrofit — to apply to Ubuntu 24.04 and Mint 22 / etc as well — and if so, these 2 `when:` clauses below will/would probably be refined & tightened up:

https://github.com/iiab/iiab/blob/4b01b226df6bd846cf5af9203dc2298fbb6de85b/roles/kalite/tasks/install.yml#L13-L25

**Comment by holta** [comment]
@jvonau can you remind me/all what these 2 lines are for?

https://github.com/iiab/iiab/blob/db84a0d03f2c7dc505a8e1b8a29d200f268a17a3/scripts/install_python2.sh#L5-L6

(I'm assuming the above 2 lines are necessary for tangential reasons, somewhat unrelated to Python 2?)

**Comment by jvonau** [comment]
Rather than split out virtualenv from the clause above I just included the installation in the alternate install path conditional. The mime-support package is listed as a dependency when viewing `apt info libpython2.7-stdlib` on U-22.04 and thought it would be best to cover that dependency.

```
jvonau@kickass:/mnt/scratch/git/mk-image$ apt info libpython2.7-stdlib
Package: libpython2.7-stdlib
Version: 2.7.18-13ubuntu1.1
Priority: optional
Section: universe/python
Source: python2.7
Origin: Ubuntu
Maintainer: Ubuntu Core Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Matthias Klose <doko@debian.org>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 9,043 kB
Provides: python-argparse, python2.7-argparse, python2.7-celementtree, python2.7-cjkcodecs, python2.7-ctypes, python2.7-elementtree, python2.7-profiler, python2.7-wsgiref
Depends: libpython2.7-minimal (= 2.7.18-13ubuntu1.1), libssl3 (>= 3.0.0~~alpha1), media-types | mime-support, libbz2-1.0, libc6 (>= 2.34), libcrypt1 (>= 1:4.1.0), libdb5.3, libexpat1 (>= 2.1~beta3), libffi8 (>= 3.4), libncursesw6 (>= 6), libnsl2 (>= 1.0), libreadline8 (>= 7.0~beta), libsqlite3-0 (>= 3.5.9), libtinfo6 (>= 6), libtirpc3 (>= 1.0.2)
Breaks: python-urllib3 (<< 1.9.1-3)
Replaces: libpython2.7-testsuite (<< 2.7.13-4), python2.7 (<< 2.7.5-0~)
Download-Size: 1,977 kB
APT-Sources: http://ca.archive.ubuntu.com/ubuntu jammy-updates/universe amd64 Packages
Description: Interactive high-level object-oriented language (standard library, version 2.7)
 Python is a high-level, interactive, object-oriented language. Its 2.7 version
 includes an extensive class library with lots of goodies for
 network programming, system administration, sounds and graphics.
 .
 This package contains Python 2.7's standard library. It is normally not
 used on its own, but as a dependency of python2.7.
```
Finer point the conditional is 'media-types | mime-support', with the '|' present that becomes an 'or' so either 'provides' would satisfy the requirement.

**Comment by jvonau** [comment]
```
jerryv@U2310arm64:/opt/iiab/iiab$ apt list mime-support
Listing... Done
mime-support/lunar,now 3.66 all [installed]
jerryv@U2310arm64:/opt/iiab/iiab$ apt list media-types
Listing... Done
media-types/lunar,now 10.0.0 all [installed,automatic]

jerryv@U2310arm64:/opt/iiab/iiab$ apt info mime-support
Package: mime-support
Version: 3.66
Priority: optional
Section: net
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Mime-Support Packagers <team+debian-mimesupport-packagers@tracker.debian.org>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 17.4 kB
Depends: mailcap, media-types
Task: ubuntu-desktop-minimal, ubuntu-desktop, ubuntu-desktop-raspi, ubuntu-wsl, kubuntu-desktop, xubuntu-minimal, xubuntu-desktop, lubuntu-desktop, ubuntustudio-desktop-core, ubuntustudio-desktop, ubuntukylin-desktop, ubuntu-mate-core, ubuntu-mate-desktop, ubuntu-budgie-desktop, ubuntu-budgie-desktop-raspi, ubuntu-unity-desktop, edubuntu-desktop-minimal, edubuntu-desktop, edubuntu-desktop-raspi, edubuntu-wsl
Download-Size: 3696 B
APT-Manual-Installed: yes
APT-Sources: http://ports.ubuntu.com/ubuntu-ports lunar/main arm64 Packages
Description: transitional package
 This is a transitional package. It will be possible to remove it
 safely once its dependency chain has adjusted to depend on mailcap
 or media-types directly.

jerryv@U2310arm64:/opt/iiab/iiab$ apt info mailcap
Package: mailcap
Version: 3.70+nmu1ubuntu1
Priority: optional
Section: utils
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Mime-Support Packagers <team+debian-mimesupport-packagers@tracker.debian.org>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 90.1 kB
Provides: run-mailcap
Depends: perl, media-types
Recommends: bzip2, file, xz-utils
Breaks: mime-support (<< 3.65)
Replaces: mime-support (<< 3.65)
Task: ubuntu-desktop-minimal, ubuntu-desktop, ubuntu-desktop-raspi, ubuntu-wsl, mail-server, kubuntu-desktop, xubuntu-minimal, xubuntu-desktop, lubuntu-desktop, ubuntustudio-desktop-core, ubuntustudio-desktop, ubuntukylin-desktop, ubuntu-mate-core, ubuntu-mate-desktop, ubuntu-budgie-desktop, ubuntu-budgie-desktop-raspi, ubuntu-unity-desktop, edubuntu-desktop-minimal, edubuntu-desktop, edubuntu-desktop-raspi, edubuntu-wsl
Download-Size: 23.8 kB
APT-Manual-Installed: no
APT-Sources: http://ports.ubuntu.com/ubuntu-ports lunar/main arm64 Packages
Description: Debian's mailcap system, and support programs
 The mailcap system associates media types with programs that can handle them,
 using system and user configuration files.  A file's media type is determined
 by its extension or by running the "file" command if available.
 .
 Other packages register their programs as viewers/editors/composers/etc by
 placing mailcap entry files or FreeDesktop menu entries in predetermined
 directories monitored by this package's dpkg triggers.
 .
 This package provides a "run-mailcap" program to open arbitrary files, and in
 addition the "see", "edit", "compose", and "print" aliases to display, alter,
 create, and print (respectively).
 .
 This package also provides the "debian-view" utility to handle Debian packages
 interactively.
```
mime-support would be more for a desktop and I would suspect be preinstalled on a desktop install, I could change that to media-types if you like.

**Comment by holta** [comment]
> mime-support would be more for a desktop and I would suspect be preinstalled on a desktop install, I could change that to media-types if you like

Whatever you recommend for reliability / longevity.

**Comment by jvonau** [comment]
Given mime-support is tagged as a transitional package I switched to media-types in the other PR, seems more future proof.

**Comment by jvonau** [comment]
https://github.com/iiab/iiab/pull/3535#issuecomment-1503626474

**Pull request merged**
