### PR TITLE
use iptables legacy mode

### PR DESCRIPTION
**Pull request by jvonau**
### Fixes bug:
#2665

### CODE REVIEW

**Comment by holta** [comment]
@georgejhunt: can you review this?

All: what testing coverage is most important prior to merging?

**Comment by georgejhunt** [comment]
This seems unrelated to Ubuntu moving iptables from /sbin/ to /usr/sbin/ between 18.04 and 20.04. I fixed my problem with the command "ln -s /usr/sbin/iptables /sbin/iptables".  But somewhere, someone mentioned that their clean install had a symbolic link between directories, from /sbin to /usr/sbin. I have no knowledge if that is true. My machine was upgraded from 18.04 in place, and  I may have generated a spurious issue that is not really a problem on a clean install.

**Comment by holta** [comment]
Let's investigate if this PR is also suitable for Ubuntu 21.04 whose final release is expected within 2 weeks now?

**Comment by jvonau** [comment]
> Let's investigate if this PR is also suitable for Ubuntu 21.04 whose final release is expected within 2 weeks now?

Well currently 20.10 is broken, not sure about 20.04, (I'll assume so based on the above note) when iiab_gateway_enabled: True is present in local_vars. You are free to cook up your own solution as it appears the lack of timely responses to known issues is directly related to who files the issue.

**Comment by holta** [comment]
@georgejhunt and everyone I know of welcomed this PR.  But testing is (always) time-consuming, hard work, collaboratively affecting many people.  So let's not lose valuable work like this PR.  Which ideally should be re-opened, if others are Ok with that?

**Comment by holta** [comment]
FYI this PR was test-installed as part of a BIG-sized fresh install of IIAB on Ubuntu Desktop 20.04.2 using ansible-core 2.11 RC2:

```
pip3 install ansible-core
# Comment out apt install of ansible-base within https://github.com/iiab/iiab/blob/master/scripts/ansible#L121
curl d.iiab.io/install.txt | bash -s 2667
```

The result is here:

http://10.8.0.74 = u20-desk-BIG-2667

(FYI the VM disk began with only 20GB, and so has only 3.7G remaining as a result of the above IIAB install!)

**Comment by holta** [comment]
Likewise this PR's also being installed with a MEDIUM-sized IIAB fresh install, on a pre-release of Ubuntu "Hirsute Hippo" 21.04 (VM, also 2GB RAM with 20GB disk) that should appear here in ~20min:

http://10.8.0.78 = u21-srv-MEDIUM-2667

```
apt install nodejs npm    # Installs Node.js 12.21.x (for now, 14.16.x later?) and npm 7.5.x (for now)
echo 'nodejs_installed: True' >> /etc/iiab/iiab_state.yml
pip3 install ansible-core
# Comment out apt install of ansible-base within https://github.com/iiab/iiab/blob/master/scripts/ansible#L121
curl d.iiab.io/install.txt | bash -s 2667
```

**Comment by holta** [comment]
> http://10.8.0.78 = u21-srv-MEDIUM-2667

Install completed successfully, also using ansible-core 2.11 RC2, with above-mentioned manual install of `apt install nodejs npm` (since Ubuntu 21.04 isn't yet official for another ~11 days).

FYI the VM disk began with only 20GB, and now has 7.3G remaining, as a result of the IIAB install.

**Comment by jvonau** [comment]
> > Let's investigate if this PR is also suitable for Ubuntu 21.04 whose final release is expected within 2 weeks now?
> 
> Well currently 20.10 is broken, not sure about 20.04, (I'll assume so based on the above note) when iiab_gateway_enabled: True is present in local_vars.

Without seeing any posted iiab-diagnostics I can't tell if the "testing" is actually hitting the bug or is just in "do no harm" mode, "gateway mode" must be detected, that requires 2 or more physical interfaces be present in the "hardware" **and** "iiab_gateway_enabled: True" must be present in local_vars.yml. Before you shoot yourself in the foot for "do no harm" you should include RaspOS, as the name of the executable called is being changed, this file needs to exist on RaspOS to allow this to be a global change.

To actually test this start with iiab installed with ubuntu on a RPi for the 2 interfaces needed for gateway mode with iab_gateway_enabled: True in local_vars.ml. 
Use `sudo ./iiab-network` to apply the edit
note the output of `sudo iptables -L -v -t nat`
should see:
>buntu@box:~$ sudo iptables -L -v -t nat
\# Warning: iptables-legacy tables present, use iptables-legacy to see them
Chain POSTROUTING (policy ACCEPT 2855 packets, 218K bytes)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 MASQUERADE  all  --  any    eth0    anywhere             anywhere            

reboot
note the output of `sudo iptables -L -v -t nat`
MASQUERADE entry is missing.
Apply this PR
Use `sudo ./iiab-network` to apply the edit
note the output of `sudo iptables -L -v -t nat`
>    0     0 MASQUERADE  all  --  any    eth0    anywhere             anywhere            

reboot
note the output of `sudo iptables -L -v -t nat`
>    0     0 MASQUERADE  all  --  any    eth0  anywhere             anywhere            

MASQUERADE entry is present  
>\# Warning: iptables-legacy tables present, use iptables-legacy to see them

The change to iptables is linked to the use of docker to allow a container's networking to function and it doesn't matter if docker is installed or not.

> 8: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default 
    link/ether 02:42:27:ee:74:28 brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 brd 172.17.255.255 scope global docker0
       valid_lft forever preferred_lft forever
    inet6 fe80::42:27ff:feee:7428/64 scope link 
       valid_lft forever preferred_lft forever

>Chain FORWARD (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 DOCKER-USER  all  --  any    any     anywhere             anywhere            
    0     0 DOCKER-ISOLATION-STAGE-1  all  --  any    any     anywhere             anywhere            
    0     0 ACCEPT     all  --  any    docker0  anywhere             anywhere             ctstate RELATED,ESTABLISHED
    0     0 DOCKER     all  --  any    docker0  anywhere             anywhere            
    0     0 ACCEPT     all  --  docker0 !docker0  anywhere             anywhere            
    0     0 ACCEPT     all  --  docker0 docker0  anywhere             anywhere            
    0     0 ACCEPT     all  --  eth0   br0     anywhere             anywhere             state RELATED,ESTABLISHED
    0     0 ACCEPT     all  --  br0    eth0    anywhere             anywhere            
    0     0 DROP       all  --  eth0   br0     anywhere             anywhere            
Chain OUTPUT (policy ACCEPT 42335 packets, 4314K bytes)
 pkts bytes target     prot opt in     out     source               destination         
Chain DOCKER (1 references)
 pkts bytes target     prot opt in     out     source               destination         
Chain DOCKER-ISOLATION-STAGE-1 (1 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 DOCKER-ISOLATION-STAGE-2  all  --  docker0 !docker0  anywhere             anywhere            
    0     0 RETURN     all  --  any    any     anywhere             anywhere            
Chain DOCKER-ISOLATION-STAGE-2 (1 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 DROP       all  --  any    docker0  anywhere             anywhere            
    0     0 RETURN     all  --  any    any     anywhere             anywhere            
Chain DOCKER-USER (1 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 RETURN     all  --  any    any     anywhere  

Things to note:
iiab-gen-iptables flushes all the old rules so the docker rules will not be recreated.

**Comment by holta** [comment]
> reboot
note the output of `sudo iptables -L -v -t nat`
MASQUERADE entry is missing.

FYI the MASQUERADE line remains even after reboot here: (when following @jvonau's above instructions, right before "Apply this PR" which I did not do.)

```
root@box:~# iptables -L -v -t nat
Chain PREROUTING (policy ACCEPT 525 packets, 40946 bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain INPUT (policy ACCEPT 480 packets, 34772 bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain POSTROUTING (policy ACCEPT 28 packets, 1856 bytes)
 pkts bytes target     prot opt in     out     source               destination
   15  1213 MASQUERADE  all  --  any    eth0    anywhere             anywhere

Chain OUTPUT (policy ACCEPT 43 packets, 3069 bytes)
 pkts bytes target     prot opt in     out     source               destination
```

Details of this MEDIUM-sized IIAB freshly installed on Ubuntu Server 20.10 on RPi 4: http://sprunge.us/NpTOEM?en

Is it possible Ubuntu 20.10 might have somehow patched the #2665 problem?  Should I run something on this 10.8.0.42 to further confirm anything?

**Comment by jvonau** [comment]
> Details of this MEDIUM-sized IIAB freshly installed on Ubuntu Server 20.10 on RPi 4: http://sprunge.us/NpTOEM?en
> 
> Is it possible Ubuntu 20.10 might have somehow patched the #2665 problem? Should I run something on this 10.8.0.42 to further confirm anything?

Could be related to which kernel netfilter modules were loaded and that could change with a kernel update so the noted issue may not be presently reproducible now as I'm having issues reproducing it with the latest booted kernel that is why I closed this issue.
>ubuntu@box:/opt/iiab/iiab$ ls -la /lib/modules
drwxr-xr-x   2 root root 4096 Feb  3 06:15 5.8.0-1006-raspi
drwxr-xr-x   2 root root 4096 Feb 27 06:37 5.8.0-1011-raspi
drwxr-xr-x   2 root root 4096 Feb 27 06:38 5.8.0-1013-raspi
drwxr-xr-x   2 root root 4096 Mar 17 06:52 5.8.0-1015-raspi
drwxr-xr-x   3 root root 4096 Mar 30 06:49 5.8.0-1016-raspi
drwxr-xr-x   4 root root 4096 Mar 16 06:34 5.8.0-1017-raspi
drwxr-xr-x   4 root root 4096 Mar 29 06:06 5.8.0-1019-raspi

Post the contents of /etc/iptables/rules.v4 that is the file involved.

This desktop machine has docker installed and that [does have something to do with it.](https://docs.docker.com/network/iptables/), the docker service is adding it's own iptables rules and chains, but should not interfere as those rules/chains are inserted into default tables when docker starts that are flushed with iiab-gen-iptables. Rebooting load the netfilter-persistent stuff from /etc/iptables/rules.v4 and docker add its stuff and there is joy in the land.

>>   / # Warning: iptables-legacy tables present, use iptables-legacy to see them
>The change to iptables is linked to the use of docker to allow a container's networking to function and it doesn't matter if docker is installed or not.

Not quite true [see](https://askubuntu.com/questions/1295021/warning-iptables-legacy-tables-present), modprobe is used in iiab-gen-iptables and legacy table names are used, so this warning might be self-induced with the rules being fine anyway.
Need to reboot this machine be back later.

**Comment by jvonau** [comment]
> Details of this MEDIUM-sized IIAB freshly installed on Ubuntu Server 20.10 on RPi 4: http://sprunge.us/NpTOEM?en
> 
> Is it possible Ubuntu 20.10 might have somehow patched the #2665 problem? Should I run something on this 10.8.0.42 to further confirm anything?

Could be related to which kernel netfilter modules were loaded and that could change with a kernel update so the noted issue may not be presently reproducible now as I'm having issues reproducing it with the latest booted kernel that is why I closed this issue.
>ubuntu@box:~$ ls /lib/modules/
5.8.0-1006-raspi  5.8.0-1013-raspi  5.8.0-1016-raspi  5.8.0-1019-raspi
5.8.0-1011-raspi  5.8.0-1015-raspi  5.8.0-1017-raspi

Post the contents of /etc/iptables/rules.v4 that is the file involved.

This desktop machine has docker installed and that [does have something to do with it.](https://docs.docker.com/network/iptables/), the docker service is adding it's own iptables rules and chains, but should not interfere as those rules/chains are inserted in front of and not appended to the default tables that are flushed with iiab-gen-iptables

>>   / # Warning: iptables-legacy tables present, use iptables-legacy to see them
>The change to iptables is linked to the use of docker to allow a container's networking to function and it doesn't matter if docker is installed or not.

Not quite true [see](https://askubuntu.com/questions/1295021/warning-iptables-legacy-tables-present), modprobe is used in iiab-gen-iptables and legacy table names are used, so this warning might be self-induced with the rules being fine anyway.

**Comment by holta** [comment]
`/etc/iptables/rules.v4` pastebin from 10.8.0.42: (Ubuntu 20.10 on RPi 4)

https://paste.ubuntu.com/p/w5XJYmmJGZ/

**Comment by jvonau** [comment]
> -A POSTROUTING -o eth0 -j MASQUERADE

The value is saved correctly

**Pull request closed without merging**
