### PR TITLE
Pmychanges [phpMyAdmin]

### PR DESCRIPTION
**Pull request by georgejhunt**
Still need to use a socket to connect to MySQL And create a low capability Admin/changeme user. But there's a timing issue in using iiab_feedback table.  So manbe I need to create a useless table which would let phpmyadm  log on out  of the box.

### CODE REVIEW

**Comment by holta** [comment]
@rickgurmet this phpMyAdmin Work-in-Progress is related to:

- #2712

**Comment by rickgurmet** [comment]
PhpMyadmin works if you still have apache2 running on your server. 
For me, it worked.
Steps I followed to make it work:
1. In etc/apache2/ports.conf, added Listen 8080 in order to make apache listen to port 8080.
2. Reinstalled PhpMyadmin and set apache2 as the default server for it.
3. Accessed PHPMyAdmin using URL http://box.lan:8080/phpmyadmin
(in order to access the PHPMyAdmin, set a new username and password in MySQL with all the privileges using command line)

**Comment by holta** [comment]
Thanks @rickgurmet for the update!

FYI we're trying to transition away from Apache completely, as explained here:

https://github.com/iiab/iiab/tree/master/roles/nginx#transition-to-nginx

So we might want to move towards...a better solution here (?)

**Comment by holta** [comment]
@deldesir @rickgurmet this is essentially done, but needs testing!

Can you help?

**Comment by holta** [comment]
> @deldesir @rickgurmet this is essentially done, but needs testing!
> 
> Can you help?

@georgejhunt what specifically should we/they test for?

Thanks for explaining just a bit: are you just looking to see if this PR installs on OS's with PHP 7.4 (e.g. Raspberry Pi OS) and 8.0 (Ubuntu 21.10) ?

Tangentially Related:

- #2864

**Comment by holta** [comment]
@deldesir this needs more testing if you get the chance to hopefully test this?

This was just merged after discussion among 4 people on IIAB's weekly community call:

- Install IIAB, e.g. by changing [Lines 324 and 325 of local_vars_unittest.yml](https://github.com/iiab/iiab/blob/master/vars/local_vars_unittest.yml#L322-L325) so that your [/etc/iiab/local_vars.yml](http://wiki.laptop.org/go/IIAB/FAQ#What_is_local_vars.yml_and_how_do_I_customize_it.3F) includes:
  - `phpmyadmin_install: True`
  - `phpmyadmin_enabled: True`
- @georgejhunt then suggests you run script [roles/phpmyadmin/templates/mkuser](https://github.com/iiab/iiab/tree/master/roles/phpmyadmin/templates/mkuser)
- Then use login credential `Admin/changeme` at http://box/phpmyadmin to verify it works!

**Comment by deldesir** [comment]
PhpMyAdmin works with PHP 8.0 on Ubuntu 21.10 desktop and server (on Raspberry 4).

**Pull request merged**
