### PR TITLE
Remove named dhcpd + roles/firmware refinements + clean networkd-dispatcher for Mint

### PR DESCRIPTION
**Pull request by holta**
Building on @jvonau's:

- PR #3312

### CODE REVIEW

**Comment by holta** [comment]
Tested on Ubuntu Server 22.04

**Comment by holta** [comment]
@jvonau can you look over this PR quickly?

Prior to it being merged today if possible?

**Comment by holta** [comment]
Tested on Ubuntu Server 22.04 VM: http://sprunge.us/1uZ8wI?en

**Comment by jvonau** [comment]
Think this looks fine, that would just leave #3313 to hash through.

**Comment by holta** [comment]
> Think this looks fine, that would just leave #3313 to hash through.

Thanks for weighing in.

This is a large PR with 54 files changes, but I agree it's time to move forward so broad community testing can begin across other HW/OS combinations, so let's do it.

**Pull request merged**
