### PR TITLE
Testing latest lokole - use lokole_commit for install

### PR DESCRIPTION
**Pull request by jvonau**
#2767 To grab the latest code use of lokole_commit is required @nzola @deldesir @holta https://github.com/ascoderu/lokole/commits/master 1c189e0f9ec689fce98e8b7c47152678bcf00aca is the latest as of today.

### CODE REVIEW

**Comment by jvonau** [comment]
`lokole_commit: 1c189e0f9ec689fce98e8b7c47152678bcf00aca` could be appended to your local_vars.yml for testing if this PR is not merged yet.

**Comment by holta** [comment]
Thanks @deldesir if you have time to test today, or when you have time!  On any recently installed IIAB, test as follows:

```
# VERIFY that 'lokole_install: True' and 'lokole_enabled: True' are in /etc/iiab/local_vars.yml
cd /opt/iiab/iiab
git pull    # Use this line *IF* you want your IIAB local branch/repo updated!
git checkout -b jvonau-lok master
git pull https://github.com/jvonau/iiab.git lok
./runrole lokole
# Login and verify that http://box.lan/lokole can send & receive emails.
```

(Or any other "test plan" that @jvonau recommends!)

**Comment by holta** [comment]
Thank you @nzola for this iiab-diagnostics output: http://sprunge.us/LAfuI0?en

**Comment by jvonau** [comment]
Notes:
/library/lokole and /home/lokole/state contain all the file needed to run the app, backing up these directories will preserve the current install.

[lokole-changes2.txt](https://github.com/iiab/iiab/files/6412401/lokole-changes2.txt)
>Only in /library/lokole.new/venv/lib/python3.8/site-packages/opwen_email_client/webapp/forms: register.py
Only in /library/lokole.old/venv/lib/python3.8/site-packages/opwen_email_client/webapp/static/css: about.min.css
Only in /library/lokole.old/venv/lib/python3.8/site-packages/opwen_email_client/webapp/static/css: _base_email.min.css
Only in /library/lokole.old/venv/lib/python3.8/site-packages/opwen_email_client/webapp/static/css: bootstrap3-wysihtml5.min.css
Only in /library/lokole.old/venv/lib/python3.8/site-packages/opwen_email_client/webapp/static/css: bootstrap.min.css
Only in /library/lokole.old/venv/lib/python3.8/site-packages/opwen_email_client/webapp/static/css: email_new.min.css
Only in /library/lokole.old/venv/lib/python3.8/site-packages/opwen_email_client/webapp/static/css: fileinput.min.css
Only in /library/lokole.old/venv/lib/python3.8/site-packages/opwen_email_client/webapp/static/css: flag-icon.min.css
Only in /library/lokole.old/venv/lib/python3.8/site-packages/opwen_email_client/webapp/static/css: font-awesome.min.css
Only in /library/lokole.old/venv/lib/python3.8/site-packages/opwen_email_client/webapp/static/css: home.min.css
Only in /library/lokole.old/venv/lib/python3.8/site-packages/opwen_email_client/webapp/static/css: settings.min.css
Only in /library/lokole.old/venv/lib/python3.8/site-packages/opwen_email_client/webapp/static: flags
Only in /library/lokole.old/venv/lib/python3.8/site-packages/opwen_email_client/webapp/static: fonts
Only in /library/lokole.old/venv/lib/python3.8/site-packages/opwen_email_client/webapp/static/js: _base_email.min.js
Only in /library/lokole.old/venv/lib/python3.8/site-packages/opwen_email_client/webapp/static/js: _base.min.js
Only in /library/lokole.old/venv/lib/python3.8/site-packages/opwen_email_client/webapp/static/js: bootstrap3-wysihtml5.all.min.js
Only in /library/lokole.old/venv/lib/python3.8/site-packages/opwen_email_client/webapp/static/js: bootstrap.min.js
Only in /library/lokole.old/venv/lib/python3.8/site-packages/opwen_email_client/webapp/static/js: email_new.min.js
Only in /library/lokole.old/venv/lib/python3.8/site-packages/opwen_email_client/webapp/static/js: fileinput.min.js
Only in /library/lokole.old/venv/lib/python3.8/site-packages/opwen_email_client/webapp/static/js: jquery.lazyload.min.js
Only in /library/lokole.old/venv/lib/python3.8/site-packages/opwen_email_client/webapp/static/js: jquery.min.js
Only in /library/lokole.old/venv/lib/python3.8/site-packages/opwen_email_client/webapp/static/js: printThis.min.js
Only in /library/lokole.old/venv/lib/python3.8/site-packages/opwen_email_client/webapp/static/js: register.min.js
Only in /library/lokole.old/venv/lib/python3.8/site-packages/opwen_email_client/webapp/static/js: settings.min.js
Files /library/lokole.new/venv/lib/python3.8/site-packages/opwen_email_client/webapp/tasks.py and /library/lokole.old/venv/lib/python3.8/site-packages/opwen_email_client/webapp/tasks.py differ
Only in /library/lokole.new/venv/lib/python3.8/site-packages/opwen_email_client/webapp/templates: register.html

Think this explains why the new version doesn't render like the older version as noted in chat.

**Comment by jvonau** [comment]
https://github.com/ascoderu/lokole/blob/master/.gitignore

**Comment by jvonau** [comment]
d03a0b1
Screenshot at 2021-05-03 08-29-44

Not clear on how registration should be working, https://github.com/ascoderu/lokole/issues/454 mentions OPWEN_CLIENT_ID being unset as the trigger to the one-time registration, not sure how that should present itself.

**Comment by holta** [comment]
If [Lokole 0.6.12](https://github.com/ascoderu/lokole/releases/tag/0.6.12) looks good, I imagine @jvonau and @deldesir may recommend this line: (or version's tag/branch equivalent?)

```
lokole_commit: fdbb21b5830831a1c3db154cc7faf74afdb940a1
```

Ref: #2767 "Lokole 0.6.11 & 0.6.12 released, but pip install not yet available"

**Comment by jvonau** [comment]
The only way I get a decent looking page is with 8169e58b3a2aea67fc77320ba420016e18cc6362 reverted meaning first pip install 0.6.10 then move to 0.6.12 with git enabled.

**Comment by jvonau** [comment]
No need start from scrach
>sudo systemctl stop celerybeat.service 
sudo systemctl stop lokole_restarter.service 
sudo systemctl stop celery.service 
sudo systemctl stop lokole.service 
sudo rm -rf /home/lokole/
sudo rm -rf /library/lokole/
sudo ./runrole --reinstall lokole

register
The register tab appears, rejects the password
regfail

The sub-domain is set none as this info needs to be configured on client, that would become the equivalent of 'teams' or 'victest2' in what I assume to be the working production environment. The registration function should be pointed towards how the remote admin enters the upstream email relay information before the remote site goes live.

**Comment by jvonau** [comment]
The register tab should really be treated like the settings tab, only appearing for the site administrator, then there is the difference in environment variables and the use of settings.env. Note that client_create_url in register.py is using an authorization token that must be passed with OPWEN_CLIENT_NAME set ie(teams,victest2,... ) that must be unique and not already in use.

**Comment by adamsclafani** [comment]
Hi all, Hopefully I can clear up some questions. 

To access the page to register a new client you must do the following:

1.  Login as admin. Default credentials found [here](https://github.com/ascoderu/lokole/blob/fdbb21b5830831a1c3db154cc7faf74afdb940a1/docker-compose.yml#L150).
2. Once logged in, manually type in the route admin/register
3. Provide the necessary credentials to the page which are as follows: 
     - GitHub Username 
     - Github personal access token (Needs to be created)
     - The name of the client to be registered i.e. ('victest')
  
From here, The client will be registered on our servers. From here one can create new accounts such as user@lokole.ca (which is what the public register tab is for) under that client (setting up a client is like setting up a new PI Lokole device). What was done here was basically porting part of the setup process to a click of a button on the web app as opposed to running an install script. 

On another note, I'm not 100% sure on this, but I'm mentioning this now just in case it becomes an issue. 
the environment variables needed for the setup [here](https://github.com/ascoderu/lokole/blob/fdbb21b5830831a1c3db154cc7faf74afdb940a1/opwen_email_client/webapp/actions.py#L259) might need to be added on the IIAB side [here](https://github.com/iiab/iiab/blob/master/roles/lokole/templates/webapp_secrets.sh.j2), so the setup can properly reference them.

**Comment by jvonau** [comment]
> Hi all, Hopefully I can clear up some questions.
> 
> To access the page to register a new client you must do the following:
> 
>     1. Login as admin. Default credentials found [here](https://github.com/ascoderu/lokole/blob/fdbb21b5830831a1c3db154cc7faf74afdb940a1/docker-compose.yml#L150).
> 

Looks like [OPWEN_CLIENT_NAME & OPWEN_CLIENT_ID ](https://github.com/ascoderu/lokole/blob/fdbb21b5830831a1c3db154cc7faf74afdb940a1/docker-compose.yml#L148-L151)needs to be set also. How does one know what values to include here, seems like these need to be provided to the person provisioning the new site before installation begins.
 
>     2. Once logged in, manually type in the route admin/register
> 
>     3. Provide the necessary credentials to the page which are as follows:
>        
>        * GitHub Username
>        * Github personal access token (Needs to be created)
>        * The name of the client to be registered i.e. ('victest')
> 
> 
> From here, The client will be registered on our servers. From here one can create new accounts such as [user@lokole.ca](mailto:user@lokole.ca) (which is what the public register tab is for) under that client (setting up a client is like setting up a new PI Lokole device). What was done here was basically porting part of the setup process to a click of a button on the web app as opposed to running an install script.
> 

The older screen shots https://github.com/ascoderu/lokole/issues/458 of an admin user logged in clearly shows that user@site.lokole.ca was being used, where site would I presume to be OPWEN_CLIENT_NAME, based upon what I have seen populating settings.env.

> On another note, I'm not 100% sure on this, but I'm mentioning this now just in case it becomes an issue.
> the environment variables needed for the setup [here](https://github.com/ascoderu/lokole/blob/fdbb21b5830831a1c3db154cc7faf74afdb940a1/opwen_email_client/webapp/actions.py#L259) might need to be added on the IIAB side [here](https://github.com/iiab/iiab/blob/master/roles/lokole/templates/webapp_secrets.sh.j2), so the setup can properly reference them.

That is the issue, OPWEN_CLIENT_NAME needs to be unique to each machine.

**Comment by adamsclafani** [comment]
My bad on the login credentials. The IIAB default admin credentials (listed on the IIAB lokole [readme)](https://github.com/iiab/iiab/blob/33a1212f4e8841fec82ab162698e3c0b6b9e62c2/roles/lokole/defaults/main.yml#L14) is something different from what I linked. In any case, you already managed to login and locate the register UI 🙂

As per our discussion on Skype and Messenger,  In case you're interested, [here](https://github.com/ascoderu/lokole/blob/fdbb21b5830831a1c3db154cc7faf74afdb940a1/opwen_email_client/webapp/actions.py#L233) is the code for the client setup process . 
The client name does need to be provided by the user. The provided information will get sent to the server and then processed. the client id will be returned to the user and the client id and client name will be stored automatically.

**Comment by jvonau** [comment]
@adamsclafani While testing new machine registration I was able to have the machine appear in the 'dashboard', but am unable to see where the registration information returned is stored on the new client. The docs and code mention using /state/settings.env but the file does not appear to be created so I have no idea what these were set to by the registration server to be further used by the client.
OPWEN_CLIENT_ID=
OPWEN_REMOTE_ACCOUNT_NAME=
OPWEN_REMOTE_ACCOUNT_KEY=
OPWEN_REMOTE_RESOURCE_CONTAINER=

**Comment by jvonau** [comment]
fished this out of `sudo journalctl -b 0 -u lokole.service`
>May 05 11:29:19 box.lan systemd[1]: Started Provides the Lokole Server.
May 05 11:31:21 box.lan bash[58273]: [2021-05-05 11:31:21 -0500] [58273] [ERROR] Unhandled exception!
May 05 11:31:21 box.lan bash[58273]: Traceback (most recent call last):
May 05 11:31:21 box.lan bash[58273]:   File "/library/lokole/venv/lib/python3.8/site-packages/opwen_email_client/webapp/views.py", line 412, in _on_exception
May 05 11:31:21 box.lan bash[58273]:     raise exception
May 05 11:31:21 box.lan bash[58273]:   File "/library/lokole/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
May 05 11:31:21 box.lan bash[58273]:     rv = self.dispatch_request()
May 05 11:31:21 box.lan bash[58273]:   File "/library/lokole/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
May 05 11:31:21 box.lan bash[58273]:     return self.view_functions[rule.endpoint](**req.view_args)
May 05 11:31:21 box.lan bash[58273]:   File "/library/lokole/venv/lib/python3.8/site-packages/opwen_email_client/webapp/session.py", line 38, in history_tracker
May 05 11:31:21 box.lan bash[58273]:     return func(*args, **kwargs)
May 05 11:31:21 box.lan bash[58273]:   File "/library/lokole/venv/lib/python3.8/site-packages/opwen_email_client/webapp/views.py", line 291, in register
May 05 11:31:21 box.lan bash[58273]:     form.register_client()
May 05 11:31:21 box.lan bash[58273]:   File "/library/lokole/venv/lib/python3.8/site-packages/opwen_email_client/webapp/forms/register.py", line 25, in register_client
May 05 11:31:21 box.lan bash[58273]:     self._setup_client(path)
May 05 11:31:21 box.lan bash[58273]:   File "/library/lokole/venv/lib/python3.8/site-packages/opwen_email_client/webapp/forms/register.py", line 38, in _setup_client
May 05 11:31:21 box.lan bash[58273]:     if response.status != 200:
May 05 11:31:21 box.lan bash[58273]: AttributeError: 'Response' object has no attribute 'status'

**Comment by adamsclafani** [comment]
Thanks so much for that. Status just needs to be changed to status_code which I will do asap. The file is supposed to be created [here](https://github.com/ascoderu/lokole/blob/fdbb21b5830831a1c3db154cc7faf74afdb940a1/opwen_email_client/webapp/actions.py#L274) but since the code is erroring [here](https://github.com/ascoderu/lokole/blob/fdbb21b5830831a1c3db154cc7faf74afdb940a1/opwen_email_client/webapp/forms/register.py#L38) before the register.delay call, I don't think it is even getting to that part where the file is created, and the returned variables are written to it.

**Comment by jvonau** [comment]
>self._setup_client(path)

Should that more or less be OPWEN_STATE_DIRECTORY? That is where we are using /home/lokole/state/ and upstream has /lokole/state/ while [register.py](https://github.com/ascoderu/lokole/blob/fdbb21b5830831a1c3db154cc7faf74afdb940a1/opwen_email_client/webapp/forms/register.py#L45) is using that value also.

**Comment by adamsclafani** [comment]
Yes that is correct. [LOKOLE_STATE_DIRECTORY](https://github.com/ascoderu/lokole/blob/fdbb21b5830831a1c3db154cc7faf74afdb940a1/install.py#L883) is the name of one of the arguments in the original install script. It gets set to [OPWEN_STATE_DIRECTORY](https://github.com/ascoderu/lokole/blob/fdbb21b5830831a1c3db154cc7faf74afdb940a1/install.py#L542) during the setup process, so they are basically the same. 

Maybe in [register.py](https://github.com/ascoderu/lokole/blob/fdbb21b5830831a1c3db154cc7faf74afdb940a1/opwen_email_client/webapp/forms/register.py#L45) I should switch LOKOLE_STATE_DIRECTORY to OPWEN_STATE_DIRECTORY so that way getenv() will grab whatever OPWEN_STATE_DIRECTORY is set to on the IIAB side (home/lokole/state)? Otherwise it will always default to lokole/state since LOKOLE_STATE_DIR doesn't exist on the IIAB side. thoughts?

**Comment by jvonau** [comment]
> Yes that is correct. [LOKOLE_STATE_DIRECTORY](https://github.com/ascoderu/lokole/blob/fdbb21b5830831a1c3db154cc7faf74afdb940a1/install.py#L883) is the name of one of the arguments in the original install script. It gets set to [OPWEN_STATE_DIRECTORY](https://github.com/ascoderu/lokole/blob/fdbb21b5830831a1c3db154cc7faf74afdb940a1/install.py#L542) during the setup process, so they are basically the same.

OPWEN_STATE_DIRECTORY is what I've seen get written to /lokole/state/settings.env messing with install.py in a chroot. Has everything prepended with OPWEN been moved over to LOKOLE or is there a mix? 

> 
> Maybe in [register.py](https://github.com/ascoderu/lokole/blob/fdbb21b5830831a1c3db154cc7faf74afdb940a1/opwen_email_client/webapp/forms/register.py#L45) I should switch LOKOLE_STATE_DIRECTORY to OPWEN_STATE_DIRECTORY so that way getenv() will grab whatever OPWEN_STATE_DIRECTORY is set to on the IIAB side (home/lokole/state)? Otherwise it will always default to lokole/state since LOKOLE_STATE_DIR doesn't exist on the IIAB side. thoughts?

Yes, think that is the way to go, everything uses OPWEN from my quick look. Any chance for the routine to write OPWEN_CLIENT_NAME along side OPWEN_CLIENT_ID in registration_details in actions.py? Think that would make things easier rather than having to set the variable OPWEN_CLIENT_NAME first, which would really become what you are entering in the top field of the form when registering, should help keep the NAME to ID relationship clearer.

**Comment by adamsclafani** [comment]
You’re correct, in short everything does use OPWEN, and variables with that prefix are written to the settings file. To keep things simple don’t worry too much about the LOKOLE variables, (Basically Everything LOKOLE gets reassigned to an OPWEN variable)

OPWEN_CLIENT_NAME and ID fo get written. All the variables that get written to the settings file upon submission of the registration form are [here](https://github.com/ascoderu/lokole/blob/fdbb21b5830831a1c3db154cc7faf74afdb940a1/opwen_email_client/webapp/actions.py#L259)

**Comment by holta** [comment]
Lokole 0.6.13 is now released:
https://github.com/ascoderu/lokole/releases/tag/0.6.13

Based on @c-w's PR [ascoderu/lokole#544](https://github.com/ascoderu/lokole/pull/544) that stands to restore 2-way email relaying, based on a workaround that changes the structure of email addresses like:

```
name@subdomain.lokoke.ca
```

...over to:

```
name-subdomain@lokole.ca
```

**Comment by jvonau** [comment]
Even better the release shows up [here](https://pypi.org/project/opwen-email-client/#history), so none of the workarounds to install is required, just master should be needed. What needs to be reviewed are the variable that should make up the default values in webapp_secrets.sh.j2, what those values might need to be changed before a live registration and follow up on the above traceback.

**Comment by holta** [comment]
Clarification from @c-w:

> Basically we lost the ability to send mail [SendGrid] from {user}@{client}.lokole.ca so I modify the email sending code to set the from to {user}-{client}@lokole.ca and the reply-to as {user}@{client}.lokole.ca so that the rest of the system should work as before.

**Pull request closed without merging**
