### PR TITLE
pbx/tasks/asterisk.yml: Experiment w/o aptitude

### PR DESCRIPTION
**Pull request by holta**
Thanks to @jvonau suggestion:

https://github.com/iiab/iiab/pull/2896#issuecomment-892061982

cc: @lemueldsouza @m-anish

- PR #2896
- PR #2899
- PR #2901

### CODE REVIEW

**Comment by jvonau** [comment]
This does not really remove installing aptitude just moves the dependency back into `install_prereq`, you are missing the main part of the suggestion to use asterisk_dependencies.yml, after all that is what the name implies, in place of using install_prereq.

**Comment by holta** [comment]
> This does not really remove installing aptitude just moves the dependency back into `install_prereq`, you are missing the main part of the suggestion to use asterisk_dependencies.yml, after all that is what the name implies, in place of using install_prereq.

Good point.

While also noting the people who maintain Asterisk's install_prereq seem to do a really good job.

So I strongly suspect we should rely on this well-maintained script of theirs going forward, instead of trying to reverse engineer and micromanage the dozens and dozens of requirements therein.

Yes they install the older `aptitude` rather than relying on the more modern apt ~= apt-get &mdash; but that's likely a small price to pay, to contain the larger Dependency Hell: https://github.com/asterisk/asterisk/blob/master/contrib/scripts/install_prereq#L262-L271

So it seems this PR #2902 might just be the right medicine after all ?  (A few more install tests should hopefully confirm!)

**Comment by jvonau** [comment]
Now aptitude pulls in its own dependency chain altering what would be installed over a 'normal' base install I would suggest moving from 6-generic-apps where the new dependency might mask dependencies in other roles installing afterwards to be after calibre-web in 9-local-addons given this is the lone apache holdout.

**Comment by holta** [comment]
> Now aptitude pulls in its own dependency chain altering what would be installed over a 'normal' base install I would suggest moving from 6-generic-apps where the new dependency might mask dependencies in other roles installing afterwards to be after calibre-web in 9-local-addons given this is the lone apache holdout.

Very good idea.  As Asterisk + FreePBX are humongous.

**Comment by jvonau** [comment]
https://github.com/iiab/iiab/blob/master/roles/pbx/tasks/install.yml#L53-L56 should really be removed in light of the presence of build-essential within asterisk_dependencies.yml which would explain why 'make' is installed as a dependency of build-essential but otherwise build-essential would be installed via [install_prereq](https://github.com/iiab/iiab/pull/2896#issuecomment-892061982) anyway.

**Comment by holta** [comment]
> https://github.com/iiab/iiab/blob/master/roles/pbx/tasks/install.yml#L53-L56 should really be removed

Good catch.  I'm now testing that (https://github.com/iiab/iiab/pull/2903/commits/e39aacbbab94bf2d7ffe89a4726ab66f269ff691) as part of PR #2903.

Of course Asterisk/FreePBX are gigantic so we can't exactly put them on a no-carb diet.

Still: this is absolutely tremendous progress &mdash; making [roles/pbx](https://github.com/iiab/iiab/tree/master/roles/pbx#pbx-readme) substantially more coherent + understandable + maintainable &mdash; so it'll actually be used!

**Comment by jvonau** [comment]
still should be after calibre-web

**Comment by holta** [comment]
> still should be after calibre-web

Really?  Ok, if that's truly best?

In the past our story was...that Calibre should be at the very end...due to testing branch wackiness.

But possibly nobody installs Calibre today.  In no small part b/c of its Eternal Dependency Hell (!)

**Comment by jvonau** [comment]
if it the level of riskiness 
calibre-web
calibre might be better with newer distros?
pbx given the large number of devel packages pulled in by install_prereq

**Comment by holta** [comment]
> if it the level of riskiness
> calibre-web
> calibre might be better with newer distros?
> pbx given the large number of devel packages pulled in by install_prereq

In the past I'd assumed that Calibre-Web should be installed after Calibre &mdash; so as to better take advantage of Calibre's own `/usr/bin/ebook-convert`

But possibly that's a non-issue?

e.g. if Calibre-Web very regularly monitors for such plugin-like programs, even if they appear some day later, after the fact.

**Comment by jvonau** [comment]
https://github.com/iiab/iiab/blame/master/roles/calibre/tasks/install.yml should receive the axe apache treatment given just the port is now available.

> > if it the level of riskiness
> > calibre-web
> > calibre might be better with newer distros?
> > pbx given the large number of devel packages pulled in by install_prereq
> 
> In the past I'd assumed that Calibre-Web should be installed after Calibre — so as to better take advantage of Calibre's own `/usr/bin/ebook-convert`
> 
> But possibly that's a non-issue?
> 

Would that not depend on if calibre is selected to be installed?

> e.g. if Calibre-Web very regularly monitors for such plugin-like programs, even if they appear some day later, after the fact.

Would depend on if you require that functionality I would think, enduser's choice...

**Comment by holta** [comment]
> Would that not depend on if calibre is selected to be installed?

Yes, I just want to make sure Calibre-Web finds `/usr/bin/ebook-convert` reliably, when the implementer has also installed Calibre.

But let's take the risk and see what happens: https://github.com/iiab/iiab/blob/master/roles/9-local-addons/tasks/main.yml#L22-L38 (that's PR #2903, now merged).

So [roles/calibre-web/README.rst](https://github.com/iiab/iiab/tree/master/roles/calibre-web#calibre-web-readme) can be cleaned up properly in short order.

**Comment by jvonau** [comment]
Feels like a semi-firm dependency, could force calibre to install when calibre-web is selected to get the binary but not start the calibre service otherwise.

**Comment by holta** [comment]
> get the binary but not start the calibre service otherwise

That could be very interesting.

Even if `/usr/bin/ebook-convert` might not be as powerful as https://pandoc.org, it's still an essential & powerful "legal scraping" tool in anybody's quiver.

_I suspect a lot of Calibre-Web users would be interested &mdash; and not just those using IIAB &mdash; if anybody knows how to make this happen !_

**Comment by jvonau** [comment]
>apt-file search /usr/bin/ebook-convert
calibre: /usr/bin/ebook-convert           

>apt-file search /usr/bin/calibre-server
calibre: /usr/bin/calibre-server

apt install calibre is used in the calibre role but calibre-bin I think is the desktop widget having libqt5core5a as a dependency... Non desktops might benefit by omitting calibre-bin as calibre-server is provided by calibre and would drag in a desktop to meet the mentioned dependency of calibre-bin.

**Pull request merged**
