### PR TITLE
Comment out non-existent var {{ ansible_product_uuid }} [not quite enough: {{ prior_gateway_device }} has a similar issue]

### PR DESCRIPTION
**Pull request by holta**
Proposed emergency fix for #2669

### CODE REVIEW

**Comment by holta** [comment]
This PR wasn't enough, as seen during this fresh IIAB install attempt on 193-deb10-BIG-0128 = 10.8.0.46:

> TASK [network : Add 'detected_network' variable values to /etc/iiab/iiab.ini] ***
...
> failed: [127.0.0.1] (item={'option': 'prior_gateway_device', 'value': ''}) => {"ansible_loop_var": "item", "changed": false, "item": {"option": "prior_gateway_device", "value": ""}, "msg": "Parameter 'value' must not be empty if state=present and allow_no_value=False"}

@jvonau and others may have ideas on the most thoughtful ways to clean up here, i.e. given Ansible's removal of `{{ ansible_product_uuid }}` and similar problems with undeclared vars ?

**Comment by jvonau** [comment]
Fun, the version reported by apt is 2.10.5-1 but is referred to as "Ansible 2.10.6 contains Ansible-base version 2.10.5. This is a newer version than version 2.10.4 contained in the previous Ansible release", released on 2021-01-26 according to https://github.com/ansible-community/ansible-build-data/blob/main/2.10/CHANGELOG-v2.10.rst. 

The fix for above would be just to define a better default value than "" in roles/network/defaults/main.yml, I suggest "not-found" for what is used as a recording variable.

**Comment by jvonau** [comment]
> ubuntu@box:~$ ansible -m setup localhost --connection=local | grep product
        "ansible_product_name": "",
        "ansible_product_serial": "",
        "ansible_product_uuid": "",
        "ansible_product_version": "",

" ansible_product_uuid  " error smells like a upstream bug somewhere, that is a built-in variable supplied by the setup module, that in fact does exist but has returned "", it's the stricter checking that caused this ansible supplied variable to puke.

**Comment by holta** [comment]
Currently https://github.com/iiab/iiab/blob/master/roles/network/defaults/main.yml#L64 shows:

```
prior_gw_device: ""
```

Likely we should adopt & use an industry norm keyword like the following?

```
prior_gw_device: undefined
```

Possibly using the long-form variable name  `prior_gateway_device` ?

**Comment by tim-moody** [comment]
>prior_gw_device: undefined

I would use 'none' like the other parameters. To me let x = 'undefined' is an oxymoron.

**Comment by holta** [comment]
An initial value like "unknown" "undeclared" "undefined" "not-yet-found" is needed to (very intentionally) convey the ambiguity of initial state.  Similar to "unset" used here:

https://github.com/iiab/iiab/blob/master/roles/network/defaults/main.yml#L86-L87

Whereas wordings like "none" erroneously convey certainty.

We really should convey (accurate) ambiguity — wherever realistically possible anyway.  No solution is perfect given Ansible limitations etc.  But let's avoid Little Lies as much as possible...as these accidentally/inevitably become Big Lies (and bugs) down the road :/

**Comment by holta** [comment]
@chjohn22

I'd like others to review it for possible improvements / future directions, but FYI this fix has been smoke-tested to work: PR #2672

**Pull request merged**
