### PR TITLE
Run network playbook once during runansible

### PR DESCRIPTION
**Pull request by jvonau**
for illustration only ATM

### CODE REVIEW

**Comment by tim-moody** [comment]
do networking as soon as configured, it should be possible to do services without a networking side effect.

**Comment by jvonau** [comment]
revised 239 -> Run network playbook once during runansible.

**Comment by jvonau** [comment]
also part of #243

**Comment by jvonau** [comment]
Nothing more than eliminating the all the 'skipping' of the first round of networking that is never used that spams and bloats up the logfile. one subset of #267

**Comment by holta** [comment]
@jvonau (on live call http://minutes.iiab.io) says he's repeatedly smoke-tested this over past 2 weeks.

**Pull request merged**
