### PR TITLE
/etc/iiab/iiab.ini norms: install / enabled -> ROLE_install / ROLE_enabled

### LINKED ISSUE #2763: CUPS Printing is not auto-added to IIAB's main page (http://box.lan)
Bug that we figured out during the http://minutes.iiab.io weekly call (things like 'install = True' should really be 'cups_install = True' in /etc/iiab/iiab.ini).  I'll fix it after the call.

Ref: https://github.com/iiab/iiab/pull/2761#issuecomment-829342302

### PR DESCRIPTION
**Pull request by holta**
Fixes #2763 and brings consistency across all roles, to help avoid similar bugs in future.

Ref: #2738 "RFC: how to determine enabled status"

### CODE REVIEW

**Comment by holta** [comment]
A BIG-sized test install is now running (and looks likely to complete soon) on an Ubuntu Server 20.04.2 VM at 10.8.0.66

**Comment by holta** [comment]
@jvonau do you have time to look at these 4 files in https://github.com/holta/iiab/tree/iiab.ini-vars-standardized/roles/network/tasks ?

- [computed_services.yml Lines 60-71](https://github.com/holta/iiab/blob/iiab.ini-vars-standardized/roles/network/tasks/computed_services.yml#L60-L71)
- [enable_services.yml Lines 220-254](https://github.com/holta/iiab/blob/iiab.ini-vars-standardized/roles/network/tasks/enable_services.yml#L220-L254)
- [squid.yml Lines 98-129](https://github.com/holta/iiab/blob/iiab.ini-vars-standardized/roles/network/tasks/squid.yml#L98-L129)
- [wondershaper.yml Lines 55-69](https://github.com/holta/iiab/blob/iiab.ini-vars-standardized/roles/network/tasks/wondershaper.yml#L55-L69)

(Just a bit more consistency is needed in the recording of ROLE_install and ROLE_enabled into iiab.ini, however you recommend doing this in the 4 files above?)

**Comment by holta** [comment]
> * computed_services.yml Lines 60-71

For now I commented out these 12 lines, as vars for all 3 {Squid, DansGuardian, Wondershaper} were also/already being saved (repeatedly it seems?) into their own sections of /etc/iiab/iiab.ini

@jvonau: Or do you prefer these 3 apps/services always save their vars together/centrally into the [network] section of iiab.ini ? (Instead of using their own sections of iiab.ini [squid], [dansguardian] and [wondershaper] ?)

In any case, just make the recommendation that's most appropriate and/or most expedient!

**Comment by holta** [comment]
@jvonau if it's easier to call me, let's do that.  I can work on this overnight as nec.

**Comment by jvonau** [comment]
https://github.com/iiab/iiab/blame/master/roles/network/tasks/enable_services.yml#L219-L247 were intended to update the already created individual keys noted in the 'section:' within the iiab.ini file, from a time when the three were not optional. Think each block should be dependent upon *_installed being defined to suppress the needless recording of not installed services. The computed_services.yml recording is more informational for diagnostics purposes, install info is not really needed, but keep the rest.

**Comment by jvonau** [comment]
Have a look at #2768, I'd revert the last commit, or use the other PR as a bases for the change.

**Comment by holta** [comment]
> computed_services.yml recording is more informational for diagnostics purposes

The above was writing to the [network] section of /etc/iiab/iiab.ini &mdash; whereas the 2 other code paths write to separate sections of iiab.ini: [squid], [dansguardian] and [wondershaper].

@jvonau do you prefer that all messaging/recordings (for all 3 of these services/apps) be unified into the [network] section of /etc/iiab/iiab.ini ?

**Comment by holta** [comment]
> install info is not really needed

Very true.  For almost every single service/app, recording ROLE_install to iiab.ini is gratuitous.

But consistency across all of /etc/iiab/iiab.ini and across Ansible playbooks (roles) has the advantage of making all things substantially more readable for newcomers, trying to understand IIAB.

**Comment by jvonau** [comment]
The computed_services.yml recording of squid, dansguardian and wondershaper enabled setting is just a convenience to me, at a glance summary. Now enable_services.yml, the install state would appear elsewhere in the ini file and only those enabled keys would need to be updated, the extra installed part is redundant but harmless.

Ship it..

**Pull request merged**
