### PR TITLE
Update & tighten up .travis.yml from Trusty (Ubuntu 14.04) + Python 2.7 to Focal (Ubuntu 20.04) + Python 3.8

### PR DESCRIPTION
**Pull request by holta**
Tested.

Bonus it runs substantially faster than in recent months, now that it avoids installing all ~80 Ansible Collections!

Thanks to @jvonau offering suggestions at #2105.

### CODE REVIEW

**Comment by jvonau** [comment]
Really should enable the ansible ppa and install the same apt package set as used in scripts/ansible.

**Comment by jvonau** [comment]
in place of `pip install ansible-base` numbers are spaces:
>addons:
2apt:
  4sources:
  6 - sourceline: 'ppa:ansible/ansible-2.10'
  4packages:
  6 - ansible-base
  6 - python3-pymysql
  6 -  python3-psycopg2
  6 -  python3-passlib
  6 - python3-pip
  6 - python3-setuptools 
  6 - python3-packaging 
  6 - python3-venv 
  6 - virtualenv

**Comment by holta** [comment]
> in place of `pip install ansible-base` numbers are spaces:
> 
> > addons:
> > 2apt:
> > 4sources:
> > 6 - sourceline: 'ppa:ansible/ansible-2.10'
> > 4packages:
> > 6 - ansible-base
> > 6 - python3-pymysql
> > 6 -  python3-psycopg2
> > 6 -  python3-passlib
> > 6 - python3-pip
> > 6 - python3-setuptools
> > 6 - python3-packaging
> > 6 - python3-venv
> > 6 - virtualenv

Do we really need all those packages for a simple syntax check that takes about 1 second to run?

**Comment by jvonau** [comment]
#2521

**Comment by jvonau** [comment]
>Do we really need all those packages for a simple syntax check that takes about 1 second to run?

Then don't add all of them, just use the ppa for now, pip is not apt, with apt used in the field would it not be the best to have the exact same environment should 'linting' be added to the testing mix?

**Comment by holta** [comment]
I have no idea why the apt install of ansible-base appears slower than the pip install of ansible-base (and certainly a whole lot wordier, in both .travis.yml and the Travis output!)

But it's good enough.  And we can always revert to a pip install of ansible-base later, if we want that bit of extra speed.

**Comment by jvonau** [comment]
All the listed dependencies in the deb are installed, pip is bare bones and can't install system level dependencies not part of python.

**Pull request merged**
