### PR TITLE
Introduce var 'calibreweb_venv_wipe: False' for TDD (test-driven development) of Calibre-Web

### PR DESCRIPTION
**Pull request by holta**
Thanks @deldesir for please reviewing!

▶️ This need not be perfect, but is hopefully much closer to what community testing volunteers truly need.

Building on...

- PR #3503
- PR #3676
- PR #3677

### CODE REVIEW

**Review by deldesir — APPROVED** [review]
Good job. This is getting better and better.

**Comment by holta** [comment]
Many code paths tested on an Ubuntu 24.04 VM.

One example "TDD workflow" that I tested:

I pulled 2 live PR's (iiab/calibre-web#51 and iiab/calibre-web#57) into venv `/usr/local/calibre-web-py3` and then used that code to "reinstall" Calibre-Web as follows...

```
cd /usr/local/calibre-web-py3
git pull https://github.com/deldesir/calibre-web deldesir-oom-fix                   # PR iiab/calibre-web#51
git pull https://github.com/deldesir/calibre-web deldesir-access-fix --no-rebase    # PR iiab/calibre-web#57

cd /opt/iiab/iiab
./runrole --reinstall calibre-web    # Run in ~23 seconds, installing and/or upgrading xklb and yt-dlp as nec!
```

**Comment by tim-moody** [comment]
This is a missed opportunity to set something like calibre-web_reset, that could be a standard for other roles as well.

**Comment by tim-moody** [comment]
also what is its default value and what turns it off?

**Pull request merged**
