### PR TITLE
add mbstring for debian

### PR DESCRIPTION
**Pull request by georgejhunt**
smoke tested on debian 9 vm, will test on other platforms, and rpi hardware, with other branches

### CODE REVIEW

**Comment by holta** [comment]
Some chance this will solve Nextcloud #175 which mentions "PHP module mb multibyte not installed" ?

**Comment by georgejhunt** [comment]
No I think we need to go to 2.3.3 version of nextcloud.   The older one
uses php mysql language, which has been deprecated for years, and finally
removed from php7.

**Comment by holta** [comment]
> No I think we need to go to 2.3.3 version of nextcloud.

Nextcloud's current version is 12.0.2 from August 14, 2017.

You must mean Elgg 2.3.3 from May 16, 2017?

Ref #188 "Elgg 1.12.12 & 1.12.16 don't show anything in browser (500 Internal Server Error)"

**Comment by georgejhunt** [comment]
smoke tested on rpi hardware. I had to attempt to log in twice, before I got the nextcloud data page. There might have been a timeout in my browser that canceled the operation.

**Comment by georgejhunt** [comment]
included by accident in the elgg fixes

**Pull request closed without merging**
