### PR TITLE
disable systemd usbmount

### PR DESCRIPTION
**Pull request by georgejhunt**
### Fixes Bug
Not really a bug -- just annoying boot message

### CODE REVIEW

**Comment by holta** [comment]
@georgejhunt if you have 4 USB sticks inserted, do you know if `systemctl disable usbmount\@.service` acts as a regexp, as if running all 4 commands below?

1. `systemctl disable usbmount@dev-sda.service`
2. `systemctl disable usbmount@dev-sdb.service`
3. `systemctl disable usbmount@dev-sdc.service`
4. `systemctl disable usbmount@dev-sdd.service`

PS this PR mitigates #710

**Comment by jvonau** [comment]
Any reason for this undo function of usb-lib's changes is placed the network section? Seems it would be better to not install the systemd service file in roles/usb-lib/tasks/main.yml's for the rpi's to begin with.

**Comment by jvonau** [comment]
The provided systemd service file might benefit from having an After= present in the unit section to delay the running of this service as not to mount the filesystem too early resulting in read-only. I'll suggest to try After=rc-local.service to delay the mount as late as possible in the boot sequence.

**Comment by holta** [comment]
@jvonau experiment shows another method to make red error go away...adding `After=rc-local.service` to the end of [Unit] section in /etc/systemd/system/usbmount@.service so that it appears as follows:
```
[Unit]
BindTo=%i.device
After=%i.device
After=rc-local.service

...
```

**Comment by georgejhunt** [comment]
Jerry had a better fix

**Comment by holta** [comment]
> Jerry had a better fix

Where should this be implemented / in which playbook?

**Comment by holta** [comment]
Resolved by #722

**Pull request closed without merging**
