### PR TITLE
need sqlite3 for rachel maps

### PR DESCRIPTION
**Pull request by georgejhunt**
### Fixes Bug
rachel maps require sqlite3 module
### Smoke-tested in operating system.
not smoke tested

### CODE REVIEW

**Comment by holta** [comment]
@georgejhunt this works for cities without accents, Thanks!

Do you know why the final click (after autocomplete indeed works!) fails to show those cities, for all cities that contain accents in their names?

**Comment by tim-moody** [comment]
sqlite install was a by-product of installing admin console, which is now optional.

**Comment by tim-moody** [comment]
maybe I missed the point if this is due to a debian version change. could put in os.yml

**Comment by holta** [comment]
@tim-moody & @jvonau please clarify if this PR should be merged, i.e. if it is the best way to accomplish "apt install sql7.0-sqlite3" as Raspbian requires to make city search work, per http://dev.worldpossible.org/mods/en-worldmap-10/map.html

Thanks again to @georgejhunt who solved this making a HUGE different in many Mexican schools 2 weeks ago!

**Comment by tim-moody** [comment]
it is a way to install php7.0-sqlite3, though I don't understand why  when: ansible_local.local_facts.os_ver == "debian-9" didn't work. I don't object to merging after a smoke test.

**Comment by holta** [comment]
> it is a way to install php7.0-sqlite3, though I don't understand why when: ansible_local.local_facts.os_ver == "debian-9" didn't work.

Because it was commented out?

> I don't object to merging after a smoke test.

Agreed: let's merge after a smoke test on Raspbian &mdash; and ideally a functionality test of city searching too!

**Comment by holta** [comment]
Smoke-tested on Raspbian Lite on RPi3.

**Pull request merged**
