### PR TITLE
temp fix for networkd-dispatcher-2.0.1-1 in 'groovy'

### PR DESCRIPTION
**Pull request by jvonau**
revert when fixed upstream

### Fixes bug:
#2585

### CODE REVIEW

**Comment by holta** [comment]
There is some ambiguity as to why Ubuntu Server 20.10 and 21.04 pre-leases (seem) Not to be affected by this bug?

While Ubuntu Desktop 20.10 and 21.04 pre-releases Do seem greatly affected?

In any case: this PR would seem to be an incredibly useful patch...until things get sorted out upstream.

**Comment by holta** [comment]
Should this presumably be made to work on 'hirsute' (hippo) as well as 'groovy' (gorilla) ?

e.g. the BIG-sized IIAB installed on Ubuntu Server 21.04 pre-release at VM 10.8.0.22 if it's useful here?

**Comment by jvonau** [comment]
> Should this presumably be made to work on 'hirsute' (hippo) as well as 'groovy' (gorilla) ?
> 
> e.g. the BIG-sized IIAB installed on Ubuntu Server 21.04 pre-release at VM 10.8.0.22 if it's useful here?

I'll have a look at .22. You should reread my upstream ticket that was tagged as a [duplicate](
https://bugs.launchpad.net/ubuntu/+source/networkd-dispatcher/+bug/1884248), I'm not convinced it's the same bug as 'focal' was not effected in the same way and from what I can tell functions correctly while the linked issue suggests 'hirsute' should be fixed. I don't want to patch if it's been corrected on 'hirsute' as that would skew testing to see if the situation still exists.

**Comment by holta** [comment]
Just fyi @jvonau's upstream bug report is here:
https://bugs.launchpad.net/ubuntu/+source/networkd-dispatcher/+bug/1905283

**Comment by jvonau** [comment]
Notes on 'Ubuntu Server 21.04 pre-release at VM 10.8.0.22'
>iiab-admin@box:\~$ sudo journalctl  -u  networkd-dispatcher.service > netd-disp2.txt
[sudo] password for iiab-admin: 
iiab-admin@box:\~$ cat netd-disp2.txt
-- Logs begin at Sat 2020-11-14 23:54:45 UTC, end at Tue 2020-11-24 13:21:13 UTC. --
Nov 14 23:54:51 u21-srv systemd[1]: Starting Dispatcher daemon for systemd-networkd...
Nov 14 23:54:51 u21-srv networkd-dispatcher[823]: No valid path found for iwconfig
Nov 14 23:54:51 u21-srv systemd[1]: Started Dispatcher daemon for systemd-networkd.
Nov 14 23:59:28 u21-srv systemd[1]: Stopping Dispatcher daemon for systemd-networkd...
Nov 14 23:59:28 u21-srv systemd[1]: networkd-dispatcher.service: Succeeded.
Nov 14 23:59:28 u21-srv systemd[1]: Stopped Dispatcher daemon for systemd-networkd.
-- Reboot --
Nov 14 23:59:47 u21-srv systemd[1]: Starting Dispatcher daemon for systemd-networkd...
Nov 14 23:59:47 u21-srv networkd-dispatcher[651]: No valid path found for iwconfig
Nov 14 23:59:47 u21-srv systemd[1]: Started Dispatcher daemon for systemd-networkd.
Nov 15 00:04:44 u21-srv systemd[1]: Stopping Dispatcher daemon for systemd-networkd...
Nov 15 00:04:44 u21-srv systemd[1]: networkd-dispatcher.service: Succeeded.
Nov 15 00:04:44 u21-srv systemd[1]: Stopped Dispatcher daemon for systemd-networkd.
-- Reboot --
Nov 15 00:07:00 u21-srv systemd[1]: Starting Dispatcher daemon for systemd-networkd...
Nov 15 00:07:00 u21-srv networkd-dispatcher[654]: No valid path found for iwconfig
Nov 15 00:07:00 u21-srv systemd[1]: Started Dispatcher daemon for systemd-networkd.
Nov 15 00:31:43 box.lan networkd-dispatcher[654]: WARNING:Unknown index 3 seen, reloading interface list
Nov 15 01:22:16 box.lan systemd[1]: Stopping Dispatcher daemon for systemd-networkd...
Nov 15 01:22:16 box.lan systemd[1]: networkd-dispatcher.service: Succeeded.
Nov 15 01:22:16 box.lan systemd[1]: Stopped Dispatcher daemon for systemd-networkd.
-- Reboot --
Nov 15 01:22:43 box.lan systemd[1]: Starting Dispatcher daemon for systemd-networkd...
Nov 15 01:22:44 box.lan networkd-dispatcher[668]: No valid path found for iwconfig
Nov 15 01:22:45 box.lan systemd[1]: Started Dispatcher daemon for systemd-networkd.
Nov 15 01:22:46 box.lan networkd-dispatcher[668]: WARNING:Unknown index 3 seen, reloading interface list
Nov 15 01:29:57 box.lan systemd[1]: Stopping Dispatcher daemon for systemd-networkd...
Nov 15 01:29:57 box.lan systemd[1]: networkd-dispatcher.service: Succeeded.
Nov 15 01:29:57 box.lan systemd[1]: Stopped Dispatcher daemon for systemd-networkd.
-- Reboot --
Nov 15 01:30:19 box.lan systemd[1]: Starting Dispatcher daemon for systemd-networkd...
Nov 15 01:30:20 box.lan networkd-dispatcher[668]: No valid path found for iwconfig
Nov 15 01:30:21 box.lan systemd[1]: Started Dispatcher daemon for systemd-networkd.
Nov 15 01:30:22 box.lan networkd-dispatcher[668]: WARNING:Unknown index 3 seen, reloading interface list
Nov 20 15:58:14 box.lan systemd[1]: Stopping Dispatcher daemon for systemd-networkd...
Nov 20 15:58:15 box.lan systemd[1]: networkd-dispatcher.service: Succeeded.
Nov 20 15:58:15 box.lan systemd[1]: Stopped Dispatcher daemon for systemd-networkd.
-- Reboot --
Nov 20 16:48:30 box.lan systemd[1]: Starting Dispatcher daemon for systemd-networkd...
Nov 20 16:48:30 box.lan networkd-dispatcher[672]: No valid path found for iwconfig
Nov 20 16:48:32 box.lan systemd[1]: Started Dispatcher daemon for systemd-networkd.
Nov 20 16:48:33 box.lan networkd-dispatcher[672]: WARNING:Unknown index 3 seen, reloading interface list
Nov 23 06:49:41 box.lan networkd-dispatcher[672]: WARNING:Unknown index 4 seen, reloading interface list
Nov 23 06:51:06 box.lan networkd-dispatcher[672]: WARNING:Unknown index 5 seen, reloading interface list
Nov 23 06:51:40 box.lan networkd-dispatcher[672]: WARNING:Unknown index 6 seen, reloading interface list
Nov 23 07:07:02 box.lan networkd-dispatcher[672]: WARNING:Unknown index 7 seen, reloading interface list
Nov 23 07:09:37 box.lan networkd-dispatcher[672]: WARNING:Unknown index 8 seen, reloading interface list
Nov 23 07:18:54 box.lan networkd-dispatcher[672]: WARNING:Unknown index 9 seen, reloading interface list
Nov 23 07:24:11 box.lan networkd-dispatcher[672]: WARNING:Unknown index 10 seen, reloading interface list
Nov 23 07:47:30 box.lan networkd-dispatcher[672]: WARNING:Unknown index 11 seen, reloading interface list
Nov 23 07:57:11 box.lan networkd-dispatcher[672]: WARNING:Unknown index 12 seen, reloading interface list
Nov 23 07:58:20 box.lan networkd-dispatcher[672]: WARNING:Unknown index 13 seen, reloading interface list
Nov 23 07:59:22 box.lan networkd-dispatcher[672]: WARNING:Unknown index 14 seen, reloading interface list
Nov 23 08:09:32 box.lan networkd-dispatcher[672]: WARNING:Unknown index 15 seen, reloading interface list
Nov 23 08:10:14 box.lan networkd-dispatcher[672]: WARNING:Unknown index 16 seen, reloading interface list
Nov 23 08:13:39 box.lan networkd-dispatcher[672]: WARNING:Unknown index 17 seen, reloading interface list
Nov 23 08:24:57 box.lan networkd-dispatcher[672]: WARNING:Unknown index 18 seen, reloading interface list

Something is getting logged now.
>iiab-admin@box:~$ ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
2: enp0s3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 08:00:27:26:9e:0c brd ff:ff:ff:ff:ff:ff
    inet 192.168.0.196/24 brd 192.168.0.255 scope global enp0s3
       valid_lft forever preferred_lft forever
    inet6 fe80::a00:27ff:fe26:9e0c/64 scope link 
       valid_lft forever preferred_lft forever
18: tun0: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UNKNOWN group default qlen 100
    link/none 
    inet 10.8.0.22 peer 10.8.0.21/32 scope global tun0
       valid_lft forever preferred_lft forever

Looks like 'Unknown index' is related to "tun0" noted the '18' is present with `ip a`: **18: tun0:** above

>iiab-admin@box:~$ apt list networkd-dispatcher 
Listing... Done
networkd-dispatcher/hirsute,now 2.1-1 all [installed,automatic]

/var/log/apt/history.log lists networkd-dispatcher in the first entry "Start-Date: 2020-11-14  07:13:13"

Single interface VMs don't actually test the network well enough to draw any conclusions but can help point out where the future is pointing.

**Comment by jvonau** [comment]
Sample of 20.10 with fix applied:
>ubuntu@box:/opt/iiab/iiab$ sudo systemctl -l status networkd-dispatcher.service > ~/fixed.txt
ubuntu@box:/opt/iiab/iiab$ cat ~/fixed.txt
● networkd-dispatcher.service - Dispatcher daemon for systemd-networkd
     Loaded: loaded (/lib/systemd/system/networkd-dispatcher.service; enabled; vendor preset: enabled)
     Active: active (running) since Mon 2020-11-23 19:22:02 CST; 12h ago
   Main PID: 57618 (python3)
      Tasks: 1 (limit: 4141)
     CGroup: /system.slice/networkd-dispatcher.service
             └─57618 python3 /usr/bin/networkd-dispatcher --run-startup-triggers
Nov 23 19:21:54 box.lan networkd-dispatcher[57630]: NET-DISP-WiFi wlan0 routable
Nov 23 19:21:54 box.lan networkd-dispatcher[57630]: Using channel 11 for carrier
Nov 23 19:21:54 box.lan networkd-dispatcher[57630]: Hostapd set for 11
Nov 23 19:21:54 box.lan networkd-dispatcher[57630]: Upstream Channel greater than 13 or is the same - not changing hostapd.conf
Nov 23 19:21:57 box.lan networkd-dispatcher[57641]: NET-DISP-configured br0 routable
Nov 23 19:21:57 box.lan networkd-dispatcher[57642]: Restarting dnsmasq in 5 seconds
Nov 23 19:22:02 box.lan networkd-dispatcher[57642]: Restarted dnsmasq
Nov 23 19:22:02 box.lan networkd-dispatcher[57655]: NET-DISP-unmanaged ap0 carrier
Nov 23 19:22:02 box.lan networkd-dispatcher[57665]: NET-DISP-unmanaged tun0 routable
Nov 23 19:22:02 box.lan systemd[1]: Started Dispatcher daemon for systemd-networkd.

**Comment by holta** [comment]
If I recruit a volunteer to do a fresh 1-line install of this PR...

```
curl d.iiab.io/install.txt | sudo bash -s 2645
```

...what exact OS is most useful for testing here?

**Comment by jvonau** [comment]
> There is some ambiguity as to why Ubuntu Server 20.10

Not enough data to rule out U-20.10-server as **NOT** effected, VMs may not trigger the issue. Just checked 182-rpi4-2g-u2010-srv-MIN, the situation with networkd-dispatcher exists there also, the WiFi hotspot was never tested as functioning correctly as /var/lib/misc/dnsmasq.leases is empty.

**Comment by jvonau** [comment]
> ...what exact OS is most useful for testing here?

"groovy" server or desktops are the only ones where this issue shows up.

**Comment by holta** [comment]
> "groovy" server or desktops are the only ones where this issue shows up.

I believe @deldesir in Haiti installed Ubuntu Server 20.10 (Groovy Gorilla) on a laptop recently, and I'll ask him if he possibly has time over the coming days to do a fresh install of this PR #2645 on there.

ASIDE: my personal preference is to put keywords like "Ubuntu 20.10" in the subject line of tickets, so as to make them much more findable later.  Granted "Groovy" is a nickname/synonym, but digging up old emails/tickets is always a pain-in-the-butt, so I try to use the most mainstream/canonical keywords/names (e.g. things like "Ubuntu") where possible anyway.

**Comment by holta** [comment]
Does this issue/fix also affect 10.8.0.42 = 182-rpi4-2g-u2010-srv-MIN and 10.8.0.46 = 183-rpi4-2g-u2010-desk-MIN ?

i.e. is it also useful to test this PR on U20.10 on RPi 4, and which test(s) would be most useful if so...Server or Desktop?

(Apologies if I'm losing track.)

**Comment by jvonau** [comment]
Hope you are capable of looking at `systemctl status networkd-dispatcher` and making up your own mind.

**Comment by jvonau** [comment]
> If I recruit a volunteer to do a fresh 1-line install of this PR...

Why do a full install when you have **2** machines right next to you that should show this error, See https://github.com/iiab/iiab/pull/2645#issuecomment-733005635. Just apply this PR and `sudo ./iiab-network` but you should know that already.

**Comment by holta** [comment]
Prior to applying this PR, 10.8.0.46 = 183-rpi4-2g-u2010-desk-MIN shows: (likewise on 10.8.0.42 = 182-rpi4-2g-u2010-srv-MIN)

```
root@box:~# systemctl restart networkd-dispatcher
root@box:~# systemctl status networkd-dispatcher
● networkd-dispatcher.service - Dispatcher daemon for systemd-networkd
     Loaded: loaded (/lib/systemd/system/networkd-dispatcher.service; enabled; vendor preset: enabled)
     Active: active (running) since Wed 2020-11-25 07:42:37 EST; 1s ago
   Main PID: 7825 (networkd-dispat)
      Tasks: 1 (limit: 1811)
     CGroup: /system.slice/networkd-dispatcher.service
             └─7825 /usr/bin/python3 /usr/bin/networkd-dispatcher --run-startup-triggers

Nov 25 07:42:37 box.lan networkd-dispatcher[7825]:   File "/usr/bin/networkd-dispatcher", line 328, in run_hooks_for_state
Nov 25 07:42:37 box.lan networkd-dispatcher[7825]:     'json': json.dumps(data, sort_keys=True),
Nov 25 07:42:37 box.lan networkd-dispatcher[7825]:   File "/usr/lib/python3.8/json/__init__.py", line 234, in dumps
Nov 25 07:42:37 box.lan networkd-dispatcher[7825]:     return cls(
Nov 25 07:42:37 box.lan networkd-dispatcher[7825]:   File "/usr/lib/python3.8/json/encoder.py", line 199, in encode
Nov 25 07:42:37 box.lan networkd-dispatcher[7825]:     chunks = self.iterencode(o, _one_shot=True)
Nov 25 07:42:37 box.lan networkd-dispatcher[7825]:   File "/usr/lib/python3.8/json/encoder.py", line 257, in iterencode
Nov 25 07:42:37 box.lan networkd-dispatcher[7825]:     return _iterencode(o, 0)
Nov 25 07:42:37 box.lan networkd-dispatcher[7825]: TypeError: '<' not supported between instances of 'NoneType' and 'str'
Nov 25 07:42:37 box.lan systemd[1]: Started Dispatcher daemon for systemd-networkd.
```

Then this PR was applied, on 10.8.0.46: (likewise on 10.8.0.42)

```
cd /opt/iiab/iiab
git checkout -b jvonau-netd-disp-fix master
git pull https://github.com/jvonau/iiab.git netd-disp-fix
./iiab-network
```

After applying this PR, `systemctl restart networkd-dispatcher` was needed, but then all seems good on 10.8.0.46: (likewise on 10.8.0.42)

```
root@box:/opt/iiab/iiab# systemctl restart networkd-dispatcher
root@box:/opt/iiab/iiab# systemctl status networkd-dispatcher
● networkd-dispatcher.service - Dispatcher daemon for systemd-networkd
     Loaded: loaded (/lib/systemd/system/networkd-dispatcher.service; enabled; vendor preset: enabled)
     Active: active (running) since Wed 2020-11-25 07:48:14 EST; 1s ago
   Main PID: 13478 (python3)
      Tasks: 1 (limit: 1811)
     CGroup: /system.slice/networkd-dispatcher.service
             └─13478 python3 /usr/bin/networkd-dispatcher --run-startup-triggers

Nov 25 07:48:08 box.lan networkd-dispatcher[13481]: NET-DISP-unmanaged lo carrier
Nov 25 07:48:08 box.lan networkd-dispatcher[13484]: NET-DISP-unmanaged eth0 routable
Nov 25 07:48:08 box.lan networkd-dispatcher[13489]: NET-DISP-unmanaged wlan0 no-carrier
Nov 25 07:48:08 box.lan networkd-dispatcher[13490]: NET-DISP-WiFi wlan0 no-carrier
Nov 25 07:48:09 box.lan networkd-dispatcher[13495]: NET-DISP-unmanaged ap0 carrier
Nov 25 07:48:09 box.lan networkd-dispatcher[13498]: NET-DISP-configured br0 routable
Nov 25 07:48:09 box.lan networkd-dispatcher[13499]: Restarting dnsmasq in 5 seconds
Nov 25 07:48:14 box.lan networkd-dispatcher[13499]: Restarted dnsmasq
Nov 25 07:48:14 box.lan networkd-dispatcher[13511]: NET-DISP-unmanaged tun0 routable
Nov 25 07:48:14 box.lan systemd[1]: Started Dispatcher daemon for systemd-networkd.
```

FYI `/etc/default/networkd-dispatcher` currently appears as: (on 10.8.0.46, and likewise on 10.8.0.42)

```
root@box:~# more /etc/default/networkd-dispatcher
# Specify command line options here. This config file is used
# by the included systemd service file.
networkd_dispatcher_args="--run-startup-triggers"
#JV
#networkd_dispatcher_args="-vv"
```

**Comment by holta** [comment]
FYI after applying this PR, a quick followup test of the WiFi hotspot (and then browsing to http://box, with an Android phone) worked for both, 10.8.0.42 = 182-rpi4-2g-u2010-srv-MIN and 10.8.0.46 = 183-rpi4-2g-u2010-desk-MIN.

**Pull request merged**
