### PR TITLE
Tighten up Asterisk deps + Remember to Enable/Disable Asterisk + Move PBX from Stage 6 to 9

### PR DESCRIPTION
**Pull request by holta**
Tightens up & refines the PBX role in general, towards the next phase of stripping out or containing/isolating Apache as much as possible.  Thanks to several @jvonau suggestions.  So the real work can begin with @lemueldsouza tomorrow.

Tested on Debian 11 (server).  Testing is ongoing on Ubuntu Server 20.04:

- PR #2899 
- PR #2901
- PR #2902

### CODE REVIEW

**Comment by jvonau** [comment]
https://github.com/iiab/iiab/pull/2899#issuecomment-892081046 Think there is still the question of 'does fwconsole still manage asterisk' before enabling a systemd unit file for asterisk

**Comment by holta** [comment]
> [#2899 (comment)](https://github.com/iiab/iiab/pull/2899#issuecomment-892081046) Think there is still the question of 'does fwconsole still manage asterisk' before enabling a systemd unit file for asterisk

It is a fair question for sure!

Myself I'm just really tired of Asterisk not starting, on one install after another, across our most mainstream OS's &mdash; which will certainly drive implementers nuts.

Until someone comes up with a more sophisticated answer to the above question (@lemueldsouza or @m-anish might know?) I do want Asterisk to start reliably.  And so I've made the good-enough-for-now approach happen within this PR's [roles/pbx/tasks/enable-or-disable.yml](https://github.com/holta/iiab/blob/asterisk-deps-and-refine-pbx/roles/pbx/tasks/enable-or-disable.yml#L1-L15)

**Comment by holta** [comment]
Also tested successfully on a Ubuntu Server 20.04 VM.

**Comment by jvonau** [comment]
https://github.com/iiab/iiab/blob/master/roles/pbx/tasks/freepbx.yml#L35-L43 seem to be stale if freepbx was updated similar to https://github.com/iiab/iiab/blame/master/roles/pbx/tasks/freepbx.yml#L117-L120

**Comment by jvonau** [comment]
4c1b8906d6f7a76e36b0ff0995b129d52e2f6a87 think I introduced a regression at https://github.com/iiab/iiab/blame/master/roles/pbx/tasks/freepbx.yml#L108 which I think is bogus remove it, the exact same condition is in the stanza below.

**Comment by holta** [comment]
Done!  This PR implements both of @jvonau's suggestions above:

- PR #2906

**Pull request merged**
