### PR TITLE
iiab-install4: ./runansible -> ./iiab-install avoids repetition of Stages 1-9 when rerun

### PR DESCRIPTION
**Pull request by jvonau**
### Fixes Bug
replaces #487 and others (will close open RPs as needed)
### Description of changes proposed in this pull request.
as per meeting (http://minutes.iiab.io)
### Smoke-tested in operating system.
jenkins:8080/job/IIAB-debian-jvonau/124/console

### CODE REVIEW

**Comment by holta** [comment]
Replaces #477 #486 #487

**Comment by holta** [comment]
If there's time, let's invert the kernel-check conditional @ [jvonau/iiab/blob/iiab-install4/iiab-install#L24-L31](https://github.com/jvonau/iiab/blob/iiab-install4/iiab-install#L24-L31) in the coming ~24h.

To reject kernel 4.9.41-v7+ (with a 1-sentence PSA insisting they "apt update" then "apt dist-upgrade" then reboot for kernel 4.9.59-or-higher...ideally including a URL to https://github.com/iiab/iiab/wiki/IIAB-Installation#do-everything-from-scratch ?)

**Comment by tim-moody** [comment]
re: jiggle fl.yml why is this run twice? also I thought first-run was eliminated.

**Comment by holta** [comment]
> re: jiggle fl.yml why is this run twice?

What makes you believe fl.yml is being run twice?

(I may be wrong, but I'm not seeing that!)

**Comment by holta** [comment]
Lines 22, 47 and 53 of [/opt/iiab/iiab/iiab-install](https://github.com/jvonau/iiab/blob/iiab-install4/iiab-install) looks like bugs...shouldn't these be "==" instead of "=" ?
```
if [ $OS == "raspbian" ]; then
...
if [ "$OLD" != 0 ] || [ "$1" == "--reinstall" ]; then
...
if [ "$1" == "--debug" ]; then
```
...instead of
```
if [ $OS = "raspbian" ]; then
...
if [ "$OLD" != 0 ] || [ "$1" = "--reinstall" ]; then
...
if [ "$1" = "--debug" ]; then
```
...similar to lines 56 and 58?

**Comment by holta** [comment]
I'm in favor or merging PR490 a.s.a.p. after @jvonau & @tim-moody can nail the above small issues, one way or another, so we can dramatically increase testing coverage as a collaborative community&mdash;Thanks all for pushing this over the hump now!

**Comment by tim-moody** [comment]
is fl.yml not in both hostname.yml and roles/2-common/tasks/main.yml?

**Comment by holta** [comment]
> is fl.yml not in both hostname.yml and roles/2-common/tasks/main.yml?

No it is not.

Please see https://github.com/jvonau/iiab/blob/iiab-install4/roles/2-common/tasks/main.yml#L9

**Comment by tim-moody** [comment]
sorry, missed the pound sign

**Comment by holta** [comment]
Thanks @tim-moody & thanks @jvonau & thanks ALL for making this push possible~

I'll merge this sometime after midnight EST if there are no objections.

Until then, let's try to freeze this PR490 please (or limit it to byte-sized and/or doc changes!) rather than piling on further &mdash; incremental issues can be community-tested broadly as part of RC's very soon &mdash; prior to final release around the 3rd week of Nov!

**Comment by holta** [comment]
Oops I was wrong above: bash does tolerate a single equal sign (=) to test strings' (lexical) equality.  Apparently that's specified by POSIX, so preferred by traditionalists.

At some point we should lint all of our code &mdash; changing one way or the other for readability -> testing string equivalence consistently &mdash; either with (==) or (=) whatever we decide...

PS bash requires "-eq" to test numerical equality.

**Comment by jvonau** [comment]
I've been looking at what the code should look like in PR #493 to make
travis happy and still run. How about the group clean up the massive amount
of ansible code that does not pass travis due to being written
incorrectly(but runs anyway) to begin with?

**Comment by holta** [comment]
Extensively smoke-tested with basic functionality-testing on Raspbian Lite 2017-09-07 on RPi3 especially.

**Pull request merged**
