### PR TITLE
rename apache_allow_sudo [to allow_www_data_sudo] and make True default

### PR DESCRIPTION
**Pull request by tim-moody**

### CODE REVIEW

**Comment by holta** [comment]
In conjunction with:

- PR iiab/iiab-admin-console#591

As discussed in:

- PR #3868

**Comment by holta** [comment]
@tim-moody is this tested & good enough to merge with... ?

- PR iiab/iiab-admin-console#591

**Comment by tim-moody** [comment]
doing a bit more then I will merge

**Comment by tim-moody** [comment]
Tested on W2 with none local vars:

- Smoke test passed
- Turning on poweroff in menu causes poweroff button to appear and work
- Turning on set time in menu causes a connection from my Android phone or Win 11 laptop to set system time
- Turning off either stops the corresponding behavior

**Comment by tim-moody** [comment]
Another comment regarding Rpi 5:

I thought my rpi 5 had a battery for its RTC, but when I powered it up with no Internet connection is showed an old date. When I then connected the ethernet cable with Internet access the date adjusted to the current datetime.

It's of course possible that the 5 is not setup properly, but others might have the same experience.

**Comment by holta** [comment]
Does the Raspberry Pi 5 RTC / battery need to be purchased separately for $5 as suggested by... ?

https://www.raspberrypi.com/products/rtc-battery/

**Comment by holta** [comment]
FWIW https://chicagodist.com/products/rtc-battery-for-raspberry-pi-5 suggests a $5 battery needs to be purchased separately:

> The power-management IC used on Raspberry Pi 5 integrates a real-time clock, and charging circuitry for a button cell which can power the clock while main power is disconnected.
>
> We offer a Panasonic ML-2020 Lithium Manganese Dioxide battery, with a two-pin plug suitable for connection to the battery connector on the Raspberry Pi 5 PCB.

**Comment by tim-moody** [comment]
Yes. I probably didn't add one.

**Comment by holta** [comment]
1. Official RTC docs here:

   - https://www.raspberrypi.com/documentation/computers/raspberry-pi.html#real-time-clock-rtc

2. RTC battery with Raspberry Pi 500 requires violating the warranty & serious soldering as shown in this video: 

   - https://www.hackster.io/simonvav/raspberry-pi-500-real-time-clock-battery-works-6cf9ab

   - https://youtu.be/o8OjwexNiWE

**Pull request merged**
