### PR TITLE
Node-RED on NGINX not Apache

### PR DESCRIPTION
**Pull request by holta**
Building on @jvonau's PR #2840.

Thanks @deldesir and @m-anish for please reviewing/testing, even if after this is merged!

Refs:

- #2762
- PR #2841

### CODE REVIEW

**Comment by holta** [comment]
Smoke-tested with very basic functionality testing on 64-bit Ubuntu Server 21.04 on Raspberry Pi 4.

After logging into http://box/nodered there are often warnings at the top of the screen showing:

```
Lost connection to server, reconnecting...
```

The above issue's not exactly new over the past couple years.   Though possibly it's more frequent & more severe than in the past?  (Does anybody understand how to permit websockets through an NGINX proxy?!)  As it all appears to work fine when being tested UNPROXIED as follows:

http://192.168.0.183:1880/nodered

**Comment by holta** [comment]
These WebSocket-over-NGINX-proxy suggestions seem to improve the situation if not quite fix it?

- https://groups.google.com/g/node-red/c/WqWTbYCbhfs/m/EvLtyInvDAAJ
- https://stackoverflow.com/questions/12102110/nginx-to-reverse-proxy-websockets-and-enable-ssl-wss/14969925#14969925

**Comment by holta** [comment]
@jvonau this single stanza appears to work better (commit just above) so far avoiding all "Lost connection to server, reconnecting..." errors.  As borrowed from this code sample:

https://gist.github.com/boneskull/d418b7c871d2248cfeba

Would you possibly know why?

**Comment by holta** [comment]
Also tested on 32-bit RaspiOS Lite on RPi 4 &mdash; so far Node-RED would appear to be dramatically improved as compared to the past couple years &mdash; as a result of the WebSockets-over-NGINX-proxy fix just above!

Going Forward:

_More broad community-testing on other OS's (e.g. Debian 11 and others) would be most welcome after this is merged._

**Comment by jvonau** [comment]
> @jvonau this single stanza appears to work better (commit just above) so far avoiding all "Lost connection to server, reconnecting..." errors. As borrowed from this code sample:
> 
> https://gist.github.com/boneskull/d418b7c871d2248cfeba
> 
> Would you possibly know why?

Same reason jupyterhub uses that type of 'upgrade' to serve the pages with ssl transparently by not switching ports?

**Comment by jvonau** [comment]
>"Lost connection to server, reconnecting..." errors.

Are still present on RaspOS, just takes some time to show up, need to lose the trailing slash..
```
location /nodered {
    proxy_pass http://127.0.0.1:{{ nodered_port }}/nodered;
```

**Comment by holta** [comment]
> > "Lost connection to server, reconnecting..." errors.
> 
> Are still present on RaspOS, just takes some time to show up, need to lose the trailing slash..
> 
> ```
> location /nodered {
>     proxy_pass http://127.0.0.1:{{ nodered_port }}/nodered;
> ```

Really great news if that heals the bug(s) reported at:

- #2833

@deldesir can you please create a PR and test ?

**Comment by holta** [comment]
Just a clarification of what was mentioned ~2.5 days ago — http://10.8.0.22/lokole on Ubuntu Desktop 22.04 (pre-release daily build on x86_64 VM) appears to fully work after @jvonau's 2021-09-30 workaround is run: (which boils down to installing Lokole twice)

- https://github.com/iiab/iiab/issues/2833#issuecomment-981079242

**Comment by jvonau** [comment]
I'm suggesting to try  "http://10.8.0.22/lokole/" and "http://10.8.0.22/nodered/" in the browser with the trailing `/` before the reinstall, think the trailing "/" might point to the need to remove its presence in the template, that is all... No PR coming (why bother not worth the drama for me) just a hint where to look.

**Comment by holta** [comment]
> I'm suggesting to try "http://10.8.0.22/lokole/" and "http://10.8.0.22/nodered/" in the browser with the trailing / before the reinstall

FWIW on Ubuntu Desktop 21.10 VM: (x86-64)

- The trailing / did not help with http://10.8.0.50/lokole/ (the [Lokole workaround](https://github.com/iiab/iiab/issues/2833#issuecomment-931559600) has not been applied)
- With http://10.8.0.50/nodered the trailing slash was not necessary, as it redirected to add its own trailing slash.  In any case, Node-RED worked right away after it was first installed (using `./runrole nodered`).

[iiab-diagnostics](https://github.com/iiab/iiab/blob/master/scripts/iiab-diagnostics.README.md) output: http://sprunge.us/T2erwy?en

**Pull request merged**
