### PR TITLE
Explain how to find alternative Kolibri apt / .deb installers (e.g. when 0.12.9 fails to install)

### LINKED ISSUE #2045: Kolibri's new 0.12.9 apt/deb package fails to install
@benjaoming we've confirmed this brand new failure to install Kolibri 0.12.9 on Debian 10.2 and also on Ubuntu.  The running code is here:

https://github.com/iiab/iiab/blob/master/roles/kolibri/tasks/main.yml#L48-L54

Do have recommendations below?  And/or should IIAB revert to Kolibri 0.12.8 for now?  Error is:

> TASK [kolibri : apt install latest Kolibri .deb from https://learningequality.org/r/kolibri-deb-latest (populates /library/kolibri / migrates database, based on params set in /etc/kolibri)] ***
fatal: [127.0.0.1]: FAILED! => {"changed": false, "msg": "dpkg --force-confdef --force-confold -i /root/.ansible/tmp/ansible-tmp-1574352150.99-132899473790064/kolibri-deb-latestkaicwiky failed", "stderr": "insserv: script ejabberd-iiab: service ejabberd already provided!\nTraceback (last called is first):\n     kolibri_configure() in /var/lib/dpkg/info/kolibri.postinst:1\n     main() in /var/lib/dpkg/info/kolibri.postinst:456\ndpkg: error processing package kolibri (--install):\n subprocess installed post-installation script returned error exit status 1\nErrors were encountered while processing:\n kolibri\n", "stderr_lines": ["insserv: script ejabberd-iiab: service ejabberd already provided!", "Traceback (last called is first):", "     kolibri_configure() in /var/lib/dpkg/info/kolibri.postinst:1", "     main() in /var/lib/dpkg/info/kolibri.postinst:456", "dpkg: error processing package kolibri (--install):", " subprocess installed post-installation script returned error exit status 1", "Errors were encountered while processing:", " kolibri"], "stdout": "(Reading database ... 310518 files and directories currently installed.)\nPreparing to unpack .../kolibri-deb-latestkaicwiky ...\nUnpacking kolibri (0.12.9-0ubuntu1) over (0.12.8-0ubuntu1) ...\nSetting up kolibri (0.12.9-0ubuntu1) ...\nInstalling new version of config file /etc/default/kolibri ...\nInstalling new version of config file /etc/init.d/kolibri ...\nProcessing triggers for systemd (229-4ubuntu21.22) ...\nProcessing triggers for ureadahead (0.100.0-19.1) ...\n", "stdout_lines": ["(Reading database ... 310518 files and directories currently installed.)", "Preparing to unpack .../kolibri-deb-latestkaicwiky ...", "Unpacking kolibri (0.12.9-0ubuntu1) over (0.12.8-0ubuntu1) ...", "Setting up kolibri (0.12.9-0ubuntu1) ...", "Installing new version of config file /etc/default/kolibri ...", "Installing new version of config file /etc/init.d/kolibri ...", "Processing triggers for systemd (229-4ubuntu21.22) ...", "Processing triggers for ureadahead (0.100.0-19.1) ..."]}

### PR DESCRIPTION
**Pull request by holta**
Resolves #2045 so that BIG-sized IIAB installs stop breaking (arose as a result of Kolibri 0.12.9's broken release, whose apt .deb installer was published off of https://learningequality.org/download/ sometime in the last 24h).

### CODE REVIEW

**Comment by jvonau** [comment]
think the real issue is 'latest' is not pointing to kolibri_0.12.9-0ubuntu2_all.deb where the fix is..

**Comment by holta** [comment]
> think the real issue is 'latest' is not pointing to kolibri_0.12.9-0ubuntu2_all.deb where the fix is..

My understanding is that Learning Equality's QA process intentionally introduces such delays so that testing becomes more thorough, instead of immediately publishing fixes that so often have unintended consequences.

Hence my preference that IIAB falls back to Kolibri 0.12.8 until the dust settles.

**Comment by jvonau** [comment]
Something slipped through the cracks if 'latest' is stable and QA'd or is that intended for bleeding edge testing?

**Comment by holta** [comment]
> Something slipped through the cracks if 'latest' is stable and QA'd or is that intended for bleeding edge testing?

Slipped thru the cracks.  Learning Equality has invested more in QA over recent years but 'complexity kills' and these show-stoppers still sometimes creep into final releases...

**Comment by jvonau** [comment]
By using 'latest' we were testing unofficial releases as 0.12.8 doe not appear in the [ppa](http://ppa.launchpad.net/learningequality/kolibri/ubuntu/pool/main/k/kolibri-source/) just 0.12.5 & 0.12.9 with the bug fix in the second release.

**Pull request merged**
