### PR TITLE
Experiment w/ kiwix-tools nightly 2021-12-17 (requires libzim 7.0.0 and then libkiwix 10.0.0)

### PR DESCRIPTION
**Pull request by holta**
SEE: https://github.com/openzim/libzim/milestone/2

Ref:

- PR #2815

### CODE REVIEW

**Comment by holta** [comment]
After nearly a week, this PR should probably be re-issued, sometime in coming days, based on the latest here...

http://download.kiwix.org/nightly/

**Comment by holta** [comment]
Does anybody have feedback on the new kiwix-serve, negative or positive ?

(I can push another "weekly" pre-release if necessary...)

**Comment by holta** [comment]
Another "weekly" pre-release of kiwix-serve can be pushed into this PR if necessary...?

**Comment by holta** [comment]
libzim 7.0.0 has not converged as quickly as expected, but we should still definitely check out the latest progress (nightly build of kiwix-serve) later this week as this is getting very close now...

**Comment by holta** [comment]
Looks like libzim 7.0.0 (for kiwix-serve, etc, as part of kiwix-tools) is likely converging in coming days or soon.

This is really good news!  Given that kiwix-tools 3.1.2 was released more than 15 months ago on 2020-07-02: https://github.com/kiwix/kiwix-tools/blob/master/Changelog

Refs:

- PR #2815
- PR https://github.com/openzim/libzim/pull/630

**Comment by mgautierfr** [comment]
libzim 7 is closed to be release but it will not help you a lot.
We still need to do the release of libkiwix to have a real change useful to you.

At best we will also do a new build of zim-tools, but kiwix-tools and kiwix-desktop will not change until we release libkiwix.

**Comment by holta** [comment]
> At best we will also do a new build of zim-tools, but kiwix-tools and kiwix-desktop will not change until we release libkiwix

Thanks @mgautierfr

Is libkiwix 10.0.0 related?  Or is that more in the distant future?

- https://github.com/kiwix/libkiwix/issues/618

Background: libkiwix 9.4.1 was released 2020-11-17:

- https://github.com/kiwix/libkiwix/releases

**Comment by mgautierfr** [comment]
Yes, we are speaking about libkiwix 10.0.0

**Comment by holta** [comment]
> Yes, we are speaking about libkiwix 10.0.0

It's great that libzim 7.0.0 is now released — as a key building block towards libkiwix and kiwix-serve progress soon — hopefully in a few short weeks:

- https://lists.wikimedia.org/hyperkitty/list/offline-l@lists.wikimedia.org/thread/45Q35AAMCN6JVFCZ5T6UVY7BYQVW2USH/
- https://github.com/openzim/libzim/blob/master/ChangeLog

**Comment by holta** [comment]
libzim's new documentation:

https://libzim.readthedocs.io

**Comment by holta** [comment]
Just a clarification that the new release of kiwix-serve ([3.2.0 or 3.3.0?](https://github.com/kiwix/kiwix-tools/milestones)) is awaiting libkiwix 10.0.0 and its 4 remaining tickets here:

https://github.com/kiwix/libkiwix/milestone/1

**Comment by holta** [comment]
@icebox827 reports that this PR appears to work well with recently published ZIM files on Ubuntu Desktop 21.10 on x86_64, great news.

_He used Incognito tabs to make sure that his browser cache was cleared (effectively anyway)._

@avni can you confirm that ZIM files are searchable on armhf if possible?  (i.e. if you're able to test this on 32-bit Raspberry Pi OS — on either Raspberry Pi 4 or Raspberry Pi 400?)

Context:

- kiwix/kiwix-tools#505

**Comment by holta** [comment]
Thanks to @icebox827 for having tested this overnight &mdash; it fixes important things compared to the older 2021-06-09 kiwix-serve &mdash; so let's roll this into IIAB 7.2 pre-release for wider community testing now.

Example: it fixes the dice button when using ZIM files like...

- http://iiab.me/kiwix/wikihow_fr_maxi_2021-10/ 14G
- http://iiab.me/kiwix/wikihow_es_maxi_2021-10/ 20G
- http://iiab.me/kiwix/wikihow_en_maxi_2021-10/ 41G

**Comment by holta** [comment]
Somewhat Related:

- kiwix/kiwix-tools#505
  - kiwix/libkiwix#650
- kiwix/kiwix-tools#513

**Pull request merged**
