### PR TITLE
Mitra - 'internetarchive' & 'yarn' Ansible playbooks for IIAB

### PR DESCRIPTION
**Pull request by mitra42**
### Fixes Bug
Partial for issue #1576 

### Description of changes proposed in this pull request.
Installation process for Internet Archive code into IIAB 

### Smoke-tested in operating system.
Tested on RPI (Raspbian) current. 

### Mention a team member for further information or comment using @ name
@holta

### CODE REVIEW

**Comment by holta** [comment]
Thanks to @georgejhunt who will try to review this PR in the coming ~48h !

Possibly Related: #1622

**Comment by holta** [comment]
> Thanks to @georgejhunt who will try to review this PR in the coming ~48h !
> 
> Possibly Related: #1622

@m-anish please also review this, Thanks!

**Comment by georgejhunt** [comment]
- Before we merge, I'd like to change the internetarchive_(install/enabled) to false in role/defaults.
- On my clean install, http://<ip>:4244 works, but http://<ip>/archive.org fails with apache error Cannot GET /internetarchive
- So we may need to compare experiences some (this test was not associated to the wifi) -- I'll try that.
- But I get the same symptoms when I try box.lan after connecting to wifi. (port works, internetarchive does not.

**Comment by holta** [comment]
> * Before we merge, I'd like to change the internetarchive_(install/enabled) to false in role/defaults.

Agreed.  [default_vars.yml](https://github.com/iiab/iiab/blob/master/vars/default_vars.yml), [local_vars_min.yml](https://github.com/iiab/iiab/blob/master/vars/local_vars_min.yml) & [local_vars_medium.yml](https://github.com/iiab/iiab/blob/master/vars/local_vars_medium.yml) should each contain the following:
```
internetarchive_install: False
internetarchive_enabled: False
```
If these 2 new Ansible playbooks ('internetarchive' & 'yarn') have been tested on Raspbian, Ubuntu 18.04 & Debian 9.9 then [local_vars_big.yml](https://github.com/iiab/iiab/blob/master/vars/local_vars_big.yml) should contain the following:
```
internetarchive_install: True
internetarchive_enabled: True
```
After @mitra42 hopefully implements the above, I can then document that within the table at http://FAQ.IIAB.IO Item 9 ("What services (IIAB apps) are suggested during installation?")

**Comment by mitra42** [comment]
Happy to make the variable changes, but also need to add instructions to my code on how to change them to true, what is the prefered way.

@georgejhunt - I'm not undersstanding what you mean by http://:4244 works, but http:///archive.org do you mean from locally running browser (in local keyboard / display) if so I would expect http://:4244 to work, but http:///archive.org isn't going to work because that redirect can't work without knowing what to connect to, and box.lan only works in a small subset of cases.

**Comment by mitra42** [comment]
By the way, the main server at IA that we use to get initial content is down at the moment - it runs on Kubernetes so there is only one person at IA who can fix it :-(. So tests of the IA software on new machines are going to hit problems as they won't have any crawlable/cached data to work with if they aren't seeded from a USB drive. (I'm just trying to create such a drive for Mike Jensen to use in his test).

**Comment by holta** [comment]
> Happy to make the variable changes, but also need to add instructions to my code on how to change them to true, what is the prefered way.

Thanks @mitra42.  I suggest you also place the following 7 lines at the top of roles/internetarchive/defaults/main.yml — anyway this is our standard template:
```
# internetarchive_install: False
# internetarchive_enabled: False

# internetarchive_port: 4244

# All above are set in: github.com/iiab/iiab/blob/master/vars/default_vars.yml
# If nec, change them by editing /etc/iiab/local_vars.yml prior to installing!
```

**Comment by mitra42** [comment]
Done and pushed to mitra42/iiab#distweb 

I can't figure out how to update this PR to use that new commit, does anyone know how ?

@holta  - is /etc/iiab/local_vars.yml the place you are prompted to edit during install ? 

@georgejhunt its tested on Raspbian only, unless @m-anish tested on something else. I don't have those environments to test in.

**Comment by holta** [comment]
> @holta - is /etc/iiab/local_vars.yml the place you are prompted to edit during install ?

Yes!

https://github.com/iiab/iiab-factory/blob/master/iiab#L123-L131

**Comment by holta** [comment]
> Done and pushed to mitra42/iiab#distweb
> 
> I can't figure out how to update this PR to use that new commit, does anyone know how ?

"[branch] distweb is up to date with all commits from [branch] mitra" according to https://github.com/mitra42/iiab/compare/distweb...mitra42:mitra

https://github.com/mitra42/iiab/compare/mitra42:mitra...distweb if you want to create a PR in the other direction?

**Comment by holta** [comment]
> @georgejhunt its tested on Raspbian only, unless @m-anish tested on something else. I don't have those environments to test in.

@m-anish can you test this PR on Debian 9.9 ?

@georgejhunt can you test this PR on Ubuntu 18.04 Server and/or Desktop?

A clean VM is best.  But you can also try:
```
cd /opt/iiab/iiab
git checkout -b mitra42-mitra master
git pull https://github.com/mitra42/iiab.git mitra
# SET internetarchive_install: True AND internetarchive_enabled: True WITHIN /etc/iiab/local_vars.yml
./iiab-install --reinstall
```

**Comment by mitra42** [comment]
Oh - good catch @holta - I'd used a intermediary branch "mitra" for the PR because of the challenge of working with all the different releases etc, I'll push to the "mitra" branch right now.

**Comment by mitra42** [comment]
Ok - looks like pushing to the "mitra" branch was sufficient - thanks @holta

**Comment by holta** [comment]
Smoke-tested on Ubuntu 19.04, where http://box:4244 loads!

@mitra42 can you write up a very basic usage guide https://github.com/mitra42/iiab/tree/mitra/roles/internetarchive/README.rst so folks can explore/understand/build on your work &mdash; similar to these other IIAB playbooks below?

https://github.com/iiab/iiab/blob/master/roles/calibre-web/README.rst
https://github.com/iiab/iiab/blob/master/roles/gitea/README.rst
https://github.com/iiab/iiab/blob/master/roles/kolibri/README.rst
https://github.com/iiab/iiab/blob/master/roles/lokole/README.rst
https://github.com/iiab/iiab/blob/master/roles/minetest/README.rst
https://github.com/iiab/iiab/blob/master/roles/mosquitto/README.rst
https://github.com/iiab/iiab/blob/master/roles/nodered/README.rst

**Comment by mitra42** [comment]
Yes - I can do this, as a separate PR or is it holding up this merge ?

**Comment by holta** [comment]
> Yes - I can do this, as a separate PR or is it holding up this merge ?

Please include roles/internetarchive/README.rst within this PR if possible!

**Comment by holta** [comment]
@mitra42 if you can include a couple lines in `roles/yarn/README.rst` explaining yarn's purpose vis-a-vis npm etc, even better.

(e.g. any suggestions as to how yarn's installation process might/ideally in future become mainlined i.e. installed via apt or otherwise?)

**Comment by mitra42** [comment]
Will do - I've updated and pushed an updated README to dweb-mirror, I need to edit it to remove the non-IIAB stuff, and more painfully convert from .md to .rst to copy it over to the iiab readme, I'll do the yarn one at the same time.

**Comment by holta** [comment]
> Will do - I've updated and pushed an updated README to dweb-mirror, I need to edit it to remove the non-IIAB stuff, and more painfully convert from .md to .rst to copy it over to the iiab readme, I'll do the yarn one at the same time.

Consider a recent version of `pandoc` to convert from .md to .rst ?

And if the automatic conversion is too ugly, submit both formats?

PS I'm not entirely sure why everyone's used .rst to date!

**Comment by mitra42** [comment]
Thanks for the `pandoc` pointer, I've copied README.md to the repo and auto-converted to .rst, I have no way to view or check the .rst (nothing on my Mac views these files, and converting back to PDF to test rather defeats the purpose of checking the .rst). Its probably worth leaving both in the repo since it will make it easier to track changes each time I update dweb-mirror/README.md and then edit to iiab/roles/internetarchive/README.md and auto-convert to iiab/roles/internetarchive/README.rst

**Comment by mitra42** [comment]
Is there anything else holding up the merge from your perspective.

**Comment by holta** [comment]
1) @m-anish can you look over Mitra's PR here in coming days, so we can merge it this week hopefully?

2) @mitra42 it looks like you used [pandoc](https://pandoc.org/) to convert the wrong README.md, creating this high-level README.rst for all of IIAB:
https://github.com/mitra42/iiab/blob/mitra/README.rst

   I'd go ahead and delete the above if you can.  My thinking is that the original https://github.com/mitra42/iiab/blob/mitra/README.md is indented/formatted far more readably, and should be sufficient.

3) In the case of your own README.md (https://github.com/mitra42/iiab/blob/mitra/roles/internetarchive/README.md) do please publish an .rst version for comparison!?  Which will be viewable as soon as you publish it here: https://github.com/mitra42/iiab/blob/mitra/roles/internetarchive/README.rst (GitHub renders it, so no need for any client-side viewing software!)

4) We still need to recruit someone to test this PR #1617 on Debian 9.9 (or better yet on a [pre-release of Debian 10](https://cdimage.debian.org/cdimage/daily-builds/daily/arch-latest/amd64/), whose final release is expected in [coming weeks](https://github.com/iiab/iiab/issues/1387#issuecomment-489424829) ?)  Anticipating that we'll hopefully find some Debian help, is it ok if I go ahead and [create the 3 modified files](https://github.com/iiab/iiab/pull/1617#issuecomment-487402079):
   - vars/local_vars_min.yml
   - vars/local_vars_medium.yml
   - vars/local_vars_big.yml

   ...in your https://github.com/mitra42/iiab/tree/mitra repo?
   ...or do you prefer I create a separate PR?

**Comment by holta** [comment]
@georgejhunt does https://github.com/mitra42/iiab/blob/mitra/roles/internetarchive/README.md answer some-or-all of the questions you had Thursday about how implementers/schools might use roles/internetarchive ?

**Comment by mitra42** [comment]
Sorry about the pandoc mistake - ran the tool in the wrong directory :-( Its fixed now (badly created one deleted and new one made). Thanks for catching it.  

Thanks also for a way to view it (on github)

Feel free to make the changes to `vars/local_vars_(min|medium|big).yml` directly in my repo, it appears your permissions on the iiab repo get cloned across, but let me know if I need to set them somehow. (I watch the repo with SourceTree so I'll see any changes).   Note that I added the variables in `vars/default_vars.yml`, I'm not sure whether you delete them there as you add them to `local_vars_(min|medium|big)`

Regarding use cases ... remember we are still working on this ... I'm adding UI to allow better selection of offline content (without editing the yaml) at the moment.

**Comment by mitra42** [comment]
One question ... it creates and uses a local config file in its home directory, On IIAB that is in `/root/dweb-mirror.config.yaml` it can't be in `/opt/iiab/internetarchive` as that will get overwritten by updates, and it shouldn't be in `/library/archiveorg`  because that has a specific format of one directory per item, and in a platform independent way I don't know whether the user will be using an external disk instead for content (e.g. in `/media/pi/*`). If there are strong objections to it being in /root I can move it, but its complex to do so in a platform independent way.

**Comment by holta** [comment]
@m-anish & @georgejhunt can you review and/or test this (on [Debian 10 Buster](https://github.com/iiab/iiab/issues/1387) ideally) so we can merge this week?

In particular, please do look over these two:
- https://github.com/mitra42/iiab/blob/mitra/roles/internetarchive/README.md
- https://github.com/mitra42/iiab/blob/mitra/roles/yarn/README.rst

**Comment by georgejhunt** [comment]
I pulled Mitra's branch into a test branch on debian9 vbox instance. It
installed. There was no menu on the home page.
http://box.local/internetarchive did not work and since my vbox instance
did not have a functioning wifi, http://box.lan makes no sense. But
http://<local
ip -- with instance in bridge mode>:4244 did work.

Concerning the README:
I'd like to see some mention where all the internetarchive data is stored.
Is there a way to get a list of what is cached, and the size of each.
Is there a way to delete an item?
If the crawl button is pushed. Is there a way to tell the background
process to stop filling the disk?
If the disk becomes full, from a crawl, what recovery methods are proposed?
Does a crawl restart after a reboot?

**Comment by mitra42** [comment]
@georgejhunt
There is no menu on the home page because 
a) I don’t know how to do it
b) reluctant to link to either http://box.lan:4244 or box.local:4244 from /internetarchive when we know that’s either is going to fail in 50% of the cases. I wish there was a way to  figure out a fix for that, but needs an Apache whizz.

There is a section on the README called Disks which covers where the data is stored and some of these other questions. 

There is *currently* no way to get a list of what is cached, size of each, or ability to delete items from the UI - that is under development at the moment (partly completed, but probably a few weeks from being in dweb-mirror, a month before its really usable and 2 months before has most of what you are asking for). 

Currently “Crawl” button just flags the item for crawling, crawl is only currently run from the command line, by the time there is a button to start it, there will be one to stop it and probably more controls because of the highly varied nature of use-cases (for example I don’t want to just run a crawl when connected to the net, as maybe connected via tethering on an expensive GSM link) but note crawls are cheap (in bandwidth terms) when only verifying, they are only expensive if there is new material to download.  Deleting any archived content is safe, (and documented in the README).

**Comment by holta** [comment]
> I pulled Mitra's branch into a test branch on debian9 vbox instance. It installed.

Great!

> There was no menu on the home page.

An Internet Archive logo (approx 300x300) & very short paragraph using non-technical language are needed ("teacherspeak not geekspeak") ...can you supply those @mitra42 ?

> http://box.local/internetarchive did not work and since my vbox instance did not have a functioning wifi, http://box.lan makes no sense. But http://<local ip -- with instance in bridge mode>:4244 did work.

Yes, http://box:4244 works for most others.

If http://box/internetarchive is too long to be a mnemonic, are there other recommendations?

> Concerning the README: I'd like to see some mention where all the internetarchive data is stored.

Definitely !

> - Is there a way to get a list of what is cached, and the size of each.
> - Is there a way to delete an item?
> - If the crawl button is [pushed, is] there a way to tell the background process to stop filling the disk?
> - If the disk becomes full, from a crawl, what recovery methods are proposed?
> - Does a crawl restart after a reboot?

Yes: documentation should outline manual / command-line techniques if web interface(s) are not yet ready to deal with the 5 situations/points above?  Some say 90% of the code in TV set-top DVR's is all about heuristics (and annoying GUI's !) to keep the disk from filing up...

**Comment by holta** [comment]
@mitra42 if possible prior to IIAB's weekly call Thursday 10AM NYC Time can you:

1) Beef up https://github.com/mitra42/iiab/blob/mitra/roles/internetarchive/README.md#disks explaining what each of these bits of the local storage areas are intended for &mdash; now and in future:
   - e.g. so far the README makes so mention of `/library/internetarchive`
   - Hint at the best crawling & disk-management strategies even if web interfaces are not yet possible?
2) A very short paragraph using non-technical language is needed for IIAB's offline home page.
3) Suggest a logo for Internet Archive, that will appear in less than 300x300 pixels when students/teachers visit IIAB's offline home page (http://box or equivalent).
4) Finally, can you offer any favorite "snackable" demo/content examples (cookie-cutter recipes to follow!?) for newbie teachers / newbie implementers, so they can make Internet Archive sample/demo content shine for their students using http://box:4244 ?

**Comment by mitra42** [comment]
For your comment before last (excepting things addressed in my last comment which crossed-in-the-post with yours): 

http://box:4244 might work (http://box gets rewritten to http://box.com but http://box:4244 might not get rewritten. I'll have to try it on my home LAN to see if it works to get to the RPI when on the same LAN via router. 

I'm fine if you want a link from http://..../internetarchive to http://box:4244/ it has to be a link, not a proxy as the rewritten URLs will fail if its a proxy (separate issue from the box|box.local|box.lan issue). 

1a: I've updated (and just pushed) the README ... disks section to make it clearer about /library/archiveorg etc 

1b: I don't want to write more about crawling than I've done as people unable to figure it out from `internetarchive --help` and the examples I've given are unlikely to figure out the command line at all - which is why I'm actively working on the crawl UI at the moment, and working with the relevant team at the archive on giving me some UI's on that system for organizing resources for this application, and because I'm working with anyone using this in person at the moment to figure out what they really want so the tools can reflect that. 

2: How about Paragraphs 2,3,4 of the README ...
```
The project is a local server that allows users to browse resources from the
Internet Archive stored on local drives - including USB drives.  
It includes a crawler that can regularly synchronize local collections, against
a list of Internet Archive items and collections, and those collections can be
moved between installations.
When connected to the internet, the server works as a Proxy, i.e. it will store
Internet Archive (IA) content the user views for later off-line viewing. 
```
3: There is a logo in the dweb-archive repo at https://github.com/internetarchive/dweb-archive/raw/master/images/archivelogo246x246.jpg that you can use, Its 246x246, you can grab it, or let me know where in the PR you would like it put (I couldnt find other logos to sit it alongside).

4: I don't have cookie-cutter recipes at present, I need some tools at the Archive end to make this usable for a teacher to collate resources, and the UI for crawling to be better - at this point is mostly of relevance to the people at a higher level - such as @m-anish and the 12 networks that Mike Jensen loaded this onto, whose feedback will get incorporated into the final system. 

I think i covered it all ...

**Comment by holta** [comment]
> http://box gets rewritten to http://box.com

Offline users don't experience this, as there's no DNS in an offline world (:

- Are your iPhones forcing you online, even after you've deleted 8.8.8.8?
- Can you remove their SIM cards for a more real-world offline test alongside testing http://box:4244 below?

> but http://box:4244 might not get rewritten. I'll have to try it on my home LAN to see if it works to get to the RPI when on the same LAN via router.
> 
> I'm fine if you want a link from http://..../internetarchive to http://box:4244/ it has to be a link, not a proxy as the rewritten URLs will fail if its a proxy (separate issue from the box|box.local|box.lan issue).
> 
> 1a: I've updated (and just pushed) the README ... disks section to make it clearer about /library/archiveorg etc

Thanks!

> 1b: I don't want to write more about crawling than I've done as people unable to figure it out from `internetarchive --help` and the examples I've given are unlikely to figure out the command line at all - which is why I'm actively working on the crawl UI at the moment, and working with the relevant team at the archive on giving me some UI's on that system for organizing resources for this application, and because I'm working with anyone using this in person at the moment to figure out what they really want so the tools can reflect that.

Ok

> 2: How about Paragraphs 2,3,4 of the README ...
> 
> ```
> The project is a local server that allows users to browse resources from the
> Internet Archive stored on local drives - including USB drives.  
> It includes a crawler that can regularly synchronize local collections, against
> a list of Internet Archive items and collections, and those collections can be
> moved between installations.
> When connected to the internet, the server works as a Proxy, i.e. it will store
> Internet Archive (IA) content the user views for later off-line viewing. 
> ```

Great Start: we'll probably shrink this further into 2-sentences-or-so, per IIAB norms (most students/teachers want 1 or 2-lines maximum!) while trying to simplify the language a bit more...for teachers/librarians in very low-income parts of the world...whose English is obviously different from ours.

> 3: There is a logo in the dweb-archive repo at https://github.com/internetarchive/dweb-archive/raw/master/images/archivelogo246x246.jpg that you can use, Its 246x246, you can grab it, or let me know where in the PR you would like it put (I couldnt find other logos to sit it alongside).

Perfect.  Even if this should be black-font-on-white-background (or transparent background) but we'll take it from here...

> 4: I don't have cookie-cutter recipes at present, I need some tools at the Archive end to make this usable for a teacher to collate resources, and the UI for crawling to be better - at this point is mostly of relevance to the people at a higher level - such as @m-anish and the 12 networks that Mike Jensen loaded this onto, whose feedback will get incorporated into the final system.

Demo materials are *highly persuasive* in low-resource / offline communities &mdash; keep eyes open for the best shiny examples to help drive adoption in future!

Meantime yes, strong reference docs will best catalyze community action among implementers at this point:
- any quick summary of what to directories/databases/settings to wipe, in order to do a fresh install?
- any suggestions for how upgrades might work in future?  (e.g. will the Ansible playbook [roles/internetarchive] possibly be updatable after installation, using a basic recipe such as...?)
```
cd /opt/iiab/iiab
git pull
./runrole internetarchive
```

**Comment by mitra42** [comment]
Re Box - this is really not the place for it, as its not specific to internetarchive, there are different open issues that relate to it.  In https://github.com/iiab/iiab/issues/1576 we identified three scenarios in which box.lan breaks (connected via router; 8.8.8.8 and SIM cards) any of which could occur in many of the settings in which this could get used - for example a) in @m-anish example I believe there is a 2G network which is likely to drive DNS even if its unusable for any volume of data; b) in several scenarios I'm talking to people thinking to add the PI next to the Router, in which case the router will often be doing local DNS (and not forwarding .lan presumably).  Also note that the one install test we had with MikeJ he hit precisely the problem of the standard IIAB install instructions not working, because he was following them and installing with the RPI connected to the ethernet and hit one of these three cases.  

I'm sort of giving up on trying to persuade you to fix this, since its holding up the merge of this patch, and the problem isn't specific to the internetarchive server, so feel free to go ahead and forward box/internetarchive to box.lan:4244 and we'll see how many more issues will have to get posted by installers/deployers before it gets fixed.

**Comment by mitra42** [comment]
Oh - and the statement about rewriting http://box to box.com doesn't apply offline is incorrect, even if I turn of Wifi so I have no network connection, http://box gets rewritten to http://box.com by firefox (as does http://sadsadsda get rewritten to http://sadsadsda.com (test it by turning off your wifi)

**Comment by mitra42** [comment]
Logo: Do you prefer black-on-white, if so I can get this, but it will be after your meeting as I'll need to ask someone at the office, and they've all gone home today long ago. 

Intro paragraph - feel free to rewrite how you want, and I will check its accurate. 

Demo materials - yes understood - will work on demos with the first few adopters that I handhold. 

Updating is covered in the README already. Its not via the role, its via yarn directly. 

Fresh install isn't covered, most of that is the stuff George put into the role, but you can delete /opt/iiab/internetarchive, /library/archiveorg, and /root/dweb-mirror.config.yaml to get rid of all my stuff. I'm loath to tell people to do this because the 2nd wipes out potentially a lot of content, and the latter wipes out any settings.

**Comment by holta** [comment]
> if I turn of Wifi so I have no network connection, http://box gets rewritten to http://box.com by firefox (as does http://sadsadsda get rewritten to http://sadsadsda.com (test it by turning off your wifi)

Why turn off WiFi when Firefox works with http://box over WiFi to connect to IIAB, as is used in schools around the world, precisely as they want it to work?

Certainly in every country where I've visited.

(Firefox forwards to http://sadsadsda.com only when it fails to find anything at http://sadsadsda &mdash; so while this is an interesting curiosity, dating from the Netscape days in the 1990s I believe, it does not materially affect IIAB communities.)

**Comment by holta** [comment]
> Logo: Do you prefer black-on-white, if so I can get this, but it will be after your meeting as I'll need to ask someone at the office, and they've all gone home today long ago.

Great if possible!  Any size is possible but preferably 200x200 or larger, and square is strongly preferred.

> Intro paragraph - feel free to rewrite how you want, and I will check its accurate.

Thx...will try to get this done well within the coming week.

> Demo materials - yes understood - will work on demos with the first few adopters that I handhold.

+1

> Updating is covered in the README already. Its not via the role, its via yarn directly.
> 
> Fresh install isn't covered, most of that is the stuff George put into the role, but you can delete /opt/iiab/internetarchive, /library/archiveorg, and /root/dweb-mirror.config.yaml to get rid of all my stuff. I'm loath to tell people to do this because the 2nd wipes out potentially a lot of content, and the latter wipes out any settings.

Ok!

**Comment by holta** [comment]
> a) in @m-anish example I believe there is a 2G network which is likely to drive DNS even if its unusable for any volume of data; b) in several scenarios I'm talking to people thinking to add the PI next to the Router, in which case the router will often be doing local DNS (and not forwarding .lan presumably)

Hybrid online/offline environments as hinted at above will grow in importance for sure.

So far http://box and http://box.lan (formerly http://schoolserver and http://schoolserver.lan) have worked perfectly well in offline environments over the past decade of IIAB's (formerly the OLPC School Server) use since 2007/2008.

So exclamations that "box.lan" isn't satisfactory don't really mean much, when a specific alternative proposal isn't articulated, explaining how exactly one can do better.

If however there are specific and concrete suggestions for techniques or TLD's beyond .lan and .local that would work better to abide by real-world and IETF standards anticipated for 2020-2030, those will certainly be considered.

**Comment by mitra42** [comment]
Adam, my point of turning off Wifi was to prove what happened when you don’t have access to DNS, to show that Firefox rewriting is independent of DNS and will be happening anywhere (and probably in other browsers as well) that assume a one-word name is short for xxx.com 

I don’t know the right solution fo box, box.lan, because I don’t know all your scenarios, all I know is that it failed for me in two different scenarios in different setups, and first person I had saw try and install it in their own situation (Mike J) also failed when they followed your instructions. 

For forwarding on the home page, I think it needs an apache whizz to figure out what the server that worked to access the home page was, to use it to forward. I know how to do this in express (on node) and in nginx , but you are using apache which I’m not up to date on, and the standard config file on apache doesn’t have access to that variable and you are using a setup with sites_enabled etc which doesnt seem to allow enabling the modules that allow access to that variable, as explained on the issue - I was hoping one of you might know apache well enough to figure it out as I tried and failed. 
. 
I suggest moving any further discussion on this back to https://github.com/iiab/iiab/issues/1576 since its just being rehashed here, at this point I don't have the energy to try and convince you that you've got a problem.

**Comment by mitra42** [comment]
Here's black-on-white 300px
ia-logo-pos-300x300

**Comment by holta** [comment]
Smoke-tested on Ubuntu 16.04 &mdash; recap from #1576:

- This needs more expansive testing on RPi 3 B+ now that it's merged, that everyone can now help with, if they select "BIG-sized" soon after they launch IIAB's 1-line installer at http://download.iiab.io

- It looks like there's a problem with Apache's [/etc/apache2/sites-available/internetarchive.conf](https://github.com/iiab/iiab/blob/master/roles/internetarchive/templates/internetarchive.conf) — http://IP-OR-BOX-NAME:4244 works but http://IP-OR-BOX-NAME/archive doesn't (yet!) work

**Comment by holta** [comment]
> Here's black-on-white 300px
> ia-logo-pos-300x300

Just FYI I'm going with https://upload.wikimedia.org/wikipedia/commons/8/84/Internet_Archive_logo_and_wordmark.svg which is about 99% smaller than the above JPG (8KB instead of 597KB) and does the job well.

PR evolving here, thanks to @tim-moody: https://github.com/iiab/iiab-admin-console/pull/205 -> https://github.com/iiab/iiab-admin-console/pull/207

**Pull request merged**
