### PR TITLE
atstart: auto-create /etc/iiab/uuid on cloned images

### PR DESCRIPTION
**Pull request by georgejhunt**
### Fixes Bug
This is an alternative to #271. I do not like generating a uuid only if openvpn is installed.
### Description of changes proposed in this pull request. I 
This creates a bash script that is run at every boot, which in turn looks for uuid, and generates it if it does not exist`
I think a uuid is strategic for determining how many people are contributing to "field back".
### Smoke-tested in operating system.
rpi stretch (but not a fresh install)

### CODE REVIEW

**Comment by holta** [comment]
Ref #229

**Comment by holta** [comment]
CLARIF!  During our Thur Nov 23 community/team call (http://minutes.iiab.io) we delayed uuid issues to [IIAB 6.6](https://github.com/iiab/iiab/milestone/2).

(As appropriate we can reverse this decision in coming days, if a consensus/compromise emerges and there's time to get this into IIAB 6.5?)

**Comment by georgejhunt** [comment]
delay to 6.6 seems appropriate

**Comment by holta** [comment]
> delay to 6.6 seems appropriate

Or maybe not.  If an agreed-upon & tested solution is available this week?!

Context: Tim has made enormous progress supporting Admin Console downloading of new ZIM files (that contain an internal index) into a local catalog that sorts out new & old &mdash; and also ZIM files that do not contain an index at all.

Also Calibre (etc!) have made massive improvements in recent days &mdash; _so it makes sense to delay IIAB 6.5's release a bit &mdash; such that Every Kid Worldwide gets one in their stocking ;)_

**Comment by holta** [comment]
Monday during our call let's also talk over quickly:

* Community Analytics Purpose (moving in which directions, in consideration of kiwix/kiwix-tools#96 ?)
* Privacy-by-Design action plan ([GDPR](https://en.wikipedia.org/wiki/General_Data_Protection_Regulation) offers thoughtful principles!)

**Pull request merged**
