### PR TITLE
Moodle 3.1 -> 3.5 LTS TESTING (on Moodle's master branch for now)

### PR DESCRIPTION
**Pull request by holta**
Ref
#627 Moodle 3.1 -> 3.5 LTS - ETA May 14th 2018
#759 Moodle 3.1.11 LTS impossible on Ubuntu 18.04? (due to php7.2, even w/ encrypted password)

### CODE REVIEW

**Comment by holta** [comment]
`./runrole moodle` completes installing Moodle's master (after Moodle startup script runs for many minutes) resulting in:

> $release  = '3.5beta+ (Build: 20180427)'

...as shown in /opt/iiab/moodle/version.php

BUT: attempting to login to http://box.lan/moodle with Admin/changeme shows "Invalid login, please try again"

**Comment by holta** [comment]
This time Admin/changeme *worked* to log into http://box.lan/moodle apparently as a result of `--adminuser=admin` bring restored to lowercase (regardless of my deleting /library/moodle ?)

FYI `./runrole moodle` takes about 10min even on a recent PC, as a result of this moodle_installer (which in turn runs /opt/iiab/moodle/admin/cli/install.php, what's running for most of these ~10min).

**Comment by holta** [comment]
@martignoni & @georgejhunt please if you can review this patch, in light of https://github.com/moodlebox/moodlebox/blob/master/roles/moodle/tasks/coreinstall.yml

_While this PR #768 has been smoke-tested on Ubuntu 18.04 LTS (Desktop edition) and the latest Raspbian Lite, it could use improvement towards making it more future-proof, in keeping with Moodle's best practices, Thanks!_

**Comment by holta** [comment]
CLARIF: on/around Monday 2018-05-14 when Moodle 3.5 LTS is released, line 47 of roles/moodle/tasks/main.yml (`version: master`) should be commented out in favor of the original:
```
version: "MOODLE_{{ moodle_version }}_STABLE"
```

**Comment by holta** [comment]
CLARIF 2: in between each test, I ran the following so as to have a clean slate prior to installing Moodle:
```
rm -rf /opt/iiab/moodle /library/moodle
dropdb -U postgres moodle (...or "/usr/lib/postgresql/10/bin/dropdb -U postgres moodle")
```
Also useful is the command `psql -U postgres postgres` followed by `\l` (similar to `mysql -u root` followed by `SHOW DATABASES;`) ...and then of course `\q` to quit.

**Review by martignoni — APPROVED** [review]
Good. Seems OK to me.

**Comment by holta** [comment]
> CLARIF: on/around Monday 2018-05-14 when Moodle 3.5 LTS is released, line 47 of roles/moodle/tasks/main.yml (`version: master`) should be commented out in favor of the original:
> ```
> version: "MOODLE_{{ moodle_version }}_STABLE"
> ```

Further improvements incredibly welcome now that this is merged — as we approach IIAB 6.5's Final Release.

**Pull request merged**
