### PR TITLE
PSA2: refactoring for Travis, readability & networking

### PR DESCRIPTION
**Pull request by jvonau**
### Fixes Bug
working on travis warning, don't force kernel upgrade on is_redhat, condense fl.yml to one call
### Description of changes proposed in this pull request.
switch away from lineinfile for STAGE recording, removes unused files, allows for IIAB_RELEASE IIAB_REVISION to be source from /etc/iiab/iiab.env for smarter upgrading in the future.
### Smoke-tested in operating system.
basic structure tested in PSA branch when in jenkins

### CODE REVIEW

**Comment by jvonau** [comment]
HOLD for jenkins testing

**Comment by holta** [comment]
On the topic of PSA's: (public service announcements, i.e. wake-up calls for installers/implementer drowning in the wrong prereqs!)

#498 "experimental ./iiab-install blocks older/stale kernels, using version_gt()" includes 1-line subroutine version_gt() the verify version number of any software: (ensuring it's greater than w.x.y.z or whatev)
```
function version_gt() { [ "$(printf '%s\n' "$@" | sort -V | head -1)" != "$1" ]; }
```
#457 "scripts/ansible does not upgrade or issue any message"

**Comment by holta** [comment]
24 files reviewed extensively during our live community/team call (http://minutes.iiab.io).  @jvonau will carve off the best ideas into individual PR's when he has time!

Personally I find the following 3 things confusing &mdash; but documentation can hopefully mitigate this &mdash; so I'm writing this up here to get the ball rolling, making these mechanics a bit more clear:
* [Stages 1 to 8 use each of their tasks/main.yml's](https://github.com/jvonau/iiab/tree/PSA2/roles) to set `STAGE: <stage that is about to complete>` at the top of the file, but then encode that onto the filesystem at the bottom of the file, using:
```
  template:
           src: roles/1-prep/templates/iiab.stage.j2
           dest: /etc/iiab/iiab.env
           owner: root
           group: root
           mode: 0644
```
* [Stage 9's tasks/main.yml](https://github.com/jvonau/iiab/blob/PSA2/roles/9-local-addons/tasks/main.yml ) does much more (using a different template roles/1-prep/templates/iiab.env.j2, that has 8 functional lines instead of 6) to encode the following 2 into the filesystem as well:
```
IIAB_RELEASE={{ iiab_base_ver }}
IIAB_REVISION={{ iiab_revision }}
```
* These 2 variables are originally set by [roles/0-init/defaults/main.yml](https://github.com/jvonau/iiab/blob/PSA2/roles/0-init/defaults/main.yml) here:
```
# use these as a tag a release at a point in time
iiab_base_ver: 6.4    [change to "6.5" soon!]
iiab_revision: 0    [change to "Preview 3" soon?]
```

**Comment by holta** [comment]
@jvonau can we move this ticket (some or all of it) to [IIAB 6.6](https://github.com/iiab/iiab/milestone/3) ?

**Pull request closed without merging**
