### PR TITLE
Nextcloud 21 recommends php{{ php_version }}-bcmath

### PR DESCRIPTION
**Pull request by holta**
As recommended in the "Security & setup warnings" shown when visiting from http://box/nextcloud > Settings (top-right) > Overview:

> There are some errors regarding your setup.
The PHP memory limit is below the recommended value of 512MB.
You are accessing your instance over a secure connection, however your instance is generating insecure URLs. This most likely means that you are behind a reverse proxy and the overwrite config variables are not set correctly. Please read [the documentation page about this](https://docs.nextcloud.com/server/21/go.php?to=admin-reverse-proxy).
Accessing site insecurely via HTTP. You are strongly advised to set up your server to require HTTPS instead, as described in the [security tips ↗](https://docs.nextcloud.com/server/21/go.php?to=admin-security).
Your web server is not properly set up to resolve "/.well-known/webfinger". Further information can be found in the [documentation](https://docs.nextcloud.com/server/21/go.php?to=admin-setup-well-known-URL).
Your web server is not properly set up to resolve "/.well-known/nodeinfo". Further information can be found in the [documentation](https://docs.nextcloud.com/server/21/go.php?to=admin-setup-well-known-URL).
Your web server is not properly set up to resolve "/.well-known/caldav". Further information can be found in the [documentation](https://docs.nextcloud.com/server/21/go.php?to=admin-setup-well-known-URL).
Your web server is not properly set up to resolve "/.well-known/carddav". Further information can be found in the [documentation](https://docs.nextcloud.com/server/21/go.php?to=admin-setup-well-known-URL).
Your installation has no default phone region set. This is required to validate phone numbers in the profile settings without a country code. To allow numbers without a country code, please add "default_phone_region" with the respective [ISO 3166-1 code ↗](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#Officially_assigned_code_elements) of the region to your config file.
No memory cache has been configured. To enhance performance, please configure a memcache, if available. Further information can be found in the [documentation](https://docs.nextcloud.com/server/21/go.php?to=admin-performance).
This instance is missing some recommended PHP modules. For improved performance and better compatibility it is highly recommended to install them.
bcmath
The "Referrer-Policy" HTTP header is not set to "no-referrer", "no-referrer-when-downgrade", "strict-origin", "strict-origin-when-cross-origin" or "same-origin". This can leak referer information. See the [W3C Recommendation ↗](https://www.w3.org/TR/referrer-policy/).
Please double check the [installation guides ↗](https://docs.nextcloud.com/server/21/go.php?to=admin-install), and check for any errors or warnings in the log.
>
> Check the security of your Nextcloud over our [security scan ↗](https://scan.nextcloud.com/).

Ref: PR #2683

### CODE REVIEW

**Comment by holta** [comment]
FYI this PR was tested on Raspberry Pi OS 2021-01-11 apt updated with kernel 5.10 LTS on RPi 4.

**Comment by holta** [comment]
FYI Nextcloud 23.0.0 (whose release process is right now underway) thankfully has the same official PHP requirements as Nextloud 21:

https://docs.nextcloud.com/server/23/admin_manual/installation/source_installation.html

**Comment by jvonau** [comment]
Have you resolved the "Your web server is not properly set up to resolve" issues noted above?

**Comment by holta** [comment]
> Have you resolved the "Your web server is not properly set up to resolve" issues noted above?

There are no more red warnings!

There is just 1 orange warning.

And the usual litany of black warnings.

Screenshot_20211216-071549

**Comment by holta** [comment]
Of course the legalese / smallprint is getting longer — here's yet another screen-full:

Screenshot_20211216-072414

Tangentially Related:

- #3069

**Pull request merged**
