### PR TITLE
drop netifaces workaround - replaced with netifaces-plus

### PR DESCRIPTION
**Pull request by jvonau**
### Fixes bug:
just keeping up with changes to requirements,txt upstream  
### Description of changes proposed in this pull request:
drop workaround for failure to compile package
### Smoke-tested on which OS or OS's:
24.04 vm installs clean but no functional testing preformed.

### CODE REVIEW

**Comment by holta** [comment]
@deldesir can you review by testing this on Raspberry Pi OS?

(And on a Debian 12 and Debian 13 and Ubuntu 25.04 VMs too, to be safe!)

**Comment by deldesir** [comment]
Yep, doing it right now...

**Comment by deldesir** [comment]
Functional testing on RPI 5 with Raspberry Pi OS Lite (64 bit) went successfully
 https://paste.centos.org/view/2d459b86

**Comment by holta** [comment]
@deldesir please can you test on 3 VMs {bmdeb12, bmdeb13b, bm2504c} that are currently being created?

**Comment by holta** [comment]
> @deldesir please can you test on 3 VMs {bmdeb12, bmdeb13b, bm2504c} that are currently being created?

Tested on various OS's with the help of @deldesir, in combination with these 2 other PR's:

- PR #3862
- PR #3864

**Comment by holta** [comment]
Thank you to everyone, including @OzzieIsaacs (upstream!) who clarified that python3-netifaces is no longer needed here:

https://github.com/janeczku/calibre-web/wiki/Manual-Installation/_compare/918ae3cb2172c8c72598ad5f7cfcc592c3e88c41...0542e8d36c3a9d258449a86559069c5e422310d5

**Pull request merged**
