### PR TITLE
Install 'make' package only when nec e.g. roles/pbx

### PR DESCRIPTION
**Pull request by holta**
@lemueldsouza this is just an interim/small step forward suggestion, as IIAB was declaring far too many 'pollution' packages across the board, that many schools/clinics will never need.

Refs:

- PR #2862
- #2875 
- PR #2877 
- PR #2878

### CODE REVIEW

**Comment by tim-moody** [comment]
roles such as pbx should do any build outside of IIAB and remove dependency on make. having a build as part of install unnecessarily uses time and storage

**Comment by holta** [comment]
> roles such as pbx should do any build outside of IIAB and remove dependency on make. having a build as part of install unnecessarily uses time and storage

I wholeheartedly agree with the sentiment.

At the same time it's possible this is a special case, where we should respect @m-anish's extremely hard work putting this together 2+ years ago, that @jvonau and others have put some hard work into maintaining.  Especially in light of the fact that compiling for every CPU/OS and regularly-changing FreePBX upstream code arrangement would be a herculean task if not impossible in this case :/

**Comment by holta** [comment]
FYI this PR was tested on Ubuntu Server 20.04 LTS VM 10.8.0.58 and generally looks good.

However it FreePBX doesn't compile on this particular OS for other/known reasons?  Trace pasted in here:

> 2021-07-27 09:47:04,757 p=171649 u=root n=ansible | TASK [pbx : FreePBX - Install (just run once) - CAN TAKE 12 MIN OR LONGER!] ****
2021-07-27 09:47:30,785 p=171649 u=root n=ansible | fatal: [127.0.0.1]: FAILED! => {"changed": true, "cmd": ["./install", "-n", "--webroot", "/var/www/html/freepbx", "--dbuser", "asterisk", "--dbpass", "asterisk", "--dbname", "asterisk", "--cdrdbname", "asteriskcdrdb"], "delta": "0:00:25.716950", "end": "2021-07-27 09:47:30.736926", "msg": "non-zero return code", "rc": 1, "start": "2021-07-27 09:47:05.019976", "stderr": "    0/9395 [>---------------------------]   0%\n  100/9395 [>---------------------------]   1%\n  200/9395 [>---------------------------]   2%\n  300/9395 [>---------------------------]   3%\n  400/9395 [=>--------------------------]   4%\n  500/9395 [=>--------------------------]   5%\n  600/9395 [=>--------------------------]   6%\n  700/9395 [==>-------------------------]   7%\n  800/9395 [==>-------------------------]   8%\n  900/9395 [==>-------------------------]   9%\n 1000/9395 [==>-------------------------]  10%\n 1100/9395 [===>------------------------]  11%\n 1200/9395 [===>------------------------]  12%\n 1300/9395 [===>------------------------]  13%\n 1400/9395 [====>-----------------------]  14%\n 1500/9395 [====>-----------------------]  15%\n 1600/9395 [====>-----------------------]  17%\n 1700/9395 [=====>----------------------]  18%\n 1800/9395 [=====>----------------------]  19%\n 1900/9395 [=====>----------------------]  20%\n 2000/9395 [=====>----------------------]  21%\n 2100/9395 [======>---------------------]  22%\n 2200/9395 [======>---------------------]  23%\n 2300/9395 [======>---------------------]  24%\n 2400/9395 [=======>--------------------]  25%\n 2500/9395 [=======>--------------------]  26%\n 2600/9395 [=======>--------------------]  27%\n 2700/9395 [========>-------------------]  28%\n 2800/9395 [========>-------------------]  29%\n 2900/9395 [========>-------------------]  30%\n 3000/9395 [========>-------------------]  31%\n 3100/9395 [=========>------------------]  32%\n 3200/9395 [=========>------------------]  34%\n 3300/9395 [=========>------------------]  35%\n 3400/9395 [==========>-----------------]  36%\n 3500/9395 [==========>-----------------]  37%\n 3600/9395 [==========>-----------------]  38%\n 3700/9395 [===========>----------------]  39%\n 3800/9395 [===========>----------------]  40%\n 3900/9395 [===========>----------------]  41%\n 4000/9395 [===========>----------------]  42%\n 4100/9395 [============>---------------]  43%\n 4200/9395 [============>---------------]  44%\n 4300/9395 [============>---------------]  45%\n 4400/9395 [=============>--------------]  46%\n 4500/9395 [=============>--------------]  47%\n 4600/9395 [=============>--------------]  48%\n 4700/9395 [==============>-------------]  50%\n 4800/9395 [==============>-------------]  51%\n 4900/9395 [==============>-------------]  52%\n 5000/9395 [==============>-------------]  53%\n 5100/9395 [===============>------------]  54%\n 5200/9395 [===============>------------]  55%\n 5300/9395 [===============>------------]  56%\n 5400/9395 [================>-----------]  57%\n 5500/9395 [================>-----------]  58%\n 5600/9395 [================>-----------]  59%\n 5700/9395 [================>-----------]  60%\n 5800/9395 [=================>----------]  61%\n 5900/9395 [=================>----------]  62%\n 6000/9395 [=================>----------]  63%\n 6100/9395 [==================>---------]  64%\n 6200/9395 [==================>---------]  65%\n 6300/9395 [==================>---------]  67%\n 6400/9395 [===================>--------]  68%\n 6500/9395 [===================>--------]  69%\n 6600/9395 [===================>--------]  70%\n 6700/9395 [===================>--------]  71%\n 6800/9395 [====================>-------]  72%\n 6900/9395 [====================>-------]  73%\n 7000/9395 [====================>-------]  74%\n 7100/9395 [=====================>------]  75%\n 7200/9395 [=====================>------]  76%\n 7300/9395 [=====================>------]  77%\n 7400/9395 [======================>-----]  78%\n 7500/9395 [======================>-----]  79%\n 7600/9395 [======================>-----]  80%\n 7700/9395 [======================>-----]  81%\n 7800/9395 [=======================>----]  83%\n 7900/9395 [=======================>----]  84%\n 8000/9395 [=======================>----]  85%\n 8100/9395 [========================>---]  86%\n 8200/9395 [========================>---]  87%\n 8300/9395 [========================>---]  88%\n 8400/9395 [=========================>--]  89%\n 8500/9395 [=========================>--]  90%\n 8600/9395 [=========================>--]  91%\n 8700/9395 [=========================>--]  92%\n 8800/9395 [==========================>-]  93%\n 8900/9395 [==========================>-]  94%\n 9000/9395 [==========================>-]  95%\n 9100/9395 [===========================>]  96%\n 9200/9395 [===========================>]  97%\n 9300/9395 [===========================>]  98%\n 9395/9395 [============================] 100%    0 [>---------------------------]\nIn Process.php line 239:\n                                                                               \n  The command \"/usr/sbin/fwconsole ma install core dashboard sipsettings voic  \n  email\" failed.                                                               \n                                                                               \n  Exit Code: 1(General error)                                                  \n                                                                               \n  Working directory: /opt/iiab/freepbx                                         \n                                                                               \n  Output:                                                                      \n  ================                                                             \n                                                                               \n                                                                               \n  Error Output:                                                                \n  ================                                                             \n                                                                               \n\ninstall [--dbengine DBENGINE] [--dbname DBNAME] [--dbhost DBHOST] [--dbport DBPORT] [--cdrdbname CDRDBNAME] [--dbuser DBUSER] [--dbpass DBPASS] [--user USER] [--group GROUP] [--dev-links] [--skip-install] [--webroot WEBROOT] [--astetcdir ASTETCDIR] [--astmoddir ASTMODDIR] [--astvarlibdir ASTVARLIBDIR] [--astagidir ASTAGIDIR] [--astspooldir ASTSPOOLDIR] [--astrundir ASTRUNDIR] [--astlogdir ASTLOGDIR] [--ampbin AMPBIN] [--ampsbin AMPSBIN] [--ampcgibin AMPCGIBIN] [--ampplayback AMPPLAYBACK] [-r|--rootdb] [-f|--force]", "stderr_lines": ["    0/9395 [>---------------------------]   0%", "  100/9395 [>---------------------------]   1%", "  200/9395 [>---------------------------]   2%", "  300/9395 [>---------------------------]   3%", "  400/9395 [=>--------------------------]   4%", "  500/9395 [=>--------------------------]   5%", "  600/9395 [=>--------------------------]   6%", "  700/9395 [==>-------------------------]   7%", "  800/9395 [==>-------------------------]   8%", "  900/9395 [==>-------------------------]   9%", " 1000/9395 [==>-------------------------]  10%", " 1100/9395 [===>------------------------]  11%", " 1200/9395 [===>------------------------]  12%", " 1300/9395 [===>------------------------]  13%", " 1400/9395 [====>-----------------------]  14%", " 1500/9395 [====>-----------------------]  15%", " 1600/9395 [====>-----------------------]  17%", " 1700/9395 [=====>----------------------]  18%", " 1800/9395 [=====>----------------------]  19%", " 1900/9395 [=====>----------------------]  20%", " 2000/9395 [=====>----------------------]  21%", " 2100/9395 [======>---------------------]  22%", " 2200/9395 [======>---------------------]  23%", " 2300/9395 [======>---------------------]  24%", " 2400/9395 [=======>--------------------]  25%", " 2500/9395 [=======>--------------------]  26%", " 2600/9395 [=======>--------------------]  27%", " 2700/9395 [========>-------------------]  28%", " 2800/9395 [========>-------------------]  29%", " 2900/9395 [========>-------------------]  30%", " 3000/9395 [========>-------------------]  31%", " 3100/9395 [=========>------------------]  32%", " 3200/9395 [=========>------------------]  34%", " 3300/9395 [=========>------------------]  35%", " 3400/9395 [==========>-----------------]  36%", " 3500/9395 [==========>-----------------]  37%", " 3600/9395 [==========>-----------------]  38%", " 3700/9395 [===========>----------------]  39%", " 3800/9395 [===========>----------------]  40%", " 3900/9395 [===========>----------------]  41%", " 4000/9395 [===========>----------------]  42%", " 4100/9395 [============>---------------]  43%", " 4200/9395 [============>---------------]  44%", " 4300/9395 [============>---------------]  45%", " 4400/9395 [=============>--------------]  46%", " 4500/9395 [=============>--------------]  47%", " 4600/9395 [=============>--------------]  48%", " 4700/9395 [==============>-------------]  50%", " 4800/9395 [==============>-------------]  51%", " 4900/9395 [==============>-------------]  52%", " 5000/9395 [==============>-------------]  53%", " 5100/9395 [===============>------------]  54%", " 5200/9395 [===============>------------]  55%", " 5300/9395 [===============>------------]  56%", " 5400/9395 [================>-----------]  57%", " 5500/9395 [================>-----------]  58%", " 5600/9395 [================>-----------]  59%", " 5700/9395 [================>-----------]  60%", " 5800/9395 [=================>----------]  61%", " 5900/9395 [=================>----------]  62%", " 6000/9395 [=================>----------]  63%", " 6100/9395 [==================>---------]  64%", " 6200/9395 [==================>---------]  65%", " 6300/9395 [==================>---------]  67%", " 6400/9395 [===================>--------]  68%", " 6500/9395 [===================>--------]  69%", " 6600/9395 [===================>--------]  70%", " 6700/9395 [===================>--------]  71%", " 6800/9395 [====================>-------]  72%", " 6900/9395 [====================>-------]  73%", " 7000/9395 [====================>-------]  74%", " 7100/9395 [=====================>------]  75%", " 7200/9395 [=====================>------]  76%", " 7300/9395 [=====================>------]  77%", " 7400/9395 [======================>-----]  78%", " 7500/9395 [======================>-----]  79%", " 7600/9395 [======================>-----]  80%", " 7700/9395 [======================>-----]  81%", " 7800/9395 [=======================>----]  83%", " 7900/9395 [=======================>----]  84%", " 8000/9395 [=======================>----]  85%", " 8100/9395 [========================>---]  86%", " 8200/9395 [========================>---]  87%", " 8300/9395 [========================>---]  88%", " 8400/9395 [=========================>--]  89%", " 8500/9395 [=========================>--]  90%", " 8600/9395 [=========================>--]  91%", " 8700/9395 [=========================>--]  92%", " 8800/9395 [==========================>-]  93%", " 8900/9395 [==========================>-]  94%", " 9000/9395 [==========================>-]  95%", " 9100/9395 [===========================>]  96%", " 9200/9395 [===========================>]  97%", " 9300/9395 [===========================>]  98%", " 9395/9395 [============================] 100%    0 [>---------------------------]", "In Process.php line 239:", "                                                                               ", "  The command \"/usr/sbin/fwconsole ma install core dashboard sipsettings voic  ", "  email\" failed.                                                               ", "                                                                               ", "  Exit Code: 1(General error)                                                  ", "                                                                               ", "  Working directory: /opt/iiab/freepbx                                         ", "                                                                               ", "  Output:                                                                      ", "  ================                                                             ", "                                                                               ", "                                                                               ", "  Error Output:                                                                ", "  ================                                                             ", "                                                                               ", "", "install [--dbengine DBENGINE] [--dbname DBNAME] [--dbhost DBHOST] [--dbport DBPORT] [--cdrdbname CDRDBNAME] [--dbuser DBUSER] [--dbpass DBPASS] [--user USER] [--group GROUP] [--dev-links] [--skip-install] [--webroot WEBROOT] [--astetcdir ASTETCDIR] [--astmoddir ASTMODDIR] [--astvarlibdir ASTVARLIBDIR] [--astagidir ASTAGIDIR] [--astspooldir ASTSPOOLDIR] [--astrundir ASTRUNDIR] [--astlogdir ASTLOGDIR] [--ampbin AMPBIN] [--ampsbin AMPSBIN] [--ampcgibin AMPCGIBIN] [--ampplayback AMPPLAYBACK] [-r|--rootdb] [-f|--force]"], "stdout": "Checking if SELinux is enabled...Its not (good)!\nReading /etc/asterisk/asterisk.conf...Done\nChecking if Asterisk is running and we can talk to it as the 'asterisk' user...Yes. Determined Asterisk version to be: 16.19.1\nChecking if NodeJS is installed and we can get a version from it...Yes. Determined NodeJS version to be: 16.5.0\nPreliminary checks done. Starting FreePBX Installation\nChecking if this is a new install...Yes (No /etc/freepbx.conf file detected)\nDatabase installation checking credentials and permissions..Connected!\nBlank /etc/odbc.ini file detected. Installing...Done\nEmpty asterisk Database going to populate it\nUpdating tables admin, ampusers, cronmanager, featurecodes, freepbx_log, freepbx_settings, globals, module_xml, modules, notifications, cron_jobs...Done\nEmpty asteriskcdrdb Database going to populate it\nInitializing FreePBX Settings\n\tChanging AMPWEBROOT [/var/www/html] to match what was given at install time: /var/www/html/freepbx\n\tChanging AMPMGRPASS [amp111] to match what was given at install time: c51cd6e9b468b06bed8af525cab717ba\nFinished initalizing settings\nCopying files (this may take a bit)....\n\nDone\nbin is: /var/lib/asterisk/bin\nsbin is: /usr/sbin\nSymlinking /var/lib/asterisk/bin/fwconsole to /usr/sbin/fwconsole ...Done\nSymlinking /var/lib/asterisk/bin/amportal to /usr/sbin/amportal ...Done\nFinishing up directory processes...Done!\nRunning variable replacement...Done\nCreating missing #include files...Done\nSetting up Asterisk Manager Connection...Done\nRunning through upgrades...\nChecking for upgrades..\nNo further upgrades necessary\nFinished upgrades\nSetting FreePBX version to 15.0.17.37...Done\nWriting out /etc/amportal.conf...Done\nWriting out /etc/freepbx.conf...Done\nChowning directories...\nSetting Permissions...\nSetting base permissions...Done in 0 seconds\nSetting specific permissions...\n\nFinished setting permissions\nDone\nInstalling framework...\nDone\nBuilding Packaged Scripts...Done\nTrusting FreePBX...Trusted\nInstalling base modules...", "stdout_lines": ["Checking if SELinux is enabled...Its not (good)!", "Reading /etc/asterisk/asterisk.conf...Done", "Checking if Asterisk is running and we can talk to it as the 'asterisk' user...Yes. Determined Asterisk version to be: 16.19.1", "Checking if NodeJS is installed and we can get a version from it...Yes. Determined NodeJS version to be: 16.5.0", "Preliminary checks done. Starting FreePBX Installation", "Checking if this is a new install...Yes (No /etc/freepbx.conf file detected)", "Database installation checking credentials and permissions..Connected!", "Blank /etc/odbc.ini file detected. Installing...Done", "Empty asterisk Database going to populate it", "Updating tables admin, ampusers, cronmanager, featurecodes, freepbx_log, freepbx_settings, globals, module_xml, modules, notifications, cron_jobs...Done", "Empty asteriskcdrdb Database going to populate it", "Initializing FreePBX Settings", "\tChanging AMPWEBROOT [/var/www/html] to match what was given at install time: /var/www/html/freepbx", "\tChanging AMPMGRPASS [amp111] to match what was given at install time: c51cd6e9b468b06bed8af525cab717ba", "Finished initalizing settings", "Copying files (this may take a bit)....", "", "Done", "bin is: /var/lib/asterisk/bin", "sbin is: /usr/sbin", "Symlinking /var/lib/asterisk/bin/fwconsole to /usr/sbin/fwconsole ...Done", "Symlinking /var/lib/asterisk/bin/amportal to /usr/sbin/amportal ...Done", "Finishing up directory processes...Done!", "Running variable replacement...Done", "Creating missing #include files...Done", "Setting up Asterisk Manager Connection...Done", "Running through upgrades...", "Checking for upgrades..", "No further upgrades necessary", "Finished upgrades", "Setting FreePBX version to 15.0.17.37...Done", "Writing out /etc/amportal.conf...Done", "Writing out /etc/freepbx.conf...Done", "Chowning directories...", "Setting Permissions...", "Setting base permissions...Done in 0 seconds", "Setting specific permissions...", "", "Finished setting permissions", "Done", "Installing framework...", "Done", "Building Packaged Scripts...Done", "Trusting FreePBX...Trusted", "Installing base modules..."]}
2021-07-27 09:47:30,788 p=171649 u=root n=ansible | PLAY RECAP *********************************************************************
2021-07-27 09:47:30,789 p=171649 u=root n=ansible | 127.0.0.1                  : ok=104  changed=46   unreachable=0    failed=1    skipped=15   rescued=0    ignored=0

**Comment by jvonau** [comment]
The installation of 'make' has it roots in the olpc based layout from 10 years ago, not sure what other roles might be using 'make' without knowing it, ie hidden within some other script that might be involved.

**Comment by holta** [comment]
> The installation of 'make' has it roots in the olpc based layout from 10 years ago, not sure what other roles might be using 'make' without knowing it, ie hidden within some other script that might be involved.

I checked pretty carefully with 'grep -r' using several regexp patterns that should flag all uses of `make`.

roles/pbx seems to be the only one left still using `make`.

And absolute worst case, this PR will serve to surface any stragglers...

**Comment by holta** [comment]
FWIW there are other package(s) that install apt package `make` &mdash; very early on in IIAB's install process &mdash; it seems this is arising from one-or-more of the `python3-*` (or virtualenv) packages being installed here:

```
$APT_PATH/apt -y install \
              python3-pymysql python3-psycopg2 python3-passlib python3-pip \
              python3-setuptools python3-packaging python3-venv virtualenv
```

https://github.com/iiab/iiab/blob/master/scripts/ansible#L156-L158

**Comment by jvonau** [comment]
build-essential drags in make... python3-pip Recommends build-essential... you are compiling wheels when you use pip... apt distributes compiled wheels dropping the need to install and compile yourself... Really should not leave compilers installed on a production server out on the web but that is just me.

**Comment by holta** [comment]
Agreed: this list of packages should be tailored to specific needs in future.  In any case, we can better explain the purpose of each of these 8 packages at some point (when there is time to verify these!)

One possible example: some claim `virtualenv` is no longer necessary, as a result of `python3-venv`.

**Comment by jvonau** [comment]
> > roles such as pbx should do any build outside of IIAB and remove dependency on make. having a build as part of install unnecessarily uses time and storage
> 
> I wholeheartedly agree with the sentiment.

Then all nodejs based apps need to be reviewed, all of them are compiled.

**Comment by jvonau** [comment]
> One possible example: some claim `virtualenv` is no longer necessary, as a result of `python3-venv`.

Go ahead, remove it, watch kalite not be able to install its python2 virtual environment but you can 'fix' what is not broken.

**Comment by holta** [comment]
> > One possible example: some claim `virtualenv` is no longer necessary, as a result of `python3-venv`.

> remove it, watch kalite not be able to install its python2 virtual environment

This is good information.

The install of package `virtualenv` should probably be localized to [roles/kalite](https://github.com/iiab/iiab/tree/master/roles/kalite) for those who truly need this Python 2 legacy stuff.

**Comment by jvonau** [comment]
The 'virtualenv' name is provided by 'python-virtualenv' package which is actually python3 but provides the virtual package 'virtualenv'. The difference is virtualenv takes the python version as an argument while the 'python3-venv' name was once an add-on to python3 but now is build-in and 'provides' the name python3-venv has only ever handled python3.

**Pull request merged**
