### PR TITLE
testing changes for CentOS testing

### PR DESCRIPTION
**Pull request by jvonau**
backport from a different branch - should fixup reported centos error - for 6.4

### CODE REVIEW

**Comment by holta** [comment]
Ref #314 ("Setting ifcfg-WAN True" fails on CentOS)

**Comment by jvonau** [comment]
Lightly tested on hadron://job/IIAB-debian-jvonau/19/consoleText

**Comment by holta** [comment]
@jvonau @georgejhunt is this appropriate and very-low-risk for IIAB 6.4 despite it needing rebasing?

Or better to defer to IIAB 6.5?

**Comment by holta** [comment]
@jvonau is this PR important for consideration Monday?

**Pull request merged**
