### PR TITLE
Check transmission_kalite_languages is undefined

### PR DESCRIPTION
**Pull request by arky**
Check if transmission_kalite_languages is defined.

https://github.com/iiab/iiab/issues/1193

### Fixes Bug

Proposed fix for bug #1193.

### Description of changes proposed in this pull request.

Check If there any languages are defined in transmission_kalite_languages. 

### Smoke-tested in operating system.

Debian 10

### Mention a team member for further information or comment using @ name

@holta

### CODE REVIEW

**Comment by holta** [comment]
Quite Popular Scenario:

A BitTorrent service (e.g. Transmission) is desired/needed to be turned on for _future_ usages, rather than for immediate downloads, particularly in areas where Internet costs are expensive.

(Am I perhaps misunderstanding this PR when I say that it would not support this common need to defer content torrenting ?)

**Comment by holta** [comment]
> @holta This PR is a simple check for null variable. We are using jinja2 filters to catch the edge cases where the variable is undefined.

I'm concerned implementers will be stuck downloading (and paying for the download of) ~43GB of English content against their will.

Wouldn't it be better to test if {{ transmission_kalite_languages }} is null, and (if indeed null) then launch /usr/bin/transmission-remote WITHOUT the `-a <URL>` flag?

**Comment by holta** [comment]
Interestingly http://box:9091 works immediately during IIAB 6.7/master installations, even when a language is not set in /etc/iiab/local_vars.yml

In other words: functionality is complete (from my perspective) however the red error as shown in #1193 really should be mitigated to avoid confusing new implementers &mdash; who will very reasonably perceive (incorrectly!) that http://box:9091 failed to start :/

**Comment by arky** [comment]
> I'm concerned implementers will be stuck downloading (and paying for the download of) ~43GB of English content against their will.
> 
Set always transmission_provision: False to prevent adding any torrents. 

> Wouldn't it be better to test if {{ transmission_kalite_languages }} is null, and (if indeed null) then launch /usr/bin/transmission-remote WITHOUT the `-a <URL>` flag?

Tried that already. The Ansible looping with_items is limited. This is very simple solution for an edge case.

**Comment by arky** [comment]
> Interestingly http://box:9091 works immediately during IIAB 6.7/master installations, even when a language is not set in /etc/iiab/local_vars.yml
> 
> In other words: functionality is complete (from my perspective) however the red error as shown in #1193 really should be mitigated to avoid confusing new implementers — who will very reasonably perceive (incorrectly!) that http://box:9091 failed to start :/

The failure or success of the following task has no impact on the transmission-daemon process. Seems to me like totally different problem.

**Comment by arky** [comment]
@holta Updated the pull request and changed the PR title.

**Comment by tim-moody** [comment]
when: transmission_kalite_languages is **not** defined and transmission_provision

seems backwards

**Comment by arky** [comment]
@tim-moody Typo fixed

**Comment by holta** [comment]
Thanks all for continuing to push this forward so we can get passionate educators far closer to the Sneakernet-of-Alexandria vision (#1078 and similar) of efficiently exchanging the best local/peer-proven OER's [Open Education Resources].

Fixes #1193

**Pull request merged**
