### PR TITLE
add utility scripts

### PR DESCRIPTION
**Pull request by tim-moody**

### CODE REVIEW

**Comment by jvonau** [comment]
Ok, now I'm a bit miffed...  iiab-upgrade? Really after https://github.com/iiab/iiab-factory/pull/135 has been open for discussion for 2 years and  https://github.com/iiab/iiab/issues/3303#issuecomment-1197073845 Really, just wow some nerve..

**Comment by tim-moody** [comment]
looks like your factory 135 does a lot more than this, so not sure there's a conflict.

**Comment by jvonau** [comment]
Very misleading name for a utility that upgrades only admin-console

**Comment by jvonau** [comment]
```
iiab-admin@box:/opt/iiab/iiab $ sudo ./iiab-upgrade

WARNING: Upgrades are not guaranteed to be compatible with previous installs

\Please make sure you know what you are doing.

\Press CTL-C to STOP or <enter> to continue.


Cloning into 'iiab-latest'...
remote: Enumerating objects: 1262, done.
remote: Counting objects: 100% (1262/1262), done.
remote: Compressing objects: 100% (1071/1071), done.
remote: Total 1262 (delta 137), reused 658 (delta 74), pack-reused 0
Receiving objects: 100% (1262/1262), 4.30 MiB | 7.49 MiB/s, done.
Resolving deltas: 100% (137/137), done.
fatal: No names found, cannot describe anything.
Failed to get unit file state for NetworkManager.service: No such file or directory
{"stage"                  : "9",
"dhcpcd"                  : "enabled",
"network_manager"         : "none",
"systemd_networkd"        : "disabled",
"iiab_remote_url"         : "https://github.com/iiab/iiab",
"iiab_branch"             : "master",
"iiab_commit"             : "f83a7188bd653822aa101b40fbea18ae6fdf406a",
"iiab_recent_tag"         : "none",
"rpi_model"               : "Raspberry Pi 400 Rev 1.0",
"devicetree_model"        : "Raspberry Pi 400 Rev 1.0",
"ansible_version"         : "2.13.0",
"os"                      : "raspbian",
"os_ver"                  : "raspbian-11"}

IIAB has been Upgraded

\Press CTL-C to STOP or <enter> to upgrade Admin Console.


hint: Pulling without specifying how to reconcile divergent branches is
hint: discouraged. You can squelch this message by running one of the following
hint: commands sometime before your next pull:
hint: 
hint:   git config pull.rebase false  # merge (the default strategy)
hint:   git config pull.rebase true   # rebase
hint:   git config pull.ff only       # fast-forward only
hint: 
hint: You can replace "git config" with "git config --global" to set a default
hint: preference for all repositories. You can also pass --rebase, --no-rebase,
hint: or --ff-only on the command line to override the configured default per
hint: invocation.
remote: Enumerating objects: 67, done.
remote: Counting objects: 100% (67/67), done.
remote: Compressing objects: 100% (27/27), done.
remote: Total 67 (delta 43), reused 60 (delta 40), pack-reused 0
Unpacking objects: 100% (67/67), 12.95 KiB | 184.00 KiB/s, done.
From https://github.com/iiab/iiab-admin-console
   8a20602..84ed438  master     -> origin/master
Updating 8a20602..84ed438
Fast-forward
 docs/1.Overview.md                                 |   4 +-
 docs/4.JS-Menu.md                                  |   2 +-
 roles/cmdsrv/files/iiab-cmdsrv3.py                 |   4 +
 roles/cmdsrv/files/presets/fr-school/menu.json     |   1 -
 .../templates/scripts/check-oer2go_catalog.py      | 111 +++++++++++++++++
 .../templates/scripts/get_oer2go_catalog3.py       |  16 ++-
 roles/cmdsrv/templates/scripts/oer2go-extra.txt    | 134 +++++++++++++++++++++
 roles/console/files/js/admin_console.js            |   6 +
 vars/linuxmint.yml                                 |   2 +-
 9 files changed, 270 insertions(+), 10 deletions(-)
 create mode 100644 roles/cmdsrv/templates/scripts/check-oer2go_catalog.py
 create mode 100644 roles/cmdsrv/templates/scripts/oer2go-extra.txt
Running local playbooks! 

PLAY [all] *********************************************************************

TASK [Gathering Facts] *********************************************************
ok: [127.0.0.1]

TASK [common] ******************************************************************

TASK [common : End Installation if nginx not enabled] **************************
skipping: [127.0.0.1]
```

**Comment by tim-moody** [comment]
>Very misleading name for a utility that upgrades only admin-console

agree. adm-upgrade would be better

**Comment by tim-moody** [comment]
if you prefer it can go in iiab-admin-console repo, but it will still touch iiab

**Pull request merged**
