### PR TITLE
[WIP] lokole: using Dead Snakes PPA to install python3.7

### PR DESCRIPTION
**Pull request by dahagag**
### Fixes bug:
- Lokole requiring Python 3.7

### Description of changes proposed in this pull request:
- Installed Python 3.7 using DeadSnakes PPA

### Smoke-tested on which OS or OS's:
- ubuntu/jammy64 on Vagrant

### CODE REVIEW

**Comment by holta** [comment]
@mabuelhagag thank you!

@jvonau do you have time to review this?

**Comment by dahagag** [comment]
Thank you @holta !
I'm still working on this. 
One thing I noticed is that the Celery worker is not reading the settings file.:

From `/home/lokole/logs/lokole_celery_worker.stderr.log`:

```[2022-06-20 12:01:00,327: ERROR/ForkPoolWorker-2] Task opwen_email_client.webapp.tasks.sync[9e86b746-9da1-4790-add4-0e1be05897f5] raised unexpected: TypeError('gethostbyname() argument 1 must be str, bytes or bytearray, not None')
Traceback (most recent call last):
  File "/library/lokole/venv/lib/python3.7/site-packages/celery/app/trace.py", line 412, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/library/lokole/venv/lib/python3.7/site-packages/celery/app/trace.py", line 704, in __protected_call__
    return self.run(*args, **kwargs)
  File "/library/lokole/venv/lib/python3.7/site-packages/opwen_email_client/webapp/tasks.py", line 41, in sync
    if check_connection(AppConfig.EMAIL_SERVER_HOSTNAME, 80):
  File "/library/lokole/venv/lib/python3.7/site-packages/opwen_email_client/util/network.py", line 7, in check_connection
    host = gethostbyname(hostname)
TypeError: gethostbyname() argument 1 must be str, bytes or bytearray, not None```

**Comment by holta** [comment]
@mabuelhagag what aspects most need to be tested?

Can we focus testing on Ubuntu 22.04 initially?

PS I don't know if Python 3.7 is a long-term solution (?) but I agree that pushing to explore workarounds is a vital 1st step!

**Comment by dahagag** [comment]
I'm testing it on Ubuntu 22.04 (Jammy) VM.

I agree that Python3.7 is not a permanent solution. I was initially thinking about upgrading Lokale itself to use Python 3.10 but that would be considerable mount of work that might be done at a later stage.

**Comment by jvonau** [comment]
With Lokole running in a virtual environment there is no real need to install system level packages, I suggest try adding ' - { name: 'python', version: '3.7' }' to the "workarounds for older flask version used" ansible pip call.

**Comment by jvonau** [comment]
> I'm testing it on Ubuntu 22.04 (Jammy) VM.
> 
> I agree that Python3.7 is not a permanent solution. I was initially thinking about upgrading Lokale itself to use Python 3.10 but that would be considerable mount of work that might be done at a later stage.

You could pin the python version in the requirements file.

**Comment by jvonau** [comment]
> Thank you @holta ! I'm still working on this. One thing I noticed is that the Celery worker is not reading the settings file.:
> 
> From `/home/lokole/logs/lokole_celery_worker.stderr.log`:
> 
> ```
> Traceback (most recent call last):
>   File "/library/lokole/venv/lib/python3.7/site-packages/celery/app/trace.py", line 412, in trace_task
>     R = retval = fun(*args, **kwargs)
>   File "/library/lokole/venv/lib/python3.7/site-packages/celery/app/trace.py", line 704, in __protected_call__
>     return self.run(*args, **kwargs)
>   File "/library/lokole/venv/lib/python3.7/site-packages/opwen_email_client/webapp/tasks.py", line 41, in sync
>     if check_connection(AppConfig.EMAIL_SERVER_HOSTNAME, 80):
>   File "/library/lokole/venv/lib/python3.7/site-packages/opwen_email_client/util/network.py", line 7, in check_connection
>     host = gethostbyname(hostname)
> TypeError: gethostbyname() argument 1 must be str, bytes or bytearray, not None```
> ```

It's reading the file just fine, that variable does not exist until the client is registered.

**Comment by jvonau** [comment]
> With Lokole running in a virtual environment there is no real need to install system level packages, I suggest try adding ' - { name: 'python', version: '3.7' }' to the "workarounds for older flask version used" ansible pip call.

Sorry that doesn't work..

**Comment by jvonau** [comment]
Doesn't `add-apt-repository` break non-Ubuntu based OS like RasPiOS and Debian? You don't need to use `sudo`, the script is already running under sudo. The current RasPiOS ships with python 3.9 and that hardware was the target platform for deployment.

**Comment by jvonau** [comment]
Refs:https://github.com/iiab/iiab/issues/3132 https://github.com/iiab/iiab/pull/3149 Upstream https://github.com/ascoderu/lokole/issues/585

**Comment by jvonau** [comment]
There is a small bug with 'python_ver: 3.10 in vars/ubuntu-2204.yml the value needs to be a string and not an integer as the trailing '0' is being dropped when writing the nginx template. Still requires workaround https://github.com/iiab/iiab/issues/2833#issuecomment-931559600 but otherwise the install is successful on Ubuntu-22.04.

**Comment by jvonau** [comment]
@mabuelhagag what is your working branch you are using at https://github.com/mabuelhagag/lokole?

**Comment by holta** [comment]
Thanks @jvonau for catching this:

> There is a small bug with 'python_ver: 3.10 in vars/ubuntu-2204.yml the value needs to be a string and not an integer as the trailing '0' is being dropped when writing the nginx template.

Is the following small patch (just applied) sufficient to deal with the above?

- PR #3260

**Comment by holta** [comment]
(Typo fixed above: I meant 3260 not 3160)

**Comment by holta** [comment]
> > Thank you @holta ! I'm still working on this. One thing I noticed is that the Celery worker is not reading the settings file.:
> > From `/home/lokole/logs/lokole_celery_worker.stderr.log`:
> > ```
> > Traceback (most recent call last):
> >   File "/library/lokole/venv/lib/python3.7/site-packages/celery/app/trace.py", line 412, in trace_task
> >     R = retval = fun(*args, **kwargs)
> >   File "/library/lokole/venv/lib/python3.7/site-packages/celery/app/trace.py", line 704, in __protected_call__
> >     return self.run(*args, **kwargs)
> >   File "/library/lokole/venv/lib/python3.7/site-packages/opwen_email_client/webapp/tasks.py", line 41, in sync
> >     if check_connection(AppConfig.EMAIL_SERVER_HOSTNAME, 80):
> >   File "/library/lokole/venv/lib/python3.7/site-packages/opwen_email_client/util/network.py", line 7, in check_connection
> >     host = gethostbyname(hostname)
> > TypeError: gethostbyname() argument 1 must be str, bytes or bytearray, not None```
> > ```
> 
> It's reading the file just fine, that variable does not exist until the client is registered.

Who can provide @mabuelhagag instructions to register a client, so he can move forward in his understanding here?

@nzola can you help?

**Comment by dahagag** [comment]
> With Lokole running in a virtual environment there is no real need to install system level packages, I suggest try adding ' - { name: 'python', version: '3.7' }' to the "workarounds for older flask version used" ansible pip call.

@jvonau 
I'm using `virtualenv_command: python3.7 -m venv "{{ lokole_venv }}"` which should install the packages by Python 3.7 in the venv.

**Comment by nzola** [comment]
@mabuelhagag @holta @jvonau To register a client one need to have a toeken ID from Ascoderu/Lokole GitHub. This token can be added in the Lokole script during the stand alone install or when you start Lokole for the first time after IIAB/Lokole install option.
I may be able to create a token for @mabuelhagag . If I can't, I will ask for help.

**Comment by jvonau** [comment]
> > With Lokole running in a virtual environment there is no real need to install system level packages, I suggest try adding ' - { name: 'python', version: '3.7' }' to the "workarounds for older flask version used" ansible pip call.
> 
> @jvonau I'm using `virtualenv_command: python3.7 -m venv "{{ lokole_venv }}"` which should install the packages by Python 3.7 in the venv.

Why 3.7? The code has known to be working with python 3.9 and I just tested 3.10 on ubuntu-22.04. What issue are you trying to solve?

**Comment by mabuelhagag** [comment]
> > > With Lokole running in a virtual environment there is no real need to install system level packages, I suggest try adding ' - { name: 'python', version: '3.7' }' to the "workarounds for older flask version used" ansible pip call.
> > 
> > 
> > @jvonau I'm using `virtualenv_command: python3.7 -m venv "{{ lokole_venv }}"` which should install the packages by Python 3.7 in the venv.
> 
> Why 3.7? The code has known to be working with python 3.9 and I just tested 3.10 on ubuntu-22.04. What issue are you trying to solve?

#3132

**Comment by dahagag** [comment]
@jvonau As I had a discussion with @holta I found out that the issue shouldn't be with the Python version rather than making the configuration work and resolving issues with Ubuntu 22.04.

So I'll be closing this PR and will attempt to resolve #2833, #2986

**Comment by holta** [comment]
Thanks @mabuelhagag for your efforts!

If you get the chance in coming days, please post additional tickets (issues or PR's!) towards getting to the bottom of this.

Also do clarify this upstream ticket when you can, which @jvonau mentioned above:

- ascoderu/lokole#585

**Pull request closed without merging**
