### PR TITLE
Deprecated

### PR DESCRIPTION
**Pull request by georgejhunt**
I'll wait for Tim's ok on this. I think he said yes in principle

### CODE REVIEW

**Comment by tim-moody** [comment]
OK. Maybe leave any install and enable variables behind to keep from breaking things.

**Comment by holta** [comment]
Context: several people had asked to deprecate activity-server however George just told me by telephone that he overruled them in order to honor @jvonau's request in PR #146 ("I'd like to keep activity-server around as this playbook has the last know working example of loading "content" on demand from usbkeys.")

**Comment by georgejhunt** [comment]
I take that as an ok for deprecated. I've needed to comment out ./meta/main
liines for the moved items, and Adam has left the variables commented out
in his downloadable local vars files. That seems best to me.

In the spirit of checking with one another, are you ok with:


   - use published local_vars_big as test vars for both centos, and debian
   <https://github.com/iiab/iiab/pull/220>
   #220 opened 34 minutes ago by georgejhunt
   <https://github.com/iiab/iiab/issues?q=is%3Apr+is%3Aopen+author%3Ageorgejhunt>

   -
   Npmreinstall <https://github.com/iiab/iiab/pull/216>
   #216 opened 2 hours ago by georgejhunt
   <https://github.com/iiab/iiab/issues?q=is%3Apr+is%3Aopen+author%3Ageorgejhunt>


This just checks for existence of a directory that the npm install
generates, and avoids reinstall, which is what is broken -- permits
sugarizer to install -- I'd still like to disable mongodb.  But that takes
more testing

   -
   quotes  <https://github.com/iiab/iiab/pull/215>bug
   <https://github.com/iiab/iiab/issues?q=is%3Apr+is%3Aopen+label%3Abug>
   #215 opened 2 hours ago by georgejhunt
   <https://github.com/iiab/iiab/issues?q=is%3Apr+is%3Aopen+author%3Ageorgejhunt>
      6.4 <https://github.com/iiab/iiab/milestone/1>
   - An oversight default password in vars/default.yml
   -
   move install test to last item copied
   <https://github.com/iiab/iiab/pull/213>
   #213 opened 4 hours ago by georgejhunt
   <https://github.com/iiab/iiab/issues?q=is%3Apr+is%3Aopen+author%3Ageorgejhunt>

   - This fixes the library.xml test which you don't like (I think)

**Comment by jvonau** [comment]
> Context: several people had asked to deprecate activity-server

I can see why, it was never ported over to debian until I did the work a year later. If you turned it on boom broken ansible.

**Comment by tim-moody** [comment]
I'm assuming this won't break the console as variables are loaded dynamically. I prefer to leave services in the interface undisplayed rather than taking things in and out.

**Comment by jvonau** [comment]
It's ok for testing but the boolean definitions should really be in roles/1-prep/defaults/main.yml, away from the users who like to edit files blindly.

**Comment by jvonau** [comment]
I'd rather not move the playbooks but support # out the meta files to enable quick testing if someone wanted.

**Comment by holta** [comment]
This PR has been rejected in our community call this morning (http://minutes.iiab.io)

**Pull request closed without merging**
