### PR TITLE
Some copyedits [CONTRIBUTING.md -> IIAB-Contributors-Guide on GitHub wiki]

### PR DESCRIPTION
**Pull request by Daniel-Mietchen**
Brushed the text a bit.

### CODE REVIEW

**Comment by holta** [comment]
@Daniel-Mietchen I feel absolutely terrible that you edited an obsolete file that was moved to https://github.com/iiab/iiab/wiki/IIAB-Contributors-Guide over 2017/2018, and much further revised in its new location:

1) Can you possibly edit https://github.com/iiab/iiab/wiki/IIAB-Contributors-Guide instead?
2) Can we delete https://github.com/iiab/iiab/blob/master/CONTRIBUTING.md so this kind of wasted effort never happens again?
3) And/or any other recommendations to embrace your suggestions more cleanly?

**Comment by Daniel-Mietchen** [comment]
First-time submitters of issues or pull requests are directed towards CONTRIBUTING.md by default, so I think updating this should take priority here on GitHub.

Happy to go over IIAB-Contributors-Guide and related documentation during the hackathon.

**Comment by holta** [comment]
> First-time submitters of issues or pull requests are directed towards CONTRIBUTING.md by default, so I think updating this should take priority here on GitHub.

Maintaining 2 copies of the identical document would be too wasteful, and downright maddening truth be told :-(

Can we please just put a single link (and nothing else) inside CONTRIBUTING.md — pointing to https://github.com/iiab/iiab/wiki/IIAB-Contributors-Guide ?

I'm so terribly sorry this happened, but we need to get this right now, to avoid infuriating others !

PS manually auto-converting https://github.com/iiab/iiab/wiki/IIAB-Contributors-Guide to CONTRIBUTING.md using https://pandoc.org is more than I personally can handle (i.e. on a regular basis every time someone happens to change the wiki!)

**Comment by holta** [comment]
@Daniel-Mietchen I'm going to merge this and then immediately rename it to CONTRIBUTING.deprecated.md via PR #2032 

Again my profound apologies (the person who wrote this originally appears to have drifted off).

**Pull request merged**
