### PR TITLE
iiab-make-kiwix-lib: clean up, cut out commented out material

### PR DESCRIPTION
**Pull request by georgejhunt**
Pulling this into iiab/master needs to be done with a corresponding change to admin-console js-menu.js.
Installed on unclean working rpi (with ./runrole kiwix), ran to completion (iiab-make-kiwix-lib) without error, and had the new zim_version_idx.json output structure.
I don't remember from this mornings' discussion whether I should soft code role "js-menu".

### CODE REVIEW

**Comment by georgejhunt** [comment]
I assume that this also applies to:
                zim_info['menu_item'] =
find_menuitem_from_zimname(wiki_name)
                articlecount,mediacount,size,tags =
get_substitution_data(wiki_name)
                zim_info['article_count'] = articlecount
                zim_info['media_count'] = mediacount

etc...

**Comment by georgejhunt** [comment]
No, This is part of the automatic loading of home page that we agreed last
week would wait for the next release.

**Comment by holta** [comment]
> This PR, and the corresponding one in iiab-admin-console are ready to go.

Great, @tim-moody please confirm!

PS is the "corresponding one" https://github.com/iiab/iiab-admin-console/pull/104 ?

**Comment by holta** [comment]
@georgejhunt thinks this tkt will likely go away in the coming month, in favor of a superset (likely to be paired up with superset https://github.com/iiab/iiab-admin-console/pull/106 ...just like this PR was paired up with https://github.com/iiab/iiab-admin-console/pull/104).

**Comment by georgejhunt** [comment]
Tim,
Following up on this morning's conversation, I started looking into using library.xml as the source for substitution data. But I do not find size, date,articleCount,etc fields in library.xml. It looks like we are using kiwix manage to generate library.xml (roles/kiwix/templates.iiab_make_kiwix_lib.py line 171).  How can I configure manage to pass through the fields we need? Can you point me to the documentation for manage?

**Comment by tim-moody** [comment]
Here is a typical entry in library.xml. The problem is that it is overwhelmed by the icon in base64, but look clear at the bottom.

`<book id="018c2866-e312-d56e-5d64-2f405de74090" path="content/phet_fr_2018-06.zim" title="PhET Interactive Simulations" name="phets" description="Interactives simulations for Science and Math" language="fra" creator="University of Colorado" publisher="Kiwix" favicon="iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAYAAABXAvmHAAAABmJLR0QA/wD/AP+gvaeTAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH4QEZFTYXEZ8mCwAAABl0RVh0Q29tbWVudABDcmVhdGVkIHdpdGggR0lNUFeBDhcAAArlSURBVGjexZl7cFzVfcc/59x796nd1cPa1eppW3h42Abzip8yDk5wGgcmEENbQjLpNMOY4HQIJoEytAOp00JcSMdNghNCoIGpJyXFwTYpAUMSxtgG7EJsbFmWhOTVcxc9d1er3b177+kfK8vIlmxLltzf7M7sPfecc7+/+/v+Hue3gilI53Cacrdr9PqRli7XG8m0q9LQAoM5u7JI1xYlbBXMWXaBJlC6lINCcKIQcfyjrNlSIET6ntJA6qvhYvPkHk9FYtxfHZw0FjGZyfXxIS7/5Vtw380AfP1Y25UfprPLkrZamVVqybCt5gzYNpatTu2uTj3JKQRFmkTCn72a3Gcg/nhzwPPuE3PDrQAPNnfxRG14ZhS4p7GDp+dVAPB3jZ2rfpdIPdSZy11pK8JppaZiSNxS2DoiUus09v5LWfHf/0WoMALw1IkY99cEp0eBv2lo57lLKwF4rKW7bFc89cLB4cxqe5LWO5c4haDO696yoyb4oMfnTgP8e1uMb1flFVGZLoQzPDkFvPuPMbTkMv4YHXT/Y6zv9uMZ82fdZs6FmFbsY2SuQ2+pdBjffHvB7LdOjimlhBBCTcoCO7p6uSVcwuOtsbJn+uJbOszc7VOlyqREgVvTs4b0/uTPlUefrzHfuBP/F38gAzckzluBV6N9rA0V8/2W7qL/6E/uac6aV3BRRIAyWGR08rBnr7rNeWRIaH4hfKv8smSdPd4K/fQBx/6jrA0V81hLd+DFgcSB5kxuLmJmQRtY+EWGGx1tPOR5h2uME6CksBEFnSnnh1sGFzuA9PqDHWy9tmJiBe5qaOPFS6vYdKI7/GxP4vWW7EyBF6B0AjJFnRHhJsfH3OY4RoUeA6VjqTwsTbd4bF/xon3h7FbgG1uvreCJYzEevCw4MYV2RPs83+nse6E5Y942/cAlKJ05Wi/3eg7weaOROdoAPpFGIbBPg2PlFCv3r+ZAYBlX+B0/Onxj7f3j7HhKHj8RZVN04I62bG5GwK8y2vh94Qs0lWzhPvc7zNdjeEQWC3kGeAF8PGgQM0JYStGcNL+5/E8tNwFsj/SPpdC+vjhLi/30WXZFJJv7efaCo40AJB6RoVbrZ7Vxgg3uA9TqHXmKoJ2pngBbjd3ieNJLF0UApCzb1zqce/SBQ137b60uio9RYGmxH4DX4qlfdZs5Y+pxPk+RoIyzzlXPFxxNLDHaKZUDoDQs5TxjhSYVOVvwQdTDomBqtPJQCo6ni0kr9+jcaDq39HA8+w1gy7bWfv56dhF681CaWq+Le5s61z7dM3jj1MALUBpX6VG+59nHGmcDBSKLQQ4QWMoYd5UmFY19Lp4+NIt/WNw95l4mJzgYLwWHY3QspxTvDqSfVEr9XAiRBtBrvfmqctfg0EZ7kqB1LPwiy2qjjY2efSx2tIASWCOupSYIYQJImJLn62fxQlOQX3++Cb/T4tMMStuSd+OzIKiDOoVsIGvpy99ufQh4dJRCt9dHrtuVSC2YDPgbjA6+5jnMF40GwvKTkfCnnXWVJhVmTvJSg49/aroUiorZcfP71DpTWLYco2B/xkFLNjSu9seS2buVUv8shMhKgIasuSKnKJ3UmaDfJnYsipEeAkMHIc/q0prD5kC3l8+9PIevtnyW0kVz+MOKfcxz9IwBDyClYneHH3yFn6rHT0nctAu/sDeyFkDe09jhjlv2SnMykUdA45CLhw/NpvTZhdz220s4GPNOOD1pSu7bXcVnXprH2xUrqFtewm8rd1JKHEuNo7hUvBopAr8/781nlEvK3ZDMrgTQ9w+l3Vmllk+u4FIQDkJFCLpibG9oZft/h7k60MPdC3qpq0xSG8gynJO81VbAg++EaSYMaxaxsizBNs9/USxSWBOleRtej9dABWCdedtSkMrZC7c29wb0Cqfhb0rkJn+Ws22wgVAplJVCf5wPunq454MOQns7WV45zEDW4K2IFy6rhfkL+ZK/mWc9rxCUg+PmgpN+8mG3m4w3PMZ5T5esovpX7fFCvVjKKxO2PfWcdXKtvyD/ra0k2h/n5UP10NMHN1wP5eV8zX2En/p24iEzIfhR+rQUQGlwXPqcsoKq6DEtv/6JmZs3rRWDrkOwBG6qg5wFUoJS9A8L3u53c13QJuCwcGgKpcZxUaF4NRqGuW6wcxM+xpDC4wCf3q9U1fQfSlSeqELkfwsNVybF71p9bDtWyOyCNNeUDbOiPEWpLwuWwLIFQsBAQqdFr8w7wllkwLQJGNKlBzQtnH/IDBb9NlQU2fzbqnb6MzobGxbxoz/ZVMs4y6vSbLiyl6vKkzBSUqT8ZWelD4CtFNVuI6DP6FnlU2H3E6sA05Y8dbCU5z4y4KZl1Ed7qT9ynF98NIvLSzI8triLxn4HQ66icyqAyH/0PsuKzOjbH4ncEVnMV3Zfys5ICFYuAI8H5nphbjV0dFN/NMIdrxeCQ4NrjHO7GoLIsNmv+6B15k1gsycbBt8SWF0MBd589FIqn6aLy2BBCJKDkE2Dpp1zR58ucUgxLBd7XV1chGYDlgVzysHjPhV6AUxg0MqPeXxQWHrWsuRT2TjpFCIpt/QM7inWJRdFTqeqAhJAbvJbaUJ0hl16XC50OXNuKdv5/5C4gmE1pR6fDY1fLi/okV8JeFJeKfZcdPCDClJMCbwuBGVO/dj6OSUp+UBNKK0Uu51CXBzgChgkD37qWyTDTu210a5Enc/1viFE10znAmwgDgxdWNQI6DL25oqaN0cV+OW8ykNlhnZgRsFngD6VB38hxlaKuhL300II9ciRKHJzaxSA9SX+7+szRaPECHiTCwQPYbfR+8rS6n8F2DQ/hPzu7BAbm7t4oDp44Dq346Xp5LowgZ6RaDMNuUaTgmsK3fcCnEhkzmwtbm3r9T8a623qNq3SKVNFjdAlBaRHgIvpYWG1x3gj5JRra70uc9v1FWNbi/c2drK+qiRe6zC+5ZVicjsLEDaIBNCjoF/lwcO0/Y/j1mTfVX7nI++tqh0FP0aBn8wrB2DPgtkvVzuM584nN0tLIIZAfAIqqlCJEZ5Pf2mi6krcm3csrX7vln2Ridvrm09EEULYSqlvz32/eV7HkLkil0/b2ApsSyFsUCaIHNiWPa1vefySAa7wO3/6++U1j/PkO+xYWj1xd/q7NSE2NHUihBjaYPi+XJHRd9v9CrPPxuq3UXGFnVSorMK21Sh9Zg68YLbH2Hz4xtoNAL9Zdzlnba8D/PiScta9G2Hj1aHeuhLPHfN8jp1SnuI6FylhC+DqgHNLU13NwwA/rI+yrqZ43HnnyBtKv+LN5uebkuY6U43TXp4B4LoUQ2tKvY/vWla9CeDFj3u5a27JRP3wiWXjoS6EELn6z11y1+Ii1/pZDu2oNlMWUKBLQZlL/8Odlf41u5ZVb+I7r9GaSE8I/rwssL19gFsrCwH4+sG28PGEeffxIfPRvkxu+hoBCqo9Rl/IpX9rkc/x6jPXViT/8r12fv2ZyvOy2HnJjrYBbqlaBhxlwLKMW/e2bf7fwfTfxk3bO5XqRuSDrSp16rGlxe4fvLKk6scAd77fzn9eXzkpyk1Kvnckyg/nh076h3PN3shfNSbNL8WyuVqlCEpBiWkrl306rwUIIZK2UjGXlL1hl3Z4vs/5m5cWV/3PhfrM1OT+nfDUzaOX2yJ9hc9EktXJXC4cS1u+QocMuqRwKWDYJpnNWT1+pzYQ0GT79sVVbQWGNjzqa4e7eHJheEow/g/AmXoqnCDZuAAAAABJRU5ErkJggg==" faviconMimeType="image/png" date="2018-06-01" articleCount="61" mediaCount="63" size="32964" />
`

**Comment by tim-moody** [comment]
/opt/iiab/kiwix/bin/kiwix-manage gives usage, but there are no parameters to pass meta data. It just reads from the zim and writes to library.xml.

the show command is not working for me.

**Comment by georgejhunt** [comment]
Thanks, I missed that

**Comment by tim-moody** [comment]
there's already a function to read it.

**Comment by holta** [comment]
I'm assuming this is being replaced by #1377 and/or subsequent PR against master?

(But please re-open if I'm wrong!)

**Pull request closed without merging**
