### PR TITLE
Update roles/samba/README.rst and review IIAB's /etc/samba/smb.conf

### PR DESCRIPTION
**Pull request by holta**
@georgejhunt can you review IIAB's [Samba README](https://github.com/holta/iiab/blob/samba-update/roles/samba/README.rst) quickly?

Thanks also if you can quick sanity-check IIAB's default [/etc/samba/smb.conf](https://github.com/holta/iiab/blob/samba-update/roles/samba/templates/smb.conf.j2) !

Finally, is it time to deprecate IIAB's Samba [handler](https://github.com/holta/iiab/blob/samba-update/roles/samba/handlers/main.yml) &mdash; or is this still useful?

cc: @tim-moody, @jvonau, @deltacloud9

Other recent security/maintenance issues, just FYI:

- #2924
- PR #2948

### CODE REVIEW

**Comment by jvonau** [comment]
> Finally, is it time to deprecate IIAB's Samba [handler](https://github.com/holta/iiab/blob/samba-update/roles/samba/handlers/main.yml) — or is this still useful?
> 
> cc: @tim-moody, @jvonau, @deltacloud9

This is the only instance in roles/ where a handler is used. An ansible handler would wait until the ansible play is ending and restart the service then but there is code to restart the smb service within the role making one of the operations redundant.

**Comment by holta** [comment]
I'm happy to `mv roles/samba/helpers roles/samba/helpers.unused` unless someone has a better idea (:

**Comment by holta** [comment]
I've added a link from http://wiki.laptop.org/go/IIAB/Security

(...in preparation for the merging of this PR.)

**Comment by holta** [comment]
Summary:

- We still very much need someone to review IIAB's [/etc/samba/smb.conf](https://github.com/holta/iiab/blob/samba-update/roles/samba/templates/smb.conf.j2)
- This PR will now be merged, so IIAB's [Samba README](https://github.com/holta/iiab/blob/samba-update/roles/samba/README.rst) is at least more vividly clear.

**Pull request merged**
