### PR TITLE
use gitea as a template for remoteit

### PR DESCRIPTION
**Pull request by jvonau**
### Fixes bug:
#3006
### Description of changes proposed in this pull request:
map archs to file names in defaults/main.yml like gitea does
### Smoke-tested on which OS or OS's:
not yet.

### CODE REVIEW

**Comment by jvonau** [comment]
corrects https://github.com/iiab/iiab/pull/3005#issuecomment-953505445 runs to completion and should work across all distros http://sprunge.us/tDwje0

**Comment by jvonau** [comment]
Should I open an issue for these or are you aware?
```
Oct 28 10:26:02 box systemd[1]: /etc/systemd/system/nodered.service:14: Standard output type syslog is obsolete, automatically updating to journal. Please update your unit file, and consider removing the setting altogether.
Oct 28 10:26:02 box systemd[1]: /etc/systemd/system/iiab-rpi-root-resize.service:8: Standard output type syslog is obsolete, automatically updating to journal. Please update your unit file, and consider removing the setting altogether.
```

**Comment by holta** [comment]
This PR looks awesome.

**Comment by holta** [comment]
> Should I open an issue for these or are you aware?
> 
> ```
> Oct 28 10:26:02 box systemd[1]: /etc/systemd/system/nodered.service:14: Standard output type syslog is obsolete, automatically updating to journal. Please update your unit file, and consider removing the setting altogether.
> Oct 28 10:26:02 box systemd[1]: /etc/systemd/system/iiab-rpi-root-resize.service:8: Standard output type syslog is obsolete, automatically updating to journal. Please update your unit file, and consider removing the setting altogether.
> ```

Really great to know.

Definitely open an issue if you have a moment.

Thanks!

**Comment by holta** [comment]
Needs testing but this looks to be a huge step forward so let's let it rip — to broadly advance community testing across all OS's.

**Pull request merged**
