### PR TITLE
Open Samba ports if enabled

### PR DESCRIPTION
**Pull request by tim-moody**
untested

### CODE REVIEW

**Comment by holta** [comment]
Hi @mikerjensen as the original requester (#1664) can you please review and/test Tim's PR #1665 here?

Thanks if possible!

(Tagging @georgejhunt @jvonau @m-anish who might also be to help?)

**Comment by mikerjensen** [comment]
The proposed changes look good to me, but it's not apparent to me how to test them.

**Comment by holta** [comment]
> The proposed changes look good to me, but it's not apparent to me how to test them.

@mikerjensen can you let us know if the following works!?
```
sudo su -
cd /opt/iiab/iiab
git checkout -b tim-moody-samba-ports master
git pull https://github.com/tim-moody/iiab.git samba-ports
./iiab-network    # this command arranges IIAB networking -- plz make sure your WiFi/Ethernet/routers are all plugged in (or unplugged from!) IIAB according to your final configuration, before running this command
```
PS normally you'd run the command `/usr/bin/iiab-gen-iptables` whose source code is here: https://github.com/iiab/iiab/blob/master/roles/network/templates/gateway/iiab-gen-iptables

**Comment by mikerjensen** [comment]
Sorry i'm such a noob at this, i ran the below three lines from the above:
sudo su -
cd /opt/iiab/iiab
git checkout -b tim-moody-samba-ports master

and on the last line I  got:
fatal: Cannot update paths and switch to branch 'tim-moody-samba-ports' at the same time.
Did you intend to checkout 'master' which can not be resolved as commit?

Not sure what to do next.

**Comment by holta** [comment]
@mikerjensen ok!  Let me tentatively merge this so you can test from our master branch.  I can always revert it later if nec.

So...please now run the following:
```
sudo su -
cd /opt/iiab/iiab
git checkout master
git pull
./iiab-network    # this command arranges IIAB networking -- plz make sure your WiFi/Ethernet/routers are all plugged in (or unplugged from!) IIAB according to your final configuration, before running this command
```
Does that solve your Samba problem?

**Comment by mikerjensen** [comment]
Sorry, 
'git checkout master' 
results in: 
error: pathspec 'master' did not match any file(s) known to git.

**Comment by holta** [comment]
> Sorry,
> 'git checkout master'
> results in:
> error: pathspec 'master' did not match any file(s) known to git.

Did @mitra42 build these machines?  Perhaps I wrongly assumed you were on IIAB's master branch.

So just manually install the 2 necessary files:
```
cd /opt/iiab/iiab/roles/network/templates/gateway/
mv iiab-gen-iptables iiab-gen-iptables.bkp
wget https://raw.githubusercontent.com/tim-moody/iiab/94eba076368ff21a5e7fcdd22dd55f723a690235/roles/network/templates/gateway/iiab-gen-iptables

cd /opt/iiab/iiab/vars
mv default_vars.yml default_vars.yml.bkp
wget https://raw.githubusercontent.com/tim-moody/iiab/94eba076368ff21a5e7fcdd22dd55f723a690235/vars/default_vars.yml

cd /opt/iiab/iiab
./iiab-network
```
Does that solve your Samba problem?

**Comment by mikerjensen** [comment]
Yes, sorry, i have installed IIAB via /usr/sbin/iiab with a modified line 179: 
git clone https://github.com/mitra42/iiab -b distweb --depth 1
I'm not sure running /usr/sbin/iiab again will pull these new files, 
so i tried running the commands you suggested in message above, but it didn't fix the samba problem, and the RPI was still unpingable via eth0. I did notice that after running the above commands /etc/iptables/rules.v4 had not changed (including after reboot) so i figured there was still an intermediary step i missed. I assumed it was 'install configured options' in the iiab admin menu, so i ran this, and iptables/rules.v4 did indeed change, dropped in size from 2204 bytes to 765 bytes. And SMB now works via eth0!

**Comment by holta** [comment]
@mikerjensen can you take a quick look at PR https://github.com/iiab/iiab/pull/1677 which should make your life a great deal easier, after I hopefully merge it along with Internet Archive functionality in the coming 24h?

**Comment by mikerjensen** [comment]
Looking good to me! and looking forward to the IA merge...good
      luck.
    Mike
    
    
    
    On 19/05/19 12:46, A Holt wrote:
    
    
      
      @mikerjensen
        can you take a quick look at PR #1677 which should make your life a
        great deal easier, after I hopefully merge it along with
        Internet Archive functionality in the coming 24h?
      —
        You are receiving this because you were mentioned.
        Reply to this email directly, view it on GitHub, or mute the thread.
      [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/iiab/iiab/pull/1665?email_source=notifications\u0026email_token=ABOY56WOLZJX4FLRVJM5I63PWE4ZFA5CNFSM4HNDUBAKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODVXANTY#issuecomment-493749967",
"url": "https://github.com/iiab/iiab/pull/1665?email_source=notifications\u0026email_token=ABOY56WOLZJX4FLRVJM5I63PWE4ZFA5CNFSM4HNDUBAKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODVXANTY#issuecomment-493749967",
"name": "View Pull Request"
},
"description": "View this Pull Request on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Pull request merged**
