### PR TITLE
Does something like 'RestartSec=3' in /etc/systemd/system/freepbx.service help Asterisk start reliably? (WIP)

### PR DESCRIPTION
**Pull request by holta**
I don't know yet!

But @lemueldsouza and @jvonau may be able to guide us towards a reliable outcome?

Asterisk 18.x should certainly be stable after almost 10 months (is it possible FreePBX 16.x Beta is not yet stable in this very basic way?)

Refs:

- PR #2905 
- PR #2906

### CODE REVIEW

**Comment by holta** [comment]
This PR is now being test-installed onto VM 191-u20-srv-2885-2908 = 10.8.0.42

That should complete within ~20 min &mdash; hopefully shedding light on the situation?

(Feel free to log in if it helps!)

PS its bare bones /etc/iiab/local_vars.yml is here: https://paste.ubuntu.com/p/Crp98g2Z5P/

**Comment by holta** [comment]
> That should complete within ~20 min — hopefully shedding light on the situation?

Done: that's only 1 test case so far, but it worked!

Now we need more data points &mdash; so I'll merge this PR hoping more folk can test this new install of [roles/pbx](https://github.com/iiab/iiab/tree/master/roles/pbx) on different hardware and different OS' &mdash; as intermittent timing issues (if that's what this is?!) are really tough to nail down.

Still, we'd really like a Silver Medal if not an actual Gold :1st_place_medal:

**Comment by jvonau** [comment]
The answer is NO, the setting is ignored unless Restart= is set to something other than the default of 'no'. A few seconds with your favorite search engine should of uncovered the answer for you.

**Comment by holta** [comment]
> setting is ignored unless Restart= is set to something other than the default of 'no'

Oops.  In any case, lots of background on that extraneous topic here:
https://www.freedesktop.org/software/systemd/man/systemd.service.html#Restart=

FWIW these crazy-long scripts are somehow/likely involved under the covers:

```
root@u20-srv:~# wc -l /etc/init.d/asterisk
143 /etc/init.d/asterisk
```
```
root@u20-srv:~# wc -l /usr/sbin/safe_asterisk
228 /usr/sbin/safe_asterisk
```

In any case, the pruning of Asterisk from [pbx/tasks/enable-or-disable.yml](https://github.com/iiab/iiab/blob/master/roles/pbx/tasks/enable-or-disable.yml) hopefully at least got rid of this rather regular error displayed by 'systemctl status asterisk' :

> Asterisk is already running.  /etc/init.d/asterisk will exit now.

Finally, note that 'systemctl restart asterisk' works at the command line (to properly enable the `asterisk -rvvv` command, our main test!)

Even if this same action causes more-trouble-than-its-worth when baked into enable-or-disable.yml :/

**Comment by holta** [comment]
Absolute worst case if we can't solve this in coming days we'll post a "Known Issue" in @lemueldsouza's pbx/README.rst here:

- PR #2905

**Comment by holta** [comment]
Another possibility is that Asterisk 18.5.1 (v18 originally released 2020-10-20) still needs to tune up its init.d timings for Debian 11, similar to systemd unit file timing/sequencing?  I can't prove it, but this kind of result below would certainly appear to be more common on Debian 11 than with Ubuntu 20.04 [*] &mdash; immediately after install of roles/pbx:

```
root@deb11-srv:~# asterisk -rvvv
Unable to connect to remote asterisk (does /var/run/asterisk/asterisk.ctl exist?)
```
```
root@deb11-srv:~# systemctl status asterisk
● asterisk.service - LSB: Asterisk PBX
     Loaded: loaded (/etc/init.d/asterisk; generated)
     Active: inactive (dead)
       Docs: man:systemd-sysv-generator(8)
```

```
root@deb11-srv:~# systemctl is-enabled asterisk
asterisk.service is not a native service, redirecting to systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install is-enabled asterisk

...
```

```
root@deb11-srv:~# systemctl status freepbx
● freepbx.service - FreePBX VoIP Server
     Loaded: loaded (/etc/systemd/system/freepbx.service; enabled; vendor preset: enabled)
     Active: active (exited) since Wed 2021-08-04 15:41:57 EDT; 4min 1s ago
   Main PID: 81055 (code=exited, status=0/SUCCESS)
      Tasks: 0 (limit: 2341)
     Memory: 0B
        CPU: 0
     CGroup: /system.slice/freepbx.service

Aug 04 15:41:57 box.lan fwconsole[81055]:  34000 [-------->-------------------]
Aug 04 15:41:57 box.lan fwconsole[81055]:  34100 [------------------------>---]
Aug 04 15:41:57 box.lan fwconsole[81055]:  34200 [------------>---------------]
Aug 04 15:41:57 box.lan fwconsole[81055]: Finished setting permissions
Aug 04 15:41:57 box.lan fwconsole[81055]: Unable to run Pre-Asterisk hooks, because Asterisk is already running on PID 79506 and has been running for 2 minutes, 27 seconds
Aug 04 15:41:57 box.lan fwconsole[81055]: Running Asterisk post from Core module
Aug 04 15:41:57 box.lan runuser[81178]: pam_unix(runuser:session): session opened for user asterisk(uid=998) by (uid=0)
Aug 04 15:41:57 box.lan runuser[81178]: pam_unix(runuser:session): session closed for user asterisk
Aug 04 15:41:57 box.lan fwconsole[81055]: Core FastAGI Server has already been running on PID 80547 for 8 seconds
Aug 04 15:41:57 box.lan systemd[1]: Finished FreePBX VoIP Server.
```

[iiab-diagnostics](https://github.com/iiab/iiab/blob/master/scripts/iiab-diagnostics.README.md) for this fresh install: http://sprunge.us/FlJ0QT?en

_[*] for sure more OS's & hardware combinations need to be tried!_

- PR #2896
- PR #2899

**Pull request merged**
