### PR TITLE
Proposed enhancements to PR #2499: Mint might need static mapping to Ubuntu [for MongoDB] + get real admitting we no longer support 11 distros/versions...to strengthen support for our 4 core OS's + revert to installing the latest Ansible

### PR DESCRIPTION
**Pull request by holta**
Building on and modifying @jvonau's PR #2499.

Thanks to @shanti-bhardwa's ongoing hard work, testing on Linux Mint 20.

Refs:
- PR #2482 'scripts/ansible: temp workaround (revert to Ansible 2.9.6) mitigating #2481'
- PR #2483 'Experimental IIAB support for Linux Mint 20 ?'
- PR #2493 'RFC Mongo2 [reinforce MongoDB on most distros, e.g. for Sugarizer]'
- PR #2495 'Various fixes [PostgreSQL, MongoDB for Sugarizer, OSM]'
- PR #2498 'Revert "use ansible_userspace_architecture for booted 64bit kernels a…'

### CODE REVIEW

**Comment by holta** [comment]
@jvonau personally I dislike hard-coding to particular distro versions e.g. Linux Mint 20, Raspbian 10, or whatever.  While I'm well aware Linux Mint 21 and Raspbian 11 will be a whole new ballgame!

Still, I find the idea of manufactured obsolescence distasteful, where we can plausibly avoid it anyway (:

**Comment by jvonau** [comment]
I find your petty meddling over the position of blank lines, the resulting clobbering the git history with rather bothersome petty changes annoying.

**Comment by jvonau** [comment]
You are really off base what other debian-10 distro maps to buster? so an old install with debian-9 is going to run buster packages? you would want to use ansible_distribution_release to map the available packages but what do I know.

**Comment by holta** [comment]
Code readability is not petty, quite the opposite in a community project especially, truth be told.

With all due respect to everyone trying to participate each in their own way.

**Comment by holta** [comment]
Debian 9 is not supported for 14 months now; it's time to let bygones be bygones and move forward (FWIW nobody asked for it in a long time).

**Comment by holta** [comment]
To be clear, hard-coding to a particular distro/version is sometimes the only way.  And we're all open to that kind of spaghetti coding of special cases...if that's truly necessary in certain areas.

**Comment by holta** [comment]
> Debian 9 is not supported for 14 months now; it's time to let bygones be bygones and move forward (FWIW nobody asked for it in a long time).

Not to blame Debian 9 in particular!

It's just one of many examples &mdash; where we so often up end supporting too many OS versions @ https://github.com/iiab/iiab/wiki/IIAB-Platforms &mdash; creating impressions we cannot possibly deliver on :/

So deprecating and pruning support for ancient/marginally used OS versions is really essential...somehow this "continual renewal" needs to be a very core part of our community's discipline.

As annoying as it is...to have distros changing on us constantly (grimace).

**Comment by jvonau** [comment]
cull scripts/local_facts.fact

**Comment by holta** [comment]
> scripts/local_facts.fact

That's an excellent idea...to start trimming https://github.com/holta/iiab/blob/mongo2/scripts/local_facts.fact#L25-L39 so folks get a grip on reality...this is almost 2021...not 2013 when Fedora 18 was released ;-)

**Comment by holta** [comment]
Smoke-test (appears!) successful on Debian 10.5 VM (using brand new Ansible 2.9.13 for good measure) but the following doesn't look entirely healthy?  @jvonau can you confirm if this is as it should be?  (Or good enough?)

> root@deb10-srv:~# systemctl status mongod
● mongod.service - MongoDB Database Server
   Loaded: loaded (/lib/systemd/system/mongod.service; disabled; vendor preset: enabled)
   Active: inactive (dead)
     Docs: https://docs.mongodb.org/manual
>
> Sep 02 15:11:11 box.lan systemd[1]: /lib/systemd/system/mongod.service:10: PIDFile= references path below legacy directory /var/run/, updating /var/run/mongodb/mongod.p
Sep 02 15:11:36 box.lan systemd[1]: /lib/systemd/system/mongod.service:10: PIDFile= references path below legacy directory /var/run/, updating /var/run/mongodb/mongod.p

**Comment by holta** [comment]
Also being smoke-tested (with default Ansible 2.9.6) on mint20-BIG-PR2501 = 10.8.0.22

**Comment by holta** [comment]
> Also being smoke-tested (with default Ansible 2.9.6) on mint20-BIG-PR2501 = 10.8.0.22

Success: installing this PR (BIG-sized IIAB) onto Linux Mint 20 completes, and http://10.8.0.22/sugarizer works.

Identical results to Debian 10.5 VM above:

i.e. the output of `systemctl status mongod` doesn't inspire confidence, but nor are there visible problems resulting?  (If any further tests of MongoDB or otherwise are advisable, please shout!)

**Comment by jvonau** [comment]
> Loaded: loaded (/lib/systemd/system/mongod.service; disabled; vendor preset: enabled)

That is the stock service file I believe what about `systemctl status mongodb`

**Comment by holta** [comment]
Output from Linux Mint 20: (mint20-BIG-PR2501 now at 10.8.0.38)

> root@box:~# systemctl status mongodb
● mongodb.service - High-performance, schema-free document-oriented database
     Loaded: loaded (/etc/systemd/system/mongodb.service; disabled; vendor preset: enabled)
     Active: active (running) since Wed 2020-09-02 20:22:53 EDT; 17min ago
    Process: 604 ExecStartPre=/usr/bin/iiab-mongodb-repair-if-no-lock (code=exited, status=0/SUCCESS)
   Main PID: 618 (mongod)
      Tasks: 34 (limit: 2278)
     Memory: 88.7M
     CGroup: /system.slice/mongodb.service
             └─618 /usr/bin/mongod -f /etc/mongod.conf
>
> Sep 02 20:22:53 box.lan systemd[1]: Starting High-performance, schema-free document-oriented database...
Sep 02 20:22:54 box.lan iiab-mongodb-repair-if-no-lock[604]: "mongod --repair" cannot run when /library/dbdata/mongodb/mongod.lock present.
Sep 02 20:22:53 box.lan systemd[1]: Started High-performance, schema-free document-oriented database.

**Pull request merged**
