### PR TITLE
Usbmount fixes

### PR DESCRIPTION
**Pull request by jvonau**
### Fixes Bug
#2277
Even thou usbmount contains a un-mount routine it is now ignored, use the service file to clean up the mountpoint.

### CODE REVIEW

**Comment by tim-moody** [comment]
on latest master neither poweroff or umount remove links in
/library/www/html/local_content/ on raspbian

**Comment by jvonau** [comment]
Using umount is not expected to work, mount did not create the symlink, usbmount did. Use `sudo  systemctl stop usbmount@dev-sda*` Powering down should remove the link I would think as stop usbmount@dev-sda1, stop usbmount@dev-sda would get run while shutting down. Haven't see any dead links lately.

**Comment by tim-moody** [comment]
and usb1 -> /media/usb1 can still appear in the mounted device

**Comment by jvonau** [comment]
might be a hanger-on from prior use.. check the date then try rm /media/usb1/usb1 yank and re-insert

**Comment by tim-moody** [comment]
> try rm /media/usb1/usb1 yank and re-insert

That's what I thought I did, but I was unable to reproduce. However if I rm /media/usbx/usbx, poweroff, and then power on with the usb still inserted I get the reported result

```
root@rpi-devel:~# ll /media/usb0/usb0
lrwxrwxrwx 1 root root 11 Mar 25 22:30 /media/usb0/usb0 -> /media/usb0

```

**Comment by jvonau** [comment]
> > try rm /media/usb1/usb1 yank and re-insert
> 
> That's what I thought I did, but I was unable to reproduce. However if I rm /media/usbx/usbx, poweroff, and then power on with the usb still inserted I get the reported result
> 
> ```
> root@rpi-devel:~# ll /media/usb0/usb0
> lrwxrwxrwx 1 root root 11 Mar 25 22:30 /media/usb0/usb0 -> /media/usb0
> ```

Interesting, rebooting is the reproducer, not really a change in prior behavior but still undesirable. Need to poke at it when I get a chance but way better than what it was.

**Comment by jvonau** [comment]
Wondering if the old workaround of [restarting udev](https://github.com/iiab/iiab/blob/master/roles/2-common/tasks/udev.yml) is maybe causing the errand symlink to appear. Can you try removing the symlink, `sudo systemctl disable udev-reload`, and reboot.

**Comment by tim-moody** [comment]
>  try removing the symlink, sudo systemctl disable udev-reload, and reboot.

unexpected

```
root@rpi-devel:~# systemctl status udev-reload
● udev-reload.service - Make sure udev is operating on RW disk
   Loaded: loaded (/etc/systemd/system/udev-reload.service; disabled; vendor preset: enabled)
   Active: inactive (dead)
root@rpi-devel:~# ll /media/usb0/usb0
lrwxrwxrwx 1 root root 11 Mar 26 12:09 /media/usb0/usb0 -> /media/usb0

```

**Comment by jvonau** [comment]
Got me stumped atm, usbmount's 70-usb-library files we provide and don't fiddle with the drive just the uppercase symlink in /library/www/html/local_content/... Something else is in the mix.

**Pull request merged**
