### PR TITLE
Lokole integration (for offline email)

### PR DESCRIPTION
**Pull request by veeara282**
See https://github.com/ascoderu/opwen-webapp/issues/37.

### CODE REVIEW

**Comment by holta** [comment]
Hi Lokole People!

FYI [IIAB 6.6](https://github.com/iiab/iiab/wiki/IIAB-6.6-Release-Notes) is approaching final freeze as its release is imminent in a few very short weeks: is there a very test plan (what should work, what's still experimental) and basic/clean documentation that can be made available to IIAB's community implementers ASAP now?

Or perhaps better to defer to [IIAB 6.7](https://github.com/iiab/iiab/milestone/4) later in 2018?

**Comment by veeara282** [comment]
Hi,

I think it's better to defer to IIAB 6.7.

**Comment by veeara282** [comment]
@holta is there a "staging" virtual machine we can use to test Lokole on an environment similar to IIAB?

**Comment by veeara282** [comment]
At this point you should be able to install and configure the Lokole web app by using the following command (or some variant of it):
```
ansible-playbook iiab/roles/lokole/tasks/install.yml --tags "install,configure"
```

**Comment by holta** [comment]
> Users provision their accounts through the web interface by visiting the endpoint /user/register.

As in http://box/lokole/user/register ?  A teacher/student-friendly URL like http://box/mail would also be great!

For comparison, @arky in Cambodia is right now working on enabling http://box/kolibri (#913) for the "successor" to Khan Academy Lite.

> Lokole doesn't currently support admin accounts, but we can add this functionality if necessary.

Most all IIAB apps/services have an administrative web account for the local operator, with username/password set to Admin/changeme initially.  What would Lokole's administrative account likely offer, if it turns out to be necessary?

Of course schools may well ask us how to disable accounts when threatening emails are sent.

Finally when running `cd /opt/iiab/iiab` and then `./runrole lokole` to reinstall Lokole, it'd be really great if the implementer/operator could specify whether everything (including Lokole data?) should be wiped (or not!)  Many IIAB apps/services try to offer a "wipe-it-all trigger file" for this purpose, as seen in the "left column" of http://FAQ.IIAB.IO Question 23 [("Can I upgrade or reinstall server apps?")](http://wiki.laptop.org/go/IIAB/FAQ#Can_I_upgrade_or_reinstall_server_apps.3F)

> Using the app should be fairly straightforward, and no configuration is required in local-only mode. If you need an FAQ entry, you can copy the text from /about.

Where is that within/near https://github.com/rgangela99/iiab/tree/lokole-integration/roles/lokole ?

> is there a "staging" virtual machine we can use to test Lokole on an environment similar to IIAB?

Not that I know of.  Most developers test again the latest pre-release (IIAB 6.6/master) which they install using our ["1-line installer"](http://download.iiab.io/6.6/).  The Raspbian OS on Raspberry Pi 3 (or 3 B+) is what most everyone uses in the field.  But you can also use this very same "1-line installer" to install IIAB 6.6/master much more quickly onto a VM (or old laptop/PC) running Ubuntu 18.04 or Debian 9.5 if you prefer!

**Comment by veeara282** [comment]
@holta I noticed that IIAB comes with what looks like [a single sign-on server](https://github.com/iiab/iiab/tree/master/roles/authserver). Do a lot of apps that ship with IIAB integrate with the SSO server, and if so, should we try to set up Lokole to do the same? I have some experience working with SSO systems, which I think would come in handy if we do this.

**Comment by holta** [comment]
> @holta I noticed that IIAB comes with what looks like a single sign-on server. Do a lot of apps that ship with IIAB integrate with the SSO server, and if so, should we try to set up Lokole to do the same? I have some experience working with SSO systems, which I think would come in handy if we do this.

This authserver (single sign-in) is not really used at present, sorry for the confusion!

**Comment by veeara282** [comment]
Can't promise anything, but we are almost done developing the Lokole role and plan to go into code review and QA soon. We might be able to finish by 6.6. What date is 6.6 planned to be released?

**Comment by holta** [comment]
> Can't promise anything, but we are almost done developing the Lokole role and plan to go into code review and QA soon. We might be able to finish by 6.6. What date is 6.6 planned to be released?

Great news!

If documentation is clean (understandable by non-programmer implementers & teachers) we can consider including this in the 6.6 Release Candidate arising in coming days, very likely this weekend?

**Comment by veeara282** [comment]
Sorry, there's no way we'll be able to QA this _and_ have documentation ready by this weekend. :stuck_out_tongue_winking_eye:

**Comment by veeara282** [comment]
@holta @rgangela99 I've created a staging server on DigitalOcean to mimic the Raspberry Pi environment, which we'll use for testing this PR. Its domain is `iiab-staging-01.aidan-fitz.com`. For now it's only us using it, but if anyone else wants to access the server, they should email me their SSH public key and I will set up an account for them.

**Comment by holta** [comment]
> I've created a staging server on DigitalOcean to mimic the Raspberry Pi environment, which we'll use for testing this PR. Its domain is iiab-staging-01.aidan-fitz.com.

Thanks much @aidan-fitz.

Can http://iiab-staging-01.aidan-fitz.com/lokole or similar be made public possibly, for basic user testing of account creation etc?

**Comment by holta** [comment]
> I've created a staging server on DigitalOcean to mimic the Raspberry Pi environment, which we'll use for testing this PR. Its domain is iiab-staging-01.aidan-fitz.com.

Hi @aidan-fitz & @rgangela99

Internet-in-a-Box 6.7 should be released in-or-around November, in just over a month: is it possible you can arrange for a site like http://iiab-staging-01.aidan-fitz.com/lokole or similar, so a few more people can try out Lokole account creation/deletion/etc prior to release?

(A couple-sentence introduction for non-technical teachers would also be really great, if you can hopefully suggest something for http://FAQ.IIAB.IO, Thanks much!)

**Comment by veeara282** [comment]
Hi Adam,

We're so sorry for dropping the ball on this. We can talk to Clemens about setting up a staging server for anyone to use, but I'm not sure how secure it would be.

What format should we use for the documentation? Just a README file in the role directory?

**Comment by holta** [comment]
> We can talk to Clemens about setting up a staging server for anyone to use, but I'm not sure how secure it would be.

Recommendation, if you so choose: setting up a for VM for testing can be extremely useful even it's taken down a week or two later, mitigating long-term security concerns.

> What format should we use for the documentation? Just a README file in the role directory?

A README.rst would be great if you can, similar to these IIAB apps/services/roles:

https://github.com/iiab/iiab/tree/master/roles/calibre-web
https://github.com/iiab/iiab/tree/master/roles/kolibri

I'm not sure if Python reStructuredText (.rst) is required or not!  RST being yet another markup language/syntax ([cheat sheet here](https://github.com/ralsina/rst-cheatsheet/blob/master/rst-cheatsheet.rst)) which is not terribly important.  What does matter is easing long-term maintenance/operations by serious implementers/integrators around the planet, who may not all speak English of course (but all benefit from understanding the intent and the system architecture of what you've created!)

_Separately let's try to write a couple sentences for non-technical teachers, to include in http://FAQ.IIAB.IO &mdash; so teachers never get stuck creating/deleting accounts/resetting student passwords etc (often it's best to have an actual educator write this, in their own words, if possible...this is only a couple sentences so easily done at the end!)_

**Comment by holta** [comment]
> A README.rst would be great if you can, similar to these IIAB apps/services/roles:
>
> https://github.com/iiab/iiab/tree/master/roles/calibre-web
> https://github.com/iiab/iiab/tree/master/roles/kolibri

ASIDE...Kolibri's above README was just cleaned up over the last hour (PR #1177).

**Comment by veeara282** [comment]
@holta Angela and I are going to set up the staging server tomorrow and will let you know when it's ready. We'll probably tear it down after we're finished but document whatever steps we take to build it so anyone in the project can replicate our work later.

**Comment by veeara282** [comment]
We did a huge rebase into the branch we're working in, so a lot of comments on this PR are hidden between commits rebased from the master branch. Sorry about that. :)

**Comment by veeara282** [comment]
I've started work on the `README.rst` for the Lokole role. What sections should it include?

**Comment by holta** [comment]
Please all who can help test Lokole's Offline Email @ http://iiab.eastus.cloudapp.azure.com/lokole/ !

Some highlights (what to test) are emerging at the top of Oct 19th's community/team call agenda @ http://minutes.iiab.io :+1: 
- Account creation and deletion
- Sending and receiving emails (local only)
- Known Issues (etc!)

**Comment by veeara282** [comment]
Hi, has anyone tested our staging server? Please leave comments on this PR if you have!

**Comment by holta** [comment]
@aidan-fitz would it be possible to rebase (or at least clean) this PR so that others can review it without getting lost, allowing this to be merged?

Currently there are "159 Files changed" shown at https://github.com/iiab/iiab/pull/894/files (the vast majority of which are completely unrelated to this PR, and should not be there).  Instead of 159, this number should be about 8-or-so files (judging from a quick count of those with "roles/lokole" in their path anyway!)

_(I'm personally no expert on git or GitHub, but if you need guidance here shout as @jvonau, @arky and/or others might have recommendations towards achieving a clean/readable rebase...)_

**Pull request closed without merging**
