### PR TITLE
minetest for rpi initial checkin [Minecraft clone]

### PR DESCRIPTION
**Pull request by tim-moody**
minetest server

### CODE REVIEW

**Comment by tim-moody** [comment]
smoke and functionally tested on rpi
hooks for other platforms not implemented
still needs to go into main plays
also needs udp port opened

**Comment by tim-moody** [comment]
ran iiab-install --reinstall on rpi and have working minetest server

**Comment by holta** [comment]
@tim-moody is a README.md or README.rst possible so we can link to this from [FAQ.IIAB.IO](http://FAQ.IIAB.IO) & [Release Notes](https://github.com/iiab/iiab/wiki#our-evolution) to encourage usage?  e.g.

https://github.com/iiab/iiab/blob/master/roles/lokole/README.rst
https://github.com/iiab/iiab/blob/master/roles/kolibri/README.rst
https://github.com/iiab/iiab/blob/master/roles/mosquitto/README.rst
https://github.com/iiab/iiab/blob/master/roles/nodered/README.rst

**Comment by tim-moody** [comment]
Tested on ubuntu 18 vm. Not expected to install, but also didn't break the playbook.

**Comment by holta** [comment]
Port 30000 was added to https://github.com/iiab/iiab/wiki/IIAB-Networking#list-of-open-ports--services

**Comment by tim-moody** [comment]
that link should mention that these are all defaults and can be changed during installation.

**Comment by holta** [comment]
> that link should mention that these are all defaults and can be changed during installation.

That's true for many IIAB apps.  Do help improve the documentation at https://github.com/iiab/iiab/wiki/IIAB-Networking#list-of-open-ports--services to say that if possible?

**Comment by holta** [comment]
From https://github.com/iiab/iiab/issues/1456#issuecomment-461187419:
> minetest is not a web app [...] a browser visiting [http://box:30000] will get nothing

@tim-moody can you make it explicit for new implementers & all, where the client software(s) is/are that you recommend?

(Within https://github.com/tim-moody/iiab/blob/minetest-rpi/roles/minetest/README.rst that should soon be clickable from http://FAQ.IIAB.IO item/number 9)

**Comment by holta** [comment]
@tim-moody will Ubuntu and/or Debian support possibly be added later?

(Or is this a huge task, not in our immediate future?)

**Comment by holta** [comment]
> [what] client software(s) [do] you recommend?

@tim-moody responded:
> https://www.minetest.net/downloads/
> but I confess the android doesn't work very well on my phone

Should a couple of these be included / downloadable-in-field from offline's IIAB?

I usually put a 64-bit and 32-bit Firefox in http://box/usb = http://box/local_content as schools often need this to rescue ancient / very offline Windows 7 & XP machines in the field.

There are so many different versions to choose from however, released on a quasi-weekly basis with new security updates etc, that each trip requires I download very different versions of Firefox for a partic language etc here: https://www.mozilla.org/en-US/firefox/all/

The DRM-free (EME-free) versions of Firefox are also available here:
https://ftp.mozilla.org/pub/firefox/releases/

**Pull request merged**
