### PR TITLE
Install bionic-or-focal version of ansible-base, depending on OS

### PR DESCRIPTION
**Pull request by holta**
Catches a few more OS/distro corner cases than PR #2521, tightens code, adds explanations/options for those wanting help uninstalling/installing Ansible (ansible-base) in other ways.

Refs: #2105, PR #2521, PR #2527, #2647, PR #2652, PR #2654, PR #2655, #2659, #2669, PR #2670, PR #2671, PR #2672, PR #2685, PR #2689.

### CODE REVIEW

**Comment by holta** [comment]
I'm not sure the `focal` version of ansible-base will be materially faster than the `bionic` version, but regardless this is good practice (real-world testing) to prepare us all for Debian 11 and RaspiOS 11 &mdash; both of which are very few months away now.

This PR has been tested on many different OS's i.e. a broad diversity of "Debuntu" Linux distros.

Many thanks to @jvonau for shining a bright light here, as a more modularized Ansible ( `ansible-base` + associated Ansible Collections ) finally starts to stabilize after ~2 years now!

**Comment by holta** [comment]
> if grep -q buster /etc/os-release /etc/debian_version; then

https://askubuntu.com/questions/445487/what-debian-version-are-the-different-ubuntu-versions-based-on/445496#445496 was useful in simplifying the above [Line 14 of scripts/ansible](https://github.com/iiab/iiab/blob/master/scripts/ansible#L14) FYI:

```
Ubuntu            Debian  
20.04  focal      bullseye/ sid   - 11
19.10  eoan       buster  / sid   - 10
19.04  disco      buster  / sid
18.10  cosmic     buster  / sid
18.04  bionic     buster  / sid
17.10  artful     stretch / sid   - 9
17.04  zesty      stretch / sid
16.10  yakkety    stretch / sid
16.04  xenial     stretch / sid
15.10  wily       jessie  / sid   - 8
15.04  vivid      jessie  / sid
14.10  utopic     jessie  / sid
14.04  trusty     jessie  / sid
13.10  saucy      wheezy  / sid   - 7
13.04  raring     wheezy  / sid
12.10  quantal    wheezy  / sid
12.04  precise    wheezy  / sid
11.10  oneiric    wheezy  / sid
11.04  natty      squeeze / sid   - 6
10.10  maverick   squeeze / sid
10.04  lucid      squeeze / sid
```

**Comment by holta** [comment]
CLARIF that both files need to be checked (/etc/os-release AND /etc/debian_version) for Debian release codenames.

This is a result of the fact that Debian and 32-bit RaspiOS remove the codename (e.g. `buster/sid`) from the /etc/debian_release file as part of the official release &mdash; thereafter (released versions of these OS's) contain a _number_ (e.g. `10.8` etc) in that file.

Whereas many other Debian-related distros (Ubuntu, Mint, 64-but RaspiOS) preserve the codename in /etc/debian_release even after release &mdash; but _don't_ mention the Debian codename in /etc/os-release

Recap: grep'ing across both files acts as a very conclusive check for buster-like distros (or bullseye-like distros, etc) both before release during testing and after release too!

**Comment by jvonau** [comment]
You do know that only Ubuntu and derivatives populate /etc/os-release with the variable "CODENAME=" this variable does not exist in the [Debian world](https://manpages.debian.org/testing/systemd/os-release.5.en.html). Now Debian 11 looks to be shipping [python 3.9](https://wiki.debian.org/Python)

**Comment by holta** [comment]
Debian 10 and RaspiOS 10 both contain this line in /etc/os-release:

`VERSION_CODENAME=buster`

Debian 11 pre-releases contain this line in /etc/os-release:

`PRETTY_NAME="Debian GNU/Linux bullseye/sid"`

So either way, we are fortunately well-covered — grep'ing for bullseye-instead-of-buster would likely work well — e.g. if that turns out to be necessary in future.

**Pull request merged**
