### PR TITLE
(1) Quick clean high-level roles: NGINX, Apache, network, OpenVPN, numbered roles (stages) & defaults_vars.yml (2) Add vars/ubuntu-20.yml for Ubuntu 20.04 pre-releases (3) Fix http://box/mediawiki

### PR DESCRIPTION
**Pull request by holta**
Also experimentally comments out tags within these high-level roles.

WIP.

### CODE REVIEW

**Comment by holta** [comment]
This PR experimentally installs NGINX prior to Apache, both in Stage 3-BASE-SERVER.

Smoke-tested on 192-u1910-desk-BIG-0113-PR2142 = 10.8.0.66

**Comment by jvonau** [comment]
Um.. the *_install were removed from 4-9 main.yml to be able to turn off the underling roles' service due to a mis-configured *_install line where the install occurred but now a mis-edit has turned the install off by mistake.

**Comment by holta** [comment]
> Um.. the *_install were removed from 4-9 main.yml to be able to turn off the underling roles' service due to a mis-configured *_install line where the install occurred but now a mis-edit has turned the install off by mistake.

As we solve this keep in mind there was way too much "random" inconsistency across all Stages 0-9 with many having include_role's & include_tasks's conditioned on `when: XYZ_install` and others not.

Let's clean this up in a separate PR to revise[*] or eliminate all "when: XYZ_install" clauses in Stage 0-9+network after we audit the main.yml's etc that they're calling, to be sure they're all doing the right thing, _even if_ XYZ_install & XYZ_enabled each have 1 of 4 different values {undefined, True, False, bogus value}.

Granted that's 4 * 4 = 16 possible situations across most of these these 38 include_tasks + 47 include_role (85 total) so let's make their outer conditions crystal clear for everyone to visually audit, trust and rely on:

- [Stage 0](https://github.com/iiab/iiab/blob/master/roles/0-init/tasks/main.yml) contains 3 include_tasks
- [Stage 1](https://github.com/iiab/iiab/blob/master/roles/1-prep/tasks/main.yml) contains 1 include_tasks + 3 include_role
- [Stage 2](https://github.com/iiab/iiab/blob/master/roles/2-common/tasks/main.yml) contains 11 include_tasks
- [Stage 3](https://github.com/iiab/iiab/blob/master/roles/3-base-server/tasks/main.yml) contains 2 include_tasks + 2 include_role
- [Stage 4](https://github.com/iiab/iiab/blob/master/roles/4-server-options/tasks/main.yml) contains 3 include_tasks + 7 include_role
- [Stage 5](https://github.com/iiab/iiab/blob/master/roles/5-xo-services/tasks/main.yml) contains 0 include_tasks + 3 include_role
- [Stage 6](https://github.com/iiab/iiab/blob/master/roles/6-generic-apps/tasks/main.yml) contains 0 include_tasks + 12 include_role
- [Stage 7](https://github.com/iiab/iiab/blob/master/roles/7-edu-apps/tasks/main.yml) contains 0 include_tasks + 8 include_role
- [Stage 8](https://github.com/iiab/iiab/blob/master/roles/8-mgmt-tools/tasks/main.yml) contains 0 include_tasks + 6 include_role
- [Stage 9](https://github.com/iiab/iiab/blob/master/roles/9-local-addons/tasks/main.yml) contains 1 include_tasks + 6 include_role
- [Stage network](https://github.com/iiab/iiab/blob/master/roles/network/tasks/main.yml) contains 17 include_tasks

_GOAL: Let's make it clear what code should never be run &mdash; and mandate that, at as high a level as possible &mdash; with crystal clear conditions (wrapped around whatever level of modularity we choose...)_

[*] another option might be to replace these `when: XYZ_install` clauses with something like `when: XYZ_install or XYZ_installed` making sure both vars are defined in advance, presumably in [default_vars.yml](https://github.com/iiab/iiab/blob/master/vars/default_vars.yml) ?

**Comment by holta** [comment]
Smoke-tested again, on Ubuntu 19.10

**Comment by jvonau** [comment]
You pushed this BS on the 4-9 meta roles after I told you the effects, re-introducing flawed logic... Where was the designs discussion on this massive change that others must suffer through? Now I have merge conflicts to resolve for real code improvements but my time is not worth anything.

**Comment by jvonau** [comment]
> > Um.. the *_install were removed from 4-9 main.yml to be able to turn off the underling roles' service due to a mis-configured *_install line where the install occurred but now a mis-edit has turned the install off by mistake.
> 
> As we solve this keep in mind there was way too much "random" inconsistency across all Stages 0-9 with many having include_role's & include_tasks's conditioned on `when: XYZ_install` and others not.
> 
> Let's clean this up in a separate PR to revise[*] or eliminate all "when: XYZ_install" clauses in Stage 0-9+network after we audit the main.yml's etc that they're calling, to be sure they're all doing the right thing, _even if_ XYZ_install & XYZ_enabled each have 1 of 4 different values {undefined, True, False, bogus value}.
> 
> Granted that's 4 * 4 = 16 possible situations across most of these these 38 include_tasks + 47 include_role (85 total) so let's make their outer conditions crystal clear for everyone to visually audit, trust and rely on:
> 
>     * [Stage 0](https://github.com/iiab/iiab/blob/master/roles/0-init/tasks/main.yml) contains 3 include_tasks
> 
>     * [Stage 1](https://github.com/iiab/iiab/blob/master/roles/1-prep/tasks/main.yml) contains 1 include_tasks + 3 include_role
> 
>     * [Stage 2](https://github.com/iiab/iiab/blob/master/roles/2-common/tasks/main.yml) contains 11 include_tasks
> 
>     * [Stage 3](https://github.com/iiab/iiab/blob/master/roles/3-base-server/tasks/main.yml) contains 2 include_tasks + 2 include_role
> 
>     * [Stage 4](https://github.com/iiab/iiab/blob/master/roles/4-server-options/tasks/main.yml) contains 3 include_tasks + 7 include_role
> 
>     * [Stage 5](https://github.com/iiab/iiab/blob/master/roles/5-xo-services/tasks/main.yml) contains 0 include_tasks + 3 include_role
> 
>     * [Stage 6](https://github.com/iiab/iiab/blob/master/roles/6-generic-apps/tasks/main.yml) contains 0 include_tasks + 12 include_role
> 
>     * [Stage 7](https://github.com/iiab/iiab/blob/master/roles/7-edu-apps/tasks/main.yml) contains 0 include_tasks + 8 include_role
> 
>     * [Stage 8](https://github.com/iiab/iiab/blob/master/roles/8-mgmt-tools/tasks/main.yml) contains 0 include_tasks + 6 include_role
> 
>     * [Stage 9](https://github.com/iiab/iiab/blob/master/roles/9-local-addons/tasks/main.yml) contains 1 include_tasks + 6 include_role
> 
>     * [Stage network](https://github.com/iiab/iiab/blob/master/roles/network/tasks/main.yml) contains 17 include_tasks
> 
> 
> _GOAL: Let's make it clear what code should never be run — and mandate that, at as high a level as possible — with crystal clear conditions (wrapped around whatever level of modularity we choose...)_
> 
> [*] another option might be to replace these `when: XYZ_install` clauses with something like `when: XYZ_install or XYZ_installed` making sure both vars are defined in advance, presumably in [default_vars.yml](https://github.com/iiab/iiab/blob/master/vars/default_vars.yml) ?

First off 0-3 stages are intended to contain what is the base install, exclusive of most configuration files that could be altered/dis|enabled in the field. These stages contain the core programs, dnsmasq, apache, nginx and mysql, these are not really optional.

Stages 4-9 where the roles are conditioned with `*_install_ True` needs to be altered to be `*_install: True or *_installed is defined` for all the roles you modified, this is a regression in logic. Otherwise the above noted mis-edit of *_install to False after installation would not be caught causing enable-or-disable.yml never be run to turn off/on the underling service.

**Comment by holta** [comment]
> Stages 4-9 where the roles are conditioned with *_install_ True needs to be altered to be *_install: True or *_installed is defined for all the roles you modified

I greatly prefer not to support broken [/etc/iiab/local_vars.yml](http://wiki.laptop.org/go/IIAB/FAQ#What_is_local_vars.yml_and_how_do_I_customize_it.3F) files.  Blocking (failing intentionally) is a better strategy in my opinion, so as not bury & paper over a deeper problem.  Hence these loud warnings:

https://github.com/iiab/iiab/blob/master/vars/default_vars.yml#L7-L8
https://github.com/iiab/iiab/blob/master/vars/local_vars_min.yml#L7-L8
https://github.com/iiab/iiab/blob/master/vars/local_vars_medium.yml#L7-L8
https://github.com/iiab/iiab/blob/master/vars/local_vars_big.yml#L7-L8

But we could strengthen this enforcement by adding better error messaging &mdash; e.g. active Ansible logic to tell the operator where their local_vars.yml erroneously contains `XYZ_install: False` and `XYZ_enabled: True`

As a precaution in case automated-manipulation of local_vars.yml screws up?

**Comment by jvonau** [comment]
How does that help if the uses does the edit as '# *_install: True'? Now add the fact 'save configuration' will wipe out the #'ed variable from local_vars like it was not there.

**Pull request merged**
