### PR TITLE
Apache2 Reverse proxy subdirectory /kolibri

### LINKED ISSUE #913: http://box/kolibri should work (not just http://box:8009)
Thanks @arky for investigating if you can!

When Kolibri works as part of IIAB, it is available at http://box:8089 but unfortunately not at http://box/kolibri

I'd like to update http://FAQ.IIAB.IO Item 3 ("What can I do with E-books and Internet-in-a-Box?") with much friendlier info on Kolibri teachers, in coming days if possible~

### PR DESCRIPTION
**Pull request by arky**
### Fixes Bug

Fixes #913 
https://github.com/iiab/iiab/issues/913

### Description of changes proposed in this pull request.

Better handling of top level URI rewrites in Kolibri. Introduces a new environmental variable KOLIBRI_URL_PATH_PREFIX in Kolibri systemd unit and Kolibri Apache2 configuration file to handle vhost.  

### Smoke-tested in operating system.
Ubuntu Cosmic
Debian Sid

### Mention a team member for further information or comment using @ name
@holta

### CODE REVIEW

**Comment by holta** [comment]
Tested on Ubuntu 18.04

Needs testing on Raspbian!

**Comment by holta** [comment]
Amazing, thank you @arky !

**Comment by arky** [comment]
Thanks for the merge @holta .  Kudos are in order for @learningequality/kolibri team for the feature.

**Comment by holta** [comment]
Thanks all go to you @arky 

Question: any idea why Kolibri is failing on Debian Buster @ #1387 ?

**Comment by arky** [comment]
@holta Any logs or errors from Kolibri Systemd unit? My guess is Kolibri migrations took a lot of time to complete or failed.

**Comment by holta** [comment]
> @holta Any logs or errors from Kolibri Systemd unit? My guess is Kolibri migrations took a lot of time to complete or failed.

The Kolibri playbook completed without obvious errors, but possibly I missed something?

Any quick suggestions for where I should look for error messages or likely/relevant log file?

As Learning Equality's Benjamin Bach also requested :)

**Pull request merged**
