### PR TITLE
Apache service [let's try to disable apache2 systemd service across the board, when pbx doesn't need it, even on desktop OS's like Debian 11!]

### PR DESCRIPTION
**Pull request by jvonau**
### Fixes bug:
fbf7141 is to address https://github.com/iiab/iiab/pull/2850#issuecomment-882093007
### Description of changes proposed in this pull request:
Disable apache for the next boot if installed.

### CODE REVIEW

**Comment by holta** [comment]
This is somewhat aggressive e.g. if desktop/graphical versions of Debian 11 had Apache enabled for a reason.

But now's the right time to see if Apache can be turned off, across the board during IIAB installs, without too much blowback.

Then if desktop/graphical OS folks complain too much that they needed Apache enabled for one reason or another, we can always reverse this later in coming months, if absolutely necessary.

- PR #2929

**Comment by jvonau** [comment]
or supply the ports file to run apache on an alternate port or entertain the idea of running nginx on another port #2933

**Comment by jvonau** [comment]
> This is somewhat aggressive e.g. if desktop/graphical versions of Debian 11 had Apache enabled for a reason.
>

As it was without this PR, nginx and apache would of been in a race for control of port 80 upon boot, only one of them can win that race. The user wanted 'iiab', the user gets the intended layout of 'iiab'.

**Comment by holta** [comment]
> As it was without this PR, nginx and apache would of been in a race for control of port 80 upon boot, only one of them can win that race. The user wanted 'iiab', the user gets the intended layout of 'iiab'.

Good point.  We can slog thru those boot-time race conditions / timing issues if really nec.

But best to avoid them entirely if possible.

Indeed our multi-month efforts to disentangle years of legacy code no longer in use had more than one purpose &mdash; as outlined here:

- PR #2850

**Pull request merged**
