### PR TITLE
Add local_tmp permissions for TravisCI builds

### PR DESCRIPTION
**Pull request by arky**
Add local_tmp variable to ansible.cfg in travis.yml file. 

AnsibleError: Unable to create local directories(/root/.ansible/tmp): [Errno 13] Permission denied: '/root/.ansible'

### Fixes Bug
[Travis CI] Build failing: Permission denied when running Ansible #1212

### Description of changes proposed in this pull request.
Resolves ansible tmp directory permissions errors inside TravisCI build infrastructure. 

### Smoke-tested in operating system.
TravisCI 

### Mention a team member for further information or comment using @ name
@holta @aidan-fitz

### CODE REVIEW

**Comment by holta** [comment]
@aidan-fitz is this safe/ready to merge?

**Comment by veeara282** [comment]
It failed again, but on a different error: [output](https://travis-ci.org/rgangela99/iiab/builds/440440611)

```
ERROR! Syntax Error while loading YAML.
  found unacceptable key (unhashable type: 'AnsibleMapping')

The error appears to have been in '/home/travis/build/rgangela99/iiab/roles/calibre/defaults/main.yml': line 22, column 19, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


calibre_deb_url: {{ iiab_download_url }}    # http://download.iiab.io/packages
                  ^ here
We could be wrong, but this one looks like it might be an issue with
missing quotes.  Always quote template expression brackets when they
start a value. For instance:

    with_items:
      - {{ foo }}

Should be written as:

    with_items:
      - "{{ foo }}"
```

**Comment by veeara282** [comment]
LGTM :+1:

**Comment by holta** [comment]
@jvonau  & @tim-moody can you tell why 'pip install ansible' is being used in /opt/iiab/iiab/.travis.yml here?  Instead of running scripts/ansible ?

**Comment by tim-moody** [comment]
@holta I didn't write the install script or the travis playbook, so I have no idea.

**Comment by holta** [comment]
@arky & @aidan-fitz why is 'pip install ansible' being used in /opt/iiab/iiab/.travis.yml here?

Instead of running /opt/iiab/iiab/scripts/ansible as the ["official" IIAB install instructions](https://github.com/iiab/iiab/wiki/IIAB-Installation#do-everything-from-scratch) ask for?
```
cd /opt/iiab/iiab/scripts/
./ansible
# Installs latest Ansible from PPA
```
We've had so much trouble over the years with pip installs of Ansible (and pip installs of KA Lite, etc!) that I'm trying to understand better:
- what's happening here / what sequence is intended
- how we can guarantee Ansible will not be installed twice (via pip, and via apt, etc)

**Comment by arky** [comment]
@holta I think there are some misconceptions, I will try to explain here. Travis CI is not same as installing a Internet in a box. There is no need to use the install scripts to detect the OS and instal the right version of ansible. 

Travis CI is continuous integration that is built on virtual machines (in this case ubuntu trusty). It is designed to run fast and multiple instances in parallel (testing multiple combination of ansible).  It is intended for developers to catch symantec, syntactic errors and running test cases. 

Right now, We are only doing minimal ansible linting and ansible syntax on limited versions of ansible. In future, when code quality improves or we get a new developer. We can write new tests using molcule or similar testing framework to write comprehensive tests. 

Please kindly merge this simple fix.

**Pull request merged**
