### PR TITLE
enable aarch64 in kiwix, disable stem.php

### PR DESCRIPTION
**Pull request by georgejhunt**
These changes were required to install on ubuntu arm64 on rpi4. 

Stem change is temporary until we analyze further

### CODE REVIEW

**Comment by tim-moody** [comment]
stem is already compiled

**Comment by tim-moody** [comment]
could make following changes to roles/www_back_end/tasks/php-stem.yml

```
# Fixes search @ http://box/modules/es-wikihow (popular with Spanish youth)
# Source code: http://download.iiab.io/packages/php-stem.src.tar
# June 2018 debugging & compilation thanks to Tim Moody & George Hunt
# Original bug: https://github.com/iiab/iiab/issues/829

- name: Unarchive http://download.iiab.io/packages/php{{ php_version }}-stem.rpi.tar to / (rpi)
  unarchive:
    src: http://download.iiab.io/packages/php{{ php_version }}-stem.rpi.tar
    dest: /
    owner: root
    group: root
    #mode: ????
    remote_src: yes
  when: ansible_machine == "armv7l"

- name: Unarchive http://download.iiab.io/packages/php{{ php_version }}-stem.aarch64.tar to / (rpi)
  unarchive:
    src: http://download.iiab.io/packages/php{{ php_version }}-stem.aarch64.tar
    dest: /
    owner: root
    group: root
    #mode: ????
    remote_src: yes
  when: ansible_machine == "aarch64"
  
- name: Unarchive http://download.iiab.io/packages/php{{ php_version }}-stem.x64.tar to / (x64)
  unarchive:
    src: http://download.iiab.io/packages/php{{ php_version }}-stem.x64.tar
    dest: /
    owner: root
    group: root
    #mode: ????
    remote_src: yes
  when: ansible_machine == "x86_64"

# link to php done in roles/nginx/tasks/install.yml when php-fpm is installed

# Not sure what to do for apache, so do nothing for now

# The following are probably no longer true 2020-01-25
# Presumably fails on Debian 8 & 10?
# Fails on Debian i686 as of 2018-08-07: https://github.com/iiab/iiab/issues/983
# Fails on Ubuntu 18.04 as of 2018-07-28: https://github.com/iiab/iiab/issues/829

```

**Comment by georgejhunt** [comment]
Is there some way to highlight the changes requested? I'm not very good at
doing a diff on two separate browser instances by eyeball.

**Comment by tim-moody** [comment]
it's a direct replacement

**Comment by jvonau** [comment]
@holta the roles/www_back_end -> roles/www_base move broke this PR can you fix it?

**Comment by holta** [comment]
> @holta the roles/www_back_end -> roles/www_base move broke this PR can you fix it?

@georgejhunt can you resolve this merge conflict, per @jvonau's request?

Context: @tim-moody asked that roles/www_back_end be renamed to roles/www_base (which is now done).

**Pull request closed without merging**
