### PR TITLE
Calibre-Web (eBook Library) w/ experimental support for video/audio/images

### PR DESCRIPTION
**Pull request by holta**
There will be bugs initially (with large or long videos especially, and other glitches!) but it's time to start expanding community testing building on @deldesir's and others' hard work here!

IN SHORT: IIAB's experimental new version of Calibre-Web also lets everyday IIAB implementers add the YouTube and Vimeo videos they most need (as well as local videos, e.g. from teachers' phones) in support of indigenous/local learning libraries:

- https://github.com/iiab/calibre-web/wiki
- https://github.com/iiab/calibre-web

Related:

- PR #3676
- PR #3677
- PR #3689

### CODE REVIEW

**Comment by holta** [comment]
Thanks @deldesir, @EMG70 & All for reviewing & suggesting changes after this is merged — in support of the highly-reliable grassroots-centric libraries that so many people are asking for!

**Review by deldesir — COMMENTED** [review]
Looks good to me.

**Comment by holta** [comment]
Tested with a MEDIUM-sized IIAB install, which took a total of 24 minutes to install onto a VM, running Ubuntu 24.04 pre-release:

iiab-diagnostics: http://sprunge.us/FWiYyv

**Comment by holta** [comment]
Testing Method...

1. Create file medium.yml, with these exact contents:

```
runcmd:
  - mkdir /etc/iiab
  - curl https://raw.githubusercontent.com/iiab/iiab/master/vars/local_vars_medium.yml > /etc/iiab/local_vars.yml
  - curl iiab.io/risky.txt | bash &
```

2. Create the VM:

```
multipass launch 24.04 -n u24-medium -m 2G -d 20G --cloud-init medium.yml [--bridged]
```

3. Log into VM:

```
multipass shell u24-medium
```

4. Monitor install progress: (look for "INTERNET-IN-A-BOX (IIAB) SOFTWARE INSTALL IS COMPLETE" which should appear about 20-to-40 min later!)

```
sudo su -
tail -f /var/log/cloud-init-output.log
```

**Pull request merged**
