### PR TITLE
usball - show entire USB stick/drive content (at http://box/usb)

### PR DESCRIPTION
**Pull request by georgejhunt**
### Description of changes proposed in this pull request.
Mount the root directory of a USB stick, and display 

### Smoke-tested in operating system.
No

### CODE REVIEW

**Comment by holta** [comment]
Proposed Implementation for #695 "Option to show entire USB stick/drive content (at http://box/usb)"

**Comment by holta** [comment]
@jvonau & @tim-moody plz review if you have time, so we can fast-track this for Haiti and IIAB 6.5 if poss!

**Comment by jvonau** [comment]
Looks ok for a fresh install but reinstalls will need to pass through 1-prep again to pickup the new variables. 
edit this part I was mistaken -> and install the new iiab-showall files.

**Comment by georgejhunt** [comment]
Yes, that's an easy change

**Comment by jvonau** [comment]
looks fine

**Comment by holta** [comment]
> looks fine

Great news.  Can I merge this today, or does it require further testing?

(We can and should test on Ubuntu etc after merging...)

**Comment by holta** [comment]
This PR initially works (on Ubuntu 16.04 more than Raspbian) but has 3 serious issues:

1) `iiab-usb-lib-show-all-off` works until reboot, but this can revert to showing stick's entire contents after reboot on RPi (whereas it works properly on Ubuntu 16.04!)

2) `iiab-usb-lib-show-all-on` fails on RPi when this directory (quickly) becomes full of stale links as follows:
```
root@box:~# ls -l /library/www/html/local_content/
lrwxrwxrwx 1 root root       15 Apr  2 18:05 USB0 -> /media/usb0/usb
lrwxrwxrwx 1 root root       15 Apr  2 17:59 USB1 -> /media/usb1/usb
lrwxrwxrwx 1 root root       15 Apr  2 17:36 USB2 -> /media/usb2/usb
lrwxrwxrwx 1 root root       15 Apr  2 17:37 USB3 -> /media/usb3/usb
```
Whereas the above soft links are (usually!) deleted properly on Ubuntu 16.04, when a USB stick is removed.  Result: whereas Ubuntu displays complete stick contents, Raspbian increasingly fails to do so (as newly inserted USB sticks are usually assigned to one of the above 4 pre-existing & erroneous "just show teacher subfolder" links).

3. Broken links of the form USB0 -> /media/usb0 (while they do exist, to show entire USB stick contents) are unfortunately displayed by Apache to students/users (at http://box/usb) even after the stick was removed.

**Comment by holta** [comment]
> 1) `iiab-usb-lib-show-all-off` works until reboot, but this can revert to showing stick's entire contents after reboot on RPi (whereas it works properly on Ubuntu 16.04!)

@jvonau found an RPi workaround: remove all USB sticks/drives before running `iiab-usb-lib-show-all-off` (the correct behavior should then persist after reboots).

**Comment by holta** [comment]
> @jvonau found an RPi workaround: remove all USB sticks/drives before running `iiab-usb-lib-show-all-off` (the correct behavior should then persist after reboots).

Should we print a warning on-screen, asking the operator to "Please remove all USB sticks/drives before (re)running this command" for both `iiab-usb-lib-show-all-off` and `iiab-usb-lib-show-all-on` ?

(Or should these 2 commands perhaps forcibly unmount all USB sticks/drives before proceeding?)

**Comment by holta** [comment]
@jvonau noticed problematic 755/751 permissions here &mdash; that may cause stale links:
```
root@box:/etc/usbmount# ls -l *
-rw-r--r-- 1 root root 2815 Apr  3 22:41 usbmount.conf

mount.d:
total 8
-rwxr-xr-x 1 root root 1447 Aug  8  2011 00_create_model_symlink
-rwxr-x--x 1 root root 1417 Apr  3 22:41 70-usb-library

umount.d:
total 8
-rwxr-xr-x 1 root root 710 Aug  8  2011 00_remove_model_symlink
-rwxr-x--x 1 root root 651 Apr  3 22:41 70-usb-library
```

**Comment by holta** [comment]
Thanks @georgejhunt & @jvonau who made this merge happen per collective decision during our community/team call @ http://minutes.iiab.io :+1: 

Summary: https://github.com/georgejhunt/iiab/commit/170dc0d84338407d2377132f88daf1754559604c removes `udevadm trigger -t subsystems -s usb -c add` (from `iiab-usb-lib-show-all-off` and `iiab-usb-lib-show-all-on`) allowing us to better understand usbmount's permission & related issues...

**Pull request merged**
