### PR TITLE
Install latest Calibre 3.x+ on all Linuxes (needs work!)

### PR DESCRIPTION
**Pull request by holta**
Tested on Ubuntu 16.04 LTS.

Needs testing on other OS's.

### CODE REVIEW

**Comment by holta** [comment]
Details on the **completely rewritten** Calibre 3 Content Server:

https://calibre-ebook.com/new-in/twelve
https://manual.calibre-ebook.com/server.html
https://manual.calibre-ebook.com/generated/en/calibre-server.html (new flags)
https://manual.calibre-ebook.com/generated/en/calibredb.html (to add books)
https://manual.calibre-ebook.com/faq.html

**Comment by holta** [comment]
Oops I _thought_ calibre-server 3.x would have been published on ARM (Raspbian) 5 months later but I was wrong!  The official builds anyway seem to be all i686 and x86_64 here:

https://calibre-ebook.com/signatures/

I can easily wrap the new Calibre 3.x stuff in "when: not is_rpi" conditional(s) for Big Iron etc.  Begging the question: is legacy calibre-server 2.75.1 still good enough for Raspbian _??_

It will be hard to beat to community action that revolves around Calibre.  But might there possibly be any basic/alternative book servers for RPi already viable, e.g. post-Pathagar such as COPS etc?
- https://github.com/seblucas/cops
- http://blog.slucas.fr/en/oss/calibre-opds-php-server

**Comment by jvonau** [comment]
Debian-9VM 
> 05:40:56 ==> debian: TASK [calibre : Check if /library/calibre/metadata.db exists] ******************
05:40:56 ==> debian: ok: [127.0.0.1]
05:40:56 ==> debian: 
05:40:56 ==> debian: TASK [calibre : Incorporate sample book into Calibre DB (mandatory since Calibre 3.x)] ***
05:40:57 ==> debian: fatal: [127.0.0.1]: FAILED! => {"changed": true, "cmd": "calibredb add /library/downloads/Metamorphosis-jackson.epub --with-library /library/calibre", "delta": "0:00:00.170349", "end": "2017-11-16 13:40:57.319762", "failed": true, "msg": "non-zero return code", "rc": 1, "start": "2017-11-16 13:40:57.149413", "stderr": "Traceback (most recent call last):\n  File \"site.py\", line 75, in main\n  File \"site-packages/calibre/db/cli/main.py\", line 17, in <module>\n  File \"site-packages/calibre/db/legacy.py\", line 18, in <module>\n  File \"site-packages/calibre/db/backend.py\", line 33, in <module>\n  File \"site-packages/calibre/utils/img.py\", line 18, in <module>\nImportError: libGL.so.1: cannot open shared object file: No such file or directory", "stderr_lines": ["Traceback (most recent call last):", "  File \"site.py\", line 75, in main", "  File \"site-packages/calibre/db/cli/main.py\", line 17, in <module>", "  File \"site-packages/calibre/db/legacy.py\", line 18, in <module>", "  File \"site-packages/calibre/db/backend.py\", line 33, in <module>", "  File \"site-packages/calibre/utils/img.py\", line 18, in <module>", "ImportError: libGL.so.1: cannot open shared object file: No such file or directory"], "stdout": "", "stdout_lines": []}
05:40:57 ==> debian: 	to retry, use: --limit @/opt/iiab/iiab/iiab-stages.retry

ImportError: libGL.so.1: cannot open shared object file:   No such file or directory     
Did Ubuntu-16 have a graphical desktop installed? OpenGL is an undeclared dependence maybe?

**Comment by holta** [comment]
fyi on @deldesir's Ubuntu 17.10 (with the [original Calibre install technique](https://github.com/iiab/iiab/blob/master/roles/calibre/tasks/main.yml#L15-L21), prior to this PR #530) we observe:
```
root@box:~# apt -a list calibre
Listing... Done
calibre/artful,artful,now 3.7.0+dfsg-2 all [installed]

root@box:~# locate libGL.so.1
/usr/lib/x86_64-linux-gnu/mesa/libGL.so.1
/usr/lib/x86_64-linux-gnu/mesa/libGL.so.1.2.0
```

**Comment by holta** [comment]
@jvonau found Calibre 3.7.0 in BOTH these places, raising possibly hope for Raspbian!?

* https://packages.ubuntu.com/source/artful/calibre
* https://packages.ubuntu.com/artful/armhf/calibre-bin/download

"pool/universe/c/calibre/   on a mirror"

See Also Calibre 3.10 someone's trying to prep for Raspbian:

* http://archive.raspbian.org/raspbian/pool/main/c/calibre/

**Comment by holta** [comment]
@georgejhunt, @tim-moody & All:

No such luck trying to use the above to install Calibre 3.7.0 onto RPi3!

What We Tried: `wget http://launchpadlibrarian.net/335759103/calibre-bin_3.7.0+dfsg-2_armhf.deb` worked, as listed @ https://launchpad.net/ubuntu/artful/armhf/calibre-bin

But unfortunately `dpkg -i calibre-bin_3.7.0+dfsg-2_armhf.deb` then fails as follows: (on Raspbian Lite 2017-09-07, updated using apt, on RPi3)
```
root@box:~# dpkg -i calibre-bin_3.7.0+dfsg-2_armhf.deb
(Reading database ... 84883 files and directories currently installed.)
Preparing to unpack calibre-bin_3.7.0+dfsg-2_armhf.deb ...
Unpacking calibre-bin (3.7.0+dfsg-2) over (2.75.1+dfsg-1) ...
dpkg: dependency problems prevent configuration of calibre-bin:
 calibre-bin depends on libfontconfig1 (>= 2.11.94); however:
  Version of libfontconfig1:armhf on system is 2.11.0-6.7.
 calibre-bin depends on libpodofo0.9.5; however:
  Package libpodofo0.9.5 is not installed.
 calibre-bin depends on libqt5gui5 (>= 5.9.0); however:
  Version of libqt5gui5:armhf on system is 5.7.1+dfsg-3+rpi1.
 calibre-bin depends on libssl1.0.0 (>= 1.0.0); however:
  Package libssl1.0.0 is not installed.
 calibre-bin depends on qtbase-abi-5-9-0; however:
  Package qtbase-abi-5-9-0 is not installed.

dpkg: error processing package calibre-bin (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 calibre-bin
```

**Comment by holta** [comment]
@jvonau discovered some folks are getting the very latest Calibre 3.x (3.12.0+dfsg-1) to work on Debian:

https://tracker.debian.org/pkg/calibre
https://bugs.debian.org/cgi-bin/pkgreport.cgi?maint=preining%40debian.org

This is critically important to getting most/all IIAB OS's on board with calibre-server 3.x when we can soon (if armhf on Raspbian is hopefully possible!?) as 3.x is a complete rewrite (as mentioned above @ https://github.com/iiab/iiab/pull/530#issuecomment-344753747) released 2017-06-16.

Additional details: https://calibre-ebook.com/whats-new

**Comment by holta** [comment]
Here is the error when trying to install Calibre's [linux-installer.py](https://github.com/kovidgoyal/calibre/blob/master/setup/linux-installer.py) onto a clean install of Raspbian 2017-09-07 with all updates.  (@jvonau suggested starting with Raspbian Desktop to reduce dependency problems with X Windows and OpenGL)

```
root@raspberrypi:~# ./linux-installer.py
Installing to /opt/calibre
Downloading tarball signature securely...
Will download and install calibre-3.12.0-i686.txz
                      Downloading calibre-3.12.0-i686.txz
100% [======================================================================]
                                                                                Downloaded 61979060 bytes
Checking downloaded file integrity...
Extracting files to /opt/calibre ...
Extracting application files...
Traceback (most recent call last):
  File "./linux-installer.py", line 736, in <module>
    main()
  File "./linux-installer.py", line 726, in main
    run_installer(install_dir, isolated, bin_dir, share_dir)
  File "./linux-installer.py", line 687, in run_installer
    subprocess.call(pi)
  File "/usr/lib/python2.7/subprocess.py", line 168, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1024, in _execute_child
    raise child_exception
OSError: [Errno 8] Exec format error
```

**Comment by jvonau** [comment]
> Downloading calibre-3.12.0-i686.txz
OSError: [Errno 8] Exec format error

wrong arch

**Comment by holta** [comment]
Here is one attempt to get calibre-server 3.12 to possibly run on RPi (?!) thanks to @jvonau &mdash; http://box:8080 shows:
```
500 Internal Server Error
The server encountered an unexpected condition which prevented it from fulfilling the request.
Powered by CherryPy 3.5.0 
```
Leading to:
```
root@box:~# /usr/bin/calibre-server --daemonize --log=/var/log/calibre.log --pidfile=/var/run/calibre.pid --port=8080 /library/calibre
Traceback (most recent call last):
  File "/usr/bin/calibre-server", line 20, in <module>
    sys.exit(main())
  File "/usr/lib/calibre/calibre/srv/standalone.py", line 207, in main
    server = Server(libraries, opts)
  File "/usr/lib/calibre/calibre/srv/standalone.py", line 66, in __init__
    self.handler = Handler(libraries, opts)
  File "/usr/lib/calibre/calibre/srv/handler.py", line 197, in __init__
    module = import_module('calibre.srv.' + module)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/lib/calibre/calibre/srv/books.py", line 18, in <module>
    from calibre.srv.render_book import RENDER_VERSION
  File "/usr/lib/calibre/calibre/srv/render_book.py", line 24, in <module>
    from calibre.ebooks.oeb.polish.container import Container as ContainerBase
  File "/usr/lib/calibre/calibre/ebooks/oeb/polish/container.py", line 49, in <module>
    from calibre.ebooks.oeb.polish.parsing import parse as parse_html_tweak
  File "/usr/lib/calibre/calibre/ebooks/oeb/polish/parsing.py", line 12, in <module>
    import html5_parser
  File "/usr/lib/python2.7/dist-packages/html5_parser/__init__.py", line 25, in <module>
    raise ImportError('Your version of lxml is too old, version 3.8.0 is minimum')
ImportError: Your version of lxml is too old, version 3.8.0 is minimum
```

**Comment by jvonau** [comment]
Initial attempt to install 3.12 from debian on the rpi used the below to minimize the number of packages that would be drawn from testing and unstable resulted in the above error 
> add testing 
apt update <-  note the missing key number
add key  https://raspberrypi.stackexchange.com/questions/12258/where-is-the-archive-key-for-backports-debian-org  [Insert here your missing key ID] 
apt update
apt install libqt5core5a                  <- updates calibre-bin to 3.10
add unstable | disable testing
apt update
apt install calibre                          <-  updates both calibre-bin calibre to 3.12
disable unstable
apt update

After updating python-lxml to 4.1 (due to missing dependency) with
> add testing
apt update
apt install python-lxml
disable testing
apt update

The above error went away.

**Comment by jvonau** [comment]
adding python-lxml to the apt install libqt5core5a line would save the last step

**Comment by holta** [comment]
Led to #539 & #541 !

**Pull request closed without merging**
