### PR TITLE
BUGFIX Usbmnt2 [usbmount_0.0.14.1_all.deb -> usbmount_0.0.22_all.deb on Debian]

### PR DESCRIPTION
**Pull request by jvonau**

### CODE REVIEW

**Comment by holta** [comment]
Related: #2422 "Test IIAB 7.2 pre-releases on 64-bit Raspbian (renamed to Raspberry Pi OS / RaspiOS)"

**Comment by holta** [comment]
Which OS tests are most needed, to verify this PR?

**Comment by jvonau** [comment]
none really, just moving the package install locations the variables are more or less the same. Debian variants use the RaspiOS provided package. Ubuntu variants use what comes with the OS. Current installs are unaffected with the use of 'installed' flag.

**Comment by holta** [comment]
Thanks @floydianslips who is now test-installing this on 32-bit RaspiOS &mdash; to verify that http://box/usb actually works!

(i.e. installing MEDIUM-sized IIAB onto a Raspberry Pi 4 with 2GB.)

**Comment by holta** [comment]
http://box.usb tested successfully by @floydianslips (with a USB stick and its content inserted into) a MEDIUM-sized IIAB installed on 32-bit RaspiOS Lite on RPi 4 with 2GB.

**Pull request merged**
