### PR TITLE
Using file module instead of chmod (Fixes #326)

### LINKED ISSUE #326: debian:  [WARNING]: Consider using file module with mode rather than running chmod
Harmless warning from Ansible. Report from nightly Jenkins CI run. Please kindly close the bug if it is low priority.

==> debian: TASK [iiab-admin : edit the sudoers file--first make it editable] **************
==> debian: changed: [127.0.0.1]
==> debian:  [WARNING]: Consider using file module with mode rather than running chmod
==> debian: 
==> debian: TASK [iiab-admin : have sudo log all commands it handles] **********************
==> debian: changed: [127.0.0.1]
==> debian: 
==> debian: TASK [iiab-admin : lets wheel sudo without password] ***************************
==> debian: changed: [127.0.0.1]

### PR DESCRIPTION
**Pull request by arky**
New pull request to fix following warning. 

[WARNING]: Consider using file module with mode rather than running chmod

### CODE REVIEW

**Comment by holta** [comment]
@jvonau plz review if poss?

**Comment by holta** [comment]
Ref #326

**Comment by holta** [comment]
@arky plz confirm this is smoke-tested (and on which OS's if poss, Thanks!)

**Comment by arky** [comment]
Smoketested on in Debian VM

**Comment by holta** [comment]
@georgejhunt reminds that chmod functionality results need actual confirmation, as Ansible was doing the wrong thing in recent years (hence the need for a shell: call to chmod...)

Can someone confirm this #435 code indeeds set the correct perms after smoke-test?

**Comment by holta** [comment]
Similar: PR #352

**Comment by jvonau** [comment]
passed jenkins test
> root@ubuntu-xenial:/home/iiab-admin# ls -la /etc/sudoers
-r--r----- 1 root root 822 Oct 25 16:32 /etc/sudoers

**Comment by jvonau** [comment]
@holta  conflicts

**Pull request merged**
