### PR TITLE
nginx requires trailing slash [for Kolibri URL] to function properly

### PR DESCRIPTION
**Pull request by jvonau**
### Fixes Bug
/kolibri not working and looping login

### CODE REVIEW

**Comment by holta** [comment]
As confirmed on 181-rpi4-1g-u20srv-2337-BIG-0422 = 10.8.0.22

**Comment by holta** [comment]
@tim-moody @ivanistheone PR #2316 caused a regression 3 weeks ago[*] causing http://box/kolibri to show:

> Not Found
The requested resource was not found on this server.

So I'd like to apply this emergency patch now, but let us know if further adjustments are necessary!

[*] arising from https://github.com/learningequality/kolibri-exercise-perseus-plugin/issues/213#issuecomment-604748222

**Comment by holta** [comment]
Question for @benjaoming: does this NGINX trailing slash issue relate to #1532 (Kolibri login looping) in any way...or is they entirely unrelated ?

**Comment by benjaoming** [comment]
> Question for @benjaoming: does this NGINX trailing slash issue relate to #1532 (Kolibri login looping) in any way...or is they entirely unrelated ?

I would LOVE to set up IIAB and try to repro, but I don't have the time :/ So I can only answer with a guess: I don't think so. Django etc. handles trailing slashes very gracefully and this is normally not the reason for a circular redirect.

**Pull request merged**
