### PR TITLE
aarch64 ubuntu on top of Jerry's ap0

### PR DESCRIPTION
**Pull request by georgejhunt**
Got a clean install on top of http://cdimage.ubuntu.com/ubuntu-server/daily-preinstalled/current/focal-preinstalled-server-arm64+raspi.img.xz

This replaces #2290

### CODE REVIEW

**Comment by georgejhunt** [comment]
But on further investigation, wifi beacon is not visible -- https://paste.debian.net/1137931

**Comment by holta** [comment]
I've annotated this as an IIAB 7.2 ticket given its branch name (pre7.2).

**Comment by holta** [comment]
Update from today's http://minutes.iiab.io call:

Compare this branch to @jvonau PR #2266 and branch https://github.com/jvonau/iiab/tree/IIAB-test

**Comment by georgejhunt** [comment]
replaced by #2337

**Pull request closed without merging**
