### PR TITLE
Initialize vars more meaningfully, for #2669 and #2670, thx to ansible-base 2.10.5's more strict checking [roles/network/defaults/main.yml]

### PR DESCRIPTION
**Pull request by holta**
Possible emergency fix, given ansible-base 2.10.5's changed behavior.

See ongoing discussion at PR #2670.  See also #2669 and PR #2671.

### CODE REVIEW

**Comment by holta** [comment]
@jvonau this was Smoke-Tested successfully on VM 193-deb10-BIG-0128 = 10.8.0.46

I've used your original lingo ("unset") for now.

Please review this PR if you have time?

**Comment by jvonau** [comment]
Is it so hard to change a single variable (prior_gw_device) instead of this mass change? I have this suspicion that removing " " from around variables changes them from strings to booleans or perhaps being seen as **None** in the case of where **none** was used, VM's with a single network interface are useless to validate network code, doesn't exercise the full scope of the code. You have been warned.

**Comment by holta** [comment]
> I have this suspicion that removing " " from around variables changes them from strings to booleans

As documented at https://github.com/iiab/iiab/blob/master/roles/0-init/tasks/validate_vars.yml#L19-L27 an Ansible var will be type "bool" if-and-only-if you set it to one of these ~18 values: (without using quotation marks, or vertical bar symbol!)

### yes|Yes|YES|no|No|NO
### |true|True|TRUE|false|False|FALSE
### |on|On|ON|off|Off|OFF

> or perhaps being seen as None in the case of where none was used

Not a risk.  The following 2 snippets are identical: (both create an Ansible string variable, i.e. of type "AnsibleUnicode")

```
myvar: none
```

```
myvar: "none"
```

**Comment by jvonau** [comment]
@chjohn22

Personally given that the above test was preformed on Ubuntu and you are on RaspOS as the main author of the network code I would suggest that you try:

`cd /opt/iiab/iiab`
`sudo git checkout -b testing ` Creates new branch to keep change apart from the main code.
Now edit (must have sudo access or be root) roles/network/defaults/main.yml changing 
prior_gw_device: ""
to 
prior_gw_device: "not-found"
save the file
Check to see if the main install was completed
`sudo cat /etc/iiab/iiab.env` looking for what is present in the STAGE= variable
If STAGE= is less than 9 complete the install with `sudo ./iiab-install` otherwise use `sudo ./iiab-network` to configure the network.

Warning, there may be other errors that might appear with this new version of ansible and I would rather deal with any errors individually rather than risk upsetting the whole apple cart.

@holta 

Do as you wish, you asked, I provided feedback.

**Comment by holta** [comment]
FYI this PR was also Smoke-Tested on RaspiOS Lite on RPi 4.

Thanks @chjohn22 if you can test any other environments as @jvonau has outlined above.

**Comment by chjohn22** [comment]
@jvonau I only did run `sudo iiab` two hours ago and the install finished successfully.  I did not have to do anything else.

**Comment by holta** [comment]
FYI here's an easy way to display the type of any Ansible variable: (in general)

```
- debug:
    msg: "myvar has type: {{ myvar | type_debug }}"
```

The output should always be...one of these 8 things:

1. bool
2. int
3. float
4. AnsibleUnicode [which means string]
5. list
6. dict
7. NoneType [if `myvar` doesn't yet have a type, e.g. `myvar:` was declared with no value]
8. AnsibleUndefined [if variable `myvar` has not yet been declared]

IIAB might in future use the above values for code safety.

Even snappier, one can test the type of a variable using these 4-5 (formerly 7-8) tests along the lines of `when: myvar is not string` and `when: myvar is number` etc:

1. <strike>is boolean</strike> (no longer supported by ansible-base 2.10.5)
2. <strike>is integer</strike> (no longer supported by ansible-base 2.10.5)
3. <strike>is float</strike> (no longer supported by ansible-base 2.10.5)
4. is number [int or float]
5. is string
6. is sequence [dict or list or string]
7. is mapping [dict or string]
8. is iterable [dict or list or string, apparently identical to `is sequence` above]

More details @ https://jon.sprig.gs/blog/post/1801 and https://jon.sprig.gs/blog/post/tag/ansible

**Comment by jvonau** [comment]
> @jvonau I only did run `sudo iiab` two hours ago and the install finished successfully. I did not have to do anything else.

I doubt your network is fully configured, the noted error https://github.com/iiab/iiab/issues/2669#issuecomment-769681513 would not be exposed while using 'sudo iiab' a second time if the STAGE= counter is already at 9, the network configuration would be skipped, that is the reason for using ./iiab-network as I noted above.

**Pull request merged**
