### PR TITLE
Begin transition to Ansible 2.10 (now that ansible-base 2.10.1 is released & appears solid!)

### PR DESCRIPTION
**Pull request by holta**
Building on and evolving from:

- #2479 'Validate Ansible 2.10 expected 2020-08-13 [with simplified auto-installation of "Collections" ETA 2020-09-22 ?]'
- #2481 'Ansible promised not to change things, but this seems like a big one: file permissions like 666 become 600, in new Ansible 2.10.0 (and in Ansible 2.9.12 too?)'
- PR #2512 'Revamp ansible for the future'

### CODE REVIEW

**Comment by holta** [comment]
Tested on Ubuntu Server 20.04.1 VM.

**Comment by holta** [comment]
Further smoke-tested on latest:

- 32-bit RaspiOS (with desktop) on RPi 4
- 64-bit RaspiOS (headless) on RPi 4
- 64-bit Ubuntu (20.04.1) on RPi 4
- Debian 10.5 VM

**Comment by holta** [comment]
Also smoke-tested on Ubuntu Desktop 20.04.1 VM, with PR #2519 "2515 fix [for non-WiFi situations]"

**Comment by jvonau** [comment]
#2532

**Pull request merged**
