### PR TITLE
Introduce new VPN approach (roles/tailscale) with commands iiab-vpn and iiab-vpn-off in /usr/bin

### PR DESCRIPTION
**Pull request by holta**
This PR:

- Deprecates @georgejhunt's roles/openvpn which not only helped countless people over many years — but also greatly helped inspire this new approach.

- Introduces a new approach that greatly strengthens IIAB's support/community VPN security, using WireGuard, Tailscale and Headscale.

Instructions:

- Anybody who runs `/usr/bin/iiab-vpn` == `/usr/bin/iiab-support` will need a key going forward, as is explained when you run those commands (please follow the [instructions](https://github.com/iiab/iiab/blob/762fed228a65126acbea66b2dd376f3d8df2320d/roles/tailscale/templates/iiab-vpn#L25), which boil down to emailing for a key).

- http://FAQ.IIAB.IO ➡️ "35 How can I remotely manage my Internet-in-a-Box?" ➡️ Item 3. [was] revised and clarified accordingly, to improve the overall experience for newbies and newcomers especially!

- TIPS: https://github.com/iiab/iiab/blob/d3d0b9767c29fc3108dc6510993a20532bd9be0e/roles/tailscale/templates/iiab-vpn#L46-L58

Testing:

- Finally, this PR was tested on Ubuntu 24.10 and Debian 12.

- Additional testing on Raspberry Pi OS 12 (very much like Debian 12 above) and Mint 22 should follow after merging (thanks all who are willing to kick the tires, please email holt@unleashkids.org if you're interested and can help!)

### CODE REVIEW

**Comment by holta** [comment]
> * http://FAQ.IIAB.IO [was just] revised and clarified accordingly, to improve the overall experience for newbies and newcomers especially!

New Documentation:

- https://wiki.iiab.io/go/FAQ > "35 How can I remotely manage my Internet-in-a-Box?" > Item 3.
- https://wiki.iiab.io/go/FAQ#How_can_I_remotely_manage_my_Internet-in-a-Box%3F > Item 3.
- https://wiki.iiab.io/index.php?title=FAQ&diff=817&oldid=816 > Item 3.

(If anything's too ambiguous LMK, so docs / instructions can be cleaned up!)

**Comment by holta** [comment]
Merging in coming minutes, so broader community testing can now grow: _thanks all who can help._ :pray:

**Comment by holta** [comment]
> Merging in coming minutes, so broader community testing can now grow: thanks all who can help. 🙏

I'm sure there will be a few adjustments needed over coming weeks ~ as we get to know this new VPN approach !

e.g. if needed, I can later implement [ACLs](https://headscale.net/acls/) within the "internal" VPN pool (100.64.0.0/10 IP address range, In [CIDR notation](https://en.wikipedia.org/wiki/Classless_Inter-Domain_Routing)).  _Not that we really need all 4,194,303 = 2²² - 1 of these IP addresses 😉 but still let's be careful if/as use of this new approach grows!_

In any case: we now have many more usability + scalability options, especially when compared to the "maximum 63 IP addresses" offered by our earlier xscenet.net OpenVPN implementation! 😆

**Comment by avni** [comment]
Tried out Tailscale on 2 VMs (multipass, Ubuntu 24.04 LTS) from a macOS laptop. Works smoothly and was straightforward to install! I also installed Tailscale directly on my MacOS laptop and connected to the VPN server easily. 🎉 🙏

**Comment by holta** [comment]
Really great news:

3-5 people / groups around the world are now trying it out, so far so good!

**Pull request merged**
