### PR TITLE
Experiment with FreePBX 16 Beta, as required by PHP 7.4

### PR DESCRIPTION
**Pull request by holta**
Refs:

- PR #1761
- PR #2489
- PR #2896
- PR #2897
  - https://www.freepbx.org/freepbx-16-beta-is-here/
  - https://wiki.freepbx.org/pages/viewpage.action?spaceKey=FOP&title=Installing+FreePBX+16+on+Debian+10.9
- PR #2898

### CODE REVIEW

**Comment by holta** [comment]
Almost worked!  Error on Ubuntu Server 20.04 was:

```
Finished setting permissions
changed: [127.0.0.1]

TASK [pbx : FreePBX - Patch FreePBX source - disable get_magic_quotes_gpc()] *******************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: PatchError: 1 out of 1 hunk FAILED
fatal: [127.0.0.1]: FAILED! => {"changed": false, "msg": "1 out of 1 hunk FAILED\n"}

PLAY RECAP *************************************************************************************************************************************************************
127.0.0.1                  : ok=310  changed=171  unreachable=0    failed=1    skipped=63   rescued=0    ignored=2
```

Per https://github.com/iiab/iiab/blob/master/roles/pbx/tasks/freepbx.yml#L116-L119

**Comment by holta** [comment]
@lemueldsouza can you review this PR, to see if we can merge it or similar?

Ideally with a fresh install on any PHP 7.4 machine like Ubuntu Server 21.04 on RPi or VM?

And/or just by playing with my Ubuntu Server 20.04 install at http://10.8.0.6:83/freepbx to see if it's genuinely working?

(Thanks Much if you have time!)

**Comment by holta** [comment]
This PR's also being install onto Debian 11 (non-desktop) VM 10.8.0.42 = 194-deb11-srv-2885-2900-2899 to verify...that it's good enough or close?!

With these 2 PR's for good measure:

- PR #2885 
- PR #2900

**Comment by holta** [comment]
This PR was successfully installed on Ubuntu Desktop 20.04 and Desbian 11 (no desktop).

In both cases, http://box:83/freepbx appears in browser, but had a RED warning in the top-right prior to the standard IIAB post-install reboot:

image

After reboot, the RED warning went away, so all looks promising so far!

General Tips recommended by @lemueldsouza:

1) Run `asterisk -rvvv` to verify Asterisk is indeed running.  If it's not, run `systemctl restart asterisk` &mdash; and it might also be necessary to run `systemctl restart freepbx`

2) In files `/etc/asterisk/cdr.conf` and `/etc/asterisk/cel.conf`, this line sometimes needed to be added: (possibly this manual step is no longer necessary with Asterisk 18.x now!)

   ```
   radiuscfg => /etc/radcli/radiusclient.conf
   ```

   - In any case, make 100% sure the file `/etc/radcli/radiusclient.conf` is non-empty.  You can end up with a zero-length file here, if IIAB's roles/pbx install was interrupted (it should be about 2-to-3 kBytes initially).  Probably best to start over with a clean OS in such situations!

   - Also make sure any older lines including `radiuscfg => /usr/local/etc/radiusclient-ng/radiusclient.conf` are commented out within `cdr.conf` and `cel.conf`

3) Finally, it might occasionally be necessary to run `fwconsole chown` to fix FreePBX's console ownership/permissions?  e.g. if IIAB's roles/pbx install was interrupted or such.

**Comment by holta** [comment]
Note To Selves!

Let's gather the best such tips (thanks to @lemueldsouza just above!) and write them into the new [roles/pbx/README.md](https://github.com/holta/iiab/tree/pbx-readme/roles/pbx#pbx-readme)

- https://github.com/iiab/iiab/pull/2898

**Comment by holta** [comment]
FYI this PR #2899 is also being installed with PR #2885 onto an RPi 4 with Ubuntu Server 21.04 (10.8.0.34) to see if this new PHP 7.4 approach to roles/pbx (Asterisk 18 + FreePBX 16) also works on **_arm64_** Raspberry Pis &mdash; i.e. not just PC's = amd64 / x86_64 !

_@lemueldsouza may be able to confirm that within the coming hour or so..._

**Comment by holta** [comment]
Huge thanks to @lemueldsouza who helped a lot with testing overnight:

- Ubuntu Server 21.04 on RPi 4 (I tested this one with Linphone on Android, to make actual SIP extension test calls)
- Ubuntu Desktop 20.04 VM
- Debian 11 VM

So that wraps up Phase 1: this PR will now be merged so we have a new FreePBX baseline with PHP 7,4 bringing us into the future.  Together we've decided now is the time to make the jump from PHP 7.3 to 7.4, even if yes this means desupporting FreePBX 15 (i.e. RaspiOS 10 Buster's PHP 7.3) during the final days of its existence, right before RaspiOS 11 Bullseye brings PHP 7.4 in not so many days &mdash we need to be prepared so the time for cutover is now.

Conclusion: yes FreePBX 16 is still in Beta (7 weeks later) but it seems to work really well, including on Ubuntu Server 20.04 on RPi 4.

NOTE: when logging into http://box:83/freepbx it shows an "fwconsole reload" error &mdash; so he ran these 2 things at the command-line to fix it:

```
sudo fwconsole chown
sudo fwconsole reload
```

He will document that into roles/pbx/README.rst as PR #2898 evolves into something much better &mdash; over coming days if not hours!  We might possibly even include Linphone screenshots into the README if there's time, e.g. things like:

image

**Comment by jvonau** [comment]
> This PR was successfully installed on Ubuntu Desktop 20.04 and Desbian 11 (no desktop).
> 
> In both cases, http://box;83/freepbx appears in browser, but had a RED warning in the top-right prior to the standard IIAB post-install reboot:
> 

So Asterisk is not running or cannot connect to the backend DB

> After reboot, the RED warning went away, so all looks promising so far!
> 
> General Tips recommended by @lemueldsouza:
> 
>     1. Run `asterisk -rvvv` to verify Asterisk is indeed running.  If it's not, run `systemctl restart asterisk` — and it might also be necessary to run `systemctl restart freepbx`
> 

In the older version of freepbx the starting of Asterisk was handled by `fwconsole` and Asterisk is specially disabled during the [install](https://github.com/iiab/iiab/blob/master/roles/pbx/tasks/freepbx.yml#L45-L50)  that no longer the case? 

>     2. In files `/etc/asterisk/cdr.conf` and `/etc/asterisk/cel.conf`, this line sometimes needed to be added: (possibly this manual step is no longer necessary with Asterisk 18.x now!)
>        ```
>        radiuscfg => /etc/radcli/radiusclient.conf
>        ```
>        * In any case, make 100% sure the file `/etc/radcli/radiusclient.conf` is non-empty.  You can end up with a zero-length file here, if IIAB's roles/pbx install was interrupted (it should be about 2-to-3 kBytes initially).  Probably best to start over with a clean OS in such situations!
>        * Also make sure any older lines including `radiuscfg => /usr/local/etc/radiusclient-ng/radiusclient.conf` are commented out within `cdr.conf` and `cel.conf`
> 

Best you figure out how radius is being used.
>     3. Finally, it might occasionally be necessary to run `fwconsole chown` to fix FreePBX's console ownership/permissions?  e.g. if IIAB's roles/pbx install was interrupted or such.

That was in version 15 (still is in 16?) run automatically with fwconsole start noted in https://github.com/iiab/iiab/pull/2862#issuecomment-880713148

**Pull request merged**
