### PR TITLE
Update detected_network.yml [for Docker]

### PR DESCRIPTION
**Pull request by jvonau**
Docker

### CODE REVIEW

**Comment by holta** [comment]
@m-anish & all can you review this Docker-oriented change?

Thanks!

(Not directly related to yesterday's networking tweaks @ PR #1745, #1750)

**Comment by jvonau** [comment]
Still need to deal with iptables

**Comment by holta** [comment]
> Still need to deal with iptables

Ok.  Is this likely for IIAB 7.0?

Or is this more suitable for IIAB 7.1?

**Review by m-anish — CHANGES_REQUESTED** [review]
Okay. From the code it seems we're trying to exclude interfaces here which we're not interested in. 
While we're at it, can we exclude:

* "br-*" because these are bridges azuracast/docker creates
* docker0 because this is the default docker bridge

**Comment by m-anish** [comment]
Try this patch on.

[0001-Add-br-and-docker-to-network-interface-list-to-exclu.patch.zip](https://github.com/iiab/iiab/files/3317436/0001-Add-br-and-docker-to-network-interface-list-to-exclu.patch.zip)

**Comment by m-anish** [comment]
Superseded by #1765

**Pull request merged**
