### PR TITLE
dhcpcd.conf.j2: denyinterfaces IF {{ iiab_wireless_lan_iface }} defined — for Raspberry Pi OS on PC/Mac

### PR DESCRIPTION
**Pull request by holta**
@jvonau can you review this PR?

To resolve Part 2 of #2148 for @deltacloud9.

(i.e. we're hoping this might permit IIAB to install onto Raspberry Pi OS on PC/Mac)

### CODE REVIEW

**Comment by holta** [comment]
@deltacloud9 you can _install IIAB with this PR included_ by running: (on a fresh OS)

```
curl d.iiab.io/install.txt | sudo bash -s 2870
```

Can you confirm that this...hopefully...allows IIAB to install onto "Raspberry Pi Desktop" on a PC/VM !?

**Comment by jvonau** [comment]
looks fine

**Comment by mattsap34** [comment]
Rebuilt the Rasberry OS VM > Ran all updates > Rebooted

Installed iiab with standard one line installer > Rebooted

Forbidden 403 error message again.

Here is the diagnostics: http://sprunge.us/jVPYMK?en

**Comment by mattsap34** [comment]
Testing URLs, here are the results 

http://box - Forbidden 403 Error
http://box.lan - 404 Not Found Error
http://127.0.0.1 - Forbidden 403 Error
http://172.18.96.1 - This one spins endlessly from within the VM then says site cannot be reached
http://192.168.122.173 - Site cannot be reached error

**Comment by holta** [comment]
> Installed iiab with standard one line installer > Rebooted
> 
> Forbidden 403 error message again.
> 
> Here is the diagnostics: http://sprunge.us/jVPYMK?en

@deltacloud9 the IIAB install did not complete.  Keep a close eye on that central question (whether the IIAB 1-line installer completes or not!)  The screen that matters, contains this sentence on top:

```
INTERNET-IN-A-BOX (IIAB) SOFTWARE INSTALL IS COMPLETE
```

@jvonau issue is below:

> 1085 2021-07-20 19:46:00,616 p=3613 u=root n=ansible | TASK [network : Clone wifi if needed] ****************************************************************************************
1086 2021-07-20 19:46:01,316 p=3613 u=root n=ansible | fatal: [127.0.0.1]: FAILED! => {"changed": false, "msg": "Could not find the requested service clone-wifi: host"}

**Comment by mattsap34** [comment]
> > Installed iiab with standard one line installer > Rebooted
> > Forbidden 403 error message again.
> > Here is the diagnostics: http://sprunge.us/jVPYMK?en
> 
> @deltacloud9 the IIAB install did not complete. Keep a close eye on that central question (whether the IIAB 1-line installer completes or not!) The screen that matters, contains this sentence on top:
> @holta Ahh I see now, huge apologies here. The installer appears to run through but yes always seems shorter than installing on a standard Rasberry Pi.
> ```
> INTERNET-IN-A-BOX (IIAB) SOFTWARE INSTALL IS COMPLETE
> ```
> 
> @jvonau issue is below:
> 
> > 1085 2021-07-20 19:46:00,616 p=3613 u=root n=ansible | TASK [network : Clone wifi if needed] ****************************************************************************************
> > 1086 2021-07-20 19:46:01,316 p=3613 u=root n=ansible | fatal: [127.0.0.1]: FAILED! => {"changed": false, "msg": "Could not find the requested service clone-wifi: host"}
@jvonau  Interesting. Appears to not be able to connect via the "wifi" connection. What is strange though is that internet seems to be flowing fine via this VM. I am able to go to websites via the web browser and such. Wondering why it's not making a connection to iiab?

**Comment by holta** [comment]
> Testing URLs, here are the results
> 
> http://box - Forbidden 403 Error
> http://box.lan - 404 Not Found Error
> http://127.0.0.1 - Forbidden 403 Error
> http://172.18.96.1 - This one spins endlessly from within the VM then says site cannot be reached
> http://192.168.122.173 - Site cannot be reached error

Understood.

Just a CLARIFICATION that the final test for this VM would be:
http://192.168.122.124

Unlike the prior VM (from #2749) which was:
http://192.168.122.173

**Comment by mattsap34** [comment]
> > Testing URLs, here are the results
> > http://box - Forbidden 403 Error
> > http://box.lan - 404 Not Found Error
> > http://127.0.0.1 - Forbidden 403 Error
> > http://172.18.96.1 - This one spins endlessly from within the VM then says site cannot be reached
> > http://192.168.122.173 - Site cannot be reached error
> 
> Understood.
> 
> Just a CLARIFICATION that the final test for this VM would be:
> http://192.168.122.124
> @holta Results: Forbidden 403 Error

This has to be a network issue with the VM.
> Unlike the prior VM (from #2749) which was:
> http://192.168.122.173

**Comment by jvonau** [comment]
@holta (why you insist on sending new users down unsupported rabbit holes is beyond me.) Again it's the long standing design decision to equate raspbian with wifi hardware being present so change: 
```
- name: Clone wifi if needed
  systemd:
    name: clone-wifi
    state: started
```
 adding 
```
 when: discovered_wireless_iface != "none"
``` 
There may be others lurking around the corner, but it's almost through the raspbian specific code in rpi_debian.yml.  
Without the networking being full completed and the firewall active you should be able to ping 192.168.122.124.

**Pull request merged**
